language: python
dist: trusty
sudo: required
env:
  - NO_GCE_CHECK=True
node_js:
  - node
python:
  - 2.7
install:
  - pip install flask rstr
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.3

  - nvm install node
  - nvm use node
script:
  - python run_tests.py pubsub:v1 tasks:v1

