language: python
python:
  - 2.7
dist: trusty
sudo: required
install:
  - pip3 install flask gunicorn six
  # Install dotnet.
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.3
  # Install the latest Node.js runtime.
  - nvm install node
  - nvm use node
script:
  - ./run_tests.py discoveries/compute.v1.json

