{
  "baseUrl": "https://admin.googleapis.com/",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "version": "directory_v1",
  "packagePath": "admin",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admin.directory.domain.readonly": {
          "description": "View domains related to your customers"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud Platform data"
        },
        "https://www.googleapis.com/auth/admin.directory.group.member": {
          "description": "View and manage group subscriptions on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly": {
          "description": "View organization units on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly": {
          "description": "View user aliases on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.customer": {
          "description": "View and manage customer related information"
        },
        "https://www.googleapis.com/auth/admin.directory.group.member.readonly": {
          "description": "View group subscriptions on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.group.readonly": {
          "description": "View groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.device.mobile": {
          "description": "View and manage your mobile devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.chrome.printers": {
          "description": "See, add, edit, and permanently delete the printers that your organization can use with Chrome"
        },
        "https://www.googleapis.com/auth/admin.directory.user.readonly": {
          "description": "See info about users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly": {
          "description": "View your Chrome OS devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly": {
          "description": "View your mobile devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.device.mobile.action": {
          "description": "Manage your mobile devices by performing administrative tasks"
        },
        "https://www.googleapis.com/auth/admin.directory.user.alias": {
          "description": "View and manage user aliases on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.userschema": {
          "description": "View and manage the provisioning of user schemas on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.rolemanagement": {
          "description": "Manage delegated admin roles for your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.domain": {
          "description": "View and manage the provisioning of domains for your customers"
        },
        "https://www.googleapis.com/auth/admin.directory.user.security": {
          "description": "Manage data access permissions for users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.resource.calendar": {
          "description": "View and manage the provisioning of calendar resources on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.device.chromeos": {
          "description": "View and manage your Chrome OS devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.customer.readonly": {
          "description": "View customer related information"
        },
        "https://www.googleapis.com/auth/admin.directory.orgunit": {
          "description": "View and manage organization units on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly": {
          "description": "View delegated admin roles for your domain"
        },
        "https://www.googleapis.com/auth/admin.chrome.printers.readonly": {
          "description": "See the printers that your organization can use with Chrome"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.userschema.readonly": {
          "description": "View user schemas on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly": {
          "description": "View calendar resources on your domain"
        }
      }
    }
  },
  "name": "admin",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "protocol": "rest",
  "documentationLink": "http://developers.google.com/admin-sdk/",
  "servicePath": "",
  "basePath": "",
  "batchPath": "batch",
  "id": "admin:directory_v1",
  "resources": {
    "customers": {
      "resources": {
        "chrome": {
          "resources": {
            "printers": {
              "methods": {
                "get": {
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers/{printersId}",
                  "id": "admin.customers.chrome.printers.get",
                  "httpMethod": "GET",
                  "path": "admin/directory/v1/{+name}",
                  "description": "Returns a `Printer` resource (printer's config).",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers",
                    "https://www.googleapis.com/auth/admin.chrome.printers.readonly"
                  ]
                },
                "create": {
                  "id": "admin.customers.chrome.printers.create",
                  "description": "Creates a printer under given Organization Unit.",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers"
                  ],
                  "path": "admin/directory/v1/{+parent}/chrome/printers",
                  "httpMethod": "POST",
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers"
                },
                "listPrinterModels": {
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers",
                    "https://www.googleapis.com/auth/admin.chrome.printers.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists the supported printer models.",
                  "path": "admin/directory/v1/{+parent}/chrome/printers:listPrinterModels",
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers:listPrinterModels",
                  "id": "admin.customers.chrome.printers.listPrinterModels"
                },
                "delete": {
                  "id": "admin.customers.chrome.printers.delete",
                  "path": "admin/directory/v1/{+name}",
                  "description": "Deletes a `Printer`.",
                  "httpMethod": "DELETE",
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers/{printersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers"
                  ]
                },
                "batchCreatePrinters": {
                  "description": "Creates printers under given Organization Unit.",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers"
                  ],
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers:batchCreatePrinters",
                  "path": "admin/directory/v1/{+parent}/chrome/printers:batchCreatePrinters",
                  "httpMethod": "POST",
                  "id": "admin.customers.chrome.printers.batchCreatePrinters"
                },
                "batchDeletePrinters": {
                  "path": "admin/directory/v1/{+parent}/chrome/printers:batchDeletePrinters",
                  "id": "admin.customers.chrome.printers.batchDeletePrinters",
                  "description": "Deletes printers in batch.",
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers:batchDeletePrinters",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers"
                  ]
                },
                "patch": {
                  "description": "Updates a `Printer` resource.",
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers/{printersId}",
                  "path": "admin/directory/v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers"
                  ],
                  "id": "admin.customers.chrome.printers.patch",
                  "httpMethod": "PATCH"
                },
                "list": {
                  "flatPath": "admin/directory/v1/customers/{customersId}/chrome/printers",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.chrome.printers",
                    "https://www.googleapis.com/auth/admin.chrome.printers.readonly"
                  ],
                  "description": "List printers configs.",
                  "httpMethod": "GET",
                  "id": "admin.customers.chrome.printers.list",
                  "path": "admin/directory/v1/{+parent}/chrome/printers"
                }
              }
            }
          }
        }
      },
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.customer",
            "https://www.googleapis.com/auth/admin.directory.customer.readonly"
          ],
          "id": "directory.customers.get",
          "description": "Retrieves a customer.",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/customers/{customerKey}",
          "path": "admin/directory/v1/customers/{customerKey}"
        },
        "patch": {
          "flatPath": "admin/directory/v1/customers/{customerKey}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.customer"
          ],
          "id": "directory.customers.patch",
          "description": "Patch Customers via Apiary Patch Orchestration",
          "httpMethod": "PATCH",
          "path": "admin/directory/v1/customers/{customerKey}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.customer"
          ],
          "httpMethod": "PUT",
          "id": "directory.customers.update",
          "path": "admin/directory/v1/customers/{customerKey}",
          "flatPath": "admin/directory/v1/customers/{customerKey}",
          "description": "Updates a customer."
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.alias",
            "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
            "https://www.googleapis.com/auth/admin.directory.user.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "admin/directory_v1/channels/stop",
          "path": "admin/directory_v1/channels/stop",
          "httpMethod": "POST",
          "description": "Stop watching resources through this channel.",
          "id": "admin.channels.stop"
        }
      }
    },
    "groups": {
      "resources": {
        "aliases": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.group",
                "https://www.googleapis.com/auth/admin.directory.group.readonly"
              ],
              "flatPath": "admin/directory/v1/groups/{groupKey}/aliases",
              "description": "Lists all aliases for a group.",
              "id": "directory.groups.aliases.list",
              "path": "admin/directory/v1/groups/{groupKey}/aliases"
            },
            "insert": {
              "flatPath": "admin/directory/v1/groups/{groupKey}/aliases",
              "path": "admin/directory/v1/groups/{groupKey}/aliases",
              "description": "Adds an alias for the group.",
              "httpMethod": "POST",
              "id": "directory.groups.aliases.insert",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.group"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.group"
              ],
              "httpMethod": "DELETE",
              "id": "directory.groups.aliases.delete",
              "description": "Removes an alias.",
              "path": "admin/directory/v1/groups/{groupKey}/aliases/{alias}",
              "flatPath": "admin/directory/v1/groups/{groupKey}/aliases/{alias}"
            }
          }
        }
      },
      "methods": {
        "delete": {
          "id": "directory.groups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "description": "Deletes a group.",
          "httpMethod": "DELETE",
          "path": "admin/directory/v1/groups/{groupKey}",
          "flatPath": "admin/directory/v1/groups/{groupKey}"
        },
        "patch": {
          "path": "admin/directory/v1/groups/{groupKey}",
          "id": "directory.groups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "flatPath": "admin/directory/v1/groups/{groupKey}",
          "httpMethod": "PATCH",
          "description": "Updates a group's properties. This method supports [patch semantics](/admin-sdk/directory/v1/guides/performance#patch)."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "httpMethod": "POST",
          "path": "admin/directory/v1/groups",
          "flatPath": "admin/directory/v1/groups",
          "description": "Creates a group.",
          "id": "directory.groups.insert"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "flatPath": "admin/directory/v1/groups",
          "description": "Retrieve all groups of a domain or of a user given a userKey (paginated)",
          "path": "admin/directory/v1/groups",
          "id": "directory.groups.list"
        },
        "get": {
          "id": "directory.groups.get",
          "flatPath": "admin/directory/v1/groups/{groupKey}",
          "description": "Retrieves a group's properties.",
          "path": "admin/directory/v1/groups/{groupKey}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "id": "directory.groups.update",
          "flatPath": "admin/directory/v1/groups/{groupKey}",
          "path": "admin/directory/v1/groups/{groupKey}",
          "description": "Updates a group's properties.",
          "httpMethod": "PUT"
        }
      }
    },
    "members": {
      "methods": {
        "hasMember": {
          "httpMethod": "GET",
          "description": "Checks whether the given user is a member of the group. Membership can be direct or nested.",
          "flatPath": "admin/directory/v1/groups/{groupKey}/hasMember/{memberKey}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member",
            "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "path": "admin/directory/v1/groups/{groupKey}/hasMember/{memberKey}",
          "id": "directory.members.hasMember"
        },
        "insert": {
          "path": "admin/directory/v1/groups/{groupKey}/members",
          "description": "Adds a user to the specified group.",
          "id": "directory.members.insert",
          "flatPath": "admin/directory/v1/groups/{groupKey}/members",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates the membership properties of a user in the specified group. This method supports [patch semantics](/admin-sdk/directory/v1/guides/performance#patch).",
          "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "flatPath": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "id": "directory.members.patch",
          "httpMethod": "PATCH"
        },
        "update": {
          "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "id": "directory.members.update",
          "httpMethod": "PUT",
          "description": "Updates the membership of a user in the specified group.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "flatPath": "admin/directory/v1/groups/{groupKey}/members/{memberKey}"
        },
        "list": {
          "description": "Retrieves a paginated list of all members in a group.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member",
            "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "flatPath": "admin/directory/v1/groups/{groupKey}/members",
          "path": "admin/directory/v1/groups/{groupKey}/members",
          "id": "directory.members.list"
        },
        "get": {
          "flatPath": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "httpMethod": "GET",
          "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "id": "directory.members.get",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member",
            "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "description": "Retrieves a group member's properties."
        },
        "delete": {
          "id": "directory.members.delete",
          "path": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "description": "Removes a member from a group.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "flatPath": "admin/directory/v1/groups/{groupKey}/members/{memberKey}",
          "httpMethod": "DELETE"
        }
      }
    },
    "resources": {
      "resources": {
        "buildings": {
          "methods": {
            "insert": {
              "flatPath": "admin/directory/v1/customer/{customer}/resources/buildings",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "httpMethod": "POST",
              "id": "directory.resources.buildings.insert",
              "path": "admin/directory/v1/customer/{customer}/resources/buildings",
              "description": "Inserts a building."
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "flatPath": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "description": "Updates a building.",
              "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "httpMethod": "PUT",
              "id": "directory.resources.buildings.update"
            },
            "list": {
              "description": "Retrieves a list of buildings for an account.",
              "path": "admin/directory/v1/customer/{customer}/resources/buildings",
              "id": "directory.resources.buildings.list",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/buildings"
            },
            "delete": {
              "description": "Deletes a building.",
              "httpMethod": "DELETE",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "id": "directory.resources.buildings.delete",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ]
            },
            "get": {
              "description": "Retrieves a building.",
              "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "id": "directory.resources.buildings.get",
              "httpMethod": "GET",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}"
            },
            "patch": {
              "description": "Patches a building via Apiary Patch Orchestration.",
              "path": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "id": "directory.resources.buildings.patch",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "httpMethod": "PATCH"
            }
          }
        },
        "features": {
          "methods": {
            "list": {
              "path": "admin/directory/v1/customer/{customer}/resources/features",
              "description": "Retrieves a list of features for an account.",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "id": "directory.resources.features.list",
              "httpMethod": "GET"
            },
            "rename": {
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features/{oldName}/rename",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "path": "admin/directory/v1/customer/{customer}/resources/features/{oldName}/rename",
              "description": "Renames a feature.",
              "httpMethod": "POST",
              "id": "directory.resources.features.rename"
            },
            "patch": {
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "description": "Patches a feature via Apiary Patch Orchestration.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "httpMethod": "PATCH",
              "id": "directory.resources.features.patch"
            },
            "insert": {
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features",
              "id": "directory.resources.features.insert",
              "httpMethod": "POST",
              "description": "Inserts a feature.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "path": "admin/directory/v1/customer/{customer}/resources/features"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "description": "Retrieves a feature.",
              "id": "directory.resources.features.get",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}"
            },
            "delete": {
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "description": "Deletes a feature.",
              "httpMethod": "DELETE",
              "id": "directory.resources.features.delete",
              "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ]
            },
            "update": {
              "httpMethod": "PUT",
              "id": "directory.resources.features.update",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "description": "Updates a feature.",
              "path": "admin/directory/v1/customer/{customer}/resources/features/{featureKey}",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ]
            }
          }
        },
        "calendars": {
          "methods": {
            "update": {
              "id": "directory.resources.calendars.update",
              "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "description": "Updates a calendar resource. This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "flatPath": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "PUT"
            },
            "insert": {
              "httpMethod": "POST",
              "description": "Inserts a calendar resource.",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/calendars",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "path": "admin/directory/v1/customer/{customer}/resources/calendars",
              "id": "directory.resources.calendars.insert"
            },
            "get": {
              "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "GET",
              "description": "Retrieves a calendar resource.",
              "id": "directory.resources.calendars.get",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ]
            },
            "patch": {
              "description": "Patches a calendar resource via Apiary Patch Orchestration.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "flatPath": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "id": "directory.resources.calendars.patch",
              "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "PATCH"
            },
            "list": {
              "httpMethod": "GET",
              "path": "admin/directory/v1/customer/{customer}/resources/calendars",
              "flatPath": "admin/directory/v1/customer/{customer}/resources/calendars",
              "id": "directory.resources.calendars.list",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "description": "Retrieves a list of calendar resources for an account."
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "flatPath": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "id": "directory.resources.calendars.delete",
              "path": "admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}",
              "description": "Deletes a calendar resource."
            }
          }
        }
      }
    },
    "customer": {
      "resources": {
        "devices": {
          "resources": {
            "chromeos": {
              "resources": {
                "commands": {
                  "methods": {
                    "get": {
                      "description": "Gets command data a specific command issued to the device.",
                      "id": "admin.customer.devices.chromeos.commands.get",
                      "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}/commands/{commandId}",
                      "httpMethod": "GET",
                      "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}/commands/{commandId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos",
                        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "issueCommand": {
                  "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}:issueCommand",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.device.chromeos"
                  ],
                  "id": "admin.customer.devices.chromeos.issueCommand",
                  "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}:issueCommand",
                  "description": "Issues a command for the device to execute."
                }
              }
            }
          }
        }
      }
    },
    "domains": {
      "methods": {
        "insert": {
          "path": "admin/directory/v1/customer/{customer}/domains",
          "description": "Inserts a domain of the customer.",
          "flatPath": "admin/directory/v1/customer/{customer}/domains",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "id": "directory.domains.insert"
        },
        "delete": {
          "id": "directory.domains.delete",
          "flatPath": "admin/directory/v1/customer/{customer}/domains/{domainName}",
          "description": "Deletes a domain of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "path": "admin/directory/v1/customer/{customer}/domains/{domainName}",
          "httpMethod": "DELETE"
        },
        "get": {
          "id": "directory.domains.get",
          "httpMethod": "GET",
          "description": "Retrieves a domain of the customer.",
          "path": "admin/directory/v1/customer/{customer}/domains/{domainName}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "flatPath": "admin/directory/v1/customer/{customer}/domains/{domainName}"
        },
        "list": {
          "id": "directory.domains.list",
          "httpMethod": "GET",
          "description": "Lists the domains of the customer.",
          "flatPath": "admin/directory/v1/customer/{customer}/domains",
          "path": "admin/directory/v1/customer/{customer}/domains",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ]
        }
      }
    },
    "chromeosdevices": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
          "id": "directory.chromeosdevices.get",
          "description": "Retrieves a Chrome OS device's properties.",
          "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos",
            "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
          ]
        },
        "update": {
          "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "id": "directory.chromeosdevices.update",
          "description": "Updates a device's updatable properties, such as `annotatedUser`, `annotatedLocation`, `notes`, `orgUnitPath`, or `annotatedAssetId`.",
          "httpMethod": "PUT"
        },
        "list": {
          "path": "admin/directory/v1/customer/{customerId}/devices/chromeos",
          "description": "Retrieves a paginated list of Chrome OS devices within an account.",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos",
          "id": "directory.chromeosdevices.list",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos",
            "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
          ]
        },
        "patch": {
          "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "description": "Updates a device's updatable properties, such as `annotatedUser`, `annotatedLocation`, `notes`, `orgUnitPath`, or `annotatedAssetId`. This method supports [patch semantics](/admin-sdk/directory/v1/guides/performance#patch).",
          "id": "directory.chromeosdevices.patch",
          "httpMethod": "PATCH"
        },
        "action": {
          "httpMethod": "POST",
          "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/{resourceId}/action",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/{resourceId}/action",
          "id": "directory.chromeosdevices.action",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "description": "Takes an action that affects a Chrome OS Device. This includes deprovisioning, disabling, and re-enabling devices. *Warning:* * Deprovisioning a device will stop device policy syncing and remove device-level printers. After a device is deprovisioned, it must be wiped before it can be re-enrolled. * Lost or stolen devices should use the disable action. * Re-enabling a disabled device will consume a device license. If you do not have sufficient licenses available when com[...]"
        },
        "moveDevicesToOu": {
          "description": "Move or insert multiple Chrome OS devices to an organizational unit. You can move up to 50 devices at once.",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/chromeos/moveDevicesToOu",
          "id": "directory.chromeosdevices.moveDevicesToOu",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "path": "admin/directory/v1/customer/{customerId}/devices/chromeos/moveDevicesToOu",
          "httpMethod": "POST"
        }
      }
    },
    "users": {
      "resources": {
        "aliases": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias"
              ],
              "description": "Removes an alias.",
              "flatPath": "admin/directory/v1/users/{userKey}/aliases/{alias}",
              "id": "directory.users.aliases.delete",
              "path": "admin/directory/v1/users/{userKey}/aliases/{alias}"
            },
            "insert": {
              "httpMethod": "POST",
              "path": "admin/directory/v1/users/{userKey}/aliases",
              "flatPath": "admin/directory/v1/users/{userKey}/aliases",
              "description": "Adds an alias.",
              "id": "directory.users.aliases.insert",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias"
              ]
            },
            "list": {
              "path": "admin/directory/v1/users/{userKey}/aliases",
              "id": "directory.users.aliases.list",
              "httpMethod": "GET",
              "description": "Lists all aliases for a user.",
              "flatPath": "admin/directory/v1/users/{userKey}/aliases",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias",
                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                "https://www.googleapis.com/auth/admin.directory.user.readonly"
              ]
            },
            "watch": {
              "httpMethod": "POST",
              "description": "Watch for changes in users list.",
              "path": "admin/directory/v1/users/{userKey}/aliases/watch",
              "flatPath": "admin/directory/v1/users/{userKey}/aliases/watch",
              "id": "directory.users.aliases.watch",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias",
                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                "https://www.googleapis.com/auth/admin.directory.user.readonly"
              ]
            }
          }
        },
        "photos": {
          "methods": {
            "patch": {
              "description": "Adds a photo for the user. This method supports [patch semantics](/admin-sdk/directory/v1/guides/performance#patch).",
              "flatPath": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user"
              ],
              "id": "directory.users.photos.patch",
              "httpMethod": "PATCH",
              "path": "admin/directory/v1/users/{userKey}/photos/thumbnail"
            },
            "update": {
              "description": "Adds a photo for the user.",
              "flatPath": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "id": "directory.users.photos.update",
              "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.readonly"
              ],
              "id": "directory.users.photos.get",
              "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "description": "Retrieves the user's photo.",
              "flatPath": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "path": "admin/directory/v1/users/{userKey}/photos/thumbnail",
              "description": "Removes the user's photo.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user"
              ],
              "id": "directory.users.photos.delete",
              "httpMethod": "DELETE"
            }
          }
        }
      },
      "methods": {
        "signOut": {
          "path": "admin/directory/v1/users/{userKey}/signOut",
          "httpMethod": "POST",
          "id": "directory.users.signOut",
          "flatPath": "admin/directory/v1/users/{userKey}/signOut",
          "description": "Sign a user out of all web and device sessions and reset their sign-in cookies. User will have to sign in by authenticating again.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ]
        },
        "undelete": {
          "path": "admin/directory/v1/users/{userKey}/undelete",
          "httpMethod": "POST",
          "description": "Undeletes a deleted user.",
          "id": "directory.users.undelete",
          "flatPath": "admin/directory/v1/users/{userKey}/undelete",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "id": "directory.users.update",
          "httpMethod": "PUT",
          "path": "admin/directory/v1/users/{userKey}",
          "flatPath": "admin/directory/v1/users/{userKey}",
          "description": "Updates a user. This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved, and fields set to `null` will be cleared."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "path": "admin/directory/v1/users",
          "description": "Creates a user.",
          "flatPath": "admin/directory/v1/users",
          "id": "directory.users.insert",
          "httpMethod": "POST"
        },
        "watch": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Watch for changes in users list",
          "flatPath": "admin/directory/v1/users/watch",
          "id": "directory.users.watch",
          "path": "admin/directory/v1/users/watch"
        },
        "delete": {
          "flatPath": "admin/directory/v1/users/{userKey}",
          "id": "directory.users.delete",
          "path": "admin/directory/v1/users/{userKey}",
          "httpMethod": "DELETE",
          "description": "Deletes a user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ]
        },
        "patch": {
          "id": "directory.users.patch",
          "description": "Updates a user using patch semantics. The update method should be used instead, since it also supports patch semantics and has better performance. This method is unable to clear fields that contain repeated objects (`addresses`, `phones`, etc). Use the update method instead.",
          "httpMethod": "PATCH",
          "flatPath": "admin/directory/v1/users/{userKey}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "path": "admin/directory/v1/users/{userKey}"
        },
        "get": {
          "flatPath": "admin/directory/v1/users/{userKey}",
          "path": "admin/directory/v1/users/{userKey}",
          "description": "Retrieves a user.",
          "id": "directory.users.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.readonly"
          ]
        },
        "makeAdmin": {
          "flatPath": "admin/directory/v1/users/{userKey}/makeAdmin",
          "path": "admin/directory/v1/users/{userKey}/makeAdmin",
          "id": "directory.users.makeAdmin",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "description": "Makes a user a super administrator."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/users",
          "id": "directory.users.list",
          "description": "Retrieves a paginated list of either deleted users or all users in a domain.",
          "path": "admin/directory/v1/users",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      }
    },
    "domainAliases": {
      "methods": {
        "list": {
          "id": "directory.domainAliases.list",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "path": "admin/directory/v1/customer/{customer}/domainaliases",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/customer/{customer}/domainaliases",
          "description": "Lists the domain aliases of the customer."
        },
        "delete": {
          "id": "directory.domainAliases.delete",
          "flatPath": "admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "description": "Deletes a domain Alias of the customer.",
          "httpMethod": "DELETE",
          "path": "admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}"
        },
        "get": {
          "flatPath": "admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}",
          "path": "admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "id": "directory.domainAliases.get",
          "description": "Retrieves a domain alias of the customer."
        },
        "insert": {
          "path": "admin/directory/v1/customer/{customer}/domainaliases",
          "httpMethod": "POST",
          "description": "Inserts a domain alias of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "flatPath": "admin/directory/v1/customer/{customer}/domainaliases",
          "id": "directory.domainAliases.insert"
        }
      }
    },
    "orgunits": {
      "methods": {
        "insert": {
          "path": "admin/directory/v1/customer/{customerId}/orgunits",
          "description": "Adds an organizational unit.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "flatPath": "admin/directory/v1/customer/{customerId}/orgunits",
          "id": "directory.orgunits.insert"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/customer/{customerId}/orgunits",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit",
            "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
          ],
          "id": "directory.orgunits.list",
          "description": "Retrieves a list of all organizational units for an account.",
          "path": "admin/directory/v1/customer/{customerId}/orgunits"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
          "flatPath": "admin/directory/v1/customer/{customerId}/orgunits/{orgunitsId}",
          "id": "directory.orgunits.patch",
          "description": "Updates an organizational unit. This method supports [patch semantics](/admin-sdk/directory/v1/guides/performance#patch)",
          "httpMethod": "PATCH"
        },
        "update": {
          "flatPath": "admin/directory/v1/customer/{customerId}/orgunits/{orgunitsId}",
          "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "description": "Updates an organizational unit.",
          "id": "directory.orgunits.update",
          "httpMethod": "PUT"
        },
        "get": {
          "flatPath": "admin/directory/v1/customer/{customerId}/orgunits/{orgunitsId}",
          "httpMethod": "GET",
          "description": "Retrieves an organizational unit.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit",
            "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
          ],
          "id": "directory.orgunits.get",
          "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}"
        },
        "delete": {
          "description": "Removes an organizational unit.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "flatPath": "admin/directory/v1/customer/{customerId}/orgunits/{orgunitsId}",
          "path": "admin/directory/v1/customer/{customerId}/orgunits/{+orgUnitPath}",
          "id": "directory.orgunits.delete",
          "httpMethod": "DELETE"
        }
      }
    },
    "mobiledevices": {
      "methods": {
        "list": {
          "id": "directory.mobiledevices.list",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/mobile",
          "description": "Retrieves a paginated list of all mobile devices for an account.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
          ],
          "path": "admin/directory/v1/customer/{customerId}/devices/mobile",
          "httpMethod": "GET"
        },
        "action": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.action"
          ],
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}/action",
          "description": "Takes an action that affects a mobile device. For example, remotely wiping a device.",
          "id": "directory.mobiledevices.action",
          "httpMethod": "POST",
          "path": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}/action"
        },
        "delete": {
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile"
          ],
          "id": "directory.mobiledevices.delete",
          "description": "Removes a mobile device.",
          "httpMethod": "DELETE",
          "path": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}"
        },
        "get": {
          "id": "directory.mobiledevices.get",
          "httpMethod": "GET",
          "description": "Retrieves a mobile device's properties.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
          ],
          "path": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}",
          "flatPath": "admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}"
        }
      }
    },
    "schemas": {
      "methods": {
        "insert": {
          "description": "Create schema.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "id": "directory.schemas.insert",
          "flatPath": "admin/directory/v1/customer/{customerId}/schemas",
          "httpMethod": "POST",
          "path": "admin/directory/v1/customer/{customerId}/schemas"
        },
        "patch": {
          "flatPath": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "description": "Patch Schema via Apiary Patch Orchestration",
          "id": "directory.schemas.patch",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "httpMethod": "PATCH",
          "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}"
        },
        "update": {
          "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "httpMethod": "PUT",
          "flatPath": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "id": "directory.schemas.update",
          "description": "Update schema"
        },
        "list": {
          "description": "Retrieve all schemas for a customer",
          "flatPath": "admin/directory/v1/customer/{customerId}/schemas",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema",
            "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
          ],
          "httpMethod": "GET",
          "path": "admin/directory/v1/customer/{customerId}/schemas",
          "id": "directory.schemas.list"
        },
        "get": {
          "flatPath": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "id": "directory.schemas.get",
          "httpMethod": "GET",
          "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema",
            "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
          ],
          "description": "Retrieve schema"
        },
        "delete": {
          "id": "directory.schemas.delete",
          "flatPath": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "path": "admin/directory/v1/customer/{customerId}/schemas/{schemaKey}",
          "description": "Delete schema",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ]
        }
      }
    },
    "tokens": {
      "methods": {
        "get": {
          "id": "directory.tokens.get",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/users/{userKey}/tokens/{clientId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "description": "Get information about an access token issued by a user.",
          "path": "admin/directory/v1/users/{userKey}/tokens/{clientId}"
        },
        "list": {
          "description": "Returns the set of tokens specified user has issued to 3rd party applications.",
          "id": "directory.tokens.list",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/users/{userKey}/tokens",
          "path": "admin/directory/v1/users/{userKey}/tokens",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ]
        },
        "delete": {
          "description": "Delete all access tokens issued by a user for an application.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "httpMethod": "DELETE",
          "flatPath": "admin/directory/v1/users/{userKey}/tokens/{clientId}",
          "path": "admin/directory/v1/users/{userKey}/tokens/{clientId}",
          "id": "directory.tokens.delete"
        }
      }
    },
    "verificationCodes": {
      "methods": {
        "generate": {
          "httpMethod": "POST",
          "id": "directory.verificationCodes.generate",
          "flatPath": "admin/directory/v1/users/{userKey}/verificationCodes/generate",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "path": "admin/directory/v1/users/{userKey}/verificationCodes/generate",
          "description": "Generate new backup verification codes for the user."
        },
        "invalidate": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "id": "directory.verificationCodes.invalidate",
          "httpMethod": "POST",
          "path": "admin/directory/v1/users/{userKey}/verificationCodes/invalidate",
          "description": "Invalidate the current backup verification codes for the user.",
          "flatPath": "admin/directory/v1/users/{userKey}/verificationCodes/invalidate"
        },
        "list": {
          "path": "admin/directory/v1/users/{userKey}/verificationCodes",
          "description": "Returns the current set of valid backup verification codes for the specified user.",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/users/{userKey}/verificationCodes",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "id": "directory.verificationCodes.list"
        }
      }
    },
    "privileges": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "flatPath": "admin/directory/v1/customer/{customer}/roles/ALL/privileges",
          "description": "Retrieves a paginated list of all privileges for a customer.",
          "id": "directory.privileges.list",
          "path": "admin/directory/v1/customer/{customer}/roles/ALL/privileges"
        }
      }
    },
    "roles": {
      "methods": {
        "delete": {
          "flatPath": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "httpMethod": "DELETE",
          "id": "directory.roles.delete",
          "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "description": "Deletes a role.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ]
        },
        "insert": {
          "path": "admin/directory/v1/customer/{customer}/roles",
          "id": "directory.roles.insert",
          "description": "Creates a role.",
          "httpMethod": "POST",
          "flatPath": "admin/directory/v1/customer/{customer}/roles",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ]
        },
        "get": {
          "description": "Retrieves a role.",
          "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "id": "directory.roles.get",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "flatPath": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "admin/directory/v1/customer/{customer}/roles",
          "id": "directory.roles.list",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "path": "admin/directory/v1/customer/{customer}/roles",
          "description": "Retrieves a paginated list of all the roles in a domain.",
          "httpMethod": "GET"
        },
        "update": {
          "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "httpMethod": "PUT",
          "flatPath": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "description": "Updates a role.",
          "id": "directory.roles.update"
        },
        "patch": {
          "path": "admin/directory/v1/customer/{customer}/roles/{roleId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "description": "Patch role via Apiary Patch Orchestration",
          "id": "directory.roles.patch",
          "flatPath": "admin/directory/v1/customer/{customer}/roles/{roleId}"
        }
      }
    },
    "asps": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "flatPath": "admin/directory/v1/users/{userKey}/asps",
          "path": "admin/directory/v1/users/{userKey}/asps",
          "httpMethod": "GET",
          "description": "List the ASPs issued by a user.",
          "id": "directory.asps.list"
        },
        "get": {
          "id": "directory.asps.get",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "description": "Get information about an ASP issued by a user.",
          "flatPath": "admin/directory/v1/users/{userKey}/asps/{codeId}",
          "httpMethod": "GET",
          "path": "admin/directory/v1/users/{userKey}/asps/{codeId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "httpMethod": "DELETE",
          "flatPath": "admin/directory/v1/users/{userKey}/asps/{codeId}",
          "path": "admin/directory/v1/users/{userKey}/asps/{codeId}",
          "id": "directory.asps.delete",
          "description": "Delete an ASP issued by a user."
        }
      }
    },
    "twoStepVerification": {
      "methods": {
        "turnOff": {
          "description": "Turn off 2-Step Verification for user.",
          "id": "directory.twoStepVerification.turnOff",
          "path": "admin/directory/v1/users/{userKey}/twoStepVerification/turnOff",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "flatPath": "admin/directory/v1/users/{userKey}/twoStepVerification/turnOff",
          "httpMethod": "POST"
        }
      }
    },
    "roleAssignments": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "directory.roleAssignments.get",
          "flatPath": "admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "description": "Retrieve a role assignment.",
          "path": "admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "admin/directory/v1/customer/{customer}/roleassignments",
          "id": "directory.roleAssignments.insert",
          "flatPath": "admin/directory/v1/customer/{customer}/roleassignments",
          "description": "Creates a role assignment.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ]
        },
        "delete": {
          "id": "directory.roleAssignments.delete",
          "httpMethod": "DELETE",
          "flatPath": "admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}",
          "path": "admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}",
          "description": "Deletes a role assignment.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ]
        },
        "list": {
          "id": "directory.roleAssignments.list",
          "description": "Retrieves a paginated list of all roleAssignments.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "path": "admin/directory/v1/customer/{customer}/roleassignments",
          "httpMethod": "GET",
          "flatPath": "admin/directory/v1/customer/{customer}/roleassignments"
        }
      }
    }
  },
  "rootUrl": "https://admin.googleapis.com/",
  "canonicalName": "directory",
  "description": "Admin SDK lets administrators of enterprise domains to view and manage resources like user, groups etc. It also provides audit and usage reports of domain.",
  "title": "Admin SDK API",
  "revision": "20210413",
  "mtlsRootUrl": "https://admin.mtls.googleapis.com/"
}
