{
  "protocol": "rest",
  "id": "admob:v1",
  "kind": "discovery#restDescription",
  "baseUrl": "https://admob.googleapis.com/",
  "name": "admob",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admob.readonly": {
          "description": "See your AdMob data"
        },
        "https://www.googleapis.com/auth/admob.report": {
          "description": "See your AdMob data"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/admob/api/",
  "batchPath": "batch",
  "ownerName": "Google",
  "version": "v1",
  "rootUrl": "https://admob.googleapis.com/",
  "servicePath": "",
  "revision": "20210414",
  "description": "The AdMob API allows publishers to programmatically get information about their AdMob account. ",
  "discoveryVersion": "v1",
  "resources": {
    "accounts": {
      "resources": {
        "networkReport": {
          "methods": {
            "generate": {
              "path": "v1/{+parent}/networkReport:generate",
              "flatPath": "v1/accounts/{accountsId}/networkReport:generate",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "id": "admob.accounts.networkReport.generate",
              "httpMethod": "POST",
              "description": "Generates an AdMob Network report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.",
              "streamingType": "SERVER_SIDE"
            }
          }
        },
        "apps": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v1/{+parent}/apps",
              "flatPath": "v1/accounts/{accountsId}/apps",
              "streamingType": "NONE",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly"
              ],
              "description": "List the apps under the specified AdMob account.",
              "id": "admob.accounts.apps.list"
            }
          }
        },
        "adUnits": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/accounts/{accountsId}/adUnits",
              "path": "v1/{+parent}/adUnits",
              "streamingType": "NONE",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly"
              ],
              "description": "List the ad units under the specified AdMob account.",
              "id": "admob.accounts.adUnits.list"
            }
          }
        },
        "mediationReport": {
          "methods": {
            "generate": {
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "streamingType": "SERVER_SIDE",
              "description": "Generates an AdMob Mediation report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.",
              "flatPath": "v1/accounts/{accountsId}/mediationReport:generate",
              "httpMethod": "POST",
              "id": "admob.accounts.mediationReport.generate",
              "path": "v1/{+parent}/mediationReport:generate"
            }
          }
        }
      },
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admob.readonly",
            "https://www.googleapis.com/auth/admob.report"
          ],
          "id": "admob.accounts.get",
          "flatPath": "v1/accounts/{accountsId}",
          "streamingType": "NONE",
          "path": "v1/{+name}",
          "description": "Gets information about the specified AdMob publisher account."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admob.readonly",
            "https://www.googleapis.com/auth/admob.report"
          ],
          "description": "Lists the AdMob publisher account that was most recently signed in to from the AdMob UI. For more information, see https://support.google.com/admob/answer/10243672.",
          "id": "admob.accounts.list",
          "path": "v1/accounts",
          "flatPath": "v1/accounts",
          "streamingType": "NONE"
        }
      }
    }
  },
  "mtlsRootUrl": "https://admob.mtls.googleapis.com/",
  "canonicalName": "AdMob",
  "ownerDomain": "google.com",
  "version_module": true,
  "title": "AdMob API",
  "fullyEncodeReservedExpansion": true,
  "basePath": ""
}
