{
  "servicePath": "",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "rootUrl": "https://adsense.googleapis.com/",
  "version": "v2",
  "revision": "20240324",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "title": "AdSense Management API",
  "fullyEncodeReservedExpansion": true,
  "id": "adsense:v2",
  "ownerName": "Google",
  "batchPath": "batch",
  "version_module": true,
  "baseUrl": "https://adsense.googleapis.com/",
  "documentationLink": "https://developers.google.com/adsense/management/",
  "name": "adsense",
  "mtlsRootUrl": "https://adsense.mtls.googleapis.com/",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        }
      }
    }
  },
  "description": "The AdSense Management API allows publishers to access their inventory and run earnings and performance reports.",
  "resources": {
    "accounts": {
      "methods": {
        "get": {
          "id": "adsense.accounts.get",
          "path": "v2/{+name}",
          "flatPath": "v2/accounts/{accountsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "description": "Gets information about the selected AdSense account."
        },
        "list": {
          "id": "adsense.accounts.list",
          "path": "v2/accounts",
          "flatPath": "v2/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "description": "Lists all accounts available to this user."
        },
        "listChildAccounts": {
          "id": "adsense.accounts.listChildAccounts",
          "path": "v2/{+parent}:listChildAccounts",
          "flatPath": "v2/accounts/{accountsId}:listChildAccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "description": "Lists all accounts directly managed by the given AdSense account."
        },
        "getAdBlockingRecoveryTag": {
          "id": "adsense.accounts.getAdBlockingRecoveryTag",
          "path": "v2/{+name}/adBlockingRecoveryTag",
          "flatPath": "v2/accounts/{accountsId}/adBlockingRecoveryTag",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "description": "Gets the ad blocking recovery tag of an account."
        }
      },
      "resources": {
        "adclients": {
          "methods": {
            "list": {
              "id": "adsense.accounts.adclients.list",
              "path": "v2/{+parent}/adclients",
              "flatPath": "v2/accounts/{accountsId}/adclients",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists all the ad clients available in an account."
            },
            "get": {
              "id": "adsense.accounts.adclients.get",
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets the ad client from the given resource name."
            },
            "getAdcode": {
              "id": "adsense.accounts.adclients.getAdcode",
              "path": "v2/{+name}/adcode",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adcode",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets the AdSense code for a given ad client. This returns what was previously known as the 'auto ad code'. This is only supported for ad clients with a product_code of AFC. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634)."
            }
          },
          "resources": {
            "adunits": {
              "methods": {
                "get": {
                  "id": "adsense.accounts.adclients.adunits.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Gets an ad unit from a specified account and ad client."
                },
                "list": {
                  "id": "adsense.accounts.adclients.adunits.list",
                  "path": "v2/{+parent}/adunits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all ad units under a specified account and ad client."
                },
                "getAdcode": {
                  "id": "adsense.accounts.adclients.adunits.getAdcode",
                  "path": "v2/{+name}/adcode",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Gets the ad unit code for a given ad unit. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634) and [Where to place the ad code in your HTML](https://support.google.com/adsense/answer/9190028)."
                },
                "create": {
                  "id": "adsense.accounts.adclients.adunits.create",
                  "path": "v2/{+parent}/adunits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Creates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. Note that ad units can only be created for ad clients with an \"AFC\" product code. For more info see the [AdClient resource](/adsense/management/reference/rest/v2/accounts.adclients). For now, this method ca[...]"
                },
                "patch": {
                  "id": "adsense.accounts.adclients.adunits.patch",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Updates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. For now, this method can only be used to update `DISPLAY` ad units. See: https://support.google.com/adsense/answer/9183566"
                },
                "listLinkedCustomChannels": {
                  "id": "adsense.accounts.adclients.adunits.listLinkedCustomChannels",
                  "path": "v2/{+parent}:listLinkedCustomChannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the custom channels available for an ad unit."
                }
              }
            },
            "customchannels": {
              "methods": {
                "listLinkedAdUnits": {
                  "id": "adsense.accounts.adclients.customchannels.listLinkedAdUnits",
                  "path": "v2/{+parent}:listLinkedAdUnits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the ad units available for a custom channel."
                },
                "get": {
                  "id": "adsense.accounts.adclients.customchannels.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Gets information about the selected custom channel."
                },
                "list": {
                  "id": "adsense.accounts.adclients.customchannels.list",
                  "path": "v2/{+parent}/customchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the custom channels available in an ad client."
                },
                "create": {
                  "id": "adsense.accounts.adclients.customchannels.create",
                  "path": "v2/{+parent}/customchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Creates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method."
                },
                "patch": {
                  "id": "adsense.accounts.adclients.customchannels.patch",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Updates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method."
                },
                "delete": {
                  "id": "adsense.accounts.adclients.customchannels.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Deletes a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method."
                }
              }
            },
            "urlchannels": {
              "methods": {
                "get": {
                  "id": "adsense.accounts.adclients.urlchannels.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels/{urlchannelsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Gets information about the selected url channel."
                },
                "list": {
                  "id": "adsense.accounts.adclients.urlchannels.list",
                  "path": "v2/{+parent}/urlchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists active url channels."
                }
              }
            }
          }
        },
        "alerts": {
          "methods": {
            "list": {
              "id": "adsense.accounts.alerts.list",
              "path": "v2/{+parent}/alerts",
              "flatPath": "v2/accounts/{accountsId}/alerts",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists all the alerts available in an account."
            }
          }
        },
        "payments": {
          "methods": {
            "list": {
              "id": "adsense.accounts.payments.list",
              "path": "v2/{+parent}/payments",
              "flatPath": "v2/accounts/{accountsId}/payments",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists all the payments available for an account."
            }
          }
        },
        "policyIssues": {
          "methods": {
            "get": {
              "id": "adsense.accounts.policyIssues.get",
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/policyIssues/{policyIssuesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets information about the selected policy issue."
            },
            "list": {
              "id": "adsense.accounts.policyIssues.list",
              "path": "v2/{+parent}/policyIssues",
              "flatPath": "v2/accounts/{accountsId}/policyIssues",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists all the policy issues for the specified account."
            }
          }
        },
        "reports": {
          "methods": {
            "getSaved": {
              "id": "adsense.accounts.reports.getSaved",
              "path": "v2/{+name}/saved",
              "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets the saved report from the given resource name."
            },
            "generate": {
              "id": "adsense.accounts.reports.generate",
              "path": "v2/{+account}/reports:generate",
              "flatPath": "v2/accounts/{accountsId}/reports:generate",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Generates an ad hoc report."
            },
            "generateCsv": {
              "id": "adsense.accounts.reports.generateCsv",
              "path": "v2/{+account}/reports:generateCsv",
              "flatPath": "v2/accounts/{accountsId}/reports:generateCsv",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Generates a csv formatted ad hoc report."
            }
          },
          "resources": {
            "saved": {
              "methods": {
                "generate": {
                  "id": "adsense.accounts.reports.saved.generate",
                  "path": "v2/{+name}/saved:generate",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generate",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Generates a saved report."
                },
                "generateCsv": {
                  "id": "adsense.accounts.reports.saved.generateCsv",
                  "path": "v2/{+name}/saved:generateCsv",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Generates a csv formatted saved report."
                },
                "list": {
                  "id": "adsense.accounts.reports.saved.list",
                  "path": "v2/{+parent}/reports/saved",
                  "flatPath": "v2/accounts/{accountsId}/reports/saved",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists saved reports."
                }
              }
            }
          }
        },
        "sites": {
          "methods": {
            "get": {
              "id": "adsense.accounts.sites.get",
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/sites/{sitesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets information about the selected site."
            },
            "list": {
              "id": "adsense.accounts.sites.list",
              "path": "v2/{+parent}/sites",
              "flatPath": "v2/accounts/{accountsId}/sites",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists all the sites available in an account."
            }
          }
        }
      }
    }
  }
}
