{
  "ownerName": "Google",
  "servicePath": "",
  "documentationLink": "http://code.google.com/apis/adsense/management/",
  "baseUrl": "https://adsense.googleapis.com/",
  "name": "adsense",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "version_module": true,
  "version": "v2",
  "id": "adsense:v2",
  "rootUrl": "https://adsense.googleapis.com/",
  "revision": "20210414",
  "resources": {
    "accounts": {
      "methods": {
        "get": {
          "path": "v2/{+name}",
          "id": "adsense.accounts.get",
          "httpMethod": "GET",
          "description": "Gets information about the selected AdSense account.",
          "flatPath": "v2/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ]
        },
        "list": {
          "flatPath": "v2/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "description": "Lists all accounts available to this user.",
          "id": "adsense.accounts.list",
          "httpMethod": "GET",
          "path": "v2/accounts"
        },
        "listChildAccounts": {
          "path": "v2/{+parent}:listChildAccounts",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v2/accounts/{accountsId}:listChildAccounts",
          "id": "adsense.accounts.listChildAccounts",
          "description": "Lists all accounts directly managed by the given AdSense account."
        }
      },
      "resources": {
        "adclients": {
          "resources": {
            "urlchannels": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists active url channels.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels",
                  "path": "v2/{+parent}/urlchannels",
                  "id": "adsense.accounts.adclients.urlchannels.list",
                  "httpMethod": "GET"
                }
              }
            },
            "adunits": {
              "methods": {
                "getAdcode": {
                  "path": "v2/{+name}/adcode",
                  "description": "Gets the AdSense code for a given ad unit.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.adunits.getAdcode",
                  "httpMethod": "GET",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.adunits.get",
                  "description": "Gets an ad unit from a specified account and ad client.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "listLinkedCustomChannels": {
                  "path": "v2/{+parent}:listLinkedCustomChannels",
                  "id": "adsense.accounts.adclients.adunits.listLinkedCustomChannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels",
                  "description": "Lists all the custom channels available for an ad unit.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "list": {
                  "path": "v2/{+parent}/adunits",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all ad units under a specified account and ad client.",
                  "id": "adsense.accounts.adclients.adunits.list",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits"
                }
              }
            },
            "customchannels": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.customchannels.get",
                  "path": "v2/{+name}",
                  "description": "Gets information about the selected custom channel."
                },
                "list": {
                  "id": "adsense.accounts.adclients.customchannels.list",
                  "path": "v2/{+parent}/customchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists all the custom channels available in an ad client."
                },
                "listLinkedAdUnits": {
                  "path": "v2/{+parent}:listLinkedAdUnits",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the ad units available for a custom channel.",
                  "id": "adsense.accounts.adclients.customchannels.listLinkedAdUnits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.adclients.list",
              "description": "Lists all the ad clients available in an account.",
              "path": "v2/{+parent}/adclients",
              "flatPath": "v2/accounts/{accountsId}/adclients",
              "httpMethod": "GET"
            },
            "getAdcode": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.adclients.getAdcode",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adcode",
              "path": "v2/{+name}/adcode",
              "description": "Gets the AdSense code for a given ad client. This returns what was previously known as the 'auto ad code'. This is only supported for ad clients with a product_code of AFC. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634).",
              "httpMethod": "GET"
            }
          }
        },
        "reports": {
          "resources": {
            "saved": {
              "methods": {
                "generateCsv": {
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv",
                  "path": "v2/{+name}/saved:generateCsv",
                  "description": "Generates a csv formatted saved report.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "adsense.accounts.reports.saved.generateCsv"
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v2/accounts/{accountsId}/reports/saved",
                  "path": "v2/{+parent}/reports/saved",
                  "id": "adsense.accounts.reports.saved.list",
                  "description": "Lists saved reports.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "generate": {
                  "httpMethod": "GET",
                  "description": "Generates a saved report.",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generate",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+name}/saved:generate",
                  "id": "adsense.accounts.reports.saved.generate"
                }
              }
            }
          },
          "methods": {
            "generateCsv": {
              "flatPath": "v2/accounts/{accountsId}/reports:generateCsv",
              "id": "adsense.accounts.reports.generateCsv",
              "httpMethod": "GET",
              "description": "Generates a csv formatted ad hoc report.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v2/{+account}/reports:generateCsv"
            },
            "generate": {
              "path": "v2/{+account}/reports:generate",
              "id": "adsense.accounts.reports.generate",
              "flatPath": "v2/accounts/{accountsId}/reports:generate",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Generates an ad hoc report."
            }
          }
        },
        "sites": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v2/accounts/{accountsId}/sites/{sitesId}",
              "description": "Gets information about the selected site.",
              "id": "adsense.accounts.sites.get"
            },
            "list": {
              "description": "Lists all the sites available in an account.",
              "flatPath": "v2/accounts/{accountsId}/sites",
              "id": "adsense.accounts.sites.list",
              "path": "v2/{+parent}/sites",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          }
        },
        "payments": {
          "methods": {
            "list": {
              "id": "adsense.accounts.payments.list",
              "description": "Lists all the payments available for an account.",
              "flatPath": "v2/accounts/{accountsId}/payments",
              "path": "v2/{+parent}/payments",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          }
        },
        "alerts": {
          "methods": {
            "list": {
              "description": "Lists all the alerts available in an account.",
              "id": "adsense.accounts.alerts.list",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v2/{+parent}/alerts",
              "flatPath": "v2/accounts/{accountsId}/alerts",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        }
      }
    }
  },
  "basePath": "",
  "description": "The AdSense Management API allows publishers to access their inventory and run earnings and performance reports.",
  "kind": "discovery#restDescription",
  "title": "AdSense Management API",
  "mtlsRootUrl": "https://adsense.mtls.googleapis.com/",
  "batchPath": "batch",
  "protocol": "rest"
}
