{
  "ownerDomain": "google.com",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "title": "Google Analytics Data API",
  "basePath": "",
  "documentationLink": "https://developers.google.com/analytics/devguides/reporting/data/v1/",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://analyticsdata.googleapis.com/",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "batchPath": "batch",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "revision": "20210827",
  "canonicalName": "AnalyticsData",
  "name": "analyticsdata",
  "version": "v1beta",
  "description": "Accesses report data in Google Analytics.",
  "version_module": true,
  "servicePath": "",
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "id": "analyticsdata:v1beta",
  "resources": {
    "properties": {
      "methods": {
        "runReport": {
          "flatPath": "v1beta/properties/{propertiesId}:runReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name.",
          "httpMethod": "POST",
          "id": "analyticsdata.properties.runReport",
          "path": "v1beta/{+property}:runReport"
        },
        "runPivotReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}:runPivotReport",
          "httpMethod": "POST",
          "description": "Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data.",
          "id": "analyticsdata.properties.runPivotReport",
          "path": "v1beta/{+property}:runPivotReport"
        },
        "batchRunPivotReports": {
          "httpMethod": "POST",
          "flatPath": "v1beta/properties/{propertiesId}:batchRunPivotReports",
          "path": "v1beta/{+property}:batchRunPivotReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns multiple pivot reports in a batch. All reports must be for the same GA4 Property.",
          "id": "analyticsdata.properties.batchRunPivotReports"
        },
        "getMetadata": {
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics GA4 Property Identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. Univer[...]",
          "id": "analyticsdata.properties.getMetadata",
          "flatPath": "v1beta/properties/{propertiesId}/metadata",
          "httpMethod": "GET"
        },
        "runRealtimeReport": {
          "httpMethod": "POST",
          "flatPath": "v1beta/properties/{propertiesId}:runRealtimeReport",
          "path": "v1beta/{+property}:runRealtimeReport",
          "id": "analyticsdata.properties.runRealtimeReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "The Google Analytics Realtime API returns a customized report of realtime event data for your property. These reports show events and usage from the last 30 minutes."
        },
        "batchRunReports": {
          "flatPath": "v1beta/properties/{propertiesId}:batchRunReports",
          "path": "v1beta/{+property}:batchRunReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns multiple reports in a batch. All reports must be for the same GA4 Property.",
          "id": "analyticsdata.properties.batchRunReports",
          "httpMethod": "POST"
        },
        "checkCompatibility": {
          "description": "This compatibility method lists dimensions and metrics that can be added to a report request and maintain compatibility. This method fails if the request's dimensions and metrics are incompatible. In Google Analytics, reports fail if they request incompatible dimensions and/or metrics; in that case, you will need to remove dimensions and/or metrics from the incompatible report until the report is compatible. The Realtime and Core reports have different compatibility rul[...]",
          "flatPath": "v1beta/properties/{propertiesId}:checkCompatibility",
          "id": "analyticsdata.properties.checkCompatibility",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "path": "v1beta/{+property}:checkCompatibility"
        }
      }
    }
  }
}
