{
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "canonicalName": "Google Analytics Admin",
  "revision": "20240115",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  },
  "id": "analyticsadmin:v1alpha",
  "servicePath": "",
  "version": "v1alpha",
  "name": "analyticsadmin",
  "version_module": true,
  "batchPath": "batch",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1alpha/accountSummaries",
          "flatPath": "v1alpha/accountSummaries"
        }
      }
    },
    "properties": {
      "resources": {
        "channelGroups": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Lists ChannelGroups on a property."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "description": "Updates a ChannelGroup.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.channelGroups.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "description": "Creates a ChannelGroup."
            },
            "get": {
              "id": "analyticsadmin.properties.channelGroups.get",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single ChannelGroup."
            },
            "delete": {
              "id": "analyticsadmin.properties.channelGroups.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "dataStreams": {
          "resources": {
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get"
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "create": {
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema."
                }
              }
            },
            "eventCreateRules": {
              "methods": {
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "description": "Updates an EventCreateRule.",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single EventCreateRule.",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create"
                },
                "list": {
                  "description": "Lists EventCreateRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                }
              }
            }
          },
          "methods": {
            "updateDataRedactionSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "path": "v1alpha/{+name}",
              "description": "Updates a DataRedactionSettings on a property."
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "getEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Lists DataStreams on a property."
            },
            "getDataRedactionSettings": {
              "httpMethod": "GET",
              "description": "Lookup for a single DataRedactionSettings.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings"
            },
            "get": {
              "id": "analyticsadmin.properties.dataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single DataStream."
            },
            "updateEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/dataStreams"
            },
            "getGlobalSiteTag": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "path": "v1alpha/{+name}",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "create": {
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch"
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete"
            }
          }
        },
        "audiences": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "archive": {
              "id": "analyticsadmin.properties.audiences.archive",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "description": "Archives an Audience on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive"
            },
            "get": {
              "id": "analyticsadmin.properties.audiences.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "list": {
              "path": "v1alpha/{+parent}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "id": "analyticsadmin.properties.audiences.list"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an Audience.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "id": "analyticsadmin.properties.audiences.create"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST",
              "description": "Creates a CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "httpMethod": "POST"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a CustomMetric on a property.",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "delete": {
              "description": "Deletes a ExpandedDataSet on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}"
            },
            "create": {
              "path": "v1alpha/{+parent}/expandedDataSets",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "description": "Creates a ExpandedDataSet.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Lookup for a single ExpandedDataSet.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "description": "Lists ExpandedDataSets on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.patch"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Looks up a single AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "description": "Deletes an AdSenseLink."
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "description": "Creates an AdSenseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists AdSenseLinks on a property.",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single CalculatedMetric.",
              "id": "analyticsadmin.properties.calculatedMetrics.get"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "description": "Updates a CalculatedMetric on a property."
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "description": "Deletes a CalculatedMetric on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.delete"
            },
            "list": {
              "description": "Lists CalculatedMetrics on a property.",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "description": "Creates a CalculatedMetric.",
              "httpMethod": "POST"
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "httpMethod": "GET",
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a SearchAds360Link.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.create"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Lists all SearchAds360Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.searchAds360Links.list"
            },
            "patch": {
              "description": "Updates a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.patch"
            },
            "get": {
              "description": "Look up a single SearchAds360Link",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "httpMethod": "GET",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "httpMethod": "PATCH",
              "description": "Updates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "description": "Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a conversion event in a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Creates a conversion event with the specified attributes."
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET",
              "description": "Lists CustomDimensions on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1alpha/{+parent}/customDimensions"
            },
            "archive": {
              "description": "Archives a CustomDimension on a property.",
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a GoogleAdsLink on a property"
            },
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Deletes a GoogleAdsLink on a property",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all access bindings on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.list"
            },
            "patch": {
              "description": "Updates an access binding on an account or property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "batchDelete": {
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "httpMethod": "GET",
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.create",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Creates an access binding on an account or property."
            },
            "batchUpdate": {
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "httpMethod": "POST"
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.batchCreate"
            },
            "get": {
              "id": "analyticsadmin.properties.accessBindings.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Gets information about an access binding.",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "cancel": {
              "path": "v1alpha/{+name}:cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals."
            },
            "list": {
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals"
            },
            "approve": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link.",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "description": "Lists BigQuery Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "httpMethod": "GET"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "description": "Creates a subproperty Event Filter.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "description": "Deletes a subproperty event filter.",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "description": "Updates a subproperty Event Filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "description": "List all subproperty Event Filters on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.list"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single subproperty Event Filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.subpropertyEventFilters.get"
            }
          }
        }
      },
      "methods": {
        "createSubproperty": {
          "flatPath": "v1alpha/properties:createSubproperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createSubproperty",
          "httpMethod": "POST",
          "path": "v1alpha/properties:createSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty."
        },
        "fetchConnectedGa4Property": {
          "httpMethod": "GET",
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties."
        },
        "deleteConnectedSiteTag": {
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
          "path": "v1alpha/properties:deleteConnectedSiteTag",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "createConnectedSiteTag": {
          "path": "v1alpha/properties:createConnectedSiteTag",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:createConnectedSiteTag",
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties."
        },
        "updateDataRetentionSettings": {
          "description": "Updates the singleton data retention settings for this property.",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}"
        },
        "createRollupProperty": {
          "description": "Create a roll-up property and all roll-up property source links.",
          "flatPath": "v1alpha/properties:createRollupProperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createRollupProperty",
          "path": "v1alpha/properties:createRollupProperty",
          "httpMethod": "POST"
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE",
          "id": "analyticsadmin.properties.delete",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}"
        },
        "getAttributionSettings": {
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "description": "Lookup for a AttributionSettings singleton.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "updateAttributionSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "httpMethod": "PATCH",
          "description": "Updates attribution settings on a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateAttributionSettings"
        },
        "acknowledgeUserDataCollection": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection"
        },
        "create": {
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "path": "v1alpha/properties",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1alpha/properties"
        },
        "getGoogleSignalsSettings": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "description": "Lookup for Google Signals settings for a property.",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut"
        },
        "updateGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property."
        },
        "listConnectedSiteTags": {
          "id": "analyticsadmin.properties.listConnectedSiteTags",
          "path": "v1alpha/properties:listConnectedSiteTags",
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property.",
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single \"GA4\" Property.",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "runAccessReport": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA4 UI [...]",
          "path": "v1alpha/{+entity}:runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport"
        }
      }
    },
    "accounts": {
      "methods": {
        "runAccessReport": {
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA4 UI [...]",
          "path": "v1alpha/{+entity}:runAccessReport",
          "id": "analyticsadmin.accounts.runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts",
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found."
        },
        "getDataSharingSettings": {
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        },
        "patch": {
          "description": "Updates an account.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "delete": {
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.delete"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.get",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account.",
          "flatPath": "v1alpha/accounts/{accountsId}"
        }
      },
      "resources": {
        "accessBindings": {
          "methods": {
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "id": "analyticsadmin.accounts.accessBindings.batchGet"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.accounts.accessBindings.get",
              "description": "Gets information about an access binding."
            },
            "batchUpdate": {
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "httpMethod": "DELETE"
            },
            "batchCreate": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate"
            },
            "batchDelete": {
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.batchDelete"
            },
            "list": {
              "description": "Lists all access bindings on an account or property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.accounts.accessBindings.patch"
            },
            "create": {
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.create",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "httpMethod": "POST"
            }
          }
        }
      }
    }
  },
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "baseUrl": "https://analyticsadmin.googleapis.com/"
}
