{
  "servicePath": "",
  "ownerName": "Google",
  "version": "v1alpha",
  "name": "analyticsadmin",
  "batchPath": "batch",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "kind": "discovery#restDescription",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "description": "",
  "title": "Google Analytics Admin API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "canonicalName": "Google Analytics Admin",
  "protocol": "rest",
  "id": "analyticsadmin:v1alpha",
  "revision": "20230302",
  "version_module": true,
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "ownerDomain": "google.com",
  "resources": {
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate"
            },
            "patch": {
              "id": "analyticsadmin.accounts.userLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates a user link on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH"
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "id": "analyticsadmin.accounts.userLinks.create"
            },
            "batchGet": {
              "description": "Gets information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet"
            },
            "audit": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Lists all user links on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.list"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes a user link on an account or property."
            }
          }
        },
        "accessBindings": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "get": {
              "description": "Gets information about an access binding.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.get",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates an access binding on an account or property.",
              "httpMethod": "PATCH"
            },
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "httpMethod": "GET"
            },
            "batchDelete": {
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "batchCreate": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate"
            }
          }
        }
      },
      "methods": {
        "runAccessReport": {
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "path": "v1alpha/{+entity}:runAccessReport",
          "id": "analyticsadmin.accounts.runAccessReport"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "flatPath": "v1alpha/accounts"
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents"
        },
        "getDataSharingSettings": {
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "get": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "description": "Lookup for a single Account."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Updates an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account."
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1alpha/accountSummaries",
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "resources": {
        "firebaseLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST"
            },
            "list": {
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a ExpandedDataSet on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists ExpandedDataSets on a property.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ExpandedDataSet.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "description": "Deletes a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "description": "Creates a ExpandedDataSet.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "description": "Look up a single SearchAds360Link",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Lists all SearchAds360Links on a property.",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a SearchAds360Link.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "httpMethod": "GET",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            },
            "approve": {
              "path": "v1alpha/{+name}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "httpMethod": "POST",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals"
            },
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "description": "Lists BigQuery Links on a property.",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single BigQuery Link.",
              "httpMethod": "GET"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            }
          }
        },
        "audiences": {
          "methods": {
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.audiences.archive",
              "description": "Archives an Audience on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property.",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "analyticsadmin.properties.audiences.list",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/audiences"
            },
            "create": {
              "id": "analyticsadmin.properties.audiences.create",
              "description": "Creates an Audience.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/audiences"
            },
            "get": {
              "id": "analyticsadmin.properties.audiences.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Creates a conversion event with the specified attributes."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Retrieve a single conversion event.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.conversionEvents.get",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.get"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a DataStream on a property."
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream."
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property.",
              "path": "v1alpha/{+parent}/dataStreams"
            },
            "getGlobalSiteTag": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create"
                },
                "patch": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get"
                }
              }
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "description": "Lookup for a single CustomMetric.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "description": "Lists CustomMetrics on a property."
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "patch": {
              "id": "analyticsadmin.properties.customMetrics.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a CustomMetric on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "archive": {
              "httpMethod": "POST",
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET"
            },
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST",
              "description": "Archives a CustomDimension on a property.",
              "path": "v1alpha/{+name}:archive"
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CustomDimension."
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.create",
              "description": "Creates a CustomDimension."
            }
          }
        },
        "accessBindings": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.create",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.get",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchUpdate": {
              "description": "Updates information about multiple access bindings to an account or property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.delete"
            },
            "patch": {
              "id": "analyticsadmin.properties.accessBindings.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Updates an access binding on an account or property."
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchGet": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property."
            }
          }
        },
        "userLinks": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.userLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            },
            "get": {
              "description": "Gets information about a user's link to an account or property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE"
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list",
              "httpMethod": "GET"
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "httpMethod": "POST",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "batchDelete": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchDelete"
            },
            "batchUpdate": {
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate"
            },
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks"
            },
            "audit": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "id": "analyticsadmin.properties.userLinks.audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs."
            }
          }
        }
      },
      "methods": {
        "delete": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete",
          "httpMethod": "DELETE",
          "path": "v1alpha/{+name}"
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "acknowledgeUserDataCollection": {
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.list"
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "httpMethod": "POST"
        },
        "updateGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings"
        },
        "updateDataRetentionSettings": {
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "listConnectedSiteTags": {
          "path": "v1alpha/properties:listConnectedSiteTags",
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "id": "analyticsadmin.properties.listConnectedSiteTags",
          "description": "Lists the connected site tags for a Universal Analytics property. Note: this has no effect on GA4 property.",
          "httpMethod": "POST"
        },
        "updateAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "description": "Updates attribution settings on a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH"
        },
        "getAttributionSettings": {
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a AttributionSettings singleton.",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        },
        "create": {
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes."
        },
        "getGoogleSignalsSettings": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "description": "Lookup for Google Signals settings for a property.",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "GET"
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property."
        },
        "getDataRetentionSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "deleteConnectedSiteTag": {
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "path": "v1alpha/properties:deleteConnectedSiteTag",
          "httpMethod": "POST",
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties."
        }
      }
    }
  }
}
