{
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "version": "v1alpha",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "title": "Google Analytics Admin API",
  "servicePath": "",
  "id": "analyticsadmin:v1alpha",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accountSummaries.list",
          "flatPath": "v1alpha/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    },
    "properties": {
      "resources": {
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "cancel": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:cancel",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals"
            },
            "approve": {
              "path": "v1alpha/{+name}:approve",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve"
            },
            "list": {
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals"
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal."
            }
          }
        },
        "audiences": {
          "methods": {
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "description": "Archives an Audience on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.archive"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Creates an Audience.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.audiences.create",
              "path": "v1alpha/{+parent}/audiences"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.list",
              "path": "v1alpha/{+parent}/audiences"
            },
            "patch": {
              "description": "Updates an Audience on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.audiences.patch"
            },
            "get": {
              "id": "analyticsadmin.properties.audiences.get",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "description": "Lookup for a single BigQuery Link."
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "httpMethod": "GET",
              "description": "Lists BigQuery Links on a property.",
              "path": "v1alpha/{+parent}/bigQueryLinks"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a SearchAds360Link.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "path": "v1alpha/{+parent}/searchAds360Links"
            },
            "patch": {
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a SearchAds360Link on a property."
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "description": "Deletes a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Look up a single SearchAds360Link",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "description": "Lists all SearchAds360Links on a property.",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "description": "Deletes an AdSenseLink.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}"
            },
            "get": {
              "description": "Looks up a single AdSenseLink.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "description": "Lists AdSenseLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            },
            "create": {
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "description": "Creates an AdSenseLink.",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customMetrics",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics"
            },
            "patch": {
              "description": "Updates a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "httpMethod": "PATCH"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.get",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "accessBindings": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property."
            },
            "list": {
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "analyticsadmin.properties.accessBindings.patch",
              "description": "Updates an access binding on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate"
            },
            "batchDelete": {
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "batchGet": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.create"
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.batchCreate"
            },
            "get": {
              "id": "analyticsadmin.properties.accessBindings.get",
              "httpMethod": "GET",
              "description": "Gets information about an access binding.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.create"
            },
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/firebaseLinks"
            }
          }
        },
        "channelGroups": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.create",
              "description": "Creates a ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/channelGroups"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single ChannelGroup.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "id": "analyticsadmin.properties.channelGroups.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Lists ChannelGroups on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.channelGroups.list"
            },
            "patch": {
              "description": "Updates a ChannelGroup.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.channelGroups.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.delete",
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            }
          }
        },
        "userLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.userLinks.create",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks"
            },
            "list": {
              "description": "Lists all user links on an account or property.",
              "id": "analyticsadmin.properties.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks"
            },
            "batchCreate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "audit": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.audit"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.properties.userLinks.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}"
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete"
            },
            "patch": {
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "httpMethod": "POST"
            },
            "batchGet": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "description": "Creates a conversion event with the specified attributes.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "create": {
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Updates a ExpandedDataSet on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "description": "Lists ExpandedDataSets on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/expandedDataSets"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Lookup for a single ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "description": "Deletes a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a ExpandedDataSet.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "create": {
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete"
            },
            "get": {
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "httpMethod": "PATCH",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a CustomDimension."
            },
            "list": {
              "description": "Lists CustomDimensions on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1alpha/{+name}:archive"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.patch"
            },
            "getGlobalSiteTag": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single DataStream.",
              "id": "analyticsadmin.properties.dataStreams.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DataStream on a property.",
              "id": "analyticsadmin.properties.dataStreams.delete"
            },
            "list": {
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "getEnhancedMeasurementSettings": {
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings"
            },
            "updateEnhancedMeasurementSettings": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Creates a DataStream."
            }
          },
          "resources": {
            "eventCreateRules": {
              "methods": {
                "delete": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete"
                },
                "patch": {
                  "description": "Updates an EventCreateRule.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "description": "Lists EventCreateRules on a web data stream."
                },
                "create": {
                  "description": "Creates an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "description": "Lookup for a single EventCreateRule.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates a measurement protocol secret."
                },
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}",
                  "description": "Updates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret."
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                }
              }
            }
          }
        }
      },
      "methods": {
        "listConnectedSiteTags": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.listConnectedSiteTags",
          "path": "v1alpha/properties:listConnectedSiteTags",
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "httpMethod": "POST",
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property."
        },
        "get": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.get"
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.properties.runAccessReport"
        },
        "getGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "description": "Lookup for Google Signals settings for a property.",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut"
        },
        "updateGoogleSignalsSettings": {
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings"
        },
        "getAttributionSettings": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getAttributionSettings",
          "description": "Lookup for a AttributionSettings singleton."
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1alpha/properties",
          "path": "v1alpha/properties"
        },
        "create": {
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "path": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST"
        },
        "updateDataRetentionSettings": {
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings"
        },
        "patch": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Updates a property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "updateAttributionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates attribution settings on a property.",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        },
        "acknowledgeUserDataCollection": {
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "createConnectedSiteTag": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties.",
          "path": "v1alpha/properties:createConnectedSiteTag",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:createConnectedSiteTag"
        },
        "fetchConnectedGa4Property": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties.",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property"
        },
        "deleteConnectedSiteTag": {
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "path": "v1alpha/properties:deleteConnectedSiteTag"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete"
        }
      }
    },
    "accounts": {
      "resources": {
        "accessBindings": {
          "methods": {
            "batchDelete": {
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "create": {
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "description": "Updates an access binding on an account or property."
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property."
            },
            "delete": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE"
            },
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.list"
            },
            "get": {
              "description": "Gets information about an access binding.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.accessBindings.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        },
        "userLinks": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property.",
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.list"
            },
            "patch": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.patch",
              "path": "v1alpha/{+name}"
            },
            "batchDelete": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.delete"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property."
            },
            "create": {
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.create"
            },
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "httpMethod": "GET"
            },
            "audit": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate"
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.list",
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "get": {
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lookup for a single Account."
        },
        "patch": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates an account."
        },
        "provisionAccountTicket": {
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account.",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "runAccessReport": {
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.runAccessReport",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport"
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents"
        },
        "delete": {
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        }
      }
    }
  },
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "canonicalName": "Google Analytics Admin",
  "version_module": true,
  "ownerDomain": "google.com",
  "fullyEncodeReservedExpansion": true,
  "name": "analyticsadmin",
  "revision": "20230511",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "description": "",
  "protocol": "rest",
  "basePath": ""
}
