{
  "id": "analyticsadmin:v1alpha",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "canonicalName": "Google Analytics Admin",
  "resources": {
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.patch",
              "description": "Updates a user link on an account or property."
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property."
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "description": "Deletes a user link on an account or property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "list": {
              "description": "Lists all user links on an account or property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.list",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchGet": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property."
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "httpMethod": "POST",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.create"
            },
            "audit": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.get",
              "description": "Gets information about a user's link to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property."
            }
          }
        }
      },
      "methods": {
        "list": {
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1alpha/accounts",
          "path": "v1alpha/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "getDataSharingSettings": {
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.get",
          "description": "Lookup for a single Account.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "GET"
        },
        "searchChangeHistoryEvents": {
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents"
        },
        "patch": {
          "description": "Updates an account.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}"
        },
        "provisionAccountTicket": {
          "path": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}"
        }
      }
    },
    "properties": {
      "resources": {
        "androidAppDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.list",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a measurement protocol secret.",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.patch"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.get"
                },
                "create": {
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.create",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret."
                }
              }
            }
          },
          "methods": {
            "patch": {
              "description": "Updates an android app stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            },
            "list": {
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes an android app stream on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}"
            },
            "get": {
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single AndroidAppDataStream"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deletes a conversion event in a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "userLinks": {
          "methods": {
            "audit": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit"
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Lists all user links on an account or property.",
              "id": "analyticsadmin.properties.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks"
            },
            "patch": {
              "id": "analyticsadmin.properties.userLinks.patch",
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchUpdate"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete"
            },
            "batchGet": {
              "description": "Gets information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "httpMethod": "GET"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.firebaseLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a FirebaseLink on a property",
              "httpMethod": "PATCH"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/firebaseLinks"
            },
            "create": {
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "POST"
            }
          }
        },
        "webDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.list",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.delete"
                },
                "create": {
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.create"
                },
                "get": {
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.get"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.patch",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH"
                }
              }
            }
          },
          "methods": {
            "updateEnhancedMeasurementSettings": {
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            },
            "getEnhancedMeasurementSettings": {
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect."
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "id": "analyticsadmin.properties.webDataStreams.get",
              "description": "Lookup for a single WebDataStream",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "getGlobalSiteTag": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a web stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.webDataStreams.patch"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/webDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "description": "Creates a web stream with the specified location and attributes.",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "httpMethod": "POST"
            },
            "delete": {
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a web stream on a property.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}"
            },
            "list": {
              "path": "v1alpha/{+parent}/webDataStreams",
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.webDataStreams.list",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get"
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "description": "Creates a CustomMetric.",
              "path": "v1alpha/{+parent}/customMetrics",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Lists CustomMetrics on a property."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "iosAppDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.delete"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates a measurement protocol secret.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.create"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret."
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            }
          },
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single IosAppDataStream",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes an iOS app stream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete"
            },
            "patch": {
              "description": "Updates an iOS app stream on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}"
            },
            "list": {
              "id": "analyticsadmin.properties.iosAppDataStreams.list",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "POST",
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "description": "Archives a CustomDimension on a property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Lookup for a single CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/customDimensions"
            }
          }
        }
      },
      "methods": {
        "create": {
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties",
          "path": "v1alpha/properties"
        },
        "get": {
          "id": "analyticsadmin.properties.get",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "GET",
          "description": "Lookup for a single \"GA4\" Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "updateGoogleSignalsSettings": {
          "description": "Updates Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}"
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1alpha/properties",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1alpha/properties"
        },
        "patch": {
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.properties.delete"
        },
        "getGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for Google Signals settings for a property.",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET",
          "path": "v1alpha/accountSummaries",
          "flatPath": "v1alpha/accountSummaries"
        }
      }
    }
  },
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "servicePath": "",
  "batchPath": "batch",
  "name": "analyticsadmin",
  "version_module": true,
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "description": "",
  "ownerDomain": "google.com",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "title": "Google Analytics Admin API",
  "fullyEncodeReservedExpansion": true,
  "version": "v1alpha",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "revision": "20210610",
  "basePath": "",
  "kind": "discovery#restDescription",
  "ownerName": "Google"
}
