{
  "version_module": true,
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "revision": "20230809",
  "version": "v1beta",
  "title": "Google Analytics Admin API",
  "servicePath": "",
  "discoveryVersion": "v1",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "name": "analyticsadmin",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "canonicalName": "Google Analytics Admin",
  "ownerName": "Google",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "protocol": "rest",
  "id": "analyticsadmin:v1beta",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "resources": {
    "accounts": {
      "methods": {
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1beta/{+name}"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.accounts.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1beta/accounts/{accountsId}",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "description": "Lookup for a single Account."
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "flatPath": "v1beta/accounts:provisionAccountTicket"
        },
        "searchChangeHistoryEvents": {
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents"
        },
        "patch": {
          "path": "v1beta/{+name}",
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "PATCH"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1beta/accounts",
          "path": "v1beta/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "runAccessReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.accounts.runAccessReport",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport"
        }
      }
    },
    "properties": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1beta/properties",
          "path": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "getDataRetentionSettings": {
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1beta/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1beta/properties"
        },
        "acknowledgeUserDataCollection": {
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection"
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+name}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.delete",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "httpMethod": "DELETE",
          "flatPath": "v1beta/properties/{propertiesId}"
        },
        "runAccessReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "path": "v1beta/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport"
        },
        "patch": {
          "description": "Updates a property.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties/{propertiesId}",
          "id": "analyticsadmin.properties.patch",
          "path": "v1beta/{+name}"
        },
        "updateDataRetentionSettings": {
          "description": "Updates the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1beta/{+name}"
        }
      },
      "resources": {
        "conversionEvents": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1beta/{+name}",
              "description": "Retrieve a single conversion event."
            },
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1beta/{+parent}/conversionEvents",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Updates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deletes a conversion event in a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/conversionEvents",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "description": "Creates a conversion event with the specified attributes."
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1beta/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1beta/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1beta/{+parent}/firebaseLinks",
              "httpMethod": "GET"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.get",
              "path": "v1beta/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create",
              "path": "v1beta/{+parent}/customDimensions"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "description": "Lists CustomDimensions on a property."
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "path": "v1beta/{+name}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream.",
              "path": "v1beta/{+parent}/dataStreams"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "DELETE",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.delete"
            },
            "list": {
              "path": "v1beta/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.list",
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams"
            },
            "get": {
              "path": "v1beta/{+name}",
              "description": "Lookup for a single DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "patch": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "get": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}"
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets"
                },
                "create": {
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create"
                }
              }
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH",
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "delete": {
              "description": "Deletes a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE",
              "path": "v1beta/{+name}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "create": {
              "path": "v1beta/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric."
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "path": "v1beta/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomMetrics on a property.",
              "httpMethod": "GET"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "description": "Updates a CustomMetric on a property.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST",
              "path": "v1beta/{+name}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "flatPath": "v1beta/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "path": "v1beta/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    }
  },
  "ownerDomain": "google.com"
}
