{
  "ownerName": "Google",
  "name": "analyticsadmin",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "discoveryVersion": "v1",
  "revision": "20211102",
  "basePath": "",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "canonicalName": "Google Analytics Admin",
  "protocol": "rest",
  "description": "",
  "id": "analyticsadmin:v1alpha",
  "servicePath": "",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "version": "v1alpha",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "title": "Google Analytics Admin API",
  "fullyEncodeReservedExpansion": true,
  "resources": {
    "properties": {
      "resources": {
        "iosAppDataStreams": {
          "methods": {
            "get": {
              "description": "Lookup for a single IosAppDataStream",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "description": "Updates an iOS app stream on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.",
              "id": "analyticsadmin.properties.iosAppDataStreams.list"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes an iOS app stream on a property.",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "get": {
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                },
                "list": {
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "create": {
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret."
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret."
                }
              }
            }
          }
        },
        "userLinks": {
          "methods": {
            "audit": {
              "id": "analyticsadmin.properties.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs."
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple users' links to an account or property."
            },
            "batchGet": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple users' links to an account or property."
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.userLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property."
            },
            "patch": {
              "id": "analyticsadmin.properties.userLinks.patch",
              "httpMethod": "PATCH",
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.delete",
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE"
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.get",
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property."
            },
            "batchCreate": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        },
        "androidAppDataStreams": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single AndroidAppDataStream",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "description": "Deletes an android app stream on a property.",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates an android app stream on a property."
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.list",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.create"
                },
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Updates a measurement protocol secret.",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents"
            },
            "get": {
              "id": "analyticsadmin.properties.conversionEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Retrieve a single conversion event."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            }
          }
        },
        "webDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "patch": {
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.list",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets"
                },
                "create": {
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.create",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret."
                },
                "get": {
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "GET",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret."
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "DELETE"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "description": "Updates a web stream on a property.",
              "id": "analyticsadmin.properties.webDataStreams.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.webDataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single WebDataStream"
            },
            "create": {
              "path": "v1alpha/{+parent}/webDataStreams",
              "description": "Creates a web stream with the specified location and attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.webDataStreams.list",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/webDataStreams"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "description": "Deletes a web stream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}"
            },
            "getGlobalSiteTag": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property."
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            },
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "archive": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomMetrics on a property.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "patch": {
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "httpMethod": "PATCH"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Creates a CustomMetric.",
              "httpMethod": "POST"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1alpha/{+name}:archive"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Creates a CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create"
            },
            "list": {
              "path": "v1alpha/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "httpMethod": "GET"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "path": "v1alpha/{+name}:cancel",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal."
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}"
            },
            "approve": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "path": "v1alpha/{+name}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created."
            }
          }
        }
      },
      "methods": {
        "list": {
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.list",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "updateDataRetentionSettings": {
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property."
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create",
          "path": "v1alpha/properties"
        },
        "delete": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.properties.delete"
        },
        "get": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET",
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "acknowledgeUserDataCollection": {
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or via this API) before MeasurementProtocolSecret resources may be created.",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST"
        },
        "updateGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "patch": {
          "description": "Updates a property.",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getGoogleSignalsSettings": {
          "description": "Lookup for Google Signals settings for a property.",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accountSummaries"
        }
      }
    },
    "accounts": {
      "methods": {
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket"
        },
        "patch": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates an account."
        },
        "list": {
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts"
        },
        "searchChangeHistoryEvents": {
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Lookup for a single Account."
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete"
        },
        "getDataSharingSettings": {
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "GET",
              "description": "Lists all user links on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.list"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.patch",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH"
            },
            "batchCreate": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "audit": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.audit"
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate"
            },
            "create": {
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.create",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchDelete": {
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "id": "analyticsadmin.accounts.userLinks.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes a user link on an account or property."
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.accounts.userLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about a user's link to an account or property.",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  }
}
