{
  "description": "",
  "canonicalName": "Google Analytics Admin",
  "discoveryVersion": "v1",
  "version_module": true,
  "ownerName": "Google",
  "revision": "20230503",
  "title": "Google Analytics Admin API",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "servicePath": "",
  "basePath": "",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "ownerDomain": "google.com",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "version": "v1alpha",
  "batchPath": "batch",
  "name": "analyticsadmin",
  "id": "analyticsadmin:v1alpha",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list"
        }
      }
    },
    "properties": {
      "resources": {
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property"
            },
            "create": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink."
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "get": {
              "description": "Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a conversion event in a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchDelete": {
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.create"
            },
            "get": {
              "description": "Gets information about an access binding.",
              "id": "analyticsadmin.properties.accessBindings.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate"
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Updates an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "description": "Deletes an access binding on an account or property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.list"
            },
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "httpMethod": "GET"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "list": {
              "description": "Lists BigQuery Links on a property.",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link.",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "description": "Deletes a SearchAds360Link on a property.",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Creates a SearchAds360Link.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "description": "Lists all SearchAds360Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.list"
            },
            "get": {
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Look up a single SearchAds360Link"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "description": "Updates a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.get",
              "description": "Lookup for a single CustomMetric."
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list"
            },
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property.",
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST"
            },
            "patch": {
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Updates a CustomMetric on a property."
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "approve": {
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "cancel": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "path": "v1alpha/{+name}:cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list"
            }
          }
        },
        "channelGroups": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a ChannelGroup.",
              "path": "v1alpha/{+parent}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.create"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "description": "Updates a ChannelGroup.",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists ChannelGroups on a property.",
              "path": "v1alpha/{+parent}/channelGroups",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes a ChannelGroup on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.channelGroups.delete",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "description": "Lists ExpandedDataSets on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "description": "Creates a ExpandedDataSet.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "httpMethod": "POST"
            },
            "get": {
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Lookup for a single ExpandedDataSet."
            },
            "patch": {
              "description": "Updates a ExpandedDataSet on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "list": {
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Look up a single DisplayVideo360AdvertiserLink"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "patch": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property."
            },
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "path": "v1alpha/{+name}:archive"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a CustomDimension on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Creates a CustomDimension.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.create",
              "path": "v1alpha/{+parent}/customDimensions"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single CustomDimension."
            }
          }
        },
        "audiences": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Creates an Audience.",
              "id": "analyticsadmin.properties.audiences.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/audiences"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "path": "v1alpha/{+name}"
            },
            "archive": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.audiences.archive",
              "description": "Archives an Audience on a property."
            },
            "patch": {
              "description": "Updates an Audience on a property.",
              "id": "analyticsadmin.properties.audiences.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "list": {
              "id": "analyticsadmin.properties.audiences.list",
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "dataStreams": {
          "resources": {
            "eventCreateRules": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "description": "Creates an EventCreateRule.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                },
                "list": {
                  "description": "Lists EventCreateRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes an EventCreateRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates an EventCreateRule."
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Lookup for a single EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "patch": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                }
              }
            }
          },
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "getEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "updateEnhancedMeasurementSettings": {
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings"
            },
            "create": {
              "path": "v1alpha/{+parent}/dataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Creates a DataStream.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Lookup for a single DataStream."
            },
            "list": {
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Lists DataStreams on a property.",
              "id": "analyticsadmin.properties.dataStreams.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataStream on a property."
            },
            "getGlobalSiteTag": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            }
          }
        },
        "userLinks": {
          "methods": {
            "batchGet": {
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple users' links to an account or property."
            },
            "get": {
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.properties.userLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "id": "analyticsadmin.properties.userLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate"
            },
            "audit": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.properties.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST"
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.delete",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "id": "analyticsadmin.properties.userLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property."
            },
            "create": {
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.create"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        }
      },
      "methods": {
        "fetchConnectedGa4Property": {
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties."
        },
        "updateGoogleSignalsSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "delete": {
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete",
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "acknowledgeUserDataCollection": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "list": {
          "flatPath": "v1alpha/properties",
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list"
        },
        "updateDataRetentionSettings": {
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "description": "Returns the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings"
        },
        "deleteConnectedSiteTag": {
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "httpMethod": "POST",
          "path": "v1alpha/properties:deleteConnectedSiteTag"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut"
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST"
        },
        "listConnectedSiteTags": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties:listConnectedSiteTags",
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.listConnectedSiteTags"
        },
        "create": {
          "path": "v1alpha/properties",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create"
        },
        "runAccessReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.runAccessReport"
        },
        "createConnectedSiteTag": {
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:createConnectedSiteTag",
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "path": "v1alpha/properties:createConnectedSiteTag"
        },
        "getGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "description": "Lookup for Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "GET"
        },
        "updateAttributionSettings": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates attribution settings on a property.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        },
        "getAttributionSettings": {
          "id": "analyticsadmin.properties.getAttributionSettings",
          "httpMethod": "GET",
          "description": "Lookup for a AttributionSettings singleton.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}"
        }
      }
    },
    "accounts": {
      "methods": {
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.runAccessReport"
        },
        "searchChangeHistoryEvents": {
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "httpMethod": "POST",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents"
        },
        "get": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Lookup for a single Account.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "description": "Updates an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "getDataSharingSettings": {
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1alpha/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.list"
        },
        "provisionAccountTicket": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account."
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.accounts.userLinks.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.accounts.userLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "audit": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit"
            },
            "create": {
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.patch"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "GET",
              "description": "Lists all user links on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.list"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property."
            },
            "batchGet": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet"
            },
            "batchCreate": {
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.patch"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.accounts.accessBindings.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "POST"
            }
          }
        }
      }
    }
  },
  "protocol": "rest",
  "kind": "discovery#restDescription"
}
