{
  "ownerName": "Google",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "version_module": true,
  "batchPath": "batch",
  "description": "Accesses report data in Google Analytics.",
  "version": "v1alpha",
  "canonicalName": "AnalyticsData",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/analytics/trusted-testing/analytics-data/",
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "name": "analyticsdata",
  "title": "Google Analytics Data API",
  "id": "analyticsdata:v1alpha",
  "resources": {
    "v1alpha": {
      "methods": {
        "getUniversalMetadata": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. Dimensions and metrics will be mostly added over time, but renames and deletions may occur. This method returns Universal Metadata. Universal Metadata are dimensions and metrics applicable to any property such as `country` and `totalUsers`.",
          "id": "analyticsdata.getUniversalMetadata",
          "flatPath": "v1alpha/universalMetadata",
          "httpMethod": "GET",
          "path": "v1alpha/universalMetadata"
        },
        "batchRunReports": {
          "flatPath": "v1alpha:batchRunReports",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha:batchRunReports",
          "id": "analyticsdata.batchRunReports",
          "description": "Returns multiple reports in a batch. All reports must be for the same Entity."
        },
        "batchRunPivotReports": {
          "id": "analyticsdata.batchRunPivotReports",
          "httpMethod": "POST",
          "path": "v1alpha:batchRunPivotReports",
          "flatPath": "v1alpha:batchRunPivotReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns multiple pivot reports in a batch. All reports must be for the same Entity."
        },
        "runReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name.",
          "id": "analyticsdata.runReport",
          "path": "v1alpha:runReport",
          "flatPath": "v1alpha:runReport",
          "httpMethod": "POST"
        },
        "runPivotReport": {
          "path": "v1alpha:runPivotReport",
          "httpMethod": "POST",
          "description": "Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha:runPivotReport",
          "id": "analyticsdata.runPivotReport"
        }
      }
    },
    "properties": {
      "methods": {
        "getMetadata": {
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics App + Web Property Identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. [...]",
          "id": "analyticsdata.properties.getMetadata",
          "flatPath": "v1alpha/properties/{propertiesId}/metadata",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    }
  },
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "protocol": "rest",
  "revision": "20201006",
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "rootUrl": "https://analyticsdata.googleapis.com/"
}
