{
  "basePath": "",
  "canonicalName": "Google Analytics Admin",
  "batchPath": "batch",
  "servicePath": "",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "name": "analyticsadmin",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "revision": "20230704",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "title": "Google Analytics Admin API",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "id": "analyticsadmin:v1beta",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "resources": {
    "accounts": {
      "methods": {
        "delete": {
          "path": "v1beta/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE"
        },
        "patch": {
          "description": "Updates an account.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch",
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "path": "v1beta/{+name}",
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getDataSharingSettings": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        },
        "provisionAccountTicket": {
          "path": "v1beta/accounts:provisionAccountTicket",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1beta/accounts",
          "flatPath": "v1beta/accounts",
          "httpMethod": "GET"
        },
        "runAccessReport": {
          "id": "analyticsadmin.accounts.runAccessReport",
          "path": "v1beta/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "searchChangeHistoryEvents": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters."
        }
      }
    },
    "properties": {
      "resources": {
        "firebaseLinks": {
          "methods": {
            "list": {
              "path": "v1beta/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink."
            },
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "description": "Deletes a FirebaseLink on a property"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/firebaseLinks",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a conversion event in a property.",
              "path": "v1beta/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create"
            },
            "list": {
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "description": "Updates a DataStream on a property."
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/dataStreams",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single DataStream.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get"
            },
            "delete": {
              "description": "Deletes a DataStream on a property.",
              "httpMethod": "DELETE",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property.",
              "id": "analyticsadmin.properties.dataStreams.list"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "list": {
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a GoogleAdsLink."
            },
            "list": {
              "path": "v1beta/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/customDimensions",
              "description": "Lists CustomDimensions on a property."
            },
            "archive": {
              "httpMethod": "POST",
              "path": "v1beta/{+name}:archive",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "description": "Updates a CustomDimension on a property.",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "httpMethod": "PATCH"
            },
            "get": {
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create",
              "description": "Creates a CustomDimension."
            }
          }
        },
        "customMetrics": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "path": "v1beta/{+name}"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get",
              "httpMethod": "GET",
              "path": "v1beta/{+name}"
            },
            "archive": {
              "path": "v1beta/{+name}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1beta/{+parent}/customMetrics"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "path": "v1beta/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST"
            }
          }
        }
      },
      "methods": {
        "acknowledgeUserDataCollection": {
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "updateDataRetentionSettings": {
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+name}",
          "description": "Lookup for a single \"GA4\" Property."
        },
        "patch": {
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Updates a property."
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "httpMethod": "DELETE",
          "path": "v1beta/{+name}"
        },
        "getDataRetentionSettings": {
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "httpMethod": "GET",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getDataRetentionSettings"
        },
        "list": {
          "flatPath": "v1beta/properties",
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/properties"
        },
        "create": {
          "flatPath": "v1beta/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create",
          "httpMethod": "POST",
          "path": "v1beta/properties"
        },
        "runAccessReport": {
          "httpMethod": "POST",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+entity}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1beta/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta/accountSummaries"
        }
      }
    }
  },
  "ownerName": "Google",
  "version": "v1beta",
  "rootUrl": "https://analyticsadmin.googleapis.com/"
}
