{
  "servicePath": "",
  "name": "analyticsadmin",
  "fullyEncodeReservedExpansion": true,
  "canonicalName": "Google Analytics Admin",
  "discoveryVersion": "v1",
  "basePath": "",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "ownerName": "Google",
  "version": "v1alpha",
  "revision": "20240312",
  "kind": "discovery#restDescription",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "id": "analyticsadmin:v1alpha",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "title": "Google Analytics Admin API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "batchPath": "batch",
  "protocol": "rest",
  "resources": {
    "properties": {
      "methods": {
        "fetchAutomatedGa4ConfigurationOptOut": {
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut"
        },
        "createConnectedSiteTag": {
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "path": "v1alpha/properties:createConnectedSiteTag",
          "flatPath": "v1alpha/properties:createConnectedSiteTag",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties.",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH"
        },
        "createRollupProperty": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createRollupProperty",
          "path": "v1alpha/properties:createRollupProperty",
          "httpMethod": "POST",
          "description": "Create a roll-up property and all roll-up property source links.",
          "flatPath": "v1alpha/properties:createRollupProperty"
        },
        "listConnectedSiteTags": {
          "httpMethod": "POST",
          "path": "v1alpha/properties:listConnectedSiteTags",
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "id": "analyticsadmin.properties.listConnectedSiteTags"
        },
        "getGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "httpMethod": "GET",
          "description": "Lookup for Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "delete": {
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not[...]",
          "httpMethod": "DELETE",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "createSubproperty": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty.",
          "path": "v1alpha/properties:createSubproperty",
          "flatPath": "v1alpha/properties:createSubproperty",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list"
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA4 UI [...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.runAccessReport"
        },
        "getAttributionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a AttributionSettings singleton.",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut"
        },
        "fetchConnectedGa4Property": {
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "httpMethod": "GET",
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property"
        },
        "updateDataRetentionSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "deleteConnectedSiteTag": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
          "path": "v1alpha/properties:deleteConnectedSiteTag"
        },
        "updateGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates Google Signals settings for a property.",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings"
        },
        "getDataRetentionSettings": {
          "httpMethod": "GET",
          "description": "Returns the singleton data retention settings for this property.",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "updateAttributionSettings": {
          "path": "v1alpha/{+name}",
          "description": "Updates attribution settings on a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "httpMethod": "PATCH"
        },
        "acknowledgeUserDataCollection": {
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        }
      },
      "resources": {
        "googleAdsLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "patch": {
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "path": "v1alpha/{+name}",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "customMetrics": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Updates a CustomMetric on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomMetric.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "archive": {
              "id": "analyticsadmin.properties.customMetrics.archive",
              "httpMethod": "POST",
              "description": "Archives a CustomMetric on a property.",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive"
            },
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "dataStreams": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Creates a DataStream.",
              "path": "v1alpha/{+parent}/dataStreams",
              "httpMethod": "POST"
            },
            "getDataRedactionSettings": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "description": "Lookup for a single DataRedactionSettings.",
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "httpMethod": "GET"
            },
            "getEnhancedMeasurementSettings": {
              "httpMethod": "GET",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DataStream on a property."
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataStream on a property."
            },
            "getGlobalSiteTag": {
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            },
            "updateEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            },
            "get": {
              "id": "analyticsadmin.properties.dataStreams.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single DataStream.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "updateDataRedactionSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "httpMethod": "PATCH",
              "description": "Updates a DataRedactionSettings on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create"
                },
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET"
                }
              }
            },
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "httpMethod": "GET"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates a SKAdNetworkConversionValueSchema."
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a SKAdNetworkConversionValueSchema."
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "path": "v1alpha/{+name}",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                }
              }
            },
            "eventCreateRules": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates an EventCreateRule."
                },
                "create": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates an EventCreateRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "description": "Lookup for a single EventCreateRule."
                },
                "list": {
                  "description": "Lists EventCreateRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                }
              }
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.calculatedMetrics.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "description": "Deletes a CalculatedMetric on a property.",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CalculatedMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CalculatedMetric on a property."
            },
            "list": {
              "description": "Lists CalculatedMetrics on a property.",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.calculatedMetrics.list"
            },
            "create": {
              "description": "Creates a CalculatedMetric.",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Updates a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "description": "Deletes a ExpandedDataSet on a property."
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single ExpandedDataSet.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}"
            },
            "create": {
              "description": "Creates a ExpandedDataSet.",
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/expandedDataSets"
            },
            "list": {
              "path": "v1alpha/{+parent}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "description": "Lists ExpandedDataSets on a property.",
              "httpMethod": "GET"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "list": {
              "description": "Lists all SearchAds360Links on a property.",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "create": {
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "description": "Creates a SearchAds360Link.",
              "path": "v1alpha/{+parent}/searchAds360Links"
            },
            "get": {
              "description": "Look up a single SearchAds360Link",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "description": "Updates a SearchAds360Link on a property.",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a SearchAds360Link on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "channelGroups": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.channelGroups.patch",
              "httpMethod": "PATCH",
              "description": "Updates a ChannelGroup.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Lists ChannelGroups on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.channelGroups.list",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups"
            },
            "get": {
              "id": "analyticsadmin.properties.channelGroups.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "create": {
              "description": "Creates a ChannelGroup.",
              "path": "v1alpha/{+parent}/channelGroups",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.channelGroups.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "description": "Deletes a ChannelGroup on a property."
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single subproperty Event Filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.get"
            },
            "delete": {
              "description": "Deletes a subproperty event filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "List all subproperty Event Filters on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "id": "analyticsadmin.properties.subpropertyEventFilters.list"
            },
            "patch": {
              "description": "Updates a subproperty Event Filter.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "description": "Creates a subproperty Event Filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "approve": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "path": "v1alpha/{+name}:approve",
              "httpMethod": "POST"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals."
            },
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "path": "v1alpha/{+name}:cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property."
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink."
            },
            "list": {
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink."
            },
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "description": "Deletes a FirebaseLink on a property",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "description": "Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.create",
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Creates a conversion event with the specified attributes."
            },
            "patch": {
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Updates a conversion event with the specified attributes.",
              "httpMethod": "PATCH"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a conversion event in a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.conversionEvents.delete"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "batchDelete": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            },
            "batchUpdate": {
              "description": "Updates information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes an access binding on an account or property."
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "get": {
              "description": "Gets information about an access binding.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.accessBindings.get"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "archive": {
              "description": "Archives a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link."
            },
            "list": {
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "description": "Lists BigQuery Links on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/bigQueryLinks"
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list"
            }
          }
        },
        "audiences": {
          "methods": {
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "httpMethod": "PATCH"
            },
            "create": {
              "path": "v1alpha/{+parent}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an Audience.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "id": "analyticsadmin.properties.audiences.create"
            },
            "archive": {
              "description": "Archives an Audience on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.audiences.archive",
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "id": "analyticsadmin.properties.audiences.get",
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.audiences.list",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "path": "v1alpha/{+parent}/audiences"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates an AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/adSenseLinks"
            },
            "list": {
              "description": "Lists AdSenseLinks on a property.",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Looks up a single AdSenseLink."
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "description": "Deletes an AdSenseLink.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.delete"
            }
          }
        }
      }
    },
    "accounts": {
      "methods": {
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "provisionAccountTicket": {
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "httpMethod": "POST",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "patch": {
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates an account."
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "flatPath": "v1alpha/accounts",
          "path": "v1alpha/accounts",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.list"
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET"
        },
        "runAccessReport": {
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "id": "analyticsadmin.accounts.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA4 UI [...]",
          "path": "v1alpha/{+entity}:runAccessReport"
        }
      },
      "resources": {
        "accessBindings": {
          "methods": {
            "batchUpdate": {
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "description": "Creates an access binding on an account or property."
            },
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "get": {
              "id": "analyticsadmin.accounts.accessBindings.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Gets information about an access binding.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH",
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "httpMethod": "DELETE"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list"
        }
      }
    }
  },
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning."
}
