{
  "discoveryVersion": "v1",
  "servicePath": "",
  "title": "Google Analytics Admin API",
  "ownerDomain": "google.com",
  "canonicalName": "Google Analytics Admin",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "batchPath": "batch",
  "basePath": "",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "revision": "20210916",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns summaries of all accounts accessible by the caller.",
          "httpMethod": "GET",
          "path": "v1alpha/accountSummaries"
        }
      }
    },
    "properties": {
      "methods": {
        "get": {
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates the singleton data retention settings for this property.",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "description": "Updates a property.",
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties",
          "httpMethod": "GET",
          "path": "v1alpha/properties"
        },
        "getGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "description": "Lookup for Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "httpMethod": "GET"
        },
        "getDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1alpha/{+name}"
        },
        "create": {
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "path": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete",
          "path": "v1alpha/{+name}"
        },
        "updateGoogleSignalsSettings": {
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH"
        }
      },
      "resources": {
        "customDimensions": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.get",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions"
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive"
            },
            "create": {
              "description": "Creates a CustomDimension.",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "httpMethod": "PATCH"
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Look up a single DisplayVideo360AdvertiserLink"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            },
            "delete": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "webDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.create",
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret."
                },
                "list": {
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.webDataStreams.measurementProtocolSecrets.get"
                }
              }
            }
          },
          "methods": {
            "delete": {
              "description": "Deletes a web stream on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}"
            },
            "getGlobalSiteTag": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "description": "Lookup for a single WebDataStream",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.webDataStreams.get"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/webDataStreams",
              "id": "analyticsadmin.properties.webDataStreams.list"
            },
            "create": {
              "path": "v1alpha/{+parent}/webDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "description": "Creates a web stream with the specified location and attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams"
            },
            "updateEnhancedMeasurementSettings": {
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "getEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates a web stream on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.webDataStreams.patch"
            }
          }
        },
        "androidAppDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                },
                "patch": {
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.patch",
                  "description": "Updates a measurement protocol secret.",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.get"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.androidAppDataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "path": "v1alpha/{+parent}/androidAppDataStreams"
            },
            "patch": {
              "description": "Updates an android app stream on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single AndroidAppDataStream",
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}"
            },
            "delete": {
              "description": "Deletes an android app stream on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomMetrics on a property.",
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "create": {
              "description": "Creates a CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customMetrics",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals"
            },
            "approve": {
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get"
            },
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            },
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "path": "v1alpha/{+name}:cancel",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "httpMethod": "GET",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "create": {
              "description": "Creates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deletes a conversion event in a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "iosAppDataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret."
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Updates a measurement protocol secret."
                },
                "create": {
                  "id": "analyticsadmin.properties.iosAppDataStreams.measurementProtocolSecrets.create",
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "description": "Updates an iOS app stream on a property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "description": "Lookup for a single IosAppDataStream",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes an iOS app stream on a property.",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.",
              "id": "analyticsadmin.properties.iosAppDataStreams.list",
              "httpMethod": "GET"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink."
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}"
            }
          }
        },
        "userLinks": {
          "methods": {
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.patch",
              "description": "Updates a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink."
            },
            "list": {
              "id": "analyticsadmin.properties.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Lists all user links on an account or property."
            },
            "audit": {
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "id": "analyticsadmin.properties.userLinks.audit"
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property."
            },
            "batchCreate": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchCreate"
            },
            "batchDelete": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property."
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Gets information about a user's link to an account or property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.get",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink."
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            }
          }
        }
      }
    },
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "batchCreate": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "id": "analyticsadmin.accounts.userLinks.batchCreate"
            },
            "patch": {
              "id": "analyticsadmin.accounts.userLinks.patch",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about a user's link to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.accounts.userLinks.get"
            },
            "batchUpdate": {
              "description": "Updates information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "audit": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.create",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink."
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchDelete": {
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Lists all user links on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.list",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "patch": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.patch",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "description": "Updates an account."
        },
        "provisionAccountTicket": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account.",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "getDataSharingSettings": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Get data sharing settings on an account. Data sharing settings are singletons."
        },
        "list": {
          "flatPath": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "path": "v1alpha/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "searchChangeHistoryEvents": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "httpMethod": "POST"
        },
        "get": {
          "id": "analyticsadmin.accounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "GET"
        }
      }
    }
  },
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "ownerName": "Google",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "version": "v1alpha",
  "id": "analyticsadmin:v1alpha",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  },
  "name": "analyticsadmin",
  "description": ""
}
