{
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "servicePath": "",
  "version": "v1alpha",
  "id": "analyticsadmin:v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "revision": "20210508",
  "resources": {
    "accounts": {
      "methods": {
        "searchChangeHistoryEvents": {
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "httpMethod": "POST",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents"
        },
        "getDataSharingSettings": {
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}"
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1alpha/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "provisionAccountTicket": {
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.get",
          "description": "Lookup for a single Account.",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "description": "Updates an account.",
          "flatPath": "v1alpha/accounts/{accountsId}"
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "create": {
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property."
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.get"
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.audit"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property.",
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.list",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accountSummaries"
        }
      }
    },
    "properties": {
      "resources": {
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list"
            },
            "create": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.firebaseLinks.patch",
              "description": "Updates a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "description": "Deletes a FirebaseLink on a property"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1alpha/{+parent}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lookup for a single CustomDimension."
            },
            "patch": {
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "path": "v1alpha/{+name}:archive"
            }
          }
        },
        "androidAppDataStreams": {
          "methods": {
            "get": {
              "description": "Lookup for a single AndroidAppDataStream",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.androidAppDataStreams.get"
            },
            "list": {
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates an android app stream on a property.",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes an android app stream on a property.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "userLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.get",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "GET"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.patch"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.delete",
              "path": "v1alpha/{+name}"
            },
            "audit": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "id": "analyticsadmin.properties.userLinks.audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.userLinks.list",
              "path": "v1alpha/{+parent}/userLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists all user links on an account or property."
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property."
            }
          }
        },
        "webDataStreams": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "path": "v1alpha/{+parent}/webDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "description": "Creates a web stream with the specified location and attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "updateEnhancedMeasurementSettings": {
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "getGlobalSiteTag": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag",
              "path": "v1alpha/{+name}",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.properties.webDataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "description": "Updates a web stream on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a web stream on a property.",
              "id": "analyticsadmin.properties.webDataStreams.delete"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single WebDataStream",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.webDataStreams.get"
            },
            "getEnhancedMeasurementSettings": {
              "httpMethod": "GET",
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "id": "analyticsadmin.properties.webDataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/webDataStreams",
              "httpMethod": "GET",
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found."
            }
          }
        },
        "iosAppDataStreams": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates an iOS app stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.iosAppDataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams"
            },
            "get": {
              "description": "Lookup for a single IosAppDataStream",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.iosAppDataStreams.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.iosAppDataStreams.delete",
              "description": "Deletes an iOS app stream on a property."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a conversion event with the specified attributes.",
              "path": "v1alpha/{+parent}/conversionEvents"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "description": "Retrieve a single conversion event.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deletes a conversion event in a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "archive": {
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "description": "Archives a CustomMetric on a property."
            },
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric."
            },
            "patch": {
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        }
      },
      "methods": {
        "list": {
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1alpha/properties",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "create": {
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "httpMethod": "POST",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties"
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.get"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.patch",
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "description": "Updates a property."
        }
      }
    }
  },
  "protocol": "rest",
  "name": "analyticsadmin",
  "canonicalName": "Google Analytics Admin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "version_module": true,
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "basePath": "",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "description": ""
}
