{
  "ownerDomain": "google.com",
  "basePath": "",
  "revision": "20221205",
  "protocol": "rest",
  "canonicalName": "Google Analytics Admin",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "resources": {
    "properties": {
      "resources": {
        "userLinks": {
          "methods": {
            "audit": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs."
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists all user links on an account or property."
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete"
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "httpMethod": "POST",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate"
            },
            "delete": {
              "id": "analyticsadmin.properties.userLinks.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.get"
            },
            "batchGet": {
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH"
            },
            "create": {
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.create"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchUpdate"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "list": {
              "description": "Lists BigQuery Links on a property.",
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "description": "Lookup for a single BigQuery Link.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Creates a conversion event with the specified attributes.",
              "id": "analyticsadmin.properties.conversionEvents.create"
            },
            "list": {
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "path": "v1alpha/{+parent}/conversionEvents"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deletes a conversion event in a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Retrieve a single conversion event.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.get"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.create"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals."
            },
            "approve": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "httpMethod": "POST",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created."
            },
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "cancel": {
              "httpMethod": "POST",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "path": "v1alpha/{+name}:cancel"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "description": "Lookup for a single CustomDimension.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/customDimensions"
            },
            "archive": {
              "description": "Archives a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "POST",
              "description": "Creates a CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.patch"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DataStream."
            },
            "getGlobalSiteTag": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "description": "Deletes a DataStream on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property.",
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a DataStream.",
              "path": "v1alpha/{+parent}/dataStreams",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET"
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "GET",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "path": "v1alpha/{+name}"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete"
                }
              }
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "path": "v1alpha/{+name}",
              "description": "Look up a single SearchAds360Link",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists all SearchAds360Links on a property."
            },
            "patch": {
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a SearchAds360Link on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a SearchAds360Link.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a SearchAds360Link on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "description": "Updates a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "description": "Deletes a GoogleAdsLink on a property"
            },
            "create": {
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists GoogleAdsLinks on a property."
            }
          }
        },
        "customMetrics": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Creates a CustomMetric.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.create"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch"
            },
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CustomMetric.",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "audiences": {
          "methods": {
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.audiences.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "httpMethod": "POST",
              "description": "Archives an Audience on a property."
            },
            "get": {
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "id": "analyticsadmin.properties.audiences.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.audiences.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "description": "Updates an Audience on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "path": "v1alpha/{+parent}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "POST",
              "description": "Creates an Audience.",
              "id": "analyticsadmin.properties.audiences.create"
            },
            "list": {
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.list",
              "httpMethod": "GET",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions."
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            }
          }
        }
      },
      "methods": {
        "getAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "description": "Lookup for a AttributionSettings singleton.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getDataRetentionSettings": {
          "description": "Returns the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "create": {
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Creates an \"GA4\" property with the specified location and attributes."
        },
        "acknowledgeUserDataCollection": {
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or via this API) before MeasurementProtocolSecret resources may be created.",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection"
        },
        "runAccessReport": {
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST"
        },
        "updateDataRetentionSettings": {
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH"
        },
        "patch": {
          "description": "Updates a property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch"
        },
        "updateAttributionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates attribution settings on a property.",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "httpMethod": "PATCH"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.delete",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1alpha/properties",
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single \"GA4\" Property.",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "path": "v1alpha/{+name}"
        },
        "getGoogleSignalsSettings": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for Google Signals settings for a property."
        },
        "updateGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    },
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Gets information about a user's link to an account or property."
            },
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.patch"
            },
            "batchGet": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "httpMethod": "GET",
              "description": "Gets information about multiple users' links to an account or property."
            },
            "batchCreate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate"
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "httpMethod": "POST"
            },
            "create": {
              "id": "analyticsadmin.accounts.userLinks.create",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "path": "v1alpha/{+parent}/userLinks",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "description": "Lists all user links on an account or property.",
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchDelete": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "audit": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.audit"
            }
          }
        }
      },
      "methods": {
        "patch": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete"
        },
        "provisionAccountTicket": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account."
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+account}:searchChangeHistoryEvents"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        },
        "list": {
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "httpMethod": "GET",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    }
  },
  "id": "analyticsadmin:v1alpha",
  "version_module": true,
  "kind": "discovery#restDescription",
  "version": "v1alpha",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "fullyEncodeReservedExpansion": true,
  "description": "",
  "name": "analyticsadmin",
  "servicePath": "",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "batchPath": "batch"
}
