{
  "name": "analyticsadmin",
  "discoveryVersion": "v1",
  "canonicalName": "Google Analytics Admin",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accountSummaries",
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    },
    "accounts": {
      "methods": {
        "getDataSharingSettings": {
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "get": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.get",
          "description": "Lookup for a single Account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "httpMethod": "DELETE"
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "httpMethod": "POST",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents"
        },
        "provisionAccountTicket": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "list": {
          "flatPath": "v1alpha/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found."
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an account.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.patch",
          "path": "v1alpha/{+name}"
        },
        "runAccessReport": {
          "id": "analyticsadmin.accounts.runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "httpMethod": "POST",
          "path": "v1alpha/{+entity}:runAccessReport"
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "batchGet": {
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate"
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks"
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "httpMethod": "POST",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "id": "analyticsadmin.accounts.userLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.patch"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "description": "Deletes a user link on an account or property."
            },
            "batchDelete": {
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "httpMethod": "POST"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "httpMethod": "POST"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "description": "Gets information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "id": "analyticsadmin.accounts.accessBindings.batchGet"
            },
            "list": {
              "description": "Lists all access bindings on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple access bindings to an account or property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate"
            },
            "batchCreate": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets information about an access binding.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE"
            },
            "batchDelete": {
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "properties": {
      "resources": {
        "audiences": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/audiences",
              "id": "analyticsadmin.properties.audiences.create",
              "description": "Creates an Audience.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.audiences.get",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "archive": {
              "httpMethod": "POST",
              "description": "Archives an Audience on a property.",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "id": "analyticsadmin.properties.audiences.archive"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates an Audience on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.audiences.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "id": "analyticsadmin.properties.audiences.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/audiences",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions."
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists BigQuery Links on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "path": "v1alpha/{+parent}/bigQueryLinks"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single BigQuery Link."
            }
          }
        },
        "userLinks": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a user link on an account or property.",
              "id": "analyticsadmin.properties.userLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "patch": {
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.patch",
              "path": "v1alpha/{+name}"
            },
            "audit": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.properties.userLinks.audit"
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "httpMethod": "GET"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list",
              "description": "Lists all user links on an account or property.",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "id": "analyticsadmin.properties.userLinks.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchDelete": {
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.get",
              "path": "v1alpha/{+name}",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET",
              "description": "Lookup for a single CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create"
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "path": "v1alpha/{+name}:archive"
            },
            "list": {
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customDimensions.patch"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals"
            },
            "list": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list"
            },
            "get": {
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get"
            },
            "approve": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "httpMethod": "POST",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve"
            },
            "cancel": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Creates a SearchAds360Link.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.searchAds360Links.create"
            },
            "delete": {
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a SearchAds360Link on a property."
            },
            "patch": {
              "description": "Updates a SearchAds360Link on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Look up a single SearchAds360Link",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Lists all SearchAds360Links on a property.",
              "httpMethod": "GET"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.create"
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "httpMethod": "GET",
              "description": "Lists all access bindings on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "get": {
              "id": "analyticsadmin.properties.accessBindings.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Gets information about an access binding."
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple access bindings to an account or property.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "id": "analyticsadmin.properties.accessBindings.delete",
              "description": "Deletes an access binding on an account or property.",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchDelete": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create"
            },
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Creates a conversion event with the specified attributes.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Retrieve a single conversion event.",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "description": "Deletes a conversion event in a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get"
            },
            "patch": {
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Lookup for a single ExpandedDataSet.",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a ExpandedDataSet on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.patch"
            },
            "delete": {
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Deletes a ExpandedDataSet on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists ExpandedDataSets on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "description": "Creates a ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.create"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes an AdSenseLink."
            },
            "list": {
              "description": "Lists AdSenseLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.adSenseLinks.list"
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "description": "Looks up a single AdSenseLink."
            },
            "create": {
              "path": "v1alpha/{+parent}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "httpMethod": "POST",
              "description": "Creates an AdSenseLink."
            }
          }
        },
        "channelGroups": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.channelGroups.get",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ChannelGroup.",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.patch"
            },
            "delete": {
              "id": "analyticsadmin.properties.channelGroups.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "create": {
              "path": "v1alpha/{+parent}/channelGroups",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a ChannelGroup.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.channelGroups.create"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Lists ChannelGroups on a property.",
              "id": "analyticsadmin.properties.channelGroups.list",
              "httpMethod": "GET"
            }
          }
        },
        "dataStreams": {
          "resources": {
            "eventCreateRules": {
              "methods": {
                "list": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "httpMethod": "GET",
                  "description": "Lists EventCreateRules on a web data stream.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "patch": {
                  "description": "Updates an EventCreateRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "PATCH"
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "description": "Lookup for a single EventCreateRule.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "description": "Deletes an EventCreateRule.",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "httpMethod": "POST",
                  "description": "Creates an EventCreateRule.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create"
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "path": "v1alpha/{+name}"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch"
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            }
          },
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DataStream on a property.",
              "httpMethod": "DELETE"
            },
            "get": {
              "id": "analyticsadmin.properties.dataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "path": "v1alpha/{+parent}/dataStreams",
              "httpMethod": "POST",
              "description": "Creates a DataStream."
            },
            "patch": {
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            },
            "updateEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH"
            },
            "list": {
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "getEnhancedMeasurementSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "GET",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}"
            },
            "getGlobalSiteTag": {
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "httpMethod": "GET"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "description": "Updates a CustomMetric on a property."
            },
            "create": {
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomMetric."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}"
            }
          }
        }
      },
      "methods": {
        "runAccessReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "updateDataRetentionSettings": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings"
        },
        "deleteConnectedSiteTag": {
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "httpMethod": "POST",
          "path": "v1alpha/properties:deleteConnectedSiteTag"
        },
        "createConnectedSiteTag": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:createConnectedSiteTag",
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties.",
          "path": "v1alpha/properties:createConnectedSiteTag",
          "httpMethod": "POST"
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "path": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "listConnectedSiteTags": {
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property.",
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties:listConnectedSiteTags",
          "id": "analyticsadmin.properties.listConnectedSiteTags",
          "httpMethod": "POST"
        },
        "updateGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "description": "Updates Google Signals settings for a property."
        },
        "get": {
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lookup for a AttributionSettings singleton."
        },
        "acknowledgeUserDataCollection": {
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.create",
          "path": "v1alpha/properties"
        },
        "delete": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete",
          "path": "v1alpha/{+name}"
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property."
        },
        "patch": {
          "path": "v1alpha/{+name}",
          "description": "Updates a property.",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "updateAttributionSettings": {
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates attribution settings on a property."
        },
        "getGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "description": "Lookup for Google Signals settings for a property."
        },
        "fetchConnectedGa4Property": {
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "httpMethod": "GET"
        },
        "getDataRetentionSettings": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property."
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property."
        }
      }
    }
  },
  "servicePath": "",
  "batchPath": "batch",
  "version": "v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  },
  "version_module": true,
  "id": "analyticsadmin:v1alpha",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "description": "",
  "ownerDomain": "google.com",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "title": "Google Analytics Admin API",
  "protocol": "rest",
  "basePath": "",
  "revision": "20230622"
}
