{
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "title": "Google Analytics Admin API",
  "version": "v1beta",
  "description": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "name": "analyticsadmin",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "basePath": "",
  "protocol": "rest",
  "servicePath": "",
  "id": "analyticsadmin:v1beta",
  "ownerName": "Google",
  "resources": {
    "accounts": {
      "methods": {
        "getDataSharingSettings": {
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "path": "v1beta/{+name}",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons."
        },
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.accounts.runAccessReport"
        },
        "patch": {
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates an account."
        },
        "provisionAccountTicket": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "path": "v1beta/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "delete": {
          "id": "analyticsadmin.accounts.delete",
          "path": "v1beta/{+name}",
          "httpMethod": "DELETE",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1beta/accounts",
          "path": "v1beta/accounts"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1beta/accounts/{accountsId}",
          "path": "v1beta/{+name}"
        },
        "searchChangeHistoryEvents": {
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents"
        }
      }
    },
    "properties": {
      "methods": {
        "patch": {
          "description": "Updates a property.",
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}"
        },
        "acknowledgeUserDataCollection": {
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport"
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property."
        },
        "create": {
          "path": "v1beta/properties",
          "id": "analyticsadmin.properties.create",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.delete",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "httpMethod": "DELETE",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1beta/properties",
          "path": "v1beta/properties",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "get": {
          "id": "analyticsadmin.properties.get",
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single \"GA4\" Property."
        },
        "updateDataRetentionSettings": {
          "description": "Updates the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH"
        }
      },
      "resources": {
        "conversionEvents": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "httpMethod": "GET",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1beta/{+parent}/conversionEvents"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1beta/{+name}",
              "description": "Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get"
            },
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "httpMethod": "DELETE"
            },
            "create": {
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.create",
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "POST"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch",
              "description": "Updates a DataStream on a property.",
              "path": "v1beta/{+name}"
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get",
              "description": "Lookup for a single DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "path": "v1beta/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list",
              "description": "Lists DataStreams on a property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams"
            },
            "delete": {
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Deletes a DataStream on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/dataStreams",
              "description": "Creates a DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "description": "Creates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+name}",
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                }
              }
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1beta/{+name}:archive",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric.",
              "path": "v1beta/{+parent}/customMetrics",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Updates a CustomMetric on a property.",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "httpMethod": "PATCH"
            },
            "list": {
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property."
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "path": "v1beta/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks"
            },
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property",
              "httpMethod": "DELETE",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}"
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "path": "v1beta/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single CustomDimension."
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "path": "v1beta/{+parent}/customDimensions"
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "path": "v1beta/{+name}:archive"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "path": "v1beta/{+name}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create",
              "description": "Creates a CustomDimension."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.create"
            },
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1beta/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/accountSummaries",
          "flatPath": "v1beta/accountSummaries",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    }
  },
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "canonicalName": "Google Analytics Admin",
  "version_module": true,
  "revision": "20230410",
  "rootUrl": "https://analyticsadmin.googleapis.com/"
}
