{
  "id": "analyticsadmin:v1alpha",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "discoveryVersion": "v1",
  "basePath": "",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "batchPath": "batch",
  "revision": "20220625",
  "version": "v1alpha",
  "title": "Google Analytics Admin API",
  "description": "",
  "kind": "discovery#restDescription",
  "version_module": true,
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "fullyEncodeReservedExpansion": true,
  "name": "analyticsadmin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "servicePath": "",
  "canonicalName": "Google Analytics Admin",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "properties": {
      "resources": {
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "POST",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal."
            },
            "cancel": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "path": "v1alpha/{+name}:cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "httpMethod": "POST"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "GET",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "httpMethod": "GET"
            },
            "approve": {
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve"
            }
          }
        },
        "userLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.delete"
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.get"
            },
            "batchGet": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet"
            },
            "batchDelete": {
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "httpMethod": "POST"
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Lists all user links on an account or property."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.userLinks.patch",
              "description": "Updates a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.userLinks.create",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks"
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.audit"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "httpMethod": "POST"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property."
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE"
            }
          }
        },
        "dataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete"
                },
                "get": {
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.dataStreams.patch"
            },
            "delete": {
              "id": "analyticsadmin.properties.dataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DataStream on a property."
            },
            "list": {
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "create": {
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "httpMethod": "POST",
              "description": "Creates a DataStream.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "getGlobalSiteTag": {
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.create",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Creates a CustomDimension."
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET",
              "description": "Lists CustomDimensions on a property."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a conversion event in a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Retrieve a single conversion event.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Creates a conversion event with the specified attributes."
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Archives a CustomMetric on a property.",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive"
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric.",
              "path": "v1alpha/{+parent}/customMetrics",
              "httpMethod": "POST"
            },
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "description": "Lookup for a single CustomMetric.",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a CustomMetric on a property.",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink."
            },
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink."
            }
          }
        }
      },
      "methods": {
        "updateAttributionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "description": "Updates attribution settings on a property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        },
        "getAttributionSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a AttributionSettings singleton.",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getAttributionSettings"
        },
        "getGoogleSignalsSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lookup for Google Signals settings for a property.",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "patch": {
          "id": "analyticsadmin.properties.patch",
          "httpMethod": "PATCH",
          "description": "Updates a property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "runAccessReport": {
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "httpMethod": "POST",
          "path": "v1alpha/{+entity}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport"
        },
        "acknowledgeUserDataCollection": {
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or via this API) before MeasurementProtocolSecret resources may be created.",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST"
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns the singleton data retention settings for this property."
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete"
        },
        "updateGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET"
        },
        "create": {
          "flatPath": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "httpMethod": "POST"
        },
        "updateDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "description": "Updates the singleton data retention settings for this property."
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accountSummaries.list",
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    },
    "accounts": {
      "methods": {
        "getDataSharingSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "list": {
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1alpha/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list"
        },
        "searchChangeHistoryEvents": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents"
        },
        "get": {
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "path": "v1alpha/{+name}"
        },
        "patch": {
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates an account.",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH"
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      },
      "resources": {
        "userLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.userLinks.list",
              "description": "Lists all user links on an account or property.",
              "path": "v1alpha/{+parent}/userLinks"
            },
            "delete": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.get",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple users' links to an account or property."
            },
            "batchUpdate": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "httpMethod": "POST"
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.create"
            },
            "patch": {
              "id": "analyticsadmin.accounts.userLinks.patch",
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}"
            },
            "audit": {
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:audit",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "httpMethod": "POST"
            },
            "batchCreate": {
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  }
}
