{
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "resources": {
    "properties": {
      "resources": {
        "expandedDataSets": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "description": "Creates a ExpandedDataSet.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/expandedDataSets"
            },
            "list": {
              "description": "Lists ExpandedDataSets on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/expandedDataSets"
            },
            "get": {
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "description": "Lookup for a single ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a ExpandedDataSet on a property."
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "description": "Updates a ExpandedDataSet on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}"
            }
          }
        },
        "audiences": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.get"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Creates an Audience.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.create",
              "path": "v1alpha/{+parent}/audiences"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "path": "v1alpha/{+parent}/audiences",
              "id": "analyticsadmin.properties.audiences.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "description": "Updates an Audience on a property.",
              "id": "analyticsadmin.properties.audiences.patch",
              "httpMethod": "PATCH"
            },
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "id": "analyticsadmin.properties.audiences.archive",
              "description": "Archives an Audience on a property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "description": "Looks up a single AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes an AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "description": "Creates an AdSenseLink."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/adSenseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "description": "Lists AdSenseLinks on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.adSenseLinks.list"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "description": "Lists BigQuery Links on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.list"
            },
            "get": {
              "description": "Lookup for a single BigQuery Link.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Look up a single SearchAds360Link",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "create": {
              "description": "Creates a SearchAds360Link.",
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a SearchAds360Link on a property.",
              "httpMethod": "DELETE"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a SearchAds360Link on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.patch"
            },
            "list": {
              "description": "Lists all SearchAds360Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property"
            },
            "list": {
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.create"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Look up a single DisplayVideo360AdvertiserLink"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DisplayVideo360AdvertiserLink on a property."
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list"
            },
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "httpMethod": "DELETE"
            }
          }
        },
        "conversionEvents": {
          "deprecated": true,
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "deprecated": true,
              "path": "v1alpha/{+parent}/conversionEvents"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "description": "Deletes a conversion event in a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete"
            },
            "list": {
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "httpMethod": "GET",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "description": "Retrieve a single conversion event.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "description": "Updates a conversion event with the specified attributes.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "delete": {
              "description": "Deletes a CalculatedMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "id": "analyticsadmin.properties.calculatedMetrics.delete"
            },
            "create": {
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "description": "Creates a CalculatedMetric.",
              "httpMethod": "POST"
            },
            "list": {
              "description": "Lists CalculatedMetrics on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/calculatedMetrics"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CalculatedMetric.",
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "description": "Updates a CalculatedMetric on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "channelGroups": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.channelGroups.list",
              "description": "Lists ChannelGroups on a property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "path": "v1alpha/{+parent}/channelGroups"
            },
            "get": {
              "id": "analyticsadmin.properties.channelGroups.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single ChannelGroup.",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "description": "Creates a ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/channelGroups",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "description": "Updates a ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH"
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "get": {
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}"
            },
            "list": {
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:cancel"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "approve": {
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "customMetrics": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "description": "Archives a CustomMetric on a property.",
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "create": {
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "description": "Creates a GoogleAdsLink.",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create"
            },
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.list"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customDimensions.patch"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            },
            "patch": {
              "description": "Updates an access binding on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "httpMethod": "PATCH"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings"
            },
            "get": {
              "description": "Gets information about an access binding.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE"
            },
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet"
            },
            "batchCreate": {
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "id": "analyticsadmin.properties.accessBindings.batchCreate"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.create",
              "description": "Creates an access binding on an account or property."
            },
            "batchUpdate": {
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple access bindings to an account or property."
            }
          }
        },
        "keyEvents": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.keyEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Retrieve a single Key Event."
            },
            "delete": {
              "description": "Deletes a Key Event.",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.delete"
            },
            "create": {
              "id": "analyticsadmin.properties.keyEvents.create",
              "description": "Creates a Key Event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "path": "v1alpha/{+parent}/keyEvents",
              "httpMethod": "POST"
            },
            "list": {
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "id": "analyticsadmin.properties.keyEvents.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/keyEvents"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.keyEvents.patch",
              "httpMethod": "PATCH",
              "description": "Updates a Key Event."
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "create": {
              "description": "Creates a subproperty Event Filter.",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "httpMethod": "POST"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a subproperty event filter.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "description": "Lookup for a single subproperty Event Filter.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}"
            },
            "patch": {
              "description": "Updates a subproperty Event Filter.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "id": "analyticsadmin.properties.subpropertyEventFilters.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "description": "List all subproperty Event Filters on a property."
            }
          }
        },
        "dataStreams": {
          "resources": {
            "eventCreateRules": {
              "methods": {
                "delete": {
                  "path": "v1alpha/{+name}",
                  "description": "Deletes an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "description": "Creates an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "description": "Lookup for a single EventCreateRule."
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "path": "v1alpha/{+name}",
                  "description": "Updates an EventCreateRule."
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "description": "Lists EventCreateRules on a web data stream."
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            },
            "eventEditRules": {
              "methods": {
                "reorder": {
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder",
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "path": "v1alpha/{+parent}/eventEditRules:reorder",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder"
                }
              }
            },
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "list": {
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema.",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create"
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema."
                }
              }
            }
          },
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a DataStream on a property."
            },
            "getDataRedactionSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single DataRedactionSettings."
            },
            "getEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "httpMethod": "GET"
            },
            "create": {
              "description": "Creates a DataStream.",
              "path": "v1alpha/{+parent}/dataStreams",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams"
            },
            "updateDataRedactionSettings": {
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataRedactionSettings on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists DataStreams on a property."
            },
            "getGlobalSiteTag": {
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Lookup for a single DataStream."
            },
            "updateEnhancedMeasurementSettings": {
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        }
      },
      "methods": {
        "getAttributionSettings": {
          "description": "Lookup for a AttributionSettings singleton.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "id": "analyticsadmin.properties.getAttributionSettings"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Lookup for a single \"GA4\" Property.",
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "runAccessReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA4 UI [...]"
        },
        "create": {
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create"
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not[...]",
          "id": "analyticsadmin.properties.delete"
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property."
        },
        "listConnectedSiteTags": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.listConnectedSiteTags",
          "path": "v1alpha/properties:listConnectedSiteTags",
          "flatPath": "v1alpha/properties:listConnectedSiteTags"
        },
        "getDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings"
        },
        "updateAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates attribution settings on a property."
        },
        "createRollupProperty": {
          "description": "Create a roll-up property and all roll-up property source links.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:createRollupProperty",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:createRollupProperty",
          "id": "analyticsadmin.properties.createRollupProperty"
        },
        "createSubproperty": {
          "path": "v1alpha/properties:createSubproperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createSubproperty",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:createSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty."
        },
        "fetchConnectedGa4Property": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties.",
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property"
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1alpha/properties",
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "getGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "httpMethod": "GET",
          "description": "Lookup for Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}"
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}"
        },
        "acknowledgeUserDataCollection": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection"
        },
        "updateGoogleSignalsSettings": {
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "deleteConnectedSiteTag": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:deleteConnectedSiteTag",
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.deleteConnectedSiteTag",
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties."
        },
        "createConnectedSiteTag": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:createConnectedSiteTag",
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:createConnectedSiteTag",
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties."
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1alpha/accounts"
        },
        "searchChangeHistoryEvents": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents"
        },
        "getDataSharingSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1alpha/{+name}",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete"
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts:provisionAccountTicket"
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA4 UI [...]",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.runAccessReport",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}"
        }
      },
      "resources": {
        "accessBindings": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes an access binding on an account or property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "batchCreate": {
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate"
            },
            "get": {
              "id": "analyticsadmin.accounts.accessBindings.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding."
            },
            "patch": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all access bindings on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "batchGet": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "description": "Gets information about multiple access bindings to an account or property."
            },
            "batchDelete": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            }
          }
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "basePath": "",
  "name": "analyticsadmin",
  "ownerDomain": "google.com",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "canonicalName": "Google Analytics Admin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "batchPath": "batch",
  "version_module": true,
  "ownerName": "Google",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "id": "analyticsadmin:v1alpha",
  "protocol": "rest",
  "revision": "20240529",
  "version": "v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "title": "Google Analytics Admin API"
}
