{
  "protocol": "rest",
  "ownerName": "Google",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "basePath": "",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "canonicalName": "Google Analytics Admin",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "version": "v1alpha",
  "ownerDomain": "google.com",
  "description": "",
  "id": "analyticsadmin:v1alpha",
  "version_module": true,
  "servicePath": "",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "name": "analyticsadmin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "discoveryVersion": "v1",
  "title": "Google Analytics Admin API",
  "resources": {
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "patch": {
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "description": "Lists all user links on an account or property."
            },
            "batchDelete": {
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchDelete"
            },
            "get": {
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "description": "Updates information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Deletes a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "audit": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.accounts.userLinks.audit"
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "id": "analyticsadmin.accounts.userLinks.batchCreate"
            },
            "create": {
              "path": "v1alpha/{+parent}/userLinks",
              "httpMethod": "POST",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.create"
            },
            "batchGet": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet"
            }
          }
        }
      },
      "methods": {
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.patch",
          "path": "v1alpha/{+name}",
          "description": "Updates an account."
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents"
        },
        "list": {
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list",
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "provisionAccountTicket": {
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "get": {
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Lookup for a single Account."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        }
      }
    },
    "properties": {
      "resources": {
        "firebaseLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1alpha/{+parent}/firebaseLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "description": "Deletes a FirebaseLink on a property"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "POST"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete"
            },
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "path": "v1alpha/{+name}:cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "approve": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property."
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "description": "Creates a conversion event with the specified attributes.",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET"
            },
            "list": {
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.conversionEvents.list",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deletes a conversion event in a property."
            }
          }
        },
        "dataStreams": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Creates a DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/dataStreams"
            },
            "patch": {
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a DataStream on a property."
            },
            "getGlobalSiteTag": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag"
            },
            "list": {
              "description": "Lists DataStreams on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "delete": {
              "description": "Deletes a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "DELETE"
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "get": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch"
                },
                "list": {
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "create": {
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            },
            "patch": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Look up a single DisplayVideo360AdvertiserLink"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET"
            },
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive"
            },
            "create": {
              "description": "Creates a CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customMetrics",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics"
            }
          }
        },
        "userLinks": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.properties.userLinks.create",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchGet": {
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET"
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property.",
              "id": "analyticsadmin.properties.userLinks.patch"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "id": "analyticsadmin.properties.userLinks.audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit"
            },
            "delete": {
              "id": "analyticsadmin.properties.userLinks.delete",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchDelete": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete"
            },
            "list": {
              "description": "Lists all user links on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.userLinks.list",
              "path": "v1alpha/{+parent}/userLinks"
            },
            "get": {
              "description": "Gets information about a user's link to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.userLinks.get"
            }
          }
        },
        "audiences": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.get",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates an Audience on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.audiences.patch"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "id": "analyticsadmin.properties.audiences.list",
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Creates an Audience.",
              "id": "analyticsadmin.properties.audiences.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/audiences"
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives an Audience on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "id": "analyticsadmin.properties.audiences.archive"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.get"
            },
            "archive": {
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.archive"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a CustomDimension on a property.",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "description": "Lists CustomDimensions on a property.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists GoogleAdsLinks on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "create": {
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "description": "Updates a GoogleAdsLink on a property"
            },
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        }
      },
      "methods": {
        "runAccessReport": {
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport",
          "httpMethod": "POST"
        },
        "getDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "httpMethod": "GET",
          "description": "Returns the singleton data retention settings for this property."
        },
        "patch": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.patch",
          "httpMethod": "PATCH",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}"
        },
        "getAttributionSettings": {
          "description": "Lookup for a AttributionSettings singleton.",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/{+name}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "getGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lookup for Google Signals settings for a property.",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}"
        },
        "updateDataRetentionSettings": {
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "PATCH"
        },
        "create": {
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties",
          "path": "v1alpha/properties"
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.get"
        },
        "acknowledgeUserDataCollection": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or via this API) before MeasurementProtocolSecret resources may be created.",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection"
        },
        "updateAttributionSettings": {
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "description": "Updates attribution settings on a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}"
        },
        "updateGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an G[...]"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accountSummaries",
          "path": "v1alpha/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "revision": "20220825",
  "batchPath": "batch",
  "kind": "discovery#restDescription"
}
