{
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        }
      }
    }
  },
  "description": "Accesses report data in Google Analytics.",
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://analyticsdata.googleapis.com/",
  "title": "Google Analytics Data API",
  "servicePath": "",
  "version_module": true,
  "ownerName": "Google",
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "id": "analyticsdata:v1beta",
  "kind": "discovery#restDescription",
  "revision": "20221210",
  "version": "v1beta",
  "canonicalName": "AnalyticsData",
  "fullyEncodeReservedExpansion": true,
  "name": "analyticsdata",
  "ownerDomain": "google.com",
  "resources": {
    "properties": {
      "methods": {
        "getMetadata": {
          "path": "v1beta/{+name}",
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics GA4 Property Identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. Univer[...]",
          "httpMethod": "GET",
          "id": "analyticsdata.properties.getMetadata",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}/metadata"
        },
        "batchRunPivotReports": {
          "httpMethod": "POST",
          "id": "analyticsdata.properties.batchRunPivotReports",
          "description": "Returns multiple pivot reports in a batch. All reports must be for the same GA4 Property.",
          "path": "v1beta/{+property}:batchRunPivotReports",
          "flatPath": "v1beta/properties/{propertiesId}:batchRunPivotReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "runReport": {
          "flatPath": "v1beta/properties/{propertiesId}:runReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "path": "v1beta/{+property}:runReport",
          "id": "analyticsdata.properties.runReport",
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name. For a guide to co[...]"
        },
        "batchRunReports": {
          "flatPath": "v1beta/properties/{propertiesId}:batchRunReports",
          "id": "analyticsdata.properties.batchRunReports",
          "httpMethod": "POST",
          "description": "Returns multiple reports in a batch. All reports must be for the same GA4 Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+property}:batchRunReports"
        },
        "runRealtimeReport": {
          "path": "v1beta/{+property}:runRealtimeReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "description": "Returns a customized report of realtime event data for your property. Events appear in realtime reports seconds after they have been sent to the Google Analytics. Realtime reports show events and usage data for the periods of time ranging from the present moment to 30 minutes ago (up to 60 minutes for Google Analytics 360 properties). For a guide to constructing realtime requests & understanding responses, see [Creating a Realtime Report](https://developers.google.com/a[...]",
          "id": "analyticsdata.properties.runRealtimeReport",
          "flatPath": "v1beta/properties/{propertiesId}:runRealtimeReport"
        },
        "runPivotReport": {
          "httpMethod": "POST",
          "path": "v1beta/{+property}:runPivotReport",
          "id": "analyticsdata.properties.runPivotReport",
          "description": "Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data.",
          "flatPath": "v1beta/properties/{propertiesId}:runPivotReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "checkCompatibility": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}:checkCompatibility",
          "path": "v1beta/{+property}:checkCompatibility",
          "id": "analyticsdata.properties.checkCompatibility",
          "description": "This compatibility method lists dimensions and metrics that can be added to a report request and maintain compatibility. This method fails if the request's dimensions and metrics are incompatible. In Google Analytics, reports fail if they request incompatible dimensions and/or metrics; in that case, you will need to remove dimensions and/or metrics from the incompatible report until the report is compatible. The Realtime and Core reports have different compatibility rul[...]",
          "httpMethod": "POST"
        }
      }
    }
  },
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/analytics/devguides/reporting/data/v1/",
  "batchPath": "batch"
}
