{
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "description": "",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "version_module": true,
  "ownerDomain": "google.com",
  "revision": "20230612",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "canonicalName": "Google Analytics Admin",
  "fullyEncodeReservedExpansion": true,
  "name": "analyticsadmin",
  "resources": {
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete"
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "patch": {
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.patch"
            },
            "create": {
              "id": "analyticsadmin.accounts.userLinks.create",
              "httpMethod": "POST",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "get": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.userLinks.get",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "delete": {
              "description": "Deletes a user link on an account or property.",
              "id": "analyticsadmin.accounts.userLinks.delete",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}"
            },
            "audit": {
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all user links on an account or property.",
              "path": "v1alpha/{+parent}/userLinks",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "id": "analyticsadmin.accounts.userLinks.list",
              "httpMethod": "GET"
            },
            "batchUpdate": {
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property."
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchDelete": {
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "patch": {
              "description": "Updates an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchCreate": {
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.create"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.accounts.accessBindings.get",
              "description": "Gets information about an access binding.",
              "path": "v1alpha/{+name}"
            },
            "batchGet": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "httpMethod": "GET",
              "description": "Gets information about multiple access bindings to an account or property."
            },
            "batchUpdate": {
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "DELETE"
            }
          }
        }
      },
      "methods": {
        "runAccessReport": {
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.accounts.runAccessReport"
        },
        "provisionAccountTicket": {
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "httpMethod": "POST"
        },
        "getDataSharingSettings": {
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an account.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch"
        },
        "list": {
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "flatPath": "v1alpha/accounts"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "GET"
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters."
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "id": "analyticsadmin.accounts.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "flatPath": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "createConnectedSiteTag": {
          "id": "analyticsadmin.properties.createConnectedSiteTag",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:createConnectedSiteTag",
          "description": "Creates a connected site tag for a Universal Analytics property. You can create a maximum of 20 connected site tags per property. Note: This API cannot be used on GA4 properties.",
          "httpMethod": "POST",
          "path": "v1alpha/properties:createConnectedSiteTag"
        },
        "getGoogleSignalsSettings": {
          "description": "Lookup for Google Signals settings for a property.",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "id": "analyticsadmin.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "setAutomatedGa4ConfigurationOptOut": {
          "description": "Sets the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "id": "analyticsadmin.properties.setAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "path": "v1alpha/properties:setAutomatedGa4ConfigurationOptOut",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "deleteConnectedSiteTag": {
          "httpMethod": "POST",
          "path": "v1alpha/properties:deleteConnectedSiteTag",
          "flatPath": "v1alpha/properties:deleteConnectedSiteTag",
          "description": "Deletes a connected site tag for a Universal Analytics property. Note: this has no effect on GA4 properties.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.deleteConnectedSiteTag"
        },
        "get": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single \"GA4\" Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}"
        },
        "updateDataRetentionSettings": {
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "fetchConnectedGa4Property": {
          "flatPath": "v1alpha/properties:fetchConnectedGa4Property",
          "path": "v1alpha/properties:fetchConnectedGa4Property",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.fetchConnectedGa4Property",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Given a specified UA property, looks up the GA4 property connected to it. Note: this cannot be used with GA4 properties."
        },
        "updateAttributionSettings": {
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "description": "Updates attribution settings on a property.",
          "httpMethod": "PATCH"
        },
        "updateGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}"
        },
        "create": {
          "flatPath": "v1alpha/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.create"
        },
        "acknowledgeUserDataCollection": {
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "listConnectedSiteTags": {
          "id": "analyticsadmin.properties.listConnectedSiteTags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties:listConnectedSiteTags",
          "description": "Lists the connected site tags for a Universal Analytics property. A maximum of 20 connected site tags will be returned. Note: this has no effect on GA4 property.",
          "path": "v1alpha/properties:listConnectedSiteTags"
        },
        "getDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1alpha/{+name}"
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties"
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. The property must be in Google Analytics 360. This method is only available to Administrators. These data access records include GA4 UI Reporting, GA4 UI Explorations, GA4 Data API, and other products like Firebase & Admob that can ret[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getAttributionSettings": {
          "id": "analyticsadmin.properties.getAttributionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a AttributionSettings singleton."
        },
        "fetchAutomatedGa4ConfigurationOptOut": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.fetchAutomatedGa4ConfigurationOptOut",
          "flatPath": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut",
          "httpMethod": "POST",
          "description": "Fetches the opt out status for the automated GA4 setup process for a UA property. Note: this has no effect on GA4 property.",
          "path": "v1alpha/properties:fetchAutomatedGa4ConfigurationOptOut"
        }
      },
      "resources": {
        "bigQueryLinks": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "description": "Lookup for a single BigQuery Link.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "description": "Lists BigQuery Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.bigQueryLinks.list"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.get"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "userLinks": {
          "methods": {
            "batchDelete": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.userLinks.delete",
              "httpMethod": "DELETE"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate",
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.create",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "httpMethod": "POST"
            },
            "audit": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "path": "v1alpha/{+parent}/userLinks:audit",
              "id": "analyticsadmin.properties.userLinks.audit",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.userLinks.get",
              "description": "Gets information about a user's link to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list",
              "description": "Lists all user links on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchGet": {
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "patch": {
              "description": "Updates a user link on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.patch"
            },
            "batchCreate": {
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "id": "analyticsadmin.properties.userLinks.batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "create": {
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "GET"
            },
            "list": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "patch": {
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            },
            "delete": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property."
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "description": "Lookup for a single ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Deletes a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a ExpandedDataSet.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "httpMethod": "PATCH",
              "description": "Updates a ExpandedDataSet on a property."
            },
            "list": {
              "description": "Lists ExpandedDataSets on a property.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "id": "analyticsadmin.properties.conversionEvents.list"
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "description": "Retrieve a single conversion event.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a conversion event with the specified attributes.",
              "httpMethod": "POST"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a conversion event in a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchGet": {
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets information about an access binding.",
              "id": "analyticsadmin.properties.accessBindings.get",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}"
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "httpMethod": "POST"
            },
            "patch": {
              "description": "Updates an access binding on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.accessBindings.patch"
            },
            "list": {
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.accessBindings.create",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property."
            },
            "batchDelete": {
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete"
            },
            "delete": {
              "description": "Deletes an access binding on an account or property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/searchAds360Links",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists all SearchAds360Links on a property."
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "description": "Deletes a SearchAds360Link on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Look up a single SearchAds360Link",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.get"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "description": "Creates a SearchAds360Link.",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/searchAds360Links"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a SearchAds360Link on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "GET",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "getEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "GET",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a DataStream on a property.",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "getGlobalSiteTag": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get",
              "description": "Lookup for a single DataStream."
            },
            "updateEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Creates a DataStream.",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/dataStreams",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.list",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Lists DataStreams on a property."
            }
          },
          "resources": {
            "eventCreateRules": {
              "methods": {
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates an EventCreateRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes an EventCreateRule."
                },
                "list": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "description": "Lists EventCreateRules on a web data stream.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "create": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "description": "Creates an EventCreateRule.",
                  "httpMethod": "POST"
                },
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get"
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST"
                },
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Updates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                }
              }
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get"
            },
            "approve": {
              "path": "v1alpha/{+name}:approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve"
            },
            "cancel": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "path": "v1alpha/{+name}:cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically."
            },
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "channelGroups": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.create",
              "description": "Creates a ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "description": "Updates a ChannelGroup.",
              "httpMethod": "PATCH"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists ChannelGroups on a property.",
              "id": "analyticsadmin.properties.channelGroups.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "path": "v1alpha/{+parent}/channelGroups"
            },
            "delete": {
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "get": {
              "id": "analyticsadmin.properties.channelGroups.get",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ChannelGroup."
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "create": {
              "description": "Creates an AdSenseLink.",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "httpMethod": "POST"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes an AdSenseLink.",
              "id": "analyticsadmin.properties.adSenseLinks.delete"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "description": "Lists AdSenseLinks on a property.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/adSenseLinks"
            },
            "get": {
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "httpMethod": "GET",
              "description": "Looks up a single AdSenseLink."
            }
          }
        },
        "audiences": {
          "methods": {
            "create": {
              "description": "Creates an Audience.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.audiences.get",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions."
            },
            "archive": {
              "description": "Archives an Audience on a property.",
              "id": "analyticsadmin.properties.audiences.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "path": "v1alpha/{+parent}/audiences",
              "id": "analyticsadmin.properties.audiences.list"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST",
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions",
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Lookup for a single CustomDimension.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property.",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "description": "Lists GoogleAdsLinks on a property."
            }
          }
        }
      }
    }
  },
  "basePath": "",
  "id": "analyticsadmin:v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "title": "Google Analytics Admin API",
  "batchPath": "batch",
  "version": "v1alpha",
  "servicePath": "",
  "ownerName": "Google",
  "protocol": "rest"
}
