{
  "ownerDomain": "google.com",
  "kind": "discovery#restDescription",
  "canonicalName": "Bigtable Admin",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "documentationLink": "https://cloud.google.com/bigtable/",
  "version_module": true,
  "batchPath": "batch",
  "ownerName": "Google",
  "id": "bigtableadmin:v2",
  "revision": "20230824",
  "rootUrl": "https://bigtableadmin.googleapis.com/",
  "mtlsRootUrl": "https://bigtableadmin.mtls.googleapis.com/",
  "resources": {
    "operations": {
      "methods": {
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "httpMethod": "POST",
          "path": "v2/{+name}:cancel",
          "flatPath": "v2/operations/{operationsId}:cancel",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "bigtableadmin.operations.cancel"
        },
        "get": {
          "id": "bigtableadmin.operations.get",
          "path": "v2/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "flatPath": "v2/operations/{operationsId}",
          "httpMethod": "GET"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v2/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v2/{+name}",
          "id": "bigtableadmin.operations.delete"
        }
      },
      "resources": {
        "projects": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v2/{+name}/operations",
                  "flatPath": "v2/operations/projects/{projectsId}/operations",
                  "httpMethod": "GET",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "id": "bigtableadmin.operations.projects.operations.list"
                }
              }
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "instances": {
          "resources": {
            "appProfiles": {
              "methods": {
                "create": {
                  "path": "v2/{+parent}/appProfiles",
                  "id": "bigtableadmin.projects.instances.appProfiles.create",
                  "description": "Creates an app profile within an instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes an app profile from an instance.",
                  "id": "bigtableadmin.projects.instances.appProfiles.delete",
                  "path": "v2/{+name}",
                  "httpMethod": "DELETE",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}"
                },
                "patch": {
                  "description": "Updates an app profile within an instance.",
                  "httpMethod": "PATCH",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "id": "bigtableadmin.projects.instances.appProfiles.patch"
                },
                "list": {
                  "path": "v2/{+parent}/appProfiles",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.appProfiles.list",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "description": "Lists information about app profiles in an instance.",
                  "httpMethod": "GET"
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Gets information about an app profile.",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "id": "bigtableadmin.projects.instances.appProfiles.get"
                }
              }
            },
            "tables": {
              "methods": {
                "undelete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:undelete",
                  "description": "Restores a specified table which was accidentally deleted.",
                  "path": "v2/{+name}:undelete",
                  "id": "bigtableadmin.projects.instances.tables.undelete",
                  "httpMethod": "POST"
                },
                "restore": {
                  "description": "Create a new table by restoring from a completed backup. The returned table long-running operation can be used to track the progress of the operation, and to cancel it. The metadata field type is RestoreTableMetadata. The response type is Table, if successful.",
                  "path": "v2/{+parent}/tables:restore",
                  "id": "bigtableadmin.projects.instances.tables.restore",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables:restore",
                  "httpMethod": "POST"
                },
                "checkConsistency": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:checkConsistency",
                  "httpMethod": "POST",
                  "description": "Checks replication consistency based on a consistency token, that is, if replication has caught up based on the conditions specified in the token and the check request.",
                  "path": "v2/{+name}:checkConsistency",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.checkConsistency"
                },
                "getIamPolicy": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:getIamPolicy",
                  "id": "bigtableadmin.projects.instances.tables.getIamPolicy",
                  "description": "Gets the access control policy for a Table or Backup resource. Returns an empty policy if the resource exists but does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+resource}:getIamPolicy",
                  "httpMethod": "POST"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+parent}/tables",
                  "id": "bigtableadmin.projects.instances.tables.create",
                  "httpMethod": "POST",
                  "description": "Creates a new table in the specified instance. The table can be created with a full set of initial column families, specified in the request.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables"
                },
                "dropRowRange": {
                  "httpMethod": "POST",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:dropRowRange",
                  "description": "Permanently drop/delete a row range from a specified table. The request can specify whether to delete all rows in a table, or only those that match a particular prefix.",
                  "path": "v2/{+name}:dropRowRange",
                  "id": "bigtableadmin.projects.instances.tables.dropRowRange",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.tables.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/tables",
                  "description": "Lists all tables served from a specified instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables"
                },
                "testIamPermissions": {
                  "id": "bigtableadmin.projects.instances.tables.testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:testIamPermissions",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:testIamPermissions",
                  "description": "Returns permissions that the caller has on the specified Table or Backup resource."
                },
                "setIamPolicy": {
                  "id": "bigtableadmin.projects.instances.tables.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:setIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Sets the access control policy on a Table or Backup resource. Replaces any existing policy."
                },
                "modifyColumnFamilies": {
                  "id": "bigtableadmin.projects.instances.tables.modifyColumnFamilies",
                  "httpMethod": "POST",
                  "path": "v2/{+name}:modifyColumnFamilies",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:modifyColumnFamilies",
                  "description": "Performs a series of column family modifications on the specified table. Either all or none of the modifications will occur before this method returns, but data requests received prior to that point may see a table where only some modifications have taken effect."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets metadata information about the specified table.",
                  "path": "v2/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "id": "bigtableadmin.projects.instances.tables.get"
                },
                "generateConsistencyToken": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:generateConsistencyToken",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.generateConsistencyToken",
                  "description": "Generates a consistency token for a Table, which can be used in CheckConsistency to check whether mutations to the table that finished before this call started have been replicated. The tokens will be available for 90 days.",
                  "httpMethod": "POST",
                  "path": "v2/{+name}:generateConsistencyToken"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "bigtableadmin.projects.instances.tables.delete",
                  "path": "v2/{+name}",
                  "description": "Permanently deletes a specified table and all of its data.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "patch": {
                  "id": "bigtableadmin.projects.instances.tables.patch",
                  "description": "Updates a specified table.",
                  "httpMethod": "PATCH",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "clusters": {
              "methods": {
                "create": {
                  "path": "v2/{+parent}/clusters",
                  "id": "bigtableadmin.projects.instances.clusters.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "description": "Creates a cluster within an instance. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets information about a cluster.",
                  "httpMethod": "GET",
                  "id": "bigtableadmin.projects.instances.clusters.get",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "path": "v2/{+name}"
                },
                "partialUpdateCluster": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.partialUpdateCluster",
                  "path": "v2/{+name}",
                  "description": "Partially updates a cluster within a project. This method is the preferred way to update a Cluster. To enable and update autoscaling, set cluster_config.cluster_autoscaling_config. When autoscaling is enabled, serve_nodes is treated as an OUTPUT_ONLY field, meaning that updates to it are ignored. Note that an update cannot simultaneously set serve_nodes to non-zero and cluster_config.cluster_autoscaling_config to non-empty, and also specify both in the update_ma[...]",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}"
                },
                "update": {
                  "httpMethod": "PUT",
                  "path": "v2/{+name}",
                  "id": "bigtableadmin.projects.instances.clusters.update",
                  "description": "Updates a cluster within an instance. Note that UpdateCluster does not support updating cluster_config.cluster_autoscaling_config. In order to update it, you must use PartialUpdateCluster.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v2/{+parent}/clusters",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "description": "Lists information about clusters in an instance.",
                  "id": "bigtableadmin.projects.instances.clusters.list",
                  "httpMethod": "GET"
                },
                "delete": {
                  "path": "v2/{+name}",
                  "id": "bigtableadmin.projects.instances.clusters.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes a cluster from an instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              },
              "resources": {
                "hotTablets": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/hotTablets",
                      "id": "bigtableadmin.projects.instances.clusters.hotTablets.list",
                      "path": "v2/{+parent}/hotTablets",
                      "description": "Lists hot tablets in a cluster, within the time range provided. Hot tablets are ordered based on CPU usage.",
                      "httpMethod": "GET"
                    }
                  }
                },
                "backups": {
                  "methods": {
                    "get": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.get",
                      "httpMethod": "GET",
                      "path": "v2/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Gets metadata on a pending or completed Cloud Bigtable Backup.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}"
                    },
                    "copy": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups:copy",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Copy a Cloud Bigtable backup to a new backup in the destination cluster located in the destination instance and project.",
                      "id": "bigtableadmin.projects.instances.clusters.backups.copy",
                      "httpMethod": "POST",
                      "path": "v2/{+parent}/backups:copy"
                    },
                    "list": {
                      "path": "v2/{+parent}/backups",
                      "httpMethod": "GET",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "description": "Lists Cloud Bigtable backups. Returns both completed and pending backups.",
                      "id": "bigtableadmin.projects.instances.clusters.backups.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ]
                    },
                    "delete": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "path": "v2/{+name}",
                      "description": "Deletes a pending or completed Cloud Bigtable backup.",
                      "httpMethod": "DELETE",
                      "id": "bigtableadmin.projects.instances.clusters.backups.delete"
                    },
                    "getIamPolicy": {
                      "description": "Gets the access control policy for a Table or Backup resource. Returns an empty policy if the resource exists but does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.clusters.backups.getIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:getIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:getIamPolicy"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "httpMethod": "PATCH",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "id": "bigtableadmin.projects.instances.clusters.backups.patch",
                      "description": "Updates a pending or completed Cloud Bigtable Backup.",
                      "path": "v2/{+name}"
                    },
                    "setIamPolicy": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:setIamPolicy",
                      "id": "bigtableadmin.projects.instances.clusters.backups.setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Sets the access control policy on a Table or Backup resource. Replaces any existing policy."
                    },
                    "create": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "path": "v2/{+parent}/backups",
                      "id": "bigtableadmin.projects.instances.clusters.backups.create",
                      "description": "Starts creating a new Cloud Bigtable Backup. The returned backup long-running operation can be used to track creation of the backup. The metadata field type is CreateBackupMetadata. The response field type is Backup, if successful. Cancelling the returned operation will stop the creation and delete the backup.",
                      "httpMethod": "POST"
                    },
                    "testIamPermissions": {
                      "httpMethod": "POST",
                      "id": "bigtableadmin.projects.instances.clusters.backups.testIamPermissions",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:testIamPermissions",
                      "path": "v2/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Returns permissions that the caller has on the specified Table or Backup resource."
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "getIamPolicy": {
              "id": "bigtableadmin.projects.instances.getIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set.",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
              "path": "v2/{+resource}:getIamPolicy"
            },
            "get": {
              "path": "v2/{+name}",
              "httpMethod": "GET",
              "id": "bigtableadmin.projects.instances.get",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "description": "Gets information about an instance.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ]
            },
            "setIamPolicy": {
              "id": "bigtableadmin.projects.instances.setIamPolicy",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v2/{+resource}:setIamPolicy",
              "description": "Sets the access control policy on an instance resource. Replaces any existing policy.",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
              "httpMethod": "POST"
            },
            "partialUpdateInstance": {
              "path": "v2/{+name}",
              "id": "bigtableadmin.projects.instances.partialUpdateInstance",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Partially updates an instance within a project. This method can modify all fields of an Instance and is the preferred way to update an Instance.",
              "httpMethod": "PATCH"
            },
            "update": {
              "path": "v2/{+name}",
              "httpMethod": "PUT",
              "id": "bigtableadmin.projects.instances.update",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "description": "Updates an instance within a project. This method updates only the display name and type for an Instance. To update other Instance properties, such as labels, use PartialUpdateInstance.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "testIamPermissions": {
              "id": "bigtableadmin.projects.instances.testIamPermissions",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
              "path": "v2/{+resource}:testIamPermissions",
              "description": "Returns permissions that the caller has on the specified instance resource."
            },
            "create": {
              "description": "Create an instance within a project. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.create",
              "path": "v2/{+parent}/instances",
              "httpMethod": "POST",
              "flatPath": "v2/projects/{projectsId}/instances"
            },
            "list": {
              "flatPath": "v2/projects/{projectsId}/instances",
              "id": "bigtableadmin.projects.instances.list",
              "path": "v2/{+parent}/instances",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Lists information about instances in a project."
            },
            "delete": {
              "id": "bigtableadmin.projects.instances.delete",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "description": "Delete an instance from a project.",
              "path": "v2/{+name}"
            }
          }
        },
        "locations": {
          "methods": {
            "list": {
              "flatPath": "v2/projects/{projectsId}/locations",
              "path": "v2/{+name}/locations",
              "id": "bigtableadmin.projects.locations.list",
              "description": "Lists information about the supported locations for this service.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ]
            },
            "get": {
              "flatPath": "v2/projects/{projectsId}/locations/{locationsId}",
              "description": "Gets information about a location.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "id": "bigtableadmin.projects.locations.get",
              "path": "v2/{+name}",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://bigtableadmin.googleapis.com/",
  "description": "Administer your Cloud Bigtable tables and instances.",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "title": "Cloud Bigtable Admin API",
  "version": "v2",
  "basePath": "",
  "name": "bigtableadmin",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/bigtable.admin.instance": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        }
      }
    }
  }
}
