{
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "servicePath": "",
  "ownerName": "Google",
  "title": "Cloud Bigtable Admin API",
  "documentationLink": "https://cloud.google.com/bigtable/",
  "version_module": true,
  "rootUrl": "https://bigtableadmin.googleapis.com/",
  "canonicalName": "Bigtable Admin",
  "description": "Administer your Cloud Bigtable tables and instances.",
  "batchPath": "batch",
  "revision": "20221009",
  "version": "v2",
  "fullyEncodeReservedExpansion": true,
  "name": "bigtableadmin",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://bigtableadmin.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.instance": {
          "description": "Administer your Cloud Bigtable clusters"
        }
      }
    }
  },
  "basePath": "",
  "id": "bigtableadmin:v2",
  "protocol": "rest",
  "resources": {
    "operations": {
      "methods": {
        "cancel": {
          "id": "bigtableadmin.operations.cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "path": "v2/{+name}:cancel",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "flatPath": "v2/operations/{operationsId}:cancel"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v2/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "bigtableadmin.operations.delete",
          "path": "v2/{+name}",
          "httpMethod": "DELETE"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/{+name}",
          "flatPath": "v2/operations/{operationsId}",
          "id": "bigtableadmin.operations.get",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        }
      },
      "resources": {
        "projects": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "path": "v2/{+name}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the [...]",
                  "id": "bigtableadmin.operations.projects.operations.list",
                  "flatPath": "v2/operations/projects/{projectsId}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "instances": {
          "resources": {
            "tables": {
              "methods": {
                "generateConsistencyToken": {
                  "id": "bigtableadmin.projects.instances.tables.generateConsistencyToken",
                  "path": "v2/{+name}:generateConsistencyToken",
                  "description": "Generates a consistency token for a Table, which can be used in CheckConsistency to check whether mutations to the table that finished before this call started have been replicated. The tokens will be available for 90 days.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:generateConsistencyToken",
                  "httpMethod": "POST"
                },
                "checkConsistency": {
                  "httpMethod": "POST",
                  "id": "bigtableadmin.projects.instances.tables.checkConsistency",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:checkConsistency",
                  "description": "Checks replication consistency based on a consistency token, that is, if replication has caught up based on the conditions specified in the token and the check request.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+name}:checkConsistency"
                },
                "restore": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables:restore",
                  "description": "Create a new table by restoring from a completed backup. The new table must be in the same project as the instance containing the backup. The returned table long-running operation can be used to track the progress of the operation, and to cancel it. The metadata field type is RestoreTableMetadata. The response type is Table, if successful.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+parent}/tables:restore",
                  "id": "bigtableadmin.projects.instances.tables.restore"
                },
                "setIamPolicy": {
                  "path": "v2/{+resource}:setIamPolicy",
                  "id": "bigtableadmin.projects.instances.tables.setIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Sets the access control policy on a Table resource. Replaces any existing policy.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "path": "v2/{+name}",
                  "httpMethod": "DELETE",
                  "description": "Permanently deletes a specified table and all of its data.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.delete"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v2/{+parent}/tables",
                  "description": "Lists all tables served from a specified instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "id": "bigtableadmin.projects.instances.tables.list"
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets metadata information about the specified table.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "id": "bigtableadmin.projects.instances.tables.get"
                },
                "create": {
                  "description": "Creates a new table in the specified instance. The table can be created with a full set of initial column families, specified in the request.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/{+parent}/tables",
                  "id": "bigtableadmin.projects.instances.tables.create",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables"
                },
                "undelete": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:undelete",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+name}:undelete",
                  "httpMethod": "POST",
                  "id": "bigtableadmin.projects.instances.tables.undelete",
                  "description": "Restores a specified table which was accidentally deleted."
                },
                "dropRowRange": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/{+name}:dropRowRange",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:dropRowRange",
                  "id": "bigtableadmin.projects.instances.tables.dropRowRange",
                  "description": "Permanently drop/delete a row range from a specified table. The request can specify whether to delete all rows in a table, or only those that match a particular prefix."
                },
                "modifyColumnFamilies": {
                  "description": "Performs a series of column family modifications on the specified table. Either all or none of the modifications will occur before this method returns, but data requests received prior to that point may see a table where only some modifications have taken effect.",
                  "path": "v2/{+name}:modifyColumnFamilies",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "httpMethod": "POST",
                  "id": "bigtableadmin.projects.instances.tables.modifyColumnFamilies",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:modifyColumnFamilies"
                },
                "getIamPolicy": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Gets the access control policy for a Table resource. Returns an empty policy if the resource exists but does not have a policy set.",
                  "httpMethod": "POST",
                  "id": "bigtableadmin.projects.instances.tables.getIamPolicy",
                  "path": "v2/{+resource}:getIamPolicy"
                },
                "testIamPermissions": {
                  "id": "bigtableadmin.projects.instances.tables.testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Returns permissions that the caller has on the specified table resource.",
                  "path": "v2/{+resource}:testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:testIamPermissions"
                }
              }
            },
            "clusters": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "id": "bigtableadmin.projects.instances.clusters.delete",
                  "description": "Deletes a cluster from an instance.",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "path": "v2/{+parent}/clusters",
                  "description": "Lists information about clusters in an instance.",
                  "id": "bigtableadmin.projects.instances.clusters.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters"
                },
                "create": {
                  "path": "v2/{+parent}/clusters",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.create",
                  "description": "Creates a cluster within an instance. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters"
                },
                "update": {
                  "id": "bigtableadmin.projects.instances.clusters.update",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "description": "Updates a cluster within an instance. Note that UpdateCluster does not support updating cluster_config.cluster_autoscaling_config. In order to update it, you must use PartialUpdateCluster.",
                  "httpMethod": "PUT"
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.clusters.get",
                  "description": "Gets information about a cluster.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "GET",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "partialUpdateCluster": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.partialUpdateCluster",
                  "path": "v2/{+name}",
                  "description": "Partially updates a cluster within a project. This method is the preferred way to update a Cluster. To enable and update autoscaling, set cluster_config.cluster_autoscaling_config. When autoscaling is enabled, serve_nodes is treated as an OUTPUT_ONLY field, meaning that updates to it are ignored. Note that an update cannot simultaneously set serve_nodes to non-zero and cluster_config.cluster_autoscaling_config to non-empty, and also specify both in the update_ma[...]",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}"
                }
              },
              "resources": {
                "backups": {
                  "methods": {
                    "delete": {
                      "description": "Deletes a pending or completed Cloud Bigtable backup.",
                      "path": "v2/{+name}",
                      "id": "bigtableadmin.projects.instances.clusters.backups.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ]
                    },
                    "create": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Starts creating a new Cloud Bigtable Backup. The returned backup long-running operation can be used to track creation of the backup. The metadata field type is CreateBackupMetadata. The response field type is Backup, if successful. Cancelling the returned operation will stop the creation and delete the backup.",
                      "path": "v2/{+parent}/backups",
                      "httpMethod": "POST",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups"
                    },
                    "list": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "id": "bigtableadmin.projects.instances.clusters.backups.list",
                      "httpMethod": "GET",
                      "path": "v2/{+parent}/backups",
                      "description": "Lists Cloud Bigtable backups. Returns both completed and pending backups.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ]
                    },
                    "setIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:setIamPolicy",
                      "id": "bigtableadmin.projects.instances.clusters.backups.setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:setIamPolicy",
                      "description": "Sets the access control policy on a Table resource. Replaces any existing policy."
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "id": "bigtableadmin.projects.instances.clusters.backups.patch",
                      "path": "v2/{+name}",
                      "description": "Updates a pending or completed Cloud Bigtable Backup.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}"
                    },
                    "copy": {
                      "httpMethod": "POST",
                      "path": "v2/{+parent}/backups:copy",
                      "id": "bigtableadmin.projects.instances.clusters.backups.copy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups:copy",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Copy a Cloud Bigtable backup to a new backup in the destination cluster located in the destination instance and project."
                    },
                    "testIamPermissions": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Returns permissions that the caller has on the specified table resource.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:testIamPermissions",
                      "id": "bigtableadmin.projects.instances.clusters.backups.testIamPermissions",
                      "path": "v2/{+resource}:testIamPermissions",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "description": "Gets metadata on a pending or completed Cloud Bigtable Backup.",
                      "id": "bigtableadmin.projects.instances.clusters.backups.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "httpMethod": "GET",
                      "path": "v2/{+name}"
                    },
                    "getIamPolicy": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:getIamPolicy",
                      "path": "v2/{+resource}:getIamPolicy",
                      "description": "Gets the access control policy for a Table resource. Returns an empty policy if the resource exists but does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "httpMethod": "POST",
                      "id": "bigtableadmin.projects.instances.clusters.backups.getIamPolicy"
                    }
                  }
                },
                "hotTablets": {
                  "methods": {
                    "list": {
                      "description": "Lists hot tablets in a cluster, within the time range provided. Hot tablets are ordered based on CPU usage.",
                      "id": "bigtableadmin.projects.instances.clusters.hotTablets.list",
                      "path": "v2/{+parent}/hotTablets",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/hotTablets"
                    }
                  }
                }
              }
            },
            "appProfiles": {
              "methods": {
                "get": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "bigtableadmin.projects.instances.appProfiles.get",
                  "description": "Gets information about an app profile.",
                  "path": "v2/{+name}"
                },
                "patch": {
                  "description": "Updates an app profile within an instance.",
                  "id": "bigtableadmin.projects.instances.appProfiles.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "PATCH",
                  "path": "v2/{+name}"
                },
                "create": {
                  "id": "bigtableadmin.projects.instances.appProfiles.create",
                  "httpMethod": "POST",
                  "description": "Creates an app profile within an instance.",
                  "path": "v2/{+parent}/appProfiles",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.appProfiles.delete",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "DELETE",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes an app profile from an instance."
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "bigtableadmin.projects.instances.appProfiles.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "description": "Lists information about app profiles in an instance.",
                  "path": "v2/{+parent}/appProfiles"
                }
              }
            }
          },
          "methods": {
            "setIamPolicy": {
              "path": "v2/{+resource}:setIamPolicy",
              "description": "Sets the access control policy on an instance resource. Replaces any existing policy.",
              "id": "bigtableadmin.projects.instances.setIamPolicy",
              "httpMethod": "POST",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "partialUpdateInstance": {
              "description": "Partially updates an instance within a project. This method can modify all fields of an Instance and is the preferred way to update an Instance.",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "id": "bigtableadmin.projects.instances.partialUpdateInstance",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "PATCH",
              "path": "v2/{+name}"
            },
            "list": {
              "id": "bigtableadmin.projects.instances.list",
              "path": "v2/{+parent}/instances",
              "description": "Lists information about instances in a project.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "flatPath": "v2/projects/{projectsId}/instances"
            },
            "update": {
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "PUT",
              "description": "Updates an instance within a project. This method updates only the display name and type for an Instance. To update other Instance properties, such as labels, use PartialUpdateInstance.",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "id": "bigtableadmin.projects.instances.update"
            },
            "getIamPolicy": {
              "description": "Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set.",
              "path": "v2/{+resource}:getIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
              "httpMethod": "POST",
              "id": "bigtableadmin.projects.instances.getIamPolicy",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "httpMethod": "GET",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "id": "bigtableadmin.projects.instances.get",
              "description": "Gets information about an instance."
            },
            "testIamPermissions": {
              "path": "v2/{+resource}:testIamPermissions",
              "httpMethod": "POST",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
              "id": "bigtableadmin.projects.instances.testIamPermissions",
              "description": "Returns permissions that the caller has on the specified instance resource.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "create": {
              "description": "Create an instance within a project. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.",
              "flatPath": "v2/projects/{projectsId}/instances",
              "path": "v2/{+parent}/instances",
              "id": "bigtableadmin.projects.instances.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "path": "v2/{+name}",
              "id": "bigtableadmin.projects.instances.delete",
              "description": "Delete an instance from a project."
            }
          }
        },
        "locations": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists information about the supported locations for this service.",
              "flatPath": "v2/projects/{projectsId}/locations",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "path": "v2/{+name}/locations",
              "id": "bigtableadmin.projects.locations.list"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets information about a location.",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/locations/{locationsId}",
              "id": "bigtableadmin.projects.locations.get",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ]
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://bigtableadmin.googleapis.com/"
}
