{
  "kind": "discovery#restDescription",
  "version_module": true,
  "version": "v1",
  "name": "chat",
  "canonicalName": "Hangouts Chat",
  "title": "Google Chat API",
  "baseUrl": "https://chat.googleapis.com/",
  "protocol": "rest",
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "id": "chat:v1",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "servicePath": "",
  "description": "Enables apps to fetch information and perform actions in Google Chat. Authentication is a prerequisite for using the Google Chat REST API.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chat.memberships.readonly": {
          "description": "View members in Google Chat conversations."
        },
        "https://www.googleapis.com/auth/chat.messages.readonly": {
          "description": "View messages and reactions in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.bot": {
          "description": "Private Service: https://www.googleapis.com/auth/chat.bot"
        },
        "https://www.googleapis.com/auth/chat.messages": {
          "description": "View, compose, send, update, and delete messages, and add, view, and delete reactions to messages."
        },
        "https://www.googleapis.com/auth/chat.messages.create": {
          "description": "Compose and send messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces": {
          "description": "Create conversations and spaces and view or update metadata (including history settings) in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships": {
          "description": "View, add, and remove members from conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces.readonly": {
          "description": "View chat and spaces in Google Chat"
        }
      }
    }
  },
  "mtlsRootUrl": "https://chat.mtls.googleapis.com/",
  "revision": "20230212",
  "rootUrl": "https://chat.googleapis.com/",
  "basePath": "",
  "resources": {
    "spaces": {
      "resources": {
        "messages": {
          "methods": {
            "patch": {
              "id": "chat.spaces.messages.patch",
              "description": "Updates a message. For example usage, see [Update a message](https://developers.google.com/chat/api/guides/crudl/messages#update_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer[...]",
              "path": "v1/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}"
            },
            "delete": {
              "path": "v1/{+name}",
              "description": "Deletes a message. For example usage, see [Delete a message](https://developers.google.com/chat/api/guides/crudl/messages#delete_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer [...]",
              "id": "chat.spaces.messages.delete",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages"
              ]
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "path": "v1/{+name}",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "description": "Updates a message. For example usage, see [Update a message](https://developers.google.com/chat/api/guides/crudl/messages#update_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer[...]",
              "id": "chat.spaces.messages.update"
            },
            "get": {
              "id": "chat.spaces.messages.get",
              "path": "v1/{+name}",
              "description": "Returns a message. For example usage, see [Read a message](https://developers.google.com/chat/api/guides/crudl/messages#read_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [Service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Prev[...]",
              "httpMethod": "GET",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.readonly"
              ]
            },
            "create": {
              "id": "chat.spaces.messages.create",
              "description": "Creates a message. For example usage, see [Create a message](https://developers.google.com/chat/api/guides/crudl/messages#create_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer [...]",
              "path": "v1/{+parent}/messages",
              "flatPath": "v1/spaces/{spacesId}/messages",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.create"
              ],
              "httpMethod": "POST"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "id": "chat.spaces.messages.attachments.get",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/attachments/{attachmentsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.bot"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets the metadata of a message attachment. The attachment data is fetched using the [media API](https://developers.google.com/chat/api/reference/rest/v1/media/download). Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
                  "path": "v1/{+name}"
                }
              }
            }
          }
        },
        "members": {
          "methods": {
            "get": {
              "description": "Returns a membership. Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain features. [Use[...]",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.readonly"
              ],
              "id": "chat.spaces.members.get",
              "flatPath": "v1/spaces/{spacesId}/members/{membersId}",
              "httpMethod": "GET",
              "path": "v1/{+name}"
            },
            "list": {
              "flatPath": "v1/spaces/{spacesId}/members",
              "description": "Lists memberships in a space. Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain featur[...]",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.readonly"
              ],
              "path": "v1/{+parent}/members",
              "id": "chat.spaces.members.list",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "get": {
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ],
          "description": "Returns a space. Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain features. [User authenti[...]",
          "flatPath": "v1/spaces/{spacesId}",
          "httpMethod": "GET",
          "id": "chat.spaces.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ],
          "flatPath": "v1/spaces",
          "description": "Lists spaces the caller is a member of. Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain f[...]",
          "path": "v1/spaces",
          "id": "chat.spaces.list",
          "httpMethod": "GET"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.readonly"
          ],
          "supportsMediaDownload": true,
          "path": "v1/media/{+resourceName}",
          "flatPath": "v1/media/{mediaId}",
          "id": "chat.media.download",
          "description": "Downloads media. Download is supported on the URI `/v1/media/{+name}?alt=media`."
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/hangouts/chat"
}
