{
  "title": "Google Chat API",
  "id": "chat:v1",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/hangouts/chat",
  "discoveryVersion": "v1",
  "version": "v1",
  "kind": "discovery#restDescription",
  "canonicalName": "Hangouts Chat",
  "protocol": "rest",
  "revision": "20230514",
  "description": "Enables apps to fetch information and perform actions in Google Chat. Authentication is a prerequisite for using the Google Chat REST API.",
  "baseUrl": "https://chat.googleapis.com/",
  "name": "chat",
  "mtlsRootUrl": "https://chat.mtls.googleapis.com/",
  "version_module": true,
  "resources": {
    "media": {
      "methods": {
        "upload": {
          "flatPath": "v1/spaces/{spacesId}/attachments:upload",
          "path": "v1/{+parent}/attachments:upload",
          "httpMethod": "POST",
          "id": "chat.media.upload",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.create"
          ],
          "description": "[Developer Preview](https://developers.google.com/workspace/preview): Uploads an attachment. Requires user [authentication](https://developers.google.com/chat/api/guides/auth/users). You can upload attachments up to 200 MB. Certain file types aren't supported. For details, see [File types blocked by Google Chat](https://support.google.com/chat/answer/7651457?&co=GENIE.Platform%3DDesktop#File%20types%20blocked%20in%20Google%20Chat)."
        },
        "download": {
          "id": "chat.media.download",
          "httpMethod": "GET",
          "path": "v1/media/{+resourceName}",
          "flatPath": "v1/media/{mediaId}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.readonly"
          ],
          "description": "Downloads media. Download is supported on the URI `/v1/media/{+name}?alt=media`.",
          "supportsMediaDownload": true
        }
      }
    },
    "spaces": {
      "resources": {
        "messages": {
          "methods": {
            "get": {
              "id": "chat.spaces.messages.get",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.readonly"
              ],
              "description": "Returns a message. For example usage, see [Read a message](https://developers.google.com/chat/api/guides/crudl/messages#read_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [Service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Prev[...]"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "httpMethod": "PUT",
              "id": "chat.spaces.messages.update",
              "description": "Updates a message. There's a difference between `patch` and `update` methods. The `patch` method uses a `patch` request while the `update` method uses a `put` request. We recommend using the `patch` method. For example usage, see [Update a message](https://developers.google.com/chat/api/guides/crudl/messages#update_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://devel[...]",
              "path": "v1/{+name}"
            },
            "delete": {
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "description": "Deletes a message. For example usage, see [Delete a message](https://developers.google.com/chat/api/guides/crudl/messages#delete_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer [...]",
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "id": "chat.spaces.messages.delete"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "id": "chat.spaces.messages.patch",
              "path": "v1/{+name}",
              "description": "Updates a message. There's a difference between `patch` and `update` methods. The `patch` method uses a `patch` request while the `update` method uses a `put` request. We recommend using the `patch` method. For example usage, see [Update a message](https://developers.google.com/chat/api/guides/crudl/messages#update_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://devel[...]"
            },
            "list": {
              "path": "v1/{+parent}/messages",
              "scopes": [
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.readonly"
              ],
              "id": "chat.spaces.messages.list",
              "flatPath": "v1/spaces/{spacesId}/messages",
              "description": "[Developer Preview](https://developers.google.com/workspace/preview): Lists messages in a space that the caller is a member of, including messages from blocked members and spaces. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.messages` or `chat.messages.readonly` authorization scope. This method is only supported in spaces that don't allow users from outside the Workspace organization to join.",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.create"
              ],
              "path": "v1/{+parent}/messages",
              "flatPath": "v1/spaces/{spacesId}/messages",
              "id": "chat.spaces.messages.create",
              "description": "Creates a message. For example usage, see [Create a message](https://developers.google.com/chat/api/guides/crudl/messages#create_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer [...]"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "id": "chat.spaces.messages.attachments.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/attachments/{attachmentsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.bot"
                  ],
                  "description": "Gets the metadata of a message attachment. The attachment data is fetched using the [media API](https://developers.google.com/chat/api/reference/rest/v1/media/download). Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
                  "path": "v1/{+name}"
                }
              }
            },
            "reactions": {
              "methods": {
                "list": {
                  "id": "chat.spaces.messages.reactions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.messages",
                    "https://www.googleapis.com/auth/chat.messages.reactions",
                    "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
                    "https://www.googleapis.com/auth/chat.messages.readonly"
                  ],
                  "description": "[Developer Preview](https://developers.google.com/workspace/preview): Lists reactions to a message. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and `chat.messages`, `chat.messages.readonly`, `chat.messages.reactions`, or `chat.messages.reactions.readonly` scope.",
                  "path": "v1/{+parent}/reactions",
                  "httpMethod": "GET",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/reactions"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.messages",
                    "https://www.googleapis.com/auth/chat.messages.reactions"
                  ],
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/reactions/{reactionsId}",
                  "id": "chat.spaces.messages.reactions.delete",
                  "description": "[Developer Preview](https://developers.google.com/workspace/preview): Deletes a reaction to a message. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.messages` or `chat.messages.reactions` scope.",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.messages",
                    "https://www.googleapis.com/auth/chat.messages.reactions",
                    "https://www.googleapis.com/auth/chat.messages.reactions.create"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/reactions",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/reactions",
                  "description": "[Developer Preview](https://developers.google.com/workspace/preview): Creates a reaction and adds it to a message. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.messages`, `chat.messages.reactions`, or `chat.messages.reactions.create` scope. Only unicode emoji are supported.",
                  "id": "chat.spaces.messages.reactions.create"
                }
              }
            }
          }
        },
        "members": {
          "methods": {
            "list": {
              "path": "v1/{+parent}/members",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.readonly"
              ],
              "description": "Lists memberships in a space. Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain featur[...]",
              "httpMethod": "GET",
              "id": "chat.spaces.members.list",
              "flatPath": "v1/spaces/{spacesId}/members"
            },
            "get": {
              "id": "chat.spaces.members.get",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/spaces/{spacesId}/members/{membersId}",
              "description": "Returns a membership. Requires [authentication](https://developers.google.com/chat/api/guides/auth/). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain features. [Use[...]",
              "path": "v1/{+name}"
            },
            "delete": {
              "description": "[Developer Preview](https://developers.google.com/workspace/preview): Deletes a membership. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.memberships` or `chat.memberships.app` authorization scope.",
              "id": "chat.spaces.members.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.app"
              ],
              "flatPath": "v1/spaces/{spacesId}/members/{membersId}",
              "path": "v1/{+name}"
            },
            "create": {
              "flatPath": "v1/spaces/{spacesId}/members",
              "id": "chat.spaces.members.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.app"
              ],
              "description": "[Developer Preview](https://developers.google.com/workspace/preview): Creates a human membership or app membership for the calling app. Creating memberships for other apps is not supported. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.memberships` (for human membership) or `chat.memberships.app` (for app membership) scope. To specify the member to add, set the `membership.member.name` in the `CreateMembership[...]",
              "path": "v1/{+parent}/members"
            }
          }
        }
      },
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.create"
          ],
          "flatPath": "v1/spaces",
          "path": "v1/spaces",
          "id": "chat.spaces.create",
          "description": "[Developer Preview](https://developers.google.com/workspace/preview): Creates a named space. Spaces grouped by topics or that have guest access are not supported. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.spaces.create` or `chat.spaces` scope.",
          "httpMethod": "POST"
        },
        "findDirectMessage": {
          "path": "v1/spaces:findDirectMessage",
          "id": "chat.spaces.findDirectMessage",
          "httpMethod": "GET",
          "flatPath": "v1/spaces:findDirectMessage",
          "description": "[Developer Preview](https://developers.google.com/workspace/preview): Returns the existing direct message with the specified user. With [user authentication](https://developers.google.com/chat/api/guides/auth/users), returns the direct message space between the specified user and the authenticated user. With [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts), returns the direct message space between the specified user a[...]",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ],
          "flatPath": "v1/spaces/{spacesId}",
          "id": "chat.spaces.get",
          "path": "v1/{+name}",
          "description": "Returns a space. Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain features. [User authenti[...]"
        },
        "list": {
          "id": "chat.spaces.list",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ],
          "description": "Lists spaces the caller is a member of. Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain f[...]",
          "path": "v1/spaces",
          "flatPath": "v1/spaces",
          "httpMethod": "GET"
        },
        "setup": {
          "id": "chat.spaces.setup",
          "flatPath": "v1/spaces:setup",
          "path": "v1/spaces:setup",
          "httpMethod": "POST",
          "description": "[Developer Preview](https://developers.google.com/workspace/preview): Creates a space and adds specified users to it. The calling user is automatically added to the space, and shouldn't be specified as a membership in the request. To specify the human members to add, add memberships with the appropriate `member.name` in the `SetUpSpaceRequest`. To add a human user, use `users/{user}`, where `{user}` is either the `{person_id}` for the [person](https://developers.google.[...]",
          "scopes": [
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.create"
          ]
        },
        "delete": {
          "id": "chat.spaces.delete",
          "description": "[Developer Preview](https://developers.google.com/workspace/preview): Deletes a named space. Always performs a cascading delete, which means that the space's child resources - like messages posted in the space and memberships in the space - are also deleted. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) from a user who has permission to delete the space, and the `chat.delete` scope.",
          "flatPath": "v1/spaces/{spacesId}",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.delete"
          ],
          "httpMethod": "DELETE"
        },
        "patch": {
          "description": "[Developer Preview](https://developers.google.com/workspace/preview): Updates a space. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) and the `chat.spaces` scope.",
          "id": "chat.spaces.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/chat.spaces"
          ],
          "flatPath": "v1/spaces/{spacesId}",
          "path": "v1/{+name}"
        }
      }
    }
  },
  "servicePath": "",
  "rootUrl": "https://chat.googleapis.com/",
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chat.messages.create": {
          "description": "Compose and send messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.reactions.create": {
          "description": "Add reactions to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.delete": {
          "description": "Delete conversations and spaces & remove access to associated files in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.reactions.readonly": {
          "description": "View reactions to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.reactions": {
          "description": "View, add, and delete reactions to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces": {
          "description": "Create conversations and spaces and view or update metadata (including history settings) in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces.readonly": {
          "description": "View chat and spaces in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces.create": {
          "description": "Create new conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships.app": {
          "description": "Add and remove itself from conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.readonly": {
          "description": "View messages and reactions in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships.readonly": {
          "description": "View members in Google Chat conversations."
        },
        "https://www.googleapis.com/auth/chat.messages": {
          "description": "View, compose, send, update, and delete messages, and add, view, and delete reactions to messages."
        },
        "https://www.googleapis.com/auth/chat.memberships": {
          "description": "View, add, and remove members from conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.bot": {
          "description": "Private Service: https://www.googleapis.com/auth/chat.bot"
        }
      }
    }
  },
  "basePath": "",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch"
}
