{
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "revision": "20230921",
  "id": "chat:v1",
  "version_module": true,
  "baseUrl": "https://chat.googleapis.com/",
  "documentationLink": "https://developers.google.com/hangouts/chat",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chat.spaces.readonly": {
          "description": "View chat and spaces in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships.readonly": {
          "description": "View members in Google Chat conversations."
        },
        "https://www.googleapis.com/auth/chat.messages.create": {
          "description": "Compose and send messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages": {
          "description": "View, compose, send, update, and delete messages, and add, view, and delete reactions to messages."
        },
        "https://www.googleapis.com/auth/chat.messages.reactions": {
          "description": "View, add, and delete reactions to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.readonly": {
          "description": "View messages and reactions in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.reactions.readonly": {
          "description": "View reactions to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.spaces": {
          "description": "Create conversations and spaces and view or update metadata (including history settings) in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships.app": {
          "description": "Add and remove itself from conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.reactions.create": {
          "description": "Add reactions to messages in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.memberships": {
          "description": "View, add, and remove members from conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.import": {
          "description": "Import spaces, messages, and memberships into Google Chat."
        },
        "https://www.googleapis.com/auth/chat.bot": {
          "description": "Private Service: https://www.googleapis.com/auth/chat.bot"
        },
        "https://www.googleapis.com/auth/chat.spaces.create": {
          "description": "Create new conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.delete": {
          "description": "Delete conversations and spaces & remove access to associated files in Google Chat"
        }
      }
    }
  },
  "version": "v1",
  "kind": "discovery#restDescription",
  "rootUrl": "https://chat.googleapis.com/",
  "resources": {
    "media": {
      "methods": {
        "upload": {
          "path": "v1/{+parent}/attachments:upload",
          "id": "chat.media.upload",
          "flatPath": "v1/spaces/{spacesId}/attachments:upload",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/chat.import",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.create"
          ],
          "httpMethod": "POST",
          "description": "Uploads an attachment. For an example, see [Upload media as a file attachment](https://developers.google.com/chat/api/guides/v1/media-and-attachments/upload). Requires user [authentication](https://developers.google.com/chat/api/guides/auth/users). You can upload attachments up to 200 MB. Certain file types aren't supported. For details, see [File types blocked by Google Chat](https://support.google.com/chat/answer/7651457?&co=GENIE.Platform%3DDesktop#File%20types%20blo[...]"
        },
        "download": {
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/v1/media/{+name}?alt=media`.",
          "id": "chat.media.download",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.readonly"
          ],
          "flatPath": "v1/media/{mediaId}",
          "supportsMediaDownload": true,
          "path": "v1/media/{+resourceName}"
        }
      }
    },
    "spaces": {
      "resources": {
        "messages": {
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/attachments/{attachmentsId}",
                  "path": "v1/{+name}",
                  "id": "chat.spaces.messages.attachments.get",
                  "description": "Gets the metadata of a message attachment. The attachment data is fetched using the [media API](https://developers.google.com/chat/api/reference/rest/v1/media/download). For an example, see [Get a message attachment](https://developers.google.com/chat/api/guides/v1/media-and-attachments/get). Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.bot"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "reactions": {
              "methods": {
                "create": {
                  "description": "Creates a reaction and adds it to a message. For an example, see [Create a reaction](https://developers.google.com/chat/api/guides/v1/reactions/create). Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users). Only unicode emoji are supported.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.import",
                    "https://www.googleapis.com/auth/chat.messages",
                    "https://www.googleapis.com/auth/chat.messages.reactions",
                    "https://www.googleapis.com/auth/chat.messages.reactions.create"
                  ],
                  "path": "v1/{+parent}/reactions",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/reactions",
                  "id": "chat.spaces.messages.reactions.create",
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "chat.spaces.messages.reactions.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.messages",
                    "https://www.googleapis.com/auth/chat.messages.reactions",
                    "https://www.googleapis.com/auth/chat.messages.reactions.readonly",
                    "https://www.googleapis.com/auth/chat.messages.readonly"
                  ],
                  "path": "v1/{+parent}/reactions",
                  "description": "Lists reactions to a message. For an example, see [List reactions](https://developers.google.com/chat/api/guides/v1/reactions/list). Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users).",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/reactions"
                },
                "delete": {
                  "description": "Deletes a reaction to a message. For an example, see [Delete a reaction](https://developers.google.com/chat/api/guides/v1/reactions/delete). Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users).",
                  "scopes": [
                    "https://www.googleapis.com/auth/chat.import",
                    "https://www.googleapis.com/auth/chat.messages",
                    "https://www.googleapis.com/auth/chat.messages.reactions"
                  ],
                  "id": "chat.spaces.messages.reactions.delete",
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/reactions/{reactionsId}"
                }
              }
            }
          },
          "methods": {
            "delete": {
              "description": "Deletes a message. For an example, see [Delete a message](https://developers.google.com/chat/api/guides/v1/messages/delete). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts) and [user authentication](https://developers.google.com/chat/api/guides/auth/users). [User authentication](https://developers.google.com/chat/api/gui[...]",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "httpMethod": "DELETE",
              "id": "chat.spaces.messages.delete"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "chat.spaces.messages.patch",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "path": "v1/{+name}",
              "description": "Updates a message. There's a difference between the `patch` and `update` methods. The `patch` method uses a `patch` request while the `update` method uses a `put` request. We recommend using the `patch` method. For an example, see [Update a message](https://developers.google.com/chat/api/guides/v1/messages/update). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.[...]"
            },
            "get": {
              "description": "Returns details about a message. For an example, see [Read a message](https://developers.google.com/chat/api/guides/v1/messages/get). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts) and [user authentication](https://developers.google.com/chat/api/guides/auth/users). [User authentication](https://developers.google.com/cha[...]",
              "httpMethod": "GET",
              "id": "chat.spaces.messages.get",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.readonly"
              ],
              "path": "v1/{+name}"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "httpMethod": "PUT",
              "description": "Updates a message. There's a difference between the `patch` and `update` methods. The `patch` method uses a `patch` request while the `update` method uses a `put` request. We recommend using the `patch` method. For an example, see [Update a message](https://developers.google.com/chat/api/guides/v1/messages/update). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.[...]",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "id": "chat.spaces.messages.update",
              "path": "v1/{+name}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.create"
              ],
              "flatPath": "v1/spaces/{spacesId}/messages",
              "id": "chat.spaces.messages.create",
              "httpMethod": "POST",
              "description": "Creates a message in a Google Chat space. For an example, see [Create a message](https://developers.google.com/chat/api/guides/v1/messages/create). Calling this method requires [authentication](https://developers.google.com/chat/api/guides/auth) and supports the following authentication types: - For text messages, user authentication or app authentication are supported. - For card messages, only app authentication is supported. (Only Chat apps can create card messag[...]",
              "path": "v1/{+parent}/messages"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.readonly"
              ],
              "path": "v1/{+parent}/messages",
              "id": "chat.spaces.messages.list",
              "description": "Lists messages in a space that the caller is a member of, including messages from blocked members and spaces. For an example, see [List messages](/chat/api/guides/v1/messages/list). Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users).",
              "flatPath": "v1/spaces/{spacesId}/messages",
              "httpMethod": "GET"
            }
          }
        },
        "members": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v1/{+parent}/members",
              "flatPath": "v1/spaces/{spacesId}/members",
              "description": "Creates a human membership or app membership for the calling app. Creating memberships for other apps isn't supported. For an example, see [ Create a membership](https://developers.google.com/chat/api/guides/v1/members/create). When creating a membership, if the specified member has their auto-accept policy turned off, then they're invited, and must accept the space invitation before joining. Otherwise, creating a membership adds the member directly to the specified[...]",
              "id": "chat.spaces.members.create",
              "scopes": [
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.app"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/spaces/{spacesId}/members",
              "path": "v1/{+parent}/members",
              "id": "chat.spaces.members.list",
              "description": "Lists memberships in a space. For an example, see [List memberships](https://developers.google.com/chat/api/guides/v1/members/list). Listing memberships with [app authentication](https://developers.google.com/chat/api/guides/auth/service-accounts) lists memberships in spaces that the Chat app has access to, but excludes Chat app memberships, including its own. Listing memberships with [User authentication](https://developers.google.com/chat/api/guides/auth/users) li[...]",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.import",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.app"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1/spaces/{spacesId}/members/{membersId}",
              "path": "v1/{+name}",
              "id": "chat.spaces.members.delete",
              "description": "Deletes a membership. For an example, see [Delete a membership](https://developers.google.com/chat/api/guides/v1/members/delete). Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users)."
            },
            "get": {
              "id": "chat.spaces.members.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chat.bot",
                "https://www.googleapis.com/auth/chat.memberships",
                "https://www.googleapis.com/auth/chat.memberships.readonly"
              ],
              "description": "Returns details about a membership. For an example, see [Get a membership](https://developers.google.com/chat/api/guides/v1/members/get). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts) and [user authentication](https://developers.google.com/chat/api/guides/auth/users). [User authentication](https://developers.google.com[...]",
              "flatPath": "v1/spaces/{spacesId}/members/{membersId}",
              "path": "v1/{+name}"
            }
          }
        }
      },
      "methods": {
        "findDirectMessage": {
          "flatPath": "v1/spaces:findDirectMessage",
          "path": "v1/spaces:findDirectMessage",
          "description": "Returns the existing direct message with the specified user. If no direct message space is found, returns a `404 NOT_FOUND` error. For an example, see [Find a direct message](/chat/api/guides/v1/spaces/find-direct-message). With [user authentication](https://developers.google.com/chat/api/guides/auth/users), returns the direct message space between the specified user and the authenticated user. With [service account authentication](https://developers.google.com/chat/api[...]",
          "id": "chat.spaces.findDirectMessage",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "id": "chat.spaces.get",
          "flatPath": "v1/spaces/{spacesId}",
          "path": "v1/{+name}",
          "description": "Returns details about a space. For an example, see [Get a space](https://developers.google.com/chat/api/guides/v1/spaces/get). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts) and [user authentication](https://developers.google.com/chat/api/guides/auth/users).",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ]
        },
        "list": {
          "id": "chat.spaces.list",
          "description": "Lists spaces the caller is a member of. Group chats and DMs aren't listed until the first message is sent. For an example, see [List spaces](https://developers.google.com/chat/api/guides/v1/spaces/list). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts) and [user authentication](https://developers.google.com/chat/api/guides/au[...]",
          "path": "v1/spaces",
          "scopes": [
            "https://www.googleapis.com/auth/chat.bot",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.readonly"
          ],
          "flatPath": "v1/spaces",
          "httpMethod": "GET"
        },
        "create": {
          "id": "chat.spaces.create",
          "flatPath": "v1/spaces",
          "httpMethod": "POST",
          "path": "v1/spaces",
          "description": "Creates a named space. Spaces grouped by topics aren't supported. For an example, see [Create a space](https://developers.google.com/chat/api/guides/v1/spaces/create). If you receive the error message `ALREADY_EXISTS` when creating a space, try a different `displayName`. An existing space within the Google Workspace organization might already use this display name. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users).",
          "scopes": [
            "https://www.googleapis.com/auth/chat.import",
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.create"
          ]
        },
        "patch": {
          "flatPath": "v1/spaces/{spacesId}",
          "scopes": [
            "https://www.googleapis.com/auth/chat.import",
            "https://www.googleapis.com/auth/chat.spaces"
          ],
          "httpMethod": "PATCH",
          "description": "Updates a space. For an example, see [Update a space](https://developers.google.com/chat/api/guides/v1/spaces/update). If you're updating the `displayName` field and receive the error message `ALREADY_EXISTS`, try a different display name.. An existing space within the Google Workspace organization might already use this display name. Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users).",
          "path": "v1/{+name}",
          "id": "chat.spaces.patch"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/chat.delete",
            "https://www.googleapis.com/auth/chat.import"
          ],
          "description": "Deletes a named space. Always performs a cascading delete, which means that the space's child resources—like messages posted in the space and memberships in the space—are also deleted. For an example, see [Delete a space](https://developers.google.com/chat/api/guides/v1/spaces/delete). Requires [user authentication](https://developers.google.com/chat/api/guides/auth/users) from a user who has permission to delete the space.",
          "id": "chat.spaces.delete",
          "flatPath": "v1/spaces/{spacesId}",
          "httpMethod": "DELETE",
          "path": "v1/{+name}"
        },
        "setup": {
          "id": "chat.spaces.setup",
          "description": "Creates a space and adds specified users to it. The calling user is automatically added to the space, and shouldn't be specified as a membership in the request. For an example, see [Set up a space](https://developers.google.com/chat/api/guides/v1/spaces/set-up). To specify the human members to add, add memberships with the appropriate `member.name` in the `SetUpSpaceRequest`. To add a human user, use `users/{user}`, where `{user}` can be the email address for the user. [...]",
          "path": "v1/spaces:setup",
          "scopes": [
            "https://www.googleapis.com/auth/chat.spaces",
            "https://www.googleapis.com/auth/chat.spaces.create"
          ],
          "flatPath": "v1/spaces:setup",
          "httpMethod": "POST"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "description": "Enables apps to fetch information and perform actions in Google Chat. Authentication is a prerequisite for using the Google Chat REST API.",
  "servicePath": "",
  "title": "Google Chat API",
  "name": "chat",
  "mtlsRootUrl": "https://chat.mtls.googleapis.com/",
  "protocol": "rest",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "canonicalName": "Hangouts Chat",
  "basePath": ""
}
