{
  "protocol": "rest",
  "servicePath": "",
  "ownerDomain": "google.com",
  "canonicalName": "Hangouts Chat",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "revision": "20221112",
  "rootUrl": "https://chat.googleapis.com/",
  "description": "Enables apps to fetch information and perform actions in Google Chat. Authentication is a prerequisite for using the Google Chat REST API.",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/hangouts/chat",
  "name": "chat",
  "basePath": "",
  "resources": {
    "dms": {
      "methods": {
        "messages": {
          "flatPath": "v1/dms/{dmsId}/messages",
          "id": "chat.dms.messages",
          "path": "v1/{+parent}/messages",
          "httpMethod": "POST",
          "description": "Legacy path for creating message. Calling these will result in a BadRequest response."
        },
        "webhooks": {
          "id": "chat.dms.webhooks",
          "description": "Legacy path for creating message. Calling these will result in a BadRequest response.",
          "path": "v1/{+parent}/webhooks",
          "flatPath": "v1/dms/{dmsId}/webhooks",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "conversations": {
          "methods": {
            "messages": {
              "path": "v1/{+parent}/messages",
              "flatPath": "v1/dms/{dmsId}/conversations/{conversationsId}/messages",
              "description": "Legacy path for creating message. Calling these will result in a BadRequest response.",
              "id": "chat.dms.conversations.messages",
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "spaces": {
      "resources": {
        "members": {
          "methods": {
            "get": {
              "description": "Returns a membership. Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
              "scopes": [
                "https://www.googleapis.com/auth/chat.memberships"
              ],
              "id": "chat.spaces.members.get",
              "path": "v1/{+name}",
              "flatPath": "v1/spaces/{spacesId}/members/{membersId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "id": "chat.spaces.members.list",
              "scopes": [
                "https://www.googleapis.com/auth/chat.memberships"
              ],
              "flatPath": "v1/spaces/{spacesId}/members",
              "description": "Lists memberships in a space. Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
              "path": "v1/{+parent}/members"
            }
          }
        },
        "messages": {
          "methods": {
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "id": "chat.spaces.messages.update",
              "description": "Updates a message. For example usage, see [Update a message](https://developers.google.com/chat/api/guides/crudl/messages#update_a_message). Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "path": "v1/{+name}"
            },
            "create": {
              "description": "Creates a message. For example usage, see [Create a message](https://developers.google.com/chat/api/guides/crudl/messages#create_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer [...]",
              "httpMethod": "POST",
              "path": "v1/{+parent}/messages",
              "id": "chat.spaces.messages.create",
              "flatPath": "v1/spaces/{spacesId}/messages",
              "scopes": [
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.create"
              ]
            },
            "get": {
              "description": "Returns a message. For example usage, see [Read a message](https://developers.google.com/chat/api/guides/crudl/messages#read_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [Service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Prev[...]",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "scopes": [
                "https://www.googleapis.com/auth/chat.messages",
                "https://www.googleapis.com/auth/chat.messages.readonly"
              ],
              "id": "chat.spaces.messages.get",
              "path": "v1/{+name}",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/chat.messages"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}",
              "path": "v1/{+name}",
              "description": "Deletes a message. For example usage, see [Delete a message](https://developers.google.com/chat/api/guides/crudl/messages#delete_a_message). Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer [...]",
              "id": "chat.spaces.messages.delete"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "id": "chat.spaces.messages.attachments.get",
                  "description": "Gets the metadata of a message attachment. The attachment data is fetched using the media API. Requires [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts).",
                  "path": "v1/{+name}",
                  "flatPath": "v1/spaces/{spacesId}/messages/{messagesId}/attachments/{attachmentsId}",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      },
      "methods": {
        "list": {
          "id": "chat.spaces.list",
          "description": "Lists spaces the caller is a member of. Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain f[...]",
          "path": "v1/spaces",
          "flatPath": "v1/spaces",
          "httpMethod": "GET"
        },
        "get": {
          "path": "v1/{+name}",
          "flatPath": "v1/spaces/{spacesId}",
          "id": "chat.spaces.get",
          "httpMethod": "GET",
          "description": "Returns a space. Requires [authentication](https://developers.google.com/chat/api/guides/auth). Fully supports [service account authentication](https://developers.google.com/chat/api/guides/auth/service-accounts). Supports [user authentication](https://developers.google.com/chat/api/guides/auth/users) as part of the [Google Workspace Developer Preview Program](https://developers.google.com/workspace/preview), which grants early access to certain features. [User authenti[...]"
        },
        "webhooks": {
          "description": "Legacy path for creating message. Calling these will result in a BadRequest response.",
          "httpMethod": "POST",
          "id": "chat.spaces.webhooks",
          "flatPath": "v1/spaces/{spacesId}/webhooks",
          "path": "v1/{+parent}/webhooks"
        }
      }
    },
    "rooms": {
      "methods": {
        "webhooks": {
          "path": "v1/{+parent}/webhooks",
          "description": "Legacy path for creating message. Calling these will result in a BadRequest response.",
          "id": "chat.rooms.webhooks",
          "httpMethod": "POST",
          "flatPath": "v1/rooms/{roomsId}/webhooks"
        },
        "messages": {
          "flatPath": "v1/rooms/{roomsId}/messages",
          "description": "Legacy path for creating message. Calling these will result in a BadRequest response.",
          "httpMethod": "POST",
          "path": "v1/{+parent}/messages",
          "id": "chat.rooms.messages"
        }
      },
      "resources": {
        "conversations": {
          "methods": {
            "messages": {
              "httpMethod": "POST",
              "id": "chat.rooms.conversations.messages",
              "description": "Legacy path for creating message. Calling these will result in a BadRequest response.",
              "path": "v1/{+parent}/messages",
              "flatPath": "v1/rooms/{roomsId}/conversations/{conversationsId}/messages"
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "id": "chat.media.download",
          "flatPath": "v1/media/{mediaId}",
          "path": "v1/media/{+resourceName}",
          "description": "Downloads media. Download is supported on the URI `/v1/media/{+name}?alt=media`.",
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/chat.messages",
            "https://www.googleapis.com/auth/chat.messages.readonly"
          ]
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chat.messages": {
          "description": "View, compose, send, update, and delete messages, and add, view, and delete reactions to messages."
        },
        "https://www.googleapis.com/auth/chat.memberships": {
          "description": "View, add, and remove members from conversations in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.readonly": {
          "description": "view messages and reactions in Google Chat"
        },
        "https://www.googleapis.com/auth/chat.messages.create": {
          "description": "Compose and send messages in Google Chat"
        }
      }
    }
  },
  "baseUrl": "https://chat.googleapis.com/",
  "version": "v1",
  "version_module": true,
  "mtlsRootUrl": "https://chat.mtls.googleapis.com/",
  "title": "Google Chat API",
  "id": "chat:v1",
  "ownerName": "Google"
}
