{
  "ownerDomain": "google.com",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "canonicalName": "Chrome Management",
  "batchPath": "batch",
  "version": "v1",
  "id": "chromemanagement:v1",
  "name": "chromemanagement",
  "title": "Chrome Management API",
  "documentationLink": "http://developers.google.com/chrome/management/",
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "countChromeBrowsersNeedingAttention": {
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "findInstalledAppDevices": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "countChromeVersions": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions."
            },
            "countChromeDevicesThatNeedAttention": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countInstalledApps"
            },
            "countChromeHardwareFleetDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices"
            }
          }
        },
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.android.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "users": {
              "methods": {
                "list": {
                  "description": "List all telemetry users.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/users"
                },
                "get": {
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get telemetry user.",
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.telemetry.users.get"
                }
              }
            },
            "devices": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Get telemetry device."
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/devices",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "description": "List all telemetry devices."
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/events",
                  "description": "List telemetry events.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list"
                }
              }
            }
          }
        }
      }
    }
  },
  "ownerName": "Google",
  "basePath": "",
  "servicePath": "",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "kind": "discovery#restDescription",
  "version_module": true,
  "revision": "20230822",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/"
}
