{
  "discoveryVersion": "v1",
  "id": "chromemanagement:v1",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "protocol": "rest",
  "title": "Chrome Management API",
  "name": "chromemanagement",
  "basePath": "",
  "ownerDomain": "google.com",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "canonicalName": "Chrome Management",
  "ownerName": "Google",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "documentationLink": "http://developers.google.com/chrome/management/",
  "revision": "20230830",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "servicePath": "",
  "batchPath": "batch",
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "id": "chromemanagement.customers.apps.web.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "description": "Generate summary of app installation requests."
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry device.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}"
                },
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "description": "List all telemetry devices.",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/events",
                  "description": "List telemetry events.",
                  "httpMethod": "GET"
                }
              }
            },
            "users": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "httpMethod": "GET",
                  "description": "Get telemetry user."
                },
                "list": {
                  "path": "v1/{+parent}/telemetry/users",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry users.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.users.list"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry notification configs.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list"
                },
                "create": {
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config."
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "description": "Delete a telemetry notification config."
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "findInstalledAppDevices": {
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countChromeVersions": {
              "path": "v1/{+customer}/reports:countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions.",
              "id": "chromemanagement.customers.reports.countChromeVersions"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947)."
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices"
            },
            "countChromeBrowsersNeedingAttention": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention"
            },
            "countInstalledApps": {
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "description": "Generate report of app installations.",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "httpMethod": "GET"
            },
            "countChromeDevicesThatNeedAttention": {
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention"
            }
          }
        }
      }
    }
  },
  "kind": "discovery#restDescription"
}
