{
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "id": "chromemanagement:v1",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "version_module": true,
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "documentationLink": "http://developers.google.com/chrome/management/",
  "basePath": "",
  "protocol": "rest",
  "canonicalName": "Chrome Management",
  "revision": "20220331",
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "resources": {
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}"
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}"
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "description": "Generate summary of app installation requests.",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests"
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "description": "List all telemetry devices.",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeVersions": {
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions.",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "findInstalledAppDevices": {
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "description": "Generate report of devices that have a specified app installed.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countInstalledApps": {
              "path": "v1/{+customer}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "description": "Generate report of app installations.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "title": "Chrome Management API",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        }
      }
    }
  },
  "name": "chromemanagement",
  "version": "v1"
}
