{
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "name": "chromemanagement",
  "basePath": "",
  "servicePath": "",
  "discoveryVersion": "v1",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "title": "Chrome Management API",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "id": "chromemanagement:v1",
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "countChromeDevicesThatNeedAttention": {
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention"
            },
            "countPrintJobsByUser": {
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "description": "Get a summary of printing done by each user.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "findInstalledAppDevices": {
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of devices that have a specified app installed.",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countChromeBrowsersNeedingAttention": {
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET"
            },
            "countPrintJobsByPrinter": {
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "description": "Get a summary of printing done by each printer.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countInstalledApps": {
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "description": "Generate report of app installations.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countChromeVersions": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions"
            },
            "countChromeHardwareFleetDevices": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices"
            }
          }
        },
        "apps": {
          "resources": {
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}"
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}"
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "httpMethod": "GET"
            }
          }
        },
        "telemetry": {
          "resources": {
            "users": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry user.",
                  "id": "chromemanagement.customers.telemetry.users.get"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "description": "List all telemetry users.",
                  "path": "v1/{+parent}/telemetry/users",
                  "httpMethod": "GET"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/events",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "description": "List telemetry events.",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "description": "List all telemetry devices.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices"
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry device.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    }
  },
  "documentationLink": "http://developers.google.com/chrome/management/",
  "canonicalName": "Chrome Management",
  "revision": "20230322",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "batchPath": "batch",
  "protocol": "rest",
  "version": "v1",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "version_module": true
}
