{
  "protocol": "rest",
  "version_module": true,
  "baseUrl": "https://chromepolicy.googleapis.com/",
  "discoveryVersion": "v1",
  "version": "v1",
  "name": "chromepolicy",
  "resources": {
    "customers": {
      "resources": {
        "policies": {
          "resources": {
            "networks": {
              "methods": {
                "removeNetwork": {
                  "flatPath": "v1/customers/{customersId}/policies/networks:removeNetwork",
                  "description": "Remove an existing network by guid.",
                  "httpMethod": "POST",
                  "path": "v1/{+customer}/policies/networks:removeNetwork",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "id": "chromepolicy.customers.policies.networks.removeNetwork"
                },
                "defineNetwork": {
                  "id": "chromepolicy.customers.policies.networks.defineNetwork",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "httpMethod": "POST",
                  "description": "Define a new network.",
                  "path": "v1/{+customer}/policies/networks:defineNetwork",
                  "flatPath": "v1/customers/{customersId}/policies/networks:defineNetwork"
                },
                "removeCertificate": {
                  "flatPath": "v1/customers/{customersId}/policies/networks:removeCertificate",
                  "id": "chromepolicy.customers.policies.networks.removeCertificate",
                  "httpMethod": "POST",
                  "description": "Remove an existing certificate by guid.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "path": "v1/{+customer}/policies/networks:removeCertificate"
                },
                "defineCertificate": {
                  "path": "v1/{+customer}/policies/networks:defineCertificate",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "description": "Creates a certificate at a specified OU for a customer.",
                  "id": "chromepolicy.customers.policies.networks.defineCertificate",
                  "flatPath": "v1/customers/{customersId}/policies/networks:defineCertificate",
                  "httpMethod": "POST"
                }
              }
            },
            "groups": {
              "methods": {
                "batchDelete": {
                  "id": "chromepolicy.customers.policies.groups.batchDelete",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/policies/groups:batchDelete",
                  "description": "Delete multiple policy values that are applied to a specific group. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "path": "v1/{+customer}/policies/groups:batchDelete"
                },
                "updateGroupPriorityOrdering": {
                  "description": "Update a group priority ordering for an app. The target app must be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure the request will return the error details as part of the google.rpc.Status.",
                  "flatPath": "v1/customers/{customersId}/policies/groups:updateGroupPriorityOrdering",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "id": "chromepolicy.customers.policies.groups.updateGroupPriorityOrdering",
                  "path": "v1/{+customer}/policies/groups:updateGroupPriorityOrdering"
                },
                "listGroupPriorityOrdering": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy",
                    "https://www.googleapis.com/auth/chrome.management.policy.readonly"
                  ],
                  "path": "v1/{+customer}/policies/groups:listGroupPriorityOrdering",
                  "flatPath": "v1/customers/{customersId}/policies/groups:listGroupPriorityOrdering",
                  "description": "Retrieve a group priority ordering for an app. The target app must be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure the request will return the error details as part of the google.rpc.Status.",
                  "id": "chromepolicy.customers.policies.groups.listGroupPriorityOrdering",
                  "httpMethod": "POST"
                },
                "batchModify": {
                  "id": "chromepolicy.customers.policies.groups.batchModify",
                  "httpMethod": "POST",
                  "description": "Modify multiple policy values that are applied to a specific group. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "flatPath": "v1/customers/{customersId}/policies/groups:batchModify",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "path": "v1/{+customer}/policies/groups:batchModify"
                }
              }
            },
            "orgunits": {
              "methods": {
                "batchModify": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/policies/orgunits:batchModify",
                  "description": "Modify multiple policy values that are applied to a specific org unit. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "id": "chromepolicy.customers.policies.orgunits.batchModify",
                  "path": "v1/{+customer}/policies/orgunits:batchModify"
                },
                "batchInherit": {
                  "flatPath": "v1/customers/{customersId}/policies/orgunits:batchInherit",
                  "id": "chromepolicy.customers.policies.orgunits.batchInherit",
                  "path": "v1/{+customer}/policies/orgunits:batchInherit",
                  "description": "Modify multiple policy values that are applied to a specific org unit so that they now inherit the value from a parent (if applicable). All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ]
                }
              }
            }
          },
          "methods": {
            "resolve": {
              "path": "v1/{+customer}/policies:resolve",
              "description": "Gets the resolved policy values for a list of policies that match a search query.",
              "flatPath": "v1/customers/{customersId}/policies:resolve",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "id": "chromepolicy.customers.policies.resolve",
              "httpMethod": "POST"
            }
          }
        },
        "policySchemas": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/policySchemas/{policySchemasId}",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "description": "Get a specific policy schema for a customer by its resource name.",
              "id": "chromepolicy.customers.policySchemas.get"
            },
            "list": {
              "description": "Gets a list of policy schemas that match a specified filter value for a given customer.",
              "id": "chromepolicy.customers.policySchemas.list",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/policySchemas",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "path": "v1/{+parent}/policySchemas"
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "description": "Creates an enterprise file from the content provided by user. Returns a public download url for end user.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/chrome.management.policy"
          ],
          "id": "chromepolicy.media.upload",
          "flatPath": "v1/customers/{customersId}/policies/files:uploadPolicyFile",
          "supportsMediaUpload": true,
          "path": "v1/{+customer}/policies/files:uploadPolicyFile"
        }
      }
    }
  },
  "canonicalName": "Chrome Policy",
  "revision": "20231004",
  "basePath": "",
  "servicePath": "",
  "title": "Chrome Policy API",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.policy": {
          "description": "See, edit, create or delete policies applied to Chrome OS and Chrome Browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.policy.readonly": {
          "description": "See policies applied to Chrome OS and Chrome Browsers managed within your organization"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "documentationLink": "http://developers.google.com/chrome/policy",
  "id": "chromepolicy:v1",
  "rootUrl": "https://chromepolicy.googleapis.com/",
  "ownerName": "Google",
  "description": "The Chrome Policy API is a suite of services that allows Chrome administrators to control the policies applied to their managed Chrome OS devices and Chrome browsers.",
  "mtlsRootUrl": "https://chromepolicy.mtls.googleapis.com/"
}
