{
  "title": "Chrome Management API",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "version_module": true,
  "ownerName": "Google",
  "revision": "20230127",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "name": "chromemanagement",
  "servicePath": "",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "basePath": "",
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "documentationLink": "http://developers.google.com/chrome/management/",
  "id": "chromemanagement:v1",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "resources": {
    "customers": {
      "resources": {
        "telemetry": {
          "resources": {
            "users": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/users",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "description": "List all telemetry users.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/users"
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "httpMethod": "GET",
                  "description": "Get telemetry user."
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List telemetry events.",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "path": "v1/{+parent}/telemetry/events",
                  "httpMethod": "GET"
                }
              }
            },
            "devices": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry device.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.devices.get"
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "List all telemetry devices.",
                  "path": "v1/{+parent}/telemetry/devices"
                }
              }
            }
          }
        },
        "apps": {
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "id": "chromemanagement.customers.apps.android.get",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.chrome.get"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}"
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "description": "Generate summary of app installation requests.",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "reports": {
          "methods": {
            "countInstalledApps": {
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeVersions": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions."
            },
            "findInstalledAppDevices": {
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "description": "Generate report of devices that have a specified app installed."
            },
            "countChromeDevicesThatNeedAttention": {
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET"
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            }
          }
        }
      }
    }
  },
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "version": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "canonicalName": "Chrome Management"
}
