{
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "kind": "discovery#restDescription",
  "name": "chromemanagement",
  "ownerDomain": "google.com",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "batchPath": "batch",
  "canonicalName": "Chrome Management",
  "revision": "20231108",
  "protocol": "rest",
  "servicePath": "",
  "basePath": "",
  "ownerName": "Google",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "title": "Chrome Management API",
  "documentationLink": "http://developers.google.com/chrome/management/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        }
      }
    }
  },
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "resources": {
    "customers": {
      "resources": {
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "path": "v1/{+parent}/telemetry/devices",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "description": "List all telemetry devices.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "path": "v1/{+name}",
                  "description": "Get telemetry device.",
                  "httpMethod": "GET"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "description": "List telemetry events.",
                  "path": "v1/{+parent}/telemetry/events",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry users.",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/users"
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "httpMethod": "GET",
                  "description": "Get telemetry user.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs."
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "description": "Create a telemetry notification config.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "httpMethod": "DELETE",
                  "description": "Delete a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete"
                }
              }
            }
          }
        },
        "apps": {
          "resources": {
            "web": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "id": "chromemanagement.customers.apps.web.get",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}"
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "id": "chromemanagement.customers.apps.android.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "httpMethod": "GET",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            }
          }
        },
        "reports": {
          "methods": {
            "countPrintJobsByPrinter": {
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each printer.",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter"
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countInstalledApps": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "description": "Generate report of app installations."
            },
            "countChromeDevicesThatNeedAttention": {
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947)."
            },
            "countPrintJobsByUser": {
              "description": "Get a summary of printing done by each user.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser"
            },
            "countChromeVersions": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions.",
              "httpMethod": "GET"
            },
            "countChromeBrowsersNeedingAttention": {
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET"
            },
            "countChromeHardwareFleetDevices": {
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices"
            },
            "enumeratePrintJobs": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "description": "Get a list of print jobs.",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs"
            }
          }
        }
      }
    }
  },
  "id": "chromemanagement:v1",
  "version": "v1",
  "version_module": true
}
