{
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "version": "v1",
  "version_module": true,
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "name": "chromemanagement",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from Chrome OS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "canonicalName": "Chrome Management",
  "revision": "20220711",
  "documentationLink": "http://developers.google.com/chrome/management/",
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET"
            }
          },
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}"
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry devices.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices"
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Get telemetry device.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeVersions": {
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions.",
              "httpMethod": "GET"
            },
            "countChromeDevicesThatNeedAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention"
            },
            "findInstalledAppDevices": {
              "description": "Generate report of devices that have a specified app installed.",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:findInstalledAppDevices"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "countInstalledApps": {
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "description": "Generate report of app installations.",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countInstalledApps"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "id": "chromemanagement:v1",
  "title": "Chrome Management API",
  "protocol": "rest"
}
