{
  "documentationLink": "https://cloud.google.com/identity/",
  "revision": "20220125",
  "version": "v1beta1",
  "description": "API for provisioning and managing identity resources.",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        }
      }
    }
  },
  "version_module": true,
  "basePath": "",
  "discoveryVersion": "v1",
  "canonicalName": "Cloud Identity",
  "batchPath": "batch",
  "protocol": "rest",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "servicePath": "",
  "resources": {
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v1beta1/{+name}",
              "description": "Retrieves a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}"
            },
            "getMembershipGraph": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the response will contain all membership paths between the group and the member.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:getMembershipGraph",
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1beta1/{+parent}/memberships:getMembershipGraph",
              "httpMethod": "GET"
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1beta1/{+parent}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "description": "Lists the `Membership`s within a `Group`."
            },
            "modifyMembershipRoles": {
              "path": "v1beta1/{+name}:modifyMembershipRoles",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles"
            },
            "lookup": {
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup",
              "path": "v1beta1/{+parent}/memberships:lookup"
            },
            "searchTransitiveGroups": {
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+name}"
            },
            "checkTransitiveMembership": {
              "httpMethod": "GET",
              "path": "v1beta1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor must have view permissions to at least one transitive membership between the member and group."
            },
            "searchTransitiveMemberships": {
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveMemberships"
            },
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "path": "v1beta1/{+parent}/memberships",
              "description": "Creates a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "httpMethod": "POST"
            }
          }
        }
      },
      "methods": {
        "getSecuritySettings": {
          "flatPath": "v1beta1/groups/{groupsId}/securitySettings",
          "httpMethod": "GET",
          "path": "v1beta1/{+name}",
          "description": "Get Security Settings",
          "id": "cloudidentity.groups.getSecuritySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.list",
          "path": "v1beta1/groups",
          "flatPath": "v1beta1/groups",
          "description": "Lists the `Group` resources under a customer or namespace.",
          "httpMethod": "GET"
        },
        "updateSecuritySettings": {
          "description": "Update Security Settings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.updateSecuritySettings",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}/securitySettings",
          "httpMethod": "PATCH"
        },
        "create": {
          "description": "Creates a `Group`.",
          "path": "v1beta1/groups",
          "httpMethod": "POST",
          "id": "cloudidentity.groups.create",
          "flatPath": "v1beta1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "patch": {
          "description": "Updates a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}",
          "id": "cloudidentity.groups.patch"
        },
        "get": {
          "flatPath": "v1beta1/groups/{groupsId}",
          "path": "v1beta1/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.get",
          "description": "Retrieves a `Group`."
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "path": "v1beta1/groups:lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/groups:lookup",
          "httpMethod": "GET"
        },
        "search": {
          "path": "v1beta1/groups:search",
          "id": "cloudidentity.groups.search",
          "flatPath": "v1beta1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Searches for `Group` resources matching a specified query.",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "httpMethod": "DELETE",
          "id": "cloudidentity.groups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}"
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "httpMethod": "POST",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "description": "Approves device to access user data.",
              "path": "v1beta1/{+name}:approve"
            },
            "cancelWipe": {
              "path": "v1beta1/{+name}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "httpMethod": "POST"
            },
            "block": {
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "path": "v1beta1/{+name}:block",
              "id": "cloudidentity.devices.deviceUsers.block",
              "httpMethod": "POST",
              "description": "Blocks device from accessing user data"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1beta1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data."
            },
            "get": {
              "path": "v1beta1/{+name}",
              "description": "Retrieves the specified DeviceUser",
              "httpMethod": "GET",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "lookup": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "httpMethod": "GET",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers:lookup",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "path": "v1beta1/{+parent}:lookup"
            },
            "list": {
              "description": "Lists/Searches DeviceUsers.",
              "path": "v1beta1/{+parent}/deviceUsers",
              "httpMethod": "GET",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers",
              "id": "cloudidentity.devices.deviceUsers.list"
            },
            "wipe": {
              "description": "Wipes the user's account on a device.",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "path": "v1beta1/{+name}:wipe",
              "httpMethod": "POST",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET",
                  "path": "v1beta1/{+name}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                },
                "patch": {
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1beta1/{+name}",
                  "httpMethod": "PATCH"
                }
              }
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "cloudidentity.devices.get",
          "httpMethod": "GET",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/devices/{devicesId}",
          "description": "Retrieves the specified device."
        },
        "list": {
          "description": "Lists/Searches devices.",
          "id": "cloudidentity.devices.list",
          "path": "v1beta1/devices",
          "httpMethod": "GET",
          "flatPath": "v1beta1/devices"
        },
        "wipe": {
          "description": "Wipes all data on the specified device.",
          "path": "v1beta1/{+name}:wipe",
          "httpMethod": "POST",
          "flatPath": "v1beta1/devices/{devicesId}:wipe",
          "id": "cloudidentity.devices.wipe"
        },
        "delete": {
          "flatPath": "v1beta1/devices/{devicesId}",
          "description": "Deletes the specified device.",
          "id": "cloudidentity.devices.delete",
          "path": "v1beta1/{+name}",
          "httpMethod": "DELETE"
        },
        "cancelWipe": {
          "id": "cloudidentity.devices.cancelWipe",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
          "flatPath": "v1beta1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST",
          "path": "v1beta1/{+name}:cancelWipe"
        },
        "create": {
          "path": "v1beta1/devices",
          "flatPath": "v1beta1/devices",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.create",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "cancel": {
              "id": "cloudidentity.customers.userinvitations.cancel",
              "path": "v1beta1/{+name}:cancel",
              "httpMethod": "POST",
              "description": "Cancels a UserInvitation that was already sent.",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel"
            },
            "list": {
              "path": "v1beta1/{+parent}/userinvitations",
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.list",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains."
            },
            "isInvitableUser": {
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "httpMethod": "GET",
              "path": "v1beta1/{+name}:isInvitableUser"
            },
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "httpMethod": "GET",
              "path": "v1beta1/{+name}"
            },
            "send": {
              "httpMethod": "POST",
              "id": "cloudidentity.customers.userinvitations.send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "path": "v1beta1/{+name}:send"
            }
          }
        }
      }
    }
  },
  "name": "cloudidentity",
  "id": "cloudidentity:v1beta1",
  "kind": "discovery#restDescription",
  "title": "Cloud Identity API",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "ownerName": "Google"
}
