{
  "discoveryVersion": "v1",
  "description": "The Cloud Channel API enables Google Cloud partners to have a single unified resale platform and APIs across all of Google Cloud including GCP, Workspace, Maps and Chrome.",
  "resources": {
    "operations": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "path": "v1/{+name}",
          "id": "cloudchannel.operations.list",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "flatPath": "v1/operations"
        },
        "delete": {
          "id": "cloudchannel.operations.delete",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        },
        "cancel": {
          "flatPath": "v1/operations/{operationsId}:cancel",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "id": "cloudchannel.operations.cancel"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "id": "cloudchannel.operations.get",
          "httpMethod": "GET"
        }
      }
    },
    "products": {
      "methods": {
        "list": {
          "description": "Lists the Products the reseller is authorized to sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
          "id": "cloudchannel.products.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "v1/products",
          "path": "v1/products"
        }
      },
      "resources": {
        "skus": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v1/{+parent}/skus",
              "flatPath": "v1/products/{productsId}/skus",
              "description": "Lists the SKUs for a product the reseller is authorized to sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
              "id": "cloudchannel.products.skus.list",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ]
            }
          }
        }
      }
    },
    "accounts": {
      "methods": {
        "listTransferableOffers": {
          "flatPath": "v1/accounts/{accountsId}:listTransferableOffers",
          "httpMethod": "POST",
          "id": "cloudchannel.accounts.listTransferableOffers",
          "description": "List TransferableOffers of a customer based on Cloud Identity ID or Customer Name in the request. Use this method when a reseller gets the entitlement information of an unowned customer. The reseller should provide the customer's Cloud Identity ID or Customer Name. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller and has no auth token. * The customer provided incorrect reseller information when generating auth token. * The reselle[...]",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "path": "v1/{+parent}:listTransferableOffers"
        },
        "listTransferableSkus": {
          "httpMethod": "POST",
          "id": "cloudchannel.accounts.listTransferableSkus",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "path": "v1/{+parent}:listTransferableSkus",
          "description": "List TransferableSkus of a customer based on the Cloud Identity ID or Customer Name in the request. Use this method to list the entitlements information of an unowned customer. You should provide the customer's Cloud Identity ID or Customer Name. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller and has no auth token. * The supplied auth token is invalid. * The reseller account making the request is different from the reseller acco[...]",
          "flatPath": "v1/accounts/{accountsId}:listTransferableSkus"
        },
        "unregister": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "httpMethod": "POST",
          "path": "v1/{+account}:unregister",
          "id": "cloudchannel.accounts.unregister",
          "description": "Unregisters a service account with subscriber privileges on the Cloud Pub/Sub topic created for this Channel Services account. If there are no service accounts left with subscriber privileges, this deletes the topic. You can call ListSubscribers to check for these accounts. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: [...]",
          "flatPath": "v1/accounts/{accountsId}:unregister"
        },
        "register": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "v1/accounts/{accountsId}:register",
          "description": "Registers a service account with subscriber privileges on the Cloud Pub/Sub topic for this Channel Services account. After you create a subscriber, you get the events through SubscriberEvent Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INTERNAL: Any non-user error r[...]",
          "id": "cloudchannel.accounts.register",
          "path": "v1/{+account}:register"
        },
        "checkCloudIdentityAccountsExist": {
          "description": "Confirms the existence of Cloud Identity accounts based on the domain and if the Cloud Identity accounts are owned by the reseller. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INVALID_VALUE: Invalid domain value in the request. Return value: A list of CloudIdentityCustomerAccount resources for the dom[...]",
          "path": "v1/{+parent}:checkCloudIdentityAccountsExist",
          "flatPath": "v1/accounts/{accountsId}:checkCloudIdentityAccountsExist",
          "id": "cloudchannel.accounts.checkCloudIdentityAccountsExist",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "httpMethod": "POST"
        },
        "listSubscribers": {
          "description": "Lists service accounts with subscriber privileges on the Cloud Pub/Sub topic created for this Channel Services account. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The topic resource doesn't exist. * INTERNAL: Any non-user error related to a technical is[...]",
          "path": "v1/{+account}:listSubscribers",
          "id": "cloudchannel.accounts.listSubscribers",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "v1/accounts/{accountsId}:listSubscribers",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "reports": {
          "methods": {
            "list": {
              "path": "v1/{+parent}/reports",
              "id": "cloudchannel.accounts.reports.list",
              "description": "Lists the reports that RunReportJob can run. These reports include an ID, a description, and the list of columns that will be in the result.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/apps.reports.usage.readonly"
              ],
              "flatPath": "v1/accounts/{accountsId}/reports"
            },
            "run": {
              "description": "Begins generation of data for a given report. The report identifier is a UID (for example, `613bf59q`). Possible error codes: * PERMISSION_DENIED: The user doesn't have access to this report. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The report identifier was not found. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any non-user error related to a techni[...]",
              "id": "cloudchannel.accounts.reports.run",
              "path": "v1/{+name}:run",
              "scopes": [
                "https://www.googleapis.com/auth/apps.reports.usage.readonly"
              ],
              "flatPath": "v1/accounts/{accountsId}/reports/{reportsId}:run",
              "httpMethod": "POST"
            }
          }
        },
        "customers": {
          "methods": {
            "import": {
              "description": "Imports a Customer from the Cloud Identity associated with the provided Cloud Identity ID or domain before a TransferEntitlements call. If a linked Customer already exists and overwrite_if_exists is true, it will update that Customer's data. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * NOT_FOUND: Cloud Identity doesn't exist or was deleted. * INVALID_ARGUMENT: Required[...]",
              "flatPath": "v1/accounts/{accountsId}/customers:import",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "path": "v1/{+parent}/customers:import",
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.customers.import"
            },
            "transferEntitlements": {
              "description": "Transfers customer entitlements to new reseller. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: The SKU was already transferred for the customer. * CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires domain verification to transfer, but the domain is not verified. * An A[...]",
              "path": "v1/{+parent}:transferEntitlements",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:transferEntitlements",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "id": "cloudchannel.accounts.customers.transferEntitlements"
            },
            "list": {
              "id": "cloudchannel.accounts.customers.list",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/accounts/{accountsId}/customers",
              "description": "List Customers. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: List of Customers, or an empty list if there are no customers.",
              "path": "v1/{+parent}/customers"
            },
            "listPurchasableSkus": {
              "path": "v1/{+customer}:listPurchasableSkus",
              "id": "cloudchannel.accounts.customers.listPurchasableSkus",
              "description": "Lists the following: * SKUs that you can purchase for a customer * SKUs that you can upgrade or downgrade for an entitlement. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:listPurchasableSkus",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "httpMethod": "GET"
            },
            "provisionCloudIdentity": {
              "httpMethod": "POST",
              "description": "Creates a Cloud Identity for the given customer using the customer's information, or the information provided here. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer was not found. * ALREADY_EXISTS: The customer's primary email already exists. Retry after changing the customer's primary contact email. * INTERNAL: Any non-user error [...]",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:provisionCloudIdentity",
              "path": "v1/{+customer}:provisionCloudIdentity",
              "id": "cloudchannel.accounts.customers.provisionCloudIdentity"
            },
            "transferEntitlementsToGoogle": {
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:transferEntitlementsToGoogle",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "path": "v1/{+parent}:transferEntitlementsToGoogle",
              "id": "cloudchannel.accounts.customers.transferEntitlementsToGoogle",
              "description": "Transfers customer entitlements from their current reseller to Google. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: The SKU was already transferred for the customer. * CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires domain verification to transfer, but the domain i[...]"
            },
            "patch": {
              "description": "Updates an existing Customer resource for the reseller or distributor. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: No Customer resource found for the name in the request. Return value: The updated Customer resource.",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "path": "v1/{+name}",
              "httpMethod": "PATCH",
              "id": "cloudchannel.accounts.customers.patch"
            },
            "get": {
              "id": "cloudchannel.accounts.customers.get",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}",
              "path": "v1/{+name}",
              "description": "Returns the requested Customer resource. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer resource doesn't exist. Usually the result of an invalid name parameter. Return value: The Customer resource.",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1/{+parent}/customers",
              "flatPath": "v1/accounts/{accountsId}/customers",
              "httpMethod": "POST",
              "description": "Creates a new Customer resource under the reseller or distributor account. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Domain field value doesn't match the primary email domain. Return value: The newly created Customer resource.",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "id": "cloudchannel.accounts.customers.create"
            },
            "delete": {
              "description": "Deletes the given Customer permanently. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The customer has existing entitlements. * NOT_FOUND: No Customer resource found for the name in the request.",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}",
              "id": "cloudchannel.accounts.customers.delete",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ]
            },
            "listPurchasableOffers": {
              "description": "Lists the following: * Offers that you can purchase for a customer. * Offers that you can change for an entitlement. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.customers.listPurchasableOffers",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:listPurchasableOffers",
              "path": "v1/{+customer}:listPurchasableOffers"
            }
          },
          "resources": {
            "customerRepricingConfigs": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs",
                  "description": "Lists information about how a Reseller modifies their bill before sending it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The CustomerRepricingConfig specified does not exist or is not associated with the given account. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If succ[...]",
                  "path": "v1/{+parent}/customerRepricingConfigs",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.list"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.patch",
                  "description": "Updates a CustomerRepricingConfig. Call this method to set modifications for a specific customer's bill. This method overwrites the existing CustomerRepricingConfig. You can only update configs if the RepricingConfig.effective_invoice_month is a future month. To make changes to configs for the current month, use CreateCustomerRepricingConfig, taking note of its restrictions. You cannot update the RepricingConfig.effective_invoice_month. When updating a config in[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}",
                  "path": "v1/{+name}",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Deletes the given CustomerRepricingConfig permanently. You can only delete configs if their RepricingConfig.effective_invoice_month is set to a date after the current month. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The CustomerRepricingConfig is active or in the past. * NOT_FOUND: No CustomerRepricingConfig f[...]"
                },
                "create": {
                  "path": "v1/{+parent}/customerRepricingConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.create",
                  "description": "Creates a CustomerRepricingConfig. Call this method to set modifications for a specific customer's bill. You can only create configs if the RepricingConfig.effective_invoice_month is a future month. If needed, you can create a config for the current month, with some restrictions. When creating a config for a future month, make sure there are no existing configs for that RepricingConfig.effective_invoice_month. The following restrictions are for creating configs [...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Gets information about how a Reseller modifies their bill before sending it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The CustomerRepricingConfig was not found. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If successful, the CustomerRepricingConfig resource, otherwise [...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.get"
                }
              }
            },
            "entitlements": {
              "methods": {
                "changeRenewalSettings": {
                  "description": "Updates the renewal settings for an existing customer entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * NOT_COMMITMENT_PLAN: Renewal Settings are only applicable for a commitment plan. Ca[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeRenewalSettings",
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.customers.entitlements.changeRenewalSettings",
                  "path": "v1/{+name}:changeRenewalSettings",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ]
                },
                "activate": {
                  "description": "Activates a previously suspended entitlement. Entitlements suspended for pending ToS acceptance can't be activated using this method. An entitlement activation is a long-running operation and it updates the state of the customer entitlement. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUN[...]",
                  "path": "v1/{+name}:activate",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:activate",
                  "id": "cloudchannel.accounts.customers.entitlements.activate",
                  "httpMethod": "POST"
                },
                "create": {
                  "id": "cloudchannel.accounts.customers.entitlements.create",
                  "description": "Creates an entitlement for a customer. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * There is already a customer entitlement for a SKU from the same product family. * INVALID_VALUE: Make sure the OfferId is valid. If it is, contact Google Channel support for further troubleshooting. * NOT_FOUND: The customer or offer resource was not found. * ALR[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements",
                  "path": "v1/{+parent}/entitlements",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ]
                },
                "cancel": {
                  "id": "cloudchannel.accounts.customers.entitlements.cancel",
                  "httpMethod": "POST",
                  "description": "Cancels a previously fulfilled entitlement. An entitlement cancellation is a long-running operation. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * FAILED_PRECONDITION: There are Google Cloud projects linked to the Google Cloud entitlement's Cloud Billing subaccount. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement reso[...]",
                  "path": "v1/{+name}:cancel",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ]
                },
                "changeParameters": {
                  "path": "v1/{+name}:changeParameters",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeParameters",
                  "description": "Change parameters of the entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. For example, the number of seats being changed is greater than the allowed number of max seats, or decreasing seats for a commitment based plan. * NOT_FOUND: E[...]",
                  "id": "cloudchannel.accounts.customers.entitlements.changeParameters",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "POST"
                },
                "startPaidService": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "path": "v1/{+name}:startPaidService",
                  "id": "cloudchannel.accounts.customers.entitlements.startPaidService",
                  "httpMethod": "POST",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:startPaidService",
                  "description": "Starts paid service for a trial entitlement. Starts paid service for a trial entitlement immediately. This method is only applicable if a plan is set up for a trial entitlement but has some trial days remaining. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * FAILED_PRECONDITION/NOT_IN_TRIAL: This method o[...]"
                },
                "suspend": {
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:suspend",
                  "id": "cloudchannel.accounts.customers.entitlements.suspend",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "POST",
                  "description": "Suspends a previously fulfilled entitlement. An entitlement suspension is a long-running operation. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * NOT_ACTIVE: Entitlement is not active. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel support. * UNKNOWN: An[...]",
                  "path": "v1/{+name}:suspend"
                },
                "lookupOffer": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Returns the requested Offer resource. Possible error codes: * PERMISSION_DENIED: The entitlement doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement or offer was not found. Return value: The Offer resource.",
                  "id": "cloudchannel.accounts.customers.entitlements.lookupOffer",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:lookupOffer",
                  "path": "v1/{+entitlement}:lookupOffer",
                  "httpMethod": "GET"
                },
                "list": {
                  "description": "Lists Entitlements belonging to a customer. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: A list of the customer's Entitlements.",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "GET",
                  "id": "cloudchannel.accounts.customers.entitlements.list",
                  "path": "v1/{+parent}/entitlements"
                },
                "listEntitlementChanges": {
                  "id": "cloudchannel.accounts.customers.entitlements.listEntitlementChanges",
                  "path": "v1/{+parent}:listEntitlementChanges",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "GET",
                  "description": "List entitlement history. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different. * INVALID_ARGUMENT: Missing or invalid required fields in the request. * NOT_FOUND: The parent resource doesn't exist. Usually the result of an invalid name parameter. * INTERNAL: Any non-user error related to a technical issue in the backend. In this case, contact CloudChannel support. * UNKNOWN: Any non-u[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:listEntitlementChanges"
                },
                "get": {
                  "id": "cloudchannel.accounts.customers.entitlements.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}",
                  "description": "Returns the requested Entitlement resource. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer entitlement was not found. Return value: The requested Entitlement resource."
                },
                "changeOffer": {
                  "path": "v1/{+name}:changeOffer",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeOffer",
                  "id": "cloudchannel.accounts.customers.entitlements.changeOffer",
                  "description": "Updates the Offer for an existing customer entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Offer or Entitlement resource not found. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Clo[...]"
                }
              }
            }
          }
        },
        "reportJobs": {
          "methods": {
            "fetchReportResults": {
              "id": "cloudchannel.accounts.reportJobs.fetchReportResults",
              "flatPath": "v1/accounts/{accountsId}/reportJobs/{reportJobsId}:fetchReportResults",
              "description": "Retrieves data generated by CloudChannelReportsService.RunReportJob.",
              "path": "v1/{+reportJob}:fetchReportResults",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/apps.reports.usage.readonly"
              ]
            }
          }
        },
        "offers": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the Offers the reseller can sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
              "id": "cloudchannel.accounts.offers.list",
              "flatPath": "v1/accounts/{accountsId}/offers",
              "path": "v1/{+parent}/offers"
            }
          }
        },
        "channelPartnerLinks": {
          "resources": {
            "customers": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "GET",
                  "description": "Returns the requested Customer resource. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer resource doesn't exist. Usually the result of an invalid name parameter. Return value: The Customer resource.",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.get"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.patch",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}",
                  "description": "Updates an existing Customer resource for the reseller or distributor. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: No Customer resource found for the name in the request. Return value: The updated Customer resource.",
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/customers",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers",
                  "description": "List Customers. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: List of Customers, or an empty list if there are no customers."
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a new Customer resource under the reseller or distributor account. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Domain field value doesn't match the primary email domain. Return value: The newly created Customer resource.",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.create",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers",
                  "path": "v1/{+parent}/customers"
                },
                "delete": {
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "description": "Deletes the given Customer permanently. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The customer has existing entitlements. * NOT_FOUND: No Customer resource found for the name in the request.",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}"
                },
                "import": {
                  "httpMethod": "POST",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers:import",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.import",
                  "description": "Imports a Customer from the Cloud Identity associated with the provided Cloud Identity ID or domain before a TransferEntitlements call. If a linked Customer already exists and overwrite_if_exists is true, it will update that Customer's data. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * NOT_FOUND: Cloud Identity doesn't exist or was deleted. * INVALID_ARGUMENT: Requ[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "path": "v1/{+parent}/customers:import"
                }
              }
            },
            "channelPartnerRepricingConfigs": {
              "methods": {
                "list": {
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Lists information about how a Reseller modifies their bill before sending it to a ChannelPartner. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The ChannelPartnerRepricingConfig specified does not exist or is not associated with the given account. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Va[...]",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs",
                  "path": "v1/{+parent}/channelPartnerRepricingConfigs",
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Creates a ChannelPartnerRepricingConfig. Call this method to set modifications for a specific ChannelPartner's bill. You can only create configs if the RepricingConfig.effective_invoice_month is a future month. If needed, you can create a config for the current month, with some restrictions. When creating a config for a future month, make sure there are no existing configs for that RepricingConfig.effective_invoice_month. The following restrictions are for creat[...]",
                  "path": "v1/{+parent}/channelPartnerRepricingConfigs",
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "description": "Updates a ChannelPartnerRepricingConfig. Call this method to set modifications for a specific ChannelPartner's bill. This method overwrites the existing CustomerRepricingConfig. You can only update configs if the RepricingConfig.effective_invoice_month is a future month. To make changes to configs for the current month, use CreateChannelPartnerRepricingConfig, taking note of its restrictions. You cannot update the RepricingConfig.effective_invoice_month. When up[...]",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.patch",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Gets information about how a Distributor modifies their bill before sending it to a ChannelPartner. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The ChannelPartnerRepricingConfig was not found. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If successful, the ChannelPartnerRepricingConfig[...]",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                },
                "delete": {
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.delete",
                  "path": "v1/{+name}",
                  "description": "Deletes the given ChannelPartnerRepricingConfig permanently. You can only delete configs if their RepricingConfig.effective_invoice_month is set to a date after the current month. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The ChannelPartnerRepricingConfig is active or in the past. * NOT_FOUND: No ChannelPartne[...]",
                  "httpMethod": "DELETE"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Updates a channel partner link. Distributors call this method to change a link's status. For example, to suspend a partner link. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Link state cannot change from invited to active or suspended. * Cannot send [...]",
              "id": "cloudchannel.accounts.channelPartnerLinks.patch"
            },
            "create": {
              "description": "Initiates a channel partner link between a distributor and a reseller, or between resellers in an n-tier reseller channel. Invited partners need to follow the invite_link_uri provided in the response to accept. After accepting the invitation, a link is set up between the two parties. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API reque[...]",
              "httpMethod": "POST",
              "path": "v1/{+parent}/channelPartnerLinks",
              "id": "cloudchannel.accounts.channelPartnerLinks.create",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ]
            },
            "get": {
              "path": "v1/{+name}",
              "id": "cloudchannel.accounts.channelPartnerLinks.get",
              "httpMethod": "GET",
              "description": "Returns the requested ChannelPartnerLink resource. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: ChannelPartnerLink resource not found because of an invalid channel partner link name. Return value: The ChannelPartnerLink resource.",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}"
            },
            "list": {
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.channelPartnerLinks.list",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "path": "v1/{+parent}/channelPartnerLinks",
              "description": "List ChannelPartnerLinks belonging to a distributor. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: The list of the distributor account's ChannelPartnerLink resources."
            }
          }
        }
      }
    }
  },
  "documentationLink": "https://cloud.google.com/channel",
  "canonicalName": "Cloudchannel",
  "rootUrl": "https://cloudchannel.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "cloudchannel",
  "baseUrl": "https://cloudchannel.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "id": "cloudchannel:v1",
  "title": "Cloud Channel API",
  "basePath": "",
  "mtlsRootUrl": "https://cloudchannel.mtls.googleapis.com/",
  "version": "v1",
  "batchPath": "batch",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "revision": "20230326",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/apps.reports.usage.readonly": {
          "description": "View usage reports for your G Suite domain"
        },
        "https://www.googleapis.com/auth/apps.order": {
          "description": "Manage users on your domain"
        }
      }
    }
  },
  "ownerName": "Google",
  "servicePath": ""
}
