{
  "canonicalName": "Cloud Search",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "basePath": "",
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "resources": {
    "operations": {
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "path": "v1/{+name}/lro",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.operations.lro.list",
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the oper[...]",
              "httpMethod": "GET",
              "flatPath": "v1/operations/{operationsId}/lro"
            }
          }
        }
      },
      "methods": {
        "get": {
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "id": "cloudsearch.operations.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "path": "v1/{+name}"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a[...]",
          "path": "v1/media/{+resourceName}",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "id": "cloudsearch.media.upload",
          "flatPath": "v1/media/{mediaId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ]
        }
      }
    },
    "stats": {
      "methods": {
        "getUser": {
          "flatPath": "v1/stats/user",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "path": "v1/stats/user",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getUser"
        },
        "getSearchapplication": {
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getSearchapplication",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "path": "v1/stats/searchapplication",
          "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/searchapplication"
        },
        "getIndex": {
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getIndex",
          "path": "v1/stats/index",
          "flatPath": "v1/stats/index",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute."
        },
        "getQuery": {
          "httpMethod": "GET",
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "id": "cloudsearch.stats.getQuery",
          "flatPath": "v1/stats/query",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "path": "v1/stats/query"
        },
        "getSession": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "path": "v1/stats/session",
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "id": "cloudsearch.stats.getSession",
          "httpMethod": "GET",
          "flatPath": "v1/stats/session"
        }
      },
      "resources": {
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "id": "cloudsearch.stats.user.searchapplications.get",
                  "path": "v1/stats/user/{+name}"
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/stats/query/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute."
                }
              }
            }
          }
        },
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
                  "path": "v1/stats/index/{+name}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}"
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "path": "v1/stats/session/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "query": {
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "id": "cloudsearch.query.sources.list",
              "path": "v1/query/sources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "httpMethod": "GET",
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
              "flatPath": "v1/query/sources"
            }
          }
        }
      },
      "methods": {
        "suggest": {
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "flatPath": "v1/query/suggest",
          "id": "cloudsearch.query.suggest",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "path": "v1/query/suggest"
        },
        "search": {
          "id": "cloudsearch.query.search",
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide [...]",
          "flatPath": "v1/query/search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "path": "v1/query/search",
          "httpMethod": "POST"
        }
      }
    },
    "debug": {
      "resources": {
        "identitysources": {
          "resources": {
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            },
            "unmappedids": {
              "methods": {
                "list": {
                  "path": "v1/debug/{+parent}/unmappedids",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            }
          }
        },
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "searchByViewUrl": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "POST"
                },
                "checkAccess": {
                  "description": "Checks whether an item is accessible by specified principal. Principal must be a user; groups and domain values aren't supported. **Note:** This API requires an admin account to execute.",
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess"
                }
              },
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "path": "v1/debug/{+parent}/unmappedids",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "httpMethod": "GET",
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "searchapplications": {
          "methods": {
            "reset": {
              "httpMethod": "POST",
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.settings.searchapplications.reset",
              "path": "v1/settings/{+name}:reset"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "id": "cloudsearch.settings.searchapplications.delete",
              "path": "v1/settings/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a search application. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.searchapplications.create",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications"
            },
            "update": {
              "id": "cloudsearch.settings.searchapplications.update",
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "path": "v1/settings/{+name}",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}"
            },
            "get": {
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.settings.searchapplications.get"
            },
            "list": {
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
              "httpMethod": "GET",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.settings.searchapplications.list",
              "flatPath": "v1/settings/searchapplications"
            }
          }
        },
        "datasources": {
          "methods": {
            "delete": {
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.delete",
              "path": "v1/settings/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "get": {
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.get",
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute."
            },
            "update": {
              "id": "cloudsearch.settings.datasources.update",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "PUT",
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}"
            },
            "list": {
              "description": "Lists datasources. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.list",
              "httpMethod": "GET",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "create": {
              "flatPath": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.create",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "POST",
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute."
            }
          }
        }
      },
      "methods": {
        "getCustomer": {
          "flatPath": "v1/settings/customer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "id": "cloudsearch.settings.getCustomer",
          "description": "Get customer settings. **Note:** This API requires an admin account to execute.",
          "httpMethod": "GET"
        },
        "updateCustomer": {
          "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "path": "v1/settings/customer",
          "id": "cloudsearch.settings.updateCustomer",
          "flatPath": "v1/settings/customer"
        }
      }
    },
    "v1": {
      "methods": {
        "initializeCustomer": {
          "flatPath": "v1:initializeCustomer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute.",
          "httpMethod": "POST",
          "id": "cloudsearch.initializeCustomer",
          "path": "v1:initializeCustomer"
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "deleteSchema": {
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "path": "v1/indexing/{+name}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "DELETE"
            },
            "getSchema": {
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "GET",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.getSchema"
            },
            "updateSchema": {
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "path": "v1/indexing/{+name}/schema",
              "httpMethod": "PUT"
            }
          },
          "resources": {
            "items": {
              "methods": {
                "deleteQueueItems": {
                  "httpMethod": "POST",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "push": {
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/indexing/{+name}:push",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "httpMethod": "GET",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}/items"
                },
                "unreserve": {
                  "httpMethod": "POST",
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve"
                },
                "poll": {
                  "path": "v1/indexing/{+name}/items:poll",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]",
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "httpMethod": "POST"
                },
                "get": {
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}"
                },
                "delete": {
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "DELETE",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}"
                },
                "index": {
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "path": "v1/indexing/{+name}:index",
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index"
                },
                "upload": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "path": "v1/indexing/{+name}:upload",
                  "id": "cloudsearch.indexing.datasources.items.upload"
                }
              }
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        }
      }
    }
  },
  "name": "cloudsearch",
  "title": "Cloud Search API",
  "batchPath": "batch",
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search.",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "revision": "20220718",
  "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "id": "cloudsearch:v1",
  "schemas": {
    "GetCustomerIndexStatsResponse": {
      "type": "object",
      "id": "GetCustomerIndexStatsResponse",
      "properties": {
        "averageIndexedItemCount": {
          "description": "Average item count for the given date range for which billing is done.",
          "format": "int64",
          "type": "string"
        },
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "items": {
            "$ref": "CustomerIndexStats"
          },
          "type": "array"
        }
      }
    },
    "GetDataSourceIndexStatsResponse": {
      "type": "object",
      "id": "GetDataSourceIndexStatsResponse",
      "properties": {
        "averageIndexedItemCount": {
          "description": "Average item count for the given date range for which billing is done.",
          "format": "int64",
          "type": "string"
        },
        "stats": {
          "items": {
            "$ref": "DataSourceIndexStats"
          },
          "type": "array",
          "description": "Summary of indexed item counts, one for each day in the requested range."
        }
      }
    },
    "ResetSearchApplicationRequest": {
      "id": "ResetSearchApplicationRequest",
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      }
    },
    "ListItemsResponse": {
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        },
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        }
      },
      "id": "ListItemsResponse",
      "type": "object"
    },
    "UserId": {
      "id": "UserId",
      "type": "object",
      "properties": {
        "actingUserId": {
          "description": "Optional. Opaque, server-assigned ID of the user profile associated with App/user acting on behalf of the human user. This is currently only set when a 3P application is acting on the user's behalf.",
          "type": "string"
        },
        "originAppId": {
          "description": "Optional. Identifier of the App involved (directly or on behalf of a human creator) in creating this message. This is not set if the user posted a message directly, but is used in the case of, for example, a message being generated by a 1P integration based on a user action (creating an event, creating a task etc). This should only be used on the BE. For clients, please use the field in the FE message proto instead (google3/apps/dynamite/v1/frontend/api/message.proto?q=[...]",
          "$ref": "AppId"
        },
        "type": {
          "enumDescriptions": [
            "Notes on HUMAN type: 1) Leaving UserId.UserType field empty will return HUMAN as default value. This is expected because all the existing UserIds are without explicitly setting UserType, most of which are HUMAN Ids. For Bot Ids we will always set BOT in UserType field. 2) DO NOT explicitly set HUMAN as type. This is a proto2 issue, that a UserId with explicitly set default value HUMAN as type is NOT equal to an id without setting the field. aka. UserId id1 = UserId.newBuilder() .set[...]",
            ""
          ],
          "enum": [
            "HUMAN",
            "BOT"
          ],
          "description": "Clients do not need to send UserType to Backend, but Backend will always send this field to clients per the following rule: 1. For HUMAN Ids, the field is empty but by default .getType() will return HUMAN. 2. For BOT Ids, the field is ALWAYS set to BOT.",
          "type": "string"
        },
        "id": {
          "description": "Opaque, server-assigned ID of the User.",
          "type": "string"
        }
      },
      "description": "Primary key for User resource."
    },
    "QuerySuggestion": {
      "id": "QuerySuggestion",
      "type": "object",
      "description": "This field does not contain anything as of now and is just used as an indicator that the suggest result was a phrase completion.",
      "properties": {}
    },
    "CheckAccessResponse": {
      "id": "CheckAccessResponse",
      "type": "object",
      "properties": {
        "hasAccess": {
          "type": "boolean",
          "description": "Returns true if principal has access. Returns false otherwise."
        }
      }
    },
    "SourceConfig": {
      "description": "Configurations for a source while processing a Search or Suggest request.",
      "properties": {
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        },
        "source": {
          "$ref": "Source",
          "description": "The source for which this configuration is to be used."
        },
        "crowdingConfig": {
          "description": "The crowding configuration for the source.",
          "$ref": "SourceCrowdingConfig"
        }
      },
      "id": "SourceConfig",
      "type": "object"
    },
    "FacetResult": {
      "description": "Source specific facet response",
      "properties": {
        "objectType": {
          "description": "Object type for which facet results are returned. Can be empty.",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name for which facet results are returned. Will not be empty.",
          "type": "string"
        },
        "buckets": {
          "description": "FacetBuckets for values in response containing at least a single result with the corresponding filter.",
          "type": "array",
          "items": {
            "$ref": "FacetBucket"
          }
        },
        "operatorName": {
          "type": "string",
          "description": "The name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions"
        }
      },
      "type": "object",
      "id": "FacetResult"
    },
    "BooleanPropertyOptions": {
      "description": "The options for boolean properties.",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the boolean should be used as a search operator.",
          "$ref": "BooleanOperatorOptions"
        }
      },
      "type": "object"
    },
    "PropertyDefinition": {
      "description": "The definition of a property within an object.",
      "id": "PropertyDefinition",
      "properties": {
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "isRepeatable": {
          "type": "boolean",
          "description": "Indicates that multiple values are allowed for the property. For example, a document only has one description but can have multiple comments. Cannot be true for properties whose type is a boolean. If set to false, properties that contain more than one value cause the indexing request for that item to be rejected."
        },
        "displayOptions": {
          "description": "The options that determine how the property is displayed in the Cloud Search results page if it's specified to be displayed in the object's display options.",
          "$ref": "PropertyDisplayOptions"
        },
        "isSuggestable": {
          "description": "Indicates that the property can be used for generating query suggestions.",
          "type": "boolean"
        },
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "isFacetable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for generating facets. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for boolean, enum, and text properties."
        },
        "isSortable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for sorting. Cannot be true for properties that are repeatable. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for boolean, date, double, integer, and timestamp properties."
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "isReturnable": {
          "type": "boolean",
          "description": "Indicates that the property identifies data that should be returned in search results via the Query API. If set to *true*, indicates that Query API users can use matching property fields in results. However, storing fields requires more space allocation and uses more bandwidth for search queries, which impacts performance over large datasets. Set to *true* here only if the field is needed for search results. Cannot be true for properties whose type is an object."
        },
        "name": {
          "description": "The name of the property. Item indexing requests sent to the Indexing API should set the property name equal to this value. For example, if name is *subject_line*, then indexing requests for document items with subject fields should set the name for that field equal to *subject_line*. Use the name as the identifier for the object property. Once registered as a property for an object, you cannot re-use this name for another property within that object. The name must star[...]",
          "type": "string"
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this property. Only supported for Text properties. IsReturnable must be true to set this option. In a given datasource maximum of 5 properties can be marked as is_wildcard_searchable.",
          "type": "boolean"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        }
      },
      "type": "object"
    },
    "SearchItemsByViewUrlResponse": {
      "id": "SearchItemsByViewUrlResponse",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        },
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "Date": {
      "properties": {
        "year": {
          "type": "integer",
          "format": "int32",
          "description": "Year of date. Must be from 1 to 9999."
        },
        "month": {
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32",
          "type": "integer"
        },
        "day": {
          "format": "int32",
          "type": "integer",
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month."
        }
      },
      "type": "object",
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "id": "Date"
    },
    "SearchQualityMetadata": {
      "type": "object",
      "id": "SearchQualityMetadata",
      "properties": {
        "quality": {
          "type": "number",
          "format": "double",
          "description": "An indication of the quality of the item, used to influence search quality. Value should be between 0.0 (lowest quality) and 1.0 (highest quality). The default value is 0.0."
        }
      },
      "description": "Additional search quality metadata of the item."
    },
    "Emoji": {
      "properties": {
        "unicode": {
          "type": "string",
          "description": "A basic emoji represented by a unicode string."
        },
        "customEmoji": {
          "$ref": "CustomEmoji",
          "description": "A custom emoji."
        }
      },
      "type": "object",
      "id": "Emoji"
    },
    "DataSourceRestriction": {
      "properties": {
        "source": {
          "description": "The source of restriction.",
          "$ref": "Source"
        },
        "filterOptions": {
          "type": "array",
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
          "items": {
            "$ref": "FilterOptions"
          }
        }
      },
      "id": "DataSourceRestriction",
      "description": "Restriction on Datasource.",
      "type": "object"
    },
    "EnumValuePair": {
      "properties": {
        "stringValue": {
          "type": "string",
          "description": "The string value of the EnumValuePair. The maximum length is 32 characters."
        },
        "integerValue": {
          "description": "The integer value of the EnumValuePair which must be non-negative. Optional.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "EnumValuePair",
      "type": "object",
      "description": "The enumeration value pair defines two things: a required string value and an optional integer value. The string value defines the necessary query term required to retrieve that item, such as *p0* for a priority item. The integer value determines the ranking of that string value relative to other enumerated values for the same property. For example, you might associate *p0* with *0* and define another enum pair such as *p1* and *1*. You must use the integer value in combina[...]"
    },
    "GetSearchApplicationUserStatsResponse": {
      "type": "object",
      "id": "GetSearchApplicationUserStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationUserStats"
          },
          "type": "array"
        }
      }
    },
    "QuerySource": {
      "description": "List of sources that the user can search using the query API.",
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string",
          "description": "Display name of the data source."
        },
        "source": {
          "description": "The name of the source",
          "$ref": "Source"
        },
        "shortName": {
          "type": "string",
          "description": "A short name or alias for the source. This value can be used with the 'source' operator."
        },
        "operators": {
          "description": "List of all operators applicable for this source.",
          "type": "array",
          "items": {
            "$ref": "QueryOperator"
          }
        }
      },
      "id": "QuerySource"
    },
    "ObjectPropertyOptions": {
      "id": "ObjectPropertyOptions",
      "description": "The options for object properties.",
      "properties": {
        "subobjectProperties": {
          "items": {
            "$ref": "PropertyDefinition"
          },
          "type": "array",
          "description": "The properties of the sub-object. These properties represent a nested object. For example, if this property represents a postal address, the subobjectProperties might be named *street*, *city*, and *state*. The maximum number of elements is 1000."
        }
      },
      "type": "object"
    },
    "DriveLocationRestrict": {
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      },
      "type": "object",
      "id": "DriveLocationRestrict",
      "description": "Drive location search restricts (e.g. \"is:starred\")."
    },
    "PushItem": {
      "id": "PushItem",
      "properties": {
        "queue": {
          "description": "Queue to which this item belongs. The `default` queue is chosen if this field is not specified. The maximum length is 512 characters.",
          "type": "string"
        },
        "payload": {
          "format": "byte",
          "description": "Provides additional document state information for the connector, such as an alternate repository ID and other metadata. The maximum length is 8192 bytes.",
          "type": "string"
        },
        "contentHash": {
          "type": "string",
          "description": "Content hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "metadataHash": {
          "type": "string",
          "description": "The metadata hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "type": {
          "description": "The type of the push operation that defines the push behavior.",
          "enumDescriptions": [
            "Default UNSPECIFIED. Specifies that the push operation should not modify ItemStatus",
            "Indicates that the repository document has been modified or updated since the previous update call. This changes status to MODIFIED state for an existing item. If this is called on a non existing item, the status is changed to NEW_ITEM.",
            "Item in the repository has not been modified since the last update call. This push operation will set status to ACCEPTED state.",
            "Connector is facing a repository error regarding this item. Change status to REPOSITORY_ERROR state. Item is unreserved and rescheduled at a future time determined by exponential backoff.",
            "Call push with REQUEUE only for items that have been reserved. This action unreserves the item and resets its available time to the wall clock time."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ]
        },
        "structuredDataHash": {
          "description": "Structured data hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details. This information is displayed in the Admin Console. This field may only be populated when the Type is REPOSITORY_ERROR."
        }
      },
      "type": "object",
      "description": "Represents an item to be pushed to the indexing queue."
    },
    "UploadItemRef": {
      "description": "Represents an upload session reference. This reference is created via upload method. This reference is valid for 30 days after its creation. Updating of item content may refer to this uploaded content via contentDataRef.",
      "properties": {
        "name": {
          "description": "The name of the content reference. The maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "type": "object",
      "id": "UploadItemRef"
    },
    "ObjectValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      },
      "type": "object",
      "description": "List of object values.",
      "id": "ObjectValues"
    },
    "UnmappedIdentity": {
      "properties": {
        "externalIdentity": {
          "description": "The resource name for an external user.",
          "$ref": "Principal"
        },
        "resolutionStatusCode": {
          "description": "The resolution status for the external identity.",
          "enumDescriptions": [
            "Input-only value. Used to list all unmapped identities regardless of status.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by the user.",
            "The identity source associated with the identity was either not found or deleted.",
            "IDaaS does not understand the identity source, probably because the schema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ],
          "type": "string"
        }
      },
      "type": "object",
      "id": "UnmappedIdentity"
    },
    "SearchApplicationSessionStats": {
      "properties": {
        "date": {
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned.",
          "$ref": "Date"
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object",
      "id": "SearchApplicationSessionStats"
    },
    "ItemContent": {
      "id": "ItemContent",
      "description": "Content of an item to be indexed and surfaced by Cloud Search. Only UTF-8 encoded strings are allowed as inlineContent. If the content is uploaded and not binary, it must be UTF-8 encoded.",
      "type": "object",
      "properties": {
        "contentDataRef": {
          "$ref": "UploadItemRef",
          "description": "Upload reference ID of a previously uploaded content via write method."
        },
        "hash": {
          "type": "string",
          "description": "Hashing info calculated and provided by the API client for content. Can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "inlineContent": {
          "description": "Content that is supplied inlined within the update method. The maximum length is 102400 bytes (100 KiB).",
          "type": "string",
          "format": "byte"
        },
        "contentFormat": {
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "type": "string"
        }
      }
    },
    "QueryInterpretationConfig": {
      "description": "Default options to interpret user query.",
      "type": "object",
      "properties": {
        "forceDisableSupplementalResults": {
          "description": "Set this flag to disable supplemental results retrieval, setting a flag here will not retrieve supplemental results for queries associated with a given search application. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for supplemental results.",
          "type": "boolean"
        },
        "forceVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental results retrieval, and usage of synonyms including custom ones. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for verbatim mode.",
          "type": "boolean"
        }
      },
      "id": "QueryInterpretationConfig"
    },
    "CustomerUserStats": {
      "id": "CustomerUserStats",
      "type": "object",
      "properties": {
        "oneDayActiveUsersCount": {
          "type": "string",
          "format": "int64",
          "description": "The count of unique active users in the past one day"
        },
        "date": {
          "description": "The date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "sevenDaysActiveUsersCount": {
          "description": "The count of unique active users in the past seven days",
          "format": "int64",
          "type": "string"
        },
        "thirtyDaysActiveUsersCount": {
          "format": "int64",
          "description": "The count of unique active users in the past thirty days",
          "type": "string"
        }
      }
    },
    "DoubleValues": {
      "id": "DoubleValues",
      "description": "List of double values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        }
      }
    },
    "DateOperatorOptions": {
      "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:\u003cvalue\u003e* show results only where the value of the *closeDate* property matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an oper[...]"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "id": "DateOperatorOptions",
      "type": "object"
    },
    "SuggestResponse": {
      "description": "Response of the suggest API.",
      "properties": {
        "suggestResults": {
          "type": "array",
          "items": {
            "$ref": "SuggestResult"
          },
          "description": "List of suggestions."
        }
      },
      "type": "object",
      "id": "SuggestResponse"
    },
    "IntegerOperatorOptions": {
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any S[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the less-than operator. For example, if lessThanOperatorName is *prioritybelow* and the property's name is *priorityVal*, then queries like *prioritybelow:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is less than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the greater-than operator. For example, if greaterThanOperatorName is *priorityabove* and the property's name is *priorityVal*, then queries like *priorityabove:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is greater than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 chara[...]",
          "type": "string"
        }
      },
      "id": "IntegerOperatorOptions",
      "description": "Used to provide a search operator for integer properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object"
    },
    "GetSearchApplicationSessionStatsResponse": {
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationSessionStats"
          },
          "type": "array"
        }
      },
      "id": "GetSearchApplicationSessionStatsResponse",
      "type": "object"
    },
    "DmId": {
      "id": "DmId",
      "properties": {
        "dmId": {
          "type": "string",
          "description": "Unique server assigned Id, per Direct Message Space."
        }
      },
      "type": "object"
    },
    "Media": {
      "id": "Media",
      "properties": {
        "resourceName": {
          "type": "string",
          "description": "Name of the media resource."
        }
      },
      "type": "object",
      "description": "Media resource."
    },
    "SearchResult": {
      "type": "object",
      "description": "Results containing indexed information for a document.",
      "properties": {
        "debugInfo": {
          "description": "Debugging information about this search result.",
          "$ref": "ResultDebugInfo"
        },
        "url": {
          "description": "The URL of the search result. The URL contains a Google redirect to the actual item. This URL is signed and shouldn't be changed.",
          "type": "string"
        },
        "title": {
          "type": "string",
          "description": "Title of the search result."
        },
        "clusteredResults": {
          "type": "array",
          "description": "If source is clustered, provide list of clustered results. There will only be one level of clustered results. If current source is not enabled for clustering, this field will be empty.",
          "items": {
            "$ref": "SearchResult"
          }
        },
        "snippet": {
          "description": "The concatenation of all snippets (summaries) available for this result.",
          "$ref": "Snippet"
        },
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        }
      },
      "id": "SearchResult"
    },
    "TimestampPropertyOptions": {
      "properties": {
        "operatorOptions": {
          "$ref": "TimestampOperatorOptions",
          "description": "If set, describes how the timestamp should be used as a search operator."
        }
      },
      "description": "The options for timestamp properties.",
      "id": "TimestampPropertyOptions",
      "type": "object"
    },
    "Metadata": {
      "id": "Metadata",
      "description": "Metadata of a matched search result.",
      "type": "object",
      "properties": {
        "createTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The creation time for this document or object in the search result."
        },
        "fields": {
          "type": "array",
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "items": {
            "$ref": "NamedProperty"
          }
        },
        "mimeType": {
          "description": "Mime type of the search result.",
          "type": "string"
        },
        "owner": {
          "description": "Owner (usually creator) of the document or object of the search result.",
          "$ref": "Person"
        },
        "thumbnailUrl": {
          "type": "string",
          "description": "The thumbnail URL of the result."
        },
        "source": {
          "description": "The named source for the result, such as Gmail.",
          "$ref": "Source"
        },
        "updateTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The last modified date for the object in the search result. If not set in the item, the value returned here is empty. When `updateTime` is used for calculating freshness and is not set, this value defaults to 2 years from the current time."
        },
        "displayOptions": {
          "description": "Options that specify how to display a structured data search result.",
          "$ref": "ResultDisplayMetadata"
        },
        "objectType": {
          "description": "Object type of the search result.",
          "type": "string"
        }
      }
    },
    "GetSearchApplicationQueryStatsResponse": {
      "type": "object",
      "description": "Response format for getting query stats for a search application between given dates.",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationQueryStats"
          },
          "type": "array",
          "description": "Query stats per date for a search application."
        },
        "totalQueryCount": {
          "type": "string",
          "description": "Total successful query count (status code 200) for the given date range.",
          "format": "int64"
        }
      },
      "id": "GetSearchApplicationQueryStatsResponse"
    },
    "Id": {
      "type": "object",
      "properties": {
        "localId": {
          "type": "string",
          "description": "The local identifier for the DirEntry (local to the creator's account). local_id + app_name is guaranteed to be unique within the creator account, but not across all User accounts. The string is case sensitive. Ignore if name_space==GAIA. NB For name_space==COSMO, all local_id's should be defined in google3/java/com/google/storage/cosmo/server/api/SpecialObjectIds.java as they have a special predefined meaning. See cosmo.client.CosmoIdFactory.createObjectId(long,String)[...]"
        },
        "creatorUserId": {
          "type": "string",
          "description": "The User account in which the DirEntry was originally created. If name_space==GAIA, then it's the gaia_id of the user this id is referring to.",
          "format": "uint64"
        },
        "nameSpace": {
          "format": "int32",
          "description": "The name space in which this id is unique (typically the application that created it). Values should be drawn from the above enum, but for experimentation, use values greater than 1000.",
          "type": "integer"
        }
      },
      "description": "Identifies a particular object, including both Users and DirEntries. This Id is unique across the entire server instance, such as the production or qa instance.",
      "id": "Id"
    },
    "UnreserveItemsRequest": {
      "id": "UnreserveItemsRequest",
      "properties": {
        "connectorName": {
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "type": "string",
          "description": "The name of a queue to unreserve items from."
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object"
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "type": "object",
      "properties": {
        "itemNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        }
      },
      "id": "ListItemNamesForUnmappedIdentityResponse"
    },
    "TimestampValues": {
      "type": "object",
      "id": "TimestampValues",
      "description": "List of timestamp values.",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "google-datetime"
          }
        }
      }
    },
    "ValueFilter": {
      "id": "ValueFilter",
      "type": "object",
      "properties": {
        "value": {
          "$ref": "Value",
          "description": "The value to be compared with."
        },
        "operatorName": {
          "description": "The `operator_name` applied to the query, such as *price_greater_than*. The filter can work against both types of filters defined in the schema for your data source: 1. `operator_name`, where the query filters results by the property that matches the value. 2. `greater_than_operator_name` or `less_than_operator_name` in your schema. The query filters the results for the property values that are greater than or less than the supplied value in the query.",
          "type": "string"
        }
      }
    },
    "VideoInfo": {
      "description": "Next tag: 2",
      "id": "VideoInfo",
      "properties": {
        "duration": {
          "type": "integer",
          "format": "int32",
          "description": "Duration of the video in milliseconds. This field can be absent for recently uploaded video or inaccurate sometimes."
        }
      },
      "type": "object"
    },
    "TimestampOperatorOptions": {
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property. For example, if operatorName is *closedon* and the property's name is *closeDate*, then queries like *closedon:\u003cvalue\u003e* show results only where the value of the property named *closeDate* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Str[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      },
      "description": "Used to provide a search operator for timestamp properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "TimestampOperatorOptions"
    },
    "DoubleOperatorOptions": {
      "id": "DoubleOperatorOptions",
      "description": "Used to provide a search operator for double properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to use the double property in sorting or as a facet. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "type": "object"
    },
    "DriveFollowUpRestrict": {
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "type": "object",
      "id": "DriveFollowUpRestrict",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "type": "string"
        }
      }
    },
    "ObjectDisplayOptions": {
      "id": "ObjectDisplayOptions",
      "description": "The display options for an object.",
      "properties": {
        "objectDisplayLabel": {
          "description": "The user friendly label to display in the search result to indicate the type of the item. This is OPTIONAL; if not provided, an object label isn't displayed on the context line of the search results. The maximum length is 64 characters.",
          "type": "string"
        },
        "metalines": {
          "type": "array",
          "description": "Defines the properties that are displayed in the metalines of the search results. The property values are displayed in the order given here. If a property holds multiple values, all of the values are displayed before the next properties. For this reason, it is a good practice to specify singular properties before repeated properties in this list. All of the properties must set is_returnable to true. The maximum number of metalines is 3.",
          "items": {
            "$ref": "Metaline"
          }
        }
      },
      "type": "object"
    },
    "RepositoryError": {
      "id": "RepositoryError",
      "type": "object",
      "properties": {
        "errorMessage": {
          "type": "string",
          "description": "Message that describes the error. The maximum allowable length of the message is 8192 characters."
        },
        "type": {
          "description": "The type of error.",
          "type": "string",
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to the repository server."
          ]
        },
        "httpStatusCode": {
          "description": "Error codes. Matches the definition of HTTP status codes.",
          "format": "int32",
          "type": "integer"
        }
      },
      "description": "Errors when the connector is communicating to the source repository."
    },
    "SortOptions": {
      "id": "SortOptions",
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "The name of the operator corresponding to the field to sort on. The corresponding property must be marked as sortable."
        },
        "sortOrder": {
          "type": "string",
          "enumDescriptions": [
            "",
            ""
          ],
          "description": "Ascending is the default sort order",
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ]
        }
      }
    },
    "ItemCountByStatus": {
      "id": "ItemCountByStatus",
      "type": "object",
      "properties": {
        "count": {
          "format": "int64",
          "description": "Number of items matching the status code.",
          "type": "string"
        },
        "statusCode": {
          "type": "string",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "description": "Status of the items."
        },
        "indexedItemsCount": {
          "description": "Number of items matching the status code for which billing is done. This excludes virtual container items from the total count. This count would not be applicable for items with ERROR or NEW_ITEM status code.",
          "format": "int64",
          "type": "string"
        }
      }
    },
    "Status": {
      "description": "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).",
      "type": "object",
      "id": "Status",
      "properties": {
        "code": {
          "format": "int32",
          "type": "integer",
          "description": "The status code, which should be an enum value of google.rpc.Code."
        },
        "message": {
          "type": "string",
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client."
        },
        "details": {
          "description": "A list of messages that carry the error details. There is a common set of message types for APIs to use.",
          "items": {
            "type": "object",
            "additionalProperties": {
              "description": "Properties of the object. Contains field @type with type URL.",
              "type": "any"
            }
          },
          "type": "array"
        }
      }
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "type": "object",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "queue": {
          "description": "The name of a queue to delete items from.",
          "type": "string"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      }
    },
    "CustomerSearchApplicationStats": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which search application stats were calculated."
        },
        "count": {
          "format": "int64",
          "type": "string",
          "description": "The count of search applications for the date."
        }
      },
      "description": "Search application stats for a customer for the given date.",
      "id": "CustomerSearchApplicationStats"
    },
    "ItemAcl": {
      "id": "ItemAcl",
      "type": "object",
      "description": "Access control list information for the item. For more information see [Map ACLs](https://developers.google.com/cloud-search/docs/guides/acls).",
      "properties": {
        "readers": {
          "description": "List of principals who are allowed to see the item in search results. Optional if inheriting permissions from another item or if the item is not intended to be visible, such as virtual containers. The maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "deniedReaders": {
          "items": {
            "$ref": "Principal"
          },
          "description": "List of principals who are explicitly denied access to the item in search results. While principals are denied access by default, use denied readers to handle exceptions and override the list allowed readers. The maximum number of elements is 100.",
          "type": "array"
        },
        "owners": {
          "description": "Optional. List of owners for the item. This field has no bearing on document access permissions. It does, however, offer a slight ranking boosts items where the querying user is an owner. The maximum number of elements is 5.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        },
        "inheritAclFrom": {
          "description": "The name of the item to inherit the Access Permission List (ACL) from. Note: ACL inheritance *only* provides access permissions to child items and does not define structural relationships, nor does it provide convenient ways to delete large groups of items. Deleting an ACL parent from the index only alters the access permissions of child items that reference the parent in the inheritAclFrom field. The item is still in the index, but may not visible in search results. By[...]",
          "type": "string"
        },
        "aclInheritanceType": {
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ],
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL. Use NOT_APPLICABLE when inheritAclFrom is empty. An item without ACL inheritance can still have ACLs supplied by its own readers and deniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines its read access.",
            "During an authorization conflict, the ACL of the parent item specified in the inheritAclFrom field determines read access.",
            "Access is granted only if this item and the parent item specified in the inheritAclFrom field both permit read access."
          ],
          "type": "string",
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a parent. This should always be set in tandem with the inheritAclFrom field. Also, when the inheritAclFrom field is set, this field should be set to a valid AclInheritanceType."
        }
      }
    },
    "TypeInfo": {
      "type": "object",
      "properties": {
        "videoInfo": {
          "description": "Contains additional video information only if document_type is VIDEO.",
          "$ref": "VideoInfo"
        }
      },
      "description": "Next tag: 2",
      "id": "TypeInfo"
    },
    "ResultCounts": {
      "id": "ResultCounts",
      "type": "object",
      "description": "Result count information",
      "properties": {
        "sourceResultCounts": {
          "type": "array",
          "description": "Result count information for each source with results.",
          "items": {
            "$ref": "SourceResultCount"
          }
        }
      }
    },
    "QueryOperator": {
      "properties": {
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name that can be used to isolate the property using the greater-than operator."
        },
        "isReturnable": {
          "description": "Will the property associated with this facet be returned as part of search results.",
          "type": "boolean"
        },
        "objectType": {
          "description": "The name of the object corresponding to the operator. This field is only filled for schema-specific operators, and is unset for common operators.",
          "type": "string"
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the operator"
        },
        "isRepeatable": {
          "description": "Indicates if multiple values can be set for this property.",
          "type": "boolean"
        },
        "isSuggestable": {
          "type": "boolean",
          "description": "Can get suggestions for this field."
        },
        "isFacetable": {
          "description": "Can this operator be used to get facets.",
          "type": "boolean"
        },
        "enumValues": {
          "description": "Potential list of values for the opeatror field. This field is only filled when we can safely enumerate all the possible values of this operator.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "type": {
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "description": "The type of the operator.",
          "type": "string",
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ]
        },
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name that can be used to isolate the property using the less-than operator."
        },
        "operatorName": {
          "type": "string",
          "description": "The name of the operator."
        },
        "isSortable": {
          "description": "Can this operator be used to sort results.",
          "type": "boolean"
        }
      },
      "type": "object",
      "id": "QueryOperator",
      "description": "The definition of a operator that can be used in a Search/Suggest request."
    },
    "SearchItemsByViewUrlRequest": {
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "viewUrl": {
          "type": "string",
          "description": "Specify the full view URL to find the corresponding item. The maximum length is 2048 characters."
        },
        "pageToken": {
          "description": "The next_page_token value returned from a previous request, if any.",
          "type": "string"
        }
      },
      "type": "object",
      "id": "SearchItemsByViewUrlRequest"
    },
    "GroupId": {
      "type": "object",
      "description": "Id representing a group that could be a space, a chat, or a direct message space. Which ID is set here will determine which group",
      "properties": {
        "spaceId": {
          "description": "Unique, immutable ID of the Space",
          "$ref": "SpaceId"
        },
        "dmId": {
          "$ref": "DmId",
          "description": "Unique, immutable ID of the Direct Message Space"
        }
      },
      "id": "GroupId"
    },
    "EmailAddress": {
      "type": "object",
      "description": "A person's email address.",
      "id": "EmailAddress",
      "properties": {
        "emailAddress": {
          "type": "string",
          "description": "The email address."
        }
      }
    },
    "QueryCountByStatus": {
      "type": "object",
      "id": "QueryCountByStatus",
      "properties": {
        "count": {
          "format": "int64",
          "type": "string"
        },
        "statusCode": {
          "format": "int32",
          "description": "This represents the http status code.",
          "type": "integer"
        }
      }
    },
    "SuggestRequest": {
      "type": "object",
      "id": "SuggestRequest",
      "properties": {
        "dataSourceRestrictions": {
          "description": "The sources to use for suggestions. If not specified, the data sources are taken from the current search application. NOTE: Suggestions are only supported for the following sources: * Third-party data sources * PredefinedSource.PERSON * PredefinedSource.GOOGLE_DRIVE",
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        },
        "query": {
          "type": "string",
          "description": "Partial query for which autocomplete suggestions will be shown. For example, if the query is \"sea\", then the server might return \"season\", \"search\", \"seagull\" and so on."
        },
        "requestOptions": {
          "description": "Request options, such as the search application and user timezone.",
          "$ref": "RequestOptions"
        }
      },
      "description": "Request of suggest API."
    },
    "Name": {
      "id": "Name",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by the viewer's account or the `Accept-Language` HTTP header.",
          "type": "string"
        }
      },
      "description": "A person's name.",
      "type": "object"
    },
    "SourceCrowdingConfig": {
      "id": "SourceCrowdingConfig",
      "description": "Set search results crowding limits. Crowding is a situation in which multiple results from the same source or host \"crowd out\" other results, diminishing the quality of search for users. To foster better search quality and source diversity in search results, you can set a condition to reduce repetitive results by source.",
      "properties": {
        "numResults": {
          "description": "Maximum number of results allowed from a datasource in a result page as long as results from other sources are not exhausted. Value specified must not be negative. A default value is used if this value is equal to 0. To disable crowding, set the value greater than 100.",
          "type": "integer",
          "format": "int32"
        },
        "numSuggestions": {
          "type": "integer",
          "format": "int32",
          "description": "Maximum number of suggestions allowed from a source. No limits will be set on results if this value is less than or equal to 0."
        }
      },
      "type": "object"
    },
    "Snippet": {
      "type": "object",
      "properties": {
        "matchRanges": {
          "description": "The matched ranges in the snippet.",
          "type": "array",
          "items": {
            "$ref": "MatchRange"
          }
        },
        "snippet": {
          "description": "The snippet of the document. The snippet of the document. May contain escaped HTML character that should be unescaped prior to rendering.",
          "type": "string"
        }
      },
      "id": "Snippet",
      "description": "Snippet of the search result, which summarizes the content of the resulting page."
    },
    "Item": {
      "id": "Item",
      "properties": {
        "itemType": {
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information. These items cannot be referred in containerName or inheritAclFrom fields.",
            "An item that gets indexed and whose purpose is to supply other items with ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose as CONTAINER_ITEM."
          ],
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "type": "string",
          "description": "The type for this item."
        },
        "structuredData": {
          "description": "The structured data for the item that should conform to a registered object definition in the schema for the data source.",
          "$ref": "ItemStructuredData"
        },
        "payload": {
          "description": "Additional state connector can store for this item. The maximum length is 10000 bytes.",
          "type": "string",
          "format": "byte"
        },
        "metadata": {
          "description": "The metadata information.",
          "$ref": "ItemMetadata"
        },
        "acl": {
          "$ref": "ItemAcl",
          "description": "Access control list for this item."
        },
        "name": {
          "type": "string",
          "description": "The name of the Item. Format: datasources/{source_id}/items/{item_id} This is a required field. The maximum length is 1536 characters."
        },
        "content": {
          "$ref": "ItemContent",
          "description": "Item content to be indexed and made text searchable."
        },
        "queue": {
          "type": "string",
          "description": "Queue this item belongs to. The maximum length is 100 characters."
        },
        "version": {
          "type": "string",
          "description": "Required. The indexing system stores the version from the datasource as a byte string and compares the Item version in the index to the version of the queued Item using lexical ordering. Cloud Search Indexing won't index or delete any queued item with a version value that is less than or equal to the version of the currently indexed item. The maximum length for this field is 1024 bytes. For information on how item version affects the deletion process, refer to [Handle r[...]",
          "format": "byte"
        },
        "status": {
          "description": "Status of the item. Output only field.",
          "$ref": "ItemStatus"
        }
      },
      "type": "object",
      "description": "Represents a single object that is an item in the search index, such as a file, folder, or a database record."
    },
    "Photo": {
      "id": "Photo",
      "type": "object",
      "description": "A person's photo.",
      "properties": {
        "url": {
          "description": "The URL of the photo.",
          "type": "string"
        }
      }
    },
    "DebugOptions": {
      "properties": {
        "enableDebugging": {
          "type": "boolean",
          "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field."
        }
      },
      "type": "object",
      "id": "DebugOptions",
      "description": "Shared request debug options for all cloudsearch RPC methods."
    },
    "FieldViolation": {
      "id": "FieldViolation",
      "properties": {
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        },
        "description": {
          "type": "string",
          "description": "The description of the error."
        }
      },
      "type": "object"
    },
    "ErrorMessage": {
      "properties": {
        "errorMessage": {
          "type": "string"
        },
        "source": {
          "$ref": "Source"
        }
      },
      "id": "ErrorMessage",
      "type": "object",
      "description": "Error message per source response."
    },
    "QueryInterpretationOptions": {
      "properties": {
        "disableNlInterpretation": {
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is false, Set to true to disable natural language interpretation. NL interpretation only applies to predefined datasources.",
          "type": "boolean"
        },
        "disableSupplementalResults": {
          "description": "Use this flag to disable supplemental results for a query. Supplemental results setting chosen at SearchApplication level will take precedence if set to True.",
          "type": "boolean"
        },
        "enableVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental result retrieval, and usage of synonyms including custom ones. Nl interpretation will be disabled if either one of the two flags is true.",
          "type": "boolean"
        }
      },
      "id": "QueryInterpretationOptions",
      "description": "Options to interpret user query.",
      "type": "object"
    },
    "GoogleDocsMetadata": {
      "description": "The corpus specific metadata for office-type documents, from Google Docs and other sources. This message is passed to the scorer and beyond. Next tag: 7",
      "id": "GoogleDocsMetadata",
      "properties": {
        "typeInfo": {
          "$ref": "TypeInfo",
          "description": "Contains additional information about the document depending on its type."
        },
        "lastContentModifiedTimestamp": {
          "description": "The last time this document was modified, in seconds since epoch. Only counts content modifications.",
          "type": "string",
          "format": "int64"
        },
        "resultInfo": {
          "$ref": "GoogleDocsResultInfo",
          "description": "Additional per-result information, akin to Gmail's SingleThreadResponse. Note: GWS no longer seems to use this field, but there's still one reference to it for Scribe, so we can't remove it."
        },
        "aclInfo": {
          "description": "Contains number of users and groups which can access the document.",
          "$ref": "AclInfo"
        },
        "documentType": {
          "type": "string",
          "description": "The conceptual type (presentation, document, etc.) of this document.",
          "enum": [
            "UNKNOWN",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "PDF",
            "IMAGE",
            "BINARY_BLOB",
            "FUSION_TABLE",
            "FOLDER",
            "DRAWING",
            "VIDEO",
            "FORM",
            "DRAFT_SITE",
            "DRAFT_SITE_PAGE",
            "JAM",
            "SHORTCUT",
            "SCRIPT"
          ],
          "enumDescriptions": [
            "If the type is unknown or not represented in this enum.",
            "Writely, Word, etc.",
            "Presently, PowerPoint, etc.",
            "Trix, Excel, etc.",
            "File types for Gdrive objects are below.",
            "",
            "Fall-back for unknown Gdrive types.",
            "",
            "",
            "",
            "",
            "",
            "For Atari page and site drafts",
            "",
            "Jamboard Jams (go/jam)",
            "Drive Shortcuts (go/shortcuts)",
            ""
          ]
        },
        "fileExtension": {
          "description": "The file extension of the document. NOTE: As of October 2018 this field is not backfilled for old documents.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "CustomEmoji": {
      "properties": {
        "updateTimeMicros": {
          "type": "string",
          "format": "int64"
        },
        "contentType": {
          "description": "Content type of the file used to upload the emoji. Used for takeout. Written to Spanner when the emoji is created.",
          "type": "string"
        },
        "deleteTimeMicros": {
          "type": "string",
          "format": "int64",
          "description": "Time when the emoji was deleted, in microseconds. This field may be present in Spanner, within the server, or in public APIs. Only present if the emoji has been deleted."
        },
        "ownerCustomerId": {
          "$ref": "CustomerId",
          "description": "This field should *never* be persisted to Spanner."
        },
        "state": {
          "description": "Snapshot of the current state of the emoji, which may differ from the source-of-truth in the CustomEmojis table. This field should *never* be persisted to Spanner.",
          "enum": [
            "EMOJI_STATE_UNSPECIFIED",
            "EMOJI_ENABLED",
            "EMOJI_SYSTEM_DISABLED",
            "EMOJI_HIDDEN",
            "EMOJI_DELETED"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "Emoji is visible and available to be used, subject to access control requirements.",
            "Emoji can no longer be used (e.g. due to a shortcode conflict), but is not removed from existing embeddings.",
            "Emoji is hidden from pickers, so new usages are not allowed, but is not removed from existing embeddings.",
            "Emoji is removed everywhere and is not available to end-users."
          ]
        },
        "shortcode": {
          "type": "string",
          "description": "User-provided, human-readable ID for the custom emoji. Users are expected to observe this field in the UI instead of the UUID. This shortcode should be unique within an organization, but has no global uniqueness guarantees, unlike the UUID. This field should *never* be persisted to Spanner."
        },
        "createTimeMicros": {
          "format": "int64",
          "description": "Time when the Emoji was created, in microseconds. This field may be present in Spanner, within the server, or in public APIs.",
          "type": "string"
        },
        "blobId": {
          "description": "ID for the underlying image data in Blobstore. This field should *only* be present in Spanner or within the server, but should not be exposed in public APIs.",
          "type": "string"
        },
        "uuid": {
          "description": "Unique key for a custom emoji resource. Required. This field is *always* populated.",
          "type": "string"
        },
        "creatorUserId": {
          "description": "This field should *never* be persisted to Spanner.",
          "$ref": "UserId"
        },
        "readToken": {
          "description": "Opaque token that clients use to construct the URL for accessing the custom emoji’s image data. This field is intended for API consumption, and should *never* be persisted to Spanner.",
          "type": "string"
        },
        "ephemeralUrl": {
          "readOnly": true,
          "description": "Output only. A short-lived URL clients can use for directly accessing a custom emoji image. This field is intended for API consumption, and should *never* be persisted to Spanner.",
          "type": "string"
        }
      },
      "description": "Proto representation of a custom emoji. May be used in both APIs and in Spanner, but certain fields should be restricted to one or the other. See the per-field documentation for details. NEXT_TAG: 14",
      "id": "CustomEmoji",
      "type": "object"
    },
    "ItemStatus": {
      "type": "object",
      "description": "This contains item's status and any errors.",
      "id": "ItemStatus",
      "properties": {
        "code": {
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "type": "string",
          "description": "Status code."
        },
        "repositoryErrors": {
          "items": {
            "$ref": "RepositoryError"
          },
          "description": "Repository error reported by connector.",
          "type": "array"
        },
        "processingErrors": {
          "type": "array",
          "description": "Error details in case the item is in ERROR state.",
          "items": {
            "$ref": "ProcessingError"
          }
        }
      }
    },
    "GetCustomerQueryStatsResponse": {
      "id": "GetCustomerQueryStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerQueryStats"
          },
          "type": "array"
        },
        "totalQueryCount": {
          "type": "string",
          "format": "int64",
          "description": "Total successful query count (status code 200) for the given date range."
        }
      },
      "type": "object"
    },
    "ResultDisplayLine": {
      "properties": {
        "fields": {
          "items": {
            "$ref": "ResultDisplayField"
          },
          "type": "array"
        }
      },
      "description": "The collection of fields that make up a displayed line",
      "id": "ResultDisplayLine",
      "type": "object"
    },
    "ListUnmappedIdentitiesResponse": {
      "id": "ListUnmappedIdentitiesResponse",
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        },
        "unmappedIdentities": {
          "type": "array",
          "items": {
            "$ref": "UnmappedIdentity"
          }
        }
      }
    },
    "ErrorInfo": {
      "description": "Error information about the response.",
      "properties": {
        "errorMessages": {
          "type": "array",
          "items": {
            "$ref": "ErrorMessage"
          }
        }
      },
      "id": "ErrorInfo",
      "type": "object"
    },
    "GetCustomerSessionStatsResponse": {
      "id": "GetCustomerSessionStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerSessionStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "RestrictItem": {
      "properties": {
        "driveMimeTypeRestrict": {
          "$ref": "DriveMimeTypeRestrict",
          "description": "Drive Types."
        },
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        },
        "searchOperator": {
          "type": "string",
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
        },
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "driveFollowUpRestrict": {
          "$ref": "DriveFollowUpRestrict"
        }
      },
      "description": "Information relevant only to a restrict entry. NextId: 12",
      "type": "object",
      "id": "RestrictItem"
    },
    "DriveTimeSpanRestrict": {
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ]
        }
      },
      "id": "DriveTimeSpanRestrict",
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "type": "object"
    },
    "AclInfo": {
      "properties": {
        "scope": {
          "enumDescriptions": [
            "Explicit set of people and groups.",
            "Anybody at the same domain with the link.",
            "Now it works only for google.com. Anybody at the same domain. Now it works only",
            "for google.com. Anybody with the link.",
            "Anybody.",
            "Special tag to indicate TeamDrive scope."
          ],
          "type": "string",
          "description": "The scope to which the content was shared.",
          "enum": [
            "LIMITED",
            "DASHER_DOMAIN_WITH_LINK",
            "DASHER_DOMAIN",
            "PUBLIC_WITH_LINK",
            "PUBLIC",
            "TEAM_DRIVE"
          ]
        },
        "groupsCount": {
          "type": "integer",
          "format": "int32",
          "description": "Number of groups which have at least read access to the document."
        },
        "usersCount": {
          "type": "integer",
          "format": "int32",
          "description": "Number of users which have at least read access to the document."
        }
      },
      "id": "AclInfo",
      "description": "Next tag: 4",
      "type": "object"
    },
    "AppId": {
      "type": "object",
      "description": "Identifier of an App.",
      "properties": {
        "appType": {
          "enum": [
            "APP_TYPE_UNSPECIFIED",
            "APP",
            "GSUITE_APP",
            "INCOMING_WEBHOOK"
          ],
          "description": "Enum indicating the type of App this is.",
          "type": "string",
          "enumDescriptions": [
            "",
            "3P APP eg. external Bots(Asana Bot), 1P Bots(Drive Bot).",
            "1P APP eg. Tasks, Meet, Docs, Calendar..",
            "Asynchronous messages via an incoming webhook."
          ]
        },
        "id": {
          "description": "Numeric identifier of the App. Set to Project number for 1/3P Apps. For Webhook, this is WebhookId. Determined & set by the 1P API from App credentials on the side channel.",
          "type": "string",
          "format": "int64"
        },
        "gsuiteAppType": {
          "enum": [
            "GSUITE_APP_TYPE_UNSPECIFIED",
            "TASKS_APP",
            "CALENDAR_APP",
            "DOCS_APP",
            "SHEETS_APP",
            "SLIDES_APP",
            "MEET_APP",
            "ASSISTIVE_SUGGESTION_APP",
            "CONTACTS_APP",
            "ACTIVITY_FEED_APP",
            "DRIVE_APP"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Powered by Bullseye",
            "",
            "",
            ""
          ],
          "description": "Enum indicating which 1P App this is when app_type is GSUITE_APP. Determined & set by the 1P API as a convenience for all users of this identifier(Eg. clients, chime, backend etc.) to map to 1P properties.",
          "type": "string"
        }
      },
      "id": "AppId"
    },
    "DynamiteSpacesScoringInfo": {
      "description": "This is the proto for holding space level scoring information. This data is used for logging in query-api server and for testing purposes.",
      "type": "object",
      "properties": {
        "contactsIntersectionCount": {
          "type": "number",
          "format": "double"
        },
        "spaceAgeInDays": {
          "type": "number",
          "format": "double"
        },
        "memberMetadataCount": {
          "format": "double",
          "type": "number"
        },
        "smallUnjoinedSpacesAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "finalScore": {
          "type": "number",
          "format": "double"
        },
        "affinityScore": {
          "type": "number",
          "format": "double"
        },
        "joinedSpacesAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "numAucContacts": {
          "type": "string",
          "format": "int64"
        },
        "commonContactCountAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "spaceCreationTimestampSecs": {
          "format": "int64",
          "type": "string"
        },
        "freshnessScore": {
          "format": "double",
          "type": "number"
        },
        "lastMessagePostedTimestampSecs": {
          "type": "string",
          "format": "int64"
        },
        "lastReadTimestampSecs": {
          "type": "string",
          "format": "int64"
        },
        "messageScore": {
          "type": "number",
          "format": "double"
        },
        "topicalityScore": {
          "type": "number",
          "format": "double"
        },
        "smallContactListAffinityScore": {
          "format": "double",
          "type": "number"
        }
      },
      "id": "DynamiteSpacesScoringInfo"
    },
    "CompositeFilter": {
      "properties": {
        "subFilters": {
          "description": "Sub filters.",
          "type": "array",
          "items": {
            "$ref": "Filter"
          }
        },
        "logicOperator": {
          "type": "string",
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "description": "The logic operator of the sub filter."
        }
      },
      "id": "CompositeFilter",
      "type": "object"
    },
    "BooleanOperatorOptions": {
      "type": "object",
      "description": "Used to provide a search operator for boolean properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the boolean property. For example, if operatorName is *closed* and the property's name is *isClosed*, then queries like *closed:\u003cvalue\u003e* show results only where the value of the property named *isClosed* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any String prop[...]"
        }
      },
      "id": "BooleanOperatorOptions"
    },
    "EnumOperatorOptions": {
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the enum property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Stri[...]",
          "type": "string"
        }
      },
      "type": "object",
      "id": "EnumOperatorOptions",
      "description": "Used to provide a search operator for enum properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched. For example, if you provide no operator for a *priority* enum property with possible values *p0* and *p1*, a query that contains the term *p0* returns items that have *p0* as the value of the *priority* property, as well as any items that contain the string *p0* in other fields. If you provide [...]"
    },
    "DataSourceIndexStats": {
      "id": "DataSourceIndexStats",
      "type": "object",
      "properties": {
        "date": {
          "description": "The date for which index stats were calculated. If the date of request is not the current date then stats calculated on the next day are returned. Stats are calculated close to mid night in this case. If date of request is current date, then real time stats are returned.",
          "$ref": "Date"
        },
        "itemCountByStatus": {
          "description": "Number of items aggregrated by status code.",
          "type": "array",
          "items": {
            "$ref": "ItemCountByStatus"
          }
        }
      },
      "description": "Aggregation of items by status code as of the specified date."
    },
    "DateValues": {
      "id": "DateValues",
      "type": "object",
      "description": "List of date values.",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "Date"
          }
        }
      }
    },
    "DoublePropertyOptions": {
      "id": "DoublePropertyOptions",
      "type": "object",
      "description": "The options for double properties.",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the double should be used as a search operator.",
          "$ref": "DoubleOperatorOptions"
        }
      }
    },
    "ProcessingError": {
      "id": "ProcessingError",
      "type": "object",
      "properties": {
        "code": {
          "description": "Error code indicating the nature of the error.",
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "enumDescriptions": [
            "Input only value. Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state. FieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other items with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ],
          "type": "string"
        },
        "fieldViolations": {
          "type": "array",
          "items": {
            "$ref": "FieldViolation"
          },
          "description": "In case the item fields are invalid, this field contains the details about the validation errors."
        },
        "errorMessage": {
          "type": "string",
          "description": "The description of the error."
        }
      }
    },
    "ListSearchApplicationsResponse": {
      "id": "ListSearchApplicationsResponse",
      "type": "object",
      "properties": {
        "searchApplications": {
          "type": "array",
          "items": {
            "$ref": "SearchApplication"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      }
    },
    "TextPropertyOptions": {
      "description": "The options for text properties.",
      "properties": {
        "operatorOptions": {
          "$ref": "TextOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        },
        "retrievalImportance": {
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval.",
          "$ref": "RetrievalImportance"
        }
      },
      "type": "object",
      "id": "TextPropertyOptions"
    },
    "UpdateSchemaRequest": {
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "schema": {
          "$ref": "Schema",
          "description": "The new schema for the source."
        },
        "validateOnly": {
          "type": "boolean",
          "description": "If true, the schema will be checked for validity, but will not be registered with the data source, even if valid."
        }
      },
      "id": "UpdateSchemaRequest",
      "type": "object"
    },
    "Source": {
      "type": "object",
      "id": "Source",
      "properties": {
        "predefinedSource": {
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used with the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used with the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "description": "Predefined content source for Google Apps.",
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Source name for content indexed by the Indexing API."
        }
      },
      "description": "Defines sources for the suggest/search APIs."
    },
    "RequestOptions": {
      "description": "Shared request options for all RPC methods.",
      "properties": {
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. For translations. Set this field using the language set in browser or for the page. In the event that the user's language preference is known, set this field to the known user language. When specified, the documents in search results are biased towards the specified language. The suggest API does not use this parameter. In[...]",
          "type": "string"
        },
        "debugOptions": {
          "description": "Debug options of the request",
          "$ref": "DebugOptions"
        },
        "searchApplicationId": {
          "type": "string",
          "description": "The ID generated when you create a search application using the [admin console](https://support.google.com/a/answer/9043922)."
        },
        "timeZone": {
          "type": "string",
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) project, and currently available in the file [timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml). This field is used to correctly interpret date and time queries. If this field is not specified, the default time zone (UTC) is used."
        }
      },
      "type": "object",
      "id": "RequestOptions"
    },
    "ObjectDefinition": {
      "type": "object",
      "id": "ObjectDefinition",
      "properties": {
        "propertyDefinitions": {
          "description": "The property definitions for the object. The maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          }
        },
        "options": {
          "description": "The optional object-specific options.",
          "$ref": "ObjectOptions"
        },
        "name": {
          "type": "string",
          "description": "The name for the object, which then defines its type. Item indexing requests should set the objectType field equal to this value. For example, if *name* is *Document*, then indexing requests for items of type Document should set objectType equal to *Document*. Each object definition must be uniquely named within a schema. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The maximum length is 256 characters."
        }
      },
      "description": "The definition for an object within a data source."
    },
    "TextValues": {
      "type": "object",
      "description": "List of text values.",
      "properties": {
        "values": {
          "items": {
            "type": "string"
          },
          "description": "The maximum allowable length for text values is 2048 characters.",
          "type": "array"
        }
      },
      "id": "TextValues"
    },
    "Principal": {
      "properties": {
        "groupResourceName": {
          "type": "string",
          "description": "This principal is a group identified using an external identity. The name field must specify the group resource name with this format: identitysources/{source_id}/groups/{ID}"
        },
        "userResourceName": {
          "description": "This principal is a user identified using an external identity. The name field must specify the user resource name with this format: identitysources/{source_id}/users/{ID}",
          "type": "string"
        },
        "gsuitePrincipal": {
          "$ref": "GSuitePrincipal",
          "description": "This principal is a Google Workspace user, group or domain."
        }
      },
      "id": "Principal",
      "type": "object",
      "description": "Reference to a user, group, or domain."
    },
    "SourceScoringConfig": {
      "type": "object",
      "properties": {
        "sourceImportance": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "description": "Importance of the source.",
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ]
        }
      },
      "id": "SourceScoringConfig",
      "description": "Set the scoring configuration. This allows modifying the ranking of results for a source."
    },
    "QueryInterpretation": {
      "id": "QueryInterpretation",
      "type": "object",
      "properties": {
        "reason": {
          "enum": [
            "UNSPECIFIED",
            "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
            "NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY"
          ],
          "description": "The reason for interpretation of the query. This field will not be UNSPECIFIED if the interpretation type is not NONE.",
          "enumDescriptions": [
            "",
            "Natural language interpretation of the query is used to fetch the search results.",
            "Query and document terms similarity is used to selectively broaden the query to retrieve additional search results since enough results were not found for the user query. Interpreted query will be empty for this case."
          ],
          "type": "string"
        },
        "interpretationType": {
          "type": "string",
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ],
          "enumDescriptions": [
            "Neither the natural language interpretation, nor a broader version of the query is used to fetch the search results.",
            "The results from original query are blended with other results. The reason for blending these other results with the results from original query is populated in the 'Reason' field below.",
            "The results from original query are replaced. The reason for replacing the results from original query is populated in the 'Reason' field below."
          ]
        },
        "interpretedQuery": {
          "type": "string",
          "description": "The interpretation of the query used in search. For example, queries with natural language intent like \"email from john\" will be interpreted as \"from:john source:mail\". This field will not be filled when the reason is NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY."
        }
      }
    },
    "HtmlPropertyOptions": {
      "description": "The options for html properties.",
      "id": "HtmlPropertyOptions",
      "properties": {
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval. Can only be set to DEFAULT or NONE."
        },
        "operatorOptions": {
          "description": "If set, describes how the property should be used as a search operator.",
          "$ref": "HtmlOperatorOptions"
        }
      },
      "type": "object"
    },
    "GSuitePrincipal": {
      "id": "GSuitePrincipal",
      "type": "object",
      "properties": {
        "gsuiteGroupEmail": {
          "description": "This principal references a Google Workspace group name.",
          "type": "string"
        },
        "gsuiteUserEmail": {
          "description": "This principal references a Google Workspace user account.",
          "type": "string"
        },
        "gsuiteDomain": {
          "description": "This principal represents all users of the Google Workspace domain of the customer.",
          "type": "boolean"
        }
      }
    },
    "PeopleSuggestion": {
      "type": "object",
      "description": "This field contains information about the person being suggested.",
      "properties": {
        "person": {
          "description": "Suggested person. All fields of the person object might not be populated.",
          "$ref": "Person"
        }
      },
      "id": "PeopleSuggestion"
    },
    "SuggestResult": {
      "description": "One suggestion result.",
      "properties": {
        "source": {
          "description": "The source of the suggestion.",
          "$ref": "Source"
        },
        "peopleSuggestion": {
          "description": "This is present when the suggestion indicates a person. It contains more information about the person - like their email ID, name etc.",
          "$ref": "PeopleSuggestion"
        },
        "suggestedQuery": {
          "description": "The suggested query that will be used for search, when the user clicks on the suggestion",
          "type": "string"
        },
        "querySuggestion": {
          "description": "This field will be present if the suggested query is a word/phrase completion.",
          "$ref": "QuerySuggestion"
        }
      },
      "id": "SuggestResult",
      "type": "object"
    },
    "IndexItemRequest": {
      "id": "IndexItemRequest",
      "type": "object",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "item": {
          "description": "The name of the item. Format: datasources/{source_id}/items/{item_id}",
          "$ref": "Item"
        },
        "mode": {
          "type": "string",
          "enumDescriptions": [
            "The priority is not specified in the update request. Leaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the caller."
          ],
          "description": "Required. The RequestMode for this request.",
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ]
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        }
      }
    },
    "ObjectOptions": {
      "properties": {
        "freshnessOptions": {
          "description": "The freshness options for an object.",
          "$ref": "FreshnessOptions"
        },
        "displayOptions": {
          "description": "The options that determine how the object is displayed in the Cloud Search results page.",
          "$ref": "ObjectDisplayOptions"
        },
        "suggestionFilteringOperators": {
          "description": "Operators that can be used to filter suggestions. For Suggest API, only operators mentioned here will be honored in the FilterOptions. Only TEXT and ENUM operators are supported. NOTE: \"objecttype\", \"type\" and \"mimetype\" are already supported. This property is to configure schema specific operators. Even though this is an array, only one operator can be specified. This is an array for future extensibility. Operators mapping to multiple properties within the same o[...]",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "The options for an object.",
      "id": "ObjectOptions"
    },
    "PropertyDisplayOptions": {
      "description": "The display options for a property.",
      "type": "object",
      "id": "PropertyDisplayOptions",
      "properties": {
        "displayLabel": {
          "description": "The user friendly label for the property that is used if the property is specified to be displayed in ObjectDisplayOptions. If provided, the display label is shown in front of the property values when the property is part of the object display options. For example, if the property value is '1', the value by itself may not be useful context for the user. If the display name given was 'priority', then the user sees 'priority : 1' in the search results which provides clear[...]",
          "type": "string"
        }
      }
    },
    "PollItemsResponse": {
      "type": "object",
      "id": "PollItemsResponse",
      "properties": {
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array",
          "description": "Set of items from the queue available for connector to process. These items have the following subset of fields populated: version metadata.hash structured_data.hash content.hash payload status queue"
        }
      }
    },
    "HtmlOperatorOptions": {
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the html property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator return all items where *\u003cvalue\u003e* matches the value of any html pr[...]"
        }
      },
      "type": "object",
      "id": "HtmlOperatorOptions",
      "description": "Used to provide a search operator for html properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched."
    },
    "PushItemRequest": {
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "item": {
          "description": "Item to push onto the queue.",
          "$ref": "PushItem"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "PushItemRequest",
      "type": "object"
    },
    "Schema": {
      "id": "Schema",
      "description": "The schema definition for a data source.",
      "type": "object",
      "properties": {
        "operationIds": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema. After modifying the schema, wait for operations to complete before indexing additional content."
        },
        "objectDefinitions": {
          "description": "The list of top-level objects for the data source. The maximum number of elements is 10.",
          "type": "array",
          "items": {
            "$ref": "ObjectDefinition"
          }
        }
      }
    },
    "SourceResultCount": {
      "id": "SourceResultCount",
      "description": "Per source result count information.",
      "type": "object",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The source the result count information is associated with."
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this source.",
          "type": "string",
          "format": "int64"
        },
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        },
        "resultCountExact": {
          "type": "string",
          "description": "The exact result count for this source.",
          "format": "int64"
        }
      }
    },
    "Operation": {
      "properties": {
        "name": {
          "description": "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.",
          "type": "string"
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        },
        "done": {
          "description": "If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.",
          "type": "boolean"
        },
        "metadata": {
          "type": "object",
          "additionalProperties": {
            "type": "any",
            "description": "Properties of the object. Contains field @type with type URL."
          },
          "description": "Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any."
        }
      },
      "type": "object",
      "description": "This resource represents a long-running operation that is the result of a network API call.",
      "id": "Operation"
    },
    "SearchApplicationUserStats": {
      "type": "object",
      "properties": {
        "date": {
          "description": "The date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "thirtyDaysActiveUsersCount": {
          "description": "The count of unique active users in the past thirty days",
          "type": "string",
          "format": "int64"
        },
        "sevenDaysActiveUsersCount": {
          "format": "int64",
          "description": "The count of unique active users in the past seven days",
          "type": "string"
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "type": "string",
          "format": "int64"
        }
      },
      "id": "SearchApplicationUserStats"
    },
    "ResultDisplayField": {
      "type": "object",
      "description": "Display Fields for Search Results",
      "properties": {
        "label": {
          "type": "string",
          "description": "The display label for the property."
        },
        "operatorName": {
          "type": "string",
          "description": "The operator name of the property."
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        }
      },
      "id": "ResultDisplayField"
    },
    "ItemMetadata": {
      "description": "Available metadata fields for the item.",
      "id": "ItemMetadata",
      "type": "object",
      "properties": {
        "updateTime": {
          "type": "string",
          "format": "google-datetime",
          "description": "The time when the item was last modified in the source repository."
        },
        "createTime": {
          "format": "google-datetime",
          "description": "The time when the item was created in the source repository.",
          "type": "string"
        },
        "mimeType": {
          "type": "string",
          "description": "The original mime-type of ItemContent.content in the source repository. The maximum length is 256 characters."
        },
        "sourceRepositoryUrl": {
          "type": "string",
          "description": "Link to the source repository serving the data. Seach results apply this link to the title. Whitespace or special characters may cause Cloud Seach result links to trigger a redirect notice; to avoid this, encode the URL. The maximum length is 2048 characters."
        },
        "title": {
          "type": "string",
          "description": "The title of the item. If given, this will be the displayed title of the Search result. The maximum length is 2048 characters."
        },
        "searchQualityMetadata": {
          "$ref": "SearchQualityMetadata",
          "description": "Additional search quality metadata of the item"
        },
        "keywords": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "Additional keywords or phrases that should match the item. Used internally for user generated content. The maximum number of elements is 100. The maximum length is 8192 characters."
        },
        "contextAttributes": {
          "type": "array",
          "description": "A set of named attributes associated with the item. This can be used for influencing the ranking of the item based on the context in the request. The maximum number of elements is 10.",
          "items": {
            "$ref": "ContextAttribute"
          }
        },
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. The maximum length is 32 characters.",
          "type": "string"
        },
        "objectType": {
          "description": "The type of the item. This should correspond to the name of an object definition in the schema registered for the data source. For example, if the schema for the data source contains an object definition with name 'document', then item indexing requests for objects of that type should set objectType to 'document'. The maximum length is 256 characters.",
          "type": "string"
        },
        "containerName": {
          "description": "The name of the container for this item. Deletion of the container item leads to automatic deletion of this item. Note: ACLs are not inherited from a container item. To provide ACL inheritance for an item, use the inheritAclFrom field. The maximum length is 1536 characters.",
          "type": "string"
        },
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "interactions": {
          "items": {
            "$ref": "Interaction"
          },
          "type": "array",
          "description": "A list of interactions for the item. Interactions are used to improve Search quality, but are not exposed to end users. The maximum number of elements is 1000."
        }
      }
    },
    "ListOperationsResponse": {
      "id": "ListOperationsResponse",
      "properties": {
        "nextPageToken": {
          "description": "The standard List next-page token.",
          "type": "string"
        },
        "operations": {
          "description": "A list of operations that matches the specified filter in the request.",
          "type": "array",
          "items": {
            "$ref": "Operation"
          }
        }
      },
      "type": "object",
      "description": "The response message for Operations.ListOperations."
    },
    "ContextAttribute": {
      "id": "ContextAttribute",
      "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched."
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched."
        }
      },
      "type": "object"
    },
    "DatePropertyOptions": {
      "description": "The options for date properties.",
      "id": "DatePropertyOptions",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "DateOperatorOptions",
          "description": "If set, describes how the date should be used as a search operator."
        }
      }
    },
    "Value": {
      "properties": {
        "dateValue": {
          "$ref": "Date"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "timestampValue": {
          "type": "string",
          "format": "google-datetime"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "stringValue": {
          "type": "string"
        },
        "integerValue": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "Value",
      "type": "object",
      "description": "Definition of a single value with generic type."
    },
    "FreshnessOptions": {
      "description": "Indicates which freshness property to use when adjusting search ranking for an item. Fresher, more recent dates indicate higher quality. Use the freshness option property that best works with your data. For fileshare documents, last modified time is most relevant. For calendar event data, the time when the event occurs is a more relevant freshness indicator. In this way, calendar events that occur closer to the time of the search query are considered higher quality and rank[...]",
      "type": "object",
      "properties": {
        "freshnessProperty": {
          "type": "string",
          "description": "This property indicates the freshness level of the object in the index. If set, this property must be a top-level property within the property definitions and it must be a timestamp type or date type. Otherwise, the Indexing API uses updateTime as the freshness indicator. The maximum length is 256 characters. When a property is used to calculate freshness, the value defaults to 2 years from the current time."
        },
        "freshnessDuration": {
          "format": "google-duration",
          "description": "The duration after which an object should be considered stale. The default value is 180 days (in seconds).",
          "type": "string"
        }
      },
      "id": "FreshnessOptions"
    },
    "EnumValues": {
      "description": "List of enum values.",
      "properties": {
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "The maximum allowable length for string values is 32 characters."
        }
      },
      "type": "object",
      "id": "EnumValues"
    },
    "CustomerIndexStats": {
      "type": "object",
      "properties": {
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array",
          "description": "Number of items aggregrated by status code."
        },
        "date": {
          "description": "The date for which statistics were calculated.",
          "$ref": "Date"
        }
      },
      "id": "CustomerIndexStats",
      "description": "Aggregation of items by status code as of the specified date."
    },
    "DataSource": {
      "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search.",
      "properties": {
        "operationIds": {
          "type": "array",
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
          "items": {
            "type": "string"
          }
        },
        "displayName": {
          "description": "Required. Display name of the datasource The maximum length is 300 characters.",
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "The name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource."
        },
        "returnThumbnailUrls": {
          "type": "boolean",
          "description": "Can a user request to get thumbnail URI for Items indexed in this data source."
        },
        "itemsVisibility": {
          "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility.",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "type": "array"
        },
        "disableServing": {
          "type": "boolean",
          "description": "Disable serving any search or assist results."
        },
        "indexingServiceAccounts": {
          "description": "List of service accounts that have indexing access.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "shortName": {
          "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *\u003cvalue\u003e* then queries like *source:\u003cvalue\u003e* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, h[...]",
          "type": "string"
        },
        "disableModifications": {
          "type": "boolean",
          "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data."
        }
      },
      "id": "DataSource",
      "type": "object"
    },
    "ShareScope": {
      "properties": {
        "domain": {
          "description": "If scope is DOMAIN, this field contains the dasher domain, for example \"google.com\".",
          "type": "string"
        },
        "scope": {
          "description": "The scope to which the content was shared.",
          "enum": [
            "UNKNOWN",
            "PRIVATE",
            "LIMITED",
            "EXTENDED",
            "DASHER_DOMAIN",
            "PUBLIC"
          ],
          "enumDescriptions": [
            "",
            "Only the author can view the post.",
            "Viewable only by a set of people.",
            "Viewable by extended circles.",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "id": "ShareScope",
      "type": "object"
    },
    "GoogleDocsResultInfo": {
      "id": "GoogleDocsResultInfo",
      "properties": {
        "mimeType": {
          "type": "string",
          "description": "The mimetype of the document."
        },
        "cosmoNameSpace": {
          "description": "For Cosmo objects, the Cosmo namespace the object was in. This allows downstream clients to identify whether a document was created in Writely or Kix, Presently or Punch, or whether it was uploaded from GDrive. See storage_cosmo.Id.NAME_SPACE for a list of all Cosmo name spaces.",
          "format": "int32",
          "type": "integer"
        },
        "cosmoId": {
          "$ref": "Id",
          "description": "The storage identifier for the object in Cosmo. This field is intended to used by Stratus/Moonshine integration only. It should not be exposed externally (please refer to encrypted_id for that purpose)."
        },
        "encryptedId": {
          "type": "string",
          "description": "The encrypted (user-visible) id of this object. Knowing the id is sufficient to create a canonical URL for this document."
        },
        "attachmentSha1": {
          "type": "string",
          "description": "The SHA1 hash of the object in Drive, if any."
        },
        "shareScope": {
          "$ref": "ShareScope",
          "description": "The visibility indicator in the UI will be based upon this."
        }
      },
      "type": "object",
      "description": "A message containing information about a specific result. This information is passed to the scorer and beyond; in particular, GWS relies on it to format the result in the UI. Split from GoogleDocsMetadata in case we later want to reuse the message."
    },
    "StartUploadItemRequest": {
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "connectorName": {
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        }
      },
      "type": "object",
      "id": "StartUploadItemRequest",
      "description": "Start upload file request."
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one FacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "properties": {
        "operatorName": {
          "description": "The name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet. Defaults to 10. Maximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id} If empty, all data sources will be used.",
          "type": "string"
        },
        "objectType": {
          "type": "string",
          "description": "If object_type is set, only those objects of that type will be used to compute facets. If empty, then all objects will be used to compute facets."
        }
      },
      "type": "object"
    },
    "StructuredDataObject": {
      "id": "StructuredDataObject",
      "properties": {
        "properties": {
          "description": "The properties for the object. The maximum number of elements is 1000.",
          "items": {
            "$ref": "NamedProperty"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "A structured data object consisting of named properties."
    },
    "Filter": {
      "description": "A generic way of expressing filters in a query, which supports two approaches: **1. Setting a ValueFilter.** The name must match an operator_name defined in the schema for your data source. **2. Setting a CompositeFilter.** The filters are evaluated using the logical operator. The top-level operators can only be either an AND or a NOT. AND can appear only at the top-most level. OR can appear only under a top-level AND.",
      "type": "object",
      "properties": {
        "valueFilter": {
          "$ref": "ValueFilter"
        },
        "compositeFilter": {
          "$ref": "CompositeFilter"
        }
      },
      "id": "Filter"
    },
    "SpellResult": {
      "properties": {
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested spelling of the query."
        }
      },
      "id": "SpellResult",
      "type": "object"
    },
    "ResponseDebugInfo": {
      "properties": {
        "formattedDebugInfo": {
          "type": "string",
          "description": "General debug info formatted for display."
        }
      },
      "type": "object",
      "id": "ResponseDebugInfo",
      "description": "Debugging information about the response."
    },
    "DriveMimeTypeRestrict": {
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ]
        }
      },
      "type": "object",
      "id": "DriveMimeTypeRestrict"
    },
    "AvatarInfo": {
      "id": "AvatarInfo",
      "properties": {
        "emoji": {
          "$ref": "Emoji"
        }
      },
      "type": "object"
    },
    "QueryItem": {
      "type": "object",
      "description": "Information relevant only to a query entry.",
      "properties": {
        "isSynthetic": {
          "type": "boolean",
          "description": "True if the text was generated by means other than a previous user search."
        }
      },
      "id": "QueryItem"
    },
    "VPCSettings": {
      "type": "object",
      "id": "VPCSettings",
      "properties": {
        "project": {
          "description": "The resource name of the GCP Project to be used for VPC SC policy check. VPC security settings on this project will be honored for Cloud Search APIs after project_name has been updated through CustomerService. Format: projects/{project_id}",
          "type": "string"
        }
      }
    },
    "UpdateDataSourceRequest": {
      "properties": {
        "source": {
          "$ref": "DataSource"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "UpdateDataSourceRequest",
      "type": "object"
    },
    "PhoneNumber": {
      "description": "A person's Phone Number",
      "properties": {
        "phoneNumber": {
          "description": "The phone number of the person.",
          "type": "string"
        },
        "type": {
          "enum": [
            "OTHER",
            "MOBILE",
            "OFFICE"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      },
      "id": "PhoneNumber",
      "type": "object"
    },
    "CustomerQueryStats": {
      "id": "CustomerQueryStats",
      "properties": {
        "date": {
          "description": "The date for which query stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "GetCustomerSearchApplicationStatsResponse": {
      "description": "Response format for search application stats for a customer.",
      "id": "GetCustomerSearchApplicationStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerSearchApplicationStats"
          },
          "type": "array",
          "description": "Search application stats by date."
        },
        "averageSearchApplicationCount": {
          "format": "int64",
          "description": "Average search application count for the given date range.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SpaceId": {
      "description": "Primary key for Space resource.",
      "id": "SpaceId",
      "type": "object",
      "properties": {
        "spaceId": {
          "description": "Unique, immutable ID of the Space",
          "type": "string"
        }
      }
    },
    "MatchRange": {
      "properties": {
        "start": {
          "type": "integer",
          "description": "Starting position of the match in the snippet.",
          "format": "int32"
        },
        "end": {
          "format": "int32",
          "type": "integer",
          "description": "End of the match in the snippet."
        }
      },
      "type": "object",
      "id": "MatchRange",
      "description": "Matched range of a snippet [start, end)."
    },
    "ResultDebugInfo": {
      "description": "Debugging information about the result.",
      "type": "object",
      "id": "ResultDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      }
    },
    "CustomerSettings": {
      "description": "Represents settings at a customer level.",
      "id": "CustomerSettings",
      "type": "object",
      "properties": {
        "vpcSettings": {
          "$ref": "VPCSettings",
          "description": "VPC SC settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request."
        },
        "auditLoggingSettings": {
          "description": "Audit Logging settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request.",
          "$ref": "AuditLoggingSettings"
        }
      }
    },
    "ScoringConfig": {
      "description": "Scoring configurations for a source while processing a Search or Suggest request.",
      "id": "ScoringConfig",
      "type": "object",
      "properties": {
        "disableFreshness": {
          "type": "boolean",
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used as a ranking signal. Note that this setting is not available in the Admin UI."
        },
        "disablePersonalization": {
          "type": "boolean",
          "description": "Whether to personalize the results. By default, personal signals will be used to boost results."
        }
      }
    },
    "GetCustomerUserStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerUserStats"
          }
        }
      },
      "id": "GetCustomerUserStatsResponse"
    },
    "CustomerSessionStats": {
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned."
        },
        "searchSessionsCount": {
          "format": "int64",
          "type": "string",
          "description": "The count of search sessions on the day"
        }
      },
      "type": "object",
      "id": "CustomerSessionStats"
    },
    "EnumPropertyOptions": {
      "id": "EnumPropertyOptions",
      "type": "object",
      "description": "The options for enum properties, which allow you to define a restricted set of strings to match user queries, set rankings for those string values, and define an operator name to be paired with those strings so that users can narrow results to only items with a specific value. For example, for items in a request tracking system with priority information, you could define *p0* as an allowable enum value and tie this enum to the operator name *priority* so that search users c[...]",
      "properties": {
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All EnumValuePairs must provide a string value. If you specify an integer value for one EnumValuePair, then all possible EnumValuePairs must provide an integer value. Both the string value and integer value must be unique over all possible values. Once set, possible values cannot be removed or modified. If you supply an ordered ranking and think you might insert additional enum values in the future, leave gaps in[...]",
          "type": "array",
          "items": {
            "$ref": "EnumValuePair"
          }
        },
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        },
        "orderedRanking": {
          "enumDescriptions": [
            "There is no ranking order for the property. Results aren't adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "type": "string",
          "description": "Used to specify the ordered ranking for the enumeration that determines how the integer values provided in the possible EnumValuePairs are used to rank results. If specified, integer values must be provided for all possible EnumValuePair values given for this property. Can only be used if isRepeatable is false."
        }
      }
    },
    "ListDataSourceResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "DataSource"
          }
        }
      },
      "id": "ListDataSourceResponse"
    },
    "CustomerId": {
      "properties": {
        "customerId": {
          "type": "string"
        }
      },
      "description": "Represents a GSuite customer ID. Obfuscated with CustomerIdObfuscator.",
      "type": "object",
      "id": "CustomerId"
    },
    "FilterOptions": {
      "properties": {
        "filter": {
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`.",
          "$ref": "Filter"
        },
        "objectType": {
          "description": "If object_type is set, only objects of that type are returned. This should correspond to the name of the object that was registered within the definition of schema. The maximum length is 256 characters.",
          "type": "string"
        }
      },
      "type": "object",
      "id": "FilterOptions",
      "description": "Filter options to be applied on query."
    },
    "IntegerPropertyOptions": {
      "properties": {
        "orderedRanking": {
          "type": "string",
          "description": "Used to specify the ordered ranking for the integer. Can only be used if isRepeatable is false.",
          "enumDescriptions": [
            "There is no ranking order for the property. Results are not adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ]
        },
        "minimumValue": {
          "type": "string",
          "format": "int64",
          "description": "The minimum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values less than the minimum are accepted and ranked with the same weight as items indexed with the minimum value."
        },
        "operatorOptions": {
          "$ref": "IntegerOperatorOptions",
          "description": "If set, describes how the integer should be used as a search operator."
        },
        "maximumValue": {
          "description": "The maximum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values greater than the maximum are accepted and ranked with the same weight as items indexed with the maximum value.",
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object",
      "description": "The options for integer properties.",
      "id": "IntegerPropertyOptions"
    },
    "Person": {
      "type": "object",
      "description": "Object to represent a person.",
      "properties": {
        "name": {
          "type": "string",
          "description": "The resource name of the person to provide information about. See [`People.get`](https://developers.google.com/people/api/rest/v1/people/get) from the Google People API."
        },
        "obfuscatedId": {
          "type": "string",
          "description": "Obfuscated ID of a person."
        },
        "phoneNumbers": {
          "type": "array",
          "items": {
            "$ref": "PhoneNumber"
          },
          "description": "The person's phone numbers"
        },
        "personNames": {
          "items": {
            "$ref": "Name"
          },
          "type": "array",
          "description": "The person's name"
        },
        "photos": {
          "type": "array",
          "items": {
            "$ref": "Photo"
          },
          "description": "A person's read-only photo. A picture shown next to the person's name to help others recognize the person in search results."
        },
        "emailAddresses": {
          "description": "The person's email addresses",
          "items": {
            "$ref": "EmailAddress"
          },
          "type": "array"
        }
      },
      "id": "Person"
    },
    "SearchRequest": {
      "properties": {
        "requestOptions": {
          "description": "Request options, such as the search application and user timezone.",
          "$ref": "RequestOptions"
        },
        "dataSourceRestrictions": {
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "The sources to use for querying. If not specified, all data sources from the current search application are used."
        },
        "sortOptions": {
          "description": "The options for sorting the search results",
          "$ref": "SortOptions"
        },
        "contextAttributes": {
          "items": {
            "$ref": "ContextAttribute"
          },
          "description": "Context attributes for the request which will be used to adjust ranking of search results. The maximum number of elements is 10.",
          "type": "array"
        },
        "queryInterpretationOptions": {
          "$ref": "QueryInterpretationOptions",
          "description": "Options to interpret the user query."
        },
        "facetOptions": {
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array"
        },
        "pageSize": {
          "type": "integer",
          "description": "Maximum number of search results to return in one page. Valid values are between 1 and 100, inclusive. Default value is 10. Minimum value is 50 when results beyond 2000 are requested.",
          "format": "int32"
        },
        "start": {
          "type": "integer",
          "description": "Starting index of the results.",
          "format": "int32"
        },
        "query": {
          "type": "string",
          "description": "The raw query string. See supported search operators in the [Narrow your search with operators](https://support.google.com/cloudsearch/answer/6172299)"
        }
      },
      "description": "The search API request.",
      "id": "SearchRequest",
      "type": "object"
    },
    "TextOperatorOptions": {
      "description": "Used to provide a search operator for text properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "TextOperatorOptions",
      "type": "object",
      "properties": {
        "exactMatchWithOperator": {
          "description": "If true, the text value is tokenized as one atomic value in operator searches and facet matches. For example, if the operator name is \"genre\" and the value is \"science-fiction\" the query restrictions \"genre:science\" and \"genre:fiction\" doesn't match the item; \"genre:science-fiction\" does. Text value matching is case-sensitive and does not remove special characters. If false, the text is tokenized. For example, if the value is \"science-fiction\" the queries \"[...]",
          "type": "boolean"
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the text property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any text p[...]"
        }
      }
    },
    "ItemStructuredData": {
      "description": "Available structured data fields for the item.",
      "properties": {
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "object": {
          "$ref": "StructuredDataObject",
          "description": "The structured data object that should conform to a registered object definition in the schema for the data source."
        }
      },
      "id": "ItemStructuredData",
      "type": "object"
    },
    "ListQuerySourcesResponse": {
      "id": "ListQuerySourcesResponse",
      "type": "object",
      "properties": {
        "sources": {
          "type": "array",
          "items": {
            "$ref": "QuerySource"
          }
        },
        "nextPageToken": {
          "type": "string"
        }
      },
      "description": "List sources response."
    },
    "NamedProperty": {
      "id": "NamedProperty",
      "description": "A typed name-value pair for structured data. The type of the value should be the same as the registered type for the `name` property in the object definition of `objectType`.",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the property. This name should correspond to the name of the property that was registered for object definition in the schema. The maximum allowable length for this property is 256 characters.",
          "type": "string"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "textValues": {
          "$ref": "TextValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        }
      }
    },
    "SpaceInfo": {
      "properties": {
        "userMembershipState": {
          "enum": [
            "MEMBER_UNKNOWN",
            "MEMBER_INVITED",
            "MEMBER_JOINED",
            "MEMBER_NOT_A_MEMBER",
            "MEMBER_FAILED"
          ],
          "description": "searching user's membership state in this space",
          "type": "string",
          "enumDescriptions": [
            "Default state, do not use",
            "An invitation to the space has been sent",
            "User has joined the space",
            "User is not a member",
            "This state should never be stored in Spanner. It is a state for responses to the clients to indicate that membership mutations have failed and the member is in its previous state."
          ]
        },
        "description": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "inviterEmail": {
          "type": "string",
          "description": "The email address of the user that invited the calling user to the room, if available. This field will only be populated for direct invites, it will be empty if the user was indirectly invited to the group."
        },
        "groupId": {
          "$ref": "GroupId"
        },
        "numMembers": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "isExternal": {
          "type": "boolean",
          "description": "Whether this is a space that enables guest access"
        },
        "avatarInfo": {
          "$ref": "AvatarInfo"
        }
      },
      "id": "SpaceInfo",
      "description": "Defines the representation of a single matching space.",
      "type": "object"
    },
    "Metaline": {
      "type": "object",
      "properties": {
        "properties": {
          "items": {
            "$ref": "DisplayedProperty"
          },
          "type": "array",
          "description": "The list of displayed properties for the metaline. The maximum number of properties is 5."
        }
      },
      "id": "Metaline",
      "description": "A metaline is a list of properties that are displayed along with the search result to provide context."
    },
    "ResultDisplayMetadata": {
      "id": "ResultDisplayMetadata",
      "type": "object",
      "properties": {
        "objectTypeLabel": {
          "type": "string",
          "description": "The display label for the object."
        },
        "metalines": {
          "description": "The metalines content to be displayed with the result.",
          "items": {
            "$ref": "ResultDisplayLine"
          },
          "type": "array"
        }
      }
    },
    "InitializeCustomerRequest": {
      "type": "object",
      "properties": {},
      "id": "InitializeCustomerRequest",
      "description": "Request message for `InitializeCustomer` method."
    },
    "SearchResponse": {
      "type": "object",
      "description": "The search API response.",
      "id": "SearchResponse",
      "properties": {
        "results": {
          "description": "Results from a search query.",
          "items": {
            "$ref": "SearchResult"
          },
          "type": "array"
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "queryInterpretation": {
          "description": "Query interpretation result for user query. Empty if query interpretation is disabled.",
          "$ref": "QueryInterpretation"
        },
        "debugInfo": {
          "$ref": "ResponseDebugInfo",
          "description": "Debugging information about the response."
        },
        "facetResults": {
          "type": "array",
          "items": {
            "$ref": "FacetResult"
          },
          "description": "Repeated facet results."
        },
        "resultCounts": {
          "description": "Expanded result count information.",
          "$ref": "ResultCounts"
        },
        "spellResults": {
          "description": "Suggested spelling for the query.",
          "type": "array",
          "items": {
            "$ref": "SpellResult"
          }
        },
        "resultCountExact": {
          "description": "The exact result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "hasMoreResults": {
          "type": "boolean",
          "description": "Whether there are more search results matching the query."
        },
        "resultCountEstimate": {
          "type": "string",
          "format": "int64",
          "description": "The estimated result count for this query."
        },
        "structuredResults": {
          "description": "Structured results for the user query. These results are not counted against the page_size.",
          "items": {
            "$ref": "StructuredResult"
          },
          "type": "array"
        }
      }
    },
    "Interaction": {
      "type": "object",
      "id": "Interaction",
      "description": "Represents an interaction between a user and an item.",
      "properties": {
        "principal": {
          "$ref": "Principal",
          "description": "The user that acted on the item."
        },
        "interactionTime": {
          "format": "google-datetime",
          "description": "The time when the user acted on the item. If multiple actions of the same type exist for a single user, only the most recent action is recorded.",
          "type": "string"
        },
        "type": {
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ],
          "type": "string"
        }
      }
    },
    "FacetBucket": {
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object.",
      "id": "FacetBucket",
      "properties": {
        "count": {
          "type": "integer",
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Cloud Search does not guarantee facet counts for any query and facet counts might be present only intermittently, even for identical queries. Do not build dependencies on facet count existence; instead use facet ount percentages which are always returned.",
          "format": "int32"
        },
        "percentage": {
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts.",
          "type": "integer",
          "format": "int32"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "type": "object"
    },
    "IndexItemOptions": {
      "type": "object",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow Google Workspace principals that do not exist or are deleted.",
          "type": "boolean"
        }
      },
      "id": "IndexItemOptions"
    },
    "RetrievalImportance": {
      "type": "object",
      "id": "RetrievalImportance",
      "properties": {
        "importance": {
          "type": "string",
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still be used for operator matching, faceting, and suggest if desired."
          ],
          "description": "Indicates the ranking importance given to property when it is matched during retrieval. Once set, the token importance of a property cannot be changed.",
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ]
        }
      }
    },
    "IntegerValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "int64"
          }
        }
      },
      "id": "IntegerValues",
      "type": "object",
      "description": "List of integer values."
    },
    "AuditLoggingSettings": {
      "properties": {
        "logAdminReadActions": {
          "description": "Indicates whether audit logging is on/off for admin activity read APIs i.e. Get/List DataSources, Get/List SearchApplications etc.",
          "type": "boolean"
        },
        "logDataReadActions": {
          "description": "Indicates whether audit logging is on/off for data access read APIs i.e. ListItems, GetItem etc.",
          "type": "boolean"
        },
        "logDataWriteActions": {
          "description": "Indicates whether audit logging is on/off for data access write APIs i.e. IndexItem etc.",
          "type": "boolean"
        },
        "project": {
          "type": "string",
          "description": "The resource name of the GCP Project to store audit logs. Cloud audit logging will be enabled after project_name has been updated through CustomerService. Format: projects/{project_id}"
        }
      },
      "type": "object",
      "id": "AuditLoggingSettings",
      "description": "Represents the settings for Cloud audit logging"
    },
    "SearchApplicationQueryStats": {
      "id": "SearchApplicationQueryStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        },
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "Search application level query stats per date"
    },
    "HtmlValues": {
      "type": "object",
      "properties": {
        "values": {
          "description": "The maximum allowable length for html values is 2048 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "id": "HtmlValues",
      "description": "List of html values."
    },
    "StructuredResult": {
      "description": "Structured results that are returned as part of search request.",
      "id": "StructuredResult",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Representation of a person"
        }
      },
      "type": "object"
    },
    "SearchApplication": {
      "id": "SearchApplication",
      "description": "SearchApplication",
      "properties": {
        "defaultSortOptions": {
          "description": "The default options for sorting the search results",
          "$ref": "SortOptions"
        },
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the Search Application. The maximum length is 300 characters."
        },
        "dataSourceRestrictions": {
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array",
          "description": "Retrictions applied to the configurations. The maximum number of elements is 10."
        },
        "defaultFacetOptions": {
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array",
          "description": "The default fields for returning facet results. The sources specified here also have been included in data_source_restrictions above."
        },
        "sourceConfig": {
          "items": {
            "$ref": "SourceConfig"
          },
          "type": "array",
          "description": "Configuration for a sources specified in data_source_restrictions."
        },
        "returnResultThumbnailUrls": {
          "description": "With each result we should return the URI for its thumbnail (when applicable)",
          "type": "boolean"
        },
        "enableAuditLog": {
          "description": "Indicates whether audit logging is on/off for requests made for the search application in query APIs.",
          "type": "boolean"
        },
        "operationIds": {
          "type": "array",
          "description": "Output only. IDs of the Long Running Operations (LROs) currently running for this schema. Output only field.",
          "items": {
            "type": "string"
          },
          "readOnly": true
        },
        "queryInterpretationConfig": {
          "$ref": "QueryInterpretationConfig",
          "description": "The default options for query interpretation"
        },
        "name": {
          "type": "string",
          "description": "The name of the Search Application. Format: searchapplications/{application_id}."
        }
      },
      "type": "object"
    },
    "PollItemsRequest": {
      "id": "PollItemsRequest",
      "type": "object",
      "properties": {
        "limit": {
          "format": "int32",
          "description": "Maximum number of items to return. The maximum value is 100 and the default value is 20.",
          "type": "integer"
        },
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "queue": {
          "description": "Queue name to fetch items from. If unspecified, PollItems will fetch from 'default' queue. The maximum length is 100 characters.",
          "type": "string"
        },
        "statusCodes": {
          "type": "array",
          "description": "Limit the items polled to the ones with these statuses.",
          "items": {
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ],
            "type": "string",
            "enumDescriptions": [
              "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
              "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
              "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
              "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
              "API has accepted the up-to-date data of this item."
            ]
          }
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      }
    },
    "DisplayedProperty": {
      "type": "object",
[...]
