{
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "name": "cloudidentity",
  "ownerDomain": "google.com",
  "servicePath": "",
  "documentationLink": "https://cloud.google.com/identity/",
  "basePath": "",
  "id": "cloudidentity:v1",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "resources": {
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "get": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`.",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.get"
            },
            "modifyMembershipRoles": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "httpMethod": "POST",
              "path": "v1/{+name}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.list",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "description": "Lists the `Membership`s within a `Group`.",
              "path": "v1/{+parent}/memberships"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "id": "cloudidentity.groups.memberships.create",
              "description": "Creates a `Membership`.",
              "path": "v1/{+parent}/memberships"
            },
            "delete": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`."
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership"
            },
            "searchTransitiveMemberships": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships"
            },
            "getMembershipGraph": {
              "httpMethod": "GET",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph"
            },
            "searchTransitiveGroups": {
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "httpMethod": "GET"
            },
            "lookup": {
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`."
            }
          }
        }
      },
      "methods": {
        "search": {
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "httpMethod": "GET",
          "flatPath": "v1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Searches for `Group` resources matching a specified query."
        },
        "getSecuritySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "httpMethod": "GET",
          "description": "Get Security Settings",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.getSecuritySettings"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`.",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.patch"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.get",
          "path": "v1/{+name}",
          "description": "Retrieves a `Group`.",
          "flatPath": "v1/groups/{groupsId}"
        },
        "create": {
          "id": "cloudidentity.groups.create",
          "flatPath": "v1/groups",
          "httpMethod": "POST",
          "path": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a Group."
        },
        "lookup": {
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups:lookup",
          "id": "cloudidentity.groups.lookup",
          "path": "v1/groups:lookup",
          "httpMethod": "GET"
        },
        "list": {
          "id": "cloudidentity.groups.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the `Group` resources under a customer or namespace.",
          "flatPath": "v1/groups",
          "path": "v1/groups"
        },
        "updateSecuritySettings": {
          "description": "Update Security Settings",
          "httpMethod": "PATCH",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.updateSecuritySettings"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "list": {
              "id": "cloudidentity.customers.userinvitations.list",
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "path": "v1/{+parent}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.userinvitations",
                "https://www.googleapis.com/auth/cloud-identity.userinvitations.readonly"
              ],
              "httpMethod": "GET"
            },
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.userinvitations",
                "https://www.googleapis.com/auth/cloud-identity.userinvitations.readonly"
              ],
              "path": "v1/{+name}",
              "httpMethod": "GET"
            },
            "isInvitableUser": {
              "path": "v1/{+name}:isInvitableUser",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.userinvitations",
                "https://www.googleapis.com/auth/cloud-identity.userinvitations.readonly"
              ]
            },
            "send": {
              "id": "cloudidentity.customers.userinvitations.send",
              "httpMethod": "POST",
              "path": "v1/{+name}:send",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.userinvitations"
              ],
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True."
            },
            "cancel": {
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.userinvitations"
              ],
              "httpMethod": "POST",
              "description": "Cancels a UserInvitation that was already sent.",
              "path": "v1/{+name}:cancel",
              "id": "cloudidentity.customers.userinvitations.cancel"
            }
          }
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "cancelWipe": {
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "path": "v1/{+name}:cancelWipe"
            },
            "approve": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1/{+name}:approve",
              "description": "Approves device to access user data."
            },
            "wipe": {
              "path": "v1/{+name}:wipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "httpMethod": "POST"
            },
            "lookup": {
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "httpMethod": "GET",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "path": "v1/{+parent}:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "httpMethod": "DELETE"
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1/{+name}:block",
              "description": "Blocks device from accessing user data"
            },
            "list": {
              "id": "cloudidentity.devices.deviceUsers.list",
              "description": "Lists/Searches DeviceUsers.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "path": "v1/{+parent}/deviceUsers",
              "flatPath": "v1/devices/{devicesId}/deviceUsers"
            },
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "path": "v1/{+name}",
              "description": "Retrieves the specified DeviceUser",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "patch": {
                  "path": "v1/{+name}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "httpMethod": "PATCH",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity",
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ]
                },
                "get": {
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the client state for the device user",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity",
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get"
                },
                "list": {
                  "description": "Lists the client states for the given search query.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity",
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "path": "v1/{+parent}/clientStates",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      },
      "methods": {
        "list": {
          "flatPath": "v1/devices",
          "path": "v1/devices",
          "httpMethod": "GET",
          "id": "cloudidentity.devices.list",
          "description": "Lists/Searches devices.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ]
        },
        "create": {
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.create",
          "path": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Retrieves the specified device.",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.get"
        },
        "cancelWipe": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "path": "v1/{+name}:cancelWipe",
          "httpMethod": "POST",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe"
        },
        "wipe": {
          "path": "v1/{+name}:wipe",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Wipes all data on the specified device.",
          "id": "cloudidentity.devices.wipe",
          "flatPath": "v1/devices/{devicesId}:wipe"
        },
        "delete": {
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Deletes the specified device.",
          "path": "v1/{+name}",
          "id": "cloudidentity.devices.delete"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.userinvitations": {
          "description": "See, send, or cancel any Cloud Identity UserInvitations to join your organization to users"
        },
        "https://www.googleapis.com/auth/cloud-identity.userinvitations.readonly": {
          "description": "See, send, or cancel any Cloud Identity UserInvitations to join your organization to users"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        }
      }
    }
  },
  "title": "Cloud Identity API",
  "kind": "discovery#restDescription",
  "description": "API for provisioning and managing identity resources.",
  "version_module": true,
  "revision": "20220729",
  "batchPath": "batch",
  "version": "v1",
  "canonicalName": "Cloud Identity",
  "protocol": "rest"
}
