{
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "title": "Cloud Identity API",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "name": "cloudidentity",
  "id": "cloudidentity:v1",
  "resources": {
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the client state for the device user"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "path": "v1/{+parent}/clientStates",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "description": "Lists the client states for the given search query.",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "block": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Blocks device from accessing user data",
              "path": "v1/{+name}:block",
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.get",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Retrieves the specified DeviceUser"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "httpMethod": "GET",
              "id": "cloudidentity.devices.deviceUsers.list",
              "path": "v1/{+parent}/deviceUsers",
              "description": "Lists/Searches DeviceUsers."
            },
            "wipe": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1/{+name}:wipe",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "id": "cloudidentity.devices.deviceUsers.delete"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "path": "v1/{+name}:approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Approves device to access user data."
            },
            "lookup": {
              "path": "v1/{+parent}:lookup",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ]
            },
            "cancelWipe": {
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "httpMethod": "POST",
              "path": "v1/{+name}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ]
            }
          }
        }
      },
      "methods": {
        "wipe": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "id": "cloudidentity.devices.wipe",
          "description": "Wipes all data on the specified device.",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "path": "v1/{+name}:wipe"
        },
        "list": {
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.list",
          "description": "Lists/Searches devices.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.create",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
        },
        "get": {
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "GET",
          "description": "Retrieves the specified device.",
          "id": "cloudidentity.devices.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ]
        },
        "cancelWipe": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "id": "cloudidentity.devices.cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancelWipe",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device."
        },
        "delete": {
          "description": "Deletes the specified device.",
          "path": "v1/{+name}",
          "id": "cloudidentity.devices.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "flatPath": "v1/devices/{devicesId}"
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority.",
          "httpMethod": "PATCH",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}"
        },
        "delete": {
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "httpMethod": "DELETE",
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets an InboundSsoAssignment.",
          "httpMethod": "GET",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "id": "cloudidentity.inboundSsoAssignments.get",
          "path": "v1/{+name}"
        },
        "create": {
          "flatPath": "v1/inboundSsoAssignments",
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "path": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.create",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "v1/inboundSsoAssignments",
          "httpMethod": "GET",
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "id": "cloudidentity.inboundSsoAssignments.list",
          "path": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      }
    },
    "inboundSamlSsoProfiles": {
      "methods": {
        "list": {
          "description": "Lists InboundSamlSsoProfiles for a customer.",
          "httpMethod": "GET",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "path": "v1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "description": "Deletes an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates an InboundSamlSsoProfile for a customer.",
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSamlSsoProfiles",
          "path": "v1/inboundSamlSsoProfiles"
        },
        "patch": {
          "description": "Updates an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "description": "Gets an InboundSamlSsoProfile.",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      },
      "resources": {
        "idpCredentials": {
          "methods": {
            "add": {
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed.",
              "path": "v1/{+parent}/idpCredentials:add",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/idpCredentials",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile.",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes an IdpCredential."
            },
            "get": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "description": "Gets an IdpCredential.",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            }
          }
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "searchTransitiveGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1/{+name}",
              "httpMethod": "DELETE"
            },
            "create": {
              "path": "v1/{+parent}/memberships",
              "id": "cloudidentity.groups.memberships.create",
              "httpMethod": "POST",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "modifyMembershipRoles": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "path": "v1/{+name}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "searchTransitiveMemberships": {
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships"
            },
            "get": {
              "description": "Retrieves a `Membership`.",
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "httpMethod": "GET"
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "httpMethod": "GET",
              "description": "Lists the `Membership`s within a `Group`.",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "searchDirectGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups",
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "description": "Searches direct groups of a member.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.searchDirectGroups"
            },
            "lookup": {
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:lookup"
            }
          }
        }
      },
      "methods": {
        "list": {
          "description": "Lists the `Group` resources under a customer or namespace.",
          "flatPath": "v1/groups",
          "path": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "id": "cloudidentity.groups.list"
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates a Group.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create",
          "path": "v1/groups",
          "flatPath": "v1/groups"
        },
        "updateSecuritySettings": {
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.updateSecuritySettings",
          "description": "Update Security Settings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "lookup": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups:lookup",
          "path": "v1/groups:lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "id": "cloudidentity.groups.lookup",
          "httpMethod": "GET"
        },
        "getSecuritySettings": {
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "description": "Get Security Settings",
          "id": "cloudidentity.groups.getSecuritySettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "description": "Retrieves a `Group`.",
          "id": "cloudidentity.groups.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "GET"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE",
          "id": "cloudidentity.groups.delete",
          "description": "Deletes a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "path": "v1/{+name}"
        },
        "search": {
          "path": "v1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups:search",
          "httpMethod": "GET",
          "id": "cloudidentity.groups.search",
          "description": "Searches for `Group` resources matching a specified query."
        },
        "patch": {
          "description": "Updates a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.patch",
          "httpMethod": "PATCH",
          "flatPath": "v1/groups/{groupsId}",
          "path": "v1/{+name}"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "list": {
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.list",
              "path": "v1/{+parent}/userinvitations",
              "flatPath": "v1/customers/{customersId}/userinvitations"
            },
            "send": {
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "id": "cloudidentity.customers.userinvitations.send",
              "httpMethod": "POST",
              "path": "v1/{+name}:send"
            },
            "cancel": {
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "httpMethod": "POST",
              "path": "v1/{+name}:cancel",
              "description": "Cancels a UserInvitation that was already sent."
            },
            "isInvitableUser": {
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "path": "v1/{+name}:isInvitableUser",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]"
            },
            "get": {
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.get"
            }
          }
        }
      }
    }
  },
  "canonicalName": "Cloud Identity",
  "description": "API for provisioning and managing identity resources.",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "servicePath": "",
  "revision": "20230703",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "version": "v1",
  "documentationLink": "https://cloud.google.com/identity/",
  "ownerName": "Google",
  "version_module": true,
  "batchPath": "batch",
  "basePath": ""
}
