{
  "ownerDomain": "google.com",
  "title": "Cloud Identity API",
  "id": "cloudidentity:v1beta1",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "version_module": true,
  "servicePath": "",
  "discoveryVersion": "v1",
  "revision": "20220929",
  "canonicalName": "Cloud Identity",
  "name": "cloudidentity",
  "documentationLink": "https://cloud.google.com/identity/",
  "version": "v1beta1",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "description": "API for provisioning and managing identity resources.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        }
      }
    }
  },
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "resources": {
    "groups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "id": "cloudidentity.groups.list",
          "flatPath": "v1beta1/groups",
          "path": "v1beta1/groups",
          "description": "Lists the `Group` resources under a customer or namespace."
        },
        "getSecuritySettings": {
          "httpMethod": "GET",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.groups.getSecuritySettings",
          "flatPath": "v1beta1/groups/{groupsId}/securitySettings",
          "description": "Get Security Settings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "create": {
          "description": "Creates a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/groups",
          "id": "cloudidentity.groups.create",
          "flatPath": "v1beta1/groups",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Retrieves a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.get",
          "flatPath": "v1beta1/groups/{groupsId}",
          "httpMethod": "GET",
          "path": "v1beta1/{+name}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "httpMethod": "DELETE",
          "path": "v1beta1/{+name}",
          "description": "Deletes a `Group`.",
          "flatPath": "v1beta1/groups/{groupsId}"
        },
        "patch": {
          "description": "Updates a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/groups/{groupsId}",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.groups.patch",
          "httpMethod": "PATCH"
        },
        "search": {
          "flatPath": "v1beta1/groups:search",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.search",
          "path": "v1beta1/groups:search",
          "description": "Searches for `Group` resources matching a specified query."
        },
        "updateSecuritySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Update Security Settings",
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.updateSecuritySettings",
          "flatPath": "v1beta1/groups/{groupsId}/securitySettings",
          "path": "v1beta1/{+name}"
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/groups:lookup",
          "httpMethod": "GET",
          "flatPath": "v1beta1/groups:lookup"
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "searchTransitiveGroups": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1beta1/{+parent}/memberships:searchTransitiveGroups",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1beta1/{+name}",
              "description": "Retrieves a `Membership`.",
              "id": "cloudidentity.groups.memberships.get",
              "httpMethod": "GET"
            },
            "create": {
              "description": "Creates a `Membership`.",
              "path": "v1beta1/{+parent}/memberships",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "id": "cloudidentity.groups.memberships.create"
            },
            "delete": {
              "path": "v1beta1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`.",
              "httpMethod": "DELETE",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}"
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1beta1/{+name}:modifyMembershipRoles",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "list": {
              "path": "v1beta1/{+parent}/memberships",
              "description": "Lists the `Membership`s within a `Group`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.list"
            },
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "httpMethod": "GET",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:getMembershipGraph",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the response will contain all membership paths between the group and the member.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+parent}/memberships:getMembershipGraph"
            },
            "searchTransitiveMemberships": {
              "path": "v1beta1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships"
            },
            "lookup": {
              "path": "v1beta1/{+parent}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup"
            },
            "checkTransitiveMembership": {
              "path": "v1beta1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor must have view permissions to at least one transitive membership between the member and group."
            }
          }
        }
      }
    },
    "orgUnits": {
      "resources": {
        "memberships": {
          "methods": {
            "move": {
              "path": "v1beta1/{+name}:move",
              "flatPath": "v1beta1/orgUnits/{orgUnitsId}/memberships/{membershipsId}:move",
              "id": "cloudidentity.orgUnits.memberships.move",
              "httpMethod": "POST",
              "description": "Move an OrgMembership to a new OrgUnit. NOTE: This is an atomic copy-and-delete. The resource will have a new copy under the destination OrgUnit and be deleted from the source OrgUnit. The resource can only be searched under the destination OrgUnit afterwards."
            },
            "list": {
              "path": "v1beta1/{+parent}/memberships",
              "flatPath": "v1beta1/orgUnits/{orgUnitsId}/memberships",
              "id": "cloudidentity.orgUnits.memberships.list",
              "httpMethod": "GET",
              "description": "List OrgMembership resources in an OrgUnit treated as 'parent'. Parent format: orgUnits/{$orgUnitId} where `$orgUnitId` is the `orgUnitId` from the [Admin SDK `OrgUnit` resource](https://developers.google.com/admin-sdk/directory/reference/rest/v1/orgunits)"
            }
          }
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.get",
          "path": "v1beta1/{+name}",
          "description": "Gets an InboundSsoAssignment.",
          "flatPath": "v1beta1/inboundSsoAssignments/{inboundSsoAssignmentsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.list",
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "httpMethod": "GET",
          "flatPath": "v1beta1/inboundSsoAssignments",
          "path": "v1beta1/inboundSsoAssignments"
        },
        "create": {
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "id": "cloudidentity.inboundSsoAssignments.create",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta1/inboundSsoAssignments",
          "path": "v1beta1/inboundSsoAssignments",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "path": "v1beta1/{+name}",
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1beta1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority.",
          "flatPath": "v1beta1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "flatPath": "v1beta1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "path": "v1beta1/{+name}",
          "httpMethod": "DELETE"
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "approve": {
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1beta1/{+name}:approve",
              "httpMethod": "POST",
              "description": "Approves device to access user data.",
              "id": "cloudidentity.devices.deviceUsers.approve"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "id": "cloudidentity.devices.deviceUsers.get",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "description": "Retrieves the specified DeviceUser"
            },
            "lookup": {
              "httpMethod": "GET",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers:lookup",
              "path": "v1beta1/{+parent}:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "id": "cloudidentity.devices.deviceUsers.lookup"
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "httpMethod": "POST",
              "description": "Blocks device from accessing user data",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1beta1/{+name}:block",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block"
            },
            "wipe": {
              "path": "v1beta1/{+name}:wipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "description": "Wipes the user's account on a device.",
              "id": "cloudidentity.devices.deviceUsers.wipe"
            },
            "delete": {
              "path": "v1beta1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.delete",
              "httpMethod": "DELETE",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "path": "v1beta1/{+parent}/deviceUsers",
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers",
              "httpMethod": "GET"
            },
            "cancelWipe": {
              "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "path": "v1beta1/{+name}:cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ]
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET",
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "path": "v1beta1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ]
                },
                "patch": {
                  "flatPath": "v1beta1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "path": "v1beta1/{+name}",
                  "httpMethod": "PATCH"
                }
              }
            }
          }
        }
      },
      "methods": {
        "delete": {
          "description": "Deletes the specified device.",
          "httpMethod": "DELETE",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.devices.delete",
          "flatPath": "v1beta1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        },
        "cancelWipe": {
          "id": "cloudidentity.devices.cancelWipe",
          "path": "v1beta1/{+name}:cancelWipe",
          "flatPath": "v1beta1/devices/{devicesId}:cancelWipe",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "flatPath": "v1beta1/devices/{devicesId}",
          "description": "Retrieves the specified device.",
          "httpMethod": "GET",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.devices.get"
        },
        "create": {
          "path": "v1beta1/devices",
          "flatPath": "v1beta1/devices",
          "id": "cloudidentity.devices.create",
          "httpMethod": "POST",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        },
        "wipe": {
          "path": "v1beta1/{+name}:wipe",
          "flatPath": "v1beta1/devices/{devicesId}:wipe",
          "description": "Wipes all data on the specified device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "id": "cloudidentity.devices.wipe",
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1beta1/devices",
          "httpMethod": "GET",
          "flatPath": "v1beta1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "id": "cloudidentity.devices.list",
          "description": "Lists/Searches devices."
        }
      }
    },
    "inboundSamlSsoProfiles": {
      "methods": {
        "list": {
          "flatPath": "v1beta1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "path": "v1beta1/inboundSamlSsoProfiles",
          "description": "Lists InboundSamlSsoProfiles for a customer.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "patch": {
          "description": "Updates an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "PATCH",
          "path": "v1beta1/{+name}"
        },
        "get": {
          "description": "Gets an InboundSamlSsoProfile.",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundSamlSsoProfile.",
          "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "path": "v1beta1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.delete"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1beta1/inboundSamlSsoProfiles",
          "httpMethod": "POST",
          "flatPath": "v1beta1/inboundSamlSsoProfiles",
          "description": "Creates an InboundSamlSsoProfile for a customer.",
          "id": "cloudidentity.inboundSamlSsoProfiles.create"
        }
      },
      "resources": {
        "idpCredentials": {
          "methods": {
            "delete": {
              "path": "v1beta1/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes an IdpCredential.",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete"
            },
            "add": {
              "path": "v1beta1/{+parent}/idpCredentials:add",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed.",
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "httpMethod": "POST"
            },
            "get": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets an IdpCredential.",
              "path": "v1beta1/{+name}",
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "v1beta1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+parent}/idpCredentials",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile.",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list"
            }
          }
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "isInvitableUser": {
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "path": "v1beta1/{+name}:isInvitableUser",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]"
            },
            "send": {
              "id": "cloudidentity.customers.userinvitations.send",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "httpMethod": "POST",
              "path": "v1beta1/{+name}:send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True."
            },
            "list": {
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "id": "cloudidentity.customers.userinvitations.list",
              "httpMethod": "GET",
              "path": "v1beta1/{+parent}/userinvitations",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations"
            },
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "path": "v1beta1/{+name}"
            },
            "cancel": {
              "flatPath": "v1beta1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "path": "v1beta1/{+name}:cancel",
              "description": "Cancels a UserInvitation that was already sent.",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "httpMethod": "POST"
            }
          }
        }
      }
    }
  },
  "ownerName": "Google",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "batchPath": "batch",
  "basePath": "",
  "protocol": "rest"
}
