{
  "discoveryVersion": "v1",
  "canonicalName": "Cloud Identity",
  "protocol": "rest",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "version_module": true,
  "servicePath": "",
  "id": "cloudidentity:v1",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        }
      }
    }
  },
  "name": "cloudidentity",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "version": "v1",
  "title": "Cloud Identity API",
  "basePath": "",
  "description": "API for provisioning and managing identity resources.",
  "resources": {
    "inboundSsoAssignments": {
      "methods": {
        "create": {
          "id": "cloudidentity.inboundSsoAssignments.create",
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "httpMethod": "POST",
          "path": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSsoAssignments"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.get",
          "path": "v1/{+name}",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "description": "Gets an InboundSsoAssignment.",
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "flatPath": "v1/inboundSsoAssignments",
          "path": "v1/inboundSsoAssignments",
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.list",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority.",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.patch"
        }
      }
    },
    "devices": {
      "methods": {
        "cancelWipe": {
          "path": "v1/{+name}:cancelWipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device."
        },
        "create": {
          "id": "cloudidentity.devices.create",
          "flatPath": "v1/devices",
          "path": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
        },
        "delete": {
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.delete",
          "description": "Deletes the specified device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "DELETE",
          "path": "v1/{+name}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "id": "cloudidentity.devices.list",
          "flatPath": "v1/devices",
          "httpMethod": "GET",
          "path": "v1/devices",
          "description": "Lists/Searches devices."
        },
        "get": {
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "description": "Retrieves the specified device.",
          "id": "cloudidentity.devices.get",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        },
        "wipe": {
          "path": "v1/{+name}:wipe",
          "httpMethod": "POST",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "id": "cloudidentity.devices.wipe",
          "description": "Wipes all data on the specified device."
        }
      },
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET"
                },
                "list": {
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "path": "v1/{+parent}/clientStates",
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "description": "Lists the client states for the given search query."
                },
                "patch": {
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "httpMethod": "PATCH",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                }
              }
            }
          },
          "methods": {
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "description": "Retrieves the specified DeviceUser"
            },
            "block": {
              "path": "v1/{+name}:block",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Blocks device from accessing user data",
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "id": "cloudidentity.devices.deviceUsers.block"
            },
            "approve": {
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "description": "Approves device to access user data.",
              "path": "v1/{+name}:approve"
            },
            "cancelWipe": {
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "path": "v1/{+name}:cancelWipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST"
            },
            "lookup": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "path": "v1/{+parent}:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "httpMethod": "GET",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]"
            },
            "list": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "path": "v1/{+parent}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ]
            },
            "wipe": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "path": "v1/{+name}:wipe"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1/{+name}",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "httpMethod": "DELETE",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "id": "cloudidentity.devices.deviceUsers.delete"
            }
          }
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "list": {
              "flatPath": "v1/groups/{groupsId}/memberships",
              "path": "v1/{+parent}/memberships",
              "id": "cloudidentity.groups.memberships.list",
              "description": "Lists the `Membership`s within a `Group`.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "httpMethod": "GET",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]"
            },
            "create": {
              "description": "Creates a `Membership`.",
              "httpMethod": "POST",
              "path": "v1/{+parent}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1/groups/{groupsId}/memberships"
            },
            "searchTransitiveMemberships": {
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships"
            },
            "modifyMembershipRoles": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "path": "v1/{+name}:modifyMembershipRoles",
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles"
            },
            "searchTransitiveGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "httpMethod": "GET",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups."
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.get",
              "description": "Retrieves a `Membership`.",
              "path": "v1/{+name}"
            },
            "lookup": {
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1/{+parent}/memberships:lookup"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`."
            },
            "getMembershipGraph": {
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.getMembershipGraph"
            },
            "searchDirectGroups": {
              "httpMethod": "GET",
              "description": "Searches direct groups of a member.",
              "id": "cloudidentity.groups.memberships.searchDirectGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups"
            }
          }
        }
      },
      "methods": {
        "lookup": {
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "path": "v1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.lookup",
          "flatPath": "v1/groups:lookup",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Retrieves a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "id": "cloudidentity.groups.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}"
        },
        "getSecuritySettings": {
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Get Security Settings",
          "id": "cloudidentity.groups.getSecuritySettings"
        },
        "patch": {
          "id": "cloudidentity.groups.patch",
          "httpMethod": "PATCH",
          "description": "Updates a `Group`.",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}"
        },
        "updateSecuritySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "description": "Update Security Settings",
          "id": "cloudidentity.groups.updateSecuritySettings"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}"
        },
        "list": {
          "description": "Lists the `Group` resources under a customer or namespace.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups",
          "id": "cloudidentity.groups.list",
          "flatPath": "v1/groups"
        },
        "create": {
          "flatPath": "v1/groups",
          "path": "v1/groups",
          "id": "cloudidentity.groups.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a Group."
        },
        "search": {
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "flatPath": "v1/groups:search",
          "httpMethod": "GET",
          "description": "Searches for `Group` resources matching a specified query.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      }
    },
    "inboundSamlSsoProfiles": {
      "methods": {
        "delete": {
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "description": "Deletes an InboundSamlSsoProfile.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates an InboundSamlSsoProfile for a customer.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/inboundSamlSsoProfiles",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.create"
        },
        "patch": {
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "httpMethod": "PATCH",
          "description": "Updates an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Gets an InboundSamlSsoProfile.",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.get"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundSamlSsoProfiles for a customer.",
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "path": "v1/inboundSamlSsoProfiles",
          "flatPath": "v1/inboundSamlSsoProfiles"
        }
      },
      "resources": {
        "idpCredentials": {
          "methods": {
            "delete": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes an IdpCredential.",
              "path": "v1/{+name}",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "httpMethod": "DELETE"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+name}",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "httpMethod": "GET",
              "description": "Gets an IdpCredential."
            },
            "add": {
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "httpMethod": "POST",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "path": "v1/{+parent}/idpCredentials:add"
            },
            "list": {
              "path": "v1/{+parent}/idpCredentials",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile.",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list"
            }
          }
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "list": {
              "path": "v1/{+parent}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "id": "cloudidentity.customers.userinvitations.list",
              "httpMethod": "GET"
            },
            "send": {
              "path": "v1/{+name}:send",
              "httpMethod": "POST",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "id": "cloudidentity.customers.userinvitations.send",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send"
            },
            "isInvitableUser": {
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "path": "v1/{+name}:isInvitableUser",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "cloudidentity.customers.userinvitations.get",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}"
            },
            "cancel": {
              "description": "Cancels a UserInvitation that was already sent.",
              "httpMethod": "POST",
              "path": "v1/{+name}:cancel",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "id": "cloudidentity.customers.userinvitations.cancel"
            }
          }
        }
      }
    }
  },
  "revision": "20230530",
  "documentationLink": "https://cloud.google.com/identity/"
}
