{
  "revision": "20210406",
  "batchPath": "batch",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "servicePath": "",
  "basePath": "",
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "schemas": {
    "QueryInterpretationOptions": {
      "type": "object",
      "id": "QueryInterpretationOptions",
      "description": "Options to interpret user query.",
      "properties": {
        "disableNlInterpretation": {
          "type": "boolean",
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is false, Set to true to disable natural language interpretation. NL interpretation only applies to predefined datasources."
        },
        "enableVerbatimMode": {
          "type": "boolean",
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental result retrieval, and usage of synonyms including custom ones. Nl interpretation will be disabled if either one of the two flags is true."
        }
      }
    },
    "SearchItemsByViewUrlResponse": {
      "id": "SearchItemsByViewUrlResponse",
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        },
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        }
      }
    },
    "TimestampPropertyOptions": {
      "type": "object",
      "description": "Options for timestamp properties.",
      "properties": {
        "operatorOptions": {
          "$ref": "TimestampOperatorOptions",
          "description": "If set, describes how the timestamp should be used as a search operator."
        }
      },
      "id": "TimestampPropertyOptions"
    },
    "Operation": {
      "id": "Operation",
      "description": "This resource represents a long-running operation that is the result of a network API call.",
      "type": "object",
      "properties": {
        "metadata": {
          "description": "Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.",
          "type": "object",
          "additionalProperties": {
            "description": "Properties of the object. Contains field @type with type URL.",
            "type": "any"
          }
        },
        "done": {
          "type": "boolean",
          "description": "If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available."
        },
        "name": {
          "description": "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.",
          "type": "string"
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        }
      }
    },
    "SourceCrowdingConfig": {
      "id": "SourceCrowdingConfig",
      "description": "Set search results crowding limits. Crowding is a situation in which multiple results from the same source or host \"crowd out\" other results, diminishing the quality of search for users. To foster better search quality and source diversity in search results, you can set a condition to reduce repetitive results by source.",
      "properties": {
        "numResults": {
          "description": "Maximum number of results allowed from a source. No limits will be set on results if this value is less than or equal to 0.",
          "type": "integer",
          "format": "int32"
        },
        "numSuggestions": {
          "format": "int32",
          "description": "Maximum number of suggestions allowed from a source. No limits will be set on results if this value is less than or equal to 0.",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "QueryCountByStatus": {
      "id": "QueryCountByStatus",
      "properties": {
        "statusCode": {
          "type": "integer",
          "description": "This represents the http status code.",
          "format": "int32"
        },
        "count": {
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "Name": {
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by the viewer's account or the Accept-Language HTTP header.",
          "type": "string"
        }
      },
      "id": "Name",
      "type": "object",
      "description": "A person's name."
    },
    "ItemStructuredData": {
      "description": "Available structured data fields for the item.",
      "properties": {
        "object": {
          "$ref": "StructuredDataObject",
          "description": "The structured data object that should conform to a registered object definition in the schema for the data source."
        },
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        }
      },
      "id": "ItemStructuredData",
      "type": "object"
    },
    "UnmappedIdentity": {
      "id": "UnmappedIdentity",
      "properties": {
        "resolutionStatusCode": {
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used to list all unmapped identities regardless of status.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by the user.",
            "The identity source associated with the identity was either not found or deleted.",
            "IDaaS does not understand the identity source, probably because the schema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "description": "The resolution status for the external identity.",
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ]
        },
        "externalIdentity": {
          "$ref": "Principal",
          "description": "The resource name for an external user."
        }
      },
      "type": "object"
    },
    "TimestampValues": {
      "id": "TimestampValues",
      "type": "object",
      "properties": {
        "values": {
          "items": {
            "type": "string",
            "format": "google-datetime"
          },
          "type": "array"
        }
      },
      "description": "List of timestamp values."
    },
    "UpdateDataSourceRequest": {
      "id": "UpdateDataSourceRequest",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "source": {
          "$ref": "DataSource"
        }
      },
      "type": "object"
    },
    "ErrorMessage": {
      "type": "object",
      "properties": {
        "errorMessage": {
          "type": "string"
        },
        "source": {
          "$ref": "Source"
        }
      },
      "description": "Error message per source response.",
      "id": "ErrorMessage"
    },
    "ListSearchApplicationsResponse": {
      "type": "object",
      "properties": {
        "searchApplications": {
          "type": "array",
          "items": {
            "$ref": "SearchApplication"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "id": "ListSearchApplicationsResponse"
    },
    "RepositoryError": {
      "properties": {
        "errorMessage": {
          "description": "Message that describes the error. The maximum allowable length of the message is 8192 characters.",
          "type": "string"
        },
        "httpStatusCode": {
          "description": "Error codes. Matches the definition of HTTP status codes.",
          "type": "integer",
          "format": "int32"
        },
        "type": {
          "type": "string",
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to the repository server."
          ],
          "description": "Type of error."
        }
      },
      "description": "Errors when the connector is communicating to the source repository.",
      "id": "RepositoryError",
      "type": "object"
    },
    "ListDataSourceResponse": {
      "type": "object",
      "id": "ListDataSourceResponse",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        },
        "sources": {
          "items": {
            "$ref": "DataSource"
          },
          "type": "array"
        }
      }
    },
    "IntegerPropertyOptions": {
      "id": "IntegerPropertyOptions",
      "description": "Options for integer properties.",
      "properties": {
        "orderedRanking": {
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "type": "string",
          "description": "Used to specify the ordered ranking for the integer. Can only be used if isRepeatable is false.",
          "enumDescriptions": [
            "There is no ranking order for the property. Results are not adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ]
        },
        "maximumValue": {
          "format": "int64",
          "type": "string",
          "description": "The maximum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values greater than the maximum are accepted and ranked with the same weight as items indexed with the maximum value."
        },
        "operatorOptions": {
          "description": "If set, describes how the integer should be used as a search operator.",
          "$ref": "IntegerOperatorOptions"
        },
        "minimumValue": {
          "type": "string",
          "description": "The minimum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values less than the minimum are accepted and ranked with the same weight as items indexed with the minimum value.",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "PushItemRequest": {
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "item": {
          "$ref": "PushItem",
          "description": "Item to push onto the queue."
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "PushItemRequest",
      "type": "object"
    },
    "PropertyDisplayOptions": {
      "type": "object",
      "properties": {
        "displayLabel": {
          "description": "The user friendly label for the property that is used if the property is specified to be displayed in ObjectDisplayOptions. If provided, the display label is shown in front of the property values when the property is part of the object display options. For example, if the property value is '1', the value by itself may not be useful context for the user. If the display name given was 'priority', then the user sees 'priority : 1' in the search results which provides clear[...]",
          "type": "string"
        }
      },
      "id": "PropertyDisplayOptions",
      "description": "The display options for a property."
    },
    "ScoringConfig": {
      "id": "ScoringConfig",
      "type": "object",
      "properties": {
        "disableFreshness": {
          "type": "boolean",
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used as a ranking signal. Note that this setting is not available in the Admin UI."
        },
        "disablePersonalization": {
          "type": "boolean",
          "description": "Whether to personalize the results. By default, personal signals will be used to boost results."
        }
      },
      "description": "Scoring configurations for a source while processing a Search or Suggest request."
    },
    "Schema": {
      "description": "The schema definition for a data source.",
      "type": "object",
      "properties": {
        "objectDefinitions": {
          "description": "The list of top-level objects for the data source. The maximum number of elements is 10.",
          "items": {
            "$ref": "ObjectDefinition"
          },
          "type": "array"
        },
        "operationIds": {
          "type": "array",
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema. After modifying the schema, wait for operations to complete before indexing additional content.",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "Schema"
    },
    "SearchResult": {
      "type": "object",
      "description": "Results containing indexed information for a document.",
      "id": "SearchResult",
      "properties": {
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        },
        "title": {
          "description": "Title of the search result.",
          "type": "string"
        },
        "snippet": {
          "$ref": "Snippet",
          "description": "The concatenation of all snippets (summaries) available for this result."
        },
        "debugInfo": {
          "$ref": "ResultDebugInfo",
          "description": "Debugging information about this search result."
        },
        "url": {
          "description": "The URL of the search result. The URL contains a Google redirect to the actual item. This URL is signed and shouldn't be changed.",
          "type": "string"
        },
        "clusteredResults": {
          "type": "array",
          "description": "If source is clustered, provide list of clustered results. There will only be one level of clustered results. If current source is not enabled for clustering, this field will be empty.",
          "items": {
            "$ref": "SearchResult"
          }
        }
      }
    },
    "VPCSettings": {
      "properties": {
        "project": {
          "type": "string",
          "description": "The resource name of the GCP Project to be used for VPC SC policy check. VPC security settings on this project will be honored for Cloud Search APIs after project_name has been updated through CustomerService. Format: projects/{project_id}"
        }
      },
      "type": "object",
      "id": "VPCSettings"
    },
    "PropertyDefinition": {
      "description": "The definition of a property within an object.",
      "type": "object",
      "id": "PropertyDefinition",
      "properties": {
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        },
        "displayOptions": {
          "$ref": "PropertyDisplayOptions",
          "description": "Options that determine how the property is displayed in the Cloud Search results page if it is specified to be displayed in the object's display options ."
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this property. Only supported for Text properties. IsReturnable must be true to set this option. In a given datasource maximum of 5 properties can be marked as is_wildcard_searchable.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a document only has one description but can have multiple comments. Cannot be true for properties whose type is a boolean. If set to false, properties that contain more than one value cause the indexing request for that item to be rejected.",
          "type": "boolean"
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "name": {
          "type": "string",
          "description": "The name of the property. Item indexing requests sent to the Indexing API should set the property name equal to this value. For example, if name is *subject_line*, then indexing requests for document items with subject fields should set the name for that field equal to *subject_line*. Use the name as the identifier for the object property. Once registered as a property for an object, you cannot re-use this name for another property within that object. The name must star[...]"
        },
        "isSortable": {
          "description": "Indicates that the property can be used for sorting. Cannot be true for properties that are repeatable. Cannot be true for properties whose type is object or user identifier. IsReturnable must be true to set this option. Only supported for Boolean, Date, Double, Integer, and Timestamp properties.",
          "type": "boolean"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "isSuggestable": {
          "description": "Indicates that the property can be used for generating query suggestions.",
          "type": "boolean"
        },
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "isFacetable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for generating facets. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for Boolean, Enum, and Text properties."
        },
        "isReturnable": {
          "type": "boolean",
          "description": "Indicates that the property identifies data that should be returned in search results via the Query API. If set to *true*, indicates that Query API users can use matching property fields in results. However, storing fields requires more space allocation and uses more bandwidth for search queries, which impacts performance over large datasets. Set to *true* here only if the field is needed for search results. Cannot be true for properties whose type is an object."
        }
      }
    },
    "CompositeFilter": {
      "properties": {
        "logicOperator": {
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "description": "The logic operator of the sub filter.",
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "type": "string"
        },
        "subFilters": {
          "type": "array",
          "description": "Sub filters.",
          "items": {
            "$ref": "Filter"
          }
        }
      },
      "id": "CompositeFilter",
      "type": "object"
    },
    "BooleanPropertyOptions": {
      "description": "Options for boolean properties.",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "BooleanOperatorOptions",
          "description": "If set, describes how the boolean should be used as a search operator."
        }
      },
      "type": "object"
    },
    "DateValues": {
      "type": "object",
      "id": "DateValues",
      "description": "List of date values.",
      "properties": {
        "values": {
          "items": {
            "$ref": "Date"
          },
          "type": "array"
        }
      }
    },
    "QuerySuggestion": {
      "properties": {},
      "description": "This field does not contain anything as of now and is just used as an indicator that the suggest result was a phrase completion.",
      "id": "QuerySuggestion",
      "type": "object"
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "properties": {
        "searchSessionsCount": {
          "type": "string",
          "description": "The count of search sessions on the day",
          "format": "int64"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        }
      },
      "type": "object"
    },
    "HtmlValues": {
      "id": "HtmlValues",
      "description": "List of html values.",
      "type": "object",
      "properties": {
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "The maximum allowable length for html values is 2048 characters."
        }
      }
    },
    "StructuredResult": {
      "type": "object",
      "id": "StructuredResult",
      "description": "Structured results that are returned as part of search request.",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Representation of a person"
        }
      }
    },
    "RequestOptions": {
      "description": "Shared request options for all RPC methods.",
      "id": "RequestOptions",
      "type": "object",
      "properties": {
        "timeZone": {
          "type": "string",
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) project, and currently available in the file [timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml). This field is used to correctly interpret date and time queries. If this field is not specified, the default time zone (UTC) is used."
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Debug options of the request"
        },
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. For translations. Set this field using the language set in browser or for the page. In the event that the user's language preference is known, set this field to the known user language. When specified, the documents in search results are biased towards the specified language. The suggest API does not use this parameter. In[...]",
          "type": "string"
        },
        "searchApplicationId": {
          "type": "string",
          "description": "The ID generated when you create a search application using the [admin console](https://support.google.com/a/answer/9043922)."
        }
      }
    },
    "UploadItemRef": {
      "description": "Represents an upload session reference. This reference is created via upload method. Updating of item content may refer to this uploaded content via contentDataRef.",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the content reference. The maximum length is 2048 characters."
        }
      },
      "type": "object",
      "id": "UploadItemRef"
    },
    "DriveTimeSpanRestrict": {
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ]
        }
      },
      "type": "object",
      "id": "DriveTimeSpanRestrict"
    },
    "UpdateSchemaRequest": {
      "id": "UpdateSchemaRequest",
      "properties": {
        "schema": {
          "$ref": "Schema",
          "description": "The new schema for the source."
        },
        "validateOnly": {
          "type": "boolean",
          "description": "If true, the schema will be checked for validity, but will not be registered with the data source, even if valid."
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object"
    },
    "EnumValues": {
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for string values is 32 characters.",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "List of enum values.",
      "id": "EnumValues",
      "type": "object"
    },
    "TimestampOperatorOptions": {
      "description": "Used to provide a search operator for timestamp properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "id": "TimestampOperatorOptions",
      "properties": {
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property. For example, if operatorName is *closedon* and the property's name is *closeDate*, then queries like *closedon:\u003cvalue\u003e* show results only where the value of the property named *closeDate* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Str[...]"
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      }
    },
    "ResetSearchApplicationRequest": {
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "ResetSearchApplicationRequest",
      "type": "object"
    },
    "ItemAcl": {
      "id": "ItemAcl",
      "type": "object",
      "description": "Access control list information for the item. For more information see [Map ACLs](/cloud-search/docs/guides/acls).",
      "properties": {
        "inheritAclFrom": {
          "description": "Name of the item to inherit the Access Permission List (ACL) from. Note: ACL inheritance *only* provides access permissions to child items and does not define structural relationships, nor does it provide convenient ways to delete large groups of items. Deleting an ACL parent from the index only alters the access permissions of child items that reference the parent in the inheritAclFrom field. The item is still in the index, but may not visible in search results. By con[...]",
          "type": "string"
        },
        "readers": {
          "type": "array",
          "description": "List of principals who are allowed to see the item in search results. Optional if inheriting permissions from another item or if the item is not intended to be visible, such as virtual containers. The maximum number of elements is 1000.",
          "items": {
            "$ref": "Principal"
          }
        },
        "deniedReaders": {
          "type": "array",
          "description": "List of principals who are explicitly denied access to the item in search results. While principals are denied access by default, use denied readers to handle exceptions and override the list allowed readers. The maximum number of elements is 100.",
          "items": {
            "$ref": "Principal"
          }
        },
        "aclInheritanceType": {
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL. Use NOT_APPLICABLE when inheritAclFrom is empty. An item without ACL inheritance can still have ACLs supplied by its own readers and deniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines its read access.",
            "During an authorization conflict, the ACL of the parent item specified in the inheritAclFrom field determines read access.",
            "Access is granted only if this item and the parent item specified in the inheritAclFrom field both permit read access."
          ],
          "type": "string",
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a parent. This should always be set in tandem with the inheritAclFrom field. Also, when the inheritAclFrom field is set, this field should be set to a valid AclInheritanceType.",
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ]
        },
        "owners": {
          "description": "Optional. List of owners for the item. This field has no bearing on document access permissions. It does, however, offer a slight ranking boosts items where the querying user is an owner. The maximum number of elements is 5.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        }
      }
    },
    "IndexItemRequest": {
      "properties": {
        "item": {
          "$ref": "Item",
          "description": "Name of the item. Format: datasources/{source_id}/items/{item_id}"
        },
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "mode": {
          "description": "Required. The RequestMode for this request.",
          "type": "string",
          "enumDescriptions": [
            "Priority is not specified in the update request. Leaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the caller."
          ],
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ]
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        }
      },
      "id": "IndexItemRequest",
      "type": "object"
    },
    "Value": {
      "description": "Definition of a single value with generic type.",
      "properties": {
        "doubleValue": {
          "type": "number",
          "format": "double"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "stringValue": {
          "type": "string"
        },
        "timestampValue": {
          "format": "google-datetime",
          "type": "string"
        },
        "integerValue": {
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object",
      "id": "Value"
    },
    "CheckAccessResponse": {
      "type": "object",
      "properties": {
        "hasAccess": {
          "type": "boolean",
          "description": "Returns true if principal has access. Returns false otherwise."
        }
      },
      "id": "CheckAccessResponse"
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "properties": {
        "queue": {
          "type": "string",
          "description": "Name of a queue to delete items from."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ResultDisplayMetadata": {
      "type": "object",
      "properties": {
        "metalines": {
          "items": {
            "$ref": "ResultDisplayLine"
          },
          "description": "The metalines content to be displayed with the result.",
          "type": "array"
        },
        "objectTypeLabel": {
          "type": "string",
          "description": "The display label for the object."
        }
      },
      "id": "ResultDisplayMetadata"
    },
    "DebugOptions": {
      "id": "DebugOptions",
      "description": "Shared request debug options for all cloudsearch RPC methods.",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "SourceScoringConfig": {
      "description": "Set the scoring configuration. This allows modifying the ranking of results for a source.",
      "id": "SourceScoringConfig",
      "type": "object",
      "properties": {
        "sourceImportance": {
          "description": "Importance of the source.",
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      }
    },
    "SearchResponse": {
      "description": "The search API response.",
      "id": "SearchResponse",
      "properties": {
        "structuredResults": {
          "type": "array",
          "items": {
            "$ref": "StructuredResult"
          },
          "description": "Structured results for the user query. These results are not counted against the page_size."
        },
        "results": {
          "description": "Results from a search query.",
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          }
        },
        "queryInterpretation": {
          "$ref": "QueryInterpretation",
          "description": "Query interpretation result for user query. Empty if query interpretation is disabled."
        },
        "resultCountExact": {
          "description": "The exact result count for this query.",
          "type": "string",
          "format": "int64"
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "facetResults": {
          "description": "Repeated facet results.",
          "items": {
            "$ref": "FacetResult"
          },
          "type": "array"
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "resultCounts": {
          "$ref": "ResultCounts",
          "description": "Expanded result count information."
        },
        "hasMoreResults": {
          "type": "boolean",
          "description": "Whether there are more search results matching the query."
        },
        "debugInfo": {
          "description": "Debugging information about the response.",
          "$ref": "ResponseDebugInfo"
        },
        "spellResults": {
          "items": {
            "$ref": "SpellResult"
          },
          "type": "array",
          "description": "Suggested spelling for the query."
        }
      },
      "type": "object"
    },
    "DriveFollowUpRestrict": {
      "id": "DriveFollowUpRestrict",
      "type": "object",
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      }
    },
    "Interaction": {
      "description": "Represents an interaction between a user and an item.",
      "id": "Interaction",
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ],
          "type": "string"
        },
        "interactionTime": {
          "description": "The time when the user acted on the item. If multiple actions of the same type exist for a single user, only the most recent action is recorded.",
          "format": "google-datetime",
          "type": "string"
        },
        "principal": {
          "description": "The user that acted on the item.",
          "$ref": "Principal"
        }
      }
    },
    "GetCustomerIndexStatsResponse": {
      "properties": {
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "type": "array",
          "items": {
            "$ref": "CustomerIndexStats"
          }
        }
      },
      "id": "GetCustomerIndexStatsResponse",
      "type": "object"
    },
    "ObjectDefinition": {
      "properties": {
        "propertyDefinitions": {
          "items": {
            "$ref": "PropertyDefinition"
          },
          "description": "The property definitions for the object. The maximum number of elements is 1000.",
          "type": "array"
        },
        "name": {
          "description": "Name for the object, which then defines its type. Item indexing requests should set the objectType field equal to this value. For example, if *name* is *Document*, then indexing requests for items of type Document should set objectType equal to *Document*. Each object definition must be uniquely named within a schema. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The maximum length is 256 characters.",
          "type": "string"
        },
        "options": {
          "description": "The optional object-specific options.",
          "$ref": "ObjectOptions"
        }
      },
      "id": "ObjectDefinition",
      "description": "The definition for an object within a data source.",
      "type": "object"
    },
    "PushItem": {
      "type": "object",
      "properties": {
        "structuredDataHash": {
          "type": "string",
          "description": "Structured data hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "type": {
          "enumDescriptions": [
            "Default UNSPECIFIED. Specifies that the push operation should not modify ItemStatus",
            "Indicates that the repository document has been modified or updated since the previous update call. This changes status to MODIFIED state for an existing item. If this is called on a non existing item, the status is changed to NEW_ITEM.",
            "Item in the repository has not been modified since the last update call. This push operation will set status to ACCEPTED state.",
            "Connector is facing a repository error regarding this item. Change status to REPOSITORY_ERROR state. Item is unreserved and rescheduled at a future time determined by exponential backoff.",
            "Call push with REQUEUE only for items that have been reserved. This action unreserves the item and resets its available time to the wall clock time."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ],
          "description": "The type of the push operation that defines the push behavior."
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details. This information is displayed in the Admin Console. This field may only be populated when the Type is REPOSITORY_ERROR."
        },
        "metadataHash": {
          "description": "Metadata hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "queue": {
          "description": "Queue to which this item belongs to. The default queue is chosen if this field is not specified. The maximum length is 512 characters.",
          "type": "string"
        },
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "payload": {
          "description": "Provides additional document state information for the connector, such as an alternate repository ID and other metadata. The maximum length is 8192 bytes.",
          "format": "byte",
          "type": "string"
        }
      },
      "id": "PushItem",
      "description": "Represents an item to be pushed to the indexing queue."
    },
    "BooleanOperatorOptions": {
      "type": "object",
      "description": "Used to provide a search operator for boolean properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "BooleanOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the boolean property. For example, if operatorName is *closed* and the property's name is *isClosed*, then queries like *closed:\u003cvalue\u003e* show results only where the value of the property named *isClosed* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any String prop[...]",
          "type": "string"
        }
      }
    },
    "CustomerIndexStats": {
      "id": "CustomerIndexStats",
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which statistics were calculated."
        },
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array",
          "description": "Number of items aggregrated by status code."
        }
      },
      "description": "Aggregation of items by status code as of the specified date."
    },
    "GetCustomerUserStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerUserStats"
          },
          "type": "array"
        }
      },
      "id": "GetCustomerUserStatsResponse"
    },
    "Item": {
      "type": "object",
      "id": "Item",
      "description": "Represents a single object that is an item in the search index, such as a file, folder, or a database record.",
      "properties": {
        "payload": {
          "description": "Additional state connector can store for this item. The maximum length is 10000 bytes.",
          "format": "byte",
          "type": "string"
        },
        "structuredData": {
          "$ref": "ItemStructuredData",
          "description": "The structured data for the item that should conform to a registered object definition in the schema for the data source."
        },
        "acl": {
          "$ref": "ItemAcl",
          "description": "Access control list for this item."
        },
        "status": {
          "description": "Status of the item. Output only field.",
          "$ref": "ItemStatus"
        },
        "content": {
          "description": "Item content to be indexed and made text searchable.",
          "$ref": "ItemContent"
        },
        "name": {
          "description": "Name of the Item. Format: datasources/{source_id}/items/{item_id} This is a required field. The maximum length is 1536 characters.",
          "type": "string"
        },
        "queue": {
          "description": "Queue this item belongs to. The maximum length is 100 characters.",
          "type": "string"
        },
        "metadata": {
          "description": "Metadata information.",
          "$ref": "ItemMetadata"
        },
        "itemType": {
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "description": "Type for this item.",
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information. These items cannot be referred in containerName or inheritAclFrom fields.",
            "An item that gets indexed and whose purpose is to supply other items with ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose as CONTAINER_ITEM."
          ]
        },
        "version": {
          "type": "string",
          "description": "Required. The indexing system stores the version from the datasource as a byte string and compares the Item version in the index to the version of the queued Item using lexical ordering. Cloud Search Indexing won't index or delete any queued item with a version value that is less than or equal to the version of the currently indexed item. The maximum length for this field is 1024 bytes.",
          "format": "byte"
        }
      }
    },
    "QueryInterpretation": {
      "properties": {
        "interpretationType": {
          "type": "string",
          "enumDescriptions": [
            "Neither the natural language interpretation, nor a broader version of the query is used to fetch the search results.",
            "The results from original query are blended with other results. The reason for blending these other results with the results from original query is populated in the 'Reason' field below.",
            "The results from original query are replaced. The reason for replacing the results from original query is populated in the 'Reason' field below."
          ],
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ]
        },
        "interpretedQuery": {
          "description": "The interpretation of the query used in search. For example, queries with natural language intent like \"email from john\" will be interpreted as \"from:john source:mail\". This field will not be filled when the reason is NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY.",
          "type": "string"
        },
        "reason": {
          "enumDescriptions": [
            "",
            "Natural language interpretation of the query is used to fetch the search results.",
            "Query and document terms similarity is used to selectively broaden the query to retrieve additional search results since enough results were not found for the user query. Interpreted query will be empty for this case."
          ],
          "description": "The reason for interpretation of the query. This field will not be UNSPECIFIED if the interpretation type is not NONE.",
          "enum": [
            "UNSPECIFIED",
            "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
            "NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY"
          ],
          "type": "string"
        }
      },
      "type": "object",
      "id": "QueryInterpretation"
    },
    "ProcessingError": {
      "properties": {
        "code": {
          "description": "Error code indicating the nature of the error.",
          "enumDescriptions": [
            "Input only value. Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state. FieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other items with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ],
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "type": "string"
        },
        "errorMessage": {
          "type": "string",
          "description": "Description of the error."
        },
        "fieldViolations": {
          "items": {
            "$ref": "FieldViolation"
          },
          "type": "array",
          "description": "In case the item fields are invalid, this field contains the details about the validation errors."
        }
      },
      "id": "ProcessingError",
      "type": "object"
    },
    "IntegerOperatorOptions": {
      "type": "object",
      "description": "Used to provide a search operator for integer properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "IntegerOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any S[...]",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the greater-than operator. For example, if greaterThanOperatorName is *priorityabove* and the property's name is *priorityVal*, then queries like *priorityabove:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is greater than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 chara[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the less-than operator. For example, if lessThanOperatorName is *prioritybelow* and the property's name is *priorityVal*, then queries like *prioritybelow:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is less than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      }
    },
    "GetCustomerSessionStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerSessionStats"
          },
          "type": "array"
        }
      },
      "id": "GetCustomerSessionStatsResponse"
    },
    "RetrievalImportance": {
      "id": "RetrievalImportance",
      "properties": {
        "importance": {
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still be used for operator matching, faceting, and suggest if desired."
          ],
          "type": "string",
          "description": "Indicates the ranking importance given to property when it is matched during retrieval. Once set, the token importance of a property cannot be changed.",
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ]
        }
      },
      "type": "object"
    },
    "GSuitePrincipal": {
      "properties": {
        "gsuiteGroupEmail": {
          "type": "string",
          "description": "This principal references a G Suite group account"
        },
        "gsuiteDomain": {
          "type": "boolean",
          "description": "This principal represents all users of the G Suite domain of the customer."
        },
        "gsuiteUserEmail": {
          "description": "This principal references a G Suite user account",
          "type": "string"
        }
      },
      "type": "object",
      "id": "GSuitePrincipal"
    },
    "GetSearchApplicationQueryStatsResponse": {
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationQueryStats"
          },
          "type": "array"
        }
      },
      "type": "object",
      "id": "GetSearchApplicationQueryStatsResponse"
    },
    "Metaline": {
      "id": "Metaline",
      "type": "object",
      "properties": {
        "properties": {
          "type": "array",
          "description": "The list of displayed properties for the metaline. The maximum number of properties is 5.",
          "items": {
            "$ref": "DisplayedProperty"
          }
        }
      },
      "description": "A metaline is a list of properties that are displayed along with the search result to provide context."
    },
    "EnumPropertyOptions": {
      "type": "object",
      "properties": {
        "orderedRanking": {
          "type": "string",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Used to specify the ordered ranking for the enumeration that determines how the integer values provided in the possible EnumValuePairs are used to rank results. If specified, integer values must be provided for all possible EnumValuePair values given for this property. Can only be used if isRepeatable is false.",
          "enumDescriptions": [
            "There is no ranking order for the property. Results aren't adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ]
        },
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        },
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All EnumValuePairs must provide a string value. If you specify an integer value for one EnumValuePair, then all possible EnumValuePairs must provide an integer value. Both the string value and integer value must be unique over all possible values. Once set, possible values cannot be removed or modified. If you supply an ordered ranking and think you might insert additional enum values in the future, leave gaps in[...]",
          "items": {
            "$ref": "EnumValuePair"
          },
          "type": "array"
        }
      },
      "id": "EnumPropertyOptions",
      "description": "Options for enum properties, which allow you to define a restricted set of strings to match user queries, set rankings for those string values, and define an operator name to be paired with those strings so that users can narrow results to only items with a specific value. For example, for items in a request tracking system with priority information, you could define *p0* as an allowable enum value and tie this enum to the operator name *priority* so that search users could[...]"
    },
    "PollItemsRequest": {
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "statusCodes": {
          "description": "Limit the items polled to the ones with these statuses.",
          "type": "array",
          "items": {
            "enumDescriptions": [
              "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
              "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
              "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
              "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
              "API has accepted the up-to-date data of this item."
            ],
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ],
            "type": "string"
          }
        },
        "limit": {
          "format": "int32",
          "type": "integer",
          "description": "Maximum number of items to return. The maximum value is 100 and the default value is 20."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "queue": {
          "description": "Queue name to fetch items from. If unspecified, PollItems will fetch from 'default' queue. The maximum length is 100 characters.",
          "type": "string"
        }
      },
      "id": "PollItemsRequest",
      "type": "object"
    },
    "Filter": {
      "id": "Filter",
      "type": "object",
      "properties": {
        "compositeFilter": {
          "$ref": "CompositeFilter"
        },
        "valueFilter": {
          "$ref": "ValueFilter"
        }
      },
      "description": "A generic way of expressing filters in a query, which supports two approaches: **1. Setting a ValueFilter.** The name must match an operator_name defined in the schema for your data source. **2. Setting a CompositeFilter.** The filters are evaluated using the logical operator. The top-level operators can only be either an AND or a NOT. AND can appear only at the top-most level. OR can appear only under a top-level AND."
    },
    "IndexItemOptions": {
      "id": "IndexItemOptions",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow gsuite principals that do not exist or are deleted in the index request.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "QueryItem": {
      "id": "QueryItem",
      "description": "Information relevant only to a query entry.",
      "type": "object",
      "properties": {
        "isSynthetic": {
          "description": "True if the text was generated by means other than a previous user search.",
          "type": "boolean"
        }
      }
    },
    "IntegerValues": {
      "description": "List of integer values.",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "int64"
          }
        }
      },
      "id": "IntegerValues",
      "type": "object"
    },
    "ObjectValues": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      },
      "id": "ObjectValues",
      "description": "List of object values."
    },
    "ContextAttribute": {
      "id": "ContextAttribute",
      "properties": {
        "values": {
          "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string",
          "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched."
        }
      },
      "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
      "type": "object"
    },
    "DoublePropertyOptions": {
      "properties": {
        "operatorOptions": {
          "$ref": "DoubleOperatorOptions",
          "description": "If set, describes how the double should be used as a search operator."
        }
      },
      "id": "DoublePropertyOptions",
      "type": "object",
      "description": "Options for double properties."
    },
    "SourceConfig": {
      "type": "object",
      "description": "Configurations for a source while processing a Search or Suggest request.",
      "id": "SourceConfig",
      "properties": {
        "source": {
          "description": "The source for which this configuration is to be used.",
          "$ref": "Source"
        },
        "crowdingConfig": {
          "$ref": "SourceCrowdingConfig",
          "description": "The crowding configuration for the source."
        },
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        }
      }
    },
    "SearchApplication": {
      "description": "SearchApplication",
      "id": "SearchApplication",
      "properties": {
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        },
        "enableAuditLog": {
          "description": "Indicates whether audit logging is on/off for requests made for the search application in query APIs.",
          "type": "boolean"
        },
        "displayName": {
          "description": "Display name of the Search Application. The maximum length is 300 characters.",
          "type": "string"
        },
        "sourceConfig": {
          "type": "array",
          "description": "Configuration for a sources specified in data_source_restrictions.",
          "items": {
            "$ref": "SourceConfig"
          }
        },
        "defaultSortOptions": {
          "$ref": "SortOptions",
          "description": "The default options for sorting the search results"
        },
        "name": {
          "description": "Name of the Search Application. Format: searchapplications/{application_id}.",
          "type": "string"
        },
        "dataSourceRestrictions": {
          "description": "Retrictions applied to the configurations. The maximum number of elements is 10.",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "defaultFacetOptions": {
          "type": "array",
          "description": "The default fields for returning facet results. The sources specified here also have been included in data_source_restrictions above.",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "operationIds": {
          "readOnly": true,
          "description": "Output only. IDs of the Long Running Operations (LROs) currently running for this schema. Output only field.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "SpellResult": {
      "id": "SpellResult",
      "properties": {
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested spelling of the query."
        }
      },
      "type": "object"
    },
    "ListOperationsResponse": {
      "type": "object",
      "properties": {
        "operations": {
          "description": "A list of operations that matches the specified filter in the request.",
          "items": {
            "$ref": "Operation"
          },
          "type": "array"
        },
        "nextPageToken": {
          "type": "string",
          "description": "The standard List next-page token."
        }
      },
      "description": "The response message for Operations.ListOperations.",
      "id": "ListOperationsResponse"
    },
    "EmailAddress": {
      "properties": {
        "emailAddress": {
          "type": "string",
          "description": "The email address."
        }
      },
      "description": "A person's email address.",
      "type": "object",
      "id": "EmailAddress"
    },
    "Date": {
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "id": "Date",
      "properties": {
        "month": {
          "description": "Month of date. Must be from 1 to 12.",
          "type": "integer",
          "format": "int32"
        },
        "day": {
          "type": "integer",
          "format": "int32",
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month."
        },
        "year": {
          "format": "int32",
          "description": "Year of date. Must be from 1 to 9999.",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "GetSearchApplicationUserStatsResponse": {
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationUserStats"
          }
        }
      },
      "id": "GetSearchApplicationUserStatsResponse",
      "type": "object"
    },
    "ErrorInfo": {
      "id": "ErrorInfo",
      "description": "Error information about the response.",
      "properties": {
        "errorMessages": {
          "type": "array",
          "items": {
            "$ref": "ErrorMessage"
          }
        }
      },
      "type": "object"
    },
    "GetDataSourceIndexStatsResponse": {
      "properties": {
        "stats": {
          "type": "array",
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "items": {
            "$ref": "DataSourceIndexStats"
          }
        }
      },
      "type": "object",
      "id": "GetDataSourceIndexStatsResponse"
    },
    "TextOperatorOptions": {
      "id": "TextOperatorOptions",
      "description": "Used to provide a search operator for text properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the text property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any text p[...]"
        },
        "exactMatchWithOperator": {
          "type": "boolean",
          "description": "If true, the text value is tokenized as one atomic value in operator searches and facet matches. For example, if the operator name is \"genre\" and the value is \"science-fiction\" the query restrictions \"genre:science\" and \"genre:fiction\" doesn't match the item; \"genre:science-fiction\" does. Value matching is case-sensitive and does not remove special characters. If false, the text is tokenized. For example, if the value is \"science-fiction\" the queries \"genre[...]"
        }
      }
    },
    "CustomerQueryStats": {
      "properties": {
        "queryCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "QueryCountByStatus"
          }
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        }
      },
      "type": "object",
      "id": "CustomerQueryStats"
    },
    "SearchApplicationSessionStats": {
      "properties": {
        "searchSessionsCount": {
          "type": "string",
          "format": "int64",
          "description": "The count of search sessions on the day"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        }
      },
      "id": "SearchApplicationSessionStats",
      "type": "object"
    },
    "PollItemsResponse": {
      "type": "object",
      "properties": {
        "items": {
          "items": {
            "$ref": "Item"
          },
          "description": "Set of items from the queue available for connector to process. These items have the following subset of fields populated: version metadata.hash structured_data.hash content.hash payload status queue",
          "type": "array"
        }
      },
      "id": "PollItemsResponse"
    },
    "ItemStatus": {
      "properties": {
        "processingErrors": {
          "description": "Error details in case the item is in ERROR state.",
          "items": {
            "$ref": "ProcessingError"
          },
          "type": "array"
        },
        "code": {
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status code."
        },
        "repositoryErrors": {
          "description": "Repository error reported by connector.",
          "items": {
            "$ref": "RepositoryError"
          },
          "type": "array"
        }
      },
      "id": "ItemStatus",
      "description": "This contains item's status and any errors.",
      "type": "object"
    },
    "SearchApplicationQueryStats": {
      "id": "SearchApplicationQueryStats",
      "type": "object",
      "properties": {
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        },
        "date": {
          "description": "Date for which query stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        }
      }
    },
    "FilterOptions": {
      "description": "Filter options to be applied on query.",
      "id": "FilterOptions",
      "properties": {
        "objectType": {
          "description": "If object_type is set, only objects of that type are returned. This should correspond to the name of the object that was registered within the definition of schema. The maximum length is 256 characters.",
          "type": "string"
        },
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        }
      },
      "type": "object"
    },
    "DateOperatorOptions": {
      "type": "object",
      "id": "DateOperatorOptions",
      "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:\u003cvalue\u003e* show results only where the value of the *closeDate* property matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an oper[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      }
    },
    "SuggestResult": {
      "properties": {
        "querySuggestion": {
          "description": "This field will be present if the suggested query is a word/phrase completion.",
          "$ref": "QuerySuggestion"
        },
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested query that will be used for search, when the user clicks on the suggestion"
        },
        "source": {
          "$ref": "Source",
          "description": "The source of the suggestion."
        },
        "peopleSuggestion": {
          "$ref": "PeopleSuggestion",
          "description": "This is present when the suggestion indicates a person. It contains more information about the person - like their email ID, name etc."
        }
      },
      "id": "SuggestResult",
      "description": "One suggestion result.",
      "type": "object"
    },
    "Photo": {
      "id": "Photo",
      "properties": {
        "url": {
          "type": "string",
          "description": "The URL of the photo."
        }
      },
      "type": "object",
      "description": "A person's photo."
    },
    "SearchItemsByViewUrlRequest": {
      "id": "SearchItemsByViewUrlRequest",
      "type": "object",
      "properties": {
        "viewUrl": {
          "description": "Specify the full view URL to find the corresponding item. The maximum length is 2048 characters.",
          "type": "string"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "pageToken": {
          "type": "string",
          "description": "The next_page_token value returned from a previous request, if any."
        }
      }
    },
    "GetCustomerQueryStatsResponse": {
      "id": "GetCustomerQueryStatsResponse",
      "type": "object",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerQueryStats"
          },
          "type": "array"
        }
      }
    },
    "TextValues": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for text values is 2048 characters.",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "List of text values.",
      "id": "TextValues"
    },
    "SuggestResponse": {
      "description": "Response of the suggest API.",
      "id": "SuggestResponse",
      "type": "object",
      "properties": {
        "suggestResults": {
          "type": "array",
          "items": {
            "$ref": "SuggestResult"
          },
          "description": "List of suggestions."
        }
      }
    },
    "Status": {
      "properties": {
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": {
              "description": "Properties of the object. Contains field @type with type URL.",
              "type": "any"
            }
          },
          "description": "A list of messages that carry the error details. There is a common set of message types for APIs to use."
        },
        "code": {
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "format": "int32",
          "type": "integer"
        },
        "message": {
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.",
          "type": "string"
        }
      },
      "description": "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).",
      "type": "object",
      "id": "Status"
    },
    "SearchApplicationUserStats": {
      "properties": {
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "format": "int64",
          "description": "The count of unique active users in the past thirty days"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "sevenDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past seven days",
          "format": "int64"
        },
        "oneDayActiveUsersCount": {
          "format": "int64",
          "type": "string",
          "description": "The count of unique active users in the past one day"
        }
      },
      "id": "SearchApplicationUserStats",
      "type": "object"
    },
    "DataSource": {
      "properties": {
        "disableModifications": {
          "type": "boolean",
          "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data."
        },
        "operationIds": {
          "type": "array",
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
          "items": {
            "type": "string"
          }
        },
        "shortName": {
          "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *\u003cvalue\u003e* then queries like *source:\u003cvalue\u003e* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, h[...]",
          "type": "string"
        },
        "disableServing": {
          "type": "boolean",
          "description": "Disable serving any search or assist results."
        },
        "name": {
          "type": "string",
          "description": "Name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource."
        },
        "displayName": {
          "type": "string",
          "description": "Required. Display name of the datasource The maximum length is 300 characters."
        },
        "itemsVisibility": {
          "type": "array",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility."
        },
        "indexingServiceAccounts": {
          "description": "List of service accounts that have indexing access.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "id": "DataSource",
      "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search."
    },
    "GetSearchApplicationSessionStatsResponse": {
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationSessionStats"
          }
        }
      },
      "type": "object",
      "id": "GetSearchApplicationSessionStatsResponse"
    },
    "DriveMimeTypeRestrict": {
      "id": "DriveMimeTypeRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "type": "object",
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\")."
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one FacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "type": "object",
      "properties": {
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id} If empty, all data sources will be used.",
          "type": "string"
        },
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet. Defaults to 10. Maximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "objectType": {
          "description": "If object_type is set, only those objects of that type will be used to compute facets. If empty, then all objects will be used to compute facets.",
          "type": "string"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        }
      }
    },
    "Snippet": {
      "properties": {
        "snippet": {
          "description": "The snippet of the document. The snippet of the document. May contain escaped HTML character that should be unescaped prior to rendering.",
          "type": "string"
        },
        "matchRanges": {
          "description": "The matched ranges in the snippet.",
          "type": "array",
          "items": {
            "$ref": "MatchRange"
          }
        }
      },
      "description": "Snippet of the search result, which summarizes the content of the resulting page.",
      "id": "Snippet",
      "type": "object"
    },
    "Principal": {
      "properties": {
        "groupResourceName": {
          "type": "string",
          "description": "This principal is a group identified using an external identity. The name field must specify the group resource name with this format: identitysources/{source_id}/groups/{ID}"
        },
        "userResourceName": {
          "type": "string",
          "description": "This principal is a user identified using an external identity. The name field must specify the user resource name with this format: identitysources/{source_id}/users/{ID}"
        },
        "gsuitePrincipal": {
          "$ref": "GSuitePrincipal",
          "description": "This principal is a GSuite user, group or domain."
        }
      },
      "description": "Reference to a user, group, or domain.",
      "id": "Principal",
      "type": "object"
    },
    "ResultDebugInfo": {
      "id": "ResultDebugInfo",
      "type": "object",
      "description": "Debugging information about the result.",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      }
    },
    "ValueFilter": {
      "type": "object",
      "properties": {
        "value": {
          "description": "The value to be compared with.",
          "$ref": "Value"
        },
        "operatorName": {
          "description": "The `operator_name` applied to the query, such as *price_greater_than*. The filter can work against both types of filters defined in the schema for your data source: 1. `operator_name`, where the query filters results by the property that matches the value. 2. `greater_than_operator_name` or `less_than_operator_name` in your schema. The query filters the results for the property values that are greater than or less than the supplied value in the query.",
          "type": "string"
        }
      },
      "id": "ValueFilter"
    },
    "FreshnessOptions": {
      "type": "object",
      "properties": {
        "freshnessDuration": {
          "type": "string",
          "format": "google-duration",
          "description": "The duration after which an object should be considered stale. The default value is 180 days (in seconds)."
        },
        "freshnessProperty": {
          "description": "This property indicates the freshness level of the object in the index. If set, this property must be a top-level property within the property definitions and it must be a timestamp type or date type. Otherwise, the Indexing API uses updateTime as the freshness indicator. The maximum length is 256 characters. When a property is used to calculate freshness, the value defaults to 2 years from the current time.",
          "type": "string"
        }
      },
      "id": "FreshnessOptions",
      "description": "Indicates which freshness property to use when adjusting search ranking for an item. Fresher, more recent dates indicate higher quality. Use the freshness option property that best works with your data. For fileshare documents, last modified time is most relevant. For calendar event data, the time when the event occurs is a more relevant freshness indicator. In this way, calendar events that occur closer to the time of the search query are considered higher quality and rank[...]"
    },
    "ObjectPropertyOptions": {
      "description": "Options for object properties.",
      "id": "ObjectPropertyOptions",
      "properties": {
        "subobjectProperties": {
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          },
          "description": "The properties of the sub-object. These properties represent a nested object. For example, if this property represents a postal address, the subobjectProperties might be named *street*, *city*, and *state*. The maximum number of elements is 1000."
        }
      },
      "type": "object"
    },
    "FacetResult": {
      "properties": {
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "objectType": {
          "type": "string",
          "description": "Object type for which facet results are returned. Can be empty."
        },
        "sourceName": {
          "type": "string",
          "description": "Source name for which facet results are returned. Will not be empty."
        },
        "buckets": {
          "type": "array",
          "description": "FacetBuckets for values in response containing at least a single result.",
          "items": {
            "$ref": "FacetBucket"
          }
        }
      },
      "description": "Source specific facet response",
      "type": "object",
      "id": "FacetResult"
    },
    "PeopleSuggestion": {
      "description": "This field contains information about the person being suggested.",
      "properties": {
        "person": {
          "description": "Suggested person. All fields of the person object might not be populated.",
          "$ref": "Person"
        }
      },
      "id": "PeopleSuggestion",
      "type": "object"
    },
    "ListUnmappedIdentitiesResponse": {
      "properties": {
        "unmappedIdentities": {
          "type": "array",
          "items": {
            "$ref": "UnmappedIdentity"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "id": "ListUnmappedIdentitiesResponse",
      "type": "object"
    },
    "FieldViolation": {
      "type": "object",
      "id": "FieldViolation",
      "properties": {
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        },
        "description": {
          "type": "string",
          "description": "Description of the error."
        }
      }
    },
    "ResultDisplayField": {
      "description": "Display Fields for Search Results",
      "properties": {
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        },
        "label": {
          "description": "The display label for the property.",
          "type": "string"
        }
      },
      "id": "ResultDisplayField",
      "type": "object"
    },
    "Source": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Source name for content indexed by the Indexing API."
        },
        "predefinedSource": {
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used with the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used with the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "description": "Predefined content source for Google Apps."
        }
      },
      "description": "Defines sources for the suggest/search APIs.",
      "id": "Source"
    },
    "StructuredDataObject": {
      "properties": {
        "properties": {
          "type": "array",
          "description": "The properties for the object. The maximum number of elements is 1000.",
          "items": {
            "$ref": "NamedProperty"
          }
        }
      },
      "type": "object",
      "id": "StructuredDataObject",
      "description": "A structured data object consisting of named properties."
    },
    "ListQuerySourcesResponse": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "array",
          "items": {
            "$ref": "QuerySource"
          }
        },
        "nextPageToken": {
          "type": "string"
        }
      },
      "description": "List sources response.",
      "id": "ListQuerySourcesResponse"
    },
    "ItemMetadata": {
      "properties": {
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "objectType": {
          "description": "The type of the item. This should correspond to the name of an object definition in the schema registered for the data source. For example, if the schema for the data source contains an object definition with name 'document', then item indexing requests for objects of that type should set objectType to 'document'. The maximum length is 256 characters.",
          "type": "string"
        },
        "title": {
          "type": "string",
          "description": "The title of the item. If given, this will be the displayed title of the Search result. The maximum length is 2048 characters."
        },
        "interactions": {
          "items": {
            "$ref": "Interaction"
          },
          "description": "A list of interactions for the item. Interactions are used to improve Search quality, but are not exposed to end users. The maximum number of elements is 1000.",
          "type": "array"
        },
        "contextAttributes": {
          "items": {
            "$ref": "ContextAttribute"
          },
          "description": "A set of named attributes associated with the item. This can be used for influencing the ranking of the item based on the context in the request. The maximum number of elements is 10.",
          "type": "array"
        },
        "mimeType": {
          "description": "The original mime-type of ItemContent.content in the source repository. The maximum length is 256 characters.",
          "type": "string"
        },
        "sourceRepositoryUrl": {
          "type": "string",
          "description": "Link to the source repository serving the data. Search results apply this link to the title. Whitespace or special characters may cause Cloud Search result links to trigger a redirect notice; to avoid this, encode the URL. The maximum length is 2048 characters."
        },
        "searchQualityMetadata": {
          "$ref": "SearchQualityMetadata",
          "description": "Additional search quality metadata of the item"
        },
        "keywords": {
          "description": "Additional keywords or phrases that should match the item. Used internally for user generated content. The maximum number of elements is 100. The maximum length is 8192 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "containerName": {
          "type": "string",
          "description": "The name of the container for this item. Deletion of the container item leads to automatic deletion of this item. Note: ACLs are not inherited from a container item. To provide ACL inheritance for an item, use the inheritAclFrom field. The maximum length is 1536 characters."
        },
        "updateTime": {
          "format": "google-datetime",
          "description": "The time when the item was last modified in the source repository.",
          "type": "string"
        },
        "createTime": {
          "description": "The time when the item was created in the source repository.",
          "type": "string",
          "format": "google-datetime"
        },
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. The maximum length is 32 characters.",
          "type": "string"
        }
      },
      "description": "Available metadata fields for the item.",
      "id": "ItemMetadata",
      "type": "object"
    },
    "CustomerSettings": {
      "type": "object",
      "description": "Represents settings at a customer level.",
      "properties": {
        "vpcSettings": {
          "$ref": "VPCSettings",
          "description": "VPC SC settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request."
        },
        "auditLoggingSettings": {
          "description": "Audit Logging settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request.",
          "$ref": "AuditLoggingSettings"
        }
      },
      "id": "CustomerSettings"
    },
    "SourceResultCount": {
      "id": "SourceResultCount",
      "type": "object",
      "description": "Per source result count information.",
      "properties": {
        "resultCountEstimate": {
          "description": "The estimated result count for this source.",
          "type": "string",
          "format": "int64"
        },
        "resultCountExact": {
          "description": "The exact result count for this source.",
          "type": "string",
          "format": "int64"
        },
        "source": {
          "$ref": "Source",
          "description": "The source the result count information is associated with."
        },
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        }
      }
    },
    "RestrictItem": {
      "properties": {
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "searchOperator": {
          "type": "string",
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
        },
        "driveFollowUpRestrict": {
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/search/quality/itemsuggest/utils/SubtypeRerankingUtils.java)",
          "$ref": "DriveFollowUpRestrict"
        },
        "driveMimeTypeRestrict": {
          "description": "LINT.IfChange Drive Types.",
          "$ref": "DriveMimeTypeRestrict"
        },
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        }
      },
      "description": "Information relevant only to a restrict entry. NextId: 12",
      "id": "RestrictItem",
      "type": "object"
    },
    "DisplayedProperty": {
      "type": "object",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema.",
          "type": "string"
        }
      },
      "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown.",
      "id": "DisplayedProperty"
    },
    "AuditLoggingSettings": {
      "id": "AuditLoggingSettings",
      "description": "Represents the settings for Cloud audit logging",
      "properties": {
        "logDataReadActions": {
          "type": "boolean",
          "description": "Indicates whether audit logging is on/off for data access read APIs i.e. ListItems, GetItem etc."
        },
        "project": {
          "type": "string",
          "description": "The resource name of the GCP Project to store audit logs. Cloud audit logging will be enabled after project_name has been updated through CustomerService. Format: projects/{project_id}"
        },
        "logDataWriteActions": {
          "description": "Indicates whether audit logging is on/off for data access write APIs i.e. IndexItem etc.",
          "type": "boolean"
        },
        "logAdminReadActions": {
          "description": "Indicates whether audit logging is on/off for admin activity read APIs i.e. Get/List DataSources, Get/List SearchApplications etc.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "ObjectOptions": {
      "type": "object",
      "id": "ObjectOptions",
      "description": "The options for an object.",
      "properties": {
        "freshnessOptions": {
          "$ref": "FreshnessOptions",
          "description": "The freshness options for an object."
        },
        "displayOptions": {
          "$ref": "ObjectDisplayOptions",
          "description": "Options that determine how the object is displayed in the Cloud Search results page."
        }
      }
    },
    "ResultCounts": {
      "id": "ResultCounts",
      "description": "Result count information",
      "type": "object",
      "properties": {
        "sourceResultCounts": {
          "type": "array",
          "items": {
            "$ref": "SourceResultCount"
          },
          "description": "Result count information for each source with results."
        }
      }
    },
    "StartUploadItemRequest": {
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "description": "Start upload file request.",
      "type": "object",
      "id": "StartUploadItemRequest"
    },
    "SuggestRequest": {
      "properties": {
        "dataSourceRestrictions": {
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array",
          "description": "The sources to use for suggestions. If not specified, the data sources are taken from the current search application. NOTE: Suggestions are only supported for the following sources: * Third-party data sources * PredefinedSource.PERSON * PredefinedSource.GOOGLE_DRIVE"
        },
        "query": {
          "description": "Partial query for which autocomplete suggestions will be shown. For example, if the query is \"sea\", then the server might return \"season\", \"search\", \"seagull\" and so on.",
          "type": "string"
        },
        "requestOptions": {
          "description": "Request options, such as the search application and user timezone.",
          "$ref": "RequestOptions"
        }
      },
      "id": "SuggestRequest",
      "type": "object",
      "description": "Request of suggest API."
    },
    "FacetBucket": {
      "type": "object",
      "id": "FacetBucket",
      "properties": {
        "percentage": {
          "type": "integer",
          "format": "int32",
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts."
        },
        "count": {
          "type": "integer",
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Can be empty.",
          "format": "int32"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object."
    },
    "Media": {
      "properties": {
        "resourceName": {
          "description": "Name of the media resource.",
          "type": "string"
        }
      },
      "type": "object",
      "id": "Media",
      "description": "Media resource."
    },
    "ItemContent": {
      "properties": {
        "contentFormat": {
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "type": "string"
        },
        "inlineContent": {
          "format": "byte",
          "type": "string",
          "description": "Content that is supplied inlined within the update method. The maximum length is 102400 bytes (100 KiB)."
        },
        "contentDataRef": {
          "$ref": "UploadItemRef",
          "description": "Upload reference ID of a previously uploaded content via write method."
        },
        "hash": {
          "type": "string",
          "description": "Hashing info calculated and provided by the API client for content. Can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        }
      },
      "description": "Content of an item to be indexed and surfaced by Cloud Search. Only UTF-8 encoded strings are allowed as inlineContent. If the content is uploaded and not binary, it must be UTF-8 encoded.",
      "id": "ItemContent",
      "type": "object"
    },
    "EnumOperatorOptions": {
      "id": "EnumOperatorOptions",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the enum property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Stri[...]"
        }
      },
      "type": "object",
      "description": "Used to provide a search operator for enum properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched. For example, if you provide no operator for a *priority* enum property with possible values *p0* and *p1*, a query that contains the term *p0* returns items that have *p0* as the value of the *priority* property, as well as any items that contain the string *p0* in other fields. If you provide [...]"
    },
    "SearchRequest": {
      "type": "object",
      "description": "The search API request.",
      "id": "SearchRequest",
      "properties": {
        "contextAttributes": {
          "type": "array",
          "description": "Context attributes for the request which will be used to adjust ranking of search results. The maximum number of elements is 10.",
          "items": {
            "$ref": "ContextAttribute"
          }
        },
        "queryInterpretationOptions": {
          "$ref": "QueryInterpretationOptions",
          "description": "Options to interpret the user query."
        },
        "query": {
          "type": "string",
          "description": "The raw query string. See supported search operators in the [Cloud search Cheat Sheet](https://support.google.com/a/users/answer/9299929)"
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "pageSize": {
          "description": "Maximum number of search results to return in one page. Valid values are between 1 and 100, inclusive. Default value is 10. Minimum value is 50 when results beyond 2000 are requested.",
          "type": "integer",
          "format": "int32"
        },
        "facetOptions": {
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array"
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "dataSourceRestrictions": {
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array",
          "description": "The sources to use for querying. If not specified, all data sources from the current search application are used."
        },
        "start": {
          "type": "integer",
          "format": "int32",
          "description": "Starting index of the results."
        }
      }
    },
    "Person": {
      "description": "Object to represent a person.",
      "type": "object",
      "id": "Person",
      "properties": {
        "personNames": {
          "items": {
            "$ref": "Name"
          },
          "type": "array",
          "description": "The person's name"
        },
        "photos": {
          "description": "A person's read-only photo. A picture shown next to the person's name to help others recognize the person in search results.",
          "type": "array",
          "items": {
            "$ref": "Photo"
          }
        },
        "emailAddresses": {
          "type": "array",
          "description": "The person's email addresses",
          "items": {
            "$ref": "EmailAddress"
          }
        },
        "name": {
          "type": "string",
          "description": "The resource name of the person to provide information about. See People.get from Google People API."
        },
        "obfuscatedId": {
          "type": "string",
          "description": "Obfuscated ID of a person."
        }
      }
    },
    "SearchQualityMetadata": {
      "type": "object",
      "description": "Additional search quality metadata of the item.",
      "id": "SearchQualityMetadata",
      "properties": {
        "quality": {
          "description": "An indication of the quality of the item, used to influence search quality. Value should be between 0.0 (lowest quality) and 1.0 (highest quality). The default value is 0.0.",
          "type": "number",
          "format": "double"
        }
      }
    },
    "QueryOperator": {
      "type": "object",
      "id": "QueryOperator",
      "properties": {
        "enumValues": {
          "description": "Potential list of values for the opeatror field. This field is only filled when we can safely enumerate all the possible values of this operator.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name that can be used to isolate the property using the greater-than operator.",
          "type": "string"
        },
        "type": {
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string",
          "description": "Type of the operator.",
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ]
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name that can be used to isolate the property using the less-than operator.",
          "type": "string"
        },
        "isReturnable": {
          "type": "boolean",
          "description": "Will the property associated with this facet be returned as part of search results."
        },
        "operatorName": {
          "description": "The name of the operator.",
          "type": "string"
        },
        "isSuggestable": {
          "description": "Can get suggestions for this field.",
          "type": "boolean"
        },
        "isFacetable": {
          "type": "boolean",
          "description": "Can this operator be used to get facets."
        },
        "isRepeatable": {
          "description": "Indicates if multiple values can be set for this property.",
          "type": "boolean"
        },
        "isSortable": {
          "description": "Can this operator be used to sort results.",
          "type": "boolean"
        },
        "objectType": {
          "type": "string",
          "description": "Name of the object corresponding to the operator. This field is only filled for schema-specific operators, and is unset for common operators."
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the operator"
        }
      },
      "description": "The definition of a operator that can be used in a Search/Suggest request."
    },
    "ResultDisplayLine": {
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "ResultDisplayField"
          }
        }
      },
      "id": "ResultDisplayLine",
      "type": "object",
      "description": "The collection of fields that make up a displayed line"
    },
    "CustomerUserStats": {
      "id": "CustomerUserStats",
      "properties": {
        "oneDayActiveUsersCount": {
          "type": "string",
          "format": "int64",
          "description": "The count of unique active users in the past one day"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past thirty days",
          "format": "int64"
        },
        "sevenDaysActiveUsersCount": {
          "format": "int64",
          "type": "string",
          "description": "The count of unique active users in the past seven days"
        }
      },
      "type": "object"
    },
    "MatchRange": {
      "id": "MatchRange",
      "properties": {
        "start": {
          "format": "int32",
          "type": "integer",
          "description": "Starting position of the match in the snippet."
        },
        "end": {
          "format": "int32",
          "description": "End of the match in the snippet.",
          "type": "integer"
        }
      },
      "description": "Matched range of a snippet [start, end).",
      "type": "object"
    },
    "NamedProperty": {
      "description": "A typed name-value pair for structured data. The type of the value should be the same as the registered type for the `name` property in the object definition of `objectType`.",
      "properties": {
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "name": {
          "description": "The name of the property. This name should correspond to the name of the property that was registered for object definition in the schema. The maximum allowable length for this property is 256 characters.",
          "type": "string"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "textValues": {
          "$ref": "TextValues"
        }
      },
      "id": "NamedProperty",
      "type": "object"
    },
    "EnumValuePair": {
      "id": "EnumValuePair",
      "description": "The enumeration value pair defines two things: a required string value and an optional integer value. The string value defines the necessary query term required to retrieve that item, such as *p0* for a priority item. The integer value determines the ranking of that string value relative to other enumerated values for the same property. For example, you might associate *p0* with *0* and define another enum pair such as *p1* and *1*. You must use the integer value in combina[...]",
      "type": "object",
      "properties": {
        "stringValue": {
          "type": "string",
          "description": "The string value of the EnumValuePair. The maximum length is 32 characters."
        },
        "integerValue": {
          "format": "int32",
          "description": "The integer value of the EnumValuePair which must be non-negative. Optional.",
          "type": "integer"
        }
      }
    },
    "ResponseDebugInfo": {
      "description": "Debugging information about the response.",
      "id": "ResponseDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "HtmlPropertyOptions": {
      "type": "object",
      "id": "HtmlPropertyOptions",
      "description": "Options for html properties.",
      "properties": {
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval. Can only be set to DEFAULT or NONE."
        },
        "operatorOptions": {
          "description": "If set, describes how the property should be used as a search operator.",
          "$ref": "HtmlOperatorOptions"
        }
      }
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "id": "ListItemNamesForUnmappedIdentityResponse",
      "properties": {
        "itemNames": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "type": "object"
    },
    "ObjectDisplayOptions": {
      "id": "ObjectDisplayOptions",
      "type": "object",
      "description": "The display options for an object.",
      "properties": {
        "metalines": {
          "items": {
            "$ref": "Metaline"
          },
          "description": "Defines the properties that are displayed in the metalines of the search results. The property values are displayed in the order given here. If a property holds multiple values, all of the values are displayed before the next properties. For this reason, it is a good practice to specify singular properties before repeated properties in this list. All of the properties must set is_returnable to true. The maximum number of metalines is 3.",
          "type": "array"
        },
        "objectDisplayLabel": {
          "type": "string",
          "description": "The user friendly label to display in the search result to indicate the type of the item. This is OPTIONAL; if not provided, an object label isn't displayed on the context line of the search results. The maximum length is 64 characters."
        }
      }
    },
    "DatePropertyOptions": {
      "description": "Options for date properties.",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the date should be used as a search operator.",
          "$ref": "DateOperatorOptions"
        }
      },
      "id": "DatePropertyOptions",
      "type": "object"
    },
    "DataSourceIndexStats": {
      "properties": {
        "date": {
          "description": "Date for which index stats were calculated. If the date of request is not the current date then stats calculated on the next day are returned. Stats are calculated close to mid night in this case. If date of request is current date, then real time stats are returned.",
          "$ref": "Date"
        },
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "description": "Number of items aggregrated by status code.",
          "type": "array"
        }
      },
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "DataSourceIndexStats",
      "type": "object"
    },
    "DoubleOperatorOptions": {
      "id": "DoubleOperatorOptions",
      "description": "Used to provide a search operator for double properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to use the double property in sorting or as a facet. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "type": "object"
    },
    "DoubleValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "description": "List of double values.",
      "type": "object",
      "id": "DoubleValues"
    },
    "QuerySource": {
      "description": "List of sources that the user can search using the query API.",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "Name of the source"
        },
        "shortName": {
          "description": "A short name or alias for the source. This value can be used with the 'source' operator.",
          "type": "string"
        },
        "operators": {
          "items": {
            "$ref": "QueryOperator"
          },
          "type": "array",
          "description": "List of all operators applicable for this source."
        },
        "displayName": {
          "description": "Display name of the data source.",
          "type": "string"
        }
      },
      "id": "QuerySource",
      "type": "object"
    },
    "UnreserveItemsRequest": {
      "type": "object",
      "id": "UnreserveItemsRequest",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "queue": {
          "type": "string",
          "description": "Name of a queue to unreserve items from."
        }
      }
    },
    "SortOptions": {
      "id": "SortOptions",
      "type": "object",
      "properties": {
        "sortOrder": {
          "description": "Ascending is the default sort order",
          "type": "string",
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ],
          "enumDescriptions": [
            "",
            ""
          ]
        },
        "operatorName": {
          "description": "Name of the operator corresponding to the field to sort on. The corresponding property must be marked as sortable.",
          "type": "string"
        }
      }
    },
    "ListItemsResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        }
      },
      "id": "ListItemsResponse"
    },
    "ItemCountByStatus": {
      "id": "ItemCountByStatus",
      "properties": {
        "count": {
          "format": "int64",
          "type": "string",
          "description": "Number of items matching the status code."
        },
        "statusCode": {
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status of the items."
        }
      },
      "type": "object"
    },
    "HtmlOperatorOptions": {
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the html property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator return all items where *\u003cvalue\u003e* matches the value of any html pr[...]",
          "type": "string"
        }
      },
      "id": "HtmlOperatorOptions",
      "description": "Used to provide a search operator for html properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object"
    },
    "DataSourceRestriction": {
      "id": "DataSourceRestriction",
      "type": "object",
      "properties": {
        "filterOptions": {
          "items": {
            "$ref": "FilterOptions"
          },
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
          "type": "array"
        },
        "source": {
          "$ref": "Source",
          "description": "The source of restriction."
        }
      },
      "description": "Restriction on Datasource."
    },
    "Metadata": {
      "properties": {
        "mimeType": {
          "type": "string",
          "description": "Mime type of the search result."
        },
        "objectType": {
          "description": "Object type of the search result.",
          "type": "string"
        },
        "displayOptions": {
          "description": "Options that specify how to display a structured data search result.",
          "$ref": "ResultDisplayMetadata"
        },
        "owner": {
          "description": "Owner (usually creator) of the document or object of the search result.",
          "$ref": "Person"
        },
        "createTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The creation time for this document or object in the search result."
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "NamedProperty"
          },
          "description": "Indexed fields in structured data, returned as a generic named property."
        },
        "updateTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The last modified date for the object in the search result. If not set in the item, the value returned here is empty. When `updateTime` is used for calculating freshness and is not set, this value defaults to 2 years from the current time."
        },
        "source": {
          "description": "The named source for the result, such as Gmail.",
          "$ref": "Source"
        }
      },
      "id": "Metadata",
      "type": "object",
      "description": "Metadata of a matched search result."
    },
    "TextPropertyOptions": {
      "id": "TextPropertyOptions",
      "description": "Options for text properties.",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the property should be used as a search operator.",
          "$ref": "TextOperatorOptions"
        },
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval."
        }
      }
    },
    "DriveLocationRestrict": {
      "type": "object",
      "description": "Drive location search restricts (e.g. \"is:starred\").",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ]
        }
      },
      "id": "DriveLocationRestrict"
    }
  },
  "version": "v1",
  "title": "Cloud Search API",
  "ownerDomain": "google.com",
  "description": "Cloud Search provides cloud-based search capabilities over G Suite data. The Cloud Search API allows indexing of non-G Suite data into Cloud Search.",
  "id": "cloudsearch:v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "resources": {
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1/debug/{+parent}/unmappedids",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute."
                    }
                  }
                }
              },
              "methods": {
                "searchByViewUrl": {
                  "httpMethod": "POST",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl"
                },
                "checkAccess": {
                  "description": "Checks whether an item is accessible by specified principal. **Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "id": "cloudsearch.debug.datasources.items.checkAccess"
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity"
                }
              }
            },
            "unmappedids": {
              "methods": {
                "list": {
                  "path": "v1/debug/{+parent}/unmappedids",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids"
                }
              }
            }
          }
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "path": "v1/indexing/{+name}/items",
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "id": "cloudsearch.indexing.datasources.items.list"
                },
                "poll": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1/indexing/{+name}/items:poll",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]"
                },
                "delete": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "path": "v1/indexing/{+name}",
                  "httpMethod": "DELETE",
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "deleteQueueItems": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems"
                },
                "push": {
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "path": "v1/indexing/{+name}:push"
                },
                "index": {
                  "path": "v1/indexing/{+name}:index",
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.index"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}"
                },
                "upload": {
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}:upload",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "unreserve": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve"
                }
              }
            }
          },
          "methods": {
            "deleteSchema": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "httpMethod": "DELETE",
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute."
            },
            "getSchema": {
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "GET"
            },
            "updateSchema": {
              "httpMethod": "PUT",
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute."
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "datasources": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.get",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.datasources.delete",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "cloudsearch.settings.datasources.create",
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "POST",
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.settings.datasources.list",
              "flatPath": "v1/settings/datasources",
              "description": "Lists datasources. **Note:** This API requires an admin account to execute."
            },
            "update": {
              "path": "v1/settings/{+name}",
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.settings.datasources.update",
              "httpMethod": "PUT"
            }
          }
        },
        "searchapplications": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.get",
              "path": "v1/settings/{+name}",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute."
            },
            "delete": {
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.delete",
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "DELETE"
            },
            "list": {
              "flatPath": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/searchapplications",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.list"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "httpMethod": "POST",
              "id": "cloudsearch.settings.searchapplications.create",
              "description": "Creates a search application. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/searchapplications",
              "flatPath": "v1/settings/searchapplications"
            },
            "reset": {
              "path": "v1/settings/{+name}:reset",
              "httpMethod": "POST",
              "id": "cloudsearch.settings.searchapplications.reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset"
            },
            "update": {
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "PUT",
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.settings.searchapplications.update"
            }
          }
        }
      },
      "methods": {
        "getCustomer": {
          "flatPath": "v1/settings/customer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "httpMethod": "GET",
          "id": "cloudsearch.settings.getCustomer",
          "description": "Get customer settings. **Note:** This API requires an admin account to execute."
        },
        "updateCustomer": {
          "id": "cloudsearch.settings.updateCustomer",
          "httpMethod": "PATCH",
          "flatPath": "v1/settings/customer",
          "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ]
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a[...]",
          "flatPath": "v1/media/{mediaId}",
          "path": "v1/media/{+resourceName}",
          "id": "cloudsearch.media.upload",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "httpMethod": "POST",
          "supportsMediaUpload": true
        }
      }
    },
    "query": {
      "methods": {
        "suggest": {
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [G Suite domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "flatPath": "v1/query/suggest",
          "path": "v1/query/suggest",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "id": "cloudsearch.query.suggest",
          "httpMethod": "POST"
        },
        "search": {
          "httpMethod": "POST",
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from G Suite Apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [G Suite domain-wide delegation of auth[...]",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "id": "cloudsearch.query.search",
          "flatPath": "v1/query/search",
          "path": "v1/query/search"
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [G Suite domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
              "httpMethod": "GET",
              "flatPath": "v1/query/sources",
              "path": "v1/query/sources",
              "id": "cloudsearch.query.sources.list"
            }
          }
        }
      }
    },
    "stats": {
      "resources": {
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "path": "v1/stats/query/{+name}",
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}"
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "path": "v1/stats/session/{+name}",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "httpMethod": "GET",
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute."
                }
              }
            }
          }
        },
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/user/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "id": "cloudsearch.stats.user.searchapplications.get"
                }
              }
            }
          }
        },
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "id": "cloudsearch.stats.index.datasources.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "path": "v1/stats/index/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute."
                }
              }
            }
          }
        }
      },
      "methods": {
        "getSession": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getSession",
          "path": "v1/stats/session",
          "flatPath": "v1/stats/session"
        },
        "getUser": {
          "path": "v1/stats/user",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/stats/user",
          "id": "cloudsearch.stats.getUser",
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute."
        },
        "getIndex": {
          "flatPath": "v1/stats/index",
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getIndex",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "path": "v1/stats/index"
        },
        "getQuery": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "flatPath": "v1/stats/query",
          "path": "v1/stats/query",
          "id": "cloudsearch.stats.getQuery"
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "flatPath": "v1/operations/{operationsId}",
          "id": "cloudsearch.operations.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the oper[...]",
              "path": "v1/{+name}/lro",
              "httpMethod": "GET",
              "id": "cloudsearch.operations.lro.list",
              "flatPath": "v1/operations/{operationsId}/lro"
            }
          }
        }
      }
    }
  },
  "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/",
  "ownerName": "Google",
  "canonicalName": "Cloud Search",
  "version_module": true,
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "name": "cloudsearch",
  "fullyEncodeReservedExpansion": true
}
