{
  "rootUrl": "https://cloudbilling.googleapis.com/",
  "baseUrl": "https://cloudbilling.googleapis.com/",
  "id": "cloudbilling:v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-billing": {
          "description": "View and manage your Google Cloud Platform billing accounts"
        },
        "https://www.googleapis.com/auth/cloud-billing.readonly": {
          "description": "View your Google Cloud Platform billing accounts"
        }
      }
    }
  },
  "description": "Allows developers to manage billing for their Google Cloud Platform projects programmatically.",
  "discoveryVersion": "v1",
  "title": "Cloud Billing API",
  "ownerDomain": "google.com",
  "canonicalName": "Cloudbilling",
  "ownerName": "Google",
  "resources": {
    "billingAccounts": {
      "resources": {
        "projects": {
          "methods": {
            "list": {
              "flatPath": "v1/billingAccounts/{billingAccountsId}/projects",
              "path": "v1/{+name}/projects",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudbilling.billingAccounts.projects.list",
              "httpMethod": "GET",
              "description": "Lists the projects associated with a billing account. The current authenticated user must have the `billing.resourceAssociations.list` IAM permission, which is often given to billing account [viewers](https://cloud.google.com/billing/docs/how-to/billing-access)."
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "cloudbilling.billingAccounts.get",
          "description": "Gets information about a billing account. The current authenticated user must be a [viewer of the billing account](https://cloud.google.com/billing/docs/how-to/billing-access).",
          "httpMethod": "GET",
          "flatPath": "v1/billingAccounts/{billingAccountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}"
        },
        "list": {
          "flatPath": "v1/billingAccounts",
          "description": "Lists the billing accounts that the current authenticated user has permission to [view](https://cloud.google.com/billing/docs/how-to/billing-access).",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/billingAccounts",
          "httpMethod": "GET",
          "id": "cloudbilling.billingAccounts.list"
        },
        "patch": {
          "flatPath": "v1/billingAccounts/{billingAccountsId}",
          "description": "Updates a billing account's fields. Currently the only field that can be edited is `display_name`. The current authenticated user must have the `billing.accounts.update` IAM permission, which is typically given to the [administrator](https://cloud.google.com/billing/docs/how-to/billing-access) of the billing account.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudbilling.billingAccounts.patch",
          "httpMethod": "PATCH",
          "path": "v1/{+name}"
        },
        "testIamPermissions": {
          "flatPath": "v1/billingAccounts/{billingAccountsId}:testIamPermissions",
          "path": "v1/{+resource}:testIamPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Tests the access control policy for a billing account. This method takes the resource and a set of permissions as input and returns the subset of the input permissions that the caller is allowed for that resource.",
          "httpMethod": "POST",
          "id": "cloudbilling.billingAccounts.testIamPermissions"
        },
        "setIamPolicy": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/billingAccounts/{billingAccountsId}:setIamPolicy",
          "description": "Sets the access control policy for a billing account. Replaces any existing policy. The caller must have the `billing.accounts.setIamPolicy` permission on the account, which is often given to billing account [administrators](https://cloud.google.com/billing/docs/how-to/billing-access).",
          "id": "cloudbilling.billingAccounts.setIamPolicy",
          "path": "v1/{+resource}:setIamPolicy",
          "httpMethod": "POST"
        },
        "create": {
          "description": "This method creates [billing subaccounts](https://cloud.google.com/billing/docs/concepts#subaccounts). Google Cloud resellers should use the Channel Services APIs, [accounts.customers.create](https://cloud.google.com/channel/docs/reference/rest/v1/accounts.customers/create) and [accounts.customers.entitlements.create](https://cloud.google.com/channel/docs/reference/rest/v1/accounts.customers.entitlements/create). When creating a subaccount, the current authenticated use[...]",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/billingAccounts",
          "path": "v1/billingAccounts",
          "id": "cloudbilling.billingAccounts.create"
        },
        "getIamPolicy": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/billingAccounts/{billingAccountsId}:getIamPolicy",
          "description": "Gets the access control policy for a billing account. The caller must have the `billing.accounts.getIamPolicy` permission on the account, which is often given to billing account [viewers](https://cloud.google.com/billing/docs/how-to/billing-access).",
          "path": "v1/{+resource}:getIamPolicy",
          "id": "cloudbilling.billingAccounts.getIamPolicy"
        }
      }
    },
    "services": {
      "resources": {
        "skus": {
          "methods": {
            "list": {
              "path": "v1/{+parent}/skus",
              "flatPath": "v1/services/{servicesId}/skus",
              "description": "Lists all publicly available SKUs for a given cloud service.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "id": "cloudbilling.services.skus.list"
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1/services",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/services",
          "description": "Lists all public cloud services.",
          "id": "cloudbilling.services.list"
        }
      }
    },
    "projects": {
      "methods": {
        "updateBillingInfo": {
          "description": "Sets or updates the billing account associated with a project. You specify the new billing account by setting the `billing_account_name` in the `ProjectBillingInfo` resource to the resource name of a billing account. Associating a project with an open billing account enables billing on the project and allows charges for resource usage. If the project already had a billing account, this method changes the billing account used for resource usage charges. *Note:* Incurred [...]",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/projects/{projectsId}/billingInfo",
          "path": "v1/{+name}/billingInfo",
          "httpMethod": "PUT",
          "id": "cloudbilling.projects.updateBillingInfo"
        },
        "getBillingInfo": {
          "description": "Gets the billing information for a project. The current authenticated user must have the `resourcemanager.projects.get` permission for the project, which can be granted by assigning the [Project Viewer](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles) role.",
          "flatPath": "v1/projects/{projectsId}/billingInfo",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}/billingInfo",
          "httpMethod": "GET",
          "id": "cloudbilling.projects.getBillingInfo"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "documentationLink": "https://cloud.google.com/billing/",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "revision": "20230130",
  "basePath": "",
  "name": "cloudbilling",
  "batchPath": "batch",
  "mtlsRootUrl": "https://cloudbilling.mtls.googleapis.com/",
  "version": "v1"
}
