{
  "kind": "discovery#restDescription",
  "revision": "20220310",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "schemas": {
    "TextValues": {
      "id": "TextValues",
      "properties": {
        "values": {
          "description": "The maximum allowable length for text values is 2048 characters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "description": "List of text values."
    },
    "EmailAddress": {
      "description": "A person's email address.",
      "type": "object",
      "id": "EmailAddress",
      "properties": {
        "emailAddress": {
          "description": "The email address.",
          "type": "string"
        }
      }
    },
    "GoogleDocsResultInfo": {
      "type": "object",
      "description": "A message containing information about a specific result. This information is passed to the scorer and beyond; in particular, GWS relies on it to format the result in the UI. Split from GoogleDocsMetadata in case we later want to reuse the message.",
      "properties": {
        "encryptedId": {
          "type": "string",
          "description": "The encrypted (user-visible) id of this object. Knowing the id is sufficient to create a canonical URL for this document."
        },
        "attachmentSha1": {
          "type": "string",
          "description": "The SHA1 hash of the object in Drive, if any."
        },
        "cosmoNameSpace": {
          "type": "integer",
          "description": "For Cosmo objects, the Cosmo namespace the object was in. This allows downstream clients to identify whether a document was created in Writely or Kix, Presently or Punch, or whether it was uploaded from GDrive. See storage_cosmo.Id.NAME_SPACE for a list of all Cosmo name spaces.",
          "format": "int32"
        },
        "shareScope": {
          "description": "The visibility indicator in the UI will be based upon this.",
          "$ref": "ShareScope"
        },
        "mimeType": {
          "type": "string",
          "description": "The mimetype of the document."
        },
        "cosmoId": {
          "$ref": "Id",
          "description": "The storage identifier for the object in Cosmo. This field is intended to used by Stratus/Moonshine integration only. It should not be exposed externally (please refer to encrypted_id for that purpose)."
        }
      },
      "id": "GoogleDocsResultInfo"
    },
    "FilterOptions": {
      "id": "FilterOptions",
      "properties": {
        "objectType": {
          "type": "string",
          "description": "If object_type is set, only objects of that type are returned. This should correspond to the name of the object that was registered within the definition of schema. The maximum length is 256 characters."
        },
        "filter": {
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`.",
          "$ref": "Filter"
        }
      },
      "description": "Filter options to be applied on query.",
      "type": "object"
    },
    "ResultCounts": {
      "type": "object",
      "id": "ResultCounts",
      "properties": {
        "sourceResultCounts": {
          "items": {
            "$ref": "SourceResultCount"
          },
          "type": "array",
          "description": "Result count information for each source with results."
        }
      },
      "description": "Result count information"
    },
    "UserId": {
      "type": "object",
      "description": "Primary key for User resource.",
      "id": "UserId",
      "properties": {
        "type": {
          "enum": [
            "HUMAN",
            "BOT"
          ],
          "enumDescriptions": [
            "Notes on HUMAN type: 1) Leaving UserId.UserType field empty will return HUMAN as default value. This is expected because all the existing UserIds are without explicitly setting UserType, most of which are HUMAN Ids. For Bot Ids we will always set BOT in UserType field. 2) DO NOT explicitly set HUMAN as type. This is a proto2 issue, that a UserId with explicitly set default value HUMAN as type is NOT equal to an id without setting the field. aka. UserId id1 = UserId.newBuilder() .set[...]",
            ""
          ],
          "description": "Clients do not need to send UserType to Backend, but Backend will always send this field to clients per the following rule: 1. For HUMAN Ids, the field is empty but by default .getType() will return HUMAN. 2. For BOT Ids, the field is ALWAYS set to BOT.",
          "type": "string"
        },
        "id": {
          "description": "Opaque, server-assigned ID of the User.",
          "type": "string"
        },
        "originAppId": {
          "$ref": "AppId",
          "description": "Optional. Identifier of the App involved (directly or on behalf of a human creator) in creating this message. This is not set if the user posted a message directly, but is used in the case of, for example, a message being generated by a 1P integration based on a user action (creating an event, creating a task etc). This should only be used on the BE. For clients, please use the field in the FE message proto instead (google3/apps/dynamite/v1/frontend/api/message.proto?q=[...]"
        }
      }
    },
    "ObjectValues": {
      "type": "object",
      "id": "ObjectValues",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      },
      "description": "List of object values."
    },
    "SuggestResponse": {
      "id": "SuggestResponse",
      "description": "Response of the suggest API.",
      "type": "object",
      "properties": {
        "suggestResults": {
          "description": "List of suggestions.",
          "items": {
            "$ref": "SuggestResult"
          },
          "type": "array"
        }
      }
    },
    "FacetOptions": {
      "properties": {
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "objectType": {
          "type": "string",
          "description": "If object_type is set, only those objects of that type will be used to compute facets. If empty, then all objects will be used to compute facets."
        },
        "sourceName": {
          "type": "string",
          "description": "Source name to facet on. Format: datasources/{source_id} If empty, all data sources will be used."
        },
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet. Defaults to 10. Maximum value is 100.",
          "type": "integer",
          "format": "int32"
        }
      },
      "description": "Specifies operators to return facet results for. There will be one FacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "type": "object"
    },
    "PollItemsRequest": {
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "limit": {
          "type": "integer",
          "description": "Maximum number of items to return. The maximum value is 100 and the default value is 20.",
          "format": "int32"
        },
        "statusCodes": {
          "type": "array",
          "items": {
            "enumDescriptions": [
              "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
              "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
              "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
              "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
              "API has accepted the up-to-date data of this item."
            ],
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ],
            "type": "string"
          },
          "description": "Limit the items polled to the ones with these statuses."
        },
        "queue": {
          "description": "Queue name to fetch items from. If unspecified, PollItems will fetch from 'default' queue. The maximum length is 100 characters.",
          "type": "string"
        }
      },
      "id": "PollItemsRequest",
      "type": "object"
    },
    "Metaline": {
      "id": "Metaline",
      "properties": {
        "properties": {
          "items": {
            "$ref": "DisplayedProperty"
          },
          "description": "The list of displayed properties for the metaline. The maximum number of properties is 5.",
          "type": "array"
        }
      },
      "description": "A metaline is a list of properties that are displayed along with the search result to provide context.",
      "type": "object"
    },
    "Operation": {
      "description": "This resource represents a long-running operation that is the result of a network API call.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`."
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        },
        "done": {
          "description": "If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.",
          "type": "boolean"
        },
        "metadata": {
          "description": "Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.",
          "type": "object",
          "additionalProperties": {
            "type": "any",
            "description": "Properties of the object. Contains field @type with type URL."
          }
        }
      },
      "id": "Operation"
    },
    "SuggestResult": {
      "properties": {
        "source": {
          "description": "The source of the suggestion.",
          "$ref": "Source"
        },
        "peopleSuggestion": {
          "description": "This is present when the suggestion indicates a person. It contains more information about the person - like their email ID, name etc.",
          "$ref": "PeopleSuggestion"
        },
        "querySuggestion": {
          "description": "This field will be present if the suggested query is a word/phrase completion.",
          "$ref": "QuerySuggestion"
        },
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested query that will be used for search, when the user clicks on the suggestion"
        }
      },
      "description": "One suggestion result.",
      "type": "object",
      "id": "SuggestResult"
    },
    "QuerySuggestion": {
      "type": "object",
      "id": "QuerySuggestion",
      "description": "This field does not contain anything as of now and is just used as an indicator that the suggest result was a phrase completion.",
      "properties": {}
    },
    "RetrievalImportance": {
      "id": "RetrievalImportance",
      "properties": {
        "importance": {
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still be used for operator matching, faceting, and suggest if desired."
          ],
          "type": "string",
          "description": "Indicates the ranking importance given to property when it is matched during retrieval. Once set, the token importance of a property cannot be changed.",
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ]
        }
      },
      "type": "object"
    },
    "TypeInfo": {
      "description": "Next tag: 2",
      "id": "TypeInfo",
      "type": "object",
      "properties": {
        "videoInfo": {
          "description": "Contains additional video information only if document_type is VIDEO.",
          "$ref": "VideoInfo"
        }
      }
    },
    "ResultDisplayLine": {
      "description": "The collection of fields that make up a displayed line",
      "properties": {
        "fields": {
          "items": {
            "$ref": "ResultDisplayField"
          },
          "type": "array"
        }
      },
      "type": "object",
      "id": "ResultDisplayLine"
    },
    "ObjectOptions": {
      "id": "ObjectOptions",
      "properties": {
        "freshnessOptions": {
          "description": "The freshness options for an object.",
          "$ref": "FreshnessOptions"
        },
        "displayOptions": {
          "description": "Options that determine how the object is displayed in the Cloud Search results page.",
          "$ref": "ObjectDisplayOptions"
        }
      },
      "description": "The options for an object.",
      "type": "object"
    },
    "SortOptions": {
      "properties": {
        "operatorName": {
          "description": "Name of the operator corresponding to the field to sort on. The corresponding property must be marked as sortable.",
          "type": "string"
        },
        "sortOrder": {
          "enumDescriptions": [
            "",
            ""
          ],
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Ascending is the default sort order",
          "type": "string"
        }
      },
      "type": "object",
      "id": "SortOptions"
    },
    "TextOperatorOptions": {
      "id": "TextOperatorOptions",
      "type": "object",
      "description": "Used to provide a search operator for text properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "exactMatchWithOperator": {
          "description": "If true, the text value is tokenized as one atomic value in operator searches and facet matches. For example, if the operator name is \"genre\" and the value is \"science-fiction\" the query restrictions \"genre:science\" and \"genre:fiction\" doesn't match the item; \"genre:science-fiction\" does. Value matching is case-sensitive and does not remove special characters. If false, the text is tokenized. For example, if the value is \"science-fiction\" the queries \"genre[...]",
          "type": "boolean"
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the text property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any text p[...]"
        }
      }
    },
    "UploadItemRef": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the content reference. The maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "id": "UploadItemRef",
      "description": "Represents an upload session reference. This reference is created via upload method. This reference is valid for 30 days after its creation. Updating of item content may refer to this uploaded content via contentDataRef."
    },
    "ErrorInfo": {
      "type": "object",
      "id": "ErrorInfo",
      "description": "Error information about the response.",
      "properties": {
        "errorMessages": {
          "type": "array",
          "items": {
            "$ref": "ErrorMessage"
          }
        }
      }
    },
    "Interaction": {
      "type": "object",
      "id": "Interaction",
      "description": "Represents an interaction between a user and an item.",
      "properties": {
        "principal": {
          "description": "The user that acted on the item.",
          "$ref": "Principal"
        },
        "type": {
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ]
        },
        "interactionTime": {
          "format": "google-datetime",
          "description": "The time when the user acted on the item. If multiple actions of the same type exist for a single user, only the most recent action is recorded.",
          "type": "string"
        }
      }
    },
    "CustomerSearchApplicationStats": {
      "properties": {
        "count": {
          "description": "The count of search applications for the date.",
          "format": "int64",
          "type": "string"
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which search application stats were calculated."
        }
      },
      "description": "Search application stats for a customer for the given date.",
      "id": "CustomerSearchApplicationStats",
      "type": "object"
    },
    "GetCustomerQueryStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerQueryStats"
          }
        },
        "totalQueryCount": {
          "type": "string",
          "format": "int64",
          "description": "Total successful query count (status code 200) for the given date range."
        }
      },
      "id": "GetCustomerQueryStatsResponse"
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "type": "object",
      "id": "ListItemNamesForUnmappedIdentityResponse",
      "properties": {
        "itemNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      }
    },
    "GetSearchApplicationQueryStatsResponse": {
      "properties": {
        "totalQueryCount": {
          "description": "Total successful query count (status code 200) for the given date range.",
          "format": "int64",
          "type": "string"
        },
        "stats": {
          "type": "array",
          "description": "Query stats per date for a search application.",
          "items": {
            "$ref": "SearchApplicationQueryStats"
          }
        }
      },
      "type": "object",
      "description": "Response format for getting query stats for a search application between given dates.",
      "id": "GetSearchApplicationQueryStatsResponse"
    },
    "EnumValues": {
      "description": "List of enum values.",
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for string values is 32 characters.",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "id": "EnumValues"
    },
    "SpaceId": {
      "id": "SpaceId",
      "properties": {
        "spaceId": {
          "type": "string",
          "description": "Unique, immutable ID of the Space"
        }
      },
      "description": "Primary key for Space resource.",
      "type": "object"
    },
    "DoubleOperatorOptions": {
      "description": "Used to provide a search operator for double properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "DoubleOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to use the double property in sorting or as a facet. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "PropertyDisplayOptions": {
      "properties": {
        "displayLabel": {
          "type": "string",
          "description": "The user friendly label for the property that is used if the property is specified to be displayed in ObjectDisplayOptions. If provided, the display label is shown in front of the property values when the property is part of the object display options. For example, if the property value is '1', the value by itself may not be useful context for the user. If the display name given was 'priority', then the user sees 'priority : 1' in the search results which provides clear[...]"
        }
      },
      "id": "PropertyDisplayOptions",
      "description": "The display options for a property.",
      "type": "object"
    },
    "CompositeFilter": {
      "id": "CompositeFilter",
      "type": "object",
      "properties": {
        "subFilters": {
          "type": "array",
          "description": "Sub filters.",
          "items": {
            "$ref": "Filter"
          }
        },
        "logicOperator": {
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "type": "string",
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "description": "The logic operator of the sub filter."
        }
      }
    },
    "ItemContent": {
      "properties": {
        "hash": {
          "type": "string",
          "description": "Hashing info calculated and provided by the API client for content. Can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "contentFormat": {
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "type": "string"
        },
        "inlineContent": {
          "description": "Content that is supplied inlined within the update method. The maximum length is 102400 bytes (100 KiB).",
          "format": "byte",
          "type": "string"
        },
        "contentDataRef": {
          "$ref": "UploadItemRef",
          "description": "Upload reference ID of a previously uploaded content via write method."
        }
      },
      "id": "ItemContent",
      "description": "Content of an item to be indexed and surfaced by Cloud Search. Only UTF-8 encoded strings are allowed as inlineContent. If the content is uploaded and not binary, it must be UTF-8 encoded.",
      "type": "object"
    },
    "ProcessingError": {
      "properties": {
        "fieldViolations": {
          "items": {
            "$ref": "FieldViolation"
          },
          "description": "In case the item fields are invalid, this field contains the details about the validation errors.",
          "type": "array"
        },
        "errorMessage": {
          "description": "Description of the error.",
          "type": "string"
        },
        "code": {
          "type": "string",
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "description": "Error code indicating the nature of the error.",
          "enumDescriptions": [
            "Input only value. Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state. FieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other items with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ]
        }
      },
      "type": "object",
      "id": "ProcessingError"
    },
    "Schema": {
      "type": "object",
      "id": "Schema",
      "properties": {
        "operationIds": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema. After modifying the schema, wait for operations to complete before indexing additional content."
        },
        "objectDefinitions": {
          "items": {
            "$ref": "ObjectDefinition"
          },
          "type": "array",
          "description": "The list of top-level objects for the data source. The maximum number of elements is 10."
        }
      },
      "description": "The schema definition for a data source."
    },
    "Name": {
      "description": "A person's name.",
      "type": "object",
      "id": "Name",
      "properties": {
        "displayName": {
          "type": "string",
          "description": "The read-only display name formatted according to the locale specified by the viewer's account or the Accept-Language HTTP header."
        }
      }
    },
    "StructuredResult": {
      "properties": {
        "person": {
          "description": "Representation of a person",
          "$ref": "Person"
        }
      },
      "id": "StructuredResult",
      "type": "object",
      "description": "Structured results that are returned as part of search request."
    },
    "IndexItemRequest": {
      "properties": {
        "item": {
          "description": "Name of the item. Format: datasources/{source_id}/items/{item_id}",
          "$ref": "Item"
        },
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "mode": {
          "type": "string",
          "enumDescriptions": [
            "Priority is not specified in the update request. Leaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the caller."
          ],
          "description": "Required. The RequestMode for this request.",
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ]
        }
      },
      "type": "object",
      "id": "IndexItemRequest"
    },
    "ContextAttribute": {
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched."
        },
        "values": {
          "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
      "id": "ContextAttribute"
    },
    "SearchItemsByViewUrlRequest": {
      "id": "SearchItemsByViewUrlRequest",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "pageToken": {
          "description": "The next_page_token value returned from a previous request, if any.",
          "type": "string"
        },
        "viewUrl": {
          "type": "string",
          "description": "Specify the full view URL to find the corresponding item. The maximum length is 2048 characters."
        }
      },
      "type": "object"
    },
    "ValueFilter": {
      "type": "object",
      "id": "ValueFilter",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "The `operator_name` applied to the query, such as *price_greater_than*. The filter can work against both types of filters defined in the schema for your data source: 1. `operator_name`, where the query filters results by the property that matches the value. 2. `greater_than_operator_name` or `less_than_operator_name` in your schema. The query filters the results for the property values that are greater than or less than the supplied value in the query."
        },
        "value": {
          "$ref": "Value",
          "description": "The value to be compared with."
        }
      }
    },
    "FreshnessOptions": {
      "id": "FreshnessOptions",
      "type": "object",
      "properties": {
        "freshnessProperty": {
          "type": "string",
          "description": "This property indicates the freshness level of the object in the index. If set, this property must be a top-level property within the property definitions and it must be a timestamp type or date type. Otherwise, the Indexing API uses updateTime as the freshness indicator. The maximum length is 256 characters. When a property is used to calculate freshness, the value defaults to 2 years from the current time."
        },
        "freshnessDuration": {
          "format": "google-duration",
          "type": "string",
          "description": "The duration after which an object should be considered stale. The default value is 180 days (in seconds)."
        }
      },
      "description": "Indicates which freshness property to use when adjusting search ranking for an item. Fresher, more recent dates indicate higher quality. Use the freshness option property that best works with your data. For fileshare documents, last modified time is most relevant. For calendar event data, the time when the event occurs is a more relevant freshness indicator. In this way, calendar events that occur closer to the time of the search query are considered higher quality and rank[...]"
    },
    "AvatarInfo": {
      "type": "object",
      "properties": {
        "emoji": {
          "$ref": "Emoji"
        }
      },
      "id": "AvatarInfo"
    },
    "IndexItemOptions": {
      "type": "object",
      "id": "IndexItemOptions",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow gsuite principals that do not exist or are deleted in the index request.",
          "type": "boolean"
        }
      }
    },
    "UnreserveItemsRequest": {
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "type": "string",
          "description": "Name of a queue to unreserve items from."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "UnreserveItemsRequest"
    },
    "PushItemRequest": {
      "id": "PushItemRequest",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "item": {
          "description": "Item to push onto the queue.",
          "$ref": "PushItem"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object"
    },
    "FacetBucket": {
      "type": "object",
      "id": "FacetBucket",
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object.",
      "properties": {
        "count": {
          "format": "int32",
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Cloud Search does not guarantee facet counts for any query and facet counts might be present only intermittently, even for identical queries. Do not build dependencies on facet count existence; instead use facet ount percentages which are always returned.",
          "type": "integer"
        },
        "percentage": {
          "format": "int32",
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts.",
          "type": "integer"
        },
        "value": {
          "$ref": "Value"
        }
      }
    },
    "PushItem": {
      "description": "Represents an item to be pushed to the indexing queue.",
      "id": "PushItem",
      "properties": {
        "payload": {
          "description": "Provides additional document state information for the connector, such as an alternate repository ID and other metadata. The maximum length is 8192 bytes.",
          "type": "string",
          "format": "byte"
        },
        "metadataHash": {
          "type": "string",
          "description": "Metadata hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "repositoryError": {
          "description": "Populate this field to store Connector or repository error details. This information is displayed in the Admin Console. This field may only be populated when the Type is REPOSITORY_ERROR.",
          "$ref": "RepositoryError"
        },
        "queue": {
          "type": "string",
          "description": "Queue to which this item belongs to. The default queue is chosen if this field is not specified. The maximum length is 512 characters."
        },
        "structuredDataHash": {
          "description": "Structured data hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "type": {
          "enumDescriptions": [
            "Default UNSPECIFIED. Specifies that the push operation should not modify ItemStatus",
            "Indicates that the repository document has been modified or updated since the previous update call. This changes status to MODIFIED state for an existing item. If this is called on a non existing item, the status is changed to NEW_ITEM.",
            "Item in the repository has not been modified since the last update call. This push operation will set status to ACCEPTED state.",
            "Connector is facing a repository error regarding this item. Change status to REPOSITORY_ERROR state. Item is unreserved and rescheduled at a future time determined by exponential backoff.",
            "Call push with REQUEUE only for items that have been reserved. This action unreserves the item and resets its available time to the wall clock time."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ],
          "description": "The type of the push operation that defines the push behavior."
        }
      },
      "type": "object"
    },
    "Status": {
      "properties": {
        "code": {
          "format": "int32",
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "type": "integer"
        },
        "details": {
          "items": {
            "additionalProperties": {
              "type": "any",
              "description": "Properties of the object. Contains field @type with type URL."
            },
            "type": "object"
          },
          "description": "A list of messages that carry the error details. There is a common set of message types for APIs to use.",
          "type": "array"
        },
        "message": {
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).",
      "id": "Status"
    },
    "ListSearchApplicationsResponse": {
      "type": "object",
      "id": "ListSearchApplicationsResponse",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        },
        "searchApplications": {
          "items": {
            "$ref": "SearchApplication"
          },
          "type": "array"
        }
      }
    },
    "QueryInterpretationOptions": {
      "properties": {
        "disableSupplementalResults": {
          "description": "Use this flag to disable supplemental results for a query. Supplemental results setting chosen at SearchApplication level will take precedence if set to True.",
          "type": "boolean"
        },
        "disableNlInterpretation": {
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is false, Set to true to disable natural language interpretation. NL interpretation only applies to predefined datasources.",
          "type": "boolean"
        },
        "enableVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental result retrieval, and usage of synonyms including custom ones. Nl interpretation will be disabled if either one of the two flags is true.",
          "type": "boolean"
        }
      },
      "id": "QueryInterpretationOptions",
      "type": "object",
      "description": "Options to interpret user query."
    },
    "Photo": {
      "type": "object",
      "properties": {
        "url": {
          "description": "The URL of the photo.",
          "type": "string"
        }
      },
      "description": "A person's photo.",
      "id": "Photo"
    },
    "DriveMimeTypeRestrict": {
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
      "type": "object",
      "id": "DriveMimeTypeRestrict",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ]
        }
      }
    },
    "Value": {
      "type": "object",
      "properties": {
        "timestampValue": {
          "type": "string",
          "format": "google-datetime"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "integerValue": {
          "type": "string",
          "format": "int64"
        },
        "stringValue": {
          "type": "string"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "booleanValue": {
          "type": "boolean"
        }
      },
      "description": "Definition of a single value with generic type.",
      "id": "Value"
    },
    "ShareScope": {
      "id": "ShareScope",
      "type": "object",
      "properties": {
        "scope": {
          "enumDescriptions": [
            "",
            "Only the author can view the post.",
            "Viewable only by a set of people.",
            "Viewable by extended circles.",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "PRIVATE",
            "LIMITED",
            "EXTENDED",
            "DASHER_DOMAIN",
            "PUBLIC"
          ],
          "type": "string",
          "description": "The scope to which the content was shared."
        },
        "domain": {
          "type": "string",
          "description": "If scope is DOMAIN, this field contains the dasher domain, for example \"google.com\"."
        }
      }
    },
    "ResultDisplayMetadata": {
      "id": "ResultDisplayMetadata",
      "type": "object",
      "properties": {
        "objectTypeLabel": {
          "description": "The display label for the object.",
          "type": "string"
        },
        "metalines": {
          "items": {
            "$ref": "ResultDisplayLine"
          },
          "type": "array",
          "description": "The metalines content to be displayed with the result."
        }
      }
    },
    "DynamiteSpacesScoringInfo": {
      "properties": {
        "freshnessScore": {
          "format": "double",
          "type": "number"
        },
        "affinityScore": {
          "format": "double",
          "type": "number"
        },
        "spaceAgeInDays": {
          "format": "double",
          "type": "number"
        },
        "messageScore": {
          "format": "double",
          "type": "number"
        },
        "topicalityScore": {
          "type": "number",
          "format": "double"
        },
        "smallContactListAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "joinedSpacesAffinityScore": {
          "format": "double",
          "type": "number"
        },
        "smallUnjoinedSpacesAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "commonContactCountAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "finalScore": {
          "type": "number",
          "format": "double"
        },
        "contactsIntersectionCount": {
          "type": "number",
          "format": "double"
        }
      },
      "description": "This is the proto for holding space level scoring information. This data is used for logging in query-api server and for testing purposes.",
      "type": "object",
      "id": "DynamiteSpacesScoringInfo"
    },
    "Media": {
      "id": "Media",
      "properties": {
        "resourceName": {
          "type": "string",
          "description": "Name of the media resource."
        }
      },
      "type": "object",
      "description": "Media resource."
    },
    "InitializeCustomerRequest": {
      "id": "InitializeCustomerRequest",
      "type": "object",
      "description": "Request message for `InitializeCustomer` method.",
      "properties": {}
    },
    "Metadata": {
      "properties": {
        "fields": {
          "items": {
            "$ref": "NamedProperty"
          },
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "type": "array"
        },
        "thumbnailUrl": {
          "type": "string",
          "description": "The thumbnail URL of the result."
        },
        "objectType": {
          "type": "string",
          "description": "Object type of the search result."
        },
        "updateTime": {
          "description": "The last modified date for the object in the search result. If not set in the item, the value returned here is empty. When `updateTime` is used for calculating freshness and is not set, this value defaults to 2 years from the current time.",
          "format": "google-datetime",
          "type": "string"
        },
        "owner": {
          "$ref": "Person",
          "description": "Owner (usually creator) of the document or object of the search result."
        },
        "displayOptions": {
          "description": "Options that specify how to display a structured data search result.",
          "$ref": "ResultDisplayMetadata"
        },
        "mimeType": {
          "description": "Mime type of the search result.",
          "type": "string"
        },
        "source": {
          "$ref": "Source",
          "description": "The named source for the result, such as Gmail."
        },
        "createTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The creation time for this document or object in the search result."
        }
      },
      "id": "Metadata",
      "description": "Metadata of a matched search result.",
      "type": "object"
    },
    "EnumValuePair": {
      "type": "object",
      "description": "The enumeration value pair defines two things: a required string value and an optional integer value. The string value defines the necessary query term required to retrieve that item, such as *p0* for a priority item. The integer value determines the ranking of that string value relative to other enumerated values for the same property. For example, you might associate *p0* with *0* and define another enum pair such as *p1* and *1*. You must use the integer value in combina[...]",
      "properties": {
        "stringValue": {
          "description": "The string value of the EnumValuePair. The maximum length is 32 characters.",
          "type": "string"
        },
        "integerValue": {
          "type": "integer",
          "format": "int32",
          "description": "The integer value of the EnumValuePair which must be non-negative. Optional."
        }
      },
      "id": "EnumValuePair"
    },
    "DataSourceRestriction": {
      "description": "Restriction on Datasource.",
      "properties": {
        "filterOptions": {
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
          "type": "array",
          "items": {
            "$ref": "FilterOptions"
          }
        },
        "source": {
          "description": "The source of restriction.",
          "$ref": "Source"
        }
      },
      "type": "object",
      "id": "DataSourceRestriction"
    },
    "ScoringConfig": {
      "description": "Scoring configurations for a source while processing a Search or Suggest request.",
      "type": "object",
      "properties": {
        "disablePersonalization": {
          "description": "Whether to personalize the results. By default, personal signals will be used to boost results.",
          "type": "boolean"
        },
        "disableFreshness": {
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used as a ranking signal. Note that this setting is not available in the Admin UI.",
          "type": "boolean"
        }
      },
      "id": "ScoringConfig"
    },
    "PollItemsResponse": {
      "properties": {
        "items": {
          "description": "Set of items from the queue available for connector to process. These items have the following subset of fields populated: version metadata.hash structured_data.hash content.hash payload status queue",
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        }
      },
      "id": "PollItemsResponse",
      "type": "object"
    },
    "SourceResultCount": {
      "properties": {
        "resultCountEstimate": {
          "description": "The estimated result count for this source.",
          "type": "string",
          "format": "int64"
        },
        "source": {
          "description": "The source the result count information is associated with.",
          "$ref": "Source"
        },
        "resultCountExact": {
          "description": "The exact result count for this source.",
          "type": "string",
          "format": "int64"
        },
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        }
      },
      "id": "SourceResultCount",
      "description": "Per source result count information.",
      "type": "object"
    },
    "UnmappedIdentity": {
      "properties": {
        "externalIdentity": {
          "$ref": "Principal",
          "description": "The resource name for an external user."
        },
        "resolutionStatusCode": {
          "type": "string",
          "description": "The resolution status for the external identity.",
          "enumDescriptions": [
            "Input-only value. Used to list all unmapped identities regardless of status.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by the user.",
            "The identity source associated with the identity was either not found or deleted.",
            "IDaaS does not understand the identity source, probably because the schema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ]
        }
      },
      "type": "object",
      "id": "UnmappedIdentity"
    },
    "ObjectDisplayOptions": {
      "type": "object",
      "description": "The display options for an object.",
      "properties": {
        "metalines": {
          "type": "array",
          "description": "Defines the properties that are displayed in the metalines of the search results. The property values are displayed in the order given here. If a property holds multiple values, all of the values are displayed before the next properties. For this reason, it is a good practice to specify singular properties before repeated properties in this list. All of the properties must set is_returnable to true. The maximum number of metalines is 3.",
          "items": {
            "$ref": "Metaline"
          }
        },
        "objectDisplayLabel": {
          "type": "string",
          "description": "The user friendly label to display in the search result to indicate the type of the item. This is OPTIONAL; if not provided, an object label isn't displayed on the context line of the search results. The maximum length is 64 characters."
        }
      },
      "id": "ObjectDisplayOptions"
    },
    "DriveLocationRestrict": {
      "type": "object",
      "id": "DriveLocationRestrict",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string"
        }
      },
      "description": "Drive location search restricts (e.g. \"is:starred\")."
    },
    "SourceScoringConfig": {
      "description": "Set the scoring configuration. This allows modifying the ranking of results for a source.",
      "type": "object",
      "id": "SourceScoringConfig",
      "properties": {
        "sourceImportance": {
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "description": "Importance of the source."
        }
      }
    },
    "DmId": {
      "type": "object",
      "properties": {
        "dmId": {
          "type": "string",
          "description": "Unique server assigned Id, per Direct Message Space."
        }
      },
      "id": "DmId"
    },
    "QuerySource": {
      "properties": {
        "displayName": {
          "type": "string",
          "description": "Display name of the data source."
        },
        "operators": {
          "type": "array",
          "items": {
            "$ref": "QueryOperator"
          },
          "description": "List of all operators applicable for this source."
        },
        "source": {
          "$ref": "Source",
          "description": "Name of the source"
        },
        "shortName": {
          "type": "string",
          "description": "A short name or alias for the source. This value can be used with the 'source' operator."
        }
      },
      "type": "object",
      "description": "List of sources that the user can search using the query API.",
      "id": "QuerySource"
    },
    "RepositoryError": {
      "type": "object",
      "id": "RepositoryError",
      "description": "Errors when the connector is communicating to the source repository.",
      "properties": {
        "errorMessage": {
          "type": "string",
          "description": "Message that describes the error. The maximum allowable length of the message is 8192 characters."
        },
        "httpStatusCode": {
          "format": "int32",
          "type": "integer",
          "description": "Error codes. Matches the definition of HTTP status codes."
        },
        "type": {
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "description": "Type of error.",
          "type": "string",
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to the repository server."
          ]
        }
      }
    },
    "RequestOptions": {
      "properties": {
        "debugOptions": {
          "description": "Debug options of the request",
          "$ref": "DebugOptions"
        },
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. For translations. Set this field using the language set in browser or for the page. In the event that the user's language preference is known, set this field to the known user language. When specified, the documents in search results are biased towards the specified language. The suggest API does not use this parameter. In[...]",
          "type": "string"
        },
        "timeZone": {
          "type": "string",
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) project, and currently available in the file [timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml). This field is used to correctly interpret date and time queries. If this field is not specified, the default time zone (UTC) is used."
        },
        "searchApplicationId": {
          "description": "The ID generated when you create a search application using the [admin console](https://support.google.com/a/answer/9043922).",
          "type": "string"
        }
      },
      "id": "RequestOptions",
      "type": "object",
      "description": "Shared request options for all RPC methods."
    },
    "Id": {
      "type": "object",
      "properties": {
        "creatorUserId": {
          "description": "The User account in which the DirEntry was originally created. If name_space==GAIA, then it's the gaia_id of the user this id is referring to.",
          "type": "string",
          "format": "uint64"
        },
        "nameSpace": {
          "description": "The name space in which this id is unique (typically the application that created it). Values should be drawn from the above enum, but for experimentation, use values greater than 1000.",
          "format": "int32",
          "type": "integer"
        },
        "localId": {
          "type": "string",
          "description": "The local identifier for the DirEntry (local to the creator's account). local_id + app_name is guaranteed to be unique within the creator account, but not across all User accounts. The string is case sensitive. Ignore if name_space==GAIA. NB For name_space==COSMO, all local_id's should be defined in google3/java/com/google/storage/cosmo/server/api/SpecialObjectIds.java as they have a special predefined meaning. See cosmo.client.CosmoIdFactory.createObjectId(long,String)[...]"
        }
      },
      "description": "Identifies a particular object, including both Users and DirEntries. This Id is unique across the entire server instance, such as the production or qa instance.",
      "id": "Id"
    },
    "SpaceInfo": {
      "properties": {
        "avatarInfo": {
          "$ref": "AvatarInfo"
        },
        "userMembershipState": {
          "description": "searching user's membership state in this space",
          "enumDescriptions": [
            "Default state, do not use",
            "An invitation to the space has been sent",
            "User has joined the space",
            "User is not a member",
            "This state should never be stored in Spanner. It is a state for responses to the clients to indicate that membership mutations have failed and the member is in its previous state."
          ],
          "type": "string",
          "enum": [
            "MEMBER_UNKNOWN",
            "MEMBER_INVITED",
            "MEMBER_JOINED",
            "MEMBER_NOT_A_MEMBER",
            "MEMBER_FAILED"
          ]
        },
        "isExternal": {
          "description": "Whether this is a space that enables guest access",
          "type": "boolean"
        },
        "numMembers": {
          "format": "int32",
          "type": "integer"
        },
        "groupId": {
          "$ref": "GroupId"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        }
      },
      "id": "SpaceInfo",
      "description": "Defines the representation of a single matching space.",
      "type": "object"
    },
    "CustomerQueryStats": {
      "id": "CustomerQueryStats",
      "type": "object",
      "properties": {
        "queryCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "QueryCountByStatus"
          }
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        }
      }
    },
    "QueryCountByStatus": {
      "properties": {
        "statusCode": {
          "format": "int32",
          "type": "integer",
          "description": "This represents the http status code."
        },
        "count": {
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object",
      "id": "QueryCountByStatus"
    },
    "UpdateDataSourceRequest": {
      "type": "object",
      "id": "UpdateDataSourceRequest",
      "properties": {
        "source": {
          "$ref": "DataSource"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      }
    },
    "IntegerValues": {
      "id": "IntegerValues",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "description": "List of integer values."
    },
    "SearchApplicationSessionStats": {
      "type": "object",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned."
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "SearchApplicationSessionStats"
    },
    "RestrictItem": {
      "type": "object",
      "description": "Information relevant only to a restrict entry. NextId: 12",
      "id": "RestrictItem",
      "properties": {
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        },
        "driveMimeTypeRestrict": {
          "description": "LINT.IfChange Drive Types.",
          "$ref": "DriveMimeTypeRestrict"
        },
        "driveFollowUpRestrict": {
          "$ref": "DriveFollowUpRestrict",
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/search/quality/itemsuggest/utils/SubtypeRerankingUtils.java)"
        },
        "searchOperator": {
          "type": "string",
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
        },
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        }
      }
    },
    "GetCustomerIndexStatsResponse": {
      "properties": {
        "averageIndexedItemCount": {
          "format": "int64",
          "type": "string",
          "description": "Average item count for the given date range for which billing is done."
        },
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerIndexStats"
          },
          "description": "Summary of indexed item counts, one for each day in the requested range."
        }
      },
      "type": "object",
      "id": "GetCustomerIndexStatsResponse"
    },
    "DoublePropertyOptions": {
      "description": "Options for double properties.",
      "type": "object",
      "id": "DoublePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DoubleOperatorOptions",
          "description": "If set, describes how the double should be used as a search operator."
        }
      }
    },
    "QueryInterpretation": {
      "id": "QueryInterpretation",
      "type": "object",
      "properties": {
        "reason": {
          "description": "The reason for interpretation of the query. This field will not be UNSPECIFIED if the interpretation type is not NONE.",
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
            "NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY"
          ],
          "enumDescriptions": [
            "",
            "Natural language interpretation of the query is used to fetch the search results.",
            "Query and document terms similarity is used to selectively broaden the query to retrieve additional search results since enough results were not found for the user query. Interpreted query will be empty for this case."
          ]
        },
        "interpretedQuery": {
          "type": "string",
          "description": "The interpretation of the query used in search. For example, queries with natural language intent like \"email from john\" will be interpreted as \"from:john source:mail\". This field will not be filled when the reason is NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY."
        },
        "interpretationType": {
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ],
          "enumDescriptions": [
            "Neither the natural language interpretation, nor a broader version of the query is used to fetch the search results.",
            "The results from original query are blended with other results. The reason for blending these other results with the results from original query is populated in the 'Reason' field below.",
            "The results from original query are replaced. The reason for replacing the results from original query is populated in the 'Reason' field below."
          ],
          "type": "string"
        }
      }
    },
    "GetCustomerSessionStatsResponse": {
      "id": "GetCustomerSessionStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerSessionStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DateOperatorOptions": {
      "id": "DateOperatorOptions",
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "operatorName": {
          "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:\u003cvalue\u003e* show results only where the value of the *closeDate* property matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an oper[...]",
          "type": "string"
        }
      },
      "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched."
    },
    "SearchRequest": {
      "id": "SearchRequest",
      "properties": {
        "pageSize": {
          "type": "integer",
          "description": "Maximum number of search results to return in one page. Valid values are between 1 and 100, inclusive. Default value is 10. Minimum value is 50 when results beyond 2000 are requested.",
          "format": "int32"
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "query": {
          "type": "string",
          "description": "The raw query string. See supported search operators in the [Narrow your search with operators](https://support.google.com/cloudsearch/answer/6172299)"
        },
        "start": {
          "description": "Starting index of the results.",
          "type": "integer",
          "format": "int32"
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "queryInterpretationOptions": {
          "description": "Options to interpret the user query.",
          "$ref": "QueryInterpretationOptions"
        },
        "facetOptions": {
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array"
        },
        "contextAttributes": {
          "type": "array",
          "description": "Context attributes for the request which will be used to adjust ranking of search results. The maximum number of elements is 10.",
          "items": {
            "$ref": "ContextAttribute"
          }
        },
        "dataSourceRestrictions": {
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "The sources to use for querying. If not specified, all data sources from the current search application are used.",
          "type": "array"
        }
      },
      "description": "The search API request.",
      "type": "object"
    },
    "HtmlOperatorOptions": {
      "id": "HtmlOperatorOptions",
      "description": "Used to provide a search operator for html properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the html property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator return all items where *\u003cvalue\u003e* matches the value of any html pr[...]"
        }
      },
      "type": "object"
    },
    "QueryItem": {
      "properties": {
        "isSynthetic": {
          "type": "boolean",
          "description": "True if the text was generated by means other than a previous user search."
        }
      },
      "description": "Information relevant only to a query entry.",
      "type": "object",
      "id": "QueryItem"
    },
    "GoogleDocsMetadata": {
      "description": "The corpus specific metadata for office-type documents, from Google Docs and other sources. This message is passed to the scorer and beyond. Next tag: 7",
      "properties": {
        "aclInfo": {
          "description": "Contains number of users and groups which can access the document.",
          "$ref": "AclInfo"
        },
        "documentType": {
          "enumDescriptions": [
            "If the type is unknown or not represented in this enum.",
            "Writely, Word, etc.",
            "Presently, PowerPoint, etc.",
            "Trix, Excel, etc.",
            "File types for Gdrive objects are below.",
            "",
            "Fall-back for unknown Gdrive types.",
            "",
            "",
            "",
            "",
            "",
            "For Atari page and site drafts",
            "",
            "Jamboard Jams (go/jam)",
            "Drive Shortcuts (go/shortcuts)",
            ""
          ],
          "type": "string",
          "enum": [
            "UNKNOWN",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "PDF",
            "IMAGE",
            "BINARY_BLOB",
            "FUSION_TABLE",
            "FOLDER",
            "DRAWING",
            "VIDEO",
            "FORM",
            "DRAFT_SITE",
            "DRAFT_SITE_PAGE",
            "JAM",
            "SHORTCUT",
            "SCRIPT"
          ],
          "description": "The conceptual type (presentation, document, etc.) of this document."
        },
        "lastContentModifiedTimestamp": {
          "type": "string",
          "format": "int64",
          "description": "The last time this document was modified, in seconds since epoch. Only counts content modifications."
        },
        "resultInfo": {
          "description": "Additional per-result information, akin to Gmail's SingleThreadResponse. Note: GWS no longer seems to use this field, but there's still one reference to it for Scribe, so we can't remove it.",
          "$ref": "GoogleDocsResultInfo"
        },
        "typeInfo": {
          "$ref": "TypeInfo",
          "description": "Contains additional information about the document depending on its type."
        },
        "fileExtension": {
          "description": "The file extension of the document. NOTE: As of October 2018 this field is not backfilled for old documents.",
          "type": "string"
        }
      },
      "id": "GoogleDocsMetadata",
      "type": "object"
    },
    "PeopleSuggestion": {
      "description": "This field contains information about the person being suggested.",
      "id": "PeopleSuggestion",
      "type": "object",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Suggested person. All fields of the person object might not be populated."
        }
      }
    },
    "DataSource": {
      "properties": {
        "shortName": {
          "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *\u003cvalue\u003e* then queries like *source:\u003cvalue\u003e* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, h[...]",
          "type": "string"
        },
        "disableServing": {
          "description": "Disable serving any search or assist results.",
          "type": "boolean"
        },
        "itemsVisibility": {
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "type": "array",
          "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility."
        },
        "disableModifications": {
          "type": "boolean",
          "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data."
        },
        "displayName": {
          "type": "string",
          "description": "Required. Display name of the datasource The maximum length is 300 characters."
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "returnThumbnailUrls": {
          "type": "boolean",
          "description": "Can a user request to get thumbnail URI for Items indexed in this data source."
        },
        "name": {
          "type": "string",
          "description": "Name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource."
        },
        "indexingServiceAccounts": {
          "description": "List of service accounts that have indexing access.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "id": "DataSource",
      "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search."
    },
    "SourceConfig": {
      "description": "Configurations for a source while processing a Search or Suggest request.",
      "id": "SourceConfig",
      "properties": {
        "crowdingConfig": {
          "description": "The crowding configuration for the source.",
          "$ref": "SourceCrowdingConfig"
        },
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        },
        "source": {
          "$ref": "Source",
          "description": "The source for which this configuration is to be used."
        }
      },
      "type": "object"
    },
    "HtmlValues": {
      "id": "HtmlValues",
      "description": "List of html values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for html values is 2048 characters.",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "SearchQualityMetadata": {
      "properties": {
        "quality": {
          "format": "double",
          "type": "number",
          "description": "An indication of the quality of the item, used to influence search quality. Value should be between 0.0 (lowest quality) and 1.0 (highest quality). The default value is 0.0."
        }
      },
      "description": "Additional search quality metadata of the item.",
      "id": "SearchQualityMetadata",
      "type": "object"
    },
    "SearchResponse": {
      "properties": {
        "resultCounts": {
          "$ref": "ResultCounts",
          "description": "Expanded result count information."
        },
        "resultCountEstimate": {
          "description": "The estimated result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "structuredResults": {
          "items": {
            "$ref": "StructuredResult"
          },
          "description": "Structured results for the user query. These results are not counted against the page_size.",
          "type": "array"
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "results": {
          "type": "array",
          "description": "Results from a search query.",
          "items": {
            "$ref": "SearchResult"
          }
        },
        "hasMoreResults": {
          "type": "boolean",
          "description": "Whether there are more search results matching the query."
        },
        "facetResults": {
          "type": "array",
          "description": "Repeated facet results.",
          "items": {
            "$ref": "FacetResult"
          }
        },
        "debugInfo": {
          "$ref": "ResponseDebugInfo",
          "description": "Debugging information about the response."
        },
        "queryInterpretation": {
          "$ref": "QueryInterpretation",
          "description": "Query interpretation result for user query. Empty if query interpretation is disabled."
        },
        "resultCountExact": {
          "description": "The exact result count for this query.",
          "type": "string",
          "format": "int64"
        },
        "spellResults": {
          "type": "array",
          "description": "Suggested spelling for the query.",
          "items": {
            "$ref": "SpellResult"
          }
        }
      },
      "description": "The search API response.",
      "type": "object",
      "id": "SearchResponse"
    },
    "ItemAcl": {
      "type": "object",
      "description": "Access control list information for the item. For more information see [Map ACLs](/cloud-search/docs/guides/acls).",
      "id": "ItemAcl",
      "properties": {
        "aclInheritanceType": {
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL. Use NOT_APPLICABLE when inheritAclFrom is empty. An item without ACL inheritance can still have ACLs supplied by its own readers and deniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines its read access.",
            "During an authorization conflict, the ACL of the parent item specified in the inheritAclFrom field determines read access.",
            "Access is granted only if this item and the parent item specified in the inheritAclFrom field both permit read access."
          ],
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a parent. This should always be set in tandem with the inheritAclFrom field. Also, when the inheritAclFrom field is set, this field should be set to a valid AclInheritanceType.",
          "type": "string",
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ]
        },
        "owners": {
          "items": {
            "$ref": "Principal"
          },
          "description": "Optional. List of owners for the item. This field has no bearing on document access permissions. It does, however, offer a slight ranking boosts items where the querying user is an owner. The maximum number of elements is 5.",
          "type": "array"
        },
        "deniedReaders": {
          "type": "array",
          "items": {
            "$ref": "Principal"
          },
          "description": "List of principals who are explicitly denied access to the item in search results. While principals are denied access by default, use denied readers to handle exceptions and override the list allowed readers. The maximum number of elements is 100."
        },
        "readers": {
          "description": "List of principals who are allowed to see the item in search results. Optional if inheriting permissions from another item or if the item is not intended to be visible, such as virtual containers. The maximum number of elements is 1000.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        },
        "inheritAclFrom": {
          "type": "string",
          "description": "Name of the item to inherit the Access Permission List (ACL) from. Note: ACL inheritance *only* provides access permissions to child items and does not define structural relationships, nor does it provide convenient ways to delete large groups of items. Deleting an ACL parent from the index only alters the access permissions of child items that reference the parent in the inheritAclFrom field. The item is still in the index, but may not visible in search results. By con[...]"
        }
      }
    },
    "QueryOperator": {
      "description": "The definition of a operator that can be used in a Search/Suggest request.",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "The name of the operator."
        },
        "type": {
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ],
          "type": "string",
          "description": "Type of the operator.",
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ]
        },
        "isSuggestable": {
          "type": "boolean",
          "description": "Can get suggestions for this field."
        },
        "objectType": {
          "type": "string",
          "description": "Name of the object corresponding to the operator. This field is only filled for schema-specific operators, and is unset for common operators."
        },
        "displayName": {
          "description": "Display name of the operator",
          "type": "string"
        },
        "isSortable": {
          "type": "boolean",
          "description": "Can this operator be used to sort results."
        },
        "isFacetable": {
          "description": "Can this operator be used to get facets.",
          "type": "boolean"
        },
        "isReturnable": {
          "description": "Will the property associated with this facet be returned as part of search results.",
          "type": "boolean"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name that can be used to isolate the property using the greater-than operator."
        },
        "enumValues": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Potential list of values for the opeatror field. This field is only filled when we can safely enumerate all the possible values of this operator."
        },
        "isRepeatable": {
          "type": "boolean",
          "description": "Indicates if multiple values can be set for this property."
        },
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name that can be used to isolate the property using the less-than operator."
        }
      },
      "id": "QueryOperator",
      "type": "object"
    },
    "GSuitePrincipal": {
      "id": "GSuitePrincipal",
      "type": "object",
      "properties": {
        "gsuiteUserEmail": {
          "type": "string",
          "description": "This principal references a G Suite user account"
        },
        "gsuiteDomain": {
          "type": "boolean",
          "description": "This principal represents all users of the G Suite domain of the customer."
        },
        "gsuiteGroupEmail": {
          "description": "This principal references a G Suite group account",
          "type": "string"
        }
      }
    },
    "GetDataSourceIndexStatsResponse": {
      "type": "object",
      "id": "GetDataSourceIndexStatsResponse",
      "properties": {
        "averageIndexedItemCount": {
          "type": "string",
          "format": "int64",
          "description": "Average item count for the given date range for which billing is done."
        },
        "stats": {
          "items": {
            "$ref": "DataSourceIndexStats"
          },
          "type": "array",
          "description": "Summary of indexed item counts, one for each day in the requested range."
        }
      }
    },
    "DisplayedProperty": {
      "properties": {
        "propertyName": {
          "type": "string",
          "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema."
        }
      },
      "type": "object",
      "id": "DisplayedProperty",
      "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown."
    },
    "UpdateSchemaRequest": {
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "schema": {
          "$ref": "Schema",
          "description": "The new schema for the source."
        },
        "validateOnly": {
          "description": "If true, the schema will be checked for validity, but will not be registered with the data source, even if valid.",
          "type": "boolean"
        }
      },
      "id": "UpdateSchemaRequest",
      "type": "object"
    },
    "GetCustomerSearchApplicationStatsResponse": {
      "properties": {
        "averageSearchApplicationCount": {
          "format": "int64",
          "description": "Average search application count for the given date range.",
          "type": "string"
        },
        "stats": {
          "items": {
            "$ref": "CustomerSearchApplicationStats"
          },
          "type": "array",
          "description": "Search application stats by date."
        }
      },
      "type": "object",
      "id": "GetCustomerSearchApplicationStatsResponse",
      "description": "Response format for search application stats for a customer."
    },
    "SourceCrowdingConfig": {
      "description": "Set search results crowding limits. Crowding is a situation in which multiple results from the same source or host \"crowd out\" other results, diminishing the quality of search for users. To foster better search quality and source diversity in search results, you can set a condition to reduce repetitive results by source.",
      "type": "object",
      "id": "SourceCrowdingConfig",
      "properties": {
        "numResults": {
          "type": "integer",
          "description": "Maximum number of results allowed from a datasource in a result page as long as results from other sources are not exhausted. Value specified must not be negative. A default value is used if this value is equal to 0. To disable crowding, set the value greater than 100.",
          "format": "int32"
        },
        "numSuggestions": {
          "type": "integer",
          "description": "Maximum number of suggestions allowed from a source. No limits will be set on results if this value is less than or equal to 0.",
          "format": "int32"
        }
      }
    },
    "Snippet": {
      "id": "Snippet",
      "type": "object",
      "description": "Snippet of the search result, which summarizes the content of the resulting page.",
      "properties": {
        "snippet": {
          "description": "The snippet of the document. The snippet of the document. May contain escaped HTML character that should be unescaped prior to rendering.",
          "type": "string"
        },
        "matchRanges": {
          "items": {
            "$ref": "MatchRange"
          },
          "type": "array",
          "description": "The matched ranges in the snippet."
        }
      }
    },
    "IntegerPropertyOptions": {
      "properties": {
        "orderedRanking": {
          "enumDescriptions": [
            "There is no ranking order for the property. Results are not adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "description": "Used to specify the ordered ranking for the integer. Can only be used if isRepeatable is false.",
          "type": "string",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ]
        },
        "maximumValue": {
          "format": "int64",
          "type": "string",
          "description": "The maximum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values greater than the maximum are accepted and ranked with the same weight as items indexed with the maximum value."
        },
        "operatorOptions": {
          "description": "If set, describes how the integer should be used as a search operator.",
          "$ref": "IntegerOperatorOptions"
        },
        "minimumValue": {
          "type": "string",
          "format": "int64",
          "description": "The minimum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values less than the minimum are accepted and ranked with the same weight as items indexed with the minimum value."
        }
      },
      "description": "Options for integer properties.",
      "id": "IntegerPropertyOptions",
      "type": "object"
    },
    "ItemStatus": {
      "properties": {
        "repositoryErrors": {
          "items": {
            "$ref": "RepositoryError"
          },
          "description": "Repository error reported by connector.",
          "type": "array"
        },
        "processingErrors": {
          "type": "array",
          "description": "Error details in case the item is in ERROR state.",
          "items": {
            "$ref": "ProcessingError"
          }
        },
        "code": {
          "description": "Status code.",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "type": "string",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ]
        }
      },
      "id": "ItemStatus",
      "description": "This contains item's status and any errors.",
      "type": "object"
    },
    "ResetSearchApplicationRequest": {
      "id": "ResetSearchApplicationRequest",
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      }
    },
    "DoubleValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "id": "DoubleValues",
      "type": "object",
      "description": "List of double values."
    },
    "PropertyDefinition": {
      "type": "object",
      "id": "PropertyDefinition",
      "description": "The definition of a property within an object.",
      "properties": {
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "isSuggestable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for generating query suggestions."
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this property. Only supported for Text properties. IsReturnable must be true to set this option. In a given datasource maximum of 5 properties can be marked as is_wildcard_searchable.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a document only has one description but can have multiple comments. Cannot be true for properties whose type is a boolean. If set to false, properties that contain more than one value cause the indexing request for that item to be rejected.",
          "type": "boolean"
        },
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "displayOptions": {
          "$ref": "PropertyDisplayOptions",
          "description": "Options that determine how the property is displayed in the Cloud Search results page if it is specified to be displayed in the object's display options ."
        },
        "isFacetable": {
          "description": "Indicates that the property can be used for generating facets. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for Boolean, Enum, and Text properties.",
          "type": "boolean"
        },
        "name": {
          "description": "The name of the property. Item indexing requests sent to the Indexing API should set the property name equal to this value. For example, if name is *subject_line*, then indexing requests for document items with subject fields should set the name for that field equal to *subject_line*. Use the name as the identifier for the object property. Once registered as a property for an object, you cannot re-use this name for another property within that object. The name must star[...]",
          "type": "string"
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "isReturnable": {
          "type": "boolean",
          "description": "Indicates that the property identifies data that should be returned in search results via the Query API. If set to *true*, indicates that Query API users can use matching property fields in results. However, storing fields requires more space allocation and uses more bandwidth for search queries, which impacts performance over large datasets. Set to *true* here only if the field is needed for search results. Cannot be true for properties whose type is an object."
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "isSortable": {
          "description": "Indicates that the property can be used for sorting. Cannot be true for properties that are repeatable. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for Boolean, Date, Double, Integer, and Timestamp properties.",
          "type": "boolean"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        }
      }
    },
    "FacetResult": {
      "id": "FacetResult",
      "properties": {
        "sourceName": {
          "description": "Source name for which facet results are returned. Will not be empty.",
          "type": "string"
        },
        "objectType": {
          "description": "Object type for which facet results are returned. Can be empty.",
          "type": "string"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "buckets": {
          "description": "FacetBuckets for values in response containing at least a single result.",
          "type": "array",
          "items": {
            "$ref": "FacetBucket"
          }
        }
      },
      "type": "object",
      "description": "Source specific facet response"
    },
    "CustomerId": {
      "type": "object",
      "id": "CustomerId",
      "properties": {
        "customerId": {
          "type": "string"
        }
      },
      "description": "Represents a GSuite customer ID. Obfuscated with CustomerIdObfuscator."
    },
    "Person": {
      "properties": {
        "personNames": {
          "description": "The person's name",
          "type": "array",
          "items": {
            "$ref": "Name"
          }
        },
        "emailAddresses": {
          "description": "The person's email addresses",
          "type": "array",
          "items": {
            "$ref": "EmailAddress"
          }
        },
        "name": {
          "type": "string",
          "description": "The resource name of the person to provide information about. See People.get from Google People API."
        },
        "photos": {
          "description": "A person's read-only photo. A picture shown next to the person's name to help others recognize the person in search results.",
          "items": {
            "$ref": "Photo"
          },
          "type": "array"
        },
        "obfuscatedId": {
          "description": "Obfuscated ID of a person.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "Object to represent a person.",
      "id": "Person"
    },
    "StructuredDataObject": {
      "properties": {
        "properties": {
          "type": "array",
          "description": "The properties for the object. The maximum number of elements is 1000.",
          "items": {
            "$ref": "NamedProperty"
          }
        }
      },
      "description": "A structured data object consisting of named properties.",
      "type": "object",
      "id": "StructuredDataObject"
    },
    "Source": {
      "description": "Defines sources for the suggest/search APIs.",
      "properties": {
        "name": {
          "type": "string",
          "description": "Source name for content indexed by the Indexing API."
        },
        "predefinedSource": {
          "type": "string",
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used with the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used with the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "description": "Predefined content source for Google Apps."
        }
      },
      "type": "object",
      "id": "Source"
    },
    "DeleteQueueItemsRequest": {
      "type": "object",
      "properties": {
        "queue": {
          "description": "Name of a queue to delete items from.",
          "type": "string"
        },
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "DeleteQueueItemsRequest"
    },
    "AppId": {
      "id": "AppId",
      "type": "object",
      "description": "Identifier of an App.",
      "properties": {
        "appType": {
          "enum": [
            "APP_TYPE_UNSPECIFIED",
            "APP",
            "GSUITE_APP",
            "INCOMING_WEBHOOK"
          ],
          "enumDescriptions": [
            "",
            "3P APP eg. external Bots(Asana Bot), 1P Bots(Drive Bot).",
            "1P APP eg. Tasks, Meet, Docs, Calendar..",
            "Asynchronous messages via an incoming webhook."
          ],
          "description": "Enum indicating the type of App this is.",
          "type": "string"
        },
        "gsuiteAppType": {
          "description": "Enum indicating which 1P App this is when app_type is GSUITE_APP. Determined & set by the 1P API as a convenience for all users of this identifier(Eg. clients, chime, backend etc.) to map to 1P properties.",
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Powered by Bullseye",
            "",
            "",
            "",
            "TODO (b/220205747): replace the above FILE_SUGGESTION_APP in the future."
          ],
          "enum": [
            "GSUITE_APP_TYPE_UNSPECIFIED",
            "TASKS_APP",
            "CALENDAR_APP",
            "DOCS_APP",
            "SHEETS_APP",
            "SLIDES_APP",
            "MEET_APP",
            "FILE_SUGGESTION_APP",
            "CONTACTS_APP",
            "ACTIVITY_FEED_APP",
            "DRIVE_APP",
            "ASSISTIVE_SUGGESTION_APP"
          ]
        },
        "id": {
          "description": "Numeric identifier of the App. Set to Project number for 1/3P Apps. For Webhook, this is WebhookId. Determined & set by the 1P API from App credentials on the side channel.",
          "type": "string",
          "format": "int64"
        }
      }
    },
    "CustomEmoji": {
      "properties": {
        "updateTimeMicros": {
          "format": "int64",
          "type": "string"
        },
        "shortcode": {
          "description": "User-provided, human-readable ID for the custom emoji. Users are expected to observe this field in the UI instead of the UUID. This shortcode should be unique within an organization, but has no global uniqueness guarantees, unlike the UUID. This field should *never* be persisted to Spanner.",
          "type": "string"
        },
        "creatorUserId": {
          "description": "This field should *never* be persisted to Spanner.",
          "$ref": "UserId"
        },
        "blobId": {
          "description": "ID for the underlying image data in Blobstore. This field should *only* be present in Spanner or within the server, but should not be exposed in public APIs.",
          "type": "string"
        },
        "createTimeMicros": {
          "type": "string",
          "format": "int64",
          "description": "Time when the Emoji was created, in microseconds. This field may be present in Spanner, within the server, or in public APIs."
        },
        "uuid": {
          "type": "string",
          "description": "Unique key for a custom emoji resource. Required. This field is *always* populated."
        },
        "state": {
          "enum": [
            "EMOJI_STATE_UNSPECIFIED",
            "EMOJI_ENABLED",
            "EMOJI_SYSTEM_DISABLED",
            "EMOJI_HIDDEN",
            "EMOJI_DELETED"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "Emoji is visible and available to be used, subject to access control requirements.",
            "Emoji can no longer be used (e.g. due to a shortcode conflict), but is not removed from existing embeddings.",
            "Emoji is hidden from pickers, so new usages are not allowed, but is not removed from existing embeddings.",
            "Emoji is removed everywhere and is not available to end-users."
          ],
          "description": "Snapshot of the current state of the emoji, which may differ from the source-of-truth in the CustomEmojis table. This field should *never* be persisted to Spanner."
        },
        "ownerCustomerId": {
          "$ref": "CustomerId",
          "description": "This field should *never* be persisted to Spanner."
        },
        "readToken": {
          "type": "string",
          "description": "Opaque token that clients use to construct the URL for accessing the custom emoji’s image data. This field is intended for API consumption, and should *never* be persisted to Spanner."
        }
      },
      "id": "CustomEmoji",
      "description": "Proto representation of a custom emoji. May be used in both APIs and in Spanner, but certain fields should be restricted to one or the other. See the per-field documentation for details. NEXT_TAG: 11",
      "type": "object"
    },
    "ItemStructuredData": {
      "id": "ItemStructuredData",
      "description": "Available structured data fields for the item.",
      "type": "object",
      "properties": {
        "object": {
          "$ref": "StructuredDataObject",
          "description": "The structured data object that should conform to a registered object definition in the schema for the data source."
        },
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        }
      }
    },
    "VideoInfo": {
      "description": "Next tag: 2",
      "type": "object",
      "id": "VideoInfo",
      "properties": {
        "duration": {
          "description": "Duration of the video in milliseconds. This field can be absent for recently uploaded video or inaccurate sometimes.",
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "Emoji": {
      "type": "object",
      "id": "Emoji",
      "properties": {
        "unicode": {
          "type": "string",
          "description": "A basic emoji represented by a unicode string."
        },
        "customEmoji": {
          "description": "A custom emoji.",
          "$ref": "CustomEmoji"
        }
      }
    },
    "VPCSettings": {
      "id": "VPCSettings",
      "type": "object",
      "properties": {
        "project": {
          "description": "The resource name of the GCP Project to be used for VPC SC policy check. VPC security settings on this project will be honored for Cloud Search APIs after project_name has been updated through CustomerService. Format: projects/{project_id}",
          "type": "string"
        }
      }
    },
    "ListOperationsResponse": {
      "type": "object",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "The standard List next-page token."
        },
        "operations": {
          "description": "A list of operations that matches the specified filter in the request.",
          "type": "array",
          "items": {
            "$ref": "Operation"
          }
        }
      },
      "id": "ListOperationsResponse",
      "description": "The response message for Operations.ListOperations."
    },
    "ItemMetadata": {
      "properties": {
        "contextAttributes": {
          "description": "A set of named attributes associated with the item. This can be used for influencing the ranking of the item based on the context in the request. The maximum number of elements is 10.",
          "items": {
            "$ref": "ContextAttribute"
          },
          "type": "array"
        },
        "title": {
          "description": "The title of the item. If given, this will be the displayed title of the Search result. The maximum length is 2048 characters.",
          "type": "string"
        },
        "containerName": {
          "type": "string",
          "description": "The name of the container for this item. Deletion of the container item leads to automatic deletion of this item. Note: ACLs are not inherited from a container item. To provide ACL inheritance for an item, use the inheritAclFrom field. The maximum length is 1536 characters."
        },
        "objectType": {
          "type": "string",
          "description": "The type of the item. This should correspond to the name of an object definition in the schema registered for the data source. For example, if the schema for the data source contains an object definition with name 'document', then item indexing requests for objects of that type should set objectType to 'document'. The maximum length is 256 characters."
        },
        "updateTime": {
          "type": "string",
          "description": "The time when the item was last modified in the source repository.",
          "format": "google-datetime"
        },
        "createTime": {
          "type": "string",
          "description": "The time when the item was created in the source repository.",
          "format": "google-datetime"
        },
        "contentLanguage": {
          "type": "string",
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. The maximum length is 32 characters."
        },
        "keywords": {
          "items": {
            "type": "string"
          },
          "description": "Additional keywords or phrases that should match the item. Used internally for user generated content. The maximum number of elements is 100. The maximum length is 8192 characters.",
          "type": "array"
        },
        "mimeType": {
          "type": "string",
          "description": "The original mime-type of ItemContent.content in the source repository. The maximum length is 256 characters."
        },
        "searchQualityMetadata": {
          "description": "Additional search quality metadata of the item",
          "$ref": "SearchQualityMetadata"
        },
        "sourceRepositoryUrl": {
          "type": "string",
          "description": "Link to the source repository serving the data. Seach results apply this link to the title. Whitespace or special characters may cause Cloud Seach result links to trigger a redirect notice; to avoid this, encode the URL. The maximum length is 2048 characters."
        },
        "hash": {
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters.",
          "type": "string"
        },
        "interactions": {
          "items": {
            "$ref": "Interaction"
          },
          "description": "A list of interactions for the item. Interactions are used to improve Search quality, but are not exposed to end users. The maximum number of elements is 1000.",
          "type": "array"
        }
      },
      "description": "Available metadata fields for the item.",
      "type": "object",
      "id": "ItemMetadata"
    },
    "GetSearchApplicationUserStatsResponse": {
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationUserStats"
          },
          "type": "array"
        }
      },
      "id": "GetSearchApplicationUserStatsResponse",
      "type": "object"
    },
    "CustomerSettings": {
      "properties": {
        "vpcSettings": {
          "$ref": "VPCSettings",
          "description": "VPC SC settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request."
        },
        "auditLoggingSettings": {
          "description": "Audit Logging settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request.",
          "$ref": "AuditLoggingSettings"
        }
      },
      "description": "Represents settings at a customer level.",
      "type": "object",
      "id": "CustomerSettings"
    },
    "ResponseDebugInfo": {
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      },
      "description": "Debugging information about the response.",
      "id": "ResponseDebugInfo",
      "type": "object"
    },
    "TextPropertyOptions": {
      "description": "Options for text properties.",
      "type": "object",
      "id": "TextPropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the property should be used as a search operator.",
          "$ref": "TextOperatorOptions"
        },
        "retrievalImportance": {
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval.",
          "$ref": "RetrievalImportance"
        }
      }
    },
    "SearchItemsByViewUrlResponse": {
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        }
      },
      "type": "object",
      "id": "SearchItemsByViewUrlResponse"
    },
    "ResultDebugInfo": {
      "description": "Debugging information about the result.",
      "type": "object",
      "id": "ResultDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "type": "string",
          "description": "General debug info formatted for display."
        }
      }
    },
    "SearchApplicationUserStats": {
      "properties": {
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past thirty days",
          "format": "int64"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "type": "string",
          "format": "int64"
        },
        "sevenDaysActiveUsersCount": {
          "format": "int64",
          "type": "string",
          "description": "The count of unique active users in the past seven days"
        }
      },
      "type": "object",
      "id": "SearchApplicationUserStats"
    },
    "CustomerUserStats": {
      "type": "object",
      "id": "CustomerUserStats",
      "properties": {
        "oneDayActiveUsersCount": {
          "description": "The count of unique active users in the past one day",
          "format": "int64",
          "type": "string"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "thirtyDaysActiveUsersCount": {
          "description": "The count of unique active users in the past thirty days",
          "format": "int64",
          "type": "string"
        },
        "sevenDaysActiveUsersCount": {
          "format": "int64",
          "description": "The count of unique active users in the past seven days",
          "type": "string"
        }
      }
    },
    "ResultDisplayField": {
      "id": "ResultDisplayField",
      "description": "Display Fields for Search Results",
      "type": "object",
      "properties": {
        "label": {
          "description": "The display label for the property.",
          "type": "string"
        },
        "property": {
          "description": "The name value pair for the property.",
          "$ref": "NamedProperty"
        },
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        }
      }
    },
    "EnumPropertyOptions": {
      "description": "Options for enum properties, which allow you to define a restricted set of strings to match user queries, set rankings for those string values, and define an operator name to be paired with those strings so that users can narrow results to only items with a specific value. For example, for items in a request tracking system with priority information, you could define *p0* as an allowable enum value and tie this enum to the operator name *priority* so that search users could[...]",
      "type": "object",
      "properties": {
        "possibleValues": {
          "items": {
            "$ref": "EnumValuePair"
          },
          "description": "The list of possible values for the enumeration property. All EnumValuePairs must provide a string value. If you specify an integer value for one EnumValuePair, then all possible EnumValuePairs must provide an integer value. Both the string value and integer value must be unique over all possible values. Once set, possible values cannot be removed or modified. If you supply an ordered ranking and think you might insert additional enum values in the future, leave gaps in[...]",
          "type": "array"
        },
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        },
        "orderedRanking": {
          "type": "string",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "enumDescriptions": [
            "There is no ranking order for the property. Results aren't adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "description": "Used to specify the ordered ranking for the enumeration that determines how the integer values provided in the possible EnumValuePairs are used to rank results. If specified, integer values must be provided for all possible EnumValuePair values given for this property. Can only be used if isRepeatable is false."
        }
      },
      "id": "EnumPropertyOptions"
    },
    "DriveTimeSpanRestrict": {
      "id": "DriveTimeSpanRestrict",
      "type": "object",
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ]
        }
      }
    },
    "QueryInterpretationConfig": {
      "description": "Default options to interpret user query.",
      "id": "QueryInterpretationConfig",
      "type": "object",
      "properties": {
        "forceVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental results retrieval, and usage of synonyms including custom ones. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for verbatim mode.",
          "type": "boolean"
        },
        "forceDisableSupplementalResults": {
          "type": "boolean",
          "description": "Set this flag to disable supplemental results retrieval, setting a flag here will not retrieve supplemental results for queries associated with a given search application. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for supplemental results."
        }
      }
    },
    "GroupId": {
      "type": "object",
      "id": "GroupId",
      "description": "Id representing a group that could be a space, a chat, or a direct message space. Which ID is set here will determine which group",
      "properties": {
        "dmId": {
          "$ref": "DmId",
          "description": "Unique, immutable ID of the Direct Message Space"
        },
        "spaceId": {
          "$ref": "SpaceId",
          "description": "Unique, immutable ID of the Space"
        }
      }
    },
    "IntegerOperatorOptions": {
      "properties": {
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the less-than operator. For example, if lessThanOperatorName is *prioritybelow* and the property's name is *priorityVal*, then queries like *prioritybelow:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is less than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any S[...]",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the greater-than operator. For example, if greaterThanOperatorName is *priorityabove* and the property's name is *priorityVal*, then queries like *priorityabove:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is greater than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 chara[...]"
        }
      },
      "description": "Used to provide a search operator for integer properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "IntegerOperatorOptions",
      "type": "object"
    },
    "ItemCountByStatus": {
      "properties": {
        "count": {
          "type": "string",
          "format": "int64",
          "description": "Number of items matching the status code."
        },
        "statusCode": {
          "description": "Status of the items.",
          "type": "string",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "indexedItemsCount": {
          "type": "string",
          "format": "int64",
          "description": "Number of items matching the status code for which billing is done. This excludes virtual container items from the total count. This count would not be applicable for items with ERROR or NEW_ITEM status code."
        }
      },
      "type": "object",
      "id": "ItemCountByStatus"
    },
    "SearchResult": {
      "description": "Results containing indexed information for a document.",
      "type": "object",
      "id": "SearchResult",
      "properties": {
        "snippet": {
          "$ref": "Snippet",
          "description": "The concatenation of all snippets (summaries) available for this result."
        },
        "debugInfo": {
          "$ref": "ResultDebugInfo",
          "description": "Debugging information about this search result."
        },
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        },
        "url": {
          "type": "string",
          "description": "The URL of the search result. The URL contains a Google redirect to the actual item. This URL is signed and shouldn't be changed."
        },
        "clusteredResults": {
          "description": "If source is clustered, provide list of clustered results. There will only be one level of clustered results. If current source is not enabled for clustering, this field will be empty.",
          "items": {
            "$ref": "SearchResult"
          },
          "type": "array"
        },
        "title": {
          "type": "string",
          "description": "Title of the search result."
        }
      }
    },
    "SearchApplicationQueryStats": {
      "description": "Search application level query stats per date",
      "type": "object",
      "id": "SearchApplicationQueryStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        },
        "queryCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "QueryCountByStatus"
          }
        }
      }
    },
    "EnumOperatorOptions": {
      "description": "Used to provide a search operator for enum properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched. For example, if you provide no operator for a *priority* enum property with possible values *p0* and *p1*, a query that contains the term *p0* returns items that have *p0* as the value of the *priority* property, as well as any items that contain the string *p0* in other fields. If you provide [...]",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the enum property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Stri[...]"
        }
      },
      "type": "object",
      "id": "EnumOperatorOptions"
    },
    "Item": {
      "id": "Item",
      "properties": {
        "status": {
          "$ref": "ItemStatus",
          "description": "Status of the item. Output only field."
        },
        "version": {
          "type": "string",
          "description": "Required. The indexing system stores the version from the datasource as a byte string and compares the Item version in the index to the version of the queued Item using lexical ordering. Cloud Search Indexing won't index or delete any queued item with a version value that is less than or equal to the version of the currently indexed item. The maximum length for this field is 1024 bytes. For information on how item version affects the deletion process, refer to [Handle r[...]",
          "format": "byte"
        },
        "structuredData": {
          "$ref": "ItemStructuredData",
          "description": "The structured data for the item that should conform to a registered object definition in the schema for the data source."
        },
        "queue": {
          "type": "string",
          "description": "Queue this item belongs to. The maximum length is 100 characters."
        },
        "itemType": {
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information. These items cannot be referred in containerName or inheritAclFrom fields.",
            "An item that gets indexed and whose purpose is to supply other items with ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose as CONTAINER_ITEM."
          ],
          "description": "Type for this item.",
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "type": "string"
        },
        "content": {
          "description": "Item content to be indexed and made text searchable.",
          "$ref": "ItemContent"
        },
        "payload": {
          "type": "string",
          "description": "Additional state connector can store for this item. The maximum length is 10000 bytes.",
          "format": "byte"
        },
        "metadata": {
          "$ref": "ItemMetadata",
          "description": "Metadata information."
        },
        "acl": {
          "description": "Access control list for this item.",
          "$ref": "ItemAcl"
        },
        "name": {
          "description": "Name of the Item. Format: datasources/{source_id}/items/{item_id} This is a required field. The maximum length is 1536 characters.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "Represents a single object that is an item in the search index, such as a file, folder, or a database record."
    },
    "AuditLoggingSettings": {
      "description": "Represents the settings for Cloud audit logging",
      "properties": {
        "logDataReadActions": {
          "description": "Indicates whether audit logging is on/off for data access read APIs i.e. ListItems, GetItem etc.",
          "type": "boolean"
        },
        "logAdminReadActions": {
          "type": "boolean",
          "description": "Indicates whether audit logging is on/off for admin activity read APIs i.e. Get/List DataSources, Get/List SearchApplications etc."
        },
        "project": {
          "description": "The resource name of the GCP Project to store audit logs. Cloud audit logging will be enabled after project_name has been updated through CustomerService. Format: projects/{project_id}",
          "type": "string"
        },
        "logDataWriteActions": {
          "type": "boolean",
          "description": "Indicates whether audit logging is on/off for data access write APIs i.e. IndexItem etc."
        }
      },
      "type": "object",
      "id": "AuditLoggingSettings"
    },
    "CheckAccessResponse": {
      "id": "CheckAccessResponse",
      "type": "object",
      "properties": {
        "hasAccess": {
          "type": "boolean",
          "description": "Returns true if principal has access. Returns false otherwise."
        }
      }
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "properties": {
        "date": {
          "description": "Date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned.",
          "$ref": "Date"
        },
        "searchSessionsCount": {
          "format": "int64",
          "description": "The count of search sessions on the day",
          "type": "string"
        }
      },
      "type": "object"
    },
    "StartUploadItemRequest": {
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        }
      },
      "type": "object",
      "id": "StartUploadItemRequest",
      "description": "Start upload file request."
    },
    "SearchApplication": {
      "type": "object",
      "id": "SearchApplication",
      "properties": {
        "returnResultThumbnailUrls": {
          "type": "boolean",
          "description": "With each result we should return the URI for its thumbnail (when applicable)"
        },
        "sourceConfig": {
          "type": "array",
          "items": {
            "$ref": "SourceConfig"
          },
          "description": "Configuration for a sources specified in data_source_restrictions."
        },
        "scoringConfig": {
          "description": "Configuration for ranking results.",
          "$ref": "ScoringConfig"
        },
        "dataSourceRestrictions": {
          "type": "array",
          "description": "Retrictions applied to the configurations. The maximum number of elements is 10.",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        },
        "enableAuditLog": {
          "description": "Indicates whether audit logging is on/off for requests made for the search application in query APIs.",
          "type": "boolean"
        },
        "defaultFacetOptions": {
          "type": "array",
          "description": "The default fields for returning facet results. The sources specified here also have been included in data_source_restrictions above.",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "operationIds": {
          "items": {
            "type": "string"
          },
          "description": "Output only. IDs of the Long Running Operations (LROs) currently running for this schema. Output only field.",
          "type": "array",
          "readOnly": true
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the Search Application. The maximum length is 300 characters."
        },
        "queryInterpretationConfig": {
          "$ref": "QueryInterpretationConfig",
          "description": "The default options for query interpretation"
        },
        "name": {
          "description": "Name of the Search Application. Format: searchapplications/{application_id}.",
          "type": "string"
        },
        "defaultSortOptions": {
          "$ref": "SortOptions",
          "description": "The default options for sorting the search results"
        }
      },
      "description": "SearchApplication"
    },
    "DateValues": {
      "description": "List of date values.",
      "properties": {
        "values": {
          "items": {
            "$ref": "Date"
          },
          "type": "array"
        }
      },
      "type": "object",
      "id": "DateValues"
    },
    "ObjectDefinition": {
      "type": "object",
      "properties": {
        "options": {
          "description": "The optional object-specific options.",
          "$ref": "ObjectOptions"
        },
        "name": {
          "type": "string",
          "description": "Name for the object, which then defines its type. Item indexing requests should set the objectType field equal to this value. For example, if *name* is *Document*, then indexing requests for items of type Document should set objectType equal to *Document*. Each object definition must be uniquely named within a schema. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The maximum length is 256 characters."
        },
        "propertyDefinitions": {
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          },
          "description": "The property definitions for the object. The maximum number of elements is 1000."
        }
      },
      "id": "ObjectDefinition",
      "description": "The definition for an object within a data source."
    },
    "HtmlPropertyOptions": {
      "properties": {
        "operatorOptions": {
          "$ref": "HtmlOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        },
        "retrievalImportance": {
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval. Can only be set to DEFAULT or NONE.",
          "$ref": "RetrievalImportance"
        }
      },
      "description": "Options for html properties.",
      "id": "HtmlPropertyOptions",
      "type": "object"
    },
    "MatchRange": {
      "description": "Matched range of a snippet [start, end).",
      "properties": {
        "end": {
          "format": "int32",
          "description": "End of the match in the snippet.",
          "type": "integer"
        },
        "start": {
          "type": "integer",
          "description": "Starting position of the match in the snippet.",
          "format": "int32"
        }
      },
      "type": "object",
      "id": "MatchRange"
    },
    "TimestampOperatorOptions": {
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property. For example, if operatorName is *closedon* and the property's name is *closeDate*, then queries like *closedon:\u003cvalue\u003e* show results only where the value of the property named *closeDate* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Str[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "description": "Used to provide a search operator for timestamp properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "TimestampOperatorOptions"
    },
    "TimestampPropertyOptions": {
      "type": "object",
      "description": "Options for timestamp properties.",
      "id": "TimestampPropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the timestamp should be used as a search operator.",
          "$ref": "TimestampOperatorOptions"
        }
      }
    },
    "ListQuerySourcesResponse": {
      "type": "object",
      "properties": {
        "sources": {
          "items": {
            "$ref": "QuerySource"
          },
          "type": "array"
        },
        "nextPageToken": {
          "type": "string"
        }
      },
      "description": "List sources response.",
      "id": "ListQuerySourcesResponse"
    },
    "ListDataSourceResponse": {
      "type": "object",
      "id": "ListDataSourceResponse",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        },
        "sources": {
          "type": "array",
          "items": {
            "$ref": "DataSource"
          }
        }
      }
    },
    "DriveFollowUpRestrict": {
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ]
        }
      },
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "type": "object",
      "id": "DriveFollowUpRestrict"
    },
    "ObjectPropertyOptions": {
      "properties": {
        "subobjectProperties": {
          "items": {
            "$ref": "PropertyDefinition"
          },
          "type": "array",
          "description": "The properties of the sub-object. These properties represent a nested object. For example, if this property represents a postal address, the subobjectProperties might be named *street*, *city*, and *state*. The maximum number of elements is 1000."
        }
      },
      "description": "Options for object properties.",
      "id": "ObjectPropertyOptions",
      "type": "object"
    },
    "AclInfo": {
      "type": "object",
      "properties": {
        "groupsCount": {
          "format": "int32",
          "description": "Number of groups which have at least read access to the document.",
          "type": "integer"
        },
        "scope": {
          "enumDescriptions": [
            "Explicit set of people and groups.",
            "Anybody at the same domain with the link.",
            "Now it works only for google.com. Anybody at the same domain. Now it works only",
            "for google.com. Anybody with the link.",
            "Anybody.",
            "Special tag to indicate TeamDrive scope."
          ],
          "type": "string",
          "description": "The scope to which the content was shared.",
          "enum": [
            "LIMITED",
            "DASHER_DOMAIN_WITH_LINK",
            "DASHER_DOMAIN",
            "PUBLIC_WITH_LINK",
            "PUBLIC",
            "TEAM_DRIVE"
          ]
        },
        "usersCount": {
          "type": "integer",
          "format": "int32",
          "description": "Number of users which have at least read access to the document."
        }
      },
      "id": "AclInfo",
      "description": "Next tag: 4"
    },
    "NamedProperty": {
      "properties": {
        "dateValues": {
          "$ref": "DateValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        },
        "name": {
          "description": "The name of the property. This name should correspond to the name of the property that was registered for object definition in the schema. The maximum allowable length for this property is 256 characters.",
          "type": "string"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "textValues": {
          "$ref": "TextValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        }
      },
      "id": "NamedProperty",
      "description": "A typed name-value pair for structured data. The type of the value should be the same as the registered type for the `name` property in the object definition of `objectType`.",
      "type": "object"
    },
    "ListItemsResponse": {
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        },
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        }
      },
      "id": "ListItemsResponse",
      "type": "object"
    },
    "BooleanPropertyOptions": {
      "description": "Options for boolean properties.",
      "type": "object",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "BooleanOperatorOptions",
          "description": "If set, describes how the boolean should be used as a search operator."
        }
      }
    },
    "ErrorMessage": {
      "properties": {
        "source": {
          "$ref": "Source"
        },
        "errorMessage": {
          "type": "string"
        }
      },
      "type": "object",
      "description": "Error message per source response.",
      "id": "ErrorMessage"
    },
    "BooleanOperatorOptions": {
      "description": "Used to provide a search operator for boolean properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "id": "BooleanOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the boolean property. For example, if operatorName is *closed* and the property's name is *isClosed*, then queries like *closed:\u003cvalue\u003e* show results only where the value of the property named *isClosed* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any String prop[...]",
          "type": "string"
        }
      }
    },
    "Date": {
      "properties": {
        "year": {
          "type": "integer",
          "description": "Year of date. Must be from 1 to 9999.",
          "format": "int32"
        },
        "month": {
          "type": "integer",
          "format": "int32",
          "description": "Month of date. Must be from 1 to 12."
        },
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "type": "integer",
          "format": "int32"
        }
      },
      "type": "object",
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "id": "Date"
    },
    "SpellResult": {
      "type": "object",
      "id": "SpellResult",
      "properties": {
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested spelling of the query."
        }
      }
    },
    "DataSourceIndexStats": {
      "type": "object",
      "description": "Aggregation of items by status code as of the specified date.",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which index stats were calculated. If the date of request is not the current date then stats calculated on the next day are returned. Stats are calculated close to mid night in this case. If date of request is current date, then real time stats are returned."
        },
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array",
          "description": "Number of items aggregrated by status code."
        }
      },
      "id": "DataSourceIndexStats"
    },
    "CustomerIndexStats": {
      "properties": {
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "description": "Number of items aggregrated by status code.",
          "type": "array"
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which statistics were calculated."
        }
      },
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "CustomerIndexStats",
      "type": "object"
    },
    "ListUnmappedIdentitiesResponse": {
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        },
        "unmappedIdentities": {
          "type": "array",
          "items": {
            "$ref": "UnmappedIdentity"
          }
        }
      },
      "type": "object",
      "id": "ListUnmappedIdentitiesResponse"
    },
    "SuggestRequest": {
      "description": "Request of suggest API.",
      "type": "object",
      "id": "SuggestRequest",
      "properties": {
        "dataSourceRestrictions": {
          "description": "The sources to use for suggestions. If not specified, the data sources are taken from the current search application. NOTE: Suggestions are only supported for the following sources: * Third-party data sources * PredefinedSource.PERSON * PredefinedSource.GOOGLE_DRIVE",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "query": {
          "type": "string",
          "description": "Partial query for which autocomplete suggestions will be shown. For example, if the query is \"sea\", then the server might return \"season\", \"search\", \"seagull\" and so on."
        }
      }
    },
    "Principal": {
      "properties": {
        "gsuitePrincipal": {
          "$ref": "GSuitePrincipal",
          "description": "This principal is a GSuite user, group or domain."
        },
        "userResourceName": {
          "type": "string",
          "description": "This principal is a user identified using an external identity. The name field must specify the user resource name with this format: identitysources/{source_id}/users/{ID}"
        },
        "groupResourceName": {
          "description": "This principal is a group identified using an external identity. The name field must specify the group resource name with this format: identitysources/{source_id}/groups/{ID}",
          "type": "string"
        }
      },
      "description": "Reference to a user, group, or domain.",
      "id": "Principal",
      "type": "object"
    },
    "DebugOptions": {
      "description": "Shared request debug options for all cloudsearch RPC methods.",
      "type": "object",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "id": "DebugOptions"
    },
    "FieldViolation": {
      "properties": {
        "description": {
          "description": "Description of the error.",
          "type": "string"
        },
        "field": {
          "description": "Path of field with violation.",
          "type": "string"
        }
      },
      "type": "object",
      "id": "FieldViolation"
    },
    "TimestampValues": {
      "id": "TimestampValues",
      "type": "object",
      "description": "List of timestamp values.",
      "properties": {
        "values": {
          "items": {
            "type": "string",
            "format": "google-datetime"
          },
          "type": "array"
        }
      }
    },
    "DatePropertyOptions": {
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "DateOperatorOptions",
          "description": "If set, describes how the date should be used as a search operator."
        }
      },
      "description": "Options for date properties.",
      "id": "DatePropertyOptions"
    },
    "Filter": {
      "type": "object",
      "id": "Filter",
      "properties": {
        "compositeFilter": {
          "$ref": "CompositeFilter"
        },
        "valueFilter": {
          "$ref": "ValueFilter"
        }
      },
      "description": "A generic way of expressing filters in a query, which supports two approaches: **1. Setting a ValueFilter.** The name must match an operator_name defined in the schema for your data source. **2. Setting a CompositeFilter.** The filters are evaluated using the logical operator. The top-level operators can only be either an AND or a NOT. AND can appear only at the top-most level. OR can appear only under a top-level AND."
    },
    "GetCustomerUserStatsResponse": {
      "id": "GetCustomerUserStatsResponse",
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerUserStats"
          }
        }
      }
    },
    "GetSearchApplicationSessionStatsResponse": {
      "id": "GetSearchApplicationSessionStatsResponse",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationSessionStats"
          }
        }
      },
      "type": "object"
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "ownerName": "Google",
  "title": "Cloud Search API",
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "protocol": "rest",
  "servicePath": "",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "resources": {
    "media": {
      "methods": {
        "upload": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "supportsMediaUpload": true,
          "id": "cloudsearch.media.upload",
          "flatPath": "v1/media/{mediaId}",
          "httpMethod": "POST",
          "path": "v1/media/{+resourceName}",
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a[...]"
        }
      }
    },
    "stats": {
      "resources": {
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/user/{+name}",
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.user.searchapplications.get"
                }
              }
            }
          }
        },
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/stats/index/{+name}",
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "id": "cloudsearch.stats.index.datasources.get"
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "path": "v1/stats/session/{+name}"
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/query/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "id": "cloudsearch.stats.query.searchapplications.get"
                }
              }
            }
          }
        }
      },
      "methods": {
        "getSearchapplication": {
          "flatPath": "v1/stats/searchapplication",
          "id": "cloudsearch.stats.getSearchapplication",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute.",
          "path": "v1/stats/searchapplication"
        },
        "getSession": {
          "httpMethod": "GET",
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "path": "v1/stats/session",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/session",
          "id": "cloudsearch.stats.getSession"
        },
        "getUser": {
          "path": "v1/stats/user",
          "id": "cloudsearch.stats.getUser",
          "flatPath": "v1/stats/user",
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getQuery": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "id": "cloudsearch.stats.getQuery",
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/query",
          "path": "v1/stats/query",
          "httpMethod": "GET"
        },
        "getIndex": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "path": "v1/stats/index",
          "id": "cloudsearch.stats.getIndex",
          "flatPath": "v1/stats/index",
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute."
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "id": "cloudsearch.operations.get",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v1/{+name}/lro",
              "id": "cloudsearch.operations.lro.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the oper[...]",
              "flatPath": "v1/operations/{operationsId}/lro"
            }
          }
        }
      }
    },
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "path": "v1/debug/{+parent}/unmappedids",
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute.",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "httpMethod": "GET"
                    }
                  }
                }
              },
              "methods": {
                "checkAccess": {
                  "description": "Checks whether an item is accessible by specified principal. **Note:** This API requires an admin account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "httpMethod": "POST"
                },
                "searchByViewUrl": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "POST",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl"
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "unmappedids": {
              "methods": {
                "list": {
                  "path": "v1/debug/{+parent}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "GET",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids"
                }
              }
            },
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "getSchema": {
              "id": "cloudsearch.indexing.datasources.getSchema",
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema"
            },
            "updateSchema": {
              "path": "v1/indexing/{+name}/schema",
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema"
            },
            "deleteSchema": {
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema",
              "httpMethod": "DELETE",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          },
          "resources": {
            "items": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "path": "v1/indexing/{+name}/items",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items"
                },
                "unreserve": {
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "httpMethod": "POST"
                },
                "push": {
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}:push"
                },
                "deleteQueueItems": {
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "httpMethod": "POST",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems"
                },
                "upload": {
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}:upload",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload"
                },
                "index": {
                  "path": "v1/indexing/{+name}:index",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "POST"
                },
                "poll": {
                  "path": "v1/indexing/{+name}/items:poll",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll"
                },
                "get": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}"
                },
                "delete": {
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "DELETE",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1/indexing/{+name}"
                }
              }
            }
          }
        }
      }
    },
    "v1": {
      "methods": {
        "initializeCustomer": {
          "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "flatPath": "v1:initializeCustomer",
          "httpMethod": "POST",
          "id": "cloudsearch.initializeCustomer",
          "path": "v1:initializeCustomer"
        }
      }
    },
    "query": {
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "path": "v1/query/sources",
              "id": "cloudsearch.query.sources.list",
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "flatPath": "v1/query/sources"
            }
          }
        }
      },
      "methods": {
        "search": {
          "flatPath": "v1/query/search",
          "httpMethod": "POST",
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide [...]",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "path": "v1/query/search",
          "id": "cloudsearch.query.search"
        },
        "suggest": {
          "id": "cloudsearch.query.suggest",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "path": "v1/query/suggest",
          "flatPath": "v1/query/suggest",
          "httpMethod": "POST",
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/)."
        }
      }
    },
    "settings": {
      "methods": {
        "getCustomer": {
          "description": "Get customer settings. **Note:** This API requires an admin account to execute.",
          "id": "cloudsearch.settings.getCustomer",
          "flatPath": "v1/settings/customer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "httpMethod": "GET"
        },
        "updateCustomer": {
          "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
          "path": "v1/settings/customer",
          "flatPath": "v1/settings/customer",
          "id": "cloudsearch.settings.updateCustomer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "httpMethod": "PATCH"
        }
      },
      "resources": {
        "datasources": {
          "methods": {
            "get": {
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute.",
              "httpMethod": "GET",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.settings.datasources.get",
              "flatPath": "v1/settings/datasources/{datasourcesId}"
            },
            "create": {
              "httpMethod": "POST",
              "id": "cloudsearch.settings.datasources.create",
              "flatPath": "v1/settings/datasources",
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "path": "v1/settings/datasources"
            },
            "update": {
              "httpMethod": "PUT",
              "path": "v1/settings/{+name}",
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.update",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "list": {
              "id": "cloudsearch.settings.datasources.list",
              "httpMethod": "GET",
              "description": "Lists datasources. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "path": "v1/settings/datasources"
            },
            "delete": {
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.delete",
              "path": "v1/settings/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          }
        },
        "searchapplications": {
          "methods": {
            "delete": {
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.delete",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "update": {
              "id": "cloudsearch.settings.searchapplications.update",
              "path": "v1/settings/{+name}",
              "httpMethod": "PUT",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "reset": {
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "id": "cloudsearch.settings.searchapplications.reset",
              "path": "v1/settings/{+name}:reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
              "httpMethod": "POST"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.settings.searchapplications.create",
              "httpMethod": "POST",
              "flatPath": "v1/settings/searchapplications",
              "path": "v1/settings/searchapplications",
              "description": "Creates a search application. **Note:** This API requires an admin account to execute."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.list",
              "flatPath": "v1/settings/searchapplications",
              "path": "v1/settings/searchapplications"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.get",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "basePath": "",
  "id": "cloudsearch:v1",
  "canonicalName": "Cloud Search",
  "ownerDomain": "google.com",
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search.",
  "name": "cloudsearch",
  "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/"
}
