{
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "id": "cloudidentity:v1",
  "description": "API for provisioning and managing identity resources.",
  "version_module": true,
  "canonicalName": "Cloud Identity",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "basePath": "",
  "documentationLink": "https://cloud.google.com/identity/",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "revision": "20221221",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        }
      }
    }
  },
  "servicePath": "",
  "title": "Cloud Identity API",
  "name": "cloudidentity",
  "protocol": "rest",
  "resources": {
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "path": "v1/{+name}",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}"
            },
            "send": {
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "httpMethod": "POST",
              "path": "v1/{+name}:send",
              "id": "cloudidentity.customers.userinvitations.send"
            },
            "isInvitableUser": {
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "path": "v1/{+name}:isInvitableUser"
            },
            "cancel": {
              "httpMethod": "POST",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "description": "Cancels a UserInvitation that was already sent.",
              "path": "v1/{+name}:cancel",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel"
            },
            "list": {
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "path": "v1/{+parent}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.list"
            }
          }
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships",
              "description": "Lists the `Membership`s within a `Group`."
            },
            "getMembershipGraph": {
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.getMembershipGraph"
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET"
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1/{+name}",
              "description": "Deletes a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "searchTransitiveMemberships": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships."
            },
            "create": {
              "description": "Creates a `Membership`.",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "id": "cloudidentity.groups.memberships.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST"
            },
            "searchTransitiveGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "httpMethod": "GET"
            },
            "lookup": {
              "id": "cloudidentity.groups.memberships.lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "path": "v1/{+parent}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.get",
              "description": "Retrieves a `Membership`.",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "getSecuritySettings": {
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "description": "Get Security Settings",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.getSecuritySettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "search": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "flatPath": "v1/groups:search",
          "httpMethod": "GET",
          "description": "Searches for `Group` resources matching a specified query."
        },
        "create": {
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create",
          "path": "v1/groups",
          "httpMethod": "POST",
          "description": "Creates a Group."
        },
        "get": {
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.get",
          "description": "Retrieves a `Group`.",
          "httpMethod": "GET",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "updateSecuritySettings": {
          "id": "cloudidentity.groups.updateSecuritySettings",
          "description": "Update Security Settings",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1/groups/{groupsId}/securitySettings"
        },
        "delete": {
          "flatPath": "v1/groups/{groupsId}",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.delete",
          "description": "Deletes a `Group`.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups",
          "httpMethod": "GET",
          "flatPath": "v1/groups",
          "description": "Lists the `Group` resources under a customer or namespace.",
          "id": "cloudidentity.groups.list"
        },
        "patch": {
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.patch",
          "path": "v1/{+name}",
          "description": "Updates a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "lookup": {
          "httpMethod": "GET",
          "path": "v1/groups:lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "id": "cloudidentity.groups.lookup",
          "flatPath": "v1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "path": "v1/{+name}",
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "path": "v1/{+parent}/clientStates",
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "description": "Lists the client states for the given search query.",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates"
                },
                "patch": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1/{+name}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "PATCH"
                }
              }
            }
          },
          "methods": {
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Blocks device from accessing user data",
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "path": "v1/{+name}:block"
            },
            "lookup": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "path": "v1/{+parent}:lookup",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "httpMethod": "DELETE",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.delete",
              "path": "v1/{+name}"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "description": "Approves device to access user data.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1/{+name}:approve",
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "id": "cloudidentity.devices.deviceUsers.list",
              "description": "Lists/Searches DeviceUsers.",
              "path": "v1/{+parent}/deviceUsers"
            },
            "get": {
              "httpMethod": "GET",
              "id": "cloudidentity.devices.deviceUsers.get",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Retrieves the specified DeviceUser",
              "path": "v1/{+name}"
            },
            "cancelWipe": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "path": "v1/{+name}:cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe"
            },
            "wipe": {
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "httpMethod": "POST",
              "path": "v1/{+name}:wipe"
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "cloudidentity.devices.create",
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST",
          "path": "v1/devices",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
        },
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancelWipe"
        },
        "list": {
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "id": "cloudidentity.devices.list",
          "httpMethod": "GET",
          "description": "Lists/Searches devices.",
          "path": "v1/devices"
        },
        "get": {
          "description": "Retrieves the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "id": "cloudidentity.devices.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ]
        },
        "wipe": {
          "path": "v1/{+name}:wipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Wipes all data on the specified device.",
          "httpMethod": "POST",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "id": "cloudidentity.devices.wipe"
        },
        "delete": {
          "flatPath": "v1/devices/{devicesId}",
          "path": "v1/{+name}",
          "description": "Deletes the specified device.",
          "httpMethod": "DELETE",
          "id": "cloudidentity.devices.delete",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        }
      }
    }
  },
  "version": "v1",
  "batchPath": "batch",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/"
}
