{
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "documentationLink": "https://cloud.google.com/identity/",
  "canonicalName": "Cloud Identity",
  "name": "cloudidentity",
  "batchPath": "batch",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "servicePath": "",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "id": "cloudidentity:v1",
  "description": "API for provisioning and managing identity resources.",
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "basePath": "",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "revision": "20220125",
  "title": "Cloud Identity API",
  "resources": {
    "devices": {
      "methods": {
        "delete": {
          "path": "v1/{+name}",
          "description": "Deletes the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.delete",
          "httpMethod": "DELETE"
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "description": "Retrieves the specified device.",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1/devices/{devicesId}"
        },
        "cancelWipe": {
          "path": "v1/{+name}:cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device."
        },
        "list": {
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.list",
          "path": "v1/devices",
          "httpMethod": "GET",
          "description": "Lists/Searches devices."
        },
        "create": {
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.create",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "httpMethod": "POST"
        },
        "wipe": {
          "httpMethod": "POST",
          "description": "Wipes all data on the specified device.",
          "id": "cloudidentity.devices.wipe",
          "path": "v1/{+name}:wipe",
          "flatPath": "v1/devices/{devicesId}:wipe"
        }
      },
      "resources": {
        "deviceUsers": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v1/{+parent}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "id": "cloudidentity.devices.deviceUsers.list"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "DELETE"
            },
            "cancelWipe": {
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "httpMethod": "POST",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "path": "v1/{+name}:cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe"
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "description": "Blocks device from accessing user data",
              "path": "v1/{+name}:block",
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block"
            },
            "lookup": {
              "path": "v1/{+parent}:lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "id": "cloudidentity.devices.deviceUsers.lookup"
            },
            "wipe": {
              "httpMethod": "POST",
              "path": "v1/{+name}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe"
            },
            "get": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "description": "Retrieves the specified DeviceUser",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "approve": {
              "path": "v1/{+name}:approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "description": "Approves device to access user data.",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "description": "Gets the client state for the device user",
                  "path": "v1/{+name}"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
                },
                "list": {
                  "path": "v1/{+parent}/clientStates",
                  "description": "Lists the client states for the given search query.",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list"
                }
              }
            }
          }
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "searchTransitiveGroups": {
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "getMembershipGraph": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "id": "cloudidentity.groups.memberships.getMembershipGraph"
            },
            "list": {
              "path": "v1/{+parent}/memberships",
              "id": "cloudidentity.groups.memberships.list",
              "httpMethod": "GET",
              "description": "Lists the `Membership`s within a `Group`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships"
            },
            "delete": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1/{+name}",
              "description": "Deletes a `Membership`."
            },
            "modifyMembershipRoles": {
              "httpMethod": "POST",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+name}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles"
            },
            "searchTransitiveMemberships": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Retrieves a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.get"
            },
            "lookup": {
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.lookup",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:lookup"
            },
            "create": {
              "path": "v1/{+parent}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "description": "Creates a `Membership`.",
              "id": "cloudidentity.groups.memberships.create"
            },
            "checkTransitiveMembership": {
              "httpMethod": "GET",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership"
            }
          }
        }
      },
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}",
          "description": "Deletes a `Group`.",
          "httpMethod": "DELETE",
          "flatPath": "v1/groups/{groupsId}"
        },
        "list": {
          "flatPath": "v1/groups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.list",
          "description": "Lists the `Group` resources under a customer or namespace.",
          "path": "v1/groups"
        },
        "getSecuritySettings": {
          "description": "Get Security Settings",
          "httpMethod": "GET",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.getSecuritySettings"
        },
        "search": {
          "description": "Searches for `Group` resources matching a specified query.",
          "httpMethod": "GET",
          "flatPath": "v1/groups:search",
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a `Group`.",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.get",
          "flatPath": "v1/groups/{groupsId}"
        },
        "create": {
          "flatPath": "v1/groups",
          "httpMethod": "POST",
          "description": "Creates a Group.",
          "path": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create"
        },
        "patch": {
          "id": "cloudidentity.groups.patch",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`.",
          "httpMethod": "PATCH"
        },
        "updateSecuritySettings": {
          "path": "v1/{+name}",
          "description": "Update Security Settings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.updateSecuritySettings"
        },
        "lookup": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups:lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "flatPath": "v1/groups:lookup",
          "id": "cloudidentity.groups.lookup"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "version": "v1"
}
