{
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "version_module": true,
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "resources": {
    "stats": {
      "resources": {
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/query/{+name}",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "path": "v1/stats/user/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "id": "cloudsearch.stats.user.searchapplications.get",
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute."
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "path": "v1/stats/session/{+name}"
                }
              }
            }
          }
        },
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "id": "cloudsearch.stats.index.datasources.get",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "path": "v1/stats/index/{+name}"
                }
              }
            }
          }
        }
      },
      "methods": {
        "getSession": {
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/session",
          "path": "v1/stats/session",
          "id": "cloudsearch.stats.getSession",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "httpMethod": "GET"
        },
        "getIndex": {
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "path": "v1/stats/index",
          "flatPath": "v1/stats/index",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "id": "cloudsearch.stats.getIndex"
        },
        "getUser": {
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "path": "v1/stats/user",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "id": "cloudsearch.stats.getUser",
          "flatPath": "v1/stats/user"
        },
        "getQuery": {
          "httpMethod": "GET",
          "path": "v1/stats/query",
          "flatPath": "v1/stats/query",
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "id": "cloudsearch.stats.getQuery",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getSearchapplication": {
          "id": "cloudsearch.stats.getSearchapplication",
          "path": "v1/stats/searchapplication",
          "flatPath": "v1/stats/searchapplication",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute."
        }
      }
    },
    "query": {
      "methods": {
        "search": {
          "path": "v1/query/search",
          "flatPath": "v1/query/search",
          "id": "cloudsearch.query.search",
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide [...]",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        },
        "suggest": {
          "path": "v1/query/suggest",
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "id": "cloudsearch.query.suggest",
          "flatPath": "v1/query/suggest",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ]
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "flatPath": "v1/query/sources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "id": "cloudsearch.query.sources.list",
              "httpMethod": "GET",
              "path": "v1/query/sources",
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/)."
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "flatPath": "v1/media/{mediaId}",
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a[...]",
          "path": "v1/media/{+resourceName}",
          "id": "cloudsearch.media.upload",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "supportsMediaUpload": true,
          "httpMethod": "POST"
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "deleteSchema": {
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "DELETE",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema"
            },
            "updateSchema": {
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "PUT"
            },
            "getSchema": {
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "path": "v1/indexing/{+name}/schema",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.indexing.datasources.getSchema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema"
            }
          },
          "resources": {
            "items": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "GET",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}"
                },
                "unreserve": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve"
                },
                "deleteQueueItems": {
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems"
                },
                "delete": {
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}",
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "upload": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "httpMethod": "POST",
                  "path": "v1/indexing/{+name}:upload",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "poll": {
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1/indexing/{+name}/items:poll",
                  "httpMethod": "POST",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}/items",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items"
                },
                "push": {
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}:push",
                  "httpMethod": "POST",
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push"
                },
                "index": {
                  "httpMethod": "POST",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "path": "v1/indexing/{+name}:index",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "debug": {
      "resources": {
        "identitysources": {
          "resources": {
            "unmappedids": {
              "methods": {
                "list": {
                  "path": "v1/debug/{+parent}/unmappedids",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "datasources": {
          "resources": {
            "items": {
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "path": "v1/debug/{+parent}/unmappedids",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list"
                    }
                  }
                }
              },
              "methods": {
                "searchByViewUrl": {
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "httpMethod": "POST"
                },
                "checkAccess": {
                  "httpMethod": "POST",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "description": "Checks whether an item is accessible by specified principal. Principal must be a user; groups and domain values aren't supported. **Note:** This API requires an admin account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "searchapplications": {
          "methods": {
            "create": {
              "id": "cloudsearch.settings.searchapplications.create",
              "flatPath": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Creates a search application. **Note:** This API requires an admin account to execute.",
              "httpMethod": "POST",
              "path": "v1/settings/searchapplications"
            },
            "update": {
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "httpMethod": "PUT",
              "id": "cloudsearch.settings.searchapplications.update",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "path": "v1/settings/{+name}"
            },
            "list": {
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
              "httpMethod": "GET",
              "flatPath": "v1/settings/searchapplications",
              "path": "v1/settings/searchapplications",
              "id": "cloudsearch.settings.searchapplications.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "get": {
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.searchapplications.get",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "httpMethod": "DELETE",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.delete",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            },
            "reset": {
              "id": "cloudsearch.settings.searchapplications.reset",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "path": "v1/settings/{+name}:reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
              "httpMethod": "POST"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "id": "cloudsearch.settings.searchapplications.patch",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "path": "v1/settings/{+name}",
              "description": "Updates a search application. **Note:** This API requires an admin account to execute."
            }
          }
        },
        "datasources": {
          "methods": {
            "patch": {
              "path": "v1/settings/{+name}",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.datasources.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            },
            "get": {
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.get",
              "path": "v1/settings/{+name}",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.settings.datasources.delete",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "httpMethod": "DELETE"
            },
            "update": {
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "id": "cloudsearch.settings.datasources.update",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "PUT"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.list",
              "path": "v1/settings/datasources",
              "httpMethod": "GET",
              "description": "Lists datasources. **Note:** This API requires an admin account to execute."
            },
            "create": {
              "httpMethod": "POST",
              "id": "cloudsearch.settings.datasources.create",
              "path": "v1/settings/datasources",
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "flatPath": "v1/settings/datasources"
            }
          }
        }
      },
      "methods": {
        "updateCustomer": {
          "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
          "httpMethod": "PATCH",
          "flatPath": "v1/settings/customer",
          "id": "cloudsearch.settings.updateCustomer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ]
        },
        "getCustomer": {
          "id": "cloudsearch.settings.getCustomer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "path": "v1/settings/customer",
          "flatPath": "v1/settings/customer",
          "httpMethod": "GET",
          "description": "Get customer settings. **Note:** This API requires an admin account to execute."
        }
      }
    },
    "v1": {
      "methods": {
        "initializeCustomer": {
          "id": "cloudsearch.initializeCustomer",
          "path": "v1:initializeCustomer",
          "flatPath": "v1:initializeCustomer",
          "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ]
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "id": "cloudsearch.operations.get"
        }
      },
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
              "flatPath": "v1/operations/{operationsId}/lro",
              "path": "v1/{+name}/lro",
              "id": "cloudsearch.operations.lro.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ]
            }
          }
        }
      }
    }
  },
  "canonicalName": "Cloud Search",
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search.",
  "schemas": {
    "ErrorMessage": {
      "description": "Error message per source response.",
      "properties": {
        "source": {
          "$ref": "Source"
        },
        "errorMessage": {
          "type": "string"
        }
      },
      "type": "object",
      "id": "ErrorMessage"
    },
    "AppsDynamiteV1ApiCompatV1Field": {
      "type": "object",
      "properties": {
        "value": {
          "description": "The text value of the field.",
          "type": "string"
        },
        "short": {
          "description": "Whether the field can be shown side-by-side with another field.",
          "type": "boolean"
        },
        "title": {
          "type": "string",
          "description": "The heading text, shown in bold."
        }
      },
      "id": "AppsDynamiteV1ApiCompatV1Field",
      "description": "A column of text in an attachment. Documentation: - https://api.slack.com/docs/message-attachments"
    },
    "FilterOptions": {
      "description": "Filter options to be applied on query.",
      "properties": {
        "objectType": {
          "description": "If object_type is set, only objects of that type are returned. This should correspond to the name of the object that was registered within the definition of schema. The maximum length is 256 characters.",
          "type": "string"
        },
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        }
      },
      "id": "FilterOptions",
      "type": "object"
    },
    "SigningKeyPossessorProto": {
      "description": "Represents a principal who possesses a signing key corresponding to the verification key or keyset described here.",
      "id": "SigningKeyPossessorProto",
      "type": "object",
      "properties": {
        "keymasterKeyType": {
          "type": "integer",
          "format": "int32",
          "description": "This value must be from the KeyMetadata.Type enum in keymaster.proto."
        },
        "serializedVerificationKey": {
          "format": "byte",
          "type": "string",
          "description": "The actual verification key bytes corresponding to the above type."
        },
        "serializedVerificationKeyset": {
          "description": "The binary serialized Keymaster SerializedReader of a public keyset. The keyset must contain exactly one key. N.B.: If this field is populated, serialized_verification_key should be set to the empty string and keymaster_key_type should be set to zero.",
          "type": "string",
          "format": "byte"
        }
      }
    },
    "TransientData": {
      "type": "object",
      "properties": {},
      "id": "TransientData",
      "description": "Transient generic data that will not be saved on the server."
    },
    "ThreadKeySet": {
      "id": "ThreadKeySet",
      "properties": {
        "messageKeys": {
          "type": "array",
          "description": "Messages on which the thread_key was changed.",
          "items": {
            "$ref": "MultiKey"
          }
        },
        "newThreadKey": {
          "description": "The new thread_key for this thread",
          "$ref": "MultiKey"
        }
      },
      "description": "The ThreadKey was set on some (subset of the) messages in this thread.",
      "type": "object"
    },
    "Snippet": {
      "id": "Snippet",
      "properties": {
        "snippet": {
          "description": "The snippet of the document. The snippet of the document. May contain escaped HTML character that should be unescaped prior to rendering.",
          "type": "string"
        },
        "matchRanges": {
          "type": "array",
          "items": {
            "$ref": "MatchRange"
          },
          "description": "The matched ranges in the snippet."
        }
      },
      "type": "object",
      "description": "Snippet of the search result, which summarizes the content of the resulting page."
    },
    "SpaceId": {
      "type": "object",
      "description": "Primary key for Space resource.",
      "properties": {
        "spaceId": {
          "description": "Unique, immutable ID of the Space",
          "type": "string"
        }
      },
      "id": "SpaceId"
    },
    "VideoInfo": {
      "description": "Next tag: 2",
      "type": "object",
      "id": "VideoInfo",
      "properties": {
        "duration": {
          "type": "integer",
          "description": "Duration of the video in milliseconds. This field can be absent for recently uploaded video or inaccurate sometimes.",
          "format": "int32"
        }
      }
    },
    "DatePropertyOptions": {
      "type": "object",
      "id": "DatePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DateOperatorOptions",
          "description": "If set, describes how the date should be used as a search operator."
        }
      },
      "description": "The options for date properties."
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "type": "object",
      "properties": {
        "date": {
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned.",
          "$ref": "Date"
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "description": "User profile information. This user is not necessarily member of a space.",
      "properties": {
        "organizationInfo": {
          "$ref": "AppsDynamiteSharedOrganizationInfo",
          "description": "Information about whether the user is a consumer user, or the GSuite customer that they belong to."
        },
        "firstName": {
          "type": "string",
          "description": "First or given name of the user"
        },
        "botInfo": {
          "$ref": "BotInfo",
          "description": "Bot-specific profile information. Leave it empty for human users."
        },
        "email": {
          "description": "Email ID of the user",
          "type": "string"
        },
        "userAccountState": {
          "enumDescriptions": [
            "",
            "User has Dynamite enabled.",
            "User doesn't have Dynamite enabled. This includes service disabled by admin, or user's account is suspended",
            "User account is deleted",
            "Failed to retrieve user's info. Will use user's email address as name and first_name."
          ],
          "enum": [
            "UNKNOWN_USER_ACCOUNT_STATE",
            "ENABLED",
            "DISABLED",
            "DELETED",
            "TEMPORARY_UNAVAILABLE"
          ],
          "type": "string",
          "description": "State of user's Gaia Account"
        },
        "id": {
          "$ref": "UserId",
          "description": "UserId"
        },
        "lastName": {
          "description": "Last or family name of the user",
          "type": "string"
        },
        "phoneNumber": {
          "description": "Phone number(s) of the user",
          "items": {
            "$ref": "AppsDynamiteSharedPhoneNumber"
          },
          "type": "array"
        },
        "gender": {
          "type": "string",
          "description": "Gender of the user"
        },
        "isAnonymous": {
          "description": "Set to true if none of the depending services (Gaia, PeopleApi) returns any info for this user.",
          "type": "boolean"
        },
        "blockRelationship": {
          "$ref": "AppsDynamiteSharedUserBlockRelationship",
          "description": "Information about whether the user is blocked by requester and/or has blocked requester."
        },
        "avatarUrl": {
          "description": "URL for the avatar picture of the User in dynamite",
          "type": "string"
        },
        "deleted": {
          "description": "Deleted flag, if true, means User has been soft-deleted/purged Deprecated. Use user_account_state field instead.",
          "type": "boolean"
        },
        "userProfileVisibility": {
          "enumDescriptions": [
            "",
            "Caller has full visibility.",
            "Caller can only see target user's primary email from Gaia",
            "Caller can only see the email used to invite the target user",
            "Caller can only see the target user as a deleted user. Email is empty. Names are redacted as \"Deleted User\".",
            "Caller has no visibility to the target user at all. Email is empty. Names are redacted as \"Unknown User\".",
            "Stubby failed. Clients should always retry ASAP"
          ],
          "description": "Visibility of user's Profile",
          "enum": [
            "UNKNOWN_USER_PROFILE_VISIBILITY",
            "FULL_PROFILE",
            "PRIMARY_MAIL",
            "INVITEE_EMAIL",
            "DELETED_USER",
            "UNKNOWN_USER",
            "FAILURE"
          ],
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Non-unique, user-defined display name of the User"
        }
      },
      "id": "User"
    },
    "HashtagData": {
      "description": "Hashtag metadata, for HASHTAG segments. For a hashtag, the \"text\" field should contain the display text, and the search_text field should represent the topic being referenced, without the hash symbol; for example, we might have: text = \"#Google\" hashtag_data.search_text = \"Google\" Another example: text = \"#pikachu\" hashtag_data.search_text = \"Pokemon\" Both strings should be considered part of the searchable text. In go/sbe, both are indexed and searchable.",
      "type": "object",
      "id": "HashtagData",
      "properties": {
        "searchText": {
          "type": "string"
        }
      }
    },
    "Provenance": {
      "description": "This field records where the ItemScope was retrieved, if it was created via a web fetch.",
      "type": "object",
      "properties": {
        "retrievedTimestampMsec": {
          "format": "uint64",
          "description": "The server retrieved timestamp (in msec).",
          "type": "string"
        },
        "retrievedUrl": {
          "type": "string",
          "description": "The final URL that was the actual source of the itemscope, after any redirects."
        },
        "canonicalUrl": {
          "type": "string",
          "description": "Canonical url of the retrieved_url, if one was resolved during retrieval, for example, if a rel=\"canonical\" link tag was provided in the retrieved web page."
        },
        "itemtype": {
          "description": "Contains exact types as parsed, whether or not we recognized that type at parse time. If an itemscope is created by merging SchemaOrg markup and open graph markup then the first itemtype would be schemaorg type, the second would be open graph and so on. example: http://schema.org/VideoObject, og:video.movie Plain text; usually a URL",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "annotationBlob": {
          "format": "byte",
          "description": "Annotation blob from Annotation Service.",
          "type": "string"
        },
        "inputUrl": {
          "type": "string",
          "description": "The url originally passed in the PRS request, which should be used to re-discover the content. Note that this URL may be a forwarding service or link shortener (bit.ly), so it should not be assumed to be canonical, but should be used for navigation back to the original source of the itemscope."
        }
      },
      "id": "Provenance"
    },
    "FixedFooter": {
      "id": "FixedFooter",
      "properties": {
        "buttons": {
          "type": "array",
          "items": {
            "$ref": "Button"
          }
        },
        "primaryButton": {
          "$ref": "TextButton"
        },
        "secondaryButton": {
          "$ref": "TextButton"
        }
      },
      "type": "object",
      "description": "A persistent (sticky) footer that is added to the bottom of the card."
    },
    "LanguageConfig": {
      "properties": {
        "spokenLanguages": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "The spoken language(s) in BCP47 language code."
        }
      },
      "description": "The language configuration for the session.",
      "type": "object",
      "id": "LanguageConfig"
    },
    "PushItem": {
      "id": "PushItem",
      "description": "Represents an item to be pushed to the indexing queue.",
      "properties": {
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "type": {
          "type": "string",
          "enumDescriptions": [
            "Default UNSPECIFIED. Specifies that the push operation should not modify ItemStatus",
            "Indicates that the repository document has been modified or updated since the previous update call. This changes status to MODIFIED state for an existing item. If this is called on a non existing item, the status is changed to NEW_ITEM.",
            "Item in the repository has not been modified since the last update call. This push operation will set status to ACCEPTED state.",
            "Connector is facing a repository error regarding this item. Change status to REPOSITORY_ERROR state. Item is unreserved and rescheduled at a future time determined by exponential backoff.",
            "Call push with REQUEUE only for items that have been reserved. This action unreserves the item and resets its available time to the wall clock time."
          ],
          "description": "The type of the push operation that defines the push behavior.",
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ]
        },
        "payload": {
          "description": "Provides additional document state information for the connector, such as an alternate repository ID and other metadata. The maximum length is 8192 bytes.",
          "type": "string",
          "format": "byte"
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details. This information is displayed in the Admin Console. This field may only be populated when the Type is REPOSITORY_ERROR."
        },
        "structuredDataHash": {
          "type": "string",
          "description": "Structured data hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "metadataHash": {
          "type": "string",
          "description": "The metadata hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "queue": {
          "description": "Queue to which this item belongs. The `default` queue is chosen if this field is not specified. The maximum length is 512 characters.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "RequestFileScope": {
      "id": "RequestFileScope",
      "type": "object",
      "properties": {
        "itemId": {
          "type": "string"
        }
      }
    },
    "AppsDynamiteSharedOriginAppSuggestion": {
      "description": "Stores the suggestion provided by apps/bots.",
      "id": "AppsDynamiteSharedOriginAppSuggestion",
      "type": "object",
      "properties": {
        "appId": {
          "$ref": "AppId"
        },
        "cardClickSuggestion": {
          "$ref": "AppsDynamiteSharedCardClickSuggestion"
        }
      }
    },
    "ResultDisplayField": {
      "type": "object",
      "description": "Display Fields for Search Results",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "The operator name of the property."
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        },
        "label": {
          "description": "The display label for the property.",
          "type": "string"
        }
      },
      "id": "ResultDisplayField"
    },
    "ResetSearchApplicationRequest": {
      "type": "object",
      "id": "ResetSearchApplicationRequest",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      }
    },
    "GroupLinkSharingModificationEvent": {
      "properties": {
        "newStatus": {
          "enumDescriptions": [
            "",
            "Link sharing is turned on.",
            "Link sharing is turned off.",
            "Link sharing is not available for the conversation."
          ],
          "enum": [
            "UNKNOWN_LINK_SHARING_STATUS",
            "LINK_SHARING_ON",
            "LINK_SHARING_OFF",
            "NOT_AVAILABLE"
          ],
          "type": "string"
        }
      },
      "type": "object",
      "id": "GroupLinkSharingModificationEvent"
    },
    "StoredParticipantId": {
      "id": "StoredParticipantId",
      "type": "object",
      "properties": {
        "gaiaId": {
          "format": "int64",
          "type": "string"
        }
      }
    },
    "GoogleChatV1WidgetMarkupImage": {
      "type": "object",
      "properties": {
        "aspectRatio": {
          "description": "The aspect ratio of this image (width/height). This field allows clients to reserve the right height for the image while waiting for it to load. It's not meant to override the native aspect ratio of the image. If unset, the server fills it by prefetching the image.",
          "type": "number",
          "format": "double"
        },
        "onClick": {
          "description": "The onclick action.",
          "$ref": "GoogleChatV1WidgetMarkupOnClick"
        },
        "imageUrl": {
          "description": "The URL of the image.",
          "type": "string"
        }
      },
      "id": "GoogleChatV1WidgetMarkupImage",
      "description": "An image that is specified by a URL and can have an onclick action."
    },
    "ObjectDefinition": {
      "type": "object",
      "properties": {
        "options": {
          "description": "The optional object-specific options.",
          "$ref": "ObjectOptions"
        },
        "name": {
          "type": "string",
          "description": "The name for the object, which then defines its type. Item indexing requests should set the objectType field equal to this value. For example, if *name* is *Document*, then indexing requests for items of type Document should set objectType equal to *Document*. Each object definition must be uniquely named within a schema. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The maximum length is 256 characters."
        },
        "propertyDefinitions": {
          "type": "array",
          "description": "The property definitions for the object. The maximum number of elements is 1000.",
          "items": {
            "$ref": "PropertyDefinition"
          }
        }
      },
      "description": "The definition for an object within a data source.",
      "id": "ObjectDefinition"
    },
    "ChatConserverDynamitePlaceholderMetadataAttachmentMetadata": {
      "properties": {
        "filename": {
          "type": "string"
        }
      },
      "type": "object",
      "description": "An attachment uploaded in Dynamite and its filename.",
      "id": "ChatConserverDynamitePlaceholderMetadataAttachmentMetadata"
    },
    "ChatConserverDynamitePlaceholderMetadata": {
      "type": "object",
      "description": "Metadata used as inputs to the localization that is performed on Dynamite-originated messages that are incompatible with Hangouts clients. See go/localization-of-system-messages for more details.",
      "id": "ChatConserverDynamitePlaceholderMetadata",
      "properties": {
        "tasksMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataTasksMetadata"
        },
        "botMessageMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataBotMessageMetadata"
        },
        "calendarEventMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataCalendarEventMetadata"
        },
        "spaceUrl": {
          "type": "string",
          "description": "The space URL embedded in the localized string."
        },
        "videoCallMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataVideoCallMetadata"
        },
        "editMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataEditMetadata"
        },
        "deleteMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataDeleteMetadata"
        },
        "attachmentMetadata": {
          "$ref": "ChatConserverDynamitePlaceholderMetadataAttachmentMetadata"
        }
      }
    },
    "ChatConserverDynamitePlaceholderMetadataVideoCallMetadata": {
      "id": "ChatConserverDynamitePlaceholderMetadataVideoCallMetadata",
      "description": "A Meet initiated in Dynamite and its URL.",
      "type": "object",
      "properties": {
        "meetingUrl": {
          "type": "string"
        }
      }
    },
    "Labels": {
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The ids of the labels attached to the Item, e.g. \"^i\", \"^x_1\""
        },
        "displayName": {
          "description": "The display name of the labels. This is populated (instead of the id) when the request fetch_spec has LABEL_DISPLAY_NAMES.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object",
      "id": "Labels"
    },
    "UniversalPhoneAccess": {
      "id": "UniversalPhoneAccess",
      "description": "Universal phone access contains information required to dial into a conference using one of a static list of phone numbers and a universal PIN. The phone number list is distributed separately.",
      "type": "object",
      "properties": {
        "pstnInfoUrl": {
          "description": "This field has the same contents as the MeetingSpace.more_join_url field, and is included for compatibility reasons. Clients should use the other field instead. This field is deprecated and will be removed.",
          "type": "string"
        },
        "pin": {
          "type": "string",
          "description": "The PIN that users must enter after dialing a universal number. The pin consists of only decimal digits and the length may vary, though it generally is longer than a PhoneAccess.pin."
        }
      }
    },
    "AppsDynamiteStorageTextParagraph": {
      "properties": {
        "text": {
          "type": "string",
          "description": "The text that's shown in the widget."
        }
      },
      "id": "AppsDynamiteStorageTextParagraph",
      "description": "A paragraph of text that supports formatting. See [Text formatting](workspace/add-ons/concepts/widgets#text_formatting\") for details.",
      "type": "object"
    },
    "DataSourceRestriction": {
      "properties": {
        "source": {
          "description": "The source of restriction.",
          "$ref": "Source"
        },
        "filterOptions": {
          "type": "array",
          "items": {
            "$ref": "FilterOptions"
          },
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions."
        }
      },
      "type": "object",
      "description": "Restriction on Datasource.",
      "id": "DataSourceRestriction"
    },
    "MenuItem": {
      "id": "MenuItem",
      "type": "object",
      "properties": {
        "value": {
          "type": "string",
          "description": "The value associated with this item which will be sent back to app scripts. Client should use as a form input value."
        },
        "text": {
          "description": "The text to be displayed.",
          "type": "string"
        },
        "selected": {
          "type": "boolean"
        }
      }
    },
    "LdapGroupProto": {
      "id": "LdapGroupProto",
      "type": "object",
      "properties": {
        "groupName": {
          "type": "string"
        }
      }
    },
    "Reference": {
      "properties": {
        "size": {
          "format": "int64",
          "type": "string"
        },
        "key": {
          "type": "string",
          "description": "LINT.IfChange"
        },
        "name": {
          "type": "string",
          "description": "LINT.ThenChange(//depot/google3/storage/slice/production/gmail/ user_data_tables.pi)"
        },
        "blobId": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        },
        "contentType": {
          "type": "string"
        }
      },
      "description": "All fields in this proto are now columns in spanner see google3/storage/slice/production/gmail/user_data_tables.pi for documentation.",
      "id": "Reference",
      "type": "object"
    },
    "FormAction": {
      "id": "FormAction",
      "type": "object",
      "properties": {
        "actionMethodName": {
          "description": "Apps script function that should be invoked in the developer's apps script when the containing element is clicked/activated.",
          "type": "string"
        },
        "persistValues": {
          "description": "Indicates whether form values persist after the action. When false, the Apps Script is responsible for persisting values, by setting any form field values using the formInputs in the event. Disabling this behavior can be used if the add-on needs the ability to clear form fields, for example, as with persistent values, there is no means for clearing existing values. When disabling persistent values, it is strongly recommended that the add-on use LoadIndicator.SPINNER for[...]",
          "type": "boolean"
        },
        "loadIndicator": {
          "enumDescriptions": [
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "SPINNER",
            "NONE"
          ]
        }
      }
    },
    "SourceMessageInfo": {
      "type": "object",
      "properties": {
        "messageId": {
          "description": "Source message ID",
          "$ref": "MessageId"
        },
        "messageType": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "SOURCE_MESSAGE_TYPE_UNDEFINED",
            "ROOT_MESSAGE",
            "INLINE_REPLY"
          ]
        }
      },
      "id": "SourceMessageInfo"
    },
    "GoogleChatV1WidgetMarkupTextParagraph": {
      "id": "GoogleChatV1WidgetMarkupTextParagraph",
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        }
      },
      "description": "A paragraph of text. Formatted text supported. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons."
    },
    "BotInfo": {
      "properties": {
        "supportedUses": {
          "items": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "CAN_ADD_TO_DM",
              "CAN_ADD_TO_ROOM",
              "CAN_ADD_TO_HUMAN_DM"
            ],
            "enumDescriptions": [
              "",
              "",
              "",
              ""
            ]
          },
          "description": "The supported uses are limited according to the user that made the request. If the user does not have permission to use the bot, the list will be empty. This could occur for non whitelisted bots in the catalog.",
          "type": "array"
        },
        "appId": {
          "$ref": "AppId",
          "description": "Identifier of the application associated with the bot."
        },
        "supportHomeScreen": {
          "type": "boolean",
          "description": "If the app supports a home screen."
        },
        "appAllowlistStatus": {
          "enumDescriptions": [
            "",
            "",
            "For both ALL_APPS_DISABLED_BY_ADMIN and APP_NOT_ALLOWLISTED_BY_ADMIN, the app should still be visible in the catalog, but usage of the app will be disabled. Indicates that all apps have been disabled by the dasher admin.",
            "Indicates that the customer is using allowlisting, but that the bot is not allowlisted."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED_STATUS",
            "ALLOWED",
            "ALL_APPS_DISABLED_BY_ADMIN",
            "APP_NOT_ALLOWLISTED_BY_ADMIN"
          ]
        },
        "description": {
          "description": "Short description for the bot.",
          "type": "string"
        },
        "marketPlaceBannerUrl": {
          "type": "string",
          "description": "URL for the banner image in GSuite Market Place. The banner will be 220x140."
        },
        "status": {
          "description": "Indicates whether bot is enabled/disabled.",
          "enumDescriptions": [
            "",
            "",
            "Bot has been disabled by the bot developer. No one can @mention or interact with the bot."
          ],
          "type": "string",
          "enum": [
            "UNKNOWN_STATUS",
            "ENABLED",
            "DISABLED_BY_DEVELOPER"
          ]
        },
        "botName": {
          "description": "Non-unique, user-defined display name of the Bot. This field should be populated if the request is FetchBotCategories/ListBotCatalogEntries.",
          "type": "string"
        },
        "developerName": {
          "description": "Name of bot developer.",
          "type": "string"
        },
        "supportUrls": {
          "$ref": "SupportUrls",
          "description": "Urls with additional information related to the bot. This field should always be set even if all the fields within it are empty, so that it is convenient for clients to work with this field in javascript."
        },
        "botAvatarUrl": {
          "description": "URL for the avatar picture of the User in dynamite. This field should be populated if the request is FetchBotCategories/ListBotCatalogEntries",
          "type": "string"
        }
      },
      "id": "BotInfo",
      "type": "object",
      "description": "Bot-specific profile information."
    },
    "ImageKeyValue": {
      "properties": {
        "icon": {
          "type": "string",
          "enum": [
            "NONE",
            "AIRPLANE",
            "BOOKMARK",
            "BUS",
            "CAR",
            "CLOCK",
            "CONFIRMATION_NUMBER_ICON",
            "DOLLAR",
            "DESCRIPTION",
            "EDIT",
            "EDIT_NOTE",
            "EMAIL",
            "EVENT_PERFORMER",
            "EVENT_SEAT",
            "FLIGHT_ARRIVAL",
            "FLIGHT_DEPARTURE",
            "HOTEL",
            "HOTEL_ROOM_TYPE",
            "INVITE",
            "MAP_PIN",
            "MEMBERSHIP",
            "MULTIPLE_PEOPLE",
            "OFFER",
            "OPEN_IN_NEW",
            "PERSON",
            "PHONE",
            "RESTAURANT_ICON",
            "SHOPPING_CART",
            "STAR",
            "STORE",
            "TICKET",
            "TRAIN",
            "VIDEO_CAMERA",
            "VIDEO_PLAY"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Add new items in alphabetical order. Next Available ID: 34"
          ]
        },
        "onClick": {
          "$ref": "OnClick"
        },
        "iconUrl": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "description": "This is deprecated and please use KeyValue.",
      "type": "object",
      "id": "ImageKeyValue"
    },
    "SafeUrlProto": {
      "type": "object",
      "id": "SafeUrlProto",
      "description": "Message containing a string that is safe to use in URL contexts in DOM APIs and HTML documents, where the URL context does not refer to a resource that loads code.",
      "properties": {
        "privateDoNotAccessOrElseSafeUrlWrappedValue": {
          "type": "string",
          "description": "IMPORTANT: Never set or read this field, even from tests, it is private. See documentation at the top of .proto file for programming language packages with which to create or read this message."
        }
      }
    },
    "CardCapabilityMetadata": {
      "id": "CardCapabilityMetadata",
      "type": "object",
      "properties": {
        "requiredCapabilities": {
          "type": "array",
          "items": {
            "enum": [
              "UNKNOWN",
              "SUPPORTS_BASE_CARDS"
            ],
            "enumDescriptions": [
              "",
              "NEXT TAG : 2"
            ],
            "type": "string"
          },
          "description": "NEXT TAG : 2"
        }
      }
    },
    "AppsDynamiteStorageColumnsColumn": {
      "properties": {
        "widgets": {
          "type": "array",
          "description": "LINT.ThenChange(//depot/google3/google/apps/card/v1/card.proto) Array of widgets included in the column.",
          "items": {
            "$ref": "AppsDynamiteStorageColumnsColumnWidgets"
          }
        },
        "verticalAlignment": {
          "enum": [
            "VERTICAL_ALIGNMENT_UNSPECIFIED",
            "CENTER",
            "TOP",
            "BOTTOM"
          ],
          "enumDescriptions": [
            "Unspecified.",
            "Aligns the widget in the center of the column. Default value if unspecified.",
            "Aligns the widget at the top of the column.",
            "Aligns the widget at the bottom of the column."
          ],
          "type": "string",
          "description": "The vertical alignment of the column."
        },
        "horizontalAlignment": {
          "enum": [
            "HORIZONTAL_ALIGNMENT_UNSPECIFIED",
            "START",
            "CENTER",
            "END"
          ],
          "description": "The horizontal alignment of the column.",
          "enumDescriptions": [
            "Unspecified alignment.",
            "Alignment to the start position.",
            "Alignment to the center position.",
            "Alignment to the end position."
          ],
          "type": "string"
        },
        "horizontalSizeStyle": {
          "type": "string",
          "enumDescriptions": [
            "Unspecified.",
            "Fills up the available horizontal width. Default value if unspecified.",
            "Fills up the minimum horizontal width."
          ],
          "description": "Specifies how the column content is sized horizontally.",
          "enum": [
            "HORIZONTAL_SIZE_STYLE_UNSPECIFIED",
            "FILL_AVAILABLE_SPACE",
            "FILL_MINIMUM_SPACE"
          ]
        }
      },
      "description": "Represents a Column that consists of widgets stacked vertically.",
      "id": "AppsDynamiteStorageColumnsColumn",
      "type": "object"
    },
    "RbacSubjectProto": {
      "properties": {
        "username": {
          "type": "string",
          "description": "Format \"username\" without \"@domain\", e.g., \"bogdand\"."
        }
      },
      "id": "RbacSubjectProto",
      "type": "object",
      "description": "Principal associated with a given RBAC subject. This principal is used by Sphinx Provisioning Service for RBAC provisionable (go/sphinx-rbacz)."
    },
    "AddOnStartingState": {
      "type": "object",
      "id": "AddOnStartingState",
      "description": "Starting state properties for add-on co-activity.",
      "properties": {
        "addOnFrameStartingStates": {
          "additionalProperties": {
            "$ref": "AddOnFrameStartingState"
          },
          "type": "object",
          "description": "List of starting state frames for the add-on co-activity. Keys for this map are the values of the AddOnFrameType enum."
        }
      }
    },
    "QueryInterpretationConfig": {
      "id": "QueryInterpretationConfig",
      "type": "object",
      "description": "Default options to interpret user query.",
      "properties": {
        "forceDisableSupplementalResults": {
          "type": "boolean",
          "description": "Set this flag to disable supplemental results retrieval, setting a flag here will not retrieve supplemental results for queries associated with a given search application. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for supplemental results."
        },
        "forceVerbatimMode": {
          "type": "boolean",
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental results retrieval, and usage of synonyms including custom ones. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for verbatim mode."
        }
      }
    },
    "AppsDynamiteSharedTextSegmentsWithDescription": {
      "description": "Defines text segments with description type associated.",
      "id": "AppsDynamiteSharedTextSegmentsWithDescription",
      "properties": {
        "textSegment": {
          "items": {
            "$ref": "AppsDynamiteSharedTextSegment"
          },
          "type": "array"
        },
        "descriptionType": {
          "enumDescriptions": [
            "",
            "Indicates the text segments contain matched keywords. Client can highlight them in search results page."
          ],
          "type": "string",
          "enum": [
            "DESCRIPTION_TYPE_UNSPECIFIED",
            "KEYWORD_MATCH"
          ]
        }
      },
      "type": "object"
    },
    "RequiredMessageFeaturesMetadata": {
      "type": "object",
      "properties": {
        "requiredFeatures": {
          "type": "array",
          "items": {
            "enum": [
              "REQUIRED_FEATURE_UNSPECIFIED",
              "REQUIRED_FEATURE_MESSAGE_QUOTING",
              "REQUIRED_FEATURE_TOMBSTONES_IN_DMS_AND_UFRS",
              "REQUIRED_FEATURE_CUSTOM_HYPERLINK",
              "REQUIRED_FEATURE_DRIVE_SMART_CHIP",
              "REQUIRED_FEATURE_LEGACY_TOPIC_START"
            ],
            "type": "string",
            "enumDescriptions": [
              "",
              "",
              "",
              "",
              "",
              ""
            ]
          }
        }
      },
      "id": "RequiredMessageFeaturesMetadata",
      "description": "A list of capabilities that are used in this message."
    },
    "SwitchWidget": {
      "type": "object",
      "id": "SwitchWidget",
      "properties": {
        "selected": {
          "type": "boolean"
        },
        "value": {
          "description": "The value is what is passed back in apps script callback.",
          "type": "string"
        },
        "name": {
          "description": "The name of the switch widget which is will be used in FormInput.",
          "type": "string"
        },
        "controlType": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "SWITCH",
            "CHECKBOX"
          ]
        },
        "onChange": {
          "$ref": "FormAction"
        }
      }
    },
    "AppsDynamiteSharedEmoji": {
      "properties": {
        "customEmoji": {
          "$ref": "AppsDynamiteSharedCustomEmoji",
          "description": "A custom emoji."
        },
        "unicode": {
          "description": "A basic emoji represented by a unicode string.",
          "type": "string"
        }
      },
      "id": "AppsDynamiteSharedEmoji",
      "type": "object"
    },
    "EmbedClientItem": {
      "description": "Represents an embedded object in an update. This is a wrapper class that can contain a single specific item proto in an extension field. Think of it as a base class like `Message` in Java. Each item proto must declare that it extends this proto: message ExampleObject { option (item_type) = EXAMPLE_OBJECT; extend EmbedClientItem { optional ExampleObject example_object = ; } } See go/es-embeds for details.",
      "id": "EmbedClientItem",
      "type": "object",
      "properties": {
        "deepLinkData": {
          "$ref": "DeepLinkData",
          "description": "Deep-linking data to take the user to the right place in a mobile app. This is only used for preview and attribution. Links that are specific to a given embed type should live on that specific embed's proto by using Link. See http://goto.google.com/mariana-design."
        },
        "canonicalId": {
          "type": "string",
          "description": "The canonical ID of the embed. If absent, the canonical ID is equal to the ID; if present, then the canonical ID represents an \"equivalence class\" of embeds which really refer to the same object. (For example, the URLs http://www.foo.com/ and http://foo.com/ refer to the same object) This field may be updated periodically by background processes."
        },
        "type": {
          "description": "The first value in `type` determines which extension field will be set. When creating an EmbedClientItem, you only need to set the first (primary) type in this field. When the server receives the item, it will populate the full type list using the parent annotations in the ItemType enum.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "ACTION_V2",
              "ADD_ACTION_V2",
              "AGGREGATE_RATING_V2",
              "ARTICLE_V2",
              "ASSESS_ACTION_V2",
              "AUDIO_OBJECT_V2",
              "BASIC_INTERACTION_V2",
              "BLOG_POSTING_V2",
              "BLOG_V2",
              "BOOK_V2",
              "BUY_ACTION_V2",
              "CHECK_IN_ACTION_V2",
              "CHECKIN_V2",
              "COLLEXION_V2",
              "COMMENT_ACTION_V2",
              "COMMENT_V2",
              "COMMUNICATE_ACTION_V2",
              "CONSUME_ACTION_V2",
              "CREATE_ACTION_V2",
              "CREATIVE_WORK_V2",
              "DISCOVER_ACTION_V2",
              "DOCUMENT_OBJECT_V2",
              "DRAWING_OBJECT_V2",
              "DRIVE_OBJECT_V2",
              "EMOTISHARE_V2",
              "ENTRY_POINT_V2",
              "EVENT_TIME_V2",
              "EVENT_V2",
              "FILE_OBJECT_V2",
              "FIND_ACTION_V2",
              "FINANCIAL_QUOTE_V2",
              "FORM_OBJECT_V2",
              "GEO_COORDINATES_V2",
              "GOOGLE_OFFER_V2",
              "HANGOUT_CHAT_MESSAGE",
              "HANGOUT_QUOTE",
              "HANGOUT_V2",
              "HOA_PLUS_EVENT_V2",
              "IMAGE_OBJECT_V2",
              "INTERACT_ACTION_V2",
              "INTERACTION_V2",
              "LISTEN_ACTION_V2",
              "LOCAL_BUSINESS_V2",
              "LOCAL_PLUS_PHOTO_ALBUM_V2",
              "MAGAZINE_V2",
              "MEDIA_OBJECT_V2",
              "MOBILE_APPLICATION_V2",
              "MOVIE_V2",
              "MUSIC_ALBUM_V2",
              "MUSIC_GROUP_V2",
              "MUSIC_PLAYLIST_V2",
              "MUSIC_RECORDING_V2",
              "NEWS_ARTICLE_V2",
              "OFFER_V2",
              "ORGANIZATION_V2",
              "ORGANIZE_ACTION_V2",
              "PERSON_V2",
              "PLACE_REVIEW_V2",
              "PLACE_V2",
              "PLAN_ACTION_V2",
              "PLAY_MUSIC_ALBUM_V2",
              "PLAY_MUSIC_TRACK_V2",
              "PLAY_OBJECT_V2",
              "PLUS_AUDIO_V2",
              "PLUS_EVENT_V2",
              "PLUS_MEDIA_COLLECTION_V2",
              "PLUS_MEDIA_OBJECT_V2",
              "PLUS_PAGE_V2",
              "PLUS_PHOTOS_ADDED_TO_COLLECTION_V2",
              "PLUS_PHOTO_ALBUM_V2",
              "PLUS_PHOTO_COLLECTION_V2",
              "PLUS_PHOTO_V2",
              "PLUS_POST_V2",
              "PLUS_RESHARE_V2",
              "PLUS_SOFTWARE_APPLICATION_V2",
              "POLL_OPTION_V2",
              "POLL_V2",
              "POSTAL_ADDRESS_V2",
              "PRESENTATION_OBJECT_V2",
              "PRODUCT_REVIEW_V2",
              "RATING_V2",
              "REACT_ACTION_V2",
              "RESERVATION_V2",
              "RESERVE_ACTION_V2",
              "REVIEW_V2",
              "REVIEW_ACTION_V2",
              "SOFTWARE_APPLICATION_V2",
              "SPREADSHEET_OBJECT_V2",
              "SQUARE_INVITE_V2",
              "SQUARE_V2",
              "STICKER_V2",
              "STORY_V2",
              "THING_V2",
              "TRADE_ACTION_V2",
              "DEPRECATED_TOUR_OBJECT_V2",
              "TV_EPISODE_V2",
              "TV_SERIES_V2",
              "UPDATE_ACTION_V2",
              "VIEW_ACTION_V2",
              "VIDEO_OBJECT_V2",
              "VIDEO_GALLERY_V2",
              "WANT_ACTION_V2",
              "WEB_PAGE_V2",
              "WRITE_ACTION_V2",
              "YOUTUBE_CHANNEL_V2",
              "GOOGLE_USER_PHOTO_V2",
              "GOOGLE_USER_PHOTO_ALBUM",
              "GOOGLE_PHOTO_RECIPE",
              "THING",
              "CREATIVE_WORK",
              "EVENT",
              "INTANGIBLE",
              "ORGANIZATION",
              "PERSON",
              "PLACE",
              "PRODUCT",
              "ARTICLE",
              "BLOG_POSTING",
              "NEWS_ARTICLE",
              "SCHOLARLY_ARTICLE",
              "BLOG",
              "BOOK",
              "COMMENT",
              "ITEM_LIST",
              "MAP",
              "MEDIA_OBJECT",
              "AUDIO_OBJECT",
              "IMAGE_OBJECT",
              "MUSIC_VIDEO_OBJECT",
              "VIDEO_OBJECT",
              "MOVIE",
              "MUSIC_PLAYLIST",
              "MUSIC_ALBUM",
              "MUSIC_RECORDING",
              "PAINTING",
              "PHOTOGRAPH",
              "RECIPE",
              "REVIEW",
              "SCULPTURE",
              "SOFTWARE_APPLICATION",
              "MOBILE_APPLICATION",
              "WEB_APPLICATION",
              "TV_EPISODE",
              "TV_SEASON",
              "TV_SERIES",
              "WEB_PAGE",
              "ABOUT_PAGE",
              "CHECKOUT_PAGE",
              "COLLECTION_PAGE",
              "IMAGE_GALLERY",
              "VIDEO_GALLERY",
              "CONTACT_PAGE",
              "ITEM_PAGE",
              "PROFILE_PAGE",
              "SEARCH_RESULTS_PAGE",
              "WEB_PAGE_ELEMENT",
              "SITE_NAVIGATION_ELEMENT",
              "TABLE",
              "WP_AD_BLOCK",
              "WP_FOOTER",
              "WP_HEADER",
              "WP_SIDEBAR",
              "APP_INVITE",
              "EMOTISHARE",
              "BUSINESS_EVENT",
              "CHILDRENS_EVENT",
              "COMEDY_EVENT",
              "DANCE_EVENT",
              "EDUCATION_EVENT",
              "FESTIVAL",
              "FOOD_EVENT",
              "LITERARY_EVENT",
              "MUSIC_EVENT",
              "SALE_EVENT",
              "SOCIAL_EVENT",
              "SPORTS_EVENT",
              "THEATER_EVENT",
              "VISUAL_ARTS_EVENT",
              "RESERVATION",
              "TRAVEL_EVENT",
              "CORPORATION",
              "EDUCATIONAL_ORGANIZATION",
              "COLLEGE_OR_UNIVERSITY",
              "ELEMENTARY_SCHOOL",
              "HIGH_SCHOOL",
              "MIDDLE_SCHOOL",
              "PRESCHOOL",
              "SCHOOL",
              "GOVERNMENT_ORGANIZATION",
              "LOCAL_BUSINESS",
              "ANIMAL_SHELTER",
              "AUTOMOTIVE_BUSINESS",
              "AUTO_BODY_SHOP",
              "AUTO_DEALER",
              "AUTO_PARTS_STORE",
              "AUTO_RENTAL",
              "AUTO_REPAIR",
              "AUTO_WASH",
              "GAS_STATION",
              "MOTORCYCLE_DEALER",
              "MOTORCYCLE_REPAIR",
              "CHILD_CARE",
              "DRY_CLEANING_OR_LAUNDRY",
              "EMERGENCY_SERVICE",
              "FIRE_STATION",
              "HOSPITAL",
              "POLICE_STATION",
              "EMPLOYMENT_AGENGY",
              "ENTERTAINMENT_BUSINESS",
              "ADULT_ENTERTAINMENT",
              "AMUSEMENT_PARK",
              "ART_GALLERY",
              "CASINO",
              "COMEDY_CLUB",
              "MOVIE_THEATER",
              "NIGHT_CLUB",
              "FINANCIAL_SERVICE",
              "ACCOUNTING_SERVICE",
              "AUTOMATED_TELLER",
              "BANK_OR_CREDIT_UNION",
              "INSURANCE_AGENCY",
              "FOOD_ESTABLISHMENT",
              "BAKERY",
              "BAR_OR_PUB",
              "BREWERY",
              "CAFE_OR_COFFEE_SHOP",
              "FAST_FOOD_RESTAURANT",
              "ICE_CREAM_SHOP",
              "RESTAURANT",
              "WINERY",
              "GOVERNMENT_OFFICE",
              "POST_OFFICE",
              "HEALTH_AND_BEAUTY_BUSINESS",
              "BEAUTY_SALON",
              "DAY_SPA",
              "HAIR_SALON",
              "HEALTH_CLUB",
              "NAIL_SALON",
              "TATTOO_PARLOR",
              "HOME_AND_CONSTRUCTION_BUSINESS",
              "ELECTRICIAN",
              "GENERAL_CONTRACTOR",
              "HVAC_BUSINESS",
              "HOUSE_PAINTER",
              "LOCKSMITH",
              "MOVING_COMPANY",
              "PLUMBER",
              "ROOFING_CONTRACTOR",
              "INTERNET_CAFE",
              "LIBRARY",
              "LODGING_BUSINESS",
              "BED_AND_BREAKFAST",
              "HOSTEL",
              "HOTEL",
              "MOTEL",
              "MEDICAL_ORGANIZATION",
              "DENTIST",
              "MEDICAL_CLINIC",
              "OPTICIAN",
              "PHARMACY",
              "PHYSICIAN",
              "VETERINARY_CARE",
              "PROFESSIONAL_SERVICE",
              "ATTORNEY",
              "NOTARY",
              "RADIO_STATION",
              "REAL_ESTATE_AGENT",
              "RECYCLING_CENTER",
              "SELF_STORAGE",
              "SHOPPING_CENTER",
              "SPORTS_ACTIVITY_LOCATION",
              "BOWLING_ALLEY",
              "EXERCISE_GYM",
              "GOLF_COURSE",
              "PUBLIC_SWIMMING_POOL",
              "SKI_RESORT",
              "SPORTS_CLUB",
              "STADIUM_OR_ARENA",
              "TENNIS_COMPLEX",
              "STORE",
              "BIKE_STORE",
              "BOOK_STORE",
              "CLOTHING_STORE",
              "COMPUTER_STORE",
              "CONVENIENCE_STORE",
              "DEPARTMENT_STORE",
              "ELECTRONICS_STORE",
              "FLORIST",
              "FURNITURE_STORE",
              "GARDEN_STORE",
              "GROCERY_STORE",
              "HARDWARE_STORE",
              "HOBBY_SHOP",
              "HOME_GOODS_STORE",
              "JEWELRY_STORE",
              "LIQUOR_STORE",
              "MENS_CLOTHING_STORE",
              "MOBILE_PHONE_STORE",
              "MOVIE_RENTAL_STORE",
              "MUSIC_STORE",
              "OFFICE_EQUIPMENT_STORE",
              "OUTLET_STORE",
              "PAWN_SHOP",
              "PET_STORE",
              "SHOE_STORE",
              "SPORTING_GOODS_STORE",
              "TIRE_SHOP",
              "TOY_STORE",
              "WHOLESALE_STORE",
              "TELEVISION_STATION",
              "TOURIST_INFORMATION_CENTER",
              "TRAVEL_AGENCY",
              "PERFORMING_GROUP",
              "MUSIC_GROUP",
              "ADMINISTRATIVE_AREA",
              "CITY",
              "COUNTRY",
              "STATE",
              "CIVIC_STRUCTURE",
              "AIRPORT",
              "AQUARIUM",
              "BEACH",
              "BUS_STATION",
              "BUS_STOP",
              "CAMPGROUND",
              "CEMETERY",
              "CREMATORIUM",
              "EVENT_VENUE",
              "GOVERNMENT_BUILDING",
              "CITY_HALL",
              "COURTHOUSE",
              "DEFENCE_ESTABLISHMENT",
              "EMBASSY",
              "LEGISLATIVE_BUILDING",
              "MUSEUM",
              "MUSIC_VENUE",
              "PARK",
              "PARKING_FACILITY",
              "PERFORMING_ARTS_THEATER",
              "PLACE_OF_WORSHIP",
              "BUDDHIST_TEMPLE",
              "CATHOLIC_CHURCH",
              "CHURCH",
              "HINDU_TEMPLE",
              "MOSQUE",
              "SYNAGOGUE",
              "PLAYGROUND",
              "R_V_PARK",
              "RESIDENCE",
              "APARTMENT_COMPLEX",
              "GATED_RESIDENCE_COMMUNITY",
              "SINGLE_FAMILY_RESIDENCE",
              "TOURIST_ATTRACTION",
              "SUBWAY_STATION",
              "TAXI_STAND",
              "TRAIN_STATION",
              "ZOO",
              "LANDFORM",
              "BODY_OF_WATER",
              "CANAL",
              "LAKE_BODY_OF_WATER",
              "OCEAN_BODY_OF_WATER",
              "POND",
              "RESERVOIR",
              "RIVER_BODY_OF_WATER",
              "SEA_BODY_OF_WATER",
              "WATERFALL",
              "CONTINENT",
              "MOUNTAIN",
              "VOLCANO",
              "LANDMARKS_OR_HISTORICAL_BUILDINGS",
              "USER_INTERACTION",
              "USER_PLUS_ONES",
              "ENUMERATION",
              "BOOK_FORMAT_TYPE",
              "ITEM_AVAILABILITY",
              "OFFER_ITEM_CONDITION",
              "JOB_POSTING",
              "LANGUAGE",
              "OFFER",
              "QUANTITY",
              "DISTANCE",
              "DURATION",
              "ENERGY",
              "MASS",
              "RATING",
              "AGGREGATE_RATING",
              "STRUCTURED_VALUE",
              "CONTACT_POINT",
              "POSTAL_ADDRESS",
              "GEO_COORDINATES",
              "GEO_SHAPE",
              "NUTRITION_INFORMATION",
              "PRESENTATION_OBJECT",
              "DOCUMENT_OBJECT",
              "SPREADSHEET_OBJECT",
              "FORM_OBJECT",
              "DRAWING_OBJECT",
              "PLACE_REVIEW",
              "FILE_OBJECT",
              "PLAY_MUSIC_TRACK",
              "PLAY_MUSIC_ALBUM",
              "MAGAZINE",
              "CAROUSEL_FRAME",
              "PLUS_EVENT",
              "HANGOUT",
              "HANGOUT_BROADCAST",
              "HANGOUT_CONSUMER",
              "CHECKIN",
              "EXAMPLE_OBJECT",
              "SQUARE",
              "SQUARE_INVITE",
              "PLUS_PHOTO",
              "PLUS_PHOTO_ALBUM",
              "LOCAL_PLUS_PHOTO_ALBUM",
              "PRODUCT_REVIEW",
              "FINANCIAL_QUOTE",
              "DEPRECATED_TOUR_OBJECT",
              "PLUS_PAGE",
              "GOOGLE_CHART",
              "PLUS_PHOTOS_ADDED_TO_COLLECTION",
              "RECOMMENDED_PEOPLE",
              "PLUS_POST",
              "DATE",
              "DRIVE_OBJECT_COLLECTION",
              "NEWS_MEDIA_ORGANIZATION",
              "DYNAMITE_ATTACHMENT_METADATA",
              "DYNAMITE_MESSAGE_METADATA"
            ],
            "enumDescriptions": [
              "Largely deprecated, effectively an error condition and should not be in storage.",
              "Embeds V2 types",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "The action of checking in, as opposed to a \"check-in\".",
              "",
              "",
              "The act of commenting, which might result in a comment.",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "Boswell story (see goto/boswell)",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "A photo stored in photo service owned by a Google account user. This is distinct from PlusPhoto as it isn't tied to GPlus, but is instead intended to be a more general photo tied to a google user.",
              "A photo album in photo service owned by a Google account user. This is distinct from PlusPhotoAlbum as it isn't tied to GPlus, but is instead intended to be a general photo album tied to a google user.",
              "An embed used to create a single photo in photo service. This type is never stored but is used to create a GOOGLE_USER_PHOTO_V2 or PLUS_PHOTO_V2 embed.",
              "Embeds V1 types",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "CREATIVE_WORK subtypes",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "EVENT subtypes",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "ORGANIZATION subtypes",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "PLACE subtypes",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "NOTE(jpanzer): This is a badly designed hierarchy and we should avoid depending on Event properties inside UserInteractions as much as possible IMHO.",
              "",
              "Intangibles, primarily used as sub-objects of other types",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "CREATIVE_WORK extensions",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "Single frame for http://goto/carousel.",
              "EVENT extensions",
              "No declared proto. Used only as a base type for now.",
              "",
              "",
              "",
              "",
              "NOTE(melchang): These correspond to http://schema.org/WebPage/Community and http://schema.org/WebPage/CommunityInvite. See b/7653610 for why these are \"SQUARE\" and not \"COMMUNITY\".",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "Data visualizations. See http://code.google.com/apis/chart/index.html",
              "",
              "A collection of people that have been recommended to a user.",
              "A Google+ post.",
              "An http://schema.org/Date unstructured ISO-8859 timestamp string.",
              "Embed representing a collection of multiple Drive objects.",
              "https://schema.org/NewsMediaOrganization",
              "Deprecated in favor of DYNAMITE_MESSAGE_METADATA",
              "Used for Dynamite message metadata in Hangouts"
            ]
          }
        },
        "renderId": {
          "description": "The ID used to identify the embed during rendering. This field will match ID, if set, otherwise it will be the ID of the parent activity. This field is only populated on the server for client use and is not persisted to storage.",
          "type": "string"
        },
        "transientData": {
          "description": "Transient generic data that will not be saved on the server.",
          "$ref": "TransientData"
        },
        "id": {
          "description": "The ID of the embed. This corresponds to the schema.org ID, as represented in the ItemScope.id field.",
          "type": "string"
        },
        "provenance": {
          "description": "The provenance of the embed, populated when the embed originated from a web fetch. The provenance captures information about the web page the embed had originated, like the URL that was retrieved and the retrieved URL's canonical form. This is useful in the case where the URL shared by the URL redirects (e.g., in the case of a shortened URL).",
          "$ref": "Provenance"
        },
        "signature": {
          "description": "Signature of the embed, used for verification.",
          "type": "string"
        }
      }
    },
    "FieldViolation": {
      "type": "object",
      "id": "FieldViolation",
      "properties": {
        "description": {
          "description": "The description of the error.",
          "type": "string"
        },
        "field": {
          "type": "string",
          "description": "Path of field with violation."
        }
      }
    },
    "PrefUpdate": {
      "properties": {
        "prefWritten": {
          "$ref": "PrefWritten"
        },
        "prefDeleted": {
          "$ref": "PrefDeleted"
        },
        "preState": {
          "$ref": "FuseboxPrefUpdatePreState"
        },
        "name": {
          "description": "Name of the affected preference.",
          "type": "string"
        }
      },
      "description": "HistoryRecord for changes associated with prefs, namely: PREF_WRITTEN PREF_DELETED",
      "type": "object",
      "id": "PrefUpdate"
    },
    "ItemCountByStatus": {
      "properties": {
        "statusCode": {
          "description": "Status of the items.",
          "type": "string",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "count": {
          "description": "Number of items matching the status code.",
          "type": "string",
          "format": "int64"
        },
        "indexedItemsCount": {
          "type": "string",
          "format": "int64",
          "description": "Number of items matching the status code for which billing is done. This excludes virtual container items from the total count. This count would not be applicable for items with ERROR or NEW_ITEM status code."
        }
      },
      "id": "ItemCountByStatus",
      "type": "object"
    },
    "MeetingSpace": {
      "id": "MeetingSpace",
      "description": " A meeting space is a persistent object that is the context for one or more calls. The meeting space is what makes users find each other when they want to meet and to find shared resources. With two exceptions, all the fields in the meeting space resource are visible publicly to any client, even anonymous users. The exceptions are that * The call_info field is only visible to clients that have a device (as indicated by the meeting token) in the JOINED or HIDDEN state. * The[...]",
      "type": "object",
      "properties": {
        "meetingUrl": {
          "type": "string",
          "description": "A URL to identify and access the meeting space. Output only."
        },
        "meetingSpaceId": {
          "description": "A unique server-generated ID for the meeting space. This is the resource name of the meeting space resource and has the form `spaces/`, where is a sequence of characters in the [base64url set](https://tools.ietf.org/html/rfc4648#section-5), without any `=` characters.",
          "type": "string"
        },
        "universalPhoneAccess": {
          "description": "A universal phone access method for this meeting space. Can be unset.",
          "$ref": "UniversalPhoneAccess"
        },
        "gatewaySipAccess": {
          "items": {
            "$ref": "GatewaySipAccess"
          },
          "description": "The SIP based access methods that can be used to join the conference.",
          "type": "array"
        },
        "moreJoinUrl": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. A URL that clients (e.g. Calendar) can use to show the web page with all join methods available for this meeting space. This link is also used in iOS universal links and Android intents, used for opening the \"More ways to join\" view in the Meet mobile apps. Example: https://tel.meet/mee-ting-cod?pin=1234567891011 Here, \"pin\" is the universal phone PIN. We include it explicitly to better support the offline case on the mobile. This is set when the meetin[...]"
        },
        "settings": {
          "description": "Settings of the meeting space.",
          "$ref": "Settings"
        },
        "meetingAlias": {
          "description": "An optional alias for the meeting space. The alias can in some cases be resolved to the meeting space, similar to the meeting code. The limitation is that the user needs to be in the same meeting domain as the meeting space.",
          "type": "string"
        },
        "callInfo": {
          "$ref": "CallInfo",
          "description": "Information relevant to an ongoing conference. This field will be set in responses if the client requesting the meeting space has a device in one of the JOINED, HIDDEN, or MISSING_PREREQUISITES states. The field will also be set without a created device if the client requesting the meeting space is eligible to directly create a device in the JOINED state without knocking, eg a same-domain joiner. Can also only be updated by clients with a device in the JOINED state."
        },
        "acceptedNumberClass": {
          "description": "Which number classes are accepted by this meeting at the moment? When there is no ongoing conference, this field may change independent of the version number of the MeetingSpace. When a conference starts, this field will be locked to the value at that time, and then will be unlocked again at the end of the conference.",
          "items": {
            "enum": [
              "NUMBER_CLASS_UNSPECIFIED",
              "LOW_COST",
              "HIGH_COST",
              "LEGACY"
            ],
            "type": "string",
            "enumDescriptions": [
              "No number class has been specified.",
              "The number has a low cost to receive calls on.",
              "The number has a high cost to receive calls on.",
              "Class for legacy numbers."
            ]
          },
          "type": "array"
        },
        "gatewayAccess": {
          "$ref": "GatewayAccess",
          "description": "The interop gateway access information for the meeting space. A gateway access can be used when joining conferences from non-Google equipment through an interop gateway."
        },
        "meetingCode": {
          "type": "string",
          "description": "A meeting code is a globally unique code which points to a meeting space. Note: Meeting codes may be regenerated, which will cause old meeting codes to become invalid."
        },
        "broadcastAccess": {
          "$ref": "BroadcastAccess",
          "description": "Broadcast access information for this meeting space."
        },
        "phoneAccess": {
          "type": "array",
          "description": "All regional phone access methods for this meeting space. Can be empty.",
          "items": {
            "$ref": "PhoneAccess"
          }
        }
      }
    },
    "AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkup": {
      "type": "object",
      "properties": {
        "addonAttachments": {
          "type": "array",
          "items": {
            "$ref": "AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkupAddonAttachment"
          }
        }
      },
      "id": "AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkup"
    },
    "AppId": {
      "properties": {
        "appType": {
          "enumDescriptions": [
            "",
            "3P APP eg. external Bots(Asana Bot), 1P Bots(Drive Bot).",
            "1P APP eg. Tasks, Meet, Docs, Calendar..",
            "Asynchronous messages via an incoming webhook."
          ],
          "enum": [
            "APP_TYPE_UNSPECIFIED",
            "APP",
            "GSUITE_APP",
            "INCOMING_WEBHOOK"
          ],
          "type": "string",
          "description": "Enum indicating the type of App this is."
        },
        "id": {
          "format": "int64",
          "type": "string",
          "description": "Numeric identifier of the App. Set to Project number for 1/3P Apps. For Webhook, this is WebhookId. Determined & set by the 1P API from App credentials on the side channel."
        },
        "gsuiteAppType": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Powered by Bullseye",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "GSUITE_APP_TYPE_UNSPECIFIED",
            "TASKS_APP",
            "CALENDAR_APP",
            "DOCS_APP",
            "SHEETS_APP",
            "SLIDES_APP",
            "MEET_APP",
            "ASSISTIVE_SUGGESTION_APP",
            "CONTACTS_APP",
            "ACTIVITY_FEED_APP",
            "DRIVE_APP",
            "CHAT_IN_MEET_APP",
            "SHORTCUT_APP"
          ],
          "description": "Enum indicating which 1P App this is when app_type is GSUITE_APP. Determined & set by the 1P API as a convenience for all users of this identifier(Eg. clients, chime, backend etc.) to map to 1P properties.",
          "type": "string"
        }
      },
      "description": "Identifier of an App.",
      "id": "AppId",
      "type": "object"
    },
    "AppsDynamiteStorageAction": {
      "type": "object",
      "properties": {
        "interaction": {
          "enumDescriptions": [
            "Default value if interaction is not specified.",
            "A dialog opens by clicking the button."
          ],
          "type": "string",
          "enum": [
            "INTERACTION_UNSPECIFIED",
            "OPEN_DIALOG"
          ]
        },
        "loadIndicator": {
          "type": "string",
          "enum": [
            "SPINNER",
            "NONE"
          ],
          "enumDescriptions": [
            "Displays a spinner to indicate that content is loading.",
            "Nothing is displayed."
          ]
        },
        "persistValues": {
          "type": "boolean",
          "description": "Indicates whether form values persist after the action. The default value is `false`. If `true`, form values remain after the action is triggered. When using [LoadIndicator.NONE](workspace/add-ons/reference/rpc/google.apps.card.v1#loadindicator) for actions, `persist_values` = `true`is recommended, as it ensures that any changes made by the user after form or on change actions are sent to the server are not overwritten by the response. If `false`, the form values are cl[...]"
        },
        "function": {
          "description": "Apps Script function to invoke when the containing element is clicked/activated.",
          "type": "string"
        }
      },
      "id": "AppsDynamiteStorageAction",
      "description": "An action that describes the behavior when the form is submitted. For example, an Apps Script can be invoked to handle the form."
    },
    "MembershipChangedMetadata": {
      "description": "Annotation metadata to display system messages for membership changes. Next Tag: 8",
      "properties": {
        "affectedMemberProfiles": {
          "items": {
            "$ref": "Member"
          },
          "type": "array"
        },
        "initiator": {
          "description": "The user whose action triggered this system message.",
          "$ref": "UserId"
        },
        "affectedMemberships": {
          "type": "array",
          "items": {
            "$ref": "AffectedMembership"
          }
        },
        "initiatorType": {
          "type": "string",
          "enum": [
            "INITIATOR_TYPE_UNSPECIFIED",
            "INITIATOR_TYPE_END_USER",
            "INITIATOR_TYPE_ADMIN"
          ],
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "description": "The type of the user who initiated this membership change."
        },
        "type": {
          "enumDescriptions": [
            "Default value for the enum. DO NOT USE.",
            "Non-member -\u003e Can join. Multiple groups and users.",
            "Can join -\u003e Member. One user.",
            "Non-member -\u003e Member. Multiple users.",
            "Can join -\u003e Non-member. One group or user.",
            "Member -\u003e Can join. One user.",
            "Bot added to the room.",
            "Bot removed from the room.",
            "This signifies the user is kicked because the user's OTR policy is conflicted with the room history settings. Joined -\u003e Non-member. One user.",
            "MembershipRole changed. Multiple users.",
            "The room is now joinable by an",
            "Space limit exceeded"
          ],
          "type": "string",
          "enum": [
            "TYPE_UNSPECIFIED",
            "INVITED",
            "JOINED",
            "ADDED",
            "REMOVED",
            "LEFT",
            "BOT_ADDED",
            "BOT_REMOVED",
            "KICKED_DUE_TO_OTR_CONFLICT",
            "ROLE_UPDATED",
            "ROLE_TARGET_AUDIENCE_UPDATED",
            "SPACE_LIMIT_EXCEEDED"
          ]
        },
        "affectedMembers": {
          "type": "array",
          "description": "List of users and rosters whose membership status changed.",
          "items": {
            "$ref": "MemberId"
          }
        },
        "initiatorProfile": {
          "description": "Complete member profiles, when ListTopicsRequest FetchOptions.USER is set. Otherwise, only the id will be filled in.",
          "$ref": "User"
        }
      },
      "id": "MembershipChangedMetadata",
      "type": "object"
    },
    "AppsDynamiteStorageGridGridItem": {
      "id": "AppsDynamiteStorageGridGridItem",
      "description": "Represents a single item in the grid layout.",
      "properties": {
        "image": {
          "$ref": "AppsDynamiteStorageImageComponent",
          "description": "The image that displays in the grid item."
        },
        "title": {
          "description": "The grid item's title.",
          "type": "string"
        },
        "layout": {
          "description": "The layout to use for the grid item.",
          "enum": [
            "GRID_ITEM_LAYOUT_UNSPECIFIED",
            "TEXT_BELOW",
            "TEXT_ABOVE"
          ],
          "enumDescriptions": [
            "No layout specified.",
            "The title and subtitle are shown below the grid item's image.",
            "The title and subtitle are shown above the grid item's image."
          ],
          "type": "string"
        },
        "textAlignment": {
          "type": "string",
          "enumDescriptions": [
            "Unspecified alignment.",
            "Alignment to the start position.",
            "Alignment to the center position.",
            "Alignment to the end position."
          ],
          "description": "The horizontal alignment of the grid item's text.",
          "enum": [
            "HORIZONTAL_ALIGNMENT_UNSPECIFIED",
            "START",
            "CENTER",
            "END"
          ]
        },
        "id": {
          "description": "A user-specified identifier for this grid item. This identifier is returned in the parent Grid's onClick callback parameters.",
          "type": "string"
        },
        "subtitle": {
          "description": "The grid item's subtitle.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "AppsDynamiteSharedTasksAnnotationDataCompletionChange": {
      "properties": {},
      "type": "object",
      "id": "AppsDynamiteSharedTasksAnnotationDataCompletionChange"
    },
    "DeleteQueueItemsRequest": {
      "properties": {
        "queue": {
          "description": "The name of a queue to delete items from.",
          "type": "string"
        },
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "id": "DeleteQueueItemsRequest",
      "type": "object"
    },
    "BroadcastStats": {
      "properties": {
        "estimatedViewerCount": {
          "type": "string",
          "format": "int64",
          "description": "Estimated concurrent viewer count."
        }
      },
      "type": "object",
      "description": "Statistics of the broadcast session.",
      "id": "BroadcastStats"
    },
    "ShareScope": {
      "properties": {
        "domain": {
          "type": "string",
          "description": "If scope is DOMAIN, this field contains the dasher domain, for example \"google.com\"."
        },
        "scope": {
          "type": "string",
          "enumDescriptions": [
            "",
            "Only the author can view the post.",
            "Viewable only by a set of people.",
            "Viewable by extended circles.",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "PRIVATE",
            "LIMITED",
            "EXTENDED",
            "DASHER_DOMAIN",
            "PUBLIC"
          ],
          "description": "The scope to which the content was shared."
        }
      },
      "id": "ShareScope",
      "type": "object"
    },
    "IconImage": {
      "type": "object",
      "properties": {
        "iconUrl": {
          "type": "string"
        },
        "altText": {
          "type": "string",
          "description": "The alternative text of this icon_url which will be used for accessibility."
        },
        "imageStyle": {
          "enumDescriptions": [
            "No value specified.",
            "Applies a square crop.",
            "Applies a circular crop.",
            "Applies a rectangular crop with a custom aspect ratio.",
            "Applies a rectangular crop with a 4:3 aspect ratio."
          ],
          "enum": [
            "CROP_TYPE_NOT_SET",
            "SQUARE",
            "CIRCLE",
            "RECTANGLE_CUSTOM",
            "RECTANGLE_4_3"
          ],
          "description": "The image cropping style. Note that icons with a CIRCLE style are rendered larger than the default icon size.",
          "type": "string"
        },
        "icon": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Add new items in alphabetical order. Next Available ID: 34"
          ],
          "enum": [
            "NONE",
            "AIRPLANE",
            "BOOKMARK",
            "BUS",
            "CAR",
            "CLOCK",
            "CONFIRMATION_NUMBER_ICON",
            "DOLLAR",
            "DESCRIPTION",
            "EDIT",
            "EDIT_NOTE",
            "EMAIL",
            "EVENT_PERFORMER",
            "EVENT_SEAT",
            "FLIGHT_ARRIVAL",
            "FLIGHT_DEPARTURE",
            "HOTEL",
            "HOTEL_ROOM_TYPE",
            "INVITE",
            "MAP_PIN",
            "MEMBERSHIP",
            "MULTIPLE_PEOPLE",
            "OFFER",
            "OPEN_IN_NEW",
            "PERSON",
            "PHONE",
            "RESTAURANT_ICON",
            "SHOPPING_CART",
            "STAR",
            "STORE",
            "TICKET",
            "TRAIN",
            "VIDEO_CAMERA",
            "VIDEO_PLAY"
          ]
        }
      },
      "id": "IconImage"
    },
    "DriveTimeSpanRestrict": {
      "id": "DriveTimeSpanRestrict",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ]
        }
      },
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
    },
    "ClientContext": {
      "description": "Represents the context of the client on behalf of which a HistoryRecord is produced. The ClientContext message can be used to hold context about the service client (e.g. the internal server making fusebox requests) or the user client (e.g. the IP address of the end user).",
      "id": "ClientContext",
      "type": "object",
      "properties": {
        "userIp": {
          "description": "Textual representation of the user's IP address, if available.",
          "type": "string"
        },
        "sessionContext": {
          "$ref": "SessionContext",
          "description": "Contains information about the session which created this history record. This will be empty if the history record was generated by an internal request."
        },
        "clientOperationId": {
          "type": "string",
          "description": "The client operation to which this history record belongs. The notion of a client operation is provided to keep track of client operations which might span multiple transactions in the lower level."
        },
        "clientType": {
          "description": "E.g. \"pinto\", \"imap\", \"bigtop\", \"upload\"",
          "type": "string"
        }
      }
    },
    "ItemStatus": {
      "description": "This contains item's status and any errors.",
      "id": "ItemStatus",
      "type": "object",
      "properties": {
        "processingErrors": {
          "description": "Error details in case the item is in ERROR state.",
          "type": "array",
          "items": {
            "$ref": "ProcessingError"
          }
        },
        "code": {
          "type": "string",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status code.",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "repositoryErrors": {
          "type": "array",
          "description": "Repository error reported by connector.",
          "items": {
            "$ref": "RepositoryError"
          }
        }
      }
    },
    "UserInfo": {
      "id": "UserInfo",
      "description": "Contains info regarding the updater of an Activity Feed item. Next Id: 8",
      "properties": {
        "updaterToShowEmail": {
          "type": "string",
          "description": "The email of the updater for clients to show used for Gmail items. For Drive Notifications, this is the email of the user who triggered the Drive Notification email. This field will be populated if we can extract such information from the Drive Notification email. This is not the actual sender of the email, as the sender is always comments-noreply@docs.google.com."
        },
        "driveNotificationAvatarUrl": {
          "type": "string",
          "description": "Avatar url of the user who triggered the Drive Notification email. This field will be populated if we can extract such information from the Drive Notification email. This should only be used to fetch user avatars when updater_to_show_email is not populated. This field is not set for non-Drive Notification items."
        },
        "updaterCountDisplayType": {
          "enum": [
            "UPDATER_COUNT_DISPLAY_TYPE_UNSPECIFIED",
            "NO_DISPLAY_COUNT",
            "EXACT_COUNT",
            "NONZERO_COUNT"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "No additional updaters where involved. Shows up in clients as \"$USERNAME replied\".",
            "A precise updater count is known and the value set in updater_count_to_show should be used. If set, updater_count_to_show is set to the total number of updaters minus the one set in updater_to_show. Shows up in clients as \"$USERNAME and $NUM others replied\".",
            "A precise updater count could not be calculated, but there is at least one. Any value set in updater_count_to_show should NOT be used. Shows up in clients as \"$USERNAME and others replied\"."
          ],
          "description": "Describes how updater_count_to_show should be used."
        },
        "updaterCountToShow": {
          "format": "int32",
          "type": "integer",
          "description": "The number of updaters for clients to show depending on UpdaterCountDisplayType."
        },
        "updaterToShowGaiaId": {
          "type": "string",
          "format": "int64",
          "description": "The gaia id of the updater for clients to show used for Gmail items. If the updater is an external user, the email field below should be populated."
        },
        "updaterToShowName": {
          "description": "The display name of the updater for clients to show used for Gmail items. For non-Drive Notification items, this field will always be populated. If the display name cannot be found for the user, the fallback string will be the email address. For Drive Notification items, this is the name of the user who triggered the Drive notification email. This field will be populated if we can extract such information from the Drive Notification email. If the name cannot be extracte[...]",
          "type": "string"
        },
        "updaterToShowUserId": {
          "$ref": "UserId",
          "description": "The updater for clients to show used for Dynamite Chat items."
        }
      },
      "type": "object"
    },
    "RoomUpdatedMetadata": {
      "type": "object",
      "id": "RoomUpdatedMetadata",
      "properties": {
        "groupLinkSharingEnabled": {
          "type": "boolean"
        },
        "initiatorType": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "description": "The type of the user who initiated this room update.",
          "type": "string",
          "enum": [
            "INITIATOR_TYPE_UNSPECIFIED",
            "INITIATOR_TYPE_END_USER",
            "INITIATOR_TYPE_ADMIN"
          ]
        },
        "renameMetadata": {
          "$ref": "RoomRenameMetadata"
        },
        "name": {
          "description": "What was updated in the room.",
          "type": "string"
        },
        "visibility": {
          "$ref": "AppsDynamiteSharedGroupVisibility",
          "description": "DEPRECATED: See GroupVisibility proto definition."
        },
        "initiator": {
          "$ref": "User",
          "description": "The user who initiated this room update. Complete member profiles, when ListTopicsRequest FetchOptions.USER is set. Otherwise, only the id will be filled in."
        },
        "groupDetailsMetadata": {
          "$ref": "GroupDetailsUpdatedMetadata"
        }
      }
    },
    "DeliveryMedium": {
      "id": "DeliveryMedium",
      "properties": {
        "mediumType": {
          "enum": [
            "UNKNOWN_MEDIUM",
            "BABEL_MEDIUM",
            "GOOGLE_VOICE_MEDIUM",
            "LOCAL_SMS_MEDIUM"
          ],
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "description": "Describes the medium the cent was sent/received. For example, if I receive an SMS via GV, the medium_type will be GV.",
          "type": "string"
        },
        "selfPhone": {
          "description": "In the case of multiple GV/native numbers, this defines the exact number to send from. It is used to differentiate mediums that have the same type, but different addresses (e.g. two android phones).",
          "$ref": "VoicePhoneNumber"
        }
      },
      "type": "object"
    },
    "AppsDynamiteSharedTextWithDescription": {
      "type": "object",
      "description": "Defines a text with descriptive text segments associated.",
      "properties": {
        "textBody": {
          "type": "string"
        },
        "textSegmentsWithDescription": {
          "type": "array",
          "items": {
            "$ref": "AppsDynamiteSharedTextSegmentsWithDescription"
          }
        }
      },
      "id": "AppsDynamiteSharedTextWithDescription"
    },
    "AppsDynamiteV1ApiCompatV1Action": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "description": "User-facing label for the action."
        },
        "style": {
          "description": "Button style (\"default\", \"primary\", or \"danger\").",
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Unique identifier for this action."
        },
        "value": {
          "description": "Payload for this action. Will be sent to the action handler along with name.",
          "type": "string"
        },
        "confirm": {
          "description": "Confirmation dialog config.",
          "$ref": "AppsDynamiteV1ApiCompatV1ActionConfirm"
        },
        "type": {
          "description": "Action type - currently only \"button\".",
          "type": "string"
        }
      },
      "id": "AppsDynamiteV1ApiCompatV1Action",
      "description": "Interactive objects inside a message. Documentation: - https://api.slack.com/docs/message-buttons"
    },
    "DisplayedProperty": {
      "type": "object",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema.",
          "type": "string"
        }
      },
      "id": "DisplayedProperty",
      "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown."
    },
    "InteractionData": {
      "type": "object",
      "properties": {
        "url": {
          "$ref": "SafeUrlProto",
          "description": "A general navigation target associated with the annotation this message is contained in. For smart chips, this will be the destination of the tap/click target and will be returned by the server. For scenarios where the chip originated from a user-provided url, this value will be provided by clients; otherwise it will be built by the corresponding metadata parts."
        }
      },
      "description": "Interaction data for an annotation, which may be supplemental to the metadata oneof. For example, this will contain the fully built navigation target for smart chips. NEXT TAG: 2",
      "id": "InteractionData"
    },
    "EmailOwnerProto": {
      "description": "Represents a verified owner of the given email address. Note that a single address may have many owners, and a single user may own many addresses. (All lower-case, in display form -- see com.google.gaia.client.GaiaEmail)",
      "properties": {
        "email": {
          "type": "string"
        }
      },
      "type": "object",
      "id": "EmailOwnerProto"
    },
    "SearchApplicationSessionStats": {
      "type": "object",
      "id": "SearchApplicationSessionStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned."
        },
        "searchSessionsCount": {
          "format": "int64",
          "description": "The count of search sessions on the day",
          "type": "string"
        }
      }
    },
    "UserId": {
      "type": "object",
      "description": "Primary key for User resource.",
      "properties": {
        "type": {
          "description": "Clients do not need to send UserType to Backend, but Backend will always send this field to clients per the following rule: 1. For HUMAN Ids, the field is empty but by default .getType() will return HUMAN. 2. For BOT Ids, the field is ALWAYS set to BOT.",
          "type": "string",
          "enumDescriptions": [
            "Notes on HUMAN type: 1) Leaving UserId.UserType field empty will return HUMAN as default value. This is expected because all the existing UserIds are without explicitly setting UserType, most of which are HUMAN Ids. For Bot Ids we will always set BOT in UserType field. 2) DO NOT explicitly set HUMAN as type. This is a proto2 issue, that a UserId with explicitly set default value HUMAN as type is NOT equal to an id without setting the field. aka. UserId id1 = UserId.newBuilder() .set[...]",
            ""
          ],
          "enum": [
            "HUMAN",
            "BOT"
          ]
        },
        "id": {
          "type": "string",
          "description": "Opaque, server-assigned ID of the User."
        },
        "actingUserId": {
          "type": "string",
          "description": "Optional. Opaque, server-assigned ID of the user profile associated with App/user acting on behalf of the human user. This is currently only set when a 3P application is acting on the user's behalf."
        },
        "originAppId": {
          "description": "Optional. Identifier of the App involved (directly or on behalf of a human creator) in creating this message. This is not set if the user posted a message directly, but is used in the case of, for example, a message being generated by a 1P integration based on a user action (creating an event, creating a task etc). This should only be used on the BE. For clients, please use the field in the FE message proto instead (google3/apps/dynamite/v1/frontend/api/message.proto?q=[...]",
          "$ref": "AppId"
        }
      },
      "id": "UserId"
    },
    "ZwiebackSessionProto": {
      "type": "object",
      "id": "ZwiebackSessionProto",
      "properties": {
        "zwiebackSessionId": {
          "format": "uint64",
          "type": "string"
        }
      },
      "description": "See go/zwieback. New uses of Zwieback sessions must be approved via go/zwieback-request."
    },
    "AppsDynamiteSharedOrganizationInfo": {
      "properties": {
        "customerInfo": {
          "$ref": "AppsDynamiteSharedOrganizationInfoCustomerInfo"
        },
        "consumerInfo": {
          "$ref": "AppsDynamiteSharedOrganizationInfoConsumerInfo"
        }
      },
      "description": "Contains info about the entity that something is, or is owned by.",
      "type": "object",
      "id": "AppsDynamiteSharedOrganizationInfo"
    },
    "CheckAccessResponse": {
      "id": "CheckAccessResponse",
      "type": "object",
      "properties": {
        "hasAccess": {
          "description": "Returns true if principal has access. Returns false otherwise.",
          "type": "boolean"
        }
      }
    },
    "ConsentedAppUnfurlMetadata": {
      "type": "object",
      "description": "Annotation metadata app unfurl consent.",
      "id": "ConsentedAppUnfurlMetadata",
      "properties": {
        "clientSpecifiedAppId": {
          "$ref": "UserId",
          "description": "Client specified AppId, which will not be sanitized and is untrusted."
        }
      }
    },
    "CaribouAttributeValue": {
      "id": "CaribouAttributeValue",
      "type": "object",
      "properties": {
        "rawByteValue": {
          "format": "byte",
          "type": "string",
          "description": "Generally, applications should avoid storing raw bytes and instead store structured data as protocol buffer extensions. This both reduces the amount of ad-hoc attribute parsing code as well as eliminates an intermediate copy of the data when deserializing the value. The rawByteValue field is mainly provided for compatibility with attributes stored before the introduction of the Attribute.Value."
        },
        "stringValue": {
          "type": "string"
        },
        "longValue": {
          "type": "string",
          "format": "int64"
        },
        "booleanValue": {
          "type": "boolean",
          "description": "Tags 1 through 15 are reserved for the most commonly used fields."
        },
        "intValue": {
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "Recipient": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        }
      },
      "id": "Recipient"
    },
    "GaiaUserProto": {
      "id": "GaiaUserProto",
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "format": "int64"
        }
      },
      "description": "A Gaia account, which may represent a user, device, service account, etc. For prod (@prod.google.com) accounts, use MdbUserProto instead."
    },
    "AppsDynamiteStorageSelectionInputSelectionItem": {
      "properties": {
        "text": {
          "type": "string",
          "description": "The text to be displayed."
        },
        "value": {
          "type": "string",
          "description": "The value associated with this item. The client should use this as a form input value."
        },
        "selected": {
          "description": "If more than one item is selected for `RADIO_BUTTON` and `DROPDOWN`, the first selected item is treated as selected and the ones after are ignored.",
          "type": "boolean"
        }
      },
      "id": "AppsDynamiteStorageSelectionInputSelectionItem",
      "type": "object",
      "description": "The item in the switch control. A radio button, at most one of the items is selected."
    },
    "FacetBucket": {
      "type": "object",
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object.",
      "properties": {
        "percentage": {
          "format": "int32",
          "type": "integer",
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts."
        },
        "count": {
          "type": "integer",
          "format": "int32",
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Cloud Search does not guarantee facet counts for any query and facet counts might be present only intermittently, even for identical queries. Do not build dependencies on facet count existence; instead use facet ount percentages which are always returned."
        },
        "filter": {
          "description": "Filter to be passed in the search request if the corresponding bucket is selected.",
          "$ref": "Filter"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "id": "FacetBucket"
    },
    "AppsDynamiteSharedGroupVisibility": {
      "id": "AppsDynamiteSharedGroupVisibility",
      "properties": {
        "state": {
          "type": "string",
          "enumDescriptions": [
            "Do not use.",
            "Explicitly invited users may join the room.",
            "Anyone in the domain may join the room."
          ],
          "enum": [
            "UNKNOWN",
            "PRIVATE",
            "PUBLIC"
          ]
        }
      },
      "type": "object"
    },
    "MultiKey": {
      "id": "MultiKey",
      "type": "object",
      "properties": {
        "serverId": {
          "description": "A server-assigned ID. This ID must be used only by Gmail and is constructed using millesecond ts \u003c\u003c 20 + randomness. The ID affects the sort order of the index.",
          "type": "string",
          "format": "uint64"
        },
        "clientAssignedPermId": {
          "description": "A client-assigned string based key.",
          "type": "string"
        }
      },
      "description": "A union-like type for identifiying an object in storage. MultiKeys contain multiple key fields, each in a separate key space. At least one key field must be set. More than one key field may be set as long as all key values refer to the same object. All objects in storage have unique server_id keys. All MultiKeys returned from storage to storage clients will always have the server_id field set. When creating an object, if a MultiKey without a server_id is supplied to storage[...]"
    },
    "PollItemsRequest": {
      "id": "PollItemsRequest",
      "properties": {
        "connectorName": {
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "description": "Queue name to fetch items from. If unspecified, PollItems will fetch from 'default' queue. The maximum length is 100 characters.",
          "type": "string"
        },
        "statusCodes": {
          "items": {
            "type": "string",
            "enumDescriptions": [
              "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
              "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
              "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
              "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
              "API has accepted the up-to-date data of this item."
            ],
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ]
          },
          "description": "Limit the items polled to the ones with these statuses.",
          "type": "array"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "limit": {
          "format": "int32",
          "type": "integer",
          "description": "Maximum number of items to return. The maximum value is 100 and the default value is 20."
        }
      },
      "type": "object"
    },
    "ResultDebugInfo": {
      "id": "ResultDebugInfo",
      "description": "Debugging information about the result.",
      "type": "object",
      "properties": {
        "formattedDebugInfo": {
          "description": "General debug info formatted for display.",
          "type": "string"
        }
      }
    },
    "SupportUrls": {
      "id": "SupportUrls",
      "description": "Urls with additional bot related information.",
      "properties": {
        "gwmUrl": {
          "description": "Link to GWM page of the app. May be empty.",
          "type": "string"
        },
        "adminConfigUrl": {
          "description": "Link to the admin configuration webpage for the bot. Configured by Pantheon, may be empty.",
          "type": "string"
        },
        "deletionPolicyUrl": {
          "description": "Link to the deletion policy webpage for the bot. Configured by Pantheon, may be empty.",
          "type": "string"
        },
        "supportUrl": {
          "description": "Link to the support webpage for the developer of the bot. May be empty.",
          "type": "string"
        },
        "tosUrl": {
          "description": "Link to the terms of service webpage for the bot. May be empty.",
          "type": "string"
        },
        "setupUrl": {
          "type": "string",
          "description": "Link to the setup webpage for the bot. Configured by Pantheon, may be empty."
        },
        "privacyPolicyUrl": {
          "type": "string",
          "description": "Link to the privacy policy webpage for the bot. May be empty."
        }
      },
      "type": "object"
    },
    "StructuredDataObject": {
      "description": "A structured data object consisting of named properties.",
      "properties": {
        "properties": {
          "items": {
            "$ref": "NamedProperty"
          },
          "type": "array",
          "description": "The properties for the object. The maximum number of elements is 1000."
        }
      },
      "type": "object",
      "id": "StructuredDataObject"
    },
    "UrlMetadata": {
      "type": "object",
      "description": "Annotation metadata for a Weblink. In case of pasted link it can qualify to be other types in addition to being a URL - like DRIVE_DOC/DRIVE_SHEET and so on. The URL metadata will also be present and it's up to the client to decide which metadata to render it with. These fields are filled in using page render service.",
      "properties": {
        "url": {
          "description": "The original URL.",
          "$ref": "SafeUrlProto"
        },
        "redirectUrl": {
          "description": "The stable redirect URL pointing to frontend server.",
          "$ref": "SafeUrlProto"
        },
        "shouldNotRender": {
          "description": "If the UrlMetadata is missing data for rendering a chip. Deprecated. Use Annotation.ChipRenderType instead.",
          "type": "boolean"
        },
        "imageHeight": {
          "description": "Dimensions of the image: height. This field is string to match with page render service response. Deprecated. Use int_image_height instead.",
          "type": "string"
        },
        "title": {
          "type": "string",
          "description": "Title of the Weblink."
        },
        "imageUrl": {
          "description": "Representative image of the website.",
          "type": "string"
        },
        "intImageHeight": {
          "type": "integer",
          "format": "int32",
          "description": "Dimensions of the image: height."
        },
        "domain": {
          "description": "Domain for this url. If it's an IP address the address is returned.",
          "type": "string"
        },
        "mimeType": {
          "type": "string",
          "description": "Mime type of the content (Currently mapped from Page Render Service ItemType) Note that this is not necessarily the mime type of the http resource. For example a text/html from youtube or vimeo may actually be classified as a video type. Then we shall mark it as video/* since we don't know exactly what type of video it is."
        },
        "snippet": {
          "type": "string",
          "description": "Snippet/small description of the weblink."
        },
        "gwsUrlExpirationTimestamp": {
          "format": "int64",
          "description": "The expiration timestamp for GWS URL, only set when gws_url is set.",
          "type": "string"
        },
        "urlSource": {
          "enum": [
            "URL_SOURCE_UNKNOWN",
            "SERVER_SUPPLIED_POLICY_VIOLATION",
            "AUTO_DETECTED_PLAIN_TEXT",
            "RICH_TEXT"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "Set by the server, when it detects a URL in the message text",
            "Set by the client, when the user adds a link as a custom hyperlink. Validated by the server and persisted in storage."
          ]
        },
        "intImageWidth": {
          "type": "integer",
          "format": "int32",
          "description": "Dimensions of the image: width."
        },
        "gwsUrl": {
          "description": "The signed GWS URL.",
          "$ref": "SafeUrlProto"
        },
        "imageWidth": {
          "type": "string",
          "description": "Dimensions of the image: width. This field is string to match with page render service response. Deprecated. Use int_image_height instead."
        }
      },
      "id": "UrlMetadata"
    },
    "MemberId": {
      "type": "object",
      "description": "Eventually this can be updated to a oneOf User, Space (for nested spaces), Bots or Service, as and when these use cases come up.",
      "properties": {
        "rosterId": {
          "$ref": "RosterId",
          "description": "Unique, immutable ID of the Roster."
        },
        "userId": {
          "description": "Unique, immutable ID of the User.",
          "$ref": "UserId"
        }
      },
      "id": "MemberId"
    },
    "PackagingServiceClient": {
      "description": "Developers register a client in Google API Console to get the deep-linking feature on Google+ posts or frames about their apps. The client data is stored in this proto.",
      "type": "object",
      "properties": {
        "iosBundleId": {
          "description": "iOS app's bundle ID to generate the deep-link URI.",
          "type": "string"
        },
        "type": {
          "description": "Type of Google API Console client.",
          "enum": [
            "ANDROID",
            "IOS"
          ],
          "enumDescriptions": [
            "Client for Android app.",
            "Client for iOS app."
          ],
          "type": "string"
        },
        "iosAppStoreId": {
          "description": "iOS app's App Store ID to generate the App Store URL when app is not installed on device.",
          "type": "string"
        },
        "androidPackageName": {
          "type": "string",
          "description": "Android app's package name to generate the deep-link URI."
        }
      },
      "id": "PackagingServiceClient"
    },
    "UpdateBody": {
      "type": "object",
      "id": "UpdateBody",
      "properties": {
        "insertContents": {
          "type": "array",
          "description": "A repeated field that contains a series of content to insert into the draft that the user is currently editing. The content can contain HTML content or plain text content.",
          "items": {
            "$ref": "InsertContent"
          }
        },
        "type": {
          "type": "string",
          "enum": [
            "UNSPECIFIED_ACTION_TYPE",
            "IN_PLACE_INSERT",
            "INSERT_AT_START",
            "INSERT_AT_END",
            "REPLACE"
          ],
          "enumDescriptions": [
            "Default value when nothing is set for Type.",
            "Indicates this action is to perform an in-place insertion. By default the content is inserted at the current cursor position, if there is selected content, it replaces the selected content.",
            "Indicates this action is to perform insert at the start of the message body.",
            "Indicates this action is to perform insert at the end of the message body.",
            "Indicates this action is to replace the message body."
          ]
        }
      }
    },
    "SearchApplicationQueryStats": {
      "id": "SearchApplicationQueryStats",
      "description": "Search application level query stats per date",
      "type": "object",
      "properties": {
        "queryCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "QueryCountByStatus"
          }
        },
        "date": {
          "$ref": "Date",
          "description": "The date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        }
      }
    },
    "SearchApplication": {
      "type": "object",
      "id": "SearchApplication",
      "properties": {
        "queryInterpretationConfig": {
          "description": "The default options for query interpretation",
          "$ref": "QueryInterpretationConfig"
        },
        "sourceConfig": {
          "description": "Configuration for a sources specified in data_source_restrictions.",
          "type": "array",
          "items": {
            "$ref": "SourceConfig"
          }
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the Search Application. The maximum length is 300 characters."
        },
        "name": {
          "description": "The name of the Search Application. Format: searchapplications/{application_id}.",
          "type": "string"
        },
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        },
        "dataSourceRestrictions": {
          "type": "array",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "Retrictions applied to the configurations. The maximum number of elements is 10."
        },
        "operationIds": {
          "readOnly": true,
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Output only. IDs of the Long Running Operations (LROs) currently running for this schema. Output only field."
        },
        "defaultFacetOptions": {
          "type": "array",
          "description": "The default fields for returning facet results. The sources specified here also have been included in data_source_restrictions above.",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "defaultSortOptions": {
          "description": "The default options for sorting the search results",
          "$ref": "SortOptions"
        },
        "returnResultThumbnailUrls": {
          "type": "boolean",
          "description": "With each result we should return the URI for its thumbnail (when applicable)"
        },
        "enableAuditLog": {
          "type": "boolean",
          "description": "Indicates whether audit logging is on/off for requests made for the search application in query APIs."
        }
      },
      "description": "SearchApplication"
    },
    "AppsDynamiteStorageCardCardAction": {
      "type": "object",
      "description": "A card action is the action associated with the card. For example, an invoice card might include actions such as delete invoice, email invoice, or open the invoice in a browser.",
      "properties": {
        "onClick": {
          "description": "The onclick action for this action item.",
          "$ref": "AppsDynamiteStorageOnClick"
        },
        "actionLabel": {
          "description": "The label that displays as the action menu item.",
          "type": "string"
        }
      },
      "id": "AppsDynamiteStorageCardCardAction"
    },
    "AppsDynamiteSharedAssistantAnnotationData": {
      "id": "AppsDynamiteSharedAssistantAnnotationData",
      "description": "This is the internal version of the API proto at google3/google/chat/v1/gsuite_message_integration.proto Data used to render Assistant suggestions. See go/bullseye-rendering.",
      "type": "object",
      "properties": {
        "unfulfillable": {
          "description": "Set when the initial query was unfulfillable. Only an on-demand unfulfillable query will result in a response (not a proactive query). 1. On-demand: user explicitly invokes the bot 2. Proactive: bot makes proactive suggestion (when available) by listening to all user messages.",
          "$ref": "AppsDynamiteSharedAssistantUnfulfillableRequest"
        },
        "suggestion": {
          "$ref": "AppsDynamiteSharedAssistantSuggestion",
          "description": "The suggestion to render in the card."
        }
      }
    },
    "SearchRequest": {
      "properties": {
        "dataSourceRestrictions": {
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "The sources to use for querying. If not specified, all data sources from the current search application are used.",
          "type": "array"
        },
        "queryInterpretationOptions": {
          "$ref": "QueryInterpretationOptions",
          "description": "Options to interpret the user query."
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "start": {
          "type": "integer",
          "format": "int32",
          "description": "Starting index of the results."
        },
        "query": {
          "description": "The raw query string. See supported search operators in the [Narrow your search with operators](https://support.google.com/cloudsearch/answer/6172299)",
          "type": "string"
        },
        "pageSize": {
          "format": "int32",
          "description": "Maximum number of search results to return in one page. Valid values are between 1 and 100, inclusive. Default value is 10. Minimum value is 50 when results beyond 2000 are requested.",
          "type": "integer"
        },
        "contextAttributes": {
          "description": "Context attributes for the request which will be used to adjust ranking of search results. The maximum number of elements is 10.",
          "type": "array",
          "items": {
            "$ref": "ContextAttribute"
          }
        },
        "facetOptions": {
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "requestOptions": {
          "description": "Request options, such as the search application and user timezone.",
          "$ref": "RequestOptions"
        }
      },
      "type": "object",
      "description": "The search API request.",
      "id": "SearchRequest"
    },
    "CircleProto": {
      "properties": {
        "requiredConsistencyTimestampUsec": {
          "type": "string",
          "format": "int64",
          "description": "If present, then tests for membership in this circle must use data known to be at least as fresh as the given (FBS-assigned) timestamp. See http://go/fbs-consistent-read-after-important-write Before using this, be sure that any service checking authorization against this circle supports checking consistency timestamps. For example, as of 12/2011, Keystore only supports this for the Moonshine configuration, and in others authorization checks will fail if the timestamp is[...]"
        },
        "circleId": {
          "description": "Circle ID is unique only relative to the owner's Gaia ID. Currently required.",
          "type": "string",
          "format": "int64"
        },
        "ownerGaiaId": {
          "description": "The owner of the circle. Currently required.",
          "format": "int64",
          "type": "string"
        }
      },
      "description": "Represents a Google+ Circle. Currently (12/2011), a Circle is identical to the ContactGroup with matching parameters, but Circle must only be used for true Circles and not other Focus groups, and should be preferred over ContactGroup where applicable. Soon it may become more efficient to check membership in a Circle than in a ContactGroup (see http://go/superglue). Support for this principal type is currently (12/2011) incomplete -- e.g., Keystore does not support it yet (s[...]",
      "id": "CircleProto",
      "type": "object"
    },
    "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkup": {
      "description": "Markup that defines conference data associated to a Google Calendar event.",
      "properties": {
        "error": {
          "$ref": "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupError",
          "description": "If set, it means an error occurred during conference creation."
        },
        "entryPoints": {
          "description": "Entry points to the conference. Maximum 300 entry points are allowed.",
          "type": "array",
          "items": {
            "$ref": "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupEntryPointMarkup"
          }
        },
        "conferenceId": {
          "description": "Unique identifier for this conference data. Maximum 512 characters long.",
          "type": "string"
        },
        "conferenceSolutionId": {
          "description": "An identifier of the conferencing solution. Must match a value from the deployment's `calendar.conferenceSolution.id` field.",
          "type": "string"
        },
        "note": {
          "type": "string",
          "description": "Additional notes (such as instructions from the administrator, legal notices) to display to the user. Can contain HTML. Max length 2048 characters."
        }
      },
      "type": "object",
      "id": "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkup"
    },
    "Annotation": {
      "description": "NOTE WHEN ADDING NEW PROTO FIELDS: Be sure to add datapol annotations to new fields with potential PII, so they get scrubbed when logging protos for errors. NEXT TAG: 32",
      "id": "Annotation",
      "properties": {
        "serverInvalidated": {
          "description": "Whether or not the annotation is invalidated by the server. Example of situations for invalidation include: when the URL is malformed, or when Drive item ID is rejected by Drive Service.",
          "type": "boolean"
        },
        "uniqueId": {
          "description": "* A unique server-assigned ID for this annotation. This is helpful in matching annotation objects when fetched from service. All uploads should have a unique_id after the message they are attached to is successfully sent. Url annotations that originally were uploads (i.e. policy violations) will have a unique_id after the message they are attached to is successfully sent. No other url annotations should have a unique_id. All drive annotations should have a unique_id aft[...]",
          "type": "string"
        },
        "interactionData": {
          "$ref": "InteractionData",
          "description": "Additional interaction data for this annotation."
        },
        "integrationConfigUpdated": {
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/dynamite/v1/backend/action/common/SystemMessageHelper.java)",
          "$ref": "IntegrationConfigUpdatedMetadata"
        },
        "incomingWebhookChangedMetadata": {
          "$ref": "IncomingWebhookChangedMetadata"
        },
        "chipRenderType": {
          "type": "string",
          "enum": [
            "CHIP_RENDER_TYPE_UNSPECIFIED",
            "RENDER",
            "RENDER_IF_POSSIBLE",
            "DO_NOT_RENDER"
          ],
          "enumDescriptions": [
            "",
            "Clients must render the annotation as a preview chip, and if they cannot render this many Annotations, show a fallback card.",
            "Client can render the annotation if it has room to render it.",
            "Client should not render the annotation as a preview chip."
          ],
          "description": "Whether the annotation should be rendered as a preview chip. If this is missing or unspecified, fallback to should_not_render on the metadata."
        },
        "inlineRenderFormat": {
          "type": "string",
          "enumDescriptions": [
            "",
            ""
          ],
          "description": "The inline render format of this annotation. go/drive-smart-chips-chat-v2.",
          "enum": [
            "INLINE_RENDER_FORMAT_UNSPECIFIED",
            "SMART_CHIP"
          ]
        },
        "uploadMetadata": {
          "$ref": "UploadMetadata"
        },
        "componentSearchInfo": {
          "description": "Contains additional metadata that further enhances the annotation when it is returned as part of search response. For example, this can be used to define how the annotation matches the search. Information can be used to highlight in rendering search results. The following are the different annotation text fields that can be highlighted by this field: 1. DriveMetadata.title 2. UploadMetadata.content_name 3. GsuiteIntegrationMetadata.TasksMessageIntegrationRenderData.titl[...]",
          "$ref": "AppsDynamiteSharedMessageComponentSearchInfo"
        },
        "length": {
          "type": "integer",
          "format": "int32",
          "description": "Length of the text_body substring beginning from start_index the Annotation corresponds to."
        },
        "customEmojiMetadata": {
          "$ref": "CustomEmojiMetadata"
        },
        "babelPlaceholderMetadata": {
          "$ref": "BabelPlaceholderMetadata"
        },
        "roomUpdated": {
          "$ref": "RoomUpdatedMetadata"
        },
        "driveMetadata": {
          "description": "Chip annotations",
          "$ref": "DriveMetadata"
        },
        "userMentionMetadata": {
          "description": "Metadata that clients can set for annotations. LINT.IfChange In-text annotations",
          "$ref": "UserMentionMetadata"
        },
        "videoCallMetadata": {
          "$ref": "VideoCallMetadata"
        },
        "groupRetentionSettingsUpdated": {
          "$ref": "GroupRetentionSettingsUpdatedMetaData"
        },
        "localId": {
          "description": "* A client-assigned ID for this annotation. This is helpful in matching the back-filled annotations to the original annotations on client side, without having to re-parse the message. There is no guarantee an annotation has a local_id, it's a purely client used and controlled field with no guarantee of uniqueness.",
          "type": "string"
        },
        "youtubeMetadata": {
          "$ref": "YoutubeMetadata"
        },
        "readReceiptsSettingsMetadata": {
          "$ref": "ReadReceiptsSettingsUpdatedMetadata"
        },
        "requiredMessageFeaturesMetadata": {
          "$ref": "RequiredMessageFeaturesMetadata",
          "description": "Metadata that defines all of the required features that must be rendered in the message. Clients can use this to see whether they support the entire message, or show a fallback chip otherwise. See go/message-quoting-client-to-server for details. LINT.ThenChange( //depot/google3/java/com/google/apps/dynamite/v1/allshared/parser/AnnotationSanitizer.java, //depot/google3/java/com/google/apps/dynamite/v1/backend/action/common/SystemMessageHelper.java, //depot/google3/java/c[...]"
        },
        "consentedAppUnfurlMetadata": {
          "$ref": "ConsentedAppUnfurlMetadata"
        },
        "slashCommandMetadata": {
          "$ref": "SlashCommandMetadata"
        },
        "gsuiteIntegrationMetadata": {
          "$ref": "GsuiteIntegrationMetadata",
          "description": "Metadata for 1P integrations like tasks, calendar. These are supported only through integration server as 1P integrations use the integration API (which in turn uses backend API with special permissions) to post messages. Clients should never set this. LINT.IfChange"
        },
        "startIndex": {
          "format": "int32",
          "description": "Start index (0-indexed) of the Message text the Annotation corresponds to, inclusive.",
          "type": "integer"
        },
        "cardCapabilityMetadata": {
          "description": "LINT.ThenChange(//depot/google3/java/com/google/apps/dynamite/v1/backend/action/common/SystemMessageHelper.java)",
          "$ref": "CardCapabilityMetadata"
        },
        "type": {
          "enumDescriptions": [
            "Default value for the enum. DO NOT USE.",
            "These can have overlaps, i.e. same message can have multiple of these. For example a Drive link to a PDF can have URL, DRIVE_FILE and PDF all set Links",
            "Any drive file",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Any video, not just youtube, the url decides how to play",
            "UI should not be concerned with FORMAT_DATA",
            "",
            "",
            "For Thor integration",
            "Blobstore uploads",
            "Generic annotation for gsuite integrations",
            "",
            "Card capability for in-stream widgets.",
            "",
            "Clients can use this to see whether they support the entire message, or show a fallback chip otherwise.",
            "Annotation types for system messages. Clients should never set this.",
            "",
            "",
            "",
            "",
            "",
            "",
            "Message-level annotations. First message of an invite. Should not be set by clients."
          ],
          "type": "string",
          "description": "Type of the Annotation.",
          "enum": [
            "TYPE_UNSPECIFIED",
            "URL",
            "DRIVE_FILE",
            "DRIVE_DOC",
            "DRIVE_SHEET",
            "DRIVE_SLIDE",
            "DRIVE_FORM",
            "USER_MENTION",
            "SLASH_COMMAND",
            "CONSENTED_APP_UNFURL",
            "VIDEO",
            "FORMAT_DATA",
            "IMAGE",
            "PDF",
            "VIDEO_CALL",
            "UPLOAD_METADATA",
            "GSUITE_INTEGRATION",
            "CUSTOM_EMOJI",
            "CARD_CAPABILITY",
            "DATA_LOSS_PREVENTION",
            "REQUIRED_MESSAGE_FEATURES_METADATA",
            "MEMBERSHIP_CHANGED",
            "ROOM_UPDATED",
            "GROUP_RETENTION_SETTINGS_UPDATED",
            "BABEL_PLACEHOLDER",
            "READ_RECEIPTS_SETTINGS_UPDATED",
            "INCOMING_WEBHOOK_CHANGED",
            "INTEGRATION_CONFIG_UPDATED",
            "INVITATION"
          ]
        },
        "membershipChanged": {
          "description": "Metadata for system messages. Clients should never set this. LINT.IfChange",
          "$ref": "MembershipChangedMetadata"
        },
        "formatMetadata": {
          "$ref": "FormatMetadata"
        },
        "urlMetadata": {
          "$ref": "UrlMetadata"
        },
        "dataLossPreventionMetadata": {
          "$ref": "DataLossPreventionMetadata"
        }
      },
      "type": "object"
    },
    "AppsDynamiteSharedTasksAnnotationDataUserDefinedMessage": {
      "properties": {},
      "type": "object",
      "description": "Used for task card attachments on custom user messages that should be kept as is without generating an i18n event message, e.g. the user starts a conversation from an existing task. IMPORTANT: please don't populate this field yet as it could break existing flows until it's implemented. See code at http://shortn/_CM74CdENMx used by http://shortn/_5o85POJY8Q.",
      "id": "AppsDynamiteSharedTasksAnnotationDataUserDefinedMessage"
    },
    "FuseboxItemThreadMatchInfo": {
      "type": "object",
      "properties": {
        "lastMatchingItemId": {
          "format": "uint64",
          "type": "string",
          "description": "The server id of the last item that matched the query. This is always set, regardless of the compute_matching_items_per_thread option. This is the value by which search results are sorted, in descending (i.e. newest first) order."
        },
        "clusterId": {
          "description": "If SearchQuery.Options.Clustering is present, the query will be treated as a cluster query, and this field may be populated with the cluster ID of the cluster to which this thread belongs, if any. The cluster ID will be a label on the message.",
          "type": "string"
        },
        "rank": {
          "$ref": "Rank",
          "description": "The rank of this ItemThread in the result set of the query. This rank may be used to sort ItemThreads in proper order. Ranks are specific to a query, and stable for a given query at a specific time."
        },
        "lastMatchingItemKey": {
          "description": "The MultiKey of the last item that matched the query. This is always set, regardless of the compute_matching_items_per_thread option. This is the value by which search results are sorted, in descending (i.e. newest first) order.",
          "$ref": "MultiKey"
        },
        "matchingItemKey": {
          "type": "array",
          "items": {
            "$ref": "MultiKey"
          },
          "description": "If SearchQuery.Options.compute_matching_items_per_thread, this field will contain the keys of all items that matched the query, in ascending order. Note that this option requires extra computation."
        }
      },
      "id": "FuseboxItemThreadMatchInfo",
      "description": "In the context of a search, the MatchInfo contains information about which Items matched the query."
    },
    "RecordingEvent": {
      "id": "RecordingEvent",
      "properties": {
        "deviceId": {
          "type": "string",
          "description": "The initiator of the latest event of the recording. It will be set for all user events (`type` is 100-199) and unset for all server events (`type` is 200-299)."
        },
        "type": {
          "enum": [
            "RECORDING_EVENT_UNSPECIFIED",
            "USER_ACTION",
            "STARTED_BY_USER",
            "STOPPED_BY_USER",
            "CANCELLED_BY_USER",
            "CANCELLED_INITIALIZATION_FAILED",
            "CANCELLED_INITIATOR_LEFT",
            "ACTIVE_ABOUT_TO_STOP_TOO_LONG",
            "STOPPED_TOO_LONG",
            "STOPPED_ALL_DEVICES_LEFT",
            "STOPPED_INTERNAL_FAILURES"
          ],
          "enumDescriptions": [
            "This is never used.",
            "Deprecated, use detailed user actions instead.",
            "Recording was started or is being started by a user.",
            "Recording was stopped by a user.",
            "Recording was cancelled by a user.",
            "Recording was cancelled by the server because of a failure during recording initialization.",
            "Recording was cancelled by the server because the recording initiator left the conference during initialization. When the initiator leaves after the recording is started, no event is triggered.",
            "Recording is about to be stopped by the server because the recording is about to reach the maximum duration.",
            "Recording was stopped because the recording reached the maximum duration.",
            "Recording was stopped because there were no devices left in the conference.",
            "Recording was stopped because of an internal error."
          ],
          "type": "string",
          "description": "The type of event."
        }
      },
      "description": "A recording event is something that happens to the recording in a conference.",
      "type": "object"
    },
    "Grid": {
      "properties": {
        "borderStyle": {
          "$ref": "BorderStyle",
          "description": "The border style to apply to each grid item."
        },
        "onClick": {
          "description": "This callback will be reused by each individual GridItem, but with the item's identifier and index in the items list added to the callback's parameters.",
          "$ref": "OnClick"
        },
        "title": {
          "type": "string",
          "description": "The text to display in the grid header."
        },
        "items": {
          "type": "array",
          "description": "The items to display in the grid.",
          "items": {
            "$ref": "GridItem"
          }
        },
        "numColumns": {
          "format": "int32",
          "description": "The number of columns to display in the grid. Note that a default value will be used if this field is not specified, and that default value will be different depending on where the grid is shown (dialog vs companion).",
          "type": "integer"
        }
      },
      "id": "Grid",
      "type": "object"
    },
    "AppsDynamiteSharedChatItemActivityInfoFeedItemReactions": {
      "properties": {},
      "type": "object",
      "id": "AppsDynamiteSharedChatItemActivityInfoFeedItemReactions",
      "description": "Existence of this attribute indicates that the AF item is for message reactions, but it is intentionally left empty since the list of reactions can be found in the top-level Message.Reactions."
    },
    "Filter": {
      "id": "Filter",
      "type": "object",
      "description": "A generic way of expressing filters in a query, which supports two approaches: **1. Setting a ValueFilter.** The name must match an operator_name defined in the schema for your data source. **2. Setting a CompositeFilter.** The filters are evaluated using the logical operator. The top-level operators can only be either an AND or a NOT. AND can appear only at the top-most level. OR can appear only under a top-level AND.",
      "properties": {
        "valueFilter": {
          "$ref": "ValueFilter"
        },
        "compositeFilter": {
          "$ref": "CompositeFilter"
        }
      }
    },
    "AppsDynamiteStorageImage": {
      "properties": {
        "altText": {
          "type": "string",
          "description": "The alternative text of this image, used for accessibility."
        },
        "imageUrl": {
          "description": "An image URL.",
          "type": "string"
        },
        "onClick": {
          "$ref": "AppsDynamiteStorageOnClick"
        }
      },
      "description": "An image that is specified by a URL and can have an onClick action.",
      "type": "object",
      "id": "AppsDynamiteStorageImage"
    },
    "ChatConserverDynamitePlaceholderMetadataCalendarEventMetadata": {
      "properties": {},
      "type": "object",
      "id": "ChatConserverDynamitePlaceholderMetadataCalendarEventMetadata",
      "description": "A Calendar event message in Dynamite."
    },
    "NamedProperty": {
      "id": "NamedProperty",
      "properties": {
        "textValues": {
          "$ref": "TextValues"
        },
        "name": {
          "description": "The name of the property. This name should correspond to the name of the property that was registered for object definition in the schema. The maximum allowable length for this property is 256 characters.",
          "type": "string"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        }
      },
      "type": "object",
      "description": "A typed name-value pair for structured data. The type of the value should be the same as the registered type for the `name` property in the object definition of `objectType`."
    },
    "AttributeRemoved": {
      "properties": {
        "messageKeys": {
          "type": "array",
          "items": {
            "$ref": "MultiKey"
          }
        },
        "attributeId": {
          "type": "string"
        }
      },
      "id": "AttributeRemoved",
      "type": "object",
      "description": "An attribute was deleted from some (subset of the) messages in this thread."
    },
    "ImageComponent": {
      "properties": {
        "cropStyle": {
          "$ref": "ImageCropStyle"
        },
        "imageUrl": {
          "type": "string"
        },
        "borderStyle": {
          "$ref": "BorderStyle"
        },
        "altText": {
          "type": "string"
        }
      },
      "description": "NOTE: Through future refactoring work, this image component will eventually be used in the Image widget, and will likely replace the Icon proto as well.",
      "type": "object",
      "id": "ImageComponent"
    },
    "AppsDynamiteSharedActivityFeedAnnotationData": {
      "type": "object",
      "properties": {
        "sharedUserInfo": {
          "description": "Only populated on read path and should not be persisted in storage.",
          "$ref": "UserInfo"
        },
        "userInfo": {
          "description": "Use shared_user_info instead.",
          "$ref": "AppsDynamiteSharedActivityFeedAnnotationDataUserInfo"
        },
        "chatItem": {
          "$ref": "AppsDynamiteSharedChatItem"
        },
        "activityFeedMessageId": {
          "description": "Unique id of the Activity Feed message used by clients to implement click-to-source. This is the same messageId as the top-level id field for the Activity Feed item.",
          "$ref": "MessageId"
        },
        "activityFeedMessageCreateTime": {
          "description": "Timestamp of when the Activity Feed message that contains this annotation was created. This is roughly when the activity happened, such as when a reaction happened, but will have at least some small delay, since the Activity Feed message is created asynchronously after. This timestamp should only be used for display when the activity create time is not available in the Chat UI, like the time of a reaction.",
          "format": "google-datetime",
          "type": "string"
        }
      },
      "id": "AppsDynamiteSharedActivityFeedAnnotationData",
      "description": "Next Id: 7"
    },
    "EditMetadata": {
      "description": "A message edit in Dynamite inserts a Babel-only item containing this field.",
      "id": "EditMetadata",
      "type": "object",
      "properties": {}
    },
    "DataLossPreventionMetadata": {
      "id": "DataLossPreventionMetadata",
      "properties": {
        "dlpMessageScanRecord": {
          "$ref": "DlpMessageScanRecord",
          "description": "The scan record contains the action taken on the message send as well as scan the summary for the message contents and the attachment, if applicable."
        },
        "dlpScanSummary": {
          "$ref": "DlpScanSummary",
          "description": "Deprecated. To be replaced by DLP scan record. The DLP scan summary that should only be set after the message is scanned in the Chat backend."
        },
        "warnAcknowledged": {
          "type": "boolean",
          "description": "Flag set by client on message resend to bypass WARN violation."
        }
      },
      "description": "Annotation metadata for Data Loss Prevention that pertains to DLP violation on message send or edit events. It is used for client -\u003e BE communication and other downstream process in BE (e.g. storage and audit logging), and it should never be returned to the client.",
      "type": "object"
    },
    "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupEntryPointMarkup": {
      "id": "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupEntryPointMarkup",
      "properties": {
        "uri": {
          "description": "A URI for joining the conference. Supports tel: and http(s): and should be at most 1300 characters long. Required.",
          "type": "string"
        },
        "label": {
          "type": "string",
          "description": "The label of the entry point to display to the user. Maximum 512 characters long."
        },
        "meetingCode": {
          "description": "A meeting code for accessing the conference. Maximum 128 characters long.",
          "type": "string"
        },
        "password": {
          "description": "A password for accessing the conference. Maximum 128 characters long.",
          "type": "string"
        },
        "passcode": {
          "type": "string",
          "description": "A passcode for accessing the conference. Maximum 128 characters long."
        },
        "features": {
          "description": "Features of the entry point, such as being toll or toll-free. One entry point can have multiple features.",
          "items": {
            "type": "string",
            "enum": [
              "UNKNOWN_FEATURE",
              "TOLL",
              "TOLL_FREE"
            ],
            "enumDescriptions": [
              "Unknown feature.",
              "Applies to `PHONE` entry point. A call to a toll number is charged to the calling party. A number can't be toll and toll-free at the same time.",
              "Applies to `PHONE` entry point. For the calling party, a call to a toll-free number is free of charge. A number can't be toll and toll-free at the same time."
            ]
          },
          "type": "array"
        },
        "accessCode": {
          "description": "An access code for accessing the conference. Maximum 128 characters long.",
          "type": "string"
        },
        "pin": {
          "description": "A PIN for accessing the conference. Maximum 128 characters long.",
          "type": "string"
        },
        "type": {
          "enumDescriptions": [
            "Unknown conference type.",
            "A video conference.",
            "A phone conference.",
            "Used to provide a link to further conference joining information.",
            "A conference using [Session Initiation Protocol](https://en.wikipedia.org/wiki/Session_Initiation_Protocol)"
          ],
          "enum": [
            "UNKNOWN",
            "VIDEO",
            "PHONE",
            "MORE",
            "SIP"
          ],
          "description": "The type of the entry point. Required.",
          "type": "string"
        },
        "regionCode": {
          "description": "The CLDR/ISO 3166 region code for the country associated with this entry point. Applicable only to `Type.PHONE`.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "A way to join the conference."
    },
    "Button": {
      "type": "object",
      "id": "Button",
      "properties": {
        "imageButton": {
          "$ref": "ImageButton"
        },
        "textButton": {
          "$ref": "TextButton"
        }
      }
    },
    "SquareProto": {
      "description": "Represents the set of members (of a given type) in a Google+ Square (see http://go/squares). A Square with default member_type is currently (1/2012) identical to the GaiaGroup with the same ID, but that is expected to change soon (see http://go/superglue). Support for this principal type is currently (1/2012) incomplete -- e.g., Keystore does not support it yet (see b/5703421).",
      "properties": {
        "squareId": {
          "description": "Currently required.",
          "type": "string",
          "format": "int64"
        },
        "memberType": {
          "format": "int32",
          "type": "integer",
          "description": "The type of Square members to consider, e.g. \"all members\" vs. \"owners\" vs. \"admins\". These are defined by legacy_relation_id values in social.graph.storage.EdgeTypeEnum.EdgeType enum options in social/graph/storage/proto/id.proto. See square.pb (defined in production/config/cdd/socialgraph/mixer_config/prod/node_type_config) for all valid edge types associated with square. Currently required."
        }
      },
      "id": "SquareProto",
      "type": "object"
    },
    "Photo": {
      "type": "object",
      "id": "Photo",
      "properties": {
        "url": {
          "type": "string",
          "description": "The URL of the photo."
        }
      },
      "description": "A person's photo."
    },
    "AppsDynamiteSharedMessageComponentSearchInfo": {
      "properties": {
        "titleTextWithDescription": {
          "description": "Backend should always set TextWithDescription.text_body based on the title (or its snippet) of the annotation or attachment.",
          "$ref": "AppsDynamiteSharedTextWithDescription"
        },
        "matchedSearch": {
          "type": "boolean",
          "description": "Whether the whole component matched the search."
        }
      },
      "description": "Metadata used to describe search information in a specific component of a chat message, for example an annotation or an attachment.",
      "type": "object",
      "id": "AppsDynamiteSharedMessageComponentSearchInfo"
    },
    "Image": {
      "id": "Image",
      "properties": {
        "altText": {
          "type": "string",
          "description": "The alternative text of this image which will be used for accessibility."
        },
        "onClick": {
          "$ref": "OnClick"
        },
        "aspectRatio": {
          "type": "number",
          "format": "double",
          "description": "The aspect ratio of this image (width/height)."
        },
        "imageUrl": {
          "type": "string",
          "description": "Image url specified by developers. Server side, we will wrap with FIFE so client apps can configure size/cropping/etc."
        }
      },
      "type": "object"
    },
    "MessageId": {
      "type": "object",
      "properties": {
        "parentId": {
          "description": "ID of the Message's immediate parent.",
          "$ref": "MessageParentId"
        },
        "messageId": {
          "type": "string",
          "description": "Opaque, server-assigned ID of the Message. While this ID is guaranteed to be unique within the Space, it's not guaranteed to be globally unique."
        }
      },
      "description": "Primary key for Message resource.",
      "id": "MessageId"
    },
    "SourceScoringConfig": {
      "properties": {
        "sourceImportance": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ],
          "description": "Importance of the source."
        }
      },
      "id": "SourceScoringConfig",
      "description": "Set the scoring configuration. This allows modifying the ranking of results for a source.",
      "type": "object"
    },
    "Section": {
      "description": "Sections are separated by a line divider. They contain a collection of widgets that are rendered (vertically) in the order that they are specified. Across all platforms, AddOns have a narrow fixed width, so there is currently no need for layout properties (e.g. float).",
      "type": "object",
      "id": "Section",
      "properties": {
        "collapsable": {
          "type": "boolean",
          "description": "Indicating whether this section is collapsable. If a section is collapsable, the description must be given."
        },
        "numUncollapsableWidgets": {
          "type": "integer",
          "format": "int32",
          "description": "The number of uncollapsable widgets. For example, when a section contains 5 widgets and the num_uncollapsable_widget are set to be 2, The first 2 widgets will always shown and the last 3 is collapsed as default. Only when collapsable is set to be true, the num_uncollapsable_widget will be taken into account."
        },
        "widgets": {
          "items": {
            "$ref": "WidgetMarkup"
          },
          "description": "A section must contain at least 1 widget.",
          "type": "array"
        },
        "description": {
          "description": "The header of the section, text formatted supported.",
          "type": "string"
        }
      }
    },
    "RequestOptions": {
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Debug options of the request"
        },
        "timeZone": {
          "type": "string",
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) project, and currently available in the file [timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml). This field is used to correctly interpret date and time queries. If this field is not specified, the default time zone (UTC) is used."
        },
        "searchApplicationId": {
          "description": "The ID generated when you create a search application using the [admin console](https://support.google.com/a/answer/9043922).",
          "type": "string"
        },
        "languageCode": {
          "type": "string",
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. For translations. Set this field using the language set in browser or for the page. In the event that the user's language preference is known, set this field to the known user language. When specified, the documents in search results are biased towards the specified language. From Suggest API perspective, for 3p suggest th[...]"
        }
      },
      "type": "object",
[...]
