{
  "basePath": "",
  "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/",
  "canonicalName": "Cloud Search",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "batchPath": "batch",
  "version": "v1",
  "title": "Cloud Search API",
  "id": "cloudsearch:v1",
  "name": "cloudsearch",
  "servicePath": "",
  "schemas": {
    "CheckAccessResponse": {
      "properties": {
        "hasAccess": {
          "type": "boolean",
          "description": "Returns true if principal has access. Returns false otherwise."
        }
      },
      "type": "object",
      "id": "CheckAccessResponse"
    },
    "CompositeFilter": {
      "id": "CompositeFilter",
      "type": "object",
      "properties": {
        "logicOperator": {
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ],
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "type": "string",
          "description": "The logic operator of the sub filter."
        },
        "subFilters": {
          "type": "array",
          "items": {
            "$ref": "Filter"
          },
          "description": "Sub filters."
        }
      }
    },
    "SearchQualityMetadata": {
      "properties": {
        "quality": {
          "type": "number",
          "format": "double",
          "description": "An indication of the quality of the item, used to influence search quality. Value should be between 0.0 (lowest quality) and 1.0 (highest quality). The default value is 0.0."
        }
      },
      "id": "SearchQualityMetadata",
      "description": "Additional search quality metadata of the item.",
      "type": "object"
    },
    "SuggestResponse": {
      "description": "Response of the suggest API.",
      "properties": {
        "suggestResults": {
          "description": "List of suggestions.",
          "items": {
            "$ref": "SuggestResult"
          },
          "type": "array"
        }
      },
      "id": "SuggestResponse",
      "type": "object"
    },
    "SearchApplication": {
      "properties": {
        "dataSourceRestrictions": {
          "description": "Retrictions applied to the configurations. The maximum number of elements is 10.",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "operationIds": {
          "readOnly": true,
          "items": {
            "type": "string"
          },
          "description": "Output only. IDs of the Long Running Operations (LROs) currently running for this schema. Output only field.",
          "type": "array"
        },
        "queryInterpretationConfig": {
          "$ref": "QueryInterpretationConfig",
          "description": "The default options for query interpretation"
        },
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        },
        "displayName": {
          "description": "Display name of the Search Application. The maximum length is 300 characters.",
          "type": "string"
        },
        "sourceConfig": {
          "items": {
            "$ref": "SourceConfig"
          },
          "type": "array",
          "description": "Configuration for a sources specified in data_source_restrictions."
        },
        "name": {
          "description": "Name of the Search Application. Format: searchapplications/{application_id}.",
          "type": "string"
        },
        "defaultSortOptions": {
          "description": "The default options for sorting the search results",
          "$ref": "SortOptions"
        },
        "defaultFacetOptions": {
          "description": "The default fields for returning facet results. The sources specified here also have been included in data_source_restrictions above.",
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "returnResultThumbnailUrls": {
          "type": "boolean",
          "description": "With each result we should return the URI for its thumbnail (when applicable)"
        },
        "enableAuditLog": {
          "description": "Indicates whether audit logging is on/off for requests made for the search application in query APIs.",
          "type": "boolean"
        }
      },
      "type": "object",
      "description": "SearchApplication",
      "id": "SearchApplication"
    },
    "DateOperatorOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:\u003cvalue\u003e* show results only where the value of the *closeDate* property matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an oper[...]"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "DateOperatorOptions"
    },
    "SpaceInfo": {
      "description": "Defines the representation of a single matching space.",
      "id": "SpaceInfo",
      "properties": {
        "inviterEmail": {
          "type": "string",
          "description": "The email address of the user that invited the calling user to the room, if available. This field will only be populated for direct invites, it will be empty if the user was indirectly invited to the group."
        },
        "avatarInfo": {
          "$ref": "AvatarInfo"
        },
        "isExternal": {
          "type": "boolean",
          "description": "Whether this is a space that enables guest access"
        },
        "numMembers": {
          "type": "integer",
          "format": "int32"
        },
        "groupId": {
          "$ref": "GroupId"
        },
        "avatarUrl": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "userMembershipState": {
          "enumDescriptions": [
            "Default state, do not use",
            "An invitation to the space has been sent",
            "User has joined the space",
            "User is not a member",
            "This state should never be stored in Spanner. It is a state for responses to the clients to indicate that membership mutations have failed and the member is in its previous state."
          ],
          "enum": [
            "MEMBER_UNKNOWN",
            "MEMBER_INVITED",
            "MEMBER_JOINED",
            "MEMBER_NOT_A_MEMBER",
            "MEMBER_FAILED"
          ],
          "type": "string",
          "description": "searching user's membership state in this space"
        },
        "name": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "MatchRange": {
      "type": "object",
      "description": "Matched range of a snippet [start, end).",
      "id": "MatchRange",
      "properties": {
        "start": {
          "description": "Starting position of the match in the snippet.",
          "type": "integer",
          "format": "int32"
        },
        "end": {
          "format": "int32",
          "type": "integer",
          "description": "End of the match in the snippet."
        }
      }
    },
    "DebugOptions": {
      "id": "DebugOptions",
      "type": "object",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "description": "Shared request debug options for all cloudsearch RPC methods."
    },
    "DmId": {
      "id": "DmId",
      "properties": {
        "dmId": {
          "description": "Unique server assigned Id, per Direct Message Space.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "StructuredResult": {
      "id": "StructuredResult",
      "properties": {
        "person": {
          "description": "Representation of a person",
          "$ref": "Person"
        }
      },
      "type": "object",
      "description": "Structured results that are returned as part of search request."
    },
    "DataSource": {
      "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search.",
      "type": "object",
      "id": "DataSource",
      "properties": {
        "disableServing": {
          "type": "boolean",
          "description": "Disable serving any search or assist results."
        },
        "disableModifications": {
          "type": "boolean",
          "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data."
        },
        "displayName": {
          "type": "string",
          "description": "Required. Display name of the datasource The maximum length is 300 characters."
        },
        "shortName": {
          "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *\u003cvalue\u003e* then queries like *source:\u003cvalue\u003e* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, h[...]",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "returnThumbnailUrls": {
          "description": "Can a user request to get thumbnail URI for Items indexed in this data source.",
          "type": "boolean"
        },
        "name": {
          "description": "Name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource.",
          "type": "string"
        },
        "indexingServiceAccounts": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of service accounts that have indexing access."
        },
        "itemsVisibility": {
          "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility.",
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "type": "array"
        }
      }
    },
    "ScoringConfig": {
      "id": "ScoringConfig",
      "type": "object",
      "properties": {
        "disableFreshness": {
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used as a ranking signal. Note that this setting is not available in the Admin UI.",
          "type": "boolean"
        },
        "disablePersonalization": {
          "type": "boolean",
          "description": "Whether to personalize the results. By default, personal signals will be used to boost results."
        }
      },
      "description": "Scoring configurations for a source while processing a Search or Suggest request."
    },
    "StructuredDataObject": {
      "type": "object",
      "properties": {
        "properties": {
          "items": {
            "$ref": "NamedProperty"
          },
          "description": "The properties for the object. The maximum number of elements is 1000.",
          "type": "array"
        }
      },
      "description": "A structured data object consisting of named properties.",
      "id": "StructuredDataObject"
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned."
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "ListOperationsResponse": {
      "type": "object",
      "id": "ListOperationsResponse",
      "description": "The response message for Operations.ListOperations.",
      "properties": {
        "operations": {
          "description": "A list of operations that matches the specified filter in the request.",
          "type": "array",
          "items": {
            "$ref": "Operation"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "The standard List next-page token."
        }
      }
    },
    "DisplayedProperty": {
      "type": "object",
      "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown.",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema.",
          "type": "string"
        }
      },
      "id": "DisplayedProperty"
    },
    "IntegerValues": {
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "id": "IntegerValues",
      "type": "object",
      "description": "List of integer values."
    },
    "GetCustomerSessionStatsResponse": {
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerSessionStats"
          },
          "type": "array"
        }
      },
      "id": "GetCustomerSessionStatsResponse",
      "type": "object"
    },
    "ObjectDisplayOptions": {
      "id": "ObjectDisplayOptions",
      "description": "The display options for an object.",
      "properties": {
        "objectDisplayLabel": {
          "description": "The user friendly label to display in the search result to indicate the type of the item. This is OPTIONAL; if not provided, an object label isn't displayed on the context line of the search results. The maximum length is 64 characters.",
          "type": "string"
        },
        "metalines": {
          "items": {
            "$ref": "Metaline"
          },
          "description": "Defines the properties that are displayed in the metalines of the search results. The property values are displayed in the order given here. If a property holds multiple values, all of the values are displayed before the next properties. For this reason, it is a good practice to specify singular properties before repeated properties in this list. All of the properties must set is_returnable to true. The maximum number of metalines is 3.",
          "type": "array"
        }
      },
      "type": "object"
    },
    "UpdateDataSourceRequest": {
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "source": {
          "$ref": "DataSource"
        }
      },
      "id": "UpdateDataSourceRequest",
      "type": "object"
    },
    "SuggestRequest": {
      "id": "SuggestRequest",
      "type": "object",
      "description": "Request of suggest API.",
      "properties": {
        "query": {
          "type": "string",
          "description": "Partial query for which autocomplete suggestions will be shown. For example, if the query is \"sea\", then the server might return \"season\", \"search\", \"seagull\" and so on."
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        },
        "dataSourceRestrictions": {
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "description": "The sources to use for suggestions. If not specified, the data sources are taken from the current search application. NOTE: Suggestions are only supported for the following sources: * Third-party data sources * PredefinedSource.PERSON * PredefinedSource.GOOGLE_DRIVE",
          "type": "array"
        }
      }
    },
    "FacetBucket": {
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object.",
      "properties": {
        "percentage": {
          "type": "integer",
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts.",
          "format": "int32"
        },
        "count": {
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Cloud Search does not guarantee facet counts for any query and facet counts might be present only intermittently, even for identical queries. Do not build dependencies on facet count existence; instead use facet ount percentages which are always returned.",
          "type": "integer",
          "format": "int32"
        },
        "value": {
          "$ref": "Value"
        }
      },
      "id": "FacetBucket",
      "type": "object"
    },
    "SearchItemsByViewUrlResponse": {
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "id": "SearchItemsByViewUrlResponse",
      "type": "object"
    },
    "GroupId": {
      "properties": {
        "spaceId": {
          "$ref": "SpaceId",
          "description": "Unique, immutable ID of the Space"
        },
        "dmId": {
          "description": "Unique, immutable ID of the Direct Message Space",
          "$ref": "DmId"
        }
      },
      "type": "object",
      "description": "Id representing a group that could be a space, a chat, or a direct message space. Which ID is set here will determine which group",
      "id": "GroupId"
    },
    "DynamiteSpacesScoringInfo": {
      "type": "object",
      "description": "This is the proto for holding space level scoring information. This data is used for logging in query-api server and for testing purposes.",
      "id": "DynamiteSpacesScoringInfo",
      "properties": {
        "spaceCreationTimestampMicros": {
          "type": "string",
          "format": "int64"
        },
        "contactsIntersectionCount": {
          "type": "number",
          "format": "double"
        },
        "affinityScore": {
          "type": "number",
          "format": "double"
        },
        "smallUnjoinedSpacesAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "numAucContacts": {
          "type": "string",
          "format": "int64"
        },
        "finalScore": {
          "format": "double",
          "type": "number"
        },
        "memberMetadataCount": {
          "type": "number",
          "format": "double"
        },
        "messageScore": {
          "type": "number",
          "format": "double"
        },
        "smallContactListAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "joinedSpacesAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "lastMessagePostedTimestampMicros": {
          "format": "int64",
          "type": "string"
        },
        "freshnessScore": {
          "format": "double",
          "type": "number"
        },
        "commonContactCountAffinityScore": {
          "type": "number",
          "format": "double"
        },
        "topicalityScore": {
          "format": "double",
          "type": "number"
        },
        "spaceAgeInDays": {
          "type": "number",
          "format": "double"
        }
      }
    },
    "DoubleOperatorOptions": {
      "description": "Used to provide a search operator for double properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "DoubleOperatorOptions",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to use the double property in sorting or as a facet. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "type": "object"
    },
    "TextValues": {
      "id": "TextValues",
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for text values is 2048 characters.",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "List of text values.",
      "type": "object"
    },
    "Item": {
      "id": "Item",
      "description": "Represents a single object that is an item in the search index, such as a file, folder, or a database record.",
      "type": "object",
      "properties": {
        "acl": {
          "description": "Access control list for this item.",
          "$ref": "ItemAcl"
        },
        "queue": {
          "description": "Queue this item belongs to. The maximum length is 100 characters.",
          "type": "string"
        },
        "status": {
          "description": "Status of the item. Output only field.",
          "$ref": "ItemStatus"
        },
        "version": {
          "description": "Required. The indexing system stores the version from the datasource as a byte string and compares the Item version in the index to the version of the queued Item using lexical ordering. Cloud Search Indexing won't index or delete any queued item with a version value that is less than or equal to the version of the currently indexed item. The maximum length for this field is 1024 bytes. For information on how item version affects the deletion process, refer to [Handle r[...]",
          "type": "string",
          "format": "byte"
        },
        "content": {
          "description": "Item content to be indexed and made text searchable.",
          "$ref": "ItemContent"
        },
        "structuredData": {
          "$ref": "ItemStructuredData",
          "description": "The structured data for the item that should conform to a registered object definition in the schema for the data source."
        },
        "payload": {
          "description": "Additional state connector can store for this item. The maximum length is 10000 bytes.",
          "format": "byte",
          "type": "string"
        },
        "metadata": {
          "$ref": "ItemMetadata",
          "description": "Metadata information."
        },
        "name": {
          "type": "string",
          "description": "Name of the Item. Format: datasources/{source_id}/items/{item_id} This is a required field. The maximum length is 1536 characters."
        },
        "itemType": {
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "description": "Type for this item.",
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information. These items cannot be referred in containerName or inheritAclFrom fields.",
            "An item that gets indexed and whose purpose is to supply other items with ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose as CONTAINER_ITEM."
          ]
        }
      }
    },
    "RepositoryError": {
      "id": "RepositoryError",
      "type": "object",
      "properties": {
        "errorMessage": {
          "description": "Message that describes the error. The maximum allowable length of the message is 8192 characters.",
          "type": "string"
        },
        "type": {
          "description": "Type of error.",
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to the repository server."
          ],
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "type": "string"
        },
        "httpStatusCode": {
          "type": "integer",
          "format": "int32",
          "description": "Error codes. Matches the definition of HTTP status codes."
        }
      },
      "description": "Errors when the connector is communicating to the source repository."
    },
    "Operation": {
      "id": "Operation",
      "description": "This resource represents a long-running operation that is the result of a network API call.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`."
        },
        "metadata": {
          "description": "Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.",
          "type": "object",
          "additionalProperties": {
            "description": "Properties of the object. Contains field @type with type URL.",
            "type": "any"
          }
        },
        "done": {
          "description": "If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.",
          "type": "boolean"
        },
        "error": {
          "description": "The error result of the operation in case of failure or cancellation.",
          "$ref": "Status"
        }
      }
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "id": "ListItemNamesForUnmappedIdentityResponse",
      "type": "object",
      "properties": {
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        },
        "itemNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "QuerySource": {
      "description": "List of sources that the user can search using the query API.",
      "type": "object",
      "id": "QuerySource",
      "properties": {
        "operators": {
          "type": "array",
          "description": "List of all operators applicable for this source.",
          "items": {
            "$ref": "QueryOperator"
          }
        },
        "source": {
          "$ref": "Source",
          "description": "Name of the source"
        },
        "shortName": {
          "type": "string",
          "description": "A short name or alias for the source. This value can be used with the 'source' operator."
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the data source."
        }
      }
    },
    "QueryInterpretationConfig": {
      "description": "Default options to interpret user query.",
      "id": "QueryInterpretationConfig",
      "type": "object",
      "properties": {
        "forceDisableSupplementalResults": {
          "description": "Set this flag to disable supplemental results retrieval, setting a flag here will not retrieve supplemental results for queries associated with a given search application. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for supplemental results.",
          "type": "boolean"
        },
        "forceVerbatimMode": {
          "type": "boolean",
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental results retrieval, and usage of synonyms including custom ones. If this flag is set to True, it will take precedence over the option set at Query level. For the default value of False, query level flag will set the correct interpretation for verbatim mode."
        }
      }
    },
    "IntegerOperatorOptions": {
      "properties": {
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the less-than operator. For example, if lessThanOperatorName is *prioritybelow* and the property's name is *priorityVal*, then queries like *prioritybelow:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is less than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the greater-than operator. For example, if greaterThanOperatorName is *priorityabove* and the property's name is *priorityVal*, then queries like *priorityabove:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* is greater than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 chara[...]",
          "type": "string"
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the integer property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any S[...]"
        }
      },
      "description": "Used to provide a search operator for integer properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "id": "IntegerOperatorOptions"
    },
    "Filter": {
      "type": "object",
      "properties": {
        "valueFilter": {
          "$ref": "ValueFilter"
        },
        "compositeFilter": {
          "$ref": "CompositeFilter"
        }
      },
      "description": "A generic way of expressing filters in a query, which supports two approaches: **1. Setting a ValueFilter.** The name must match an operator_name defined in the schema for your data source. **2. Setting a CompositeFilter.** The filters are evaluated using the logical operator. The top-level operators can only be either an AND or a NOT. AND can appear only at the top-most level. OR can appear only under a top-level AND.",
      "id": "Filter"
    },
    "DriveFollowUpRestrict": {
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ]
        }
      },
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
      "id": "DriveFollowUpRestrict",
      "type": "object"
    },
    "Name": {
      "id": "Name",
      "type": "object",
      "description": "A person's name.",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by the viewer's account or the Accept-Language HTTP header.",
          "type": "string"
        }
      }
    },
    "GetSearchApplicationUserStatsResponse": {
      "id": "GetSearchApplicationUserStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationUserStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "PollItemsRequest": {
      "properties": {
        "limit": {
          "description": "Maximum number of items to return. The maximum value is 100 and the default value is 20.",
          "type": "integer",
          "format": "int32"
        },
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "queue": {
          "description": "Queue name to fetch items from. If unspecified, PollItems will fetch from 'default' queue. The maximum length is 100 characters.",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "statusCodes": {
          "description": "Limit the items polled to the ones with these statuses.",
          "items": {
            "enum": [
              "CODE_UNSPECIFIED",
              "ERROR",
              "MODIFIED",
              "NEW_ITEM",
              "ACCEPTED"
            ],
            "type": "string",
            "enumDescriptions": [
              "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
              "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
              "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
              "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
              "API has accepted the up-to-date data of this item."
            ]
          },
          "type": "array"
        }
      },
      "type": "object",
      "id": "PollItemsRequest"
    },
    "DriveMimeTypeRestrict": {
      "id": "DriveMimeTypeRestrict",
      "type": "object",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ]
        }
      },
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\")."
    },
    "ItemAcl": {
      "id": "ItemAcl",
      "description": "Access control list information for the item. For more information see [Map ACLs](/cloud-search/docs/guides/acls).",
      "type": "object",
      "properties": {
        "deniedReaders": {
          "items": {
            "$ref": "Principal"
          },
          "type": "array",
          "description": "List of principals who are explicitly denied access to the item in search results. While principals are denied access by default, use denied readers to handle exceptions and override the list allowed readers. The maximum number of elements is 100."
        },
        "readers": {
          "description": "List of principals who are allowed to see the item in search results. Optional if inheriting permissions from another item or if the item is not intended to be visible, such as virtual containers. The maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "aclInheritanceType": {
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a parent. This should always be set in tandem with the inheritAclFrom field. Also, when the inheritAclFrom field is set, this field should be set to a valid AclInheritanceType.",
          "type": "string",
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL. Use NOT_APPLICABLE when inheritAclFrom is empty. An item without ACL inheritance can still have ACLs supplied by its own readers and deniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines its read access.",
            "During an authorization conflict, the ACL of the parent item specified in the inheritAclFrom field determines read access.",
            "Access is granted only if this item and the parent item specified in the inheritAclFrom field both permit read access."
          ],
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ]
        },
        "owners": {
          "description": "Optional. List of owners for the item. This field has no bearing on document access permissions. It does, however, offer a slight ranking boosts items where the querying user is an owner. The maximum number of elements is 5.",
          "type": "array",
          "items": {
            "$ref": "Principal"
          }
        },
        "inheritAclFrom": {
          "type": "string",
          "description": "Name of the item to inherit the Access Permission List (ACL) from. Note: ACL inheritance *only* provides access permissions to child items and does not define structural relationships, nor does it provide convenient ways to delete large groups of items. Deleting an ACL parent from the index only alters the access permissions of child items that reference the parent in the inheritAclFrom field. The item is still in the index, but may not visible in search results. By con[...]"
        }
      }
    },
    "IndexItemRequest": {
      "type": "object",
      "properties": {
        "item": {
          "description": "Name of the item. Format: datasources/{source_id}/items/{item_id}",
          "$ref": "Item"
        },
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        },
        "mode": {
          "type": "string",
          "description": "Required. The RequestMode for this request.",
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ],
          "enumDescriptions": [
            "Priority is not specified in the update request. Leaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the caller."
          ]
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "id": "IndexItemRequest"
    },
    "GetCustomerUserStatsResponse": {
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerUserStats"
          }
        }
      },
      "type": "object",
      "id": "GetCustomerUserStatsResponse"
    },
    "QueryOperator": {
      "id": "QueryOperator",
      "type": "object",
      "description": "The definition of a operator that can be used in a Search/Suggest request.",
      "properties": {
        "isSortable": {
          "type": "boolean",
          "description": "Can this operator be used to sort results."
        },
        "isRepeatable": {
          "type": "boolean",
          "description": "Indicates if multiple values can be set for this property."
        },
        "isReturnable": {
          "type": "boolean",
          "description": "Will the property associated with this facet be returned as part of search results."
        },
        "enumValues": {
          "type": "array",
          "description": "Potential list of values for the opeatror field. This field is only filled when we can safely enumerate all the possible values of this operator.",
          "items": {
            "type": "string"
          }
        },
        "objectType": {
          "type": "string",
          "description": "Name of the object corresponding to the operator. This field is only filled for schema-specific operators, and is unset for common operators."
        },
        "greaterThanOperatorName": {
          "description": "Indicates the operator name that can be used to isolate the property using the greater-than operator.",
          "type": "string"
        },
        "isSuggestable": {
          "description": "Can get suggestions for this field.",
          "type": "boolean"
        },
        "displayName": {
          "description": "Display name of the operator",
          "type": "string"
        },
        "isFacetable": {
          "type": "boolean",
          "description": "Can this operator be used to get facets."
        },
        "type": {
          "type": "string",
          "description": "Type of the operator.",
          "enum": [
            "UNKNOWN",
            "INTEGER",
            "DOUBLE",
            "TIMESTAMP",
            "BOOLEAN",
            "ENUM",
            "DATE",
            "TEXT",
            "HTML"
          ],
          "enumDescriptions": [
            "Invalid value.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ]
        },
        "operatorName": {
          "type": "string",
          "description": "The name of the operator."
        },
        "lessThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name that can be used to isolate the property using the less-than operator."
        }
      }
    },
    "DriveTimeSpanRestrict": {
      "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
      "type": "object",
      "id": "DriveTimeSpanRestrict",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "Not Enabled",
            "Not Enabled"
          ],
          "enum": [
            "UNSPECIFIED",
            "TODAY",
            "YESTERDAY",
            "LAST_7_DAYS",
            "LAST_30_DAYS",
            "LAST_90_DAYS"
          ],
          "type": "string"
        }
      }
    },
    "SearchApplicationQueryStats": {
      "description": "Search application level query stats per date",
      "type": "object",
      "id": "SearchApplicationQueryStats",
      "properties": {
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        }
      }
    },
    "Metaline": {
      "description": "A metaline is a list of properties that are displayed along with the search result to provide context.",
      "properties": {
        "properties": {
          "description": "The list of displayed properties for the metaline. The maximum number of properties is 5.",
          "type": "array",
          "items": {
            "$ref": "DisplayedProperty"
          }
        }
      },
      "type": "object",
      "id": "Metaline"
    },
    "UnmappedIdentity": {
      "properties": {
        "externalIdentity": {
          "$ref": "Principal",
          "description": "The resource name for an external user."
        },
        "resolutionStatusCode": {
          "type": "string",
          "description": "The resolution status for the external identity.",
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ],
          "enumDescriptions": [
            "Input-only value. Used to list all unmapped identities regardless of status.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by the user.",
            "The identity source associated with the identity was either not found or deleted.",
            "IDaaS does not understand the identity source, probably because the schema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ]
        }
      },
      "id": "UnmappedIdentity",
      "type": "object"
    },
    "ListItemsResponse": {
      "id": "ListItemsResponse",
      "type": "object",
      "properties": {
        "items": {
          "items": {
            "$ref": "Item"
          },
          "type": "array"
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        }
      }
    },
    "ResultDisplayField": {
      "description": "Display Fields for Search Results",
      "properties": {
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        },
        "property": {
          "$ref": "NamedProperty",
          "description": "The name value pair for the property."
        },
        "label": {
          "type": "string",
          "description": "The display label for the property."
        }
      },
      "id": "ResultDisplayField",
      "type": "object"
    },
    "AclInfo": {
      "description": "Next tag: 4",
      "properties": {
        "groupsCount": {
          "format": "int32",
          "type": "integer",
          "description": "Number of groups which have at least read access to the document."
        },
        "usersCount": {
          "type": "integer",
          "format": "int32",
          "description": "Number of users which have at least read access to the document."
        },
        "scope": {
          "enum": [
            "LIMITED",
            "DASHER_DOMAIN_WITH_LINK",
            "DASHER_DOMAIN",
            "PUBLIC_WITH_LINK",
            "PUBLIC",
            "TEAM_DRIVE"
          ],
          "description": "The scope to which the content was shared.",
          "enumDescriptions": [
            "Explicit set of people and groups.",
            "Anybody at the same domain with the link.",
            "Now it works only for google.com. Anybody at the same domain. Now it works only",
            "for google.com. Anybody with the link.",
            "Anybody.",
            "Special tag to indicate TeamDrive scope."
          ],
          "type": "string"
        }
      },
      "id": "AclInfo",
      "type": "object"
    },
    "CustomerQueryStats": {
      "type": "object",
      "id": "CustomerQueryStats",
      "properties": {
        "queryCountByStatus": {
          "items": {
            "$ref": "QueryCountByStatus"
          },
          "type": "array"
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which query stats were calculated. Stats calculated on the next day close to midnight are returned."
        }
      }
    },
    "GSuitePrincipal": {
      "id": "GSuitePrincipal",
      "type": "object",
      "properties": {
        "gsuiteUserEmail": {
          "description": "This principal references a G Suite user account",
          "type": "string"
        },
        "gsuiteGroupEmail": {
          "description": "This principal references a G Suite group account",
          "type": "string"
        },
        "gsuiteDomain": {
          "description": "This principal represents all users of the G Suite domain of the customer.",
          "type": "boolean"
        }
      }
    },
    "ErrorMessage": {
      "id": "ErrorMessage",
      "properties": {
        "errorMessage": {
          "type": "string"
        },
        "source": {
          "$ref": "Source"
        }
      },
      "type": "object",
      "description": "Error message per source response."
    },
    "ShareScope": {
      "properties": {
        "domain": {
          "type": "string",
          "description": "If scope is DOMAIN, this field contains the dasher domain, for example \"google.com\"."
        },
        "scope": {
          "enum": [
            "UNKNOWN",
            "PRIVATE",
            "LIMITED",
            "EXTENDED",
            "DASHER_DOMAIN",
            "PUBLIC"
          ],
          "description": "The scope to which the content was shared.",
          "type": "string",
          "enumDescriptions": [
            "",
            "Only the author can view the post.",
            "Viewable only by a set of people.",
            "Viewable by extended circles.",
            "",
            ""
          ]
        }
      },
      "type": "object",
      "id": "ShareScope"
    },
    "IntegerPropertyOptions": {
      "type": "object",
      "properties": {
        "minimumValue": {
          "description": "The minimum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values less than the minimum are accepted and ranked with the same weight as items indexed with the minimum value.",
          "type": "string",
          "format": "int64"
        },
        "operatorOptions": {
          "$ref": "IntegerOperatorOptions",
          "description": "If set, describes how the integer should be used as a search operator."
        },
        "maximumValue": {
          "format": "int64",
          "type": "string",
          "description": "The maximum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values greater than the maximum are accepted and ranked with the same weight as items indexed with the maximum value."
        },
        "orderedRanking": {
          "description": "Used to specify the ordered ranking for the integer. Can only be used if isRepeatable is false.",
          "enumDescriptions": [
            "There is no ranking order for the property. Results are not adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "type": "string"
        }
      },
      "description": "Options for integer properties.",
      "id": "IntegerPropertyOptions"
    },
    "HtmlOperatorOptions": {
      "id": "HtmlOperatorOptions",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the html property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator return all items where *\u003cvalue\u003e* matches the value of any html pr[...]"
        }
      },
      "description": "Used to provide a search operator for html properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object"
    },
    "GetCustomerSearchApplicationStatsResponse": {
      "id": "GetCustomerSearchApplicationStatsResponse",
      "properties": {
        "averageSearchApplicationCount": {
          "format": "int64",
          "type": "string",
          "description": "Average search application count for the given date range."
        },
        "stats": {
          "description": "Search application stats by date.",
          "items": {
            "$ref": "CustomerSearchApplicationStats"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "Response format for search application stats for a customer."
    },
    "SourceCrowdingConfig": {
      "properties": {
        "numSuggestions": {
          "format": "int32",
          "type": "integer",
          "description": "Maximum number of suggestions allowed from a source. No limits will be set on results if this value is less than or equal to 0."
        },
        "numResults": {
          "type": "integer",
          "format": "int32",
          "description": "Maximum number of results allowed from a datasource in a result page as long as results from other sources are not exhausted. Value specified must not be negative. A default value is used if this value is equal to 0. To disable crowding, set the value greater than 100."
        }
      },
      "type": "object",
      "description": "Set search results crowding limits. Crowding is a situation in which multiple results from the same source or host \"crowd out\" other results, diminishing the quality of search for users. To foster better search quality and source diversity in search results, you can set a condition to reduce repetitive results by source.",
      "id": "SourceCrowdingConfig"
    },
    "VPCSettings": {
      "id": "VPCSettings",
      "type": "object",
      "properties": {
        "project": {
          "type": "string",
          "description": "The resource name of the GCP Project to be used for VPC SC policy check. VPC security settings on this project will be honored for Cloud Search APIs after project_name has been updated through CustomerService. Format: projects/{project_id}"
        }
      }
    },
    "Metadata": {
      "description": "Metadata of a matched search result.",
      "id": "Metadata",
      "type": "object",
      "properties": {
        "thumbnailUrl": {
          "description": "The thumbnail URL of the result.",
          "type": "string"
        },
        "objectType": {
          "type": "string",
          "description": "Object type of the search result."
        },
        "fields": {
          "type": "array",
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "items": {
            "$ref": "NamedProperty"
          }
        },
        "owner": {
          "$ref": "Person",
          "description": "Owner (usually creator) of the document or object of the search result."
        },
        "createTime": {
          "description": "The creation time for this document or object in the search result.",
          "format": "google-datetime",
          "type": "string"
        },
        "updateTime": {
          "description": "The last modified date for the object in the search result. If not set in the item, the value returned here is empty. When `updateTime` is used for calculating freshness and is not set, this value defaults to 2 years from the current time.",
          "format": "google-datetime",
          "type": "string"
        },
        "displayOptions": {
          "$ref": "ResultDisplayMetadata",
          "description": "Options that specify how to display a structured data search result."
        },
        "mimeType": {
          "type": "string",
          "description": "Mime type of the search result."
        },
        "source": {
          "$ref": "Source",
          "description": "The named source for the result, such as Gmail."
        }
      }
    },
    "ContextAttribute": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched."
        },
        "name": {
          "type": "string",
          "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched."
        }
      },
      "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
      "id": "ContextAttribute"
    },
    "ResponseDebugInfo": {
      "properties": {
        "formattedDebugInfo": {
          "type": "string",
          "description": "General debug info formatted for display."
        }
      },
      "type": "object",
      "description": "Debugging information about the response.",
      "id": "ResponseDebugInfo"
    },
    "GetCustomerQueryStatsResponse": {
      "properties": {
        "stats": {
          "items": {
            "$ref": "CustomerQueryStats"
          },
          "type": "array"
        },
        "totalQueryCount": {
          "description": "Total successful query count (status code 200) for the given date range.",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "GetCustomerQueryStatsResponse",
      "type": "object"
    },
    "CustomerIndexStats": {
      "properties": {
        "date": {
          "description": "Date for which statistics were calculated.",
          "$ref": "Date"
        },
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "description": "Number of items aggregrated by status code.",
          "type": "array"
        }
      },
      "type": "object",
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "CustomerIndexStats"
    },
    "ItemStructuredData": {
      "properties": {
        "object": {
          "description": "The structured data object that should conform to a registered object definition in the schema for the data source.",
          "$ref": "StructuredDataObject"
        },
        "hash": {
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters.",
          "type": "string"
        }
      },
      "description": "Available structured data fields for the item.",
      "id": "ItemStructuredData",
      "type": "object"
    },
    "Person": {
      "type": "object",
      "properties": {
        "obfuscatedId": {
          "description": "Obfuscated ID of a person.",
          "type": "string"
        },
        "personNames": {
          "type": "array",
          "description": "The person's name",
          "items": {
            "$ref": "Name"
          }
        },
        "emailAddresses": {
          "items": {
            "$ref": "EmailAddress"
          },
          "description": "The person's email addresses",
          "type": "array"
        },
        "name": {
          "description": "The resource name of the person to provide information about. See People.get from Google People API.",
          "type": "string"
        },
        "photos": {
          "items": {
            "$ref": "Photo"
          },
          "description": "A person's read-only photo. A picture shown next to the person's name to help others recognize the person in search results.",
          "type": "array"
        }
      },
      "id": "Person",
      "description": "Object to represent a person."
    },
    "CustomerId": {
      "description": "Represents a GSuite customer ID. Obfuscated with CustomerIdObfuscator.",
      "properties": {
        "customerId": {
          "type": "string"
        }
      },
      "type": "object",
      "id": "CustomerId"
    },
    "SearchItemsByViewUrlRequest": {
      "type": "object",
      "id": "SearchItemsByViewUrlRequest",
      "properties": {
        "pageToken": {
          "description": "The next_page_token value returned from a previous request, if any.",
          "type": "string"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "viewUrl": {
          "description": "Specify the full view URL to find the corresponding item. The maximum length is 2048 characters.",
          "type": "string"
        }
      }
    },
    "CustomerSearchApplicationStats": {
      "description": "Search application stats for a customer for the given date.",
      "properties": {
        "date": {
          "description": "Date for which search application stats were calculated.",
          "$ref": "Date"
        },
        "count": {
          "type": "string",
          "format": "int64",
          "description": "The count of search applications for the date."
        }
      },
      "id": "CustomerSearchApplicationStats",
      "type": "object"
    },
    "CustomerSettings": {
      "properties": {
        "vpcSettings": {
          "$ref": "VPCSettings",
          "description": "VPC SC settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request."
        },
        "auditLoggingSettings": {
          "description": "Audit Logging settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request.",
          "$ref": "AuditLoggingSettings"
        }
      },
      "description": "Represents settings at a customer level.",
      "type": "object",
      "id": "CustomerSettings"
    },
    "Schema": {
      "type": "object",
      "description": "The schema definition for a data source.",
      "properties": {
        "operationIds": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema. After modifying the schema, wait for operations to complete before indexing additional content."
        },
        "objectDefinitions": {
          "description": "The list of top-level objects for the data source. The maximum number of elements is 10.",
          "type": "array",
          "items": {
            "$ref": "ObjectDefinition"
          }
        }
      },
      "id": "Schema"
    },
    "GetSearchApplicationQueryStatsResponse": {
      "id": "GetSearchApplicationQueryStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationQueryStats"
          },
          "description": "Query stats per date for a search application.",
          "type": "array"
        },
        "totalQueryCount": {
          "description": "Total successful query count (status code 200) for the given date range.",
          "format": "int64",
          "type": "string"
        }
      },
      "description": "Response format for getting query stats for a search application between given dates.",
      "type": "object"
    },
    "HtmlPropertyOptions": {
      "description": "Options for html properties.",
      "properties": {
        "operatorOptions": {
          "$ref": "HtmlOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        },
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval. Can only be set to DEFAULT or NONE."
        }
      },
      "id": "HtmlPropertyOptions",
      "type": "object"
    },
    "RequestOptions": {
      "type": "object",
      "description": "Shared request options for all RPC methods.",
      "properties": {
        "timeZone": {
          "description": "Current user's time zone id, such as \"America/Los_Angeles\" or \"Australia/Sydney\". These IDs are defined by [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/) project, and currently available in the file [timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml). This field is used to correctly interpret date and time queries. If this field is not specified, the default time zone (UTC) is used.",
          "type": "string"
        },
        "languageCode": {
          "description": "The BCP-47 language code, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. For translations. Set this field using the language set in browser or for the page. In the event that the user's language preference is known, set this field to the known user language. When specified, the documents in search results are biased towards the specified language. The suggest API does not use this parameter. In[...]",
          "type": "string"
        },
        "debugOptions": {
          "description": "Debug options of the request",
          "$ref": "DebugOptions"
        },
        "searchApplicationId": {
          "type": "string",
          "description": "The ID generated when you create a search application using the [admin console](https://support.google.com/a/answer/9043922)."
        }
      },
      "id": "RequestOptions"
    },
    "Interaction": {
      "description": "Represents an interaction between a user and an item.",
      "type": "object",
      "id": "Interaction",
      "properties": {
        "interactionTime": {
          "format": "google-datetime",
          "description": "The time when the user acted on the item. If multiple actions of the same type exist for a single user, only the most recent action is recorded.",
          "type": "string"
        },
        "type": {
          "enumDescriptions": [
            "Invalid value.",
            "This interaction indicates the user viewed the item.",
            "This interaction indicates the user edited the item."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "VIEW",
            "EDIT"
          ]
        },
        "principal": {
          "$ref": "Principal",
          "description": "The user that acted on the item."
        }
      }
    },
    "SearchApplicationSessionStats": {
      "id": "SearchApplicationSessionStats",
      "properties": {
        "searchSessionsCount": {
          "format": "int64",
          "description": "The count of search sessions on the day",
          "type": "string"
        },
        "date": {
          "description": "Date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned.",
          "$ref": "Date"
        }
      },
      "type": "object"
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "type": "object",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "queue": {
          "description": "Name of a queue to delete items from.",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      }
    },
    "ListQuerySourcesResponse": {
      "type": "object",
      "description": "List sources response.",
      "properties": {
        "sources": {
          "items": {
            "$ref": "QuerySource"
          },
          "type": "array"
        },
        "nextPageToken": {
          "type": "string"
        }
      },
      "id": "ListQuerySourcesResponse"
    },
    "QueryCountByStatus": {
      "properties": {
        "statusCode": {
          "type": "integer",
          "description": "This represents the http status code.",
          "format": "int32"
        },
        "count": {
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object",
      "id": "QueryCountByStatus"
    },
    "Media": {
      "properties": {
        "resourceName": {
          "description": "Name of the media resource.",
          "type": "string"
        }
      },
      "description": "Media resource.",
      "id": "Media",
      "type": "object"
    },
    "QuerySuggestion": {
      "description": "This field does not contain anything as of now and is just used as an indicator that the suggest result was a phrase completion.",
      "properties": {},
      "id": "QuerySuggestion",
      "type": "object"
    },
    "DriveLocationRestrict": {
      "description": "Drive location search restricts (e.g. \"is:starred\").",
      "type": "object",
      "id": "DriveLocationRestrict",
      "properties": {
        "type": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ]
        }
      }
    },
    "Status": {
      "id": "Status",
      "properties": {
        "code": {
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string",
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client."
        },
        "details": {
          "description": "A list of messages that carry the error details. There is a common set of message types for APIs to use.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": {
              "description": "Properties of the object. Contains field @type with type URL.",
              "type": "any"
            }
          }
        }
      },
      "type": "object",
      "description": "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors)."
    },
    "RetrievalImportance": {
      "type": "object",
      "id": "RetrievalImportance",
      "properties": {
        "importance": {
          "type": "string",
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ],
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still be used for operator matching, faceting, and suggest if desired."
          ],
          "description": "Indicates the ranking importance given to property when it is matched during retrieval. Once set, the token importance of a property cannot be changed."
        }
      }
    },
    "FacetOptions": {
      "type": "object",
      "description": "Specifies operators to return facet results for. There will be one FacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "properties": {
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet. Defaults to 10. Maximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "operatorName": {
          "type": "string",
          "description": "Name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions"
        },
        "objectType": {
          "type": "string",
          "description": "If object_type is set, only those objects of that type will be used to compute facets. If empty, then all objects will be used to compute facets."
        },
        "sourceName": {
          "type": "string",
          "description": "Source name to facet on. Format: datasources/{source_id} If empty, all data sources will be used."
        }
      }
    },
    "TextOperatorOptions": {
      "type": "object",
      "description": "Used to provide a search operator for text properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the text property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:\u003cvalue\u003e* show results only where the value of the property named *subjectLine* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any text p[...]",
          "type": "string"
        },
        "exactMatchWithOperator": {
          "type": "boolean",
          "description": "If true, the text value is tokenized as one atomic value in operator searches and facet matches. For example, if the operator name is \"genre\" and the value is \"science-fiction\" the query restrictions \"genre:science\" and \"genre:fiction\" doesn't match the item; \"genre:science-fiction\" does. Value matching is case-sensitive and does not remove special characters. If false, the text is tokenized. For example, if the value is \"science-fiction\" the queries \"genre[...]"
        }
      },
      "id": "TextOperatorOptions"
    },
    "PeopleSuggestion": {
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Suggested person. All fields of the person object might not be populated."
        }
      },
      "type": "object",
      "id": "PeopleSuggestion",
      "description": "This field contains information about the person being suggested."
    },
    "ListDataSourceResponse": {
      "type": "object",
      "properties": {
        "sources": {
          "type": "array",
          "items": {
            "$ref": "DataSource"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        }
      },
      "id": "ListDataSourceResponse"
    },
    "QueryInterpretation": {
      "type": "object",
      "properties": {
        "reason": {
          "enumDescriptions": [
            "",
            "Natural language interpretation of the query is used to fetch the search results.",
            "Query and document terms similarity is used to selectively broaden the query to retrieve additional search results since enough results were not found for the user query. Interpreted query will be empty for this case."
          ],
          "description": "The reason for interpretation of the query. This field will not be UNSPECIFIED if the interpretation type is not NONE.",
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "QUERY_HAS_NATURAL_LANGUAGE_INTENT",
            "NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY"
          ]
        },
        "interpretationType": {
          "enum": [
            "NONE",
            "BLEND",
            "REPLACE"
          ],
          "type": "string",
          "enumDescriptions": [
            "Neither the natural language interpretation, nor a broader version of the query is used to fetch the search results.",
            "The results from original query are blended with other results. The reason for blending these other results with the results from original query is populated in the 'Reason' field below.",
            "The results from original query are replaced. The reason for replacing the results from original query is populated in the 'Reason' field below."
          ]
        },
        "interpretedQuery": {
          "description": "The interpretation of the query used in search. For example, queries with natural language intent like \"email from john\" will be interpreted as \"from:john source:mail\". This field will not be filled when the reason is NOT_ENOUGH_RESULTS_FOUND_FOR_USER_QUERY.",
          "type": "string"
        }
      },
      "id": "QueryInterpretation"
    },
    "SpellResult": {
      "id": "SpellResult",
      "type": "object",
      "properties": {
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested spelling of the query."
        }
      }
    },
    "ValueFilter": {
      "id": "ValueFilter",
      "properties": {
        "value": {
          "description": "The value to be compared with.",
          "$ref": "Value"
        },
        "operatorName": {
          "description": "The `operator_name` applied to the query, such as *price_greater_than*. The filter can work against both types of filters defined in the schema for your data source: 1. `operator_name`, where the query filters results by the property that matches the value. 2. `greater_than_operator_name` or `less_than_operator_name` in your schema. The query filters the results for the property values that are greater than or less than the supplied value in the query.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SpaceId": {
      "type": "object",
      "description": "Primary key for Space resource.",
      "id": "SpaceId",
      "properties": {
        "spaceId": {
          "description": "Unique, immutable ID of the Space",
          "type": "string"
        }
      }
    },
    "ResultDisplayLine": {
      "id": "ResultDisplayLine",
      "properties": {
        "fields": {
          "items": {
            "$ref": "ResultDisplayField"
          },
          "type": "array"
        }
      },
      "description": "The collection of fields that make up a displayed line",
      "type": "object"
    },
    "DatePropertyOptions": {
      "id": "DatePropertyOptions",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the date should be used as a search operator.",
          "$ref": "DateOperatorOptions"
        }
      },
      "description": "Options for date properties."
    },
    "DateValues": {
      "description": "List of date values.",
      "type": "object",
      "properties": {
        "values": {
          "items": {
            "$ref": "Date"
          },
          "type": "array"
        }
      },
      "id": "DateValues"
    },
    "StartUploadItemRequest": {
      "id": "StartUploadItemRequest",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object",
      "description": "Start upload file request."
    },
    "SourceScoringConfig": {
      "type": "object",
      "id": "SourceScoringConfig",
      "description": "Set the scoring configuration. This allows modifying the ranking of results for a source.",
      "properties": {
        "sourceImportance": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "DEFAULT",
            "LOW",
            "HIGH"
          ],
          "description": "Importance of the source.",
          "type": "string"
        }
      }
    },
    "SourceConfig": {
      "id": "SourceConfig",
      "type": "object",
      "description": "Configurations for a source while processing a Search or Suggest request.",
      "properties": {
        "crowdingConfig": {
          "description": "The crowding configuration for the source.",
          "$ref": "SourceCrowdingConfig"
        },
        "scoringConfig": {
          "$ref": "SourceScoringConfig",
          "description": "The scoring configuration for the source."
        },
        "source": {
          "$ref": "Source",
          "description": "The source for which this configuration is to be used."
        }
      }
    },
    "FacetResult": {
      "description": "Source specific facet response",
      "id": "FacetResult",
      "properties": {
        "sourceName": {
          "type": "string",
          "description": "Source name for which facet results are returned. Will not be empty."
        },
        "objectType": {
          "type": "string",
          "description": "Object type for which facet results are returned. Can be empty."
        },
        "buckets": {
          "items": {
            "$ref": "FacetBucket"
          },
          "description": "FacetBuckets for values in response containing at least a single result.",
          "type": "array"
        },
        "operatorName": {
          "description": "Name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        }
      },
      "type": "object"
    },
    "BooleanPropertyOptions": {
      "type": "object",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the boolean should be used as a search operator.",
          "$ref": "BooleanOperatorOptions"
        }
      },
      "description": "Options for boolean properties."
    },
    "EnumPropertyOptions": {
      "type": "object",
      "properties": {
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All EnumValuePairs must provide a string value. If you specify an integer value for one EnumValuePair, then all possible EnumValuePairs must provide an integer value. Both the string value and integer value must be unique over all possible values. Once set, possible values cannot be removed or modified. If you supply an ordered ranking and think you might insert additional enum values in the future, leave gaps in[...]",
          "type": "array",
          "items": {
            "$ref": "EnumValuePair"
          }
        },
        "orderedRanking": {
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "type": "string",
          "description": "Used to specify the ordered ranking for the enumeration that determines how the integer values provided in the possible EnumValuePairs are used to rank results. If specified, integer values must be provided for all possible EnumValuePair values given for this property. Can only be used if isRepeatable is false.",
          "enumDescriptions": [
            "There is no ranking order for the property. Results aren't adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ]
        },
        "operatorOptions": {
          "description": "If set, describes how the enum should be used as a search operator.",
          "$ref": "EnumOperatorOptions"
        }
      },
      "description": "Options for enum properties, which allow you to define a restricted set of strings to match user queries, set rankings for those string values, and define an operator name to be paired with those strings so that users can narrow results to only items with a specific value. For example, for items in a request tracking system with priority information, you could define *p0* as an allowable enum value and tie this enum to the operator name *priority* so that search users could[...]",
      "id": "EnumPropertyOptions"
    },
    "UpdateSchemaRequest": {
      "id": "UpdateSchemaRequest",
      "type": "object",
      "properties": {
        "validateOnly": {
          "description": "If true, the schema will be checked for validity, but will not be registered with the data source, even if valid.",
          "type": "boolean"
        },
        "schema": {
          "$ref": "Schema",
          "description": "The new schema for the source."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      }
    },
    "UnreserveItemsRequest": {
      "id": "UnreserveItemsRequest",
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        },
        "queue": {
          "description": "Name of a queue to unreserve items from.",
          "type": "string"
        },
        "connectorName": {
          "type": "string",
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        }
      }
    },
    "ItemContent": {
      "description": "Content of an item to be indexed and surfaced by Cloud Search. Only UTF-8 encoded strings are allowed as inlineContent. If the content is uploaded and not binary, it must be UTF-8 encoded.",
      "properties": {
        "inlineContent": {
          "description": "Content that is supplied inlined within the update method. The maximum length is 102400 bytes (100 KiB).",
          "format": "byte",
          "type": "string"
        },
        "hash": {
          "type": "string",
          "description": "Hashing info calculated and provided by the API client for content. Can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "contentFormat": {
          "enumDescriptions": [
            "Invalid value.",
            "contentFormat is HTML.",
            "contentFormat is free text.",
            "contentFormat is raw bytes."
          ],
          "enum": [
            "UNSPECIFIED",
            "HTML",
            "TEXT",
            "RAW"
          ],
          "type": "string"
        },
        "contentDataRef": {
          "$ref": "UploadItemRef",
          "description": "Upload reference ID of a previously uploaded content via write method."
        }
      },
      "id": "ItemContent",
      "type": "object"
    },
    "TextPropertyOptions": {
      "properties": {
        "operatorOptions": {
          "$ref": "TextOperatorOptions",
          "description": "If set, describes how the property should be used as a search operator."
        },
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval."
        }
      },
      "type": "object",
      "description": "Options for text properties.",
      "id": "TextPropertyOptions"
    },
    "Date": {
      "type": "object",
      "id": "Date",
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "properties": {
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "format": "int32",
          "type": "integer"
        },
        "year": {
          "format": "int32",
          "description": "Year of date. Must be from 1 to 9999.",
          "type": "integer"
        },
        "month": {
          "type": "integer",
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32"
        }
      }
    },
    "Photo": {
      "description": "A person's photo.",
      "id": "Photo",
      "properties": {
        "url": {
          "type": "string",
          "description": "The URL of the photo."
        }
      },
      "type": "object"
    },
    "EnumOperatorOptions": {
      "type": "object",
      "properties": {
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the enum property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:\u003cvalue\u003e* show results only where the value of the property named *priorityVal* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Stri[...]"
        }
      },
      "description": "Used to provide a search operator for enum properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched. For example, if you provide no operator for a *priority* enum property with possible values *p0* and *p1*, a query that contains the term *p0* returns items that have *p0* as the value of the *priority* property, as well as any items that contain the string *p0* in other fields. If you provide [...]",
      "id": "EnumOperatorOptions"
    },
    "CustomEmoji": {
      "description": "Proto representation of a custom emoji. May be used in both APIs and in Spanner, but certain fields should be restricted to one or the other. See the per-field documentation for details. NEXT_TAG: 11",
      "type": "object",
      "id": "CustomEmoji",
      "properties": {
        "uuid": {
          "description": "Unique key for a custom emoji resource. Required. This field is *always* populated.",
          "type": "string"
        },
        "ownerCustomerId": {
          "description": "This field should *never* be persisted to Spanner.",
          "$ref": "CustomerId"
        },
        "shortcode": {
          "description": "User-provided, human-readable ID for the custom emoji. Users are expected to observe this field in the UI instead of the UUID. This shortcode should be unique within an organization, but has no global uniqueness guarantees, unlike the UUID. This field should *never* be persisted to Spanner.",
          "type": "string"
        },
        "createTimeMicros": {
          "type": "string",
          "format": "int64",
          "description": "Time when the Emoji was created, in microseconds. This field may be present in Spanner, within the server, or in public APIs."
        },
        "state": {
          "type": "string",
          "enum": [
            "EMOJI_STATE_UNSPECIFIED",
            "EMOJI_ENABLED",
            "EMOJI_SYSTEM_DISABLED",
            "EMOJI_HIDDEN",
            "EMOJI_DELETED"
          ],
          "description": "Snapshot of the current state of the emoji, which may differ from the source-of-truth in the CustomEmojis table. This field should *never* be persisted to Spanner.",
          "enumDescriptions": [
            "",
            "Emoji is visible and available to be used, subject to access control requirements.",
            "Emoji can no longer be used (e.g. due to a shortcode conflict), but is not removed from existing embeddings.",
            "Emoji is hidden from pickers, so new usages are not allowed, but is not removed from existing embeddings.",
            "Emoji is removed everywhere and is not available to end-users."
          ]
        },
        "readToken": {
          "description": "Opaque token that clients use to construct the URL for accessing the custom emoji’s image data. This field is intended for API consumption, and should *never* be persisted to Spanner.",
          "type": "string"
        },
        "updateTimeMicros": {
          "type": "string",
          "format": "int64"
        },
        "blobId": {
          "description": "ID for the underlying image data in Blobstore. This field should *only* be present in Spanner or within the server, but should not be exposed in public APIs.",
          "type": "string"
        },
        "creatorUserId": {
          "$ref": "UserId",
          "description": "This field should *never* be persisted to Spanner."
        }
      }
    },
    "Value": {
      "description": "Definition of a single value with generic type.",
      "properties": {
        "booleanValue": {
          "type": "boolean"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "stringValue": {
          "type": "string"
        },
        "timestampValue": {
          "type": "string",
          "format": "google-datetime"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "integerValue": {
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object",
      "id": "Value"
    },
    "ResultDisplayMetadata": {
      "id": "ResultDisplayMetadata",
      "type": "object",
      "properties": {
        "objectTypeLabel": {
          "type": "string",
          "description": "The display label for the object."
        },
        "metalines": {
          "type": "array",
          "description": "The metalines content to be displayed with the result.",
          "items": {
            "$ref": "ResultDisplayLine"
          }
        }
      }
    },
    "DoublePropertyOptions": {
      "id": "DoublePropertyOptions",
      "type": "object",
      "description": "Options for double properties.",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the double should be used as a search operator.",
          "$ref": "DoubleOperatorOptions"
        }
      }
    },
    "BooleanOperatorOptions": {
      "id": "BooleanOperatorOptions",
      "description": "Used to provide a search operator for boolean properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the boolean property. For example, if operatorName is *closed* and the property's name is *isClosed*, then queries like *closed:\u003cvalue\u003e* show results only where the value of the property named *isClosed* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any String prop[...]",
          "type": "string"
        }
      }
    },
    "SearchResult": {
      "properties": {
        "snippet": {
          "$ref": "Snippet",
          "description": "The concatenation of all snippets (summaries) available for this result."
        },
        "title": {
          "type": "string",
          "description": "Title of the search result."
        },
        "url": {
          "description": "The URL of the search result. The URL contains a Google redirect to the actual item. This URL is signed and shouldn't be changed.",
          "type": "string"
        },
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        },
        "debugInfo": {
          "$ref": "ResultDebugInfo",
          "description": "Debugging information about this search result."
        },
        "clusteredResults": {
          "description": "If source is clustered, provide list of clustered results. There will only be one level of clustered results. If current source is not enabled for clustering, this field will be empty.",
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          }
        }
      },
      "id": "SearchResult",
      "description": "Results containing indexed information for a document.",
      "type": "object"
    },
    "FieldViolation": {
      "id": "FieldViolation",
      "properties": {
        "field": {
          "type": "string",
          "description": "Path of field with violation."
        },
        "description": {
          "description": "Description of the error.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "RestrictItem": {
      "description": "Information relevant only to a restrict entry. NextId: 12",
      "id": "RestrictItem",
      "type": "object",
      "properties": {
        "driveFollowUpRestrict": {
          "$ref": "DriveFollowUpRestrict"
        },
        "driveMimeTypeRestrict": {
          "$ref": "DriveMimeTypeRestrict",
          "description": "Drive Types."
        },
        "searchOperator": {
          "type": "string",
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
        },
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        }
      }
    },
    "ListSearchApplicationsResponse": {
      "id": "ListSearchApplicationsResponse",
      "type": "object",
      "properties": {
        "searchApplications": {
          "items": {
            "$ref": "SearchApplication"
          },
          "type": "array"
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        }
      }
    },
    "VideoInfo": {
      "id": "VideoInfo",
      "type": "object",
      "properties": {
        "duration": {
          "format": "int32",
          "type": "integer",
          "description": "Duration of the video in milliseconds. This field can be absent for recently uploaded video or inaccurate sometimes."
        }
      },
      "description": "Next tag: 2"
    },
    "Id": {
      "id": "Id",
      "type": "object",
      "properties": {
        "localId": {
          "description": "The local identifier for the DirEntry (local to the creator's account). local_id + app_name is guaranteed to be unique within the creator account, but not across all User accounts. The string is case sensitive. Ignore if name_space==GAIA. NB For name_space==COSMO, all local_id's should be defined in google3/java/com/google/storage/cosmo/server/api/SpecialObjectIds.java as they have a special predefined meaning. See cosmo.client.CosmoIdFactory.createObjectId(long,String)[...]",
          "type": "string"
        },
        "creatorUserId": {
          "format": "uint64",
          "description": "The User account in which the DirEntry was originally created. If name_space==GAIA, then it's the gaia_id of the user this id is referring to.",
          "type": "string"
        },
        "nameSpace": {
          "type": "integer",
          "description": "The name space in which this id is unique (typically the application that created it). Values should be drawn from the above enum, but for experimentation, use values greater than 1000.",
          "format": "int32"
        }
      },
      "description": "Identifies a particular object, including both Users and DirEntries. This Id is unique across the entire server instance, such as the production or qa instance."
    },
    "DataSourceIndexStats": {
      "id": "DataSourceIndexStats",
      "properties": {
        "date": {
          "description": "Date for which index stats were calculated. If the date of request is not the current date then stats calculated on the next day are returned. Stats are calculated close to mid night in this case. If date of request is current date, then real time stats are returned.",
          "$ref": "Date"
        },
        "itemCountByStatus": {
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "type": "array",
          "description": "Number of items aggregrated by status code."
        }
      },
      "type": "object",
      "description": "Aggregation of items by status code as of the specified date."
    },
    "SearchApplicationUserStats": {
      "type": "object",
      "properties": {
        "date": {
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned.",
          "$ref": "Date"
        },
        "thirtyDaysActiveUsersCount": {
          "description": "The count of unique active users in the past thirty days",
          "type": "string",
          "format": "int64"
        },
        "oneDayActiveUsersCount": {
          "format": "int64",
          "description": "The count of unique active users in the past one day",
          "type": "string"
        },
        "sevenDaysActiveUsersCount": {
          "description": "The count of unique active users in the past seven days",
          "type": "string",
          "format": "int64"
        }
      },
      "id": "SearchApplicationUserStats"
    },
    "PollItemsResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "description": "Set of items from the queue available for connector to process. These items have the following subset of fields populated: version metadata.hash structured_data.hash content.hash payload status queue",
          "items": {
            "$ref": "Item"
          }
        }
      },
      "id": "PollItemsResponse"
    },
    "SortOptions": {
      "id": "SortOptions",
      "type": "object",
      "properties": {
        "sortOrder": {
          "enumDescriptions": [
            "",
            ""
          ],
          "description": "Ascending is the default sort order",
          "type": "string",
          "enum": [
            "ASCENDING",
            "DESCENDING"
          ]
        },
        "operatorName": {
          "type": "string",
          "description": "Name of the operator corresponding to the field to sort on. The corresponding property must be marked as sortable."
        }
      }
    },
    "EnumValuePair": {
      "properties": {
        "stringValue": {
          "description": "The string value of the EnumValuePair. The maximum length is 32 characters.",
          "type": "string"
        },
        "integerValue": {
          "type": "integer",
          "format": "int32",
          "description": "The integer value of the EnumValuePair which must be non-negative. Optional."
        }
      },
      "id": "EnumValuePair",
      "description": "The enumeration value pair defines two things: a required string value and an optional integer value. The string value defines the necessary query term required to retrieve that item, such as *p0* for a priority item. The integer value determines the ranking of that string value relative to other enumerated values for the same property. For example, you might associate *p0* with *0* and define another enum pair such as *p1* and *1*. You must use the integer value in combina[...]",
      "type": "object"
    },
    "FreshnessOptions": {
      "description": "Indicates which freshness property to use when adjusting search ranking for an item. Fresher, more recent dates indicate higher quality. Use the freshness option property that best works with your data. For fileshare documents, last modified time is most relevant. For calendar event data, the time when the event occurs is a more relevant freshness indicator. In this way, calendar events that occur closer to the time of the search query are considered higher quality and rank[...]",
      "id": "FreshnessOptions",
      "properties": {
        "freshnessDuration": {
          "format": "google-duration",
          "description": "The duration after which an object should be considered stale. The default value is 180 days (in seconds).",
          "type": "string"
        },
        "freshnessProperty": {
          "type": "string",
          "description": "This property indicates the freshness level of the object in the index. If set, this property must be a top-level property within the property definitions and it must be a timestamp type or date type. Otherwise, the Indexing API uses updateTime as the freshness indicator. The maximum length is 256 characters. When a property is used to calculate freshness, the value defaults to 2 years from the current time."
        }
      },
      "type": "object"
    },
    "ObjectOptions": {
      "type": "object",
      "properties": {
        "displayOptions": {
          "$ref": "ObjectDisplayOptions",
          "description": "Options that determine how the object is displayed in the Cloud Search results page."
        },
        "freshnessOptions": {
          "description": "The freshness options for an object.",
          "$ref": "FreshnessOptions"
        }
      },
      "id": "ObjectOptions",
      "description": "The options for an object."
    },
    "ErrorInfo": {
      "id": "ErrorInfo",
      "properties": {
        "errorMessages": {
          "type": "array",
          "items": {
            "$ref": "ErrorMessage"
          }
        }
      },
      "type": "object",
      "description": "Error information about the response."
    },
    "GetCustomerIndexStatsResponse": {
      "type": "object",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerIndexStats"
          },
          "description": "Summary of indexed item counts, one for each day in the requested range."
        },
        "averageIndexedItemCount": {
          "description": "Average item count for the given date range for which billing is done.",
          "format": "int64",
          "type": "string"
        }
      },
      "id": "GetCustomerIndexStatsResponse"
    },
    "PushItemRequest": {
      "id": "PushItemRequest",
      "type": "object",
      "properties": {
        "connectorName": {
          "description": "Name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "item": {
          "$ref": "PushItem",
          "description": "Item to push onto the queue."
        }
      }
    },
    "DoubleValues": {
      "id": "DoubleValues",
      "properties": {
        "values": {
          "items": {
            "format": "double",
            "type": "number"
          },
          "type": "array"
        }
      },
      "description": "List of double values.",
      "type": "object"
    },
    "TypeInfo": {
      "id": "TypeInfo",
      "description": "Next tag: 2",
      "properties": {
        "videoInfo": {
          "$ref": "VideoInfo",
          "description": "Contains additional video information only if document_type is VIDEO."
        }
      },
      "type": "object"
    },
    "QueryInterpretationOptions": {
      "description": "Options to interpret user query.",
      "id": "QueryInterpretationOptions",
      "properties": {
        "disableNlInterpretation": {
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is false, Set to true to disable natural language interpretation. NL interpretation only applies to predefined datasources.",
          "type": "boolean"
        },
        "enableVerbatimMode": {
          "type": "boolean",
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental result retrieval, and usage of synonyms including custom ones. Nl interpretation will be disabled if either one of the two flags is true."
        },
        "disableSupplementalResults": {
          "description": "Use this flag to disable supplemental results for a query. Supplemental results setting chosen at SearchApplication level will take precedence if set to True.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "TimestampValues": {
      "type": "object",
      "properties": {
        "values": {
          "items": {
            "type": "string",
            "format": "google-datetime"
          },
          "type": "array"
        }
      },
      "id": "TimestampValues",
      "description": "List of timestamp values."
    },
    "ItemStatus": {
      "id": "ItemStatus",
      "type": "object",
      "description": "This contains item's status and any errors.",
      "properties": {
        "processingErrors": {
          "description": "Error details in case the item is in ERROR state.",
          "type": "array",
          "items": {
            "$ref": "ProcessingError"
          }
        },
        "code": {
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status code.",
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "repositoryErrors": {
          "description": "Repository error reported by connector.",
          "type": "array",
          "items": {
            "$ref": "RepositoryError"
          }
        }
      }
    },
    "UserId": {
      "type": "object",
      "description": "Primary key for User resource.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Opaque, server-assigned ID of the User."
        },
        "type": {
          "enumDescriptions": [
            "Notes on HUMAN type: 1) Leaving UserId.UserType field empty will return HUMAN as default value. This is expected because all the existing UserIds are without explicitly setting UserType, most of which are HUMAN Ids. For Bot Ids we will always set BOT in UserType field. 2) DO NOT explicitly set HUMAN as type. This is a proto2 issue, that a UserId with explicitly set default value HUMAN as type is NOT equal to an id without setting the field. aka. UserId id1 = UserId.newBuilder() .set[...]",
            ""
          ],
          "enum": [
            "HUMAN",
            "BOT"
          ],
          "description": "Clients do not need to send UserType to Backend, but Backend will always send this field to clients per the following rule: 1. For HUMAN Ids, the field is empty but by default .getType() will return HUMAN. 2. For BOT Ids, the field is ALWAYS set to BOT.",
          "type": "string"
        },
        "originAppId": {
          "description": "Optional. Identifier of the App involved (directly or on behalf of a human creator) in creating this message. This is not set if the user posted a message directly, but is used in the case of, for example, a message being generated by a 1P integration based on a user action (creating an event, creating a task etc). This should only be used on the BE. For clients, please use the field in the FE message proto instead (google3/apps/dynamite/v1/frontend/api/message.proto?q=[...]",
          "$ref": "AppId"
        },
        "actingUserId": {
          "description": "Optional. Opaque, server-assigned ID of the user profile associated with App/user acting on behalf of the human user. This is currently only set when a 3P application is acting on the user's behalf.",
          "type": "string"
        }
      },
      "id": "UserId"
    },
    "IndexItemOptions": {
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow gsuite principals that do not exist or are deleted in the index request.",
          "type": "boolean"
        }
      },
      "type": "object",
      "id": "IndexItemOptions"
    },
    "GetDataSourceIndexStatsResponse": {
      "type": "object",
      "id": "GetDataSourceIndexStatsResponse",
      "properties": {
        "averageIndexedItemCount": {
          "type": "string",
          "format": "int64",
          "description": "Average item count for the given date range for which billing is done."
        },
        "stats": {
          "description": "Summary of indexed item counts, one for each day in the requested range.",
          "items": {
            "$ref": "DataSourceIndexStats"
          },
          "type": "array"
        }
      }
    },
    "ItemCountByStatus": {
      "type": "object",
      "id": "ItemCountByStatus",
      "properties": {
        "statusCode": {
          "description": "Status of the items.",
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ]
        },
        "indexedItemsCount": {
          "format": "int64",
          "type": "string",
          "description": "Number of items matching the status code for which billing is done. This excludes virtual container items from the total count. This count would not be applicable for items with ERROR or NEW_ITEM status code."
        },
        "count": {
          "type": "string",
          "description": "Number of items matching the status code.",
          "format": "int64"
        }
      }
    },
    "DataSourceRestriction": {
      "description": "Restriction on Datasource.",
      "properties": {
        "source": {
          "description": "The source of restriction.",
          "$ref": "Source"
        },
        "filterOptions": {
          "items": {
            "$ref": "FilterOptions"
          },
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
          "type": "array"
        }
      },
      "type": "object",
      "id": "DataSourceRestriction"
    },
    "Emoji": {
      "id": "Emoji",
      "properties": {
        "customEmoji": {
          "description": "A custom emoji.",
          "$ref": "CustomEmoji"
        },
        "unicode": {
          "description": "A basic emoji represented by a unicode string.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "GoogleDocsResultInfo": {
      "id": "GoogleDocsResultInfo",
      "type": "object",
      "description": "A message containing information about a specific result. This information is passed to the scorer and beyond; in particular, GWS relies on it to format the result in the UI. Split from GoogleDocsMetadata in case we later want to reuse the message.",
      "properties": {
        "cosmoNameSpace": {
          "format": "int32",
          "type": "integer",
          "description": "For Cosmo objects, the Cosmo namespace the object was in. This allows downstream clients to identify whether a document was created in Writely or Kix, Presently or Punch, or whether it was uploaded from GDrive. See storage_cosmo.Id.NAME_SPACE for a list of all Cosmo name spaces."
        },
        "encryptedId": {
          "type": "string",
          "description": "The encrypted (user-visible) id of this object. Knowing the id is sufficient to create a canonical URL for this document."
        },
        "cosmoId": {
          "$ref": "Id",
          "description": "The storage identifier for the object in Cosmo. This field is intended to used by Stratus/Moonshine integration only. It should not be exposed externally (please refer to encrypted_id for that purpose)."
        },
        "shareScope": {
          "$ref": "ShareScope",
          "description": "The visibility indicator in the UI will be based upon this."
        },
        "mimeType": {
          "description": "The mimetype of the document.",
          "type": "string"
        },
        "attachmentSha1": {
          "description": "The SHA1 hash of the object in Drive, if any.",
          "type": "string"
        }
      }
    },
    "SearchResponse": {
      "id": "SearchResponse",
      "description": "The search API response.",
      "type": "object",
      "properties": {
        "resultCountExact": {
          "type": "string",
          "description": "The exact result count for this query.",
          "format": "int64"
        },
        "debugInfo": {
          "description": "Debugging information about the response.",
          "$ref": "ResponseDebugInfo"
        },
        "resultCounts": {
          "$ref": "ResultCounts",
          "description": "Expanded result count information."
        },
        "queryInterpretation": {
          "$ref": "QueryInterpretation",
          "description": "Query interpretation result for user query. Empty if query interpretation is disabled."
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "spellResults": {
          "type": "array",
          "items": {
            "$ref": "SpellResult"
          },
          "description": "Suggested spelling for the query."
        },
        "results": {
          "type": "array",
          "description": "Results from a search query.",
          "items": {
            "$ref": "SearchResult"
          }
        },
        "resultCountEstimate": {
          "type": "string",
          "format": "int64",
          "description": "The estimated result count for this query."
        },
        "structuredResults": {
          "type": "array",
          "description": "Structured results for the user query. These results are not counted against the page_size.",
          "items": {
            "$ref": "StructuredResult"
          }
        },
        "hasMoreResults": {
          "description": "Whether there are more search results matching the query.",
          "type": "boolean"
        },
        "facetResults": {
          "description": "Repeated facet results.",
          "type": "array",
          "items": {
            "$ref": "FacetResult"
          }
        }
      }
    },
    "ResultCounts": {
      "type": "object",
      "description": "Result count information",
      "id": "ResultCounts",
      "properties": {
        "sourceResultCounts": {
          "description": "Result count information for each source with results.",
          "type": "array",
          "items": {
            "$ref": "SourceResultCount"
          }
        }
      }
    },
    "ObjectDefinition": {
      "type": "object",
      "description": "The definition for an object within a data source.",
      "properties": {
        "options": {
          "$ref": "ObjectOptions",
          "description": "The optional object-specific options."
        },
        "name": {
          "description": "Name for the object, which then defines its type. Item indexing requests should set the objectType field equal to this value. For example, if *name* is *Document*, then indexing requests for items of type Document should set objectType equal to *Document*. Each object definition must be uniquely named within a schema. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The maximum length is 256 characters.",
          "type": "string"
        },
        "propertyDefinitions": {
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          },
          "description": "The property definitions for the object. The maximum number of elements is 1000."
        }
      },
      "id": "ObjectDefinition"
    },
    "ResultDebugInfo": {
      "properties": {
        "formattedDebugInfo": {
          "type": "string",
          "description": "General debug info formatted for display."
        }
      },
      "id": "ResultDebugInfo",
      "description": "Debugging information about the result.",
      "type": "object"
    },
    "AvatarInfo": {
      "properties": {
        "emoji": {
          "$ref": "Emoji"
        }
      },
      "type": "object",
      "id": "AvatarInfo"
    },
    "TimestampOperatorOptions": {
      "id": "TimestampOperatorOptions",
      "description": "Used to provide a search operator for timestamp properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "properties": {
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is later than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property. For example, if operatorName is *closedon* and the property's name is *closeDate*, then queries like *closedon:\u003cvalue\u003e* show results only where the value of the property named *closeDate* matches *\u003cvalue\u003e*. By contrast, a search that uses the same *\u003cvalue\u003e* without an operator returns all items where *\u003cvalue\u003e* matches the value of any Str[...]"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:\u003cvalue\u003e* show results only where the value of the property named *closeDate* is earlier than *\u003cvalue\u003e*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      }
    },
    "FilterOptions": {
      "properties": {
        "filter": {
          "$ref": "Filter",
          "description": "Generic filter to restrict the search, such as `lang:en`, `site:xyz`."
        },
        "objectType": {
          "type": "string",
          "description": "If object_type is set, only objects of that type are returned. This should correspond to the name of the object that was registered within the definition of schema. The maximum length is 256 characters."
        }
      },
      "id": "FilterOptions",
      "type": "object",
      "description": "Filter options to be applied on query."
    },
    "Snippet": {
      "properties": {
        "matchRanges": {
          "items": {
            "$ref": "MatchRange"
          },
          "description": "The matched ranges in the snippet.",
          "type": "array"
        },
        "snippet": {
          "description": "The snippet of the document. The snippet of the document. May contain escaped HTML character that should be unescaped prior to rendering.",
          "type": "string"
        }
      },
      "description": "Snippet of the search result, which summarizes the content of the resulting page.",
      "type": "object",
      "id": "Snippet"
    },
    "ObjectPropertyOptions": {
      "description": "Options for object properties.",
      "type": "object",
      "properties": {
        "subobjectProperties": {
          "description": "The properties of the sub-object. These properties represent a nested object. For example, if this property represents a postal address, the subobjectProperties might be named *street*, *city*, and *state*. The maximum number of elements is 1000.",
          "type": "array",
          "items": {
            "$ref": "PropertyDefinition"
          }
        }
      },
      "id": "ObjectPropertyOptions"
    },
    "ObjectValues": {
      "id": "ObjectValues",
      "type": "object",
      "description": "List of object values.",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      }
    },
    "ItemMetadata": {
      "type": "object",
      "properties": {
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. The maximum length is 32 characters.",
          "type": "string"
        },
        "createTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The time when the item was created in the source repository."
        },
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "updateTime": {
          "description": "The time when the item was last modified in the source repository.",
          "format": "google-datetime",
          "type": "string"
        },
        "title": {
          "description": "The title of the item. If given, this will be the displayed title of the Search result. The maximum length is 2048 characters.",
          "type": "string"
        },
        "sourceRepositoryUrl": {
          "description": "Link to the source repository serving the data. Seach results apply this link to the title. Whitespace or special characters may cause Cloud Seach result links to trigger a redirect notice; to avoid this, encode the URL. The maximum length is 2048 characters.",
          "type": "string"
        },
        "contextAttributes": {
          "type": "array",
          "items": {
            "$ref": "ContextAttribute"
          },
          "description": "A set of named attributes associated with the item. This can be used for influencing the ranking of the item based on the context in the request. The maximum number of elements is 10."
        },
        "searchQualityMetadata": {
          "$ref": "SearchQualityMetadata",
          "description": "Additional search quality metadata of the item"
        },
        "mimeType": {
          "description": "The original mime-type of ItemContent.content in the source repository. The maximum length is 256 characters.",
          "type": "string"
        },
        "objectType": {
          "description": "The type of the item. This should correspond to the name of an object definition in the schema registered for the data source. For example, if the schema for the data source contains an object definition with name 'document', then item indexing requests for objects of that type should set objectType to 'document'. The maximum length is 256 characters.",
          "type": "string"
        },
        "containerName": {
          "type": "string",
          "description": "The name of the container for this item. Deletion of the container item leads to automatic deletion of this item. Note: ACLs are not inherited from a container item. To provide ACL inheritance for an item, use the inheritAclFrom field. The maximum length is 1536 characters."
        },
        "interactions": {
          "items": {
            "$ref": "Interaction"
          },
          "description": "A list of interactions for the item. Interactions are used to improve Search quality, but are not exposed to end users. The maximum number of elements is 1000.",
          "type": "array"
        },
        "keywords": {
          "items": {
            "type": "string"
          },
          "type": "array",
          "description": "Additional keywords or phrases that should match the item. Used internally for user generated content. The maximum number of elements is 100. The maximum length is 8192 characters."
        }
      },
      "description": "Available metadata fields for the item.",
      "id": "ItemMetadata"
    },
    "TimestampPropertyOptions": {
      "description": "Options for timestamp properties.",
      "type": "object",
      "properties": {
        "operatorOptions": {
          "$ref": "TimestampOperatorOptions",
          "description": "If set, describes how the timestamp should be used as a search operator."
        }
      },
      "id": "TimestampPropertyOptions"
    },
    "QueryItem": {
      "type": "object",
      "id": "QueryItem",
      "description": "Information relevant only to a query entry.",
      "properties": {
        "isSynthetic": {
          "description": "True if the text was generated by means other than a previous user search.",
          "type": "boolean"
        }
      }
    },
    "NamedProperty": {
      "description": "A typed name-value pair for structured data. The type of the value should be the same as the registered type for the `name` property in the object definition of `objectType`.",
      "properties": {
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "name": {
          "type": "string",
          "description": "The name of the property. This name should correspond to the name of the property that was registered for object definition in the schema. The maximum allowable length for this property is 256 characters."
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "textValues": {
          "$ref": "TextValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        }
      },
      "id": "NamedProperty",
      "type": "object"
    },
    "Source": {
      "properties": {
        "predefinedSource": {
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "description": "Predefined content source for Google Apps.",
          "type": "string",
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used with the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used with the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ]
        },
        "name": {
          "type": "string",
          "description": "Source name for content indexed by the Indexing API."
        }
      },
      "type": "object",
      "description": "Defines sources for the suggest/search APIs.",
      "id": "Source"
    },
    "AuditLoggingSettings": {
      "description": "Represents the settings for Cloud audit logging",
      "properties": {
        "logDataReadActions": {
          "type": "boolean",
          "description": "Indicates whether audit logging is on/off for data access read APIs i.e. ListItems, GetItem etc."
        },
        "project": {
          "type": "string",
          "description": "The resource name of the GCP Project to store audit logs. Cloud audit logging will be enabled after project_name has been updated through CustomerService. Format: projects/{project_id}"
        },
        "logAdminReadActions": {
          "type": "boolean",
          "description": "Indicates whether audit logging is on/off for admin activity read APIs i.e. Get/List DataSources, Get/List SearchApplications etc."
        },
        "logDataWriteActions": {
          "description": "Indicates whether audit logging is on/off for data access write APIs i.e. IndexItem etc.",
          "type": "boolean"
        }
      },
      "id": "AuditLoggingSettings",
      "type": "object"
    },
    "EmailAddress": {
      "description": "A person's email address.",
      "type": "object",
      "id": "EmailAddress",
      "properties": {
        "emailAddress": {
          "type": "string",
          "description": "The email address."
        }
      }
    },
    "CustomerUserStats": {
      "id": "CustomerUserStats",
      "type": "object",
      "properties": {
        "sevenDaysActiveUsersCount": {
          "format": "int64",
          "description": "The count of unique active users in the past seven days",
          "type": "string"
        },
        "oneDayActiveUsersCount": {
          "format": "int64",
          "type": "string",
          "description": "The count of unique active users in the past one day"
        },
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past thirty days",
          "format": "int64"
        },
        "date": {
          "$ref": "Date",
          "description": "Date for which session stats were calculated. Stats calculated on the next day close to midnight are returned."
        }
      }
    },
    "PropertyDefinition": {
      "properties": {
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "displayOptions": {
          "$ref": "PropertyDisplayOptions",
          "description": "Options that determine how the property is displayed in the Cloud Search results page if it is specified to be displayed in the object's display options ."
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "isWildcardSearchable": {
          "type": "boolean",
          "description": "Indicates that users can perform wildcard search for this property. Only supported for Text properties. IsReturnable must be true to set this option. In a given datasource maximum of 5 properties can be marked as is_wildcard_searchable."
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "isReturnable": {
          "description": "Indicates that the property identifies data that should be returned in search results via the Query API. If set to *true*, indicates that Query API users can use matching property fields in results. However, storing fields requires more space allocation and uses more bandwidth for search queries, which impacts performance over large datasets. Set to *true* here only if the field is needed for search results. Cannot be true for properties whose type is an object.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a document only has one description but can have multiple comments. Cannot be true for properties whose type is a boolean. If set to false, properties that contain more than one value cause the indexing request for that item to be rejected.",
          "type": "boolean"
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "isFacetable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for generating facets. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for Boolean, Enum, and Text properties."
        },
        "name": {
          "description": "The name of the property. Item indexing requests sent to the Indexing API should set the property name equal to this value. For example, if name is *subject_line*, then indexing requests for document items with subject fields should set the name for that field equal to *subject_line*. Use the name as the identifier for the object property. Once registered as a property for an object, you cannot re-use this name for another property within that object. The name must star[...]",
          "type": "string"
        },
        "isSortable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for sorting. Cannot be true for properties that are repeatable. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for Boolean, Date, Double, Integer, and Timestamp properties."
        },
        "isSuggestable": {
          "description": "Indicates that the property can be used for generating query suggestions.",
          "type": "boolean"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        }
      },
      "type": "object",
      "description": "The definition of a property within an object.",
      "id": "PropertyDefinition"
    },
    "GoogleDocsMetadata": {
      "id": "GoogleDocsMetadata",
      "description": "The corpus specific metadata for office-type documents, from Google Docs and other sources. This message is passed to the scorer and beyond. Next tag: 7",
      "type": "object",
      "properties": {
        "fileExtension": {
          "type": "string",
          "description": "The file extension of the document. NOTE: As of October 2018 this field is not backfilled for old documents."
        },
        "documentType": {
          "enumDescriptions": [
            "If the type is unknown or not represented in this enum.",
            "Writely, Word, etc.",
            "Presently, PowerPoint, etc.",
            "Trix, Excel, etc.",
            "File types for Gdrive objects are below.",
            "",
            "Fall-back for unknown Gdrive types.",
            "",
            "",
            "",
            "",
            "",
            "For Atari page and site drafts",
            "",
            "Jamboard Jams (go/jam)",
            "Drive Shortcuts (go/shortcuts)",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "PDF",
            "IMAGE",
            "BINARY_BLOB",
            "FUSION_TABLE",
            "FOLDER",
            "DRAWING",
            "VIDEO",
            "FORM",
            "DRAFT_SITE",
            "DRAFT_SITE_PAGE",
            "JAM",
            "SHORTCUT",
            "SCRIPT"
          ],
          "description": "The conceptual type (presentation, document, etc.) of this document.",
          "type": "string"
        },
        "lastContentModifiedTimestamp": {
          "format": "int64",
          "type": "string",
          "description": "The last time this document was modified, in seconds since epoch. Only counts content modifications."
        },
        "resultInfo": {
          "$ref": "GoogleDocsResultInfo",
          "description": "Additional per-result information, akin to Gmail's SingleThreadResponse. Note: GWS no longer seems to use this field, but there's still one reference to it for Scribe, so we can't remove it."
        },
        "typeInfo": {
          "description": "Contains additional information about the document depending on its type.",
          "$ref": "TypeInfo"
        },
        "aclInfo": {
          "description": "Contains number of users and groups which can access the document.",
          "$ref": "AclInfo"
        }
      }
    },
    "SuggestResult": {
      "type": "object",
      "properties": {
        "peopleSuggestion": {
          "$ref": "PeopleSuggestion",
          "description": "This is present when the suggestion indicates a person. It contains more information about the person - like their email ID, name etc."
        },
        "source": {
          "description": "The source of the suggestion.",
          "$ref": "Source"
        },
        "querySuggestion": {
          "$ref": "QuerySuggestion",
          "description": "This field will be present if the suggested query is a word/phrase completion."
        },
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested query that will be used for search, when the user clicks on the suggestion"
        }
      },
      "description": "One suggestion result.",
      "id": "SuggestResult"
    },
    "PropertyDisplayOptions": {
      "type": "object",
      "properties": {
        "displayLabel": {
          "description": "The user friendly label for the property that is used if the property is specified to be displayed in ObjectDisplayOptions. If provided, the display label is shown in front of the property values when the property is part of the object display options. For example, if the property value is '1', the value by itself may not be useful context for the user. If the display name given was 'priority', then the user sees 'priority : 1' in the search results which provides clear[...]",
          "type": "string"
        }
      },
      "id": "PropertyDisplayOptions",
      "description": "The display options for a property."
    },
    "AppId": {
      "id": "AppId",
      "type": "object",
      "properties": {
        "gsuiteAppType": {
          "enum": [
            "GSUITE_APP_TYPE_UNSPECIFIED",
            "TASKS_APP",
            "CALENDAR_APP",
            "DOCS_APP",
            "SHEETS_APP",
            "SLIDES_APP",
            "MEET_APP",
            "ASSISTIVE_SUGGESTION_APP",
            "CONTACTS_APP",
            "ACTIVITY_FEED_APP",
            "DRIVE_APP"
          ],
          "type": "string",
          "description": "Enum indicating which 1P App this is when app_type is GSUITE_APP. Determined & set by the 1P API as a convenience for all users of this identifier(Eg. clients, chime, backend etc.) to map to 1P properties.",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Powered by Bullseye",
            "",
            "",
            ""
          ]
        },
        "id": {
          "description": "Numeric identifier of the App. Set to Project number for 1/3P Apps. For Webhook, this is WebhookId. Determined & set by the 1P API from App credentials on the side channel.",
          "type": "string",
          "format": "int64"
        },
        "appType": {
          "enumDescriptions": [
            "",
            "3P APP eg. external Bots(Asana Bot), 1P Bots(Drive Bot).",
            "1P APP eg. Tasks, Meet, Docs, Calendar..",
            "Asynchronous messages via an incoming webhook."
          ],
          "type": "string",
          "description": "Enum indicating the type of App this is.",
          "enum": [
            "APP_TYPE_UNSPECIFIED",
            "APP",
            "GSUITE_APP",
            "INCOMING_WEBHOOK"
          ]
        }
      },
      "description": "Identifier of an App."
    },
    "ResetSearchApplicationRequest": {
      "id": "ResetSearchApplicationRequest",
      "type": "object",
      "properties": {
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      }
    },
    "PushItem": {
      "description": "Represents an item to be pushed to the indexing queue.",
      "properties": {
        "queue": {
          "description": "Queue to which this item belongs to. The default queue is chosen if this field is not specified. The maximum length is 512 characters.",
          "type": "string"
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details. This information is displayed in the Admin Console. This field may only be populated when the Type is REPOSITORY_ERROR."
        },
        "structuredDataHash": {
          "type": "string",
          "description": "Structured data hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        },
        "contentHash": {
          "description": "Content hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "metadataHash": {
          "description": "Metadata hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "type": {
          "enumDescriptions": [
            "Default UNSPECIFIED. Specifies that the push operation should not modify ItemStatus",
            "Indicates that the repository document has been modified or updated since the previous update call. This changes status to MODIFIED state for an existing item. If this is called on a non existing item, the status is changed to NEW_ITEM.",
            "Item in the repository has not been modified since the last update call. This push operation will set status to ACCEPTED state.",
            "Connector is facing a repository error regarding this item. Change status to REPOSITORY_ERROR state. Item is unreserved and rescheduled at a future time determined by exponential backoff.",
            "Call push with REQUEUE only for items that have been reserved. This action unreserves the item and resets its available time to the wall clock time."
          ],
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ],
          "type": "string",
          "description": "The type of the push operation that defines the push behavior."
        },
        "payload": {
          "type": "string",
          "format": "byte",
          "description": "Provides additional document state information for the connector, such as an alternate repository ID and other metadata. The maximum length is 8192 bytes."
        }
      },
      "id": "PushItem",
      "type": "object"
    },
    "ProcessingError": {
      "id": "ProcessingError",
      "type": "object",
      "properties": {
        "errorMessage": {
          "description": "Description of the error.",
          "type": "string"
        },
        "code": {
          "enumDescriptions": [
            "Input only value. Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state. FieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other items with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ],
          "description": "Error code indicating the nature of the error.",
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "type": "string"
        },
        "fieldViolations": {
          "items": {
            "$ref": "FieldViolation"
          },
          "description": "In case the item fields are invalid, this field contains the details about the validation errors.",
          "type": "array"
        }
      }
    },
    "InitializeCustomerRequest": {
      "description": "Request message for `InitializeCustomer` method.",
      "id": "InitializeCustomerRequest",
      "properties": {},
      "type": "object"
    },
    "Principal": {
      "properties": {
        "gsuitePrincipal": {
          "$ref": "GSuitePrincipal",
          "description": "This principal is a GSuite user, group or domain."
        },
        "userResourceName": {
          "type": "string",
          "description": "This principal is a user identified using an external identity. The name field must specify the user resource name with this format: identitysources/{source_id}/users/{ID}"
        },
        "groupResourceName": {
          "type": "string",
          "description": "This principal is a group identified using an external identity. The name field must specify the group resource name with this format: identitysources/{source_id}/groups/{ID}"
        }
      },
      "type": "object",
      "id": "Principal",
      "description": "Reference to a user, group, or domain."
    },
    "EnumValues": {
      "description": "List of enum values.",
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The maximum allowable length for string values is 32 characters."
        }
      },
      "id": "EnumValues"
    },
    "SearchRequest": {
      "id": "SearchRequest",
      "description": "The search API request.",
      "type": "object",
      "properties": {
        "start": {
          "type": "integer",
          "description": "Starting index of the results.",
          "format": "int32"
        },
        "sortOptions": {
          "$ref": "SortOptions",
          "description": "The options for sorting the search results"
        },
        "contextAttributes": {
          "items": {
            "$ref": "ContextAttribute"
          },
          "type": "array",
          "description": "Context attributes for the request which will be used to adjust ranking of search results. The maximum number of elements is 10."
        },
        "query": {
          "description": "The raw query string. See supported search operators in the [Narrow your search with operators](https://support.google.com/cloudsearch/answer/6172299)",
          "type": "string"
        },
        "dataSourceRestrictions": {
          "description": "The sources to use for querying. If not specified, all data sources from the current search application are used.",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        },
        "pageSize": {
          "description": "Maximum number of search results to return in one page. Valid values are between 1 and 100, inclusive. Default value is 10. Minimum value is 50 when results beyond 2000 are requested.",
          "type": "integer",
          "format": "int32"
        },
        "facetOptions": {
          "type": "array",
          "items": {
            "$ref": "FacetOptions"
          }
        },
        "queryInterpretationOptions": {
          "$ref": "QueryInterpretationOptions",
          "description": "Options to interpret the user query."
        },
        "requestOptions": {
          "$ref": "RequestOptions",
          "description": "Request options, such as the search application and user timezone."
        }
      }
    },
    "UploadItemRef": {
      "description": "Represents an upload session reference. This reference is created via upload method. This reference is valid for 30 days after its creation. Updating of item content may refer to this uploaded content via contentDataRef.",
      "type": "object",
      "id": "UploadItemRef",
      "properties": {
        "name": {
          "description": "Name of the content reference. The maximum length is 2048 characters.",
          "type": "string"
        }
      }
    },
    "HtmlValues": {
      "type": "object",
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for html values is 2048 characters.",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "List of html values.",
      "id": "HtmlValues"
    },
    "ListUnmappedIdentitiesResponse": {
      "id": "ListUnmappedIdentitiesResponse",
      "type": "object",
      "properties": {
        "unmappedIdentities": {
          "type": "array",
          "items": {
            "$ref": "UnmappedIdentity"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      }
    },
    "GetSearchApplicationSessionStatsResponse": {
      "id": "GetSearchApplicationSessionStatsResponse",
      "properties": {
        "stats": {
          "items": {
            "$ref": "SearchApplicationSessionStats"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "SourceResultCount": {
      "type": "object",
      "properties": {
        "resultCountEstimate": {
          "format": "int64",
          "type": "string",
          "description": "The estimated result count for this source."
        },
        "resultCountExact": {
          "description": "The exact result count for this source.",
          "type": "string",
          "format": "int64"
        },
        "source": {
          "$ref": "Source",
          "description": "The source the result count information is associated with."
        },
        "hasMoreResults": {
          "description": "Whether there are more search results for this source.",
          "type": "boolean"
        }
      },
      "id": "SourceResultCount",
      "description": "Per source result count information."
    }
  },
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "ownerName": "Google",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "version_module": true,
  "resources": {
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "checkAccess": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "description": "Checks whether an item is accessible by specified principal. Principal must be a user; groups and domain values aren't supported. **Note:** This API requires an admin account to execute.",
                  "path": "v1/debug/{+name}:checkAccess",
                  "id": "cloudsearch.debug.datasources.items.checkAccess"
                },
                "searchByViewUrl": {
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "POST",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl"
                }
              },
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "httpMethod": "GET",
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "path": "v1/debug/{+parent}/unmappedids",
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute."
                    }
                  }
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "unmappedids": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "path": "v1/debug/{+parent}/unmappedids"
                }
              }
            },
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute."
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "datasources": {
          "methods": {
            "create": {
              "flatPath": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.create",
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/datasources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "POST"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.settings.datasources.update",
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/{+name}",
              "httpMethod": "PUT",
              "flatPath": "v1/settings/datasources/{datasourcesId}"
            },
            "get": {
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute.",
              "httpMethod": "GET",
              "path": "v1/settings/{+name}",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.settings.datasources.get"
            },
            "list": {
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources",
              "description": "Lists datasources. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.datasources.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.datasources.delete"
            }
          }
        },
        "searchapplications": {
          "methods": {
            "delete": {
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "id": "cloudsearch.settings.searchapplications.delete",
              "httpMethod": "DELETE"
            },
            "reset": {
              "id": "cloudsearch.settings.searchapplications.reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "path": "v1/settings/{+name}:reset",
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
              "httpMethod": "POST",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications",
              "path": "v1/settings/searchapplications",
              "id": "cloudsearch.settings.searchapplications.list"
            },
            "get": {
              "id": "cloudsearch.settings.searchapplications.get",
              "path": "v1/settings/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}"
            },
            "update": {
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "PUT",
              "id": "cloudsearch.settings.searchapplications.update",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Updates a search application. **Note:** This API requires an admin account to execute."
            },
            "create": {
              "path": "v1/settings/searchapplications",
              "httpMethod": "POST",
              "description": "Creates a search application. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.searchapplications.create",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "flatPath": "v1/settings/searchapplications"
            }
          }
        }
      },
      "methods": {
        "updateCustomer": {
          "path": "v1/settings/customer",
          "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1/settings/customer",
          "id": "cloudsearch.settings.updateCustomer"
        },
        "getCustomer": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "description": "Get customer settings. **Note:** This API requires an admin account to execute.",
          "path": "v1/settings/customer",
          "flatPath": "v1/settings/customer",
          "id": "cloudsearch.settings.getCustomer",
          "httpMethod": "GET"
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "upload": {
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "httpMethod": "POST",
                  "path": "v1/indexing/{+name}:upload",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload"
                },
                "unreserve": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/indexing/{+name}/items:unreserve",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve"
                },
                "delete": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}",
                  "httpMethod": "DELETE"
                },
                "poll": {
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}/items:poll",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.poll"
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1/indexing/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.get",
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "index": {
                  "path": "v1/indexing/{+name}:index",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "deleteQueueItems": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "path": "v1/indexing/{+name}/items:deleteQueueItems",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "httpMethod": "POST",
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "push": {
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "path": "v1/indexing/{+name}:push",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "list": {
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "path": "v1/indexing/{+name}/items",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.list"
                }
              }
            }
          },
          "methods": {
            "getSchema": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.indexing.datasources.getSchema",
              "httpMethod": "GET",
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute."
            },
            "updateSchema": {
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "id": "cloudsearch.indexing.datasources.updateSchema",
              "httpMethod": "PUT",
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema"
            },
            "deleteSchema": {
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "httpMethod": "DELETE",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ]
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "get": {
          "id": "cloudsearch.operations.get",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        }
      },
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "id": "cloudsearch.operations.lro.list",
              "path": "v1/{+name}/lro",
              "flatPath": "v1/operations/{operationsId}/lro",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the oper[...]",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "query": {
      "methods": {
        "suggest": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/query/suggest",
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
          "path": "v1/query/suggest",
          "id": "cloudsearch.query.suggest"
        },
        "search": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "httpMethod": "POST",
          "id": "cloudsearch.query.search",
          "flatPath": "v1/query/search",
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide [...]",
          "path": "v1/query/search"
        }
      },
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "path": "v1/query/sources",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "httpMethod": "GET",
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
              "id": "cloudsearch.query.sources.list",
              "flatPath": "v1/query/sources"
            }
          }
        }
      }
    },
    "v1": {
      "methods": {
        "initializeCustomer": {
          "path": "v1:initializeCustomer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "httpMethod": "POST",
          "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute.",
          "id": "cloudsearch.initializeCustomer",
          "flatPath": "v1:initializeCustomer"
        }
      }
    },
    "stats": {
      "methods": {
        "getUser": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/stats/user",
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "path": "v1/stats/user",
          "id": "cloudsearch.stats.getUser"
        },
        "getIndex": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getIndex",
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/index",
          "path": "v1/stats/index"
        },
        "getSearchapplication": {
          "flatPath": "v1/stats/searchapplication",
          "id": "cloudsearch.stats.getSearchapplication",
          "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute.",
          "path": "v1/stats/searchapplication",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ]
        },
        "getSession": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "path": "v1/stats/session",
          "flatPath": "v1/stats/session",
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "id": "cloudsearch.stats.getSession",
          "httpMethod": "GET"
        },
        "getQuery": {
          "id": "cloudsearch.stats.getQuery",
          "path": "v1/stats/query",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "flatPath": "v1/stats/query",
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "path": "v1/stats/session/{+name}",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.query.searchapplications.get",
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "path": "v1/stats/query/{+name}"
                }
              }
            }
          }
        },
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/user/{+name}",
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "id": "cloudsearch.stats.user.searchapplications.get",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
                  "path": "v1/stats/index/{+name}",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a[...]",
          "id": "cloudsearch.media.upload",
          "path": "v1/media/{+resourceName}",
          "flatPath": "v1/media/{mediaId}",
          "httpMethod": "POST",
          "supportsMediaUpload": true
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/cloud-search/docs/guides/",
  "revision": "20220411",
  "ownerDomain": "google.com",
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search."
}
