{
  "ownerName": "Google",
  "title": "Data Portability API",
  "revision": "20240130",
  "description": "The Data Portability API lets you build applications that request authorization from a user to move a copy of data from Google services into your application. This enables data portability and facilitates switching services.",
  "id": "dataportability:v1beta",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "baseUrl": "https://dataportability.googleapis.com/",
  "documentationLink": "https://developers.google.com/data-portability",
  "protocol": "rest",
  "basePath": "",
  "version": "v1beta",
  "mtlsRootUrl": "https://dataportability.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations": {
          "description": "Move a copy of messages between you and the businesses you have conversations with."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.youtube": {
          "description": "Move a copy of your YouTube activity."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.public_videos": {
          "description": "Move a copy of your public videos and information about them."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.private_playlists": {
          "description": "Move a copy of your private playlists."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.channel": {
          "description": "Move a copy of information about your channel."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.private_videos": {
          "description": "Move a copy of your private videos and information about them."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.live_chat": {
          "description": "Move a copy of your messages in live chat."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.music": {
          "description": "Move a copy of your uploaded YouTube Music tracks and your YouTube Music library."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.comments": {
          "description": "Move a copy of your comments."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.shopping": {
          "description": "Move a copy of YouTube Shopping Wishlists, and wishlist items."
        },
        "https://www.googleapis.com/auth/dataportability.shopping.addresses": {
          "description": "Move a copy of your shipping information."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.public_playlists": {
          "description": "Move a copy of your public playlists."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.search": {
          "description": "Move a copy of your search activity."
        },
        "https://www.googleapis.com/auth/dataportability.shopping.reviews": {
          "description": "Move a copy of reviews you wrote about products or online stores."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos": {
          "description": "Move a copy of your unlisted videos and information about them."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.subscriptions": {
          "description": "Move a copy of your channel subscriptions, even if they're private."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.shopping": {
          "description": "Move a copy of your Shopping activity."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists": {
          "description": "Move a copy of your unlisted playlists."
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "name": "dataportability",
  "version_module": true,
  "rootUrl": "https://dataportability.googleapis.com/",
  "canonicalName": "Data Portability",
  "resources": {
    "archiveJobs": {
      "methods": {
        "retry": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "id": "dataportability.archiveJobs.retry",
          "description": "Retries a failed Portability Archive job.",
          "path": "v1beta/{+name}:retry",
          "flatPath": "v1beta/archiveJobs/{archiveJobsId}:retry"
        },
        "getPortabilityArchiveState": {
          "description": "Retrieves the state of a Takeout Archive job for the Portability API.",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta/archiveJobs/{archiveJobsId}/portabilityArchiveState",
          "id": "dataportability.archiveJobs.getPortabilityArchiveState"
        }
      }
    },
    "portabilityArchive": {
      "methods": {
        "initiate": {
          "path": "v1beta/portabilityArchive:initiate",
          "description": "Initiates a new Takeout Archive job for the Portability API.",
          "id": "dataportability.portabilityArchive.initiate",
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "httpMethod": "POST",
          "flatPath": "v1beta/portabilityArchive:initiate"
        }
      }
    },
    "authorization": {
      "methods": {
        "reset": {
          "id": "dataportability.authorization.reset",
          "flatPath": "v1beta/authorization:reset",
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "httpMethod": "POST",
          "description": "Revokes OAuth tokens and resets exhausted scopes for a user/project pair. This method allows you to initiate a Takeout request after a new consent is granted. This method also indicates that previous archives can be garbage collected. You should call this method when all jobs are complete and all archives are downloaded. Do not call it only when you start a new job.",
          "path": "v1beta/authorization:reset"
        }
      }
    }
  }
}
