{
  "protocol": "rest",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "canonicalName": "Data Portability",
  "baseUrl": "https://dataportability.googleapis.com/",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataportability.youtube.channel": {
          "description": "Move a copy of information about your YouTube channel."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.shopping": {
          "description": "Move a copy of your YouTube shopping wishlists, and wishlist items."
        },
        "https://www.googleapis.com/auth/dataportability.maps.commute_settings": {
          "description": "Move a copy of your commute settings on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.live_chat": {
          "description": "Move a copy of your YouTube messages in live chat."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.private_playlists": {
          "description": "Move a copy of your YouTube private playlists."
        },
        "https://www.googleapis.com/auth/dataportability.maps.starred_places": {
          "description": "Move a copy of your Starred places list on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.maps.offering_contributions": {
          "description": "Move a copy of your updates to places on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.shopping.addresses": {
          "description": "Move a copy of your shipping information on Shopping."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.comments": {
          "description": "Move a copy of your YouTube comments."
        },
        "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations": {
          "description": "Move a copy of messages between you and the businesses you have conversations with across Google services."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.search": {
          "description": "Move a copy of your Google Search activity."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos": {
          "description": "Move a copy of your unlisted YouTube videos and information about them."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.public_videos": {
          "description": "Move a copy of your public YouTube videos and information about them."
        },
        "https://www.googleapis.com/auth/dataportability.maps.reviews": {
          "description": "Move a copy of your reviews and posts on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.maps.photos_videos": {
          "description": "Move a copy of the photos and videos you posted on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.shopping.reviews": {
          "description": "Move a copy of reviews you wrote about products or online stores on Google Search."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.music": {
          "description": "Move a copy of your uploaded YouTube music tracks and your YouTube music library."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.youtube": {
          "description": "Move a copy of your YouTube activity."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.private_videos": {
          "description": "Move a copy of your private YouTube videos and information about them."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.shopping": {
          "description": "Move a copy of your Shopping activity."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists": {
          "description": "Move a copy of your unlisted YouTube playlists."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.public_playlists": {
          "description": "Move a copy of your public YouTube playlists."
        },
        "https://www.googleapis.com/auth/dataportability.maps.ev_profile": {
          "description": "Move a copy of your electric vehicle profile on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.youtube.subscriptions": {
          "description": "Move a copy of your YouTube channel subscriptions, even if they're private."
        },
        "https://www.googleapis.com/auth/dataportability.maps.commute_routes": {
          "description": "Move a copy of your pinned trips on Maps."
        },
        "https://www.googleapis.com/auth/dataportability.myactivity.maps": {
          "description": "Move a copy of your Maps activity."
        }
      }
    }
  },
  "resources": {
    "archiveJobs": {
      "methods": {
        "getPortabilityArchiveState": {
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.maps.commute_routes",
            "https://www.googleapis.com/auth/dataportability.maps.commute_settings",
            "https://www.googleapis.com/auth/dataportability.maps.ev_profile",
            "https://www.googleapis.com/auth/dataportability.maps.offering_contributions",
            "https://www.googleapis.com/auth/dataportability.maps.photos_videos",
            "https://www.googleapis.com/auth/dataportability.maps.reviews",
            "https://www.googleapis.com/auth/dataportability.maps.starred_places",
            "https://www.googleapis.com/auth/dataportability.myactivity.maps",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "description": "Retrieves the state of an Archive job for the Portability API.",
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "id": "dataportability.archiveJobs.getPortabilityArchiveState",
          "flatPath": "v1beta/archiveJobs/{archiveJobsId}/portabilityArchiveState"
        },
        "retry": {
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.maps.commute_routes",
            "https://www.googleapis.com/auth/dataportability.maps.commute_settings",
            "https://www.googleapis.com/auth/dataportability.maps.ev_profile",
            "https://www.googleapis.com/auth/dataportability.maps.offering_contributions",
            "https://www.googleapis.com/auth/dataportability.maps.photos_videos",
            "https://www.googleapis.com/auth/dataportability.maps.reviews",
            "https://www.googleapis.com/auth/dataportability.maps.starred_places",
            "https://www.googleapis.com/auth/dataportability.myactivity.maps",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "flatPath": "v1beta/archiveJobs/{archiveJobsId}:retry",
          "description": "Retries a failed Portability Archive job.",
          "id": "dataportability.archiveJobs.retry",
          "path": "v1beta/{+name}:retry",
          "httpMethod": "POST"
        }
      }
    },
    "portabilityArchive": {
      "methods": {
        "initiate": {
          "description": "Initiates a new Archive job for the Portability API.",
          "id": "dataportability.portabilityArchive.initiate",
          "flatPath": "v1beta/portabilityArchive:initiate",
          "httpMethod": "POST",
          "path": "v1beta/portabilityArchive:initiate",
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.maps.commute_routes",
            "https://www.googleapis.com/auth/dataportability.maps.commute_settings",
            "https://www.googleapis.com/auth/dataportability.maps.ev_profile",
            "https://www.googleapis.com/auth/dataportability.maps.offering_contributions",
            "https://www.googleapis.com/auth/dataportability.maps.photos_videos",
            "https://www.googleapis.com/auth/dataportability.maps.reviews",
            "https://www.googleapis.com/auth/dataportability.maps.starred_places",
            "https://www.googleapis.com/auth/dataportability.myactivity.maps",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ]
        }
      }
    },
    "authorization": {
      "methods": {
        "reset": {
          "description": "Revokes OAuth tokens and resets exhausted scopes for a user/project pair. This method allows you to initiate a request after a new consent is granted. This method also indicates that previous archives can be garbage collected. You should call this method when all jobs are complete and all archives are downloaded. Do not call it only when you start a new job.",
          "flatPath": "v1beta/authorization:reset",
          "scopes": [
            "https://www.googleapis.com/auth/dataportability.businessmessaging.conversations",
            "https://www.googleapis.com/auth/dataportability.maps.commute_routes",
            "https://www.googleapis.com/auth/dataportability.maps.commute_settings",
            "https://www.googleapis.com/auth/dataportability.maps.ev_profile",
            "https://www.googleapis.com/auth/dataportability.maps.offering_contributions",
            "https://www.googleapis.com/auth/dataportability.maps.photos_videos",
            "https://www.googleapis.com/auth/dataportability.maps.reviews",
            "https://www.googleapis.com/auth/dataportability.maps.starred_places",
            "https://www.googleapis.com/auth/dataportability.myactivity.maps",
            "https://www.googleapis.com/auth/dataportability.myactivity.search",
            "https://www.googleapis.com/auth/dataportability.myactivity.shopping",
            "https://www.googleapis.com/auth/dataportability.myactivity.youtube",
            "https://www.googleapis.com/auth/dataportability.shopping.addresses",
            "https://www.googleapis.com/auth/dataportability.shopping.reviews",
            "https://www.googleapis.com/auth/dataportability.youtube.channel",
            "https://www.googleapis.com/auth/dataportability.youtube.comments",
            "https://www.googleapis.com/auth/dataportability.youtube.live_chat",
            "https://www.googleapis.com/auth/dataportability.youtube.music",
            "https://www.googleapis.com/auth/dataportability.youtube.private_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.private_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.public_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.public_videos",
            "https://www.googleapis.com/auth/dataportability.youtube.shopping",
            "https://www.googleapis.com/auth/dataportability.youtube.subscriptions",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists",
            "https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos"
          ],
          "id": "dataportability.authorization.reset",
          "path": "v1beta/authorization:reset",
          "httpMethod": "POST"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/data-portability",
  "servicePath": "",
  "basePath": "",
  "batchPath": "batch",
  "name": "dataportability",
  "mtlsRootUrl": "https://dataportability.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "version": "v1beta",
  "id": "dataportability:v1beta",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://dataportability.googleapis.com/",
  "revision": "20240221",
  "description": "The Data Portability API lets you build applications that request authorization from a user to move a copy of data from Google services into your application. This enables data portability and facilitates switching services.",
  "title": "Data Portability API"
}
