{
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "version": "v4",
  "discoveryVersion": "v1",
  "id": "dfareporting:v4",
  "resources": {
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountActiveAdSummaries.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.list",
          "description": "Retrieves list of user profiles for a user.",
          "flatPath": "userprofiles"
        }
      }
    },
    "userRoles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{profileId}/userRoles"
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing user role.",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/userRoles"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PUT"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new user role.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles"
        },
        "get": {
          "description": "Gets one user role by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{profileId}/userRoles/{id}"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get",
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "description": "Gets one operating system version by ID."
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "id": "dfareporting.advertiserInvoices.list",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "path": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices"
        }
      }
    },
    "reports": {
      "resources": {
        "files": {
          "methods": {
            "get": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get",
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      },
      "methods": {
        "list": {
          "id": "dfareporting.reports.list",
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "run": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "id": "dfareporting.reports.run",
          "description": "Runs a report."
        },
        "get": {
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "update": {
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report."
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "description": "Creates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "patch": {
          "id": "dfareporting.reports.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates an existing report. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID."
        }
      }
    },
    "contentCategories": {
      "methods": {
        "update": {
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.update",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "POST",
          "description": "Inserts a new content category.",
          "path": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Deletes an existing content category."
        },
        "get": {
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "id": "dfareporting.contentCategories.get",
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}"
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list share by remarketing list ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "id": "dfareporting.remarketingListShares.get",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}"
        },
        "update": {
          "path": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update"
        },
        "patch": {
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.patch"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "update": {
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one floodlight configuration by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.floodlightConfigurations.list",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/metros",
          "path": "userprofiles/{profileId}/metros",
          "httpMethod": "GET",
          "description": "Retrieves a list of metros.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get",
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}"
        },
        "list": {
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissionGroups"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "httpMethod": "DELETE"
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys"
        },
        "list": {
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys.",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.insert"
        },
        "get": {
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID."
        },
        "update": {
          "description": "Updates an existing placement strategy.",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.placementStrategies.delete",
          "description": "Deletes an existing placement strategy.",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.list"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.accountUserProfiles.list",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "description": "Gets one account user profile by ID."
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.accountUserProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update",
          "flatPath": "userprofiles/{profileId}/accounts"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "path": "userprofiles/{profileId}/accounts"
        },
        "list": {
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list",
          "flatPath": "userprofiles/{profileId}/accounts",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one account by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "id": "dfareporting.accounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "delete": {
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}"
        },
        "get": {
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/billingProfiles/{id}",
          "description": "Gets one billing profile by ID.",
          "id": "dfareporting.billingProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/billingProfiles/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.billingProfiles.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/billingProfiles"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.update",
          "path": "userprofiles/{profileId}/billingProfiles",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "description": "Updates an existing billing profile."
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{profileId}/browsers",
          "flatPath": "userprofiles/{profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.list",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers.",
          "flatPath": "userprofiles/{profileId}/mobileCarriers"
        },
        "get": {
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID."
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list",
          "flatPath": "userprofiles/{profileId}/regions"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/connectionTypes"
        },
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "httpMethod": "GET"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "path": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertisers",
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertisers.patch"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "flatPath": "userprofiles/{profileId}/advertisers"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments."
        },
        "insert": {
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.insert",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "httpMethod": "POST"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert"
        },
        "list": {
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "description": "Gets one targeting template by ID.",
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "id": "dfareporting.targetingTemplates.patch"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{profileId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/placements"
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement.",
          "flatPath": "userprofiles/{profileId}/placements"
        },
        "get": {
          "description": "Gets one placement by ID.",
          "flatPath": "userprofiles/{profileId}/placements/{id}",
          "path": "userprofiles/{profileId}/placements/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.get"
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.update"
        },
        "generatetags": {
          "path": "userprofiles/{profileId}/placements/generatetags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.get",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission by ID."
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups"
        },
        "insert": {
          "id": "dfareporting.advertiserGroups.insert",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group."
        },
        "delete": {
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        },
        "patch": {
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics."
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups"
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser group by ID.",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "update": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity."
        },
        "delete": {
          "description": "Deletes an existing floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "id": "dfareporting.floodlightActivities.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Gets one floodlight activity by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetag": {
          "description": "Generates a tag for a floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.get"
        },
        "update": {
          "id": "dfareporting.remarketingLists.update",
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.remarketingLists.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/remarketingLists"
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "path": "userprofiles/{profileId}/sites/{id}",
          "id": "dfareporting.sites.get",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "PUT"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/sites"
        },
        "list": {
          "path": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.list",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "path": "userprofiles/{profileId}/sites",
          "description": "Inserts a new site.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sizes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{profileId}/sizes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "description": "Gets one size by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new size.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/sizes",
          "flatPath": "userprofiles/{profileId}/sizes",
          "id": "dfareporting.sizes.insert"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}",
          "id": "dfareporting.subaccounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.list",
          "description": "Retrieves a list of platform types.",
          "path": "userprofiles/{profileId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/platformTypes"
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/projects",
          "path": "userprofiles/{profileId}/projects",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "httpMethod": "GET",
          "id": "dfareporting.projects.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.projects.get",
          "path": "userprofiles/{profileId}/projects/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "description": "Gets one project by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/countries/{dartId}",
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "id": "dfareporting.countries.get"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "path": "userprofiles/{profileId}/countries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "flatPath": "userprofiles/{profileId}/countries"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "patch": {
          "path": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{profileId}/ads",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad. This method supports patch semantics."
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad.",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PUT"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/ads",
          "description": "Inserts a new ad.",
          "path": "userprofiles/{profileId}/ads"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/ads/{id}",
          "description": "Gets one ad by ID.",
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "id": "dfareporting.ads.get"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/cities",
          "id": "dfareporting.cities.list",
          "description": "Retrieves a list of cities, possibly filtered."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative asset.",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert"
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "id": "dfareporting.campaigns.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "get": {
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "path": "userprofiles/{profileId}/campaigns/{id}",
          "id": "dfareporting.campaigns.get",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign."
        },
        "patch": {
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/campaigns",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Inserts a new campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.insert"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "description": "Retrieves the list of account permissions.",
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "path": "userprofiles/{profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{profileId}/accountPermissions/{id}"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/languages",
          "flatPath": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.languages.list",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orders.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders"
        },
        "get": {
          "description": "Gets one order by ID.",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "id": "dfareporting.orders.get",
          "httpMethod": "GET"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "path": "userprofiles/{profileId}/postalCodes",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.list",
          "description": "Retrieves a list of postal codes."
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get",
          "path": "userprofiles/{profileId}/postalCodes/{code}"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "POST",
          "id": "dfareporting.creativeFields.insert",
          "flatPath": "userprofiles/{profileId}/creativeFields"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Deletes an existing creative field.",
          "id": "dfareporting.creativeFields.delete"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.creativeFields.get",
          "description": "Gets one creative field by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}",
          "httpMethod": "GET",
          "description": "Gets one change log by ID.",
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.insert",
          "description": "Inserts a new creative group.",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creativeGroups"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative group by ID.",
          "path": "userprofiles/{profileId}/creativeGroups/{id}"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/creativeGroups"
        },
        "update": {
          "description": "Updates an existing creative group.",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/files",
          "path": "userprofiles/{profileId}/files"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.files.get",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "path": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "description": "Gets one order document by ID.",
          "id": "dfareporting.orderDocuments.get",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "id": "dfareporting.orderDocuments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "httpMethod": "GET"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get",
          "description": "Gets one directory site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/directorySites/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/directorySites"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "httpMethod": "POST",
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{profileId}/directorySites"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST"
        },
        "batchupdate": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/mobileApps",
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/operatingSystems",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get",
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID.",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}"
        }
      }
    },
    "creatives": {
      "methods": {
        "update": {
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update"
        },
        "insert": {
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creatives"
        },
        "get": {
          "description": "Gets one creative by ID.",
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives/{id}"
        },
        "patch": {
          "description": "Updates an existing creative. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{profileId}/creatives"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "GET",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list"
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing event tag.",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{profileId}/eventTags/{id}"
        },
        "insert": {
          "description": "Inserts a new event tag.",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.insert"
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag."
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permission groups.",
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.insert"
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one landing page by ID.",
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list",
          "description": "Retrieves a list of landing pages."
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "description": "Gets one floodlight activity group by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "id": "dfareporting.floodlightActivityGroups.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/floodlightActivityGroups"
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "POST"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one inventory item by ID."
        },
        "list": {
          "id": "dfareporting.inventoryItems.list",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "id": "dfareporting.videoFormats.list",
          "description": "Lists available video formats.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/videoFormats"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "description": "Gets one video format by ID."
        }
      }
    }
  },
  "rootUrl": "https://dfareporting.googleapis.com/",
  "title": "Campaign Manager 360 API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "basePath": "/dfareporting/v4/",
  "ownerName": "Google",
  "canonicalName": "Dfareporting",
  "kind": "discovery#restDescription",
  "servicePath": "dfareporting/v4/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "revision": "20230523",
  "fullyEncodeReservedExpansion": true,
  "name": "dfareporting",
  "batchPath": "batch",
  "protocol": "rest",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/"
}
