{
  "ownerDomain": "google.com",
  "servicePath": "dfareporting/v4/",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "revision": "20230918",
  "title": "Campaign Manager 360 API",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "resources": {
    "regions": {
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "description": "Retrieves a list of regions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/regions"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new creative group.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "description": "Gets one creative group by ID."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "description": "Deletes an existing dynamic targeting key."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "description": "Gets one video format by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.videoFormats.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "id": "dfareporting.videoFormats.list",
          "path": "userprofiles/{+profileId}/videoFormats",
          "description": "Lists available video formats.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.list",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems"
        },
        "get": {
          "description": "Gets one inventory item by ID.",
          "id": "dfareporting.inventoryItems.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "id": "dfareporting.creatives.list"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH",
          "id": "dfareporting.creatives.patch",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new creative.",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.creatives.get",
          "description": "Gets one creative by ID.",
          "path": "userprofiles/{+profileId}/creatives/{+id}"
        },
        "update": {
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "POST",
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "delete": {
          "description": "Deletes an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.get",
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT"
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles",
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "description": "Deletes an existing placement strategy."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.placementStrategies.insert",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "patch": {
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.list",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "description": "Gets one remarketing list by ID."
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "id": "dfareporting.orders.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one order by ID.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "httpMethod": "GET",
          "id": "dfareporting.orders.get"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "list": {
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "httpMethod": "POST",
          "description": "Inserts a new creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert"
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity by ID."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity.",
          "id": "dfareporting.floodlightActivities.update"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging."
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "id": "dfareporting.floodlightActivities.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.patch",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity."
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "httpMethod": "GET",
          "id": "dfareporting.projects.list",
          "path": "userprofiles/{+profileId}/projects"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "description": "Gets one project by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.projects.get",
          "path": "userprofiles/{+profileId}/projects/{+id}"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/cities"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating system versions."
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity group by ID."
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group."
        }
      }
    },
    "userRoles": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.get"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.list"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics."
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role."
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "list": {
          "id": "dfareporting.remarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list."
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.remarketingLists.get"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing RemarketingList. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "insert": {
          "description": "Inserts a new remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/remarketingLists"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "id": "dfareporting.mobileApps.get",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.list"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers.",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "id": "dfareporting.mobileCarriers.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID."
        }
      }
    },
    "placements": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID.",
          "id": "dfareporting.placements.get"
        },
        "patch": {
          "description": "Updates an existing placement. This method supports patch semantics.",
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements/generatetags"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.list",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "id": "dfareporting.placements.insert",
          "description": "Inserts a new placement."
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "description": "Inserts a new ad.",
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one ad by ID.",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{+profileId}/ads/{+id}"
        },
        "list": {
          "id": "dfareporting.ads.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.update",
          "description": "Updates an existing ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PUT"
        }
      }
    },
    "reports": {
      "resources": {
        "files": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get",
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "supportsMediaDownload": true,
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.list",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "httpMethod": "POST",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        }
      },
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "id": "dfareporting.reports.get",
          "description": "Retrieves a report by its ID."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert"
        },
        "update": {
          "description": "Updates a report.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "id": "dfareporting.reports.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "list": {
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "run": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.run",
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Deletes a report by its ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.patch",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates an existing report. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{+profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "flatPath": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "path": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "path": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "description": "Gets one content category by ID."
        },
        "update": {
          "description": "Updates an existing content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.update"
        },
        "patch": {
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PATCH"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "description": "Inserts a new directory site.",
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.insert"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "description": "Gets one user role permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "id": "dfareporting.userRolePermissions.get",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{+profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of browsers.",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "httpMethod": "GET"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/connectionTypes",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one connection type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "id": "dfareporting.connectionTypes.get"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/operatingSystems",
          "description": "Retrieves a list of operating systems.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.get"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of platform types.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{+profileId}/platformTypes",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.billingProfiles.update",
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles"
        },
        "list": {
          "id": "dfareporting.billingProfiles.list",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchinsert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert"
        },
        "batchupdate": {
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "path": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing assignments.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "description": "Gets one account by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "id": "dfareporting.accounts.get",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.accounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "description": "Updates an existing account."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch"
        },
        "list": {
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.list"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.list",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "id": "dfareporting.advertiserGroups.insert",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserGroups.update",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group."
        }
      }
    },
    "advertisers": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        },
        "list": {
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "update": {
          "description": "Updates an existing advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.update"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{+profileId}/advertisers/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "description": "Updates an existing account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        },
        "list": {
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.list"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.get",
          "httpMethod": "GET",
          "description": "Gets one account user profile by ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new subaccount.",
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "id": "dfareporting.subaccounts.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID."
        },
        "delete": {
          "description": "Deletes an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.insert"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID."
        },
        "list": {
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PUT"
        },
        "get": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "description": "Gets one floodlight configuration by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics."
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "DELETE"
        },
        "update": {
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Inserts a new event tag."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "id": "dfareporting.eventTags.get",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered."
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one change log by ID.",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "id": "dfareporting.changeLogs.get"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "description": "Gets one user role permission group by ID."
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID."
        },
        "list": {
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch"
        },
        "get": {
          "description": "Gets one targeting template by ID.",
          "id": "dfareporting.targetingTemplates.get",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Inserts a new targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update",
          "description": "Updates an existing targeting template."
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of postal codes.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{+profileId}/postalCodes"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.insert",
          "description": "Inserts a new size.",
          "path": "userprofiles/{+profileId}/sizes"
        },
        "list": {
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.list"
        },
        "get": {
          "id": "dfareporting.sizes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one size by ID.",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}"
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.update"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "description": "Inserts a new campaign."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PATCH",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "description": "Gets one remarketing list share by remarketing list ID."
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing RemarketingListShare. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.update"
        },
        "list": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "id": "dfareporting.advertiserLandingPages.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.sites.get",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "description": "Gets one site by ID."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PATCH"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT",
          "id": "dfareporting.sites.update",
          "description": "Updates an existing site."
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "canonicalName": "Dfareporting",
  "ownerName": "Google",
  "basePath": "/dfareporting/v4/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "id": "dfareporting:v4",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "name": "dfareporting",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "version": "v4"
}
