{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "title": "Campaign Manager 360 API",
  "canonicalName": "Dfareporting",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "revision": "20220920",
  "name": "dfareporting",
  "batchPath": "batch",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "id": "dfareporting:v4",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "protocol": "rest",
  "basePath": "/dfareporting/v4/",
  "resources": {
    "orderDocuments": {
      "methods": {
        "list": {
          "id": "dfareporting.orderDocuments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one order document by ID.",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orderDocuments.get"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "id": "dfareporting.placementStrategies.insert"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementStrategies.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "id": "dfareporting.placementStrategies.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch",
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "id": "dfareporting.placementStrategies.get"
        },
        "delete": {
          "id": "dfareporting.placementStrategies.delete",
          "description": "Deletes an existing placement strategy.",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/countries/{dartId}",
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "id": "dfareporting.countries.get",
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/countries",
          "id": "dfareporting.countries.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/countries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of countries."
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "id": "dfareporting.postalCodes.list"
        },
        "get": {
          "description": "Gets one postal code by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}",
          "path": "userprofiles/{profileId}/postalCodes/{code}"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/regions",
          "description": "Retrieves a list of regions.",
          "path": "userprofiles/{profileId}/regions",
          "id": "dfareporting.regions.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/videoFormats",
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "id": "dfareporting.videoFormats.get",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles",
          "path": "userprofiles",
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.get",
          "description": "Gets one user profile by ID.",
          "path": "userprofiles/{profileId}"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups."
        },
        "get": {
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "description": "Gets one account permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "description": "Gets one floodlight activity group by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "list": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.list"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.userRolePermissions.get",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/userRolePermissions"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "path": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": true,
          "flatPath": "reports/{reportId}/files/{fileId}",
          "path": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "id": "dfareporting.connectionTypes.get",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/connectionTypes",
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "description": "Retrieves a list of connection types."
        }
      }
    },
    "userRoles": {
      "methods": {
        "update": {
          "description": "Updates an existing user role.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "id": "dfareporting.userRoles.patch"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "description": "Inserts a new user role."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging."
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID.",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "GET"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Deletes an existing user role.",
          "httpMethod": "DELETE",
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}"
        }
      }
    },
    "eventTags": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new event tag."
        },
        "update": {
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.list",
          "path": "userprofiles/{profileId}/eventTags"
        },
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "description": "Deletes an existing event tag.",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{profileId}/eventTags/{id}"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "id": "dfareporting.operatingSystemVersions.get"
        },
        "list": {
          "description": "Retrieves a list of operating system versions.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.list"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets the account's active ad summary by account ID.",
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "httpMethod": "POST"
        }
      }
    },
    "sites": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{profileId}/sites"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site.",
          "id": "dfareporting.sites.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "description": "Gets one site by ID.",
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/sites/{id}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.insert",
          "description": "Inserts a new site."
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.patch",
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/sites"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/remarketingLists/{id}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/remarketingLists",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "httpMethod": "PUT"
        },
        "list": {
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.list"
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{profileId}/projects",
          "path": "userprofiles/{profileId}/projects",
          "id": "dfareporting.projects.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one project by ID.",
          "id": "dfareporting.projects.get"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{profileId}/userRolePermissionGroups"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of browsers.",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/browsers"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "id": "dfareporting.floodlightConfigurations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.update"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "description": "Updates an existing placement. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{profileId}/placements",
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement."
        },
        "update": {
          "id": "dfareporting.placements.update",
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement.",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{profileId}/placements/{id}",
          "description": "Gets one placement by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placements/{id}"
        },
        "generatetags": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements/generatetags"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "description": "Retrieves the list of account permissions.",
          "id": "dfareporting.accountPermissions.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountPermissions"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "path": "userprofiles/{profileId}/accountPermissions/{id}"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/platformTypes",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{profileId}/platformTypes/{id}"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.list",
          "path": "userprofiles/{profileId}/accounts"
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/accounts"
        },
        "update": {
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/accounts"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "id": "dfareporting.accounts.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "description": "Gets one account by ID."
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "get": {
          "description": "Gets one ad by ID.",
          "path": "userprofiles/{profileId}/ads/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "id": "dfareporting.ads.get"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/ads",
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{profileId}/ads"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.update",
          "path": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad."
        },
        "patch": {
          "description": "Updates an existing ad. This method supports patch semantics.",
          "id": "dfareporting.ads.patch",
          "path": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/ads"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/metros",
          "description": "Retrieves a list of metros.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/metros"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys"
        },
        "delete": {
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "httpMethod": "GET",
          "id": "dfareporting.billingAssignments.list"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST"
        },
        "batchupdate": {
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        }
      }
    },
    "sizes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one size by ID.",
          "id": "dfareporting.sizes.get",
          "path": "userprofiles/{profileId}/sizes/{id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{profileId}/sizes",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/sizes",
          "id": "dfareporting.sizes.insert"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations"
        },
        "insert": {
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orders.get",
          "description": "Gets one order by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "id": "dfareporting.orders.list",
          "httpMethod": "GET"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps.",
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/mobileApps",
          "flatPath": "userprofiles/{profileId}/mobileApps"
        },
        "get": {
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "description": "Gets one mobile app by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.get"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.inventoryItems.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "id": "dfareporting.inventoryItems.get",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/billingProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile.",
          "path": "userprofiles/{profileId}/billingProfiles",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update",
          "httpMethod": "PUT"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{id}",
          "path": "userprofiles/{profileId}/billingProfiles/{id}",
          "id": "dfareporting.billingProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one billing profile by ID."
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "update": {
          "description": "Updates an existing targeting template.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetingTemplates"
        },
        "get": {
          "description": "Gets one targeting template by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "id": "dfareporting.targetingTemplates.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}"
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/targetingTemplates"
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "id": "dfareporting.directorySites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites",
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/directorySites"
        },
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "path": "userprofiles/{profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID.",
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "id": "dfareporting.changeLogs.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers.",
          "flatPath": "userprofiles/{profileId}/mobileCarriers"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID.",
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFieldValues.delete",
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "description": "Gets one creative field value by ID.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "id": "dfareporting.creativeFieldValues.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Deletes an existing creative field."
        },
        "update": {
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Gets one creative field by ID.",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "id": "dfareporting.creativeFields.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.creativeFields.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields"
        }
      }
    },
    "reports": {
      "methods": {
        "delete": {
          "description": "Deletes a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete",
          "httpMethod": "DELETE"
        },
        "update": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "list": {
          "id": "dfareporting.reports.list",
          "path": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report."
        },
        "run": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "description": "Runs a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "get": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report by its ID.",
          "httpMethod": "GET",
          "id": "dfareporting.reports.get",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates an existing report. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.patch",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions."
            }
          }
        },
        "files": {
          "methods": {
            "list": {
              "id": "dfareporting.reports.files.list",
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            },
            "get": {
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "supportsMediaDownload": true
            }
          }
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of cities, possibly filtered.",
          "flatPath": "userprofiles/{profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/cities",
          "id": "dfareporting.cities.list"
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/campaigns/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get",
          "description": "Gets one campaign by ID.",
          "flatPath": "userprofiles/{profileId}/campaigns/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "update": {
          "description": "Updates an existing campaign.",
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/campaigns",
          "flatPath": "userprofiles/{profileId}/campaigns"
        },
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new campaign.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "patch": {
          "path": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/campaigns"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "path": "userprofiles/{profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "list": {
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.list"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST",
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{profileId}/placementGroups"
        },
        "update": {
          "description": "Updates an existing placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of languages.",
          "path": "userprofiles/{profileId}/languages",
          "flatPath": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{profileId}/operatingSystems",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.get",
          "description": "Gets one operating system by DART ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "description": "Gets one remarketing list share by remarketing list ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/remarketingListShares"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "patch": {
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser group by ID.",
          "id": "dfareporting.advertiserGroups.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "description": "Deletes an existing advertiser group.",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "flatPath": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "path": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics."
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/subaccounts"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.get",
          "description": "Gets one subaccount by ID.",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts/{id}"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount."
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.get"
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new landing page."
        },
        "update": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "description": "Updates an existing landing page."
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "id": "dfareporting.accountUserProfiles.get"
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity."
        },
        "insert": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Deletes an existing floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "id": "dfareporting.floodlightActivities.delete",
          "httpMethod": "DELETE"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Gets one floodlight activity by ID."
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.patch"
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one content category by ID.",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "id": "dfareporting.contentCategories.get"
        },
        "delete": {
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{profileId}/contentCategories",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/contentCategories",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category."
        },
        "list": {
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.list"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "POST"
        }
      }
    },
    "creatives": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "httpMethod": "PUT",
          "id": "dfareporting.creatives.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creatives",
          "flatPath": "userprofiles/{profileId}/creatives"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creatives",
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.insert"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative by ID.",
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "id": "dfareporting.creatives.list"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/creativeGroups",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "POST",
          "description": "Inserts a new creative group.",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert"
        },
        "get": {
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}",
          "description": "Gets one creative group by ID.",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeGroups.update"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "id": "dfareporting.advertisers.get"
        },
        "insert": {
          "description": "Inserts a new advertiser.",
          "id": "dfareporting.advertisers.insert",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "POST"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/advertisers"
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/advertisers"
        }
      }
    }
  },
  "ownerName": "Google",
  "servicePath": "dfareporting/v4/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "version": "v4"
}
