{
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "id": "dfareporting:v4",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "title": "Campaign Manager 360 API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "resources": {
    "advertisers": {
      "methods": {
        "update": {
          "description": "Updates an existing advertiser.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.insert",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.list",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert",
          "description": "Inserts a new creative asset.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET",
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.patch"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Inserts a new creative field.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Deletes an existing creative field.",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "id": "dfareporting.sizes.get",
          "description": "Gets one size by ID.",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "path": "userprofiles/{+profileId}/sizes",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.insert",
          "path": "userprofiles/{+profileId}/sizes"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "id": "dfareporting.floodlightConfigurations.get",
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "id": "dfareporting.contentCategories.delete",
          "description": "Deletes an existing content category.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "update": {
          "description": "Updates an existing content category.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "id": "dfareporting.campaignCreativeAssociations.insert"
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "httpMethod": "POST",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "get": {
          "id": "dfareporting.subaccounts.get",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "description": "Gets one subaccount by ID.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing subaccount.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "httpMethod": "POST"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingRates.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "userRoles": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "description": "Updates an existing user role."
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Deletes an existing user role."
        },
        "patch": {
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "POST",
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert"
        },
        "get": {
          "description": "Gets one user role by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "id": "dfareporting.userRoles.get",
          "httpMethod": "GET"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "id": "dfareporting.accounts.get",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.list"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/accounts"
        },
        "update": {
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.update",
          "httpMethod": "PUT"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{+profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission by ID.",
          "id": "dfareporting.accountPermissions.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.list",
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}"
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch",
          "description": "Updates an existing user role. This method supports patch semantics."
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile."
        },
        "list": {
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one account user profile by ID.",
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "httpMethod": "POST"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list",
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{+profileId}/metros",
          "flatPath": "userprofiles/{userprofilesId}/metros"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.cities.list",
          "description": "Retrieves a list of cities, possibly filtered.",
          "path": "userprofiles/{+profileId}/cities",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of report dimension values for a list of filters.",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "id": "dfareporting.dimensionValues.query"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "patch": {
          "description": "Updates an existing RemarketingListShare. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingListShares"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "id": "dfareporting.remarketingListShares.get",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "flatPath": "userprofiles/{profileId}",
          "path": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.get"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of languages.",
          "id": "dfareporting.languages.list",
          "path": "userprofiles/{+profileId}/languages",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "id": "dfareporting.directorySites.get",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "description": "Gets one directory site by ID."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/directorySites",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert"
        },
        "list": {
          "id": "dfareporting.directorySites.list",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.projects.list",
          "path": "userprofiles/{+profileId}/projects",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.get",
          "description": "Gets one project by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "path": "userprofiles/{+profileId}/projects/{+id}"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "id": "dfareporting.platformTypes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "description": "Gets one connection type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.get",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "description": "Gets one creative by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing creative. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PUT"
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.patch",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.get",
          "description": "Gets one floodlight activity by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "generatetag": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.generatetag"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity group by ID."
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "httpMethod": "PUT"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        }
      }
    },
    "sites": {
      "methods": {
        "update": {
          "id": "dfareporting.sites.update",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site.",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.insert",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Inserts a new site.",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET",
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{+profileId}/sites"
        },
        "get": {
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.get",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.patch",
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PATCH"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing assignments.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        },
        "insert": {
          "id": "dfareporting.billingAssignments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one video format by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "description": "Lists available video formats.",
          "path": "userprofiles/{+profileId}/videoFormats",
          "id": "dfareporting.videoFormats.list",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "httpMethod": "POST"
        },
        "batchinsert": {
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Inserts conversions.",
          "httpMethod": "POST"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}"
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "id": "dfareporting.orders.list",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders"
        },
        "get": {
          "id": "dfareporting.orders.get",
          "description": "Gets one order by ID.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "id": "dfareporting.operatingSystems.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "id": "dfareporting.operatingSystems.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of landing pages.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new landing page.",
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "id": "dfareporting.advertiserLandingPages.get"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page."
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "id": "dfareporting.inventoryItems.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.list",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "path": "userprofiles/{+profileId}/mobileApps",
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps"
        },
        "get": {
          "id": "dfareporting.mobileApps.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "description": "Gets one mobile app by ID.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.list",
          "description": "Retrieves the list of account permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics."
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative field value."
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value.",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one creative field value by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "campaigns": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.update",
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.campaigns.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "description": "Gets one campaign by ID.",
          "path": "userprofiles/{+profileId}/campaigns/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "POST",
          "description": "Inserts a new campaign.",
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.campaigns.list",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging."
        }
      }
    },
    "ads": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PATCH"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing ad.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.ads.get",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "description": "Gets one ad by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.list"
        },
        "insert": {
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.insert"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "description": "Retrieves a list of countries.",
          "path": "userprofiles/{+profileId}/countries",
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "description": "Gets one country by ID."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "id": "dfareporting.advertiserGroups.delete",
          "description": "Deletes an existing advertiser group.",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.patch",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "id": "dfareporting.advertiserGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "description": "Gets one advertiser group by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging."
        }
      }
    },
    "placements": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement."
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "id": "dfareporting.placements.patch",
          "httpMethod": "PATCH"
        },
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.update",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "GET",
          "id": "dfareporting.placements.list"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID."
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "description": "Gets one mobile carrier by ID."
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "description": "Lists files for a user profile.",
          "id": "dfareporting.files.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/files"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.get",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "flatPath": "reports/{reportId}/files/{fileId}"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "get": {
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile.",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/regions"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "update": {
          "id": "dfareporting.targetingTemplates.update",
          "description": "Updates an existing targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "description": "Gets one targeting template by ID."
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "id": "dfareporting.targetingTemplates.patch"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list"
        }
      }
    },
    "eventTags": {
      "methods": {
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "id": "dfareporting.eventTags.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics."
        },
        "delete": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag.",
          "id": "dfareporting.eventTags.delete"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{+profileId}/postalCodes",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.list",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "description": "Gets one postal code by ID."
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "insert": {
          "id": "dfareporting.creativeGroups.insert",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Inserts a new creative group."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "description": "Gets one creative group by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PUT"
        }
      }
    },
    "reports": {
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "id": "dfareporting.reports.files.get",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update"
        },
        "get": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "id": "dfareporting.reports.list"
        },
        "delete": {
          "description": "Deletes a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "id": "dfareporting.reports.insert",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.reports.patch",
          "description": "Updates an existing report. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "run": {
          "id": "dfareporting.reports.run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "description": "Runs a report."
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.get",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PATCH",
          "description": "Updates an existing RemarketingList. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "id": "dfareporting.placementGroups.insert",
          "description": "Inserts a new placement group.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing placement group."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "description": "Gets one placement group by ID."
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET"
        }
      }
    }
  },
  "rootUrl": "https://dfareporting.googleapis.com/",
  "basePath": "/dfareporting/v4/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "name": "dfareporting",
  "version": "v4",
  "servicePath": "dfareporting/v4/",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "revision": "20230726",
  "fullyEncodeReservedExpansion": true,
  "canonicalName": "Dfareporting",
  "ownerDomain": "google.com"
}
