{
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "title": "Display & Video 360 API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "revision": "20230817",
  "batchPath": "batch",
  "version": "v2",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "name": "displayvideo",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "canonicalName": "Display Video",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "ownerName": "Google",
  "basePath": "",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "resources": {
    "media": {
      "methods": {
        "upload": {
          "path": "media/{+resourceName}",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "httpMethod": "POST",
          "id": "displayvideo.media.upload",
          "supportsMediaUpload": true,
          "flatPath": "media/{mediaId}"
        },
        "download": {
          "path": "download/{+resourceName}",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "httpMethod": "GET",
          "flatPath": "download/{downloadId}",
          "id": "displayvideo.media.download"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/sdfdownloadtasks",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "id": "displayvideo.sdfdownloadtasks.create",
          "flatPath": "v2/sdfdownloadtasks",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}",
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds."
            }
          }
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "list": {
          "flatPath": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.list",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v2/guaranteedOrders",
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "id": "displayvideo.guaranteedOrders.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}"
        },
        "editGuaranteedOrderReadAccessors": {
          "description": "Edits read advertisers of a guaranteed order.",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "path": "v2/guaranteedOrders",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.create"
        },
        "get": {
          "id": "displayvideo.guaranteedOrders.get",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "description": "Gets a guaranteed order.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "list": {
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions",
              "description": "Lists targeting options of a given type.",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions"
            },
            "get": {
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "httpMethod": "GET",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}"
            },
            "search": {
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "httpMethod": "POST",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search"
            }
          }
        }
      }
    },
    "partners": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "description": "Lists the targeting options assigned to a partner.",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from a partner.",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful."
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "list": {
              "flatPath": "v2/partners/{partnersId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels",
              "id": "displayvideo.partners.channels.list",
              "httpMethod": "GET"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v2/partners/{+partnerId}/channels/{+channelId}",
              "id": "displayvideo.partners.channels.get",
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser."
            },
            "patch": {
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/partners/{+partnerId}/channels/{channelId}",
              "id": "displayvideo.partners.channels.patch"
            },
            "create": {
              "flatPath": "v2/partners/{partnersId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.partners.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "create": {
                  "id": "displayvideo.partners.channels.sites.create",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites",
                  "id": "displayvideo.partners.channels.sites.list",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "GET"
                },
                "bulkEdit": {
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites."
                },
                "replace": {
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.partners.channels.sites.replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "httpMethod": "POST",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.list",
          "flatPath": "v2/partners",
          "path": "v2/partners",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v2/partners/{+partnerId}",
          "id": "displayvideo.partners.get",
          "description": "Gets a partner.",
          "flatPath": "v2/partners/{partnersId}"
        },
        "editAssignedTargetingOptions": {
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "httpMethod": "POST",
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "inventorySources": {
      "methods": {
        "create": {
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources",
          "id": "displayvideo.inventorySources.create",
          "path": "v2/inventorySources"
        },
        "editInventorySourceReadWriteAccessors": {
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "path": "v2/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySources/{+inventorySourceId}",
          "description": "Gets an inventory source.",
          "httpMethod": "GET",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.get"
        },
        "patch": {
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "path": "v2/inventorySources/{+inventorySourceId}",
          "id": "displayvideo.inventorySources.patch"
        },
        "list": {
          "flatPath": "v2/inventorySources",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v2/inventorySources",
          "id": "displayvideo.inventorySources.list"
        }
      }
    },
    "users": {
      "methods": {
        "bulkEditAssignedUserRoles": {
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles",
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "create": {
          "id": "displayvideo.users.create",
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users",
          "httpMethod": "POST",
          "flatPath": "v2/users"
        },
        "delete": {
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v2/users/{usersId}",
          "id": "displayvideo.users.delete",
          "httpMethod": "DELETE",
          "path": "v2/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/users/{+userId}",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v2/users/{usersId}",
          "id": "displayvideo.users.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "list": {
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.list",
          "httpMethod": "GET",
          "path": "v2/users",
          "flatPath": "v2/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "get": {
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.get",
          "path": "v2/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "GET",
          "flatPath": "v2/users/{usersId}"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "patch": {
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "path": "v2/floodlightGroups/{floodlightGroupId}",
          "id": "displayvideo.floodlightGroups.patch",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}",
          "id": "displayvideo.floodlightGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/floodlightGroups/{+floodlightGroupId}"
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "list": {
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v2/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list",
          "flatPath": "v2/inventorySourceGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "path": "v2/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.create",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets an inventory source group.",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.patch"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "delete": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "httpMethod": "DELETE",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources"
            },
            "bulkEdit": {
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "path": "v2/combinedAudiences/{+combinedAudienceId}",
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "path": "v2/combinedAudiences",
          "httpMethod": "GET",
          "flatPath": "v2/combinedAudiences",
          "id": "displayvideo.combinedAudiences.list"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "flatPath": "v2/advertisers/{advertisersId}",
          "path": "v2/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.get",
          "description": "Gets an advertiser."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "flatPath": "v2/advertisers"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "flatPath": "v2/advertisers/{advertisersId}",
          "path": "v2/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.patch",
          "httpMethod": "PATCH"
        },
        "audit": {
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v2/advertisers/{+advertiserId}:audit"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.advertisers.delete",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "flatPath": "v2/advertisers/{advertisersId}"
        },
        "create": {
          "id": "displayvideo.advertisers.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers",
          "flatPath": "v2/advertisers",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete."
        },
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests ."
        },
        "listAssignedTargetingOptions": {
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        }
      },
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                },
                "delete": {
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "httpMethod": "DELETE",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list"
                }
              }
            }
          }
        },
        "lineItems": {
          "methods": {
            "duplicate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.list"
            },
            "bulkEditAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetin[...]"
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            },
            "bulkListAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions"
            },
            "create": {
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.create",
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "POST"
            },
            "generateDefault": {
              "httpMethod": "POST",
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:generateDefault",
              "path": "v2/advertisers/{+advertiserId}/lineItems:generateDefault"
            },
            "patch": {
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption"
            },
            "bulkUpdate": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.get",
              "description": "Gets a line item.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetingOption",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "list": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "create": {
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * DeleteLineItemAssignedTargetingOption",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "httpMethod": "POST"
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "create": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Creates a new campaign. Returns the newly created campaign if successful."
            },
            "get": {
              "id": "displayvideo.advertisers.campaigns.get",
              "description": "Gets a campaign.",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete",
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "listAssignedTargetingOptions": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}:listAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}:listAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "id": "displayvideo.advertisers.campaigns.listAssignedTargetingOptions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type."
                    }
                  }
                }
              }
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "httpMethod": "GET"
                },
                "delete": {
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}"
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "description": "Creates a site in a channel.",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace"
                }
              }
            }
          },
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.list",
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "path": "v2/advertisers/{+advertiserId}/channels"
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.patch",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}",
              "id": "displayvideo.advertisers.channels.get",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.advertisers.channels.create"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "path": "v2/advertisers/{+advertiserId}/assets",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaUpload": true,
              "id": "displayvideo.advertisers.assets.upload",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "flatPath": "v2/advertisers/{advertisersId}/assets"
            }
          }
        },
        "youtubeAdGroups": {
          "methods": {
            "bulkListAdGroupAssignedTargetingOptions": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherieted assigned targeting options are not included.",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "id": "displayvideo.advertisers.youtubeAdGroups.get",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}",
              "description": "Gets a YouTube ad group.",
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "description": "Lists YouTube ad groups.",
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get"
                    },
                    "list": {
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "methods": {
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "description": "Deletes a negative keyword from a negative keyword list."
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "httpMethod": "GET",
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "replace": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "httpMethod": "POST"
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "httpMethod": "POST"
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.create"
            },
            "delete": {
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "GET"
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful."
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "listAssignedTargetingOptions": {
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:listAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:listAssignedTargetingOptions",
              "id": "displayvideo.advertisers.insertionOrders.listAssignedTargetingOptions",
              "httpMethod": "GET"
            },
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "delete": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.create",
                      "description": "Assigns a targeting option to an insertion order. Returns the assigned targeting option if successful. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEG[...]"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from an insertion order. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPE[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.delete"
                    }
                  }
                }
              }
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "description": "Deletes the assignment between a location and a location list."
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Creates an assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists locations assigned to a location list.",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "httpMethod": "GET",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                }
              }
            }
          },
          "methods": {
            "create": {
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "id": "displayvideo.advertisers.locationLists.get",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}",
              "id": "displayvideo.advertisers.locationLists.patch",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "displayvideo.advertisers.locationLists.list",
              "description": "Lists location lists based on a given advertiser id.",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "activate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "deactivate": {
              "description": "Deactivates a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.deactivate"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.list",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "id": "displayvideo.advertisers.manualTriggers.get"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "id": "displayvideo.advertisers.manualTriggers.create",
              "httpMethod": "POST",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "patch": {
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "httpMethod": "PATCH",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}"
            }
          }
        },
        "creatives": {
          "methods": {
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "id": "displayvideo.advertisers.creatives.patch",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "id": "displayvideo.advertisers.creatives.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.delete"
            },
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.get",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Gets a creative."
            }
          }
        },
        "youtubeAdGroupAds": {
          "methods": {
            "get": {
              "description": "Gets a YouTube ad group ad.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists YouTube ad group ads.",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list"
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/invoices",
              "id": "displayvideo.advertisers.invoices.list",
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "httpMethod": "GET",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method."
            },
            "lookupInvoiceCurrency": {
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency"
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "flatPath": "v2/customLists/{customListsId}",
          "description": "Gets a custom list.",
          "path": "v2/customLists/{+customListId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.get"
        },
        "list": {
          "path": "v2/customLists",
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/customLists",
          "id": "displayvideo.customLists.list"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "patch": {
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}"
        },
        "get": {
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets a first and third party audience.",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.get"
        },
        "editCustomerMatchMembers": {
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "httpMethod": "POST",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "list": {
          "path": "v2/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "path": "v2/firstAndThirdPartyAudiences",
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "id": "displayvideo.firstAndThirdPartyAudiences.create"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.get",
          "path": "v2/googleAudiences/{+googleAudienceId}",
          "description": "Gets a Google audience.",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "v2/googleAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.list",
          "httpMethod": "GET",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "path": "v2/googleAudiences"
        }
      }
    },
    "customBiddingAlgorithms": {
      "resources": {
        "scripts": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "httpMethod": "GET",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "description": "Gets a custom bidding script.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "create": {
              "description": "Creates a new custom bidding script. Returns the newly created script if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "get": {
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom bidding algorithm.",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful.",
          "httpMethod": "PATCH",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.patch"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/customBiddingAlgorithms",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "path": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.list"
        },
        "uploadScript": {
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "httpMethod": "GET",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "path": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "flatPath": "v2/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST"
        }
      }
    }
  },
  "id": "displayvideo:v2",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/display-video/",
  "version_module": true
}
