{
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "revision": "20210722",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "baseUrl": "https://displayvideo.googleapis.com/",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "discoveryVersion": "v1",
  "canonicalName": "Display Video",
  "description": "Display & Video 360 API allows users to manage and create campaigns and reports.",
  "documentationLink": "https://developers.google.com/display-video/",
  "name": "displayvideo",
  "title": "Display & Video 360 API",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "resources": {
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "delete": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "httpMethod": "DELETE",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create"
            },
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            },
            "list": {
              "description": "Lists inventory sources assigned to an inventory source group.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      },
      "methods": {
        "create": {
          "path": "v1/inventorySourceGroups",
          "flatPath": "v1/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.create",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.get",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an inventory source group."
        },
        "patch": {
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.inventorySourceGroups.patch",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful."
        },
        "list": {
          "flatPath": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list",
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter."
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "id": "displayvideo.inventorySourceGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Deletes an inventory source group.",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}"
        }
      }
    },
    "partners": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v1/partners",
          "flatPath": "v1/partners",
          "id": "displayvideo.partners.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "path": "v1/partners/{+partnerId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/partners/{partnersId}",
          "id": "displayvideo.partners.get",
          "httpMethod": "GET",
          "description": "Gets a partner."
        },
        "bulkEditPartnerAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Bulk edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "httpMethod": "POST",
          "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions",
          "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions",
          "flatPath": "v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions"
        }
      },
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to a partner."
                },
                "list": {
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner.",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "get": {
              "path": "v1/partners/{+partnerId}/channels/{+channelId}",
              "description": "Gets a channel for a partner or advertiser.",
              "httpMethod": "GET",
              "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get"
            },
            "list": {
              "path": "v1/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.partners.channels.list",
              "flatPath": "v1/partners/{partnersId}/channels",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1/partners/{+partnerId}/channels",
              "flatPath": "v1/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.create",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "id": "displayvideo.partners.channels.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful."
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.partners.channels.sites.list",
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites."
                },
                "replace": {
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.partners.channels.sites.replace"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites",
                  "id": "displayvideo.partners.channels.sites.create"
                }
              }
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "supportsMediaDownload": true,
          "id": "displayvideo.media.download",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "flatPath": "download/{downloadId}",
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "path": "download/{+resourceName}"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "httpMethod": "GET",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "description": "Gets a first and third party audience."
        },
        "list": {
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "path": "v1/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/firstAndThirdPartyAudiences"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/googleAudiences",
          "id": "displayvideo.googleAudiences.list",
          "httpMethod": "GET",
          "flatPath": "v1/googleAudiences",
          "description": "Lists Google audiences. The order is defined by the order_by parameter."
        },
        "get": {
          "flatPath": "v1/googleAudiences/{googleAudiencesId}",
          "id": "displayvideo.googleAudiences.get",
          "description": "Gets a Google audience.",
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "inventorySources": {
      "methods": {
        "get": {
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "path": "v1/inventorySources/{+inventorySourceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.get",
          "httpMethod": "GET",
          "description": "Gets an inventory source."
        },
        "list": {
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/inventorySources",
          "flatPath": "v1/inventorySources",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.list"
        }
      }
    },
    "sdfdownloadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.sdfdownloadtasks.operations.get"
            }
          }
        }
      },
      "methods": {
        "create": {
          "flatPath": "v1/sdfdownloadtasks",
          "path": "v1/sdfdownloadtasks",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "id": "displayvideo.sdfdownloadtasks.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1/floodlightGroups/{floodlightGroupId}",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "id": "displayvideo.floodlightGroups.patch",
          "flatPath": "v1/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group.",
          "httpMethod": "GET",
          "id": "displayvideo.floodlightGroups.get",
          "flatPath": "v1/floodlightGroups/{floodlightGroupsId}",
          "path": "v1/floodlightGroups/{+floodlightGroupId}"
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "description": "Gets a custom list.",
          "httpMethod": "GET",
          "path": "v1/customLists/{+customListId}",
          "id": "displayvideo.customLists.get",
          "flatPath": "v1/customLists/{customListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v1/customLists",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "id": "displayvideo.customLists.list",
          "httpMethod": "GET",
          "path": "v1/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "list": {
          "flatPath": "v1/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "path": "v1/customBiddingAlgorithms",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.list"
        },
        "get": {
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "search": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions:search",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "httpMethod": "POST"
            },
            "list": {
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists targeting options of a given type.",
              "httpMethod": "GET"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "httpMethod": "GET",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}"
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "bulkEditAssignedUserRoles": {
          "path": "v1/users/{+userId}:bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "flatPath": "v1/users/{usersId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates an existing user. Returns the updated user if successful.",
          "id": "displayvideo.users.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users/{usersId}",
          "path": "v1/users/{+userId}",
          "httpMethod": "PATCH"
        },
        "create": {
          "path": "v1/users",
          "flatPath": "v1/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "id": "displayvideo.users.create"
        },
        "delete": {
          "description": "Deletes a user.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users/{usersId}",
          "path": "v1/users/{+userId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.users.delete"
        },
        "get": {
          "path": "v1/users/{+userId}",
          "id": "displayvideo.users.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Gets a user.",
          "httpMethod": "GET",
          "flatPath": "v1/users/{usersId}"
        },
        "list": {
          "flatPath": "v1/users",
          "path": "v1/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.list"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "description": "Gets an advertiser.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers/{advertisersId}",
          "path": "v1/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.get"
        },
        "bulkListAdvertiserAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions",
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions"
        },
        "list": {
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.list",
          "httpMethod": "GET",
          "flatPath": "v1/advertisers",
          "path": "v1/advertisers"
        },
        "audit": {
          "id": "displayvideo.advertisers.audit",
          "flatPath": "v1/advertisers/{advertisersId}:audit",
          "httpMethod": "GET",
          "path": "v1/advertisers/{+advertiserId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450."
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "path": "v1/advertisers/{+advertiserId}"
        },
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "httpMethod": "POST",
          "description": "Bulk edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.patch",
          "flatPath": "v1/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "path": "v1/advertisers/{+advertiserId}"
        },
        "create": {
          "flatPath": "v1/advertisers",
          "id": "displayvideo.advertisers.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete."
        }
      },
      "resources": {
        "assets": {
          "methods": {
            "upload": {
              "supportsMediaUpload": true,
              "flatPath": "v1/advertisers/{advertisersId}/assets",
              "id": "displayvideo.advertisers.assets.upload",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/assets",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "lineItems": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to a line item.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list"
                    },
                    "get": {
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "description": "Deletes an assigned targeting option from a line item.",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "generateDefault": {
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems:generateDefault",
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "path": "v1/advertisers/{+advertiserId}/lineItems:generateDefault",
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.create",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems"
            },
            "delete": {
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "DELETE",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "id": "displayvideo.advertisers.lineItems.delete"
            },
            "bulkEditLineItemAssignedTargetingOptions": {
              "description": "Bulk edits targeting options under a single line item. The operation will delete the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.create_requests .",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions"
            },
            "get": {
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "GET",
              "description": "Gets a line item."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.list",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "path": "v1/advertisers/{+advertiserId}/lineItems"
            },
            "bulkListLineItemAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates an existing line item. Returns the updated line item if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.lineItems.patch",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "list": {
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.manualTriggers.list",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers"
            },
            "deactivate": {
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "description": "Deactivates a manual trigger.",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.create"
            },
            "patch": {
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a manual trigger.",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "id": "displayvideo.advertisers.manualTriggers.get"
            },
            "activate": {
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate"
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations."
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list.",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "description": "Deletes the assignment between a location and a location list."
                },
                "create": {
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Creates an assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          },
          "methods": {
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a location list.",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.locationLists.create",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists location lists based on a given advertiser id.",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                },
                "list": {
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list"
                },
                "get": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to an advertiser."
                },
                "create": {
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create"
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "flatPath": "v1/advertisers/{advertisersId}/channels"
            },
            "list": {
              "path": "v1/advertisers/{+advertiserId}/channels",
              "id": "displayvideo.advertisers.channels.list",
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.get",
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}",
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.channels.patch"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites"
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites."
                },
                "replace": {
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites."
                },
                "create": {
                  "description": "Creates a site in a channel.",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel."
                }
              }
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "patch": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful."
            },
            "get": {
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "create": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "httpMethod": "POST",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list."
                },
                "replace": {
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace"
                },
                "list": {
                  "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists negative keywords in a negative keyword list."
                },
                "bulkEdit": {
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "httpMethod": "POST",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "id": "displayvideo.advertisers.creatives.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "id": "displayvideo.advertisers.creatives.list",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "id": "displayvideo.advertisers.creatives.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.get"
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "bulkListInsertionOrderAssignedTargetingOptions": {
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:bulkListInsertionOrderAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.bulkListInsertionOrderAssignedTargetingOptions",
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:bulkListInsertionOrderAssignedTargetingOptions",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH"
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "delete": {
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list"
                    }
                  }
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/invoices",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v1/advertisers/{+advertiserId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "id": "displayvideo.advertisers.invoices.list"
            },
            "lookupInvoiceCurrency": {
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "path": "v1/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency"
            }
          }
        },
        "campaigns": {
          "methods": {
            "delete": {
              "id": "displayvideo.advertisers.campaigns.delete",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "httpMethod": "DELETE"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.patch",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "PATCH"
            },
            "create": {
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v1/advertisers/{+advertiserId}/campaigns"
            },
            "get": {
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Gets a campaign.",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "bulkListCampaignAssignedTargetingOptions": {
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}:bulkListCampaignAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}:bulkListCampaignAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "id": "displayvideo.advertisers.campaigns.bulkListCampaignAssignedTargetingOptions"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type.",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "get": {
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "list": {
          "id": "displayvideo.combinedAudiences.list",
          "httpMethod": "GET",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "flatPath": "v1/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/combinedAudiences"
        },
        "get": {
          "flatPath": "v1/combinedAudiences/{combinedAudiencesId}",
          "id": "displayvideo.combinedAudiences.get",
          "httpMethod": "GET",
          "path": "v1/combinedAudiences/{+combinedAudienceId}",
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    }
  },
  "batchPath": "batch",
  "id": "displayvideo:v1",
  "version": "v1",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "version_module": true,
  "protocol": "rest",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/"
}
