{
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        }
      }
    }
  },
  "resources": {
    "advertisers": {
      "methods": {
        "list": {
          "flatPath": "v2/advertisers",
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "httpMethod": "GET",
          "path": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.get",
          "flatPath": "v2/advertisers/{advertisersId}",
          "description": "Gets an advertiser.",
          "path": "v2/advertisers/{+advertiserId}",
          "httpMethod": "GET"
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "flatPath": "v2/advertisers",
          "id": "displayvideo.advertisers.create",
          "path": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "path": "v2/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v2/advertisers/{advertisersId}"
        },
        "listAssignedTargetingOptions": {
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions"
        },
        "delete": {
          "flatPath": "v2/advertisers/{advertisersId}",
          "path": "v2/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered."
        },
        "audit": {
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}:audit",
          "httpMethod": "GET"
        },
        "editAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions"
        }
      },
      "resources": {
        "youtubeAdGroupAds": {
          "methods": {
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "description": "Lists YouTube ad group ads.",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a YouTube ad group ad."
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                },
                "list": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser."
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives"
            },
            "delete": {
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.creatives.delete",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "id": "displayvideo.advertisers.creatives.create"
            },
            "patch": {
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "id": "displayvideo.advertisers.creatives.patch",
              "httpMethod": "PATCH",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "GET",
              "description": "Gets a creative."
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "activate": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.manualTriggers.activate"
            },
            "list": {
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.manualTriggers.list",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers"
            },
            "get": {
              "id": "displayvideo.advertisers.manualTriggers.get",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "description": "Gets a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "deactivate": {
              "description": "Deactivates a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "httpMethod": "POST"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "id": "displayvideo.advertisers.manualTriggers.create",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers"
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "httpMethod": "PATCH"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "httpMethod": "DELETE"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.list"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "create": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords"
                },
                "bulkEdit": {
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure."
                },
                "replace": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete"
                }
              }
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "get": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.get",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}"
            },
            "delete": {
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful."
            },
            "create": {
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "httpMethod": "POST"
            },
            "listAssignedTargetingOptions": {
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "id": "displayvideo.advertisers.insertionOrders.listAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:listAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:listAssignedTargetingOptions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from an insertion order. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPE[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.delete"
                    },
                    "create": {
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to an insertion order. Returns the assigned targeting option if successful. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEG[...]"
                    },
                    "list": {
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type.",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "list": {
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list"
            },
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "httpMethod": "PATCH"
            },
            "listAssignedTargetingOptions": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.listAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}:listAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}:listAssignedTargetingOptions"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Gets a campaign."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "POST",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.create",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.delete"
            }
          }
        },
        "lineItems": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Gets a line item.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "bulkEditAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]"
            },
            "list": {
              "id": "displayvideo.advertisers.lineItems.list",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "create": {
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.create",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions"
            },
            "bulkUpdate": {
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.patch"
            },
            "duplicate": {
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate"
            },
            "generateDefault": {
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems:generateDefault",
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:generateDefault",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "httpMethod": "POST",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption"
                    },
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            }
          }
        },
        "youtubeAdGroups": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups",
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "description": "Lists YouTube ad groups."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "description": "Gets a YouTube ad group.",
              "id": "displayvideo.advertisers.youtubeAdGroups.get"
            },
            "bulkListAdGroupAssignedTargetingOptions": {
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherieted assigned targeting options are not included.",
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get",
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "lookupInvoiceCurrency": {
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency"
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/invoices",
              "id": "displayvideo.advertisers.invoices.list"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "path": "v2/advertisers/{+advertiserId}/assets",
              "supportsMediaUpload": true,
              "flatPath": "v2/advertisers/{advertisersId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.assets.upload"
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit"
                },
                "list": {
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.channels.sites.list"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "id": "displayvideo.advertisers.channels.sites.delete"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace"
                }
              }
            }
          },
          "methods": {
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "id": "displayvideo.advertisers.channels.list",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}"
            },
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.get",
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}"
            }
          }
        },
        "locationLists": {
          "methods": {
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}",
              "id": "displayvideo.advertisers.locationLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a location list. Returns the updated location list if successful.",
              "httpMethod": "PATCH"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists location lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list",
              "httpMethod": "GET"
            },
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/locationLists"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "create": {
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list."
                },
                "list": {
                  "description": "Lists locations assigned to a location list.",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "delete": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit"
                }
              }
            }
          }
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "patch": {
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful.",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "PATCH"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "flatPath": "v2/customBiddingAlgorithms",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v2/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.list"
        },
        "uploadScript": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript"
        },
        "get": {
          "description": "Gets a custom bidding algorithm.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts"
            },
            "get": {
              "description": "Gets a custom bidding script.",
              "httpMethod": "GET",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful.",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "list": {
          "flatPath": "v2/inventorySources",
          "path": "v2/inventorySources",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results."
        },
        "get": {
          "description": "Gets an inventory source.",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.get",
          "path": "v2/inventorySources/{+inventorySourceId}",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/inventorySources/{+inventorySourceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.patch",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful."
        },
        "editInventorySourceReadWriteAccessors": {
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "path": "v2/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "flatPath": "v2/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "id": "displayvideo.inventorySources.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySources",
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "flatPath": "v2/inventorySources"
        }
      }
    },
    "users": {
      "methods": {
        "bulkEditAssignedUserRoles": {
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.patch",
          "path": "v2/users/{+userId}",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "PATCH",
          "flatPath": "v2/users/{usersId}"
        },
        "delete": {
          "path": "v2/users/{+userId}",
          "flatPath": "v2/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.delete",
          "httpMethod": "DELETE"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.create",
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v2/users",
          "flatPath": "v2/users",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users",
          "httpMethod": "GET",
          "id": "displayvideo.users.list",
          "path": "v2/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}",
          "httpMethod": "GET",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v2/users/{usersId}",
          "id": "displayvideo.users.get"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "id": "displayvideo.media.download",
          "flatPath": "download/{downloadId}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "path": "download/{+resourceName}",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "httpMethod": "GET"
        },
        "upload": {
          "supportsMediaUpload": true,
          "flatPath": "media/{mediaId}",
          "path": "media/{+resourceName}",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "httpMethod": "POST",
          "id": "displayvideo.media.upload"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "path": "v2/googleAudiences/{+googleAudienceId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Google audience.",
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "id": "displayvideo.googleAudiences.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.googleAudiences.list",
          "httpMethod": "GET",
          "flatPath": "v2/googleAudiences",
          "path": "v2/googleAudiences"
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "httpMethod": "POST",
          "id": "displayvideo.guaranteedOrders.create",
          "flatPath": "v2/guaranteedOrders",
          "path": "v2/guaranteedOrders"
        },
        "list": {
          "id": "displayvideo.guaranteedOrders.list",
          "path": "v2/guaranteedOrders",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "httpMethod": "GET",
          "flatPath": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "httpMethod": "PATCH",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.patch"
        },
        "get": {
          "description": "Gets a guaranteed order.",
          "httpMethod": "GET",
          "id": "displayvideo.guaranteedOrders.get",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editGuaranteedOrderReadAccessors": {
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "description": "Edits read advertisers of a guaranteed order.",
          "httpMethod": "POST",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customLists": {
      "methods": {
        "list": {
          "flatPath": "v2/customLists",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customLists",
          "id": "displayvideo.customLists.list"
        },
        "get": {
          "id": "displayvideo.customLists.get",
          "flatPath": "v2/customLists/{customListsId}",
          "description": "Gets a custom list.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customLists/{+customListId}"
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "list": {
          "id": "displayvideo.combinedAudiences.list",
          "path": "v2/combinedAudiences",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "flatPath": "v2/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.get",
          "httpMethod": "GET",
          "path": "v2/combinedAudiences/{+combinedAudienceId}"
        }
      }
    },
    "partners": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                },
                "delete": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                },
                "list": {
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "description": "Lists the targeting options assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "create": {
              "id": "displayvideo.partners.channels.create",
              "httpMethod": "POST",
              "path": "v2/partners/{+partnerId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v2/partners/{partnersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v2/partners/{+partnerId}/channels/{+channelId}",
              "id": "displayvideo.partners.channels.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}",
              "description": "Gets a channel for a partner or advertiser."
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v2/partners/{partnersId}/channels",
              "path": "v2/partners/{+partnerId}/channels",
              "id": "displayvideo.partners.channels.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "patch": {
              "id": "displayvideo.partners.channels.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels/{channelId}",
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful."
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}"
                },
                "replace": {
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.partners.channels.sites.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "displayvideo.partners.channels.sites.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites",
                  "description": "Lists sites in a channel.",
                  "httpMethod": "GET"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel.",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.create",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites"
                }
              }
            }
          }
        }
      },
      "methods": {
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "id": "displayvideo.partners.editAssignedTargetingOptions"
        },
        "get": {
          "id": "displayvideo.partners.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/partners/{partnersId}",
          "path": "v2/partners/{+partnerId}",
          "httpMethod": "GET",
          "description": "Gets a partner."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v2/partners",
          "path": "v2/partners",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "id": "displayvideo.partners.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST"
            },
            "create": {
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "description": "Creates an assignment between an inventory source and an inventory source group."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "delete": {
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}"
            }
          }
        }
      },
      "methods": {
        "get": {
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "description": "Gets an inventory source group.",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v2/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list",
          "path": "v2/inventorySourceGroups"
        },
        "create": {
          "httpMethod": "POST",
          "flatPath": "v2/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v2/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "description": "Deletes an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.delete"
        },
        "patch": {
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.patch",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH"
        }
      }
    },
    "sdfdownloadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v2/{+name}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}"
            }
          }
        }
      },
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/sdfdownloadtasks",
          "path": "v2/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "patch": {
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "httpMethod": "PATCH",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "description": "Gets a first and third party audience.",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/firstAndThirdPartyAudiences",
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "editCustomerMatchMembers": {
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "httpMethod": "POST",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers"
        },
        "list": {
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "path": "v2/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "search": {
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists targeting options of a given type.",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions"
            },
            "get": {
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "description": "Gets a single targeting option.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}"
            }
          }
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "id": "displayvideo.floodlightGroups.get",
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}",
          "path": "v2/floodlightGroups/{+floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group.",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v2/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful."
        }
      }
    }
  },
  "title": "Display & Video 360 API",
  "ownerDomain": "google.com",
  "version": "v2",
  "protocol": "rest",
  "version_module": true,
  "servicePath": "",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "name": "displayvideo",
  "revision": "20230906",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "id": "displayvideo:v2",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/display-video/",
  "canonicalName": "Display Video",
  "basePath": "",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/"
}
