{
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "title": "Display & Video 360 API",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "name": "displayvideo",
  "canonicalName": "Display Video",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "id": "displayvideo:v2",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "resources": {
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources"
            },
            "list": {
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists inventory sources assigned to an inventory source group.",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "httpMethod": "DELETE",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEdit": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources."
            }
          }
        }
      },
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "path": "v2/inventorySourceGroups",
          "httpMethod": "POST",
          "id": "displayvideo.inventorySourceGroups.create",
          "flatPath": "v2/inventorySourceGroups"
        },
        "patch": {
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.list",
          "path": "v2/inventorySourceGroups",
          "flatPath": "v2/inventorySourceGroups",
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.get",
          "description": "Gets an inventory source group."
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "displayvideo.inventorySourceGroups.delete",
          "description": "Deletes an inventory source group.",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}"
        }
      }
    },
    "partners": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/partners/{partnersId}",
          "httpMethod": "GET",
          "path": "v2/partners/{+partnerId}",
          "id": "displayvideo.partners.get",
          "description": "Gets a partner."
        },
        "list": {
          "flatPath": "v2/partners",
          "path": "v2/partners",
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "id": "displayvideo.partners.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editAssignedTargetingOptions": {
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "httpMethod": "POST",
          "id": "displayvideo.partners.editAssignedTargetingOptions"
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v2/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.list",
              "path": "v2/partners/{+partnerId}/channels",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v2/partners/{+partnerId}/channels/{+channelId}",
              "id": "displayvideo.partners.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}"
            },
            "create": {
              "flatPath": "v2/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "httpMethod": "POST",
              "path": "v2/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "id": "displayvideo.partners.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels/{channelId}"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.create",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites",
                  "description": "Creates a site in a channel.",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.partners.channels.sites.replace",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace"
                },
                "bulkEdit": {
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "displayvideo.partners.channels.sites.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "description": "Lists sites in a channel.",
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites"
                },
                "delete": {
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "delete": {
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from a partner."
                },
                "list": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner."
                },
                "get": {
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST"
                }
              }
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "list": {
          "path": "v2/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "GET",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "flatPath": "v2/users",
          "id": "displayvideo.users.list"
        },
        "delete": {
          "path": "v2/users/{+userId}",
          "flatPath": "v2/users/{usersId}",
          "description": "Deletes a user.",
          "id": "displayvideo.users.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "DELETE"
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "path": "v2/users",
          "id": "displayvideo.users.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users"
        },
        "bulkEditAssignedUserRoles": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles"
        },
        "patch": {
          "id": "displayvideo.users.patch",
          "httpMethod": "PATCH",
          "flatPath": "v2/users/{usersId}",
          "description": "Updates an existing user. Returns the updated user if successful.",
          "path": "v2/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}",
          "httpMethod": "GET",
          "id": "displayvideo.users.get",
          "flatPath": "v2/users/{usersId}",
          "description": "Gets a user."
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "list": {
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/firstAndThirdPartyAudiences",
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "httpMethod": "GET"
        },
        "editCustomerMatchMembers": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "httpMethod": "POST",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers"
        },
        "patch": {
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}"
        },
        "create": {
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "path": "v2/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "description": "Gets a first and third party audience."
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "get": {
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.get",
          "description": "Gets a custom bidding algorithm.",
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.create",
          "flatPath": "v2/customBiddingAlgorithms",
          "path": "v2/customBiddingAlgorithms",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful.",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "uploadScript": {
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript"
        },
        "list": {
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "path": "v2/customBiddingAlgorithms",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "get": {
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "description": "Gets a custom bidding script.",
              "httpMethod": "GET",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}"
            },
            "list": {
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "httpMethod": "GET",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful."
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "flatPath": "v2/sdfdownloadtasks",
          "path": "v2/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}",
              "path": "v2/{+name}"
            }
          }
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "get": {
          "description": "Gets a guaranteed order.",
          "httpMethod": "GET",
          "id": "displayvideo.guaranteedOrders.get",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}"
        },
        "list": {
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.list",
          "path": "v2/guaranteedOrders"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.guaranteedOrders.patch",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}"
        },
        "create": {
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "path": "v2/guaranteedOrders",
          "flatPath": "v2/guaranteedOrders",
          "httpMethod": "POST",
          "id": "displayvideo.guaranteedOrders.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editGuaranteedOrderReadAccessors": {
          "httpMethod": "POST",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "description": "Edits read advertisers of a guaranteed order.",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.get",
          "description": "Gets a custom list.",
          "httpMethod": "GET",
          "path": "v2/customLists/{+customListId}",
          "flatPath": "v2/customLists/{customListsId}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v2/customLists",
          "id": "displayvideo.customLists.list",
          "path": "v2/customLists",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/combinedAudiences/{+combinedAudienceId}",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.get",
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "description": "Gets a combined audience."
        },
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.list",
          "flatPath": "v2/combinedAudiences",
          "path": "v2/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists combined audiences. The order is defined by the order_by parameter."
        }
      }
    },
    "inventorySources": {
      "methods": {
        "editInventorySourceReadWriteAccessors": {
          "flatPath": "v2/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "httpMethod": "POST",
          "path": "v2/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v2/inventorySources",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.list"
        },
        "create": {
          "flatPath": "v2/inventorySources",
          "path": "v2/inventorySources",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "id": "displayvideo.inventorySources.create"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySources/{+inventorySourceId}",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "httpMethod": "PATCH",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.patch"
        },
        "get": {
          "path": "v2/inventorySources/{+inventorySourceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets an inventory source.",
          "id": "displayvideo.inventorySources.get",
          "flatPath": "v2/inventorySources/{inventorySourcesId}"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "id": "displayvideo.floodlightGroups.get",
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group.",
          "path": "v2/floodlightGroups/{+floodlightGroupId}",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "id": "displayvideo.floodlightGroups.patch",
          "httpMethod": "PATCH",
          "path": "v2/floodlightGroups/{floodlightGroupId}"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "description": "Gets a Google audience.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.get",
          "path": "v2/googleAudiences/{+googleAudienceId}"
        },
        "list": {
          "flatPath": "v2/googleAudiences",
          "httpMethod": "GET",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/googleAudiences",
          "id": "displayvideo.googleAudiences.list"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions",
              "description": "Lists targeting options of a given type."
            },
            "get": {
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "description": "Gets a single targeting option.",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}"
            },
            "search": {
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "flatPath": "media/{mediaId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "path": "media/{+resourceName}",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "id": "displayvideo.media.upload",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string."
        },
        "download": {
          "path": "download/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.download",
          "flatPath": "download/{downloadId}",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string."
        }
      }
    },
    "advertisers": {
      "resources": {
        "lineItems": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetingOption"
                    },
                    "list": {
                      "description": "Lists the targeting options assigned to a line item.",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "create": {
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * DeleteLineItemAssignedTargetingOption",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "httpMethod": "POST",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "id": "displayvideo.advertisers.lineItems.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "generateDefault": {
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:generateDefault",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems:generateDefault"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "description": "Gets a line item.",
              "id": "displayvideo.advertisers.lineItems.get"
            },
            "bulkListAssignedTargetingOptions": {
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetin[...]",
              "httpMethod": "POST"
            },
            "duplicate": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "httpMethod": "POST",
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.create"
            },
            "bulkUpdate": {
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate"
            },
            "list": {
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.list",
              "path": "v2/advertisers/{+advertiserId}/lineItems"
            }
          }
        },
        "insertionOrders": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.create",
                      "httpMethod": "POST",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to an insertion order. Returns the assigned targeting option if successful. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEG[...]"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to an insertion order."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Deletes an assigned targeting option from an insertion order. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPE[...]"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.list",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "GET"
            },
            "listAssignedTargetingOptions": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:listAssignedTargetingOptions",
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:listAssignedTargetingOptions",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.insertionOrders.listAssignedTargetingOptions"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.get",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist."
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "youtubeAdGroups": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "bulkListAdGroupAssignedTargetingOptions": {
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherieted assigned targeting options are not included.",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "httpMethod": "GET",
              "description": "Lists YouTube ad groups.",
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "id": "displayvideo.advertisers.youtubeAdGroups.get",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a YouTube ad group.",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}"
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "create": {
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}"
                },
                "bulkEdit": {
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "httpMethod": "POST"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "httpMethod": "GET",
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "httpMethod": "POST"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "id": "displayvideo.advertisers.channels.patch",
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.create"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "id": "displayvideo.advertisers.channels.list"
            },
            "get": {
              "id": "displayvideo.advertisers.channels.get",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}"
            }
          }
        },
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "methods": {
                "delete": {
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "httpMethod": "GET"
                },
                "create": {
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "replace": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace"
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists"
            }
          }
        },
        "locationLists": {
          "methods": {
            "create": {
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "id": "displayvideo.advertisers.locationLists.create"
            },
            "list": {
              "id": "displayvideo.advertisers.locationLists.list",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "description": "Lists location lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists"
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch"
            },
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "httpMethod": "POST",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "description": "Creates an assignment between a location and a location list.",
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "list": {
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list"
                },
                "delete": {
                  "description": "Deletes the assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete"
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "lookupInvoiceCurrency": {
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "id": "displayvideo.advertisers.invoices.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/invoices"
            }
          }
        },
        "youtubeAdGroupAds": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "httpMethod": "GET",
              "description": "Lists YouTube ad group ads.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "httpMethod": "GET",
              "description": "Gets a YouTube ad group ad."
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "activate": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.list",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "httpMethod": "GET",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required."
            },
            "create": {
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "id": "displayvideo.advertisers.manualTriggers.create",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers"
            },
            "deactivate": {
              "description": "Deactivates a manual trigger.",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "id": "displayvideo.advertisers.manualTriggers.deactivate"
            },
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.manualTriggers.get",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "description": "Gets a manual trigger."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "httpMethod": "PATCH",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                },
                "create": {
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                },
                "list": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "httpMethod": "GET",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "patch": {
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.creatives.patch"
            },
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Gets a creative.",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "create": {
              "id": "displayvideo.advertisers.creatives.create",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/creatives"
            },
            "delete": {
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.delete",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted."
            },
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v2/advertisers/{advertisersId}/creatives"
            }
          }
        },
        "campaigns": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list"
                    },
                    "get": {
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "create": {
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful."
            },
            "list": {
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.list",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET",
              "description": "Gets a campaign."
            },
            "listAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.campaigns.listAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}:listAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}:listAssignedTargetingOptions"
            },
            "patch": {
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "flatPath": "v2/advertisers/{advertisersId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "path": "v2/advertisers/{+advertiserId}/assets",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.assets.upload"
            }
          }
        }
      },
      "methods": {
        "editAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "flatPath": "v2/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "path": "v2/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.patch"
        },
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "httpMethod": "GET",
          "path": "v2/advertisers/{+advertiserId}:audit"
        },
        "listAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists assigned targeting options of an advertiser across targeting types."
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/advertisers/{advertisersId}",
          "id": "displayvideo.advertisers.get",
          "description": "Gets an advertiser."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.list",
          "path": "v2/advertisers",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "flatPath": "v2/advertisers",
          "httpMethod": "GET"
        },
        "create": {
          "path": "v2/advertisers",
          "flatPath": "v2/advertisers",
          "id": "displayvideo.advertisers.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}",
          "flatPath": "v2/advertisers/{advertisersId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "httpMethod": "DELETE"
        }
      }
    }
  },
  "protocol": "rest",
  "version": "v2",
  "ownerName": "Google",
  "version_module": true,
  "servicePath": "",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/display-video/",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "revision": "20230302",
  "basePath": ""
}
