{
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "resources": {
    "googleAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Google audience.",
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "id": "displayvideo.googleAudiences.get",
          "path": "v2/googleAudiences/{+googleAudienceId}"
        },
        "list": {
          "flatPath": "v2/googleAudiences",
          "id": "displayvideo.googleAudiences.list",
          "path": "v2/googleAudiences",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "path": "v2/customLists/{+customListId}",
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "id": "displayvideo.customLists.get",
          "flatPath": "v2/customLists/{customListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v2/customLists",
          "path": "v2/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.list",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "httpMethod": "GET"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "id": "displayvideo.media.upload",
          "httpMethod": "POST",
          "flatPath": "media/{mediaId}",
          "path": "media/{+resourceName}",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string."
        },
        "download": {
          "flatPath": "download/{downloadId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.download",
          "httpMethod": "GET",
          "path": "download/{+resourceName}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "supportsMediaDownload": true
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "httpMethod": "GET",
              "description": "Gets a single targeting option."
            },
            "list": {
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions",
              "description": "Lists targeting options of a given type.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "httpMethod": "GET",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions"
            },
            "search": {
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search"
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "list": {
          "flatPath": "v2/combinedAudiences",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.list",
          "httpMethod": "GET",
          "path": "v2/combinedAudiences"
        },
        "get": {
          "path": "v2/combinedAudiences/{+combinedAudienceId}",
          "description": "Gets a combined audience.",
          "id": "displayvideo.combinedAudiences.get",
          "httpMethod": "GET",
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "advertisers": {
      "resources": {
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "methods": {
                "bulkEdit": {
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure."
                },
                "create": {
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "POST"
                },
                "list": {
                  "description": "Lists negative keywords in a negative keyword list.",
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords."
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list."
                }
              }
            }
          },
          "methods": {
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "httpMethod": "DELETE"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "httpMethod": "POST"
            }
          }
        },
        "campaigns": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type.",
                      "httpMethod": "GET",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.campaigns.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.delete",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "listAssignedTargetingOptions": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.campaigns.listAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}:listAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}:listAssignedTargetingOptions"
            },
            "create": {
              "id": "displayvideo.advertisers.campaigns.create",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "path": "v2/advertisers/{+advertiserId}/campaigns"
            },
            "get": {
              "description": "Gets a campaign.",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "patch": {
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.patch",
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}"
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit"
                },
                "create": {
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "description": "Creates an assignment between a location and a location list.",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "delete": {
                  "description": "Deletes the assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "description": "Lists locations assigned to a location list.",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful."
            },
            "patch": {
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.patch",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.list",
              "description": "Lists location lists based on a given advertiser id.",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists"
            },
            "get": {
              "id": "displayvideo.advertisers.locationLists.get",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "channels": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.channels.create",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            },
            "get": {
              "id": "displayvideo.advertisers.channels.get",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}"
            },
            "list": {
              "id": "displayvideo.advertisers.channels.list",
              "description": "Lists channels for a partner or advertiser.",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "description": "Lists sites in a channel.",
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.list"
                },
                "bulkEdit": {
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit"
                },
                "delete": {
                  "description": "Deletes a site from a channel.",
                  "httpMethod": "DELETE",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.delete"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites."
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites"
                }
              }
            }
          }
        },
        "lineItems": {
          "methods": {
            "bulkListAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions"
            },
            "bulkUpdate": {
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate"
            },
            "create": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create"
            },
            "duplicate": {
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.duplicate"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a line item.",
              "id": "displayvideo.advertisers.lineItems.get",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "bulkEditAssignedTargetingOptions": {
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetin[...]",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions"
            },
            "delete": {
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.list",
              "path": "v2/advertisers/{+advertiserId}/lineItems"
            },
            "patch": {
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "generateDefault": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems:generateDefault",
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:generateDefault"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetingOption",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * DeleteLineItemAssignedTargetingOption",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "get": {
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    }
                  }
                }
              }
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "deactivate": {
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "description": "Deactivates a manual trigger.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "id": "displayvideo.advertisers.manualTriggers.get",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a manual trigger.",
              "httpMethod": "GET"
            },
            "activate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "httpMethod": "POST",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "httpMethod": "GET",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "id": "displayvideo.advertisers.manualTriggers.list"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.create",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers"
            },
            "patch": {
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                },
                "list": {
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "httpMethod": "GET"
                },
                "delete": {
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from an advertiser."
                }
              }
            }
          }
        },
        "youtubeAdGroups": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "get": {
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}",
              "description": "Gets a YouTube ad group.",
              "id": "displayvideo.advertisers.youtubeAdGroups.get",
              "httpMethod": "GET"
            },
            "bulkListAdGroupAssignedTargetingOptions": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherieted assigned targeting options are not included.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "description": "Lists YouTube ad groups.",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups"
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "httpMethod": "PATCH"
            },
            "create": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            },
            "listAssignedTargetingOptions": {
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "id": "displayvideo.advertisers.insertionOrders.listAssignedTargetingOptions",
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:listAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:listAssignedTargetingOptions"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from an insertion order. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPE[...]",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.delete",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "create": {
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.create",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to an insertion order. Returns the assigned targeting option if successful. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEG[...]",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "get": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    }
                  }
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "flatPath": "v2/advertisers/{advertisersId}/assets",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "path": "v2/advertisers/{+advertiserId}/assets",
              "id": "displayvideo.advertisers.assets.upload"
            }
          }
        },
        "creatives": {
          "methods": {
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "httpMethod": "GET"
            },
            "delete": {
              "id": "displayvideo.advertisers.creatives.delete",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "id": "displayvideo.advertisers.creatives.create",
              "httpMethod": "POST"
            },
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a creative.",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "displayvideo.advertisers.creatives.patch",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "youtubeAdGroupAds": {
          "methods": {
            "get": {
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a YouTube ad group ad."
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "description": "Lists YouTube ad group ads.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/invoices",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.invoices.list",
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "httpMethod": "GET"
            },
            "lookupInvoiceCurrency": {
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency"
            }
          }
        }
      },
      "methods": {
        "audit": {
          "id": "displayvideo.advertisers.audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "path": "v2/advertisers/{+advertiserId}:audit",
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "path": "v2/advertisers/{+advertiserId}",
          "flatPath": "v2/advertisers/{advertisersId}",
          "id": "displayvideo.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "v2/advertisers",
          "id": "displayvideo.advertisers.list",
          "httpMethod": "GET",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "flatPath": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "listAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "description": "Lists assigned targeting options of an advertiser across targeting types."
        },
        "editAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions"
        },
        "get": {
          "path": "v2/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an advertiser.",
          "httpMethod": "GET",
          "flatPath": "v2/advertisers/{advertisersId}",
          "id": "displayvideo.advertisers.get"
        },
        "create": {
          "path": "v2/advertisers",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.create",
          "flatPath": "v2/advertisers"
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "flatPath": "v2/advertisers/{advertisersId}"
        }
      }
    },
    "partners": {
      "methods": {
        "list": {
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v2/partners",
          "flatPath": "v2/partners",
          "id": "displayvideo.partners.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "flatPath": "v2/partners/{partnersId}",
          "path": "v2/partners/{+partnerId}",
          "description": "Gets a partner.",
          "id": "displayvideo.partners.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        },
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions"
        }
      },
      "resources": {
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel."
                },
                "replace": {
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.replace",
                  "httpMethod": "POST",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites."
                },
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "id": "displayvideo.partners.channels.sites.bulkEdit"
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.partners.channels.sites.list",
                  "httpMethod": "GET",
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "id": "displayvideo.partners.channels.sites.create",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel."
                }
              }
            }
          },
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "path": "v2/partners/{+partnerId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.partners.channels.patch"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.partners.channels.create",
              "flatPath": "v2/partners/{partnersId}/channels",
              "path": "v2/partners/{+partnerId}/channels"
            },
            "list": {
              "flatPath": "v2/partners/{partnersId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "path": "v2/partners/{+partnerId}/channels",
              "id": "displayvideo.partners.channels.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v2/partners/{+partnerId}/channels/{+channelId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}",
              "id": "displayvideo.partners.channels.get"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from a partner.",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete"
                },
                "list": {
                  "description": "Lists the targeting options assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "path": "v2/firstAndThirdPartyAudiences",
          "flatPath": "v2/firstAndThirdPartyAudiences"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "httpMethod": "PATCH",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "description": "Gets a first and third party audience."
        },
        "editCustomerMatchMembers": {
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "httpMethod": "POST",
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "httpMethod": "POST",
          "path": "v2/firstAndThirdPartyAudiences"
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "create": {
          "flatPath": "v2/customBiddingAlgorithms",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "path": "v2/customBiddingAlgorithms"
        },
        "uploadScript": {
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "id": "displayvideo.customBiddingAlgorithms.list",
          "path": "v2/customBiddingAlgorithms",
          "flatPath": "v2/customBiddingAlgorithms",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful.",
          "id": "displayvideo.customBiddingAlgorithms.patch"
        },
        "get": {
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "create": {
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful.",
              "httpMethod": "POST",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "httpMethod": "GET",
              "description": "Gets a custom bidding script.",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "list": {
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.list"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "editInventorySourceReadWriteAccessors": {
          "path": "v2/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "httpMethod": "POST",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors"
        },
        "create": {
          "id": "displayvideo.inventorySources.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "path": "v2/inventorySources",
          "flatPath": "v2/inventorySources",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets an inventory source.",
          "httpMethod": "GET",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySources/{+inventorySourceId}",
          "id": "displayvideo.inventorySources.get"
        },
        "patch": {
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "path": "v2/inventorySources/{+inventorySourceId}"
        },
        "list": {
          "id": "displayvideo.inventorySources.list",
          "path": "v2/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources",
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results."
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "flatPath": "v2/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/sdfdownloadtasks",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET",
              "path": "v2/{+name}",
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}"
            }
          }
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "patch": {
          "id": "displayvideo.floodlightGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "path": "v2/floodlightGroups/{floodlightGroupId}"
        },
        "get": {
          "path": "v2/floodlightGroups/{+floodlightGroupId}",
          "httpMethod": "GET",
          "id": "displayvideo.floodlightGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group.",
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}"
        }
      }
    },
    "users": {
      "methods": {
        "list": {
          "flatPath": "v2/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "id": "displayvideo.users.list",
          "httpMethod": "GET",
          "path": "v2/users"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/users/{+userId}",
          "id": "displayvideo.users.patch",
          "flatPath": "v2/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Updates an existing user. Returns the updated user if successful."
        },
        "bulkEditAssignedUserRoles": {
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "httpMethod": "POST",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users/{usersId}",
          "description": "Deletes a user.",
          "path": "v2/users/{+userId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.users.delete"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Creates a new user. Returns the newly created user if successful.",
          "path": "v2/users",
          "flatPath": "v2/users",
          "id": "displayvideo.users.create",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets a user.",
          "id": "displayvideo.users.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}",
          "httpMethod": "GET",
          "flatPath": "v2/users/{usersId}"
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "delete": {
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.delete"
        },
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}"
        },
        "create": {
          "flatPath": "v2/inventorySourceGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v2/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful."
        },
        "list": {
          "flatPath": "v2/inventorySourceGroups",
          "path": "v2/inventorySourceGroups",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.list",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "httpMethod": "POST"
            },
            "list": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists inventory sources assigned to an inventory source group.",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "GET"
            },
            "bulkEdit": {
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}"
            }
          }
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "list": {
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v2/guaranteedOrders",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.list",
          "path": "v2/guaranteedOrders"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "id": "displayvideo.guaranteedOrders.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}"
        },
        "get": {
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.get",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "httpMethod": "GET"
        },
        "create": {
          "id": "displayvideo.guaranteedOrders.create",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "httpMethod": "POST",
          "path": "v2/guaranteedOrders",
          "flatPath": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editGuaranteedOrderReadAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "description": "Edits read advertisers of a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST"
        }
      }
    }
  },
  "servicePath": "",
  "basePath": "",
  "id": "displayvideo:v2",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "version_module": true,
  "name": "displayvideo",
  "documentationLink": "https://developers.google.com/display-video/",
  "canonicalName": "Display Video",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "protocol": "rest",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "version": "v2",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "batchPath": "batch",
  "revision": "20230209",
  "title": "Display & Video 360 API",
  "ownerDomain": "google.com"
}
