{
  "baseUrl": "https://displayvideo.googleapis.com/",
  "protocol": "rest",
  "servicePath": "",
  "canonicalName": "Display Video",
  "documentationLink": "https://developers.google.com/display-video/",
  "kind": "discovery#restDescription",
  "title": "Display & Video 360 API",
  "discoveryVersion": "v1",
  "resources": {
    "floodlightGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group.",
          "id": "displayvideo.floodlightGroups.get",
          "httpMethod": "GET",
          "flatPath": "v1/floodlightGroups/{floodlightGroupsId}",
          "path": "v1/floodlightGroups/{+floodlightGroupId}"
        },
        "patch": {
          "flatPath": "v1/floodlightGroups/{floodlightGroupId}",
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v1/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1/googleAudiences/{googleAudiencesId}",
          "description": "Gets a Google audience.",
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.get"
        },
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.list",
          "path": "v1/googleAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "flatPath": "v1/googleAudiences"
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "flatPath": "v1/guaranteedOrders/{guaranteedOrdersId}",
          "path": "v1/guaranteedOrders/{+guaranteedOrderId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.patch"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.list",
          "flatPath": "v1/guaranteedOrders",
          "path": "v1/guaranteedOrders",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "httpMethod": "GET"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.create",
          "path": "v1/guaranteedOrders",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "httpMethod": "POST"
        },
        "editGuaranteedOrderReadAccessors": {
          "description": "Edits read advertisers of a guaranteed order.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v1/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v1/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.get",
          "flatPath": "v1/guaranteedOrders/{guaranteedOrdersId}",
          "path": "v1/guaranteedOrders/{+guaranteedOrderId}",
          "httpMethod": "GET"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "description": "Gets a single targeting option.",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "description": "Lists targeting options of a given type.",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions"
            },
            "search": {
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions:search",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "description": "Searches for targeting options of a given type based on the given search terms."
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a combined audience.",
          "httpMethod": "GET",
          "flatPath": "v1/combinedAudiences/{combinedAudiencesId}",
          "id": "displayvideo.combinedAudiences.get",
          "path": "v1/combinedAudiences/{+combinedAudienceId}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1/combinedAudiences",
          "id": "displayvideo.combinedAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "flatPath": "v1/combinedAudiences"
        }
      }
    },
    "inventorySources": {
      "methods": {
        "create": {
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/inventorySources",
          "flatPath": "v1/inventorySources",
          "id": "displayvideo.inventorySources.create",
          "httpMethod": "POST"
        },
        "editInventorySourceReadWriteAccessors": {
          "flatPath": "v1/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "path": "v1/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "description": "Gets an inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/inventorySources/{+inventorySourceId}",
          "httpMethod": "GET",
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.get"
        },
        "list": {
          "id": "displayvideo.inventorySources.list",
          "path": "v1/inventorySources",
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v1/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "path": "v1/inventorySources/{+inventorySourceId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.inventorySources.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful."
        }
      }
    },
    "partners": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Gets a single targeting option assigned to a partner."
                },
                "list": {
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner."
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "patch": {
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "id": "displayvideo.partners.channels.patch"
            },
            "create": {
              "flatPath": "v1/partners/{partnersId}/channels",
              "httpMethod": "POST",
              "path": "v1/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/partners/{+partnerId}/channels",
              "httpMethod": "GET",
              "id": "displayvideo.partners.channels.list",
              "flatPath": "v1/partners/{partnersId}/channels",
              "description": "Lists channels for a partner or advertiser."
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v1/partners/{+partnerId}/channels/{+channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "id": "displayvideo.partners.channels.get"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.create",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists sites in a channel.",
                  "httpMethod": "GET",
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites",
                  "id": "displayvideo.partners.channels.sites.list"
                },
                "delete": {
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}"
                },
                "replace": {
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "id": "displayvideo.partners.channels.sites.replace",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:replace"
                }
              }
            }
          }
        }
      },
      "methods": {
        "get": {
          "description": "Gets a partner.",
          "httpMethod": "GET",
          "id": "displayvideo.partners.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/partners/{+partnerId}",
          "flatPath": "v1/partners/{partnersId}"
        },
        "list": {
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v1/partners",
          "id": "displayvideo.partners.list",
          "flatPath": "v1/partners",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        },
        "bulkEditPartnerAssignedTargetingOptions": {
          "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions",
          "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions",
          "httpMethod": "POST",
          "flatPath": "v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Bulk edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "httpMethod": "PATCH",
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "id": "displayvideo.inventorySourceGroups.get",
          "httpMethod": "GET",
          "description": "Gets an inventory source group.",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.inventorySourceGroups.delete",
          "description": "Deletes an inventory source group."
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create",
          "flatPath": "v1/inventorySourceGroups",
          "path": "v1/inventorySourceGroups",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful."
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "httpMethod": "POST",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources."
            },
            "delete": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE"
            },
            "create": {
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "httpMethod": "POST",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "description": "Lists inventory sources assigned to an inventory source group."
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "id": "displayvideo.sdfdownloadtasks.create",
          "httpMethod": "POST",
          "flatPath": "v1/sdfdownloadtasks",
          "path": "v1/sdfdownloadtasks",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "patch": {
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful.",
          "httpMethod": "PATCH",
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.patch"
        },
        "create": {
          "id": "displayvideo.customBiddingAlgorithms.create",
          "flatPath": "v1/customBiddingAlgorithms",
          "path": "v1/customBiddingAlgorithms",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful."
        },
        "list": {
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "path": "v1/customBiddingAlgorithms",
          "flatPath": "v1/customBiddingAlgorithms"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "description": "Gets a custom bidding algorithm.",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "httpMethod": "GET",
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "uploadScript": {
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript"
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a custom bidding script.",
              "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "create": {
              "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts"
            },
            "list": {
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts"
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "v1/users/{+userId}",
          "id": "displayvideo.users.get",
          "description": "Gets a user.",
          "flatPath": "v1/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "patch": {
          "flatPath": "v1/users/{usersId}",
          "path": "v1/users/{+userId}",
          "id": "displayvideo.users.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Updates an existing user. Returns the updated user if successful."
        },
        "create": {
          "path": "v1/users",
          "flatPath": "v1/users",
          "id": "displayvideo.users.create",
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "list": {
          "flatPath": "v1/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "id": "displayvideo.users.list",
          "path": "v1/users",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "delete": {
          "id": "displayvideo.users.delete",
          "path": "v1/users/{+userId}",
          "description": "Deletes a user.",
          "flatPath": "v1/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "DELETE"
        },
        "bulkEditAssignedUserRoles": {
          "httpMethod": "POST",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users/{usersId}:bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "path": "v1/users/{+userId}:bulkEditAssignedUserRoles"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "get": {
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "description": "Gets a first and third party audience."
        },
        "editCustomerMatchMembers": {
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/firstAndThirdPartyAudiences",
          "httpMethod": "POST",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "path": "v1/firstAndThirdPartyAudiences"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}"
        },
        "list": {
          "flatPath": "v1/firstAndThirdPartyAudiences",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "path": "v1/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "flatPath": "media/{mediaId}",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "path": "media/{+resourceName}",
          "id": "displayvideo.media.upload"
        },
        "download": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaDownload": true,
          "path": "download/{+resourceName}",
          "id": "displayvideo.media.download",
          "httpMethod": "GET",
          "flatPath": "download/{downloadId}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string."
        }
      }
    },
    "advertisers": {
      "methods": {
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "flatPath": "v1/advertisers/{advertisersId}:audit",
          "httpMethod": "GET",
          "path": "v1/advertisers/{+advertiserId}:audit"
        },
        "bulkListAdvertiserAssignedTargetingOptions": {
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions"
        },
        "patch": {
          "path": "v1/advertisers/{+advertiserId}",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "flatPath": "v1/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "id": "displayvideo.advertisers.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers/{advertisersId}",
          "path": "v1/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.get",
          "description": "Gets an advertiser.",
          "httpMethod": "GET"
        },
        "create": {
          "id": "displayvideo.advertisers.create",
          "flatPath": "v1/advertisers",
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.delete",
          "path": "v1/advertisers/{+advertiserId}",
          "httpMethod": "DELETE",
          "flatPath": "v1/advertisers/{advertisersId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered."
        },
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "description": "Bulk edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
          "httpMethod": "POST",
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1/advertisers",
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "flatPath": "v1/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "insertionOrders": {
          "methods": {
            "bulkListInsertionOrderAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:bulkListInsertionOrderAssignedTargetingOptions",
              "id": "displayvideo.advertisers.insertionOrders.bulkListInsertionOrderAssignedTargetingOptions",
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:bulkListInsertionOrderAssignedTargetingOptions",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "id": "displayvideo.advertisers.insertionOrders.delete"
            },
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "get": {
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get"
                    }
                  }
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives"
            },
            "delete": {
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.delete",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE"
            },
            "patch": {
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "id": "displayvideo.advertisers.creatives.patch",
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a creative.",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.get",
              "httpMethod": "GET"
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel.",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "description": "Deletes a site from a channel.",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          },
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.get",
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}"
            },
            "create": {
              "id": "displayvideo.advertisers.channels.create",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v1/advertisers/{advertisersId}/channels"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.channels.patch"
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "path": "v1/advertisers/{+advertiserId}/channels"
            }
          }
        },
        "lineItems": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditLineItemAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption"
                    },
                    "delete": {
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditLineItemAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption"
                    },
                    "get": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "create": {
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditLineItemAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under a single line item. The operation will delete the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditLineItemAssignedTargetingOptions * Up[...]"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditLineItemAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "get": {
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a line item.",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.get"
            },
            "bulkListLineItemAssignedTargetingOptions": {
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions"
            },
            "list": {
              "id": "displayvideo.advertisers.lineItems.list",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "generateDefault": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems:generateDefault",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems:generateDefault"
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.get"
            },
            "create": {
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit"
                },
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE"
                },
                "create": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "httpMethod": "POST",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords"
                },
                "list": {
                  "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list"
                },
                "replace": {
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "locationLists": {
          "methods": {
            "list": {
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.list"
            },
            "patch": {
              "id": "displayvideo.advertisers.locationLists.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a location list. Returns the updated location list if successful.",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}"
            },
            "create": {
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "path": "v1/advertisers/{+advertiserId}/locationLists"
            },
            "get": {
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "id": "displayvideo.advertisers.locationLists.get"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "description": "Deletes the assignment between a location and a location list."
                },
                "list": {
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "httpMethod": "GET",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit"
                },
                "create": {
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Creates an assignment between a location and a location list.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create"
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "path": "v1/advertisers/{+advertiserId}/invoices",
              "id": "displayvideo.advertisers.invoices.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "flatPath": "v1/advertisers/{advertisersId}/invoices"
            },
            "lookupInvoiceCurrency": {
              "flatPath": "v1/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Retrieves the invoice currency used by an advertiser in a given month."
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.manualTriggers.create",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.manualTriggers.list",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "deactivate": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deactivates a manual trigger.",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate"
            },
            "activate": {
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "GET",
              "description": "Gets a manual trigger.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.manualTriggers.get",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}"
            },
            "patch": {
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "httpMethod": "PATCH",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "id": "displayvideo.advertisers.manualTriggers.patch"
            }
          }
        },
        "campaigns": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.get",
              "description": "Gets a campaign.",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.delete",
              "httpMethod": "DELETE",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/campaigns"
            },
            "bulkListCampaignAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}:bulkListCampaignAssignedTargetingOptions",
              "id": "displayvideo.advertisers.campaigns.bulkListCampaignAssignedTargetingOptions",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}:bulkListCampaignAssignedTargetingOptions",
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type.",
                      "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "id": "displayvideo.advertisers.assets.upload",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "flatPath": "v1/advertisers/{advertisersId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/assets",
              "httpMethod": "POST",
              "supportsMediaUpload": true
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "delete": {
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE"
                },
                "list": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                },
                "get": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "httpMethod": "POST"
                }
              }
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "path": "v1/customLists/{+customListId}",
          "httpMethod": "GET",
          "flatPath": "v1/customLists/{customListsId}",
          "id": "displayvideo.customLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom list."
        },
        "list": {
          "path": "v1/customLists",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/customLists",
          "id": "displayvideo.customLists.list"
        }
      }
    }
  },
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "id": "displayvideo:v1",
  "ownerName": "Google",
  "revision": "20220526",
  "version_module": true,
  "name": "displayvideo",
  "basePath": "",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "version": "v1",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items."
}
