{
  "discoveryVersion": "v1",
  "version": "v1",
  "rootUrl": "https://docs.googleapis.com/",
  "baseUrl": "https://docs.googleapis.com/",
  "documentationLink": "https://developers.google.com/docs/",
  "canonicalName": "Docs",
  "batchPath": "batch",
  "ownerName": "Google",
  "version_module": true,
  "basePath": "",
  "id": "docs:v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/documents.readonly": {
          "description": "View your Google Docs documents"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, create, and edit all Google Docs documents you have access to"
        }
      }
    }
  },
  "resources": {
    "documents": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "v1/documents",
          "httpMethod": "POST",
          "description": "Creates a blank document using the title given in the request. Other fields in the request, including any provided content, are ignored. Returns the created document.",
          "id": "docs.documents.create",
          "path": "v1/documents"
        },
        "get": {
          "description": "Gets the latest version of the specified document.",
          "path": "v1/documents/{documentId}",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/documents.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/documents/{documentId}",
          "id": "docs.documents.get"
        },
        "batchUpdate": {
          "path": "v1/documents/{documentId}:batchUpdate",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "v1/documents/{documentId}:batchUpdate",
          "description": "Applies one or more updates to the document. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and only [...]",
          "httpMethod": "POST",
          "id": "docs.documents.batchUpdate"
        }
      }
    }
  },
  "mtlsRootUrl": "https://docs.mtls.googleapis.com/",
  "revision": "20210615",
  "ownerDomain": "google.com",
  "servicePath": "",
  "description": "Reads and writes Google Docs documents.",
  "kind": "discovery#restDescription",
  "name": "docs",
  "title": "Google Docs API",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true
}
