{
  "title": "Google Drive API",
  "id": "drive:v2",
  "ownerDomain": "google.com",
  "rootUrl": "https://www.googleapis.com/",
  "documentationLink": "https://developers.google.com/drive/",
  "discoveryVersion": "v1",
  "name": "drive",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "version": "v2",
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        }
      }
    }
  },
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "resources": {
    "permissions": {
      "methods": {
        "insert": {
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "httpMethod": "POST",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "DELETE",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "id": "drive.permissions.delete"
        },
        "patch": {
          "id": "drive.permissions.patch",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "list": {
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.list",
          "httpMethod": "GET",
          "description": "Lists a file's or shared drive's permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions"
        },
        "get": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Gets a permission by ID.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.get"
        },
        "getIdForEmail": {
          "description": "Returns the permission ID for an email address.",
          "flatPath": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "permissionIds/{email}",
          "id": "drive.permissions.getIdForEmail",
          "httpMethod": "GET"
        },
        "update": {
          "id": "drive.permissions.update",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}"
        }
      }
    },
    "comments": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.update",
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a comment.",
          "id": "drive.comments.delete",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "id": "drive.comments.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment."
        },
        "get": {
          "id": "drive.comments.get",
          "httpMethod": "GET",
          "description": "Gets a comment by ID.",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "insert": {
          "description": "Creates a new comment on the given file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.insert",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's comments.",
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.list"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "flatPath": "channels/stop",
          "path": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.channels.stop",
          "httpMethod": "POST",
          "description": "Stops watching resources through this channel."
        }
      }
    },
    "properties": {
      "methods": {
        "delete": {
          "description": "Deletes a property.",
          "id": "drive.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE"
        },
        "update": {
          "description": "Updates a property.",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.update",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PUT"
        },
        "list": {
          "id": "drive.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/properties",
          "flatPath": "files/{fileId}/properties",
          "httpMethod": "GET",
          "description": "Lists a file's properties."
        },
        "insert": {
          "httpMethod": "POST",
          "id": "drive.properties.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties",
          "path": "files/{fileId}/properties",
          "description": "Adds a property to a file, or updates it if it already exists."
        },
        "get": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Gets a property by its key.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.properties.get"
        },
        "patch": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PATCH",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.patch",
          "path": "files/{fileId}/properties/{propertyKey}"
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "path": "changes/{changeId}",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "id": "drive.changes.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/{changeId}"
        },
        "getStartPageToken": {
          "description": "Gets the starting pageToken for listing future changes.",
          "path": "changes/startPageToken",
          "flatPath": "changes/startPageToken",
          "id": "drive.changes.getStartPageToken",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists the changes for a user or shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes",
          "supportsSubscription": true,
          "path": "changes",
          "httpMethod": "GET",
          "id": "drive.changes.list"
        },
        "watch": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/watch",
          "supportsSubscription": true,
          "id": "drive.changes.watch",
          "description": "Subscribe to changes for a user.",
          "path": "changes/watch"
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "path": "apps/{appId}",
          "description": "Gets a specific app.",
          "httpMethod": "GET",
          "flatPath": "apps/{appId}",
          "id": "drive.apps.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists a user's installed apps.",
          "id": "drive.apps.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "apps",
          "path": "apps"
        }
      }
    },
    "revisions": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "description": "Updates a revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        },
        "list": {
          "description": "Lists a file's revisions.",
          "path": "files/{fileId}/revisions",
          "id": "drive.revisions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/revisions"
        },
        "get": {
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.get",
          "description": "Gets a specific revision.",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.delete"
        },
        "patch": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.patch",
          "description": "Updates a revision.",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/revisions/{revisionId}"
        }
      }
    },
    "children": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a file into a folder.",
          "flatPath": "files/{folderId}/children",
          "id": "drive.children.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{folderId}/children"
        },
        "delete": {
          "path": "files/{folderId}/children/{childId}",
          "id": "drive.children.delete",
          "description": "Removes a child from a folder.",
          "httpMethod": "DELETE",
          "flatPath": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "flatPath": "files/{folderId}/children/{childId}",
          "httpMethod": "GET",
          "description": "Gets a specific child reference.",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.get"
        },
        "list": {
          "path": "files/{folderId}/children",
          "id": "drive.children.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a folder's children.",
          "httpMethod": "GET",
          "flatPath": "files/{folderId}/children"
        }
      }
    },
    "replies": {
      "methods": {
        "delete": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "id": "drive.replies.delete"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing reply.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update"
        },
        "patch": {
          "id": "drive.replies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "GET",
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Creates a new reply to the given comment.",
          "httpMethod": "POST",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.insert",
          "flatPath": "files/{fileId}/comments/{commentId}/replies"
        },
        "list": {
          "path": "files/{fileId}/comments/{commentId}/replies",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists all of the replies to a comment.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.list"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "description": "Gets the information about the current user along with Drive API settings",
          "id": "drive.about.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "about",
          "path": "about",
          "httpMethod": "GET"
        }
      }
    },
    "files": {
      "methods": {
        "update": {
          "id": "drive.files.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "flatPath": "files/{fileId}",
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than th[...]",
          "path": "files/{fileId}",
          "supportsMediaUpload": true,
          "httpMethod": "PUT"
        },
        "get": {
          "supportsSubscription": true,
          "id": "drive.files.get",
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).",
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "flatPath": "files/{fileId}",
          "path": "files/{fileId}",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.",
          "httpMethod": "DELETE",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}",
          "id": "drive.files.delete"
        },
        "export": {
          "supportsMediaDownload": true,
          "id": "drive.files.export",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "useMediaDownloadService": true,
          "flatPath": "files/{fileId}/export",
          "httpMethod": "GET",
          "path": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "generateIds": {
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "id": "drive.files.generateIds",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/generateIds",
          "path": "files/generateIds"
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "flatPath": "files/{fileId}/listLabels",
          "httpMethod": "GET",
          "description": "Lists the labels on a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.listLabels"
        },
        "watch": {
          "flatPath": "files/{fileId}/watch",
          "path": "files/{fileId}/watch",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "description": "Subscribes to changes to a file.",
          "id": "drive.files.watch"
        },
        "emptyTrash": {
          "description": "Permanently deletes all of the user's trashed files.",
          "flatPath": "files/trash",
          "httpMethod": "DELETE",
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash"
        },
        "copy": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "description": "Creates a copy of the specified file.",
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/copy",
          "path": "files/{fileId}/copy"
        },
        "list": {
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "id": "drive.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files",
          "httpMethod": "GET",
          "flatPath": "files"
        },
        "touch": {
          "id": "drive.files.touch",
          "description": "Set the file's updated time to the current server time.",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/touch",
          "path": "files/{fileId}/touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "modifyLabels": {
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "path": "files/{fileId}/modifyLabels",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.files.modifyLabels"
        },
        "trash": {
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/trash",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/trash",
          "id": "drive.files.trash"
        },
        "insert": {
          "path": "files",
          "id": "drive.files.insert",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `[...]",
          "flatPath": "files"
        },
        "patch": {
          "id": "drive.files.patch",
          "flatPath": "files/{fileId}",
          "path": "files/{fileId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics."
        },
        "untrash": {
          "flatPath": "files/{fileId}/untrash",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "id": "drive.files.untrash",
          "path": "files/{fileId}/untrash"
        }
      }
    },
    "parents": {
      "methods": {
        "get": {
          "description": "Gets a specific parent reference.",
          "id": "drive.parents.get",
          "path": "files/{fileId}/parents/{parentId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/parents/{parentId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "drive.parents.list",
          "description": "Lists a file's parents.",
          "path": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/parents"
        },
        "insert": {
          "path": "files/{fileId}/parents",
          "httpMethod": "POST",
          "description": "Adds a parent folder for a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.insert",
          "flatPath": "files/{fileId}/parents"
        },
        "delete": {
          "path": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.delete",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Removes a parent from a file."
        }
      }
    },
    "teamdrives": {
      "methods": {
        "update": {
          "description": "Deprecated: Use `drives.update` instead.",
          "id": "drive.teamdrives.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "insert": {
          "id": "drive.teamdrives.insert",
          "description": "Deprecated: Use `drives.insert` instead.",
          "flatPath": "teamdrives",
          "path": "teamdrives",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead.",
          "id": "drive.teamdrives.delete"
        },
        "get": {
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "httpMethod": "GET",
          "path": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives",
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.list` instead."
        }
      }
    },
    "drives": {
      "methods": {
        "hide": {
          "flatPath": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "id": "drive.drives.hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}/hide",
          "httpMethod": "POST"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.update",
          "flatPath": "drives/{driveId}",
          "httpMethod": "PUT",
          "path": "drives/{driveId}",
          "description": "Updates the metadata for a shared drive."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}",
          "httpMethod": "DELETE",
          "id": "drive.drives.delete",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items."
        },
        "get": {
          "description": "Gets a shared drive's metadata by ID.",
          "id": "drive.drives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drives/{driveId}",
          "httpMethod": "GET",
          "flatPath": "drives/{driveId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives",
          "id": "drive.drives.list",
          "path": "drives",
          "httpMethod": "GET",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide."
        },
        "unhide": {
          "description": "Restores a shared drive to the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/unhide",
          "id": "drive.drives.unhide",
          "httpMethod": "POST",
          "path": "drives/{driveId}/unhide"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "drive.drives.insert",
          "path": "drives",
          "description": "Creates a new shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives"
        }
      }
    }
  },
  "batchPath": "batch/drive/v2",
  "basePath": "/drive/v2/",
  "protocol": "rest",
  "revision": "20230822",
  "servicePath": "drive/v2/"
}
