{
  "protocol": "rest",
  "name": "drive",
  "discoveryVersion": "v1",
  "revision": "20230502",
  "version": "v2",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        }
      }
    }
  },
  "title": "Google Drive API",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "baseUrl": "https://www.googleapis.com/",
  "servicePath": "",
  "rootUrl": "https://www.googleapis.com/",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "batchPath": "batch/drive/v2",
  "documentationLink": "https://developers.google.com/drive/",
  "basePath": "",
  "id": "drive:v2",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "resources": {
    "replies": {
      "methods": {
        "insert": {
          "id": "drive.replies.insert",
          "description": "Creates a new reply to the given comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "path": "drive/v2/files/{fileId}/comments/{commentId}/replies",
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}/replies"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "drive.replies.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing reply.",
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}",
          "path": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "patch": {
          "description": "Updates an existing reply.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.patch",
          "path": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "get": {
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a reply.",
          "path": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "list": {
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.list",
          "httpMethod": "GET",
          "path": "drive/v2/files/{fileId}/comments/{commentId}/replies",
          "description": "Lists all of the replies to a comment."
        },
        "delete": {
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "DELETE",
          "description": "Deletes a reply.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "drive/v2/files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete"
        }
      }
    },
    "revisions": {
      "methods": {
        "patch": {
          "flatPath": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.patch",
          "description": "Updates a revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PATCH",
          "path": "drive/v2/files/{fileId}/revisions/{revisionId}"
        },
        "get": {
          "id": "drive.revisions.get",
          "httpMethod": "GET",
          "flatPath": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "path": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a specific revision."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PUT",
          "path": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "flatPath": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "description": "Updates a revision."
        },
        "list": {
          "path": "drive/v2/files/{fileId}/revisions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drive/v2/files/{fileId}/revisions",
          "description": "Lists a file's revisions.",
          "id": "drive.revisions.list",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "drive/v2/files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.delete"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "description": "Gets the information about the current user along with Drive API settings",
          "flatPath": "drive/v2/about",
          "path": "drive/v2/about",
          "id": "drive.about.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "flatPath": "drive/v2/channels/stop",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Stop watching resources through this channel.",
          "id": "drive.channels.stop",
          "path": "drive/v2/channels/stop"
        }
      }
    },
    "permissions": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.insert",
          "path": "drive/v2/files/{fileId}/permissions",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "POST",
          "flatPath": "drive/v2/files/{fileId}/permissions"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.patch",
          "flatPath": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "PATCH"
        },
        "getIdForEmail": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drive/v2/permissionIds/{email}",
          "flatPath": "drive/v2/permissionIds/{email}",
          "httpMethod": "GET",
          "id": "drive.permissions.getIdForEmail",
          "description": "Returns the permission ID for an email address."
        },
        "update": {
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PUT",
          "id": "drive.permissions.update",
          "path": "drive/v2/files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "id": "drive.permissions.get",
          "flatPath": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "description": "Gets a permission by ID."
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.permissions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "flatPath": "drive/v2/files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "list": {
          "id": "drive.permissions.list",
          "path": "drive/v2/files/{fileId}/permissions",
          "description": "Lists a file's or shared drive's permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "drive/v2/files/{fileId}/permissions"
        }
      }
    },
    "properties": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.patch",
          "flatPath": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "drive.properties.update",
          "flatPath": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "path": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property."
        },
        "get": {
          "httpMethod": "GET",
          "id": "drive.properties.get",
          "description": "Gets a property by its key.",
          "path": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "flatPath": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "flatPath": "drive/v2/files/{fileId}/properties",
          "id": "drive.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's properties.",
          "httpMethod": "GET",
          "path": "drive/v2/files/{fileId}/properties"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "POST",
          "path": "drive/v2/files/{fileId}/properties",
          "flatPath": "drive/v2/files/{fileId}/properties",
          "description": "Adds a property to a file, or updates it if it already exists.",
          "id": "drive.properties.insert"
        },
        "delete": {
          "path": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE",
          "flatPath": "drive/v2/files/{fileId}/properties/{propertyKey}",
          "description": "Deletes a property.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.delete"
        }
      }
    },
    "comments": {
      "methods": {
        "insert": {
          "id": "drive.comments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "drive/v2/files/{fileId}/comments",
          "description": "Creates a new comment on the given file.",
          "path": "drive/v2/files/{fileId}/comments",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "drive.comments.patch",
          "path": "drive/v2/files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "httpMethod": "PATCH",
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.update",
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}",
          "path": "drive/v2/files/{fileId}/comments/{commentId}",
          "httpMethod": "PUT"
        },
        "get": {
          "path": "drive/v2/files/{fileId}/comments/{commentId}",
          "httpMethod": "GET",
          "description": "Gets a comment by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.comments.get",
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "drive/v2/files/{fileId}/comments",
          "description": "Lists a file's comments.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drive/v2/files/{fileId}/comments",
          "id": "drive.comments.list"
        },
        "delete": {
          "flatPath": "drive/v2/files/{fileId}/comments/{commentId}",
          "path": "drive/v2/files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.delete",
          "description": "Deletes a comment.",
          "httpMethod": "DELETE"
        }
      }
    },
    "children": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "drive/v2/files/{folderId}/children",
          "flatPath": "drive/v2/files/{folderId}/children",
          "id": "drive.children.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a folder's children."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "drive/v2/files/{folderId}/children",
          "description": "Inserts a file into a folder.",
          "httpMethod": "POST",
          "path": "drive/v2/files/{folderId}/children",
          "id": "drive.children.insert"
        },
        "delete": {
          "flatPath": "drive/v2/files/{folderId}/children/{childId}",
          "path": "drive/v2/files/{folderId}/children/{childId}",
          "description": "Removes a child from a folder.",
          "id": "drive.children.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.get",
          "description": "Gets a specific child reference.",
          "flatPath": "drive/v2/files/{folderId}/children/{childId}",
          "path": "drive/v2/files/{folderId}/children/{childId}",
          "httpMethod": "GET"
        }
      }
    },
    "parents": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "drive.parents.list",
          "description": "Lists a file's parents.",
          "flatPath": "drive/v2/files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drive/v2/files/{fileId}/parents"
        },
        "get": {
          "description": "Gets a specific parent reference.",
          "httpMethod": "GET",
          "flatPath": "drive/v2/files/{fileId}/parents/{parentId}",
          "id": "drive.parents.get",
          "path": "drive/v2/files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "id": "drive.parents.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "flatPath": "drive/v2/files/{fileId}/parents/{parentId}",
          "path": "drive/v2/files/{fileId}/parents/{parentId}",
          "description": "Removes a parent from a file."
        },
        "insert": {
          "description": "Adds a parent folder for a file.",
          "httpMethod": "POST",
          "path": "drive/v2/files/{fileId}/parents",
          "flatPath": "drive/v2/files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.insert"
        }
      }
    },
    "changes": {
      "methods": {
        "watch": {
          "id": "drive.changes.watch",
          "path": "drive/v2/changes/watch",
          "supportsSubscription": true,
          "httpMethod": "POST",
          "flatPath": "drive/v2/changes/watch",
          "description": "Subscribe to changes for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "getStartPageToken": {
          "path": "drive/v2/changes/startPageToken",
          "description": "Gets the starting pageToken for listing future changes.",
          "id": "drive.changes.getStartPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "drive/v2/changes/startPageToken"
        },
        "list": {
          "httpMethod": "GET",
          "supportsSubscription": true,
          "flatPath": "drive/v2/changes",
          "id": "drive.changes.list",
          "path": "drive/v2/changes",
          "description": "Lists the changes for a user or shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "flatPath": "drive/v2/changes/{changeId}",
          "path": "drive/v2/changes/{changeId}",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "id": "drive.changes.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "flatPath": "drive/v2/apps/{appId}",
          "description": "Gets a specific app.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "drive/v2/apps/{appId}",
          "id": "drive.apps.get"
        },
        "list": {
          "id": "drive.apps.list",
          "path": "drive/v2/apps",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "flatPath": "drive/v2/apps",
          "description": "Lists a user's installed apps."
        }
      }
    },
    "files": {
      "methods": {
        "untrash": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may untrash a file.",
          "path": "drive/v2/files/{fileId}/untrash",
          "flatPath": "drive/v2/files/{fileId}/untrash",
          "id": "drive.files.untrash",
          "httpMethod": "POST"
        },
        "export": {
          "flatPath": "drive/v2/files/{fileId}/export",
          "useMediaDownloadService": true,
          "id": "drive.files.export",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "path": "drive/v2/files/{fileId}/export"
        },
        "get": {
          "supportsSubscription": true,
          "path": "drive/v2/files/{fileId}",
          "supportsMediaDownload": true,
          "flatPath": "drive/v2/files/{fileId}",
          "useMediaDownloadService": true,
          "id": "drive.files.get",
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v2/files/export) instead. For further information on downloading files, refer to [Download files](/drive/api/guides/manage-downloads).",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "id": "drive.files.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5120GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the [...]",
          "httpMethod": "PUT",
          "supportsMediaUpload": true,
          "flatPath": "drive/v2/files/{fileId}",
          "path": "drive/v2/files/{fileId}"
        },
        "watch": {
          "flatPath": "drive/v2/files/{fileId}/watch",
          "id": "drive.files.watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "supportsSubscription": true,
          "description": "Subscribes to changes to a file.",
          "path": "drive/v2/files/{fileId}/watch"
        },
        "generateIds": {
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "drive/v2/files/generateIds",
          "id": "drive.files.generateIds",
          "path": "drive/v2/files/generateIds"
        },
        "list": {
          "path": "drive/v2/files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.list",
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to filter trashed files from the results.",
          "httpMethod": "GET",
          "flatPath": "drive/v2/files"
        },
        "emptyTrash": {
          "path": "drive/v2/files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drive/v2/files/trash",
          "id": "drive.files.emptyTrash",
          "httpMethod": "DELETE",
          "description": "Permanently deletes all of the user's trashed files."
        },
        "touch": {
          "path": "drive/v2/files/{fileId}/touch",
          "description": "Set the file's updated time to the current server time.",
          "id": "drive.files.touch",
          "httpMethod": "POST",
          "flatPath": "drive/v2/files/{fileId}/touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Permanently deletes a file by ID. Skips the trash. The currently authenticated user must own the file or be an organizer on the parent for shared drive files.",
          "httpMethod": "DELETE",
          "flatPath": "drive/v2/files/{fileId}",
          "path": "drive/v2/files/{fileId}",
          "id": "drive.files.delete"
        },
        "modifyLabels": {
          "id": "drive.files.modifyLabels",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "drive/v2/files/{fileId}/modifyLabels",
          "flatPath": "drive/v2/files/{fileId}/modifyLabels",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified."
        },
        "patch": {
          "path": "drive/v2/files/{fileId}",
          "flatPath": "drive/v2/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "httpMethod": "PATCH",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "id": "drive.files.patch"
        },
        "copy": {
          "id": "drive.files.copy",
          "flatPath": "drive/v2/files/{fileId}/copy",
          "description": "Creates a copy of the specified file.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "path": "drive/v2/files/{fileId}/copy"
        },
        "listLabels": {
          "httpMethod": "GET",
          "id": "drive.files.listLabels",
          "path": "drive/v2/files/{fileId}/listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drive/v2/files/{fileId}/listLabels",
          "description": "Lists the labels on a file."
        },
        "insert": {
          "id": "drive.files.insert",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5120GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For further information on uploading files, refer to [Upload files](/drive/api/guides/manage-uploads). Apps creating shortcuts with[...]",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "path": "drive/v2/files",
          "flatPath": "drive/v2/files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "trash": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.trash",
          "path": "drive/v2/files/{fileId}/trash",
          "httpMethod": "POST",
          "flatPath": "drive/v2/files/{fileId}/trash",
          "description": " Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may trash a file. The trashed item is excluded from all `files.list` responses returned for any user who does not own the file. However, all users with access to the file can see the trashed item metadata in an API response. All users with access can copy, download, export, and share the file. *Note:* Files [...]"
        }
      }
    },
    "teamdrives": {
      "methods": {
        "update": {
          "flatPath": "drive/v2/teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "path": "drive/v2/teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.update` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "path": "drive/v2/teamdrives",
          "flatPath": "drive/v2/teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "description": "Deprecated: Use `drives.list` instead."
        },
        "delete": {
          "description": "Deprecated: Use `drives.delete` instead.",
          "id": "drive.teamdrives.delete",
          "flatPath": "drive/v2/teamdrives/{teamDriveId}",
          "path": "drive/v2/teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "id": "drive.teamdrives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drive/v2/teamdrives/{teamDriveId}",
          "httpMethod": "GET",
          "path": "drive/v2/teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead."
        },
        "insert": {
          "description": "Deprecated: Use `drives.insert` instead.",
          "path": "drive/v2/teamdrives",
          "httpMethod": "POST",
          "flatPath": "drive/v2/teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.insert"
        }
      }
    },
    "drives": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.insert",
          "description": "Creates a new shared drive.",
          "path": "drive/v2/drives",
          "flatPath": "drive/v2/drives",
          "httpMethod": "POST"
        },
        "hide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST",
          "id": "drive.drives.hide",
          "flatPath": "drive/v2/drives/{driveId}/hide",
          "path": "drive/v2/drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view."
        },
        "get": {
          "description": "Gets a shared drive's metadata by ID.",
          "flatPath": "drive/v2/drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.get",
          "path": "drive/v2/drives/{driveId}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "drive/v2/drives",
          "httpMethod": "GET",
          "id": "drive.drives.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drive/v2/drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide."
        },
        "delete": {
          "flatPath": "drive/v2/drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "DELETE",
          "path": "drive/v2/drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
          "id": "drive.drives.delete"
        },
        "unhide": {
          "path": "drive/v2/drives/{driveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST",
          "flatPath": "drive/v2/drives/{driveId}/unhide",
          "id": "drive.drives.unhide",
          "description": "Restores a shared drive to the default view."
        },
        "update": {
          "description": "Updates the metadata for a shared drive.",
          "id": "drive.drives.update",
          "path": "drive/v2/drives/{driveId}",
          "flatPath": "drive/v2/drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "PUT"
        }
      }
    }
  }
}
