{
  "kind": "discovery#restDescription",
  "name": "drive",
  "title": "Google Drive API",
  "servicePath": "drive/v3/",
  "id": "drive:v3",
  "discoveryVersion": "v1",
  "revision": "20230610",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "version": "v3",
  "baseUrl": "https://www.googleapis.com/drive/v3/",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "basePath": "/drive/v3/",
  "protocol": "rest",
  "batchPath": "batch/drive/v3",
  "resources": {
    "changes": {
      "methods": {
        "watch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "changes/watch",
          "flatPath": "changes/watch",
          "httpMethod": "POST",
          "id": "drive.changes.watch",
          "description": "Subscribes to changes for a user.",
          "supportsSubscription": true
        },
        "getStartPageToken": {
          "description": "Gets the starting pageToken for listing future changes.",
          "id": "drive.changes.getStartPageToken",
          "path": "changes/startPageToken",
          "flatPath": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "changes",
          "id": "drive.changes.list",
          "description": "Lists the changes for a user or shared drive.",
          "httpMethod": "GET",
          "supportsSubscription": true,
          "path": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "id": "drive.channels.stop",
          "flatPath": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "path": "channels/stop",
          "description": "Stops watching resources through this channel."
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "description": "Gets a reply by ID.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "path": "files/{fileId}/comments/{commentId}/replies",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists a comment's replies.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.list"
        },
        "create": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.create",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Creates a reply to a comment."
        },
        "delete": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes a reply.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a reply with patch semantics.",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "flatPath": "about",
          "description": "Gets information about the user, the user's Drive, and system capabilities.",
          "httpMethod": "GET",
          "id": "drive.about.get",
          "path": "about",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "id": "drive.files.get",
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v3/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).",
          "useMediaDownloadService": true,
          "flatPath": "files/{fileId}",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true,
          "path": "files/{fileId}"
        },
        "list": {
          "flatPath": "files",
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files",
          "id": "drive.files.list"
        },
        "copy": {
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "description": "Creates a copy of a file and applies any requested updates with patch semantics.",
          "flatPath": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "path": "files/{fileId}/copy"
        },
        "watch": {
          "supportsSubscription": true,
          "description": "Subscribes to changes to a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.watch",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/watch",
          "path": "files/{fileId}/watch"
        },
        "generateIds": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.generateIds",
          "path": "files/generateIds",
          "flatPath": "files/generateIds",
          "httpMethod": "GET",
          "description": "Generates a set of file IDs which can be provided in create or copy requests."
        },
        "modifyLabels": {
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "id": "drive.files.modifyLabels",
          "httpMethod": "POST",
          "path": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/modifyLabels"
        },
        "create": {
          "supportsMediaUpload": true,
          "flatPath": "files",
          "path": "files",
          "id": "drive.files.create",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": " Creates a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `[...]"
        },
        "export": {
          "path": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.export",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "useMediaDownloadService": true,
          "flatPath": "files/{fileId}/export",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB."
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "httpMethod": "GET",
          "description": "Lists the labels on a file."
        },
        "emptyTrash": {
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash",
          "httpMethod": "DELETE",
          "description": "Permanently deletes all of the user's trashed files.",
          "flatPath": "files/trash"
        },
        "delete": {
          "id": "drive.files.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.",
          "path": "files/{fileId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "httpMethod": "PATCH",
          "path": "files/{fileId}",
          "id": "drive.files.update",
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than th[...]",
          "flatPath": "files/{fileId}",
          "supportsMediaUpload": true
        }
      }
    },
    "comments": {
      "methods": {
        "create": {
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "description": "Creates a comment on a file.",
          "httpMethod": "POST",
          "id": "drive.comments.create",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "drive.comments.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a comment by ID.",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}"
        },
        "delete": {
          "id": "drive.comments.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a comment.",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "httpMethod": "GET",
          "id": "drive.comments.list",
          "description": "Lists a file's comments.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments"
        },
        "update": {
          "id": "drive.comments.update",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Updates a comment with patch semantics."
        }
      }
    },
    "permissions": {
      "methods": {
        "get": {
          "description": "Gets a permission by ID.",
          "id": "drive.permissions.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "list": {
          "description": "Lists a file's or shared drive's permissions.",
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.list",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.update",
          "description": "Updates a permission with patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "create": {
          "path": "files/{fileId}/permissions",
          "description": "Creates a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.create",
          "flatPath": "files/{fileId}/permissions",
          "httpMethod": "POST"
        }
      }
    },
    "revisions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/revisions",
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions",
          "description": "Lists a file's revisions.",
          "id": "drive.revisions.list"
        },
        "get": {
          "httpMethod": "GET",
          "useMediaDownloadService": true,
          "id": "drive.revisions.get",
          "path": "files/{fileId}/revisions/{revisionId}",
          "supportsMediaDownload": true,
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Gets a revision's metadata or content by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content in Google Drive, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "httpMethod": "PATCH",
          "description": "Updates a revision with patch semantics.",
          "path": "files/{fileId}/revisions/{revisionId}"
        }
      }
    },
    "drives": {
      "methods": {
        "update": {
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "description": "Updates the metadate for a shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "PATCH",
          "id": "drive.drives.update"
        },
        "unhide": {
          "description": "Restores a shared drive to the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.unhide",
          "flatPath": "drives/{driveId}/unhide",
          "httpMethod": "POST",
          "path": "drives/{driveId}/unhide"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
          "httpMethod": "DELETE"
        },
        "hide": {
          "flatPath": "drives/{driveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Hides a shared drive from the default view.",
          "path": "drives/{driveId}/hide",
          "httpMethod": "POST",
          "id": "drive.drives.hide"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a shared drive's metadata by ID.",
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.get",
          "path": "drives/{driveId}",
          "httpMethod": "GET"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.create",
          "description": "Creates a shared drive.",
          "path": "drives",
          "httpMethod": "POST",
          "flatPath": "drives"
        },
        "list": {
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide.",
          "path": "drives",
          "flatPath": "drives",
          "httpMethod": "GET",
          "id": "drive.drives.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead.",
          "httpMethod": "DELETE",
          "id": "drive.teamdrives.delete",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "list": {
          "description": "Deprecated: Use `drives.list` instead.",
          "httpMethod": "GET",
          "flatPath": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.teamdrives.list",
          "path": "teamdrives"
        },
        "update": {
          "description": "Deprecated: Use `drives.update` instead.",
          "id": "drive.teamdrives.update",
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Deprecated: Use `drives.create` instead.",
          "flatPath": "teamdrives",
          "path": "teamdrives",
          "id": "drive.teamdrives.create",
          "httpMethod": "POST"
        },
        "get": {
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "GET",
          "id": "drive.teamdrives.get",
          "flatPath": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `drives.get` instead."
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/drive/",
  "rootUrl": "https://www.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "ownerName": "Google"
}
