{
  "discoveryVersion": "v1",
  "batchPath": "batch/drive/v2",
  "protocol": "rest",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/drive/",
  "title": "Google Drive API",
  "version": "v2",
  "rootUrl": "https://www.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "ownerName": "Google",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "resources": {
    "properties": {
      "methods": {
        "get": {
          "description": "Gets a property by its key.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.get"
        },
        "delete": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes a property.",
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.delete"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.update",
          "httpMethod": "PUT",
          "description": "Updates a property."
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.patch",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "path": "files/{fileId}/properties/{propertyKey}"
        },
        "insert": {
          "description": "Adds a property to a file, or updates it if it already exists.",
          "httpMethod": "POST",
          "path": "files/{fileId}/properties",
          "id": "drive.properties.insert",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "list": {
          "description": "Lists a file's properties.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/properties",
          "id": "drive.properties.list",
          "path": "files/{fileId}/properties",
          "httpMethod": "GET"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "description": "Gets the information about the current user along with Drive API settings",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "about",
          "path": "about",
          "id": "drive.about.get"
        }
      }
    },
    "comments": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.list",
          "description": "Lists a file's comments.",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.delete",
          "description": "Deletes a comment.",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "patch": {
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.patch",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "PATCH"
        },
        "insert": {
          "id": "drive.comments.insert",
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": "Creates a new comment on the given file."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.update"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Gets a comment by ID.",
          "id": "drive.comments.get"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "description": "Stops watching resources through this channel.",
          "path": "channels/stop",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.channels.stop",
          "flatPath": "channels/stop"
        }
      }
    },
    "drives": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.delete",
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items."
        },
        "unhide": {
          "path": "drives/{driveId}/unhide",
          "description": "Restores a shared drive to the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.unhide",
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/unhide"
        },
        "list": {
          "flatPath": "drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide.",
          "id": "drive.drives.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drives"
        },
        "insert": {
          "path": "drives",
          "flatPath": "drives",
          "id": "drive.drives.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Creates a new shared drive."
        },
        "update": {
          "id": "drive.drives.update",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Updates the metadata for a shared drive.",
          "httpMethod": "PUT"
        },
        "hide": {
          "httpMethod": "POST",
          "id": "drive.drives.hide",
          "flatPath": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}/hide"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a shared drive's metadata by ID.",
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.get",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "changes": {
      "methods": {
        "watch": {
          "supportsSubscription": true,
          "description": "Subscribe to changes for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "id": "drive.changes.watch",
          "flatPath": "changes/watch",
          "path": "changes/watch"
        },
        "getStartPageToken": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the starting pageToken for listing future changes.",
          "httpMethod": "GET",
          "id": "drive.changes.getStartPageToken",
          "flatPath": "changes/startPageToken",
          "path": "changes/startPageToken"
        },
        "get": {
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "flatPath": "changes/{changeId}",
          "path": "changes/{changeId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.get",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists the changes for a user or shared drive.",
          "flatPath": "changes",
          "path": "changes",
          "id": "drive.changes.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true,
          "httpMethod": "GET"
        }
      }
    },
    "teamdrives": {
      "methods": {
        "insert": {
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.insert",
          "flatPath": "teamdrives"
        },
        "list": {
          "description": "Deprecated: Use `drives.list` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "path": "teamdrives",
          "flatPath": "teamdrives"
        },
        "get": {
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.teamdrives.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "description": "Deprecated: Use `drives.update` instead.",
          "httpMethod": "PUT",
          "path": "teamdrives/{teamDriveId}"
        },
        "delete": {
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "description": "Deprecated: Use `drives.delete` instead.",
          "id": "drive.teamdrives.delete",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "children": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Inserts a file into a folder.",
          "flatPath": "files/{folderId}/children",
          "path": "files/{folderId}/children",
          "httpMethod": "POST",
          "id": "drive.children.insert"
        },
        "delete": {
          "description": "Removes a child from a folder.",
          "path": "files/{folderId}/children/{childId}",
          "id": "drive.children.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{folderId}/children/{childId}"
        },
        "get": {
          "description": "Gets a specific child reference.",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{folderId}/children/{childId}",
          "httpMethod": "GET",
          "id": "drive.children.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lists a folder's children.",
          "path": "files/{folderId}/children",
          "id": "drive.children.list",
          "flatPath": "files/{folderId}/children"
        }
      }
    },
    "parents": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.parents.get",
          "path": "files/{fileId}/parents/{parentId}",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "description": "Gets a specific parent reference."
        },
        "insert": {
          "httpMethod": "POST",
          "id": "drive.parents.insert",
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "description": "Adds a parent folder for a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "description": "Removes a parent from a file.",
          "id": "drive.parents.delete",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "path": "files/{fileId}/parents/{parentId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "drive.parents.list",
          "flatPath": "files/{fileId}/parents",
          "description": "Lists a file's parents.",
          "path": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's revisions.",
          "id": "drive.revisions.list",
          "path": "files/{fileId}/revisions",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/revisions"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision.",
          "id": "drive.revisions.update"
        },
        "patch": {
          "description": "Updates a revision.",
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.get",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Gets a specific revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        }
      }
    },
    "permissions": {
      "methods": {
        "getIdForEmail": {
          "flatPath": "permissionIds/{email}",
          "id": "drive.permissions.getIdForEmail",
          "description": "Returns the permission ID for an email address.",
          "path": "permissionIds/{email}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "description": "Gets a permission by ID.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "GET",
          "id": "drive.permissions.get"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "path": "files/{fileId}/permissions",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.insert"
        },
        "list": {
          "id": "drive.permissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's or shared drive's permissions.",
          "httpMethod": "GET",
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "drive.permissions.patch",
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files",
          "httpMethod": "GET",
          "id": "drive.files.list",
          "flatPath": "files"
        },
        "trash": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": " Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may trash a file. The trashed item is excluded from all `files.list` responses returned for any user who doesn't own the file. However, all users with access to the file can see the trashed item metadata in an API response. All users with access can copy, download, export, and share the file. *Note:* Files m[...]",
          "id": "drive.files.trash",
          "path": "files/{fileId}/trash",
          "flatPath": "files/{fileId}/trash"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.delete",
          "description": "Permanently deletes a file by ID. Skips the trash. The currently authenticated user must own the file or be an organizer on the parent for shared drive files.",
          "path": "files/{fileId}",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}"
        },
        "update": {
          "supportsMediaUpload": true,
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than th[...]",
          "flatPath": "files/{fileId}",
          "id": "drive.files.update",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "httpMethod": "PUT"
        },
        "untrash": {
          "path": "files/{fileId}/untrash",
          "flatPath": "files/{fileId}/untrash",
          "httpMethod": "POST",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may untrash a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.untrash"
        },
        "get": {
          "useMediaDownloadService": true,
          "flatPath": "files/{fileId}",
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).",
          "supportsMediaDownload": true,
          "id": "drive.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files/{fileId}",
          "supportsSubscription": true
        },
        "copy": {
          "flatPath": "files/{fileId}/copy",
          "path": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file.",
          "id": "drive.files.copy"
        },
        "touch": {
          "id": "drive.files.touch",
          "description": "Set the file's updated time to the current server time.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "POST",
          "path": "files/{fileId}/touch",
          "flatPath": "files/{fileId}/touch"
        },
        "listLabels": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/listLabels",
          "path": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "description": "Lists the labels on a file."
        },
        "insert": {
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.insert",
          "flatPath": "files",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `[...]",
          "path": "files"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "httpMethod": "PATCH",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "path": "files/{fileId}",
          "id": "drive.files.patch",
          "flatPath": "files/{fileId}"
        },
        "emptyTrash": {
          "flatPath": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash",
          "path": "files/trash",
          "description": "Permanently deletes all of the user's trashed files.",
          "httpMethod": "DELETE"
        },
        "export": {
          "useMediaDownloadService": true,
          "path": "files/{fileId}/export",
          "id": "drive.files.export",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "flatPath": "files/{fileId}/export",
          "httpMethod": "GET"
        },
        "watch": {
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.watch",
          "path": "files/{fileId}/watch",
          "description": "Subscribes to changes to a file.",
          "supportsSubscription": true
        },
        "modifyLabels": {
          "flatPath": "files/{fileId}/modifyLabels",
          "path": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "POST",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified."
        },
        "generateIds": {
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/generateIds",
          "httpMethod": "GET",
          "id": "drive.files.generateIds",
          "flatPath": "files/generateIds"
        }
      }
    },
    "apps": {
      "methods": {
        "list": {
          "flatPath": "apps",
          "httpMethod": "GET",
          "description": "Lists a user's installed apps.",
          "id": "drive.apps.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "path": "apps"
        },
        "get": {
          "description": "Gets a specific app.",
          "flatPath": "apps/{appId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.apps.get",
          "path": "apps/{appId}"
        }
      }
    },
    "replies": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "httpMethod": "PUT",
          "id": "drive.replies.update",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Creates a new reply to the given comment.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.insert"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "id": "drive.replies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a reply."
        },
        "list": {
          "httpMethod": "GET",
          "id": "drive.replies.list",
          "description": "Lists all of the replies to a comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "id": "drive.replies.get",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Gets a reply.",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    }
  },
  "id": "drive:v2",
  "name": "drive",
  "ownerDomain": "google.com",
  "revision": "20230815",
  "basePath": "/drive/v2/",
  "servicePath": "drive/v2/"
}
