{
  "discoveryVersion": "v1",
  "resources": {
    "apps": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "path": "apps",
          "httpMethod": "GET",
          "id": "drive.apps.list",
          "flatPath": "apps",
          "description": "Lists a user's installed apps."
        },
        "get": {
          "httpMethod": "GET",
          "path": "apps/{appId}",
          "id": "drive.apps.get",
          "flatPath": "apps/{appId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a specific app."
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "description": "Stops watching resources through this channel.",
          "id": "drive.channels.stop",
          "httpMethod": "POST",
          "flatPath": "channels/stop",
          "path": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "list": {
          "path": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/properties",
          "description": "Lists a file's properties.",
          "id": "drive.properties.list"
        },
        "update": {
          "id": "drive.properties.update",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property.",
          "httpMethod": "PUT",
          "path": "files/{fileId}/properties/{propertyKey}"
        },
        "patch": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "PATCH",
          "description": "Updates a property.",
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.patch"
        },
        "insert": {
          "id": "drive.properties.insert",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/properties",
          "httpMethod": "POST",
          "description": "Adds a property to a file, or updates it if it already exists."
        },
        "get": {
          "id": "drive.properties.get",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a property by its key.",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "GET"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Deletes a property.",
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.delete"
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Deletes a comment.",
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing comment."
        },
        "insert": {
          "description": "Creates a new comment on the given file.",
          "id": "drive.comments.insert",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/comments",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "id": "drive.comments.update",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing comment."
        },
        "get": {
          "id": "drive.comments.get",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Gets a comment by ID."
        },
        "list": {
          "flatPath": "files/{fileId}/comments",
          "path": "files/{fileId}/comments",
          "httpMethod": "GET",
          "id": "drive.comments.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's comments."
        }
      }
    },
    "permissions": {
      "methods": {
        "patch": {
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.patch",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "description": "Gets a permission by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "getIdForEmail": {
          "id": "drive.permissions.getIdForEmail",
          "flatPath": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Returns the permission ID for an email address.",
          "httpMethod": "GET",
          "path": "permissionIds/{email}"
        },
        "delete": {
          "id": "drive.permissions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "DELETE"
        },
        "insert": {
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "POST",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PUT",
          "id": "drive.permissions.update",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "drive.permissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions",
          "description": "Lists a file's or shared drive's permissions."
        }
      }
    },
    "drives": {
      "methods": {
        "hide": {
          "path": "drives/{driveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "id": "drive.drives.hide"
        },
        "unhide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.unhide",
          "description": "Restores a shared drive to the default view.",
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/unhide",
          "path": "drives/{driveId}/unhide"
        },
        "insert": {
          "flatPath": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.insert",
          "path": "drives",
          "description": "Creates a new shared drive.",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
          "httpMethod": "DELETE",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.delete"
        },
        "get": {
          "description": "Gets a shared drive's metadata by ID.",
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.get",
          "httpMethod": "GET",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.update",
          "path": "drives/{driveId}",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Updates the metadata for a shared drive."
        },
        "list": {
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide.",
          "path": "drives",
          "flatPath": "drives",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.list"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the information about the current user along with Drive API settings",
          "id": "drive.about.get",
          "path": "about",
          "httpMethod": "GET",
          "flatPath": "about"
        }
      }
    },
    "revisions": {
      "methods": {
        "get": {
          "description": "Gets a specific revision.",
          "id": "drive.revisions.get",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.revisions.list",
          "description": "Lists a file's revisions.",
          "flatPath": "files/{fileId}/revisions",
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions"
        },
        "update": {
          "description": "Updates a revision.",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "PUT",
          "id": "drive.revisions.update",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "patch": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.patch",
          "httpMethod": "PATCH",
          "description": "Updates a revision."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.delete",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted."
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "path": "files",
          "id": "drive.files.list",
          "httpMethod": "GET",
          "flatPath": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "watch": {
          "id": "drive.files.watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Subscribes to changes to a file.",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/watch",
          "path": "files/{fileId}/watch",
          "supportsSubscription": true
        },
        "modifyLabels": {
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "path": "files/{fileId}/modifyLabels",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "untrash": {
          "httpMethod": "POST",
          "path": "files/{fileId}/untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/untrash",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may untrash a file.",
          "id": "drive.files.untrash"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `[...]",
          "supportsMediaUpload": true,
          "flatPath": "files",
          "id": "drive.files.insert"
        },
        "emptyTrash": {
          "description": "Permanently deletes all of the user's trashed files.",
          "flatPath": "files/trash",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash",
          "path": "files/trash"
        },
        "touch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/touch",
          "description": "Set the file's updated time to the current server time.",
          "id": "drive.files.touch",
          "path": "files/{fileId}/touch"
        },
        "export": {
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "flatPath": "files/{fileId}/export",
          "supportsMediaDownload": true,
          "id": "drive.files.export",
          "httpMethod": "GET",
          "path": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "useMediaDownloadService": true
        },
        "get": {
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true,
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).",
          "path": "files/{fileId}",
          "id": "drive.files.get",
          "useMediaDownloadService": true
        },
        "listLabels": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/listLabels",
          "description": "Lists the labels on a file.",
          "id": "drive.files.listLabels",
          "path": "files/{fileId}/listLabels"
        },
        "generateIds": {
          "id": "drive.files.generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "flatPath": "files/generateIds",
          "httpMethod": "GET",
          "path": "files/generateIds"
        },
        "copy": {
          "description": "Creates a copy of the specified file.",
          "path": "files/{fileId}/copy",
          "flatPath": "files/{fileId}/copy",
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ]
        },
        "trash": {
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/trash",
          "id": "drive.files.trash",
          "description": " Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files. Only the owner may trash a file. The trashed item is excluded from all `files.list` responses returned for any user who doesn't own the file. However, all users with access to the file can see the trashed item metadata in an API response. All users with access can copy, download, export, and share the file. *Note:* Files m[...]",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/trash"
        },
        "patch": {
          "path": "files/{fileId}",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "flatPath": "files/{fileId}",
          "id": "drive.files.patch"
        },
        "delete": {
          "description": "Permanently deletes a file by ID. Skips the trash. The currently authenticated user must own the file or be an organizer on the parent for shared drive files.",
          "flatPath": "files/{fileId}",
          "id": "drive.files.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}",
          "httpMethod": "DELETE"
        },
        "update": {
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than th[...]",
          "supportsMediaUpload": true,
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "id": "drive.files.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "insert": {
          "flatPath": "teamdrives",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.insert",
          "httpMethod": "POST"
        },
        "get": {
          "id": "drive.teamdrives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "description": "Deprecated: Use `drives.update` instead.",
          "flatPath": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "teamdrives",
          "id": "drive.teamdrives.list",
          "description": "Deprecated: Use `drives.list` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives"
        },
        "delete": {
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "DELETE",
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.delete"
        }
      }
    },
    "changes": {
      "methods": {
        "watch": {
          "id": "drive.changes.watch",
          "description": "Subscribe to changes for a user.",
          "httpMethod": "POST",
          "flatPath": "changes/watch",
          "supportsSubscription": true,
          "path": "changes/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "id": "drive.changes.list",
          "description": "Lists the changes for a user or shared drive.",
          "flatPath": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "changes",
          "httpMethod": "GET",
          "supportsSubscription": true
        },
        "get": {
          "id": "drive.changes.get",
          "flatPath": "changes/{changeId}",
          "path": "changes/{changeId}",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        },
        "getStartPageToken": {
          "path": "changes/startPageToken",
          "flatPath": "changes/startPageToken",
          "description": "Gets the starting pageToken for listing future changes.",
          "id": "drive.changes.getStartPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "parents": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "description": "Gets a specific parent reference.",
          "path": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/parents",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/parents",
          "id": "drive.parents.list",
          "description": "Lists a file's parents."
        },
        "insert": {
          "path": "files/{fileId}/parents",
          "description": "Adds a parent folder for a file.",
          "id": "drive.parents.insert",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST"
        },
        "delete": {
          "path": "files/{fileId}/parents/{parentId}",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "description": "Removes a parent from a file.",
          "id": "drive.parents.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.list",
          "description": "Lists all of the replies to a comment.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies"
        },
        "update": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PUT",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update"
        },
        "patch": {
          "description": "Updates an existing reply.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.patch"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "description": "Creates a new reply to the given comment.",
          "id": "drive.replies.insert",
          "httpMethod": "POST",
          "path": "files/{fileId}/comments/{commentId}/replies"
        },
        "delete": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete",
          "description": "Deletes a reply.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "children": {
      "methods": {
        "get": {
          "description": "Gets a specific child reference.",
          "path": "files/{folderId}/children/{childId}",
          "flatPath": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.get",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists a folder's children.",
          "httpMethod": "GET",
          "path": "files/{folderId}/children",
          "id": "drive.children.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{folderId}/children"
        },
        "delete": {
          "id": "drive.children.delete",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "description": "Removes a child from a folder.",
          "flatPath": "files/{folderId}/children/{childId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "files/{folderId}/children",
          "id": "drive.children.insert",
          "description": "Inserts a file into a folder.",
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    }
  },
  "protocol": "rest",
  "title": "Google Drive API",
  "name": "drive",
  "batchPath": "batch/drive/v2",
  "basePath": "/drive/v2/",
  "kind": "discovery#restDescription",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "version": "v2",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        }
      }
    }
  },
  "id": "drive:v2",
  "ownerName": "Google",
  "servicePath": "drive/v2/",
  "revision": "20230517",
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "documentationLink": "https://developers.google.com/drive/"
}
