{
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "batchPath": "batch/drive/v3",
  "protocol": "rest",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "baseUrl": "https://www.googleapis.com/drive/v3/",
  "basePath": "/drive/v3/",
  "name": "drive",
  "servicePath": "drive/v3/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        }
      }
    }
  },
  "revision": "20230517",
  "version": "v3",
  "ownerName": "Google",
  "rootUrl": "https://www.googleapis.com/",
  "id": "drive:v3",
  "documentationLink": "https://developers.google.com/drive/",
  "title": "Google Drive API",
  "resources": {
    "drives": {
      "methods": {
        "unhide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}/unhide",
          "description": "Restores a shared drive to the default view.",
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/unhide",
          "id": "drive.drives.unhide"
        },
        "get": {
          "description": "Gets a shared drive's metadata by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drives/{driveId}",
          "id": "drive.drives.get",
          "httpMethod": "GET",
          "flatPath": "drives/{driveId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives",
          "httpMethod": "GET",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/drive/api/guides/search-shareddrives) guide.",
          "id": "drive.drives.list",
          "path": "drives"
        },
        "create": {
          "id": "drive.drives.create",
          "flatPath": "drives",
          "path": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Creates a shared drive.",
          "httpMethod": "POST"
        },
        "update": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.update",
          "path": "drives/{driveId}",
          "description": "Updates the metadate for a shared drive."
        },
        "hide": {
          "description": "Hides a shared drive from the default view.",
          "flatPath": "drives/{driveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST",
          "path": "drives/{driveId}/hide",
          "id": "drive.drives.hide"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
          "flatPath": "drives/{driveId}"
        }
      }
    },
    "files": {
      "methods": {
        "generateIds": {
          "id": "drive.files.generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/generateIds",
          "httpMethod": "GET",
          "description": "Generates a set of file IDs which can be provided in create or copy requests.",
          "path": "files/generateIds"
        },
        "emptyTrash": {
          "httpMethod": "DELETE",
          "path": "files/trash",
          "description": "Permanently deletes all of the user's trashed files.",
          "id": "drive.files.emptyTrash",
          "flatPath": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "flatPath": "files/{fileId}",
          "supportsSubscription": true,
          "id": "drive.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "useMediaDownloadService": true,
          "path": "files/{fileId}",
          "supportsMediaDownload": true,
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/drive/api/reference/rest/v3/files/export) instead. For more information, see [Download & export files](/drive/api/guides/manage-downloads).",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "files/{fileId}",
          "id": "drive.files.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.",
          "flatPath": "files/{fileId}",
          "httpMethod": "DELETE"
        },
        "watch": {
          "httpMethod": "POST",
          "id": "drive.files.watch",
          "supportsSubscription": true,
          "description": "Subscribes to changes to a file.",
          "path": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/watch"
        },
        "modifyLabels": {
          "path": "files/{fileId}/modifyLabels",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.files.modifyLabels"
        },
        "listLabels": {
          "id": "drive.files.listLabels",
          "description": "Lists the labels on a file.",
          "flatPath": "files/{fileId}/listLabels",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/listLabels"
        },
        "list": {
          "id": "drive.files.list",
          "description": " Lists the user's files. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for files & folders](/drive/api/guides/search-files) guide. *Note:* This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "path": "files",
          "flatPath": "files",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "flatPath": "files/{fileId}",
          "httpMethod": "PATCH",
          "description": " Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than th[...]",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "id": "drive.files.update",
          "supportsMediaUpload": true,
          "path": "files/{fileId}"
        },
        "export": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.files.export",
          "useMediaDownloadService": true,
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "supportsMediaDownload": true,
          "path": "files/{fileId}/export",
          "flatPath": "files/{fileId}/export"
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": " Creates a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/drive/api/guides/manage-uploads). Apps creating shortcuts with `[...]",
          "path": "files",
          "supportsMediaUpload": true,
          "flatPath": "files",
          "id": "drive.files.create"
        },
        "copy": {
          "description": "Creates a copy of a file and applies any requested updates with patch semantics.",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/copy",
          "id": "drive.files.copy",
          "path": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ]
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "description": "Gets information about the user, the user's Drive, and system capabilities.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "about",
          "flatPath": "about",
          "id": "drive.about.get",
          "httpMethod": "GET"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "flatPath": "channels/stop",
          "description": "Stops watching resources through this channel.",
          "path": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "id": "drive.channels.stop"
        }
      }
    },
    "replies": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete",
          "httpMethod": "DELETE"
        },
        "create": {
          "description": "Creates a reply to a comment.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.create",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.update",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "PATCH",
          "description": "Updates a reply with patch semantics."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists a comment's replies.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.list",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "path": "files/{fileId}/comments/{commentId}/replies"
        },
        "get": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.get",
          "httpMethod": "GET",
          "description": "Gets a reply by ID."
        }
      }
    },
    "teamdrives": {
      "methods": {
        "delete": {
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.delete",
          "description": "Deprecated: Use `drives.delete` instead.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST",
          "description": "Deprecated: Use `drives.create` instead.",
          "id": "drive.teamdrives.create",
          "flatPath": "teamdrives",
          "path": "teamdrives"
        },
        "list": {
          "description": "Deprecated: Use `drives.list` instead.",
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "teamdrives"
        },
        "get": {
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.teamdrives.get",
          "description": "Deprecated: Use `drives.get` instead."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "httpMethod": "PATCH",
          "description": "Deprecated: Use `drives.update` instead."
        }
      }
    },
    "permissions": {
      "methods": {
        "get": {
          "id": "drive.permissions.get",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Gets a permission by ID.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PATCH",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.update",
          "description": "Updates a permission with patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "id": "drive.permissions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "DELETE",
          "description": "Deletes a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "id": "drive.permissions.create",
          "flatPath": "files/{fileId}/permissions",
          "path": "files/{fileId}/permissions",
          "description": "Creates a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists a file's or shared drive's permissions.",
          "id": "drive.permissions.list",
          "flatPath": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions"
        }
      }
    },
    "changes": {
      "methods": {
        "getStartPageToken": {
          "httpMethod": "GET",
          "id": "drive.changes.getStartPageToken",
          "path": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the starting pageToken for listing future changes.",
          "flatPath": "changes/startPageToken"
        },
        "watch": {
          "flatPath": "changes/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.watch",
          "httpMethod": "POST",
          "description": "Subscribes to changes for a user.",
          "supportsSubscription": true,
          "path": "changes/watch"
        },
        "list": {
          "path": "changes",
          "id": "drive.changes.list",
          "flatPath": "changes",
          "description": "Lists the changes for a user or shared drive.",
          "supportsSubscription": true,
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "description": "Deletes a comment.",
          "id": "drive.comments.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists a file's comments.",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.comments.list",
          "flatPath": "files/{fileId}/comments"
        },
        "update": {
          "id": "drive.comments.update",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a comment with patch semantics."
        },
        "get": {
          "id": "drive.comments.get",
          "description": "Gets a comment by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "httpMethod": "GET"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "id": "drive.comments.create",
          "description": "Creates a comment on a file.",
          "flatPath": "files/{fileId}/comments",
          "path": "files/{fileId}/comments"
        }
      }
    },
    "revisions": {
      "methods": {
        "list": {
          "id": "drive.revisions.list",
          "path": "files/{fileId}/revisions",
          "flatPath": "files/{fileId}/revisions",
          "description": "Lists a file's revisions.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "PATCH",
          "id": "drive.revisions.update",
          "description": "Updates a revision with patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "useMediaDownloadService": true,
          "id": "drive.revisions.get",
          "description": "Gets a revision's metadata or content by ID.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        },
        "delete": {
          "id": "drive.revisions.delete",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content in Google Drive, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        }
      }
    }
  }
}
