{
  "revision": "20220908",
  "ownerName": "Google",
  "description": "Reads and writes Google Forms and responses.",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "canonicalName": "Forms",
  "batchPath": "batch",
  "name": "forms",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/forms/api",
  "kind": "discovery#restDescription",
  "rootUrl": "https://forms.googleapis.com/",
  "discoveryVersion": "v1",
  "basePath": "",
  "id": "forms:v1",
  "baseUrl": "https://forms.googleapis.com/",
  "title": "Google Forms API",
  "servicePath": "",
  "version": "v1",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/forms.responses.readonly": {
          "description": "See all responses to your Google Forms forms"
        },
        "https://www.googleapis.com/auth/forms.body": {
          "description": "See, edit, create, and delete all your Google Forms forms"
        },
        "https://www.googleapis.com/auth/forms.body.readonly": {
          "description": "See all your Google Forms forms"
        }
      }
    }
  },
  "mtlsRootUrl": "https://forms.mtls.googleapis.com/",
  "resources": {
    "forms": {
      "resources": {
        "responses": {
          "methods": {
            "list": {
              "flatPath": "v1/forms/{formId}/responses",
              "httpMethod": "GET",
              "id": "forms.forms.responses.list",
              "path": "v1/forms/{formId}/responses",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/forms.responses.readonly"
              ],
              "description": "List a form's responses."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/forms.responses.readonly"
              ],
              "description": "Get one response from the form.",
              "httpMethod": "GET",
              "path": "v1/forms/{formId}/responses/{responseId}",
              "flatPath": "v1/forms/{formId}/responses/{responseId}",
              "id": "forms.forms.responses.get"
            }
          }
        },
        "watches": {
          "methods": {
            "delete": {
              "id": "forms.forms.watches.delete",
              "path": "v1/forms/{formId}/watches/{watchId}",
              "description": "Delete a watch.",
              "httpMethod": "DELETE",
              "flatPath": "v1/forms/{formId}/watches/{watchId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/forms.body",
                "https://www.googleapis.com/auth/forms.body.readonly",
                "https://www.googleapis.com/auth/forms.responses.readonly"
              ]
            },
            "list": {
              "id": "forms.forms.watches.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/forms.body",
                "https://www.googleapis.com/auth/forms.body.readonly",
                "https://www.googleapis.com/auth/forms.responses.readonly"
              ],
              "flatPath": "v1/forms/{formId}/watches",
              "path": "v1/forms/{formId}/watches",
              "description": "Return a list of the watches owned by the invoking project. The maximum number of watches is two: For each invoker, the limit is one for each event type per form."
            },
            "renew": {
              "description": "Renew an existing watch for seven days. The state of the watch after renewal is `ACTIVE`, and the `expire_time` is seven days from the renewal. Renewing a watch in an error state (e.g. `SUSPENDED`) succeeds if the error is no longer present, but fail otherwise. After a watch has expired, RenewWatch returns `NOT_FOUND`.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/forms.body",
                "https://www.googleapis.com/auth/forms.body.readonly",
                "https://www.googleapis.com/auth/forms.responses.readonly"
              ],
              "flatPath": "v1/forms/{formId}/watches/{watchId}:renew",
              "path": "v1/forms/{formId}/watches/{watchId}:renew",
              "id": "forms.forms.watches.renew"
            },
            "create": {
              "description": "Create a new watch. If a watch ID is provided, it must be unused. For each invoking project, the per form limit is one watch per Watch.EventType. A watch expires seven days after it is created (see Watch.expire_time).",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/forms.body",
                "https://www.googleapis.com/auth/forms.body.readonly",
                "https://www.googleapis.com/auth/forms.responses.readonly"
              ],
              "flatPath": "v1/forms/{formId}/watches",
              "httpMethod": "POST",
              "path": "v1/forms/{formId}/watches",
              "id": "forms.forms.watches.create"
            }
          }
        }
      },
      "methods": {
        "batchUpdate": {
          "id": "forms.forms.batchUpdate",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/forms.body"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/forms/{formId}:batchUpdate",
          "description": "Change the form with a batch of updates.",
          "path": "v1/forms/{formId}:batchUpdate"
        },
        "create": {
          "flatPath": "v1/forms",
          "httpMethod": "POST",
          "description": "Create a new form using the title given in the provided form message in the request. *Important:* Only the form.info.title and form.info.document_title fields are copied to the new form. All other fields including the form description, items and settings are disallowed. To create a new form and add items, you must first call forms.create to create an empty form with a title and (optional) document title, and then call forms.update to add the items.",
          "path": "v1/forms",
          "id": "forms.forms.create",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/forms.body"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/forms.body",
            "https://www.googleapis.com/auth/forms.body.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/forms/{formId}",
          "path": "v1/forms/{formId}",
          "description": "Get a form.",
          "id": "forms.forms.get"
        }
      }
    }
  }
}
