{
  "title": "Google Play Game Services",
  "kind": "discovery#restDescription",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "version": "v1",
  "revision": "20220317",
  "servicePath": "",
  "documentationLink": "https://developers.google.com/games/",
  "name": "games",
  "id": "games:v1",
  "discoveryVersion": "v1",
  "rootUrl": "https://games.googleapis.com/",
  "resources": {
    "achievements": {
      "methods": {
        "reveal": {
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "id": "games.achievements.unlock",
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "flatPath": "games/v1/players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.list",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET"
        },
        "setStepsAtLeast": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "httpMethod": "POST",
          "id": "games.achievements.setStepsAtLeast"
        },
        "updateMultiple": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/updateMultiple",
          "path": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Updates multiple achievements for the currently authenticated player."
        },
        "increment": {
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.increment",
          "path": "games/v1/achievements/{achievementId}/increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/eventDefinitions",
          "flatPath": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application."
        },
        "listByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "path": "games/v1/events",
          "id": "games.events.listByPlayer",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "httpMethod": "GET"
        },
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "id": "games.events.record",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application."
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "flatPath": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "path": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.players.list"
        },
        "get": {
          "flatPath": "games/v1/players/{playerId}",
          "id": "games.players.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "games.leaderboards.get",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        },
        "list": {
          "id": "games.leaderboards.list",
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET",
          "path": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists all the achievement definitions for your application.",
          "flatPath": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements",
          "id": "games.achievementDefinitions.list"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "flatPath": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "path": "games/v1/stats",
          "id": "games.stats.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "scores": {
      "methods": {
        "listWindow": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "id": "games.scores.listWindow",
          "httpMethod": "GET",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "submitMultiple": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/scores",
          "flatPath": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "httpMethod": "POST",
          "id": "games.scores.submitMultiple"
        },
        "get": {
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "id": "games.scores.get",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "httpMethod": "GET",
          "id": "games.scores.list"
        },
        "submit": {
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores"
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.listCategoriesByPlayer"
        },
        "getMetagameConfig": {
          "path": "games/v1/metagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "id": "games.metagame.getMetagameConfig"
        }
      }
    },
    "applications": {
      "methods": {
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "id": "games.applications.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}",
          "path": "games/v1/applications/{applicationId}"
        },
        "played": {
          "id": "games.applications.played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "flatPath": "games/v1/applications/played",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/played"
        },
        "verify": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "httpMethod": "GET",
          "path": "games/v1/applications/{applicationId}/verify",
          "id": "games.applications.verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for."
        },
        "getEndPoint": {
          "description": "Returns a URL for the requested end point type.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "flatPath": "games/v1/applications/getEndPoint",
          "id": "games.applications.getEndPoint"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Checks whether the games client is out of date.",
          "httpMethod": "GET",
          "flatPath": "games/v1/revisions/check",
          "path": "games/v1/revisions/check",
          "id": "games.revisions.check"
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "id": "games.snapshots.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/snapshots/{snapshotId}",
          "httpMethod": "GET",
          "id": "games.snapshots.get",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "flatPath": "games/v1/snapshots/{snapshotId}"
        }
      }
    }
  },
  "canonicalName": "Games",
  "ownerName": "Google",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "baseUrl": "https://games.googleapis.com/",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "basePath": ""
}
