{
  "description": "The Google Play games service allows developers to enhance games with social leaderboards,\n    achievements, game state, sign-in with Google, and more.",
  "baseUrl": "https://www.googleapis.com/",
  "id": "games:v1",
  "batchPath": "batch/games/v1",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/games/",
  "canonicalName": "Games",
  "version": "v1",
  "name": "games",
  "ownerName": "Google",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        }
      }
    }
  },
  "revision": "20200625",
  "basePath": "",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "title": "Google Play Game Services",
  "resources": {
    "revisions": {
      "methods": {
        "check": {
          "flatPath": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/revisions/check",
          "id": "games.revisions.check",
          "httpMethod": "GET"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "id": "games.stats.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns engagement and spend statistics in this application for the\ncurrently authenticated user.",
          "httpMethod": "GET",
          "flatPath": "games/v1/stats",
          "path": "games/v1/stats"
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "description": "Returns a list of the event definitions in this application.",
          "flatPath": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "path": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.listDefinitions"
        },
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "description": "Records a batch of changes to the number of times events have occurred for\nthe currently authenticated user of this application.",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "id": "games.events.record"
        },
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "httpMethod": "GET",
          "path": "games/v1/events",
          "description": "Returns a list showing the current progress on events in this application\nfor the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events"
        }
      }
    },
    "achievements": {
      "methods": {
        "setStepsAtLeast": {
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an\nachievement. If the steps parameter is less than the current number of\nsteps that the player already gained for the achievement, the achievement\nis not modified.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "id": "games.achievements.setStepsAtLeast"
        },
        "reveal": {
          "id": "games.achievements.reveal",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "description": "Sets the state of the achievement with the given ID to\n`REVEALED` for the currently authenticated player."
        },
        "updateMultiple": {
          "httpMethod": "POST",
          "path": "games/v1/achievements/updateMultiple",
          "flatPath": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Updates multiple achievements for the currently authenticated player.",
          "id": "games.achievements.updateMultiple"
        },
        "unlock": {
          "id": "games.achievements.unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "increment": {
          "description": "Increments the steps of the achievement with the given ID for the currently\nauthenticated player.",
          "path": "games/v1/achievements/{achievementId}/increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.increment"
        },
        "list": {
          "description": "Lists the progress for all your application's achievements for the\ncurrently authenticated player.",
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.list",
          "flatPath": "games/v1/players/{playerId}/achievements"
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "path": "games/v1/metagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "id": "games.metagame.getMetagameConfig",
          "httpMethod": "GET",
          "flatPath": "games/v1/metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listCategoriesByPlayer": {
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to\n`playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "id": "games.metagame.listCategoriesByPlayer",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/snapshots/{snapshotId}",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "id": "games.snapshots.get",
          "httpMethod": "GET",
          "description": "Retrieves the metadata for a given snapshot ID."
        },
        "list": {
          "id": "games.snapshots.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "description": "Retrieves a list of snapshots created by your application for the player\ncorresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "flatPath": "games/v1/players/me/players/{collection}",
          "httpMethod": "GET",
          "path": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "id": "games.players.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.players.get",
          "flatPath": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID.  To retrieve the player\nfor the currently authenticated user, set `playerId` to `me`.",
          "path": "games/v1/players/{playerId}"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "description": "Lists all the achievement definitions for your application.",
          "flatPath": "games/v1/achievements",
          "id": "games.achievementDefinitions.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/achievements"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "id": "games.leaderboards.list"
        },
        "get": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "id": "games.leaderboards.get",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently\nauthenticated player.  For a specific time span, `leaderboardId`\ncan be set to `ALL` to retrieve data for all leaderboards in a\ngiven time span.  `NOTE: You cannot ask for 'ALL' leaderboards and\n'ALL' timeSpans in the same request; only one parameter may be set to\n'ALL'.",
          "httpMethod": "GET",
          "id": "games.scores.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}"
        },
        "listWindow": {
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.listWindow",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "id": "games.scores.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET"
        },
        "submitMultiple": {
          "flatPath": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "id": "games.scores.submitMultiple",
          "httpMethod": "POST"
        },
        "submit": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "id": "games.scores.submit",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard."
        }
      }
    },
    "applications": {
      "methods": {
        "verify": {
          "description": "Verifies the auth token provided with this request is for the application\nwith the specified ID, and returns the ID of the player it was granted for.",
          "id": "games.applications.verify",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/{applicationId}/verify"
        },
        "played": {
          "description": "Indicate that the currently authenticated user is playing your\napplication.",
          "path": "games/v1/applications/played",
          "httpMethod": "POST",
          "flatPath": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.played"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.applications.get",
          "description": "Retrieves the metadata of the application with the given ID. If the\nrequested application is not available for the specified\n`platformType`, the returned response will not include any\ninstance data.",
          "path": "games/v1/applications/{applicationId}",
          "flatPath": "games/v1/applications/{applicationId}"
        }
      }
    }
  },
  "servicePath": ""
}
