{
  "ownerDomain": "google.com",
  "revision": "20201015",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "canonicalName": "Games",
  "documentationLink": "https://developers.google.com/games/",
  "name": "games",
  "version": "v1",
  "ownerName": "Google",
  "baseUrl": "https://games.googleapis.com/",
  "servicePath": "",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "resources": {
    "applications": {
      "methods": {
        "played": {
          "httpMethod": "POST",
          "flatPath": "games/v1/applications/played",
          "path": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.played",
          "description": "Indicate that the currently authenticated user is playing your application."
        },
        "verify": {
          "path": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.verify",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}",
          "id": "games.applications.get",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "httpMethod": "GET",
          "path": "games/v1/applications/{applicationId}"
        }
      }
    },
    "snapshotsExtended": {
      "methods": {
        "resolveSnapshotHead": {
          "path": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "description": "Resolves any potential conflicts according to the resolution policy specified in the request and returns the snapshot head after the resolution.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "httpMethod": "POST",
          "id": "games.snapshotsExtended.resolveSnapshotHead"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "path": "games/v1/achievements",
          "flatPath": "games/v1/achievements",
          "httpMethod": "GET",
          "description": "Lists all the achievement definitions for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievementDefinitions.list"
        }
      }
    },
    "scores": {
      "methods": {
        "submit": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "id": "games.scores.submit",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard."
        },
        "list": {
          "id": "games.scores.list",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}"
        },
        "listWindow": {
          "id": "games.scores.listWindow",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.get",
          "httpMethod": "GET"
        },
        "submitMultiple": {
          "id": "games.scores.submitMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "httpMethod": "POST",
          "path": "games/v1/leaderboards/scores"
        }
      }
    },
    "achievements": {
      "methods": {
        "list": {
          "flatPath": "games/v1/players/{playerId}/achievements",
          "id": "games.achievements.list",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET"
        },
        "updateMultiple": {
          "flatPath": "games/v1/achievements/updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "httpMethod": "POST"
        },
        "unlock": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/unlock",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock"
        },
        "increment": {
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "id": "games.achievements.increment"
        },
        "setStepsAtLeast": {
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "id": "games.achievements.setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "reveal": {
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal"
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/eventDefinitions",
          "path": "games/v1/eventDefinitions"
        },
        "listByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/events",
          "httpMethod": "GET",
          "id": "games.events.listByPlayer",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "flatPath": "games/v1/events"
        },
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.record",
          "httpMethod": "POST",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application."
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "id": "games.metagame.listCategoriesByPlayer",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "getMetagameConfig": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/metagameConfig",
          "flatPath": "games/v1/metagameConfig",
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "httpMethod": "GET"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "id": "games.stats.get"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "path": "games/v1/revisions/check",
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Checks whether the games client is out of date."
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/snapshots",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list"
        },
        "get": {
          "id": "games.snapshots.get",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "path": "games/v1/snapshots/{snapshotId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/snapshots/{snapshotId}"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards",
          "flatPath": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.get"
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "id": "games.players.get",
          "flatPath": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}"
        },
        "list": {
          "flatPath": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "path": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.list",
          "httpMethod": "GET"
        }
      }
    }
  },
  "basePath": "",
  "protocol": "rest",
  "rootUrl": "https://games.googleapis.com/",
  "title": "Google Play Game Services",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "batchPath": "batch",
  "id": "games:v1"
}
