{
  "title": "Google Play Game Services",
  "ownerName": "Google",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "id": "games:v1",
  "rootUrl": "https://games.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "resources": {
    "stats": {
      "methods": {
        "get": {
          "id": "games.stats.get",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/stats",
          "path": "games/v1/stats"
        }
      }
    },
    "applications": {
      "methods": {
        "verify": {
          "httpMethod": "GET",
          "id": "games.applications.verify",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "path": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "played": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "path": "games/v1/applications/played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "id": "games.applications.played",
          "flatPath": "games/v1/applications/played"
        },
        "getEndPoint": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "description": "Returns a URL for the requested end point type.",
          "flatPath": "games/v1/applications/getEndPoint"
        },
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "httpMethod": "GET",
          "id": "games.applications.get",
          "flatPath": "games/v1/applications/{applicationId}",
          "path": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.get",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        },
        "list": {
          "id": "games.leaderboards.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the leaderboard metadata for your application.",
          "flatPath": "games/v1/leaderboards",
          "path": "games/v1/leaderboards",
          "httpMethod": "GET"
        }
      }
    },
    "achievements": {
      "methods": {
        "unlock": {
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock"
        },
        "reveal": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "id": "games.achievements.reveal",
          "httpMethod": "POST"
        },
        "increment": {
          "id": "games.achievements.increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "path": "games/v1/achievements/{achievementId}/increment"
        },
        "setStepsAtLeast": {
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "id": "games.achievements.setStepsAtLeast",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified."
        },
        "updateMultiple": {
          "description": "Updates multiple achievements for the currently authenticated player.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple"
        },
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "id": "games.achievements.list"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "id": "games.revisions.check",
          "description": "Checks whether the games client is out of date.",
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/revisions/check"
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.record",
          "path": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "httpMethod": "POST",
          "flatPath": "games/v1/events"
        },
        "listByPlayer": {
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "id": "games.events.listByPlayer",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "httpMethod": "GET"
        },
        "listDefinitions": {
          "httpMethod": "GET",
          "path": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.listDefinitions",
          "flatPath": "games/v1/eventDefinitions"
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.listCategoriesByPlayer"
        },
        "getMetagameConfig": {
          "path": "games/v1/metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "flatPath": "games/v1/metagameConfig",
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application."
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "id": "games.players.list",
          "httpMethod": "GET",
          "path": "games/v1/players/me/players/{collection}"
        },
        "getMultipleApplicationPlayerIds": {
          "id": "games.players.getMultipleApplicationPlayerIds",
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "httpMethod": "GET",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game."
        },
        "get": {
          "flatPath": "games/v1/players/{playerId}",
          "id": "games.players.get",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}",
          "httpMethod": "GET"
        },
        "getScopedPlayerIds": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/scopedIds",
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "id": "games.players.getScopedPlayerIds",
          "httpMethod": "GET",
          "path": "games/v1/players/me/scopedIds"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "flatPath": "games/v1/achievements",
          "description": "Lists all the achievement definitions for your application.",
          "id": "games.achievementDefinitions.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/achievements"
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "games.snapshots.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the metadata for a given snapshot ID.",
          "path": "games/v1/snapshots/{snapshotId}",
          "flatPath": "games/v1/snapshots/{snapshotId}"
        },
        "list": {
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "scores": {
      "methods": {
        "listWindow": {
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "id": "games.scores.listWindow",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.get",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}"
        },
        "list": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET",
          "id": "games.scores.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top."
        },
        "submit": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "id": "games.scores.submit",
          "description": "Submits a score to the specified leaderboard.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submitMultiple": {
          "id": "games.scores.submitMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "path": "games/v1/leaderboards/scores",
          "flatPath": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards."
        }
      }
    }
  },
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "revision": "20230712",
  "documentationLink": "https://developers.google.com/games/",
  "basePath": "",
  "version": "v1",
  "name": "games",
  "servicePath": "",
  "canonicalName": "Games",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "baseUrl": "https://games.googleapis.com/"
}
