{
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "id": "games:v1",
  "name": "games",
  "ownerDomain": "google.com",
  "title": "Google Play Game Services",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "ownerName": "Google",
  "batchPath": "batch",
  "resources": {
    "snapshots": {
      "methods": {
        "list": {
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.snapshots.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots"
        },
        "get": {
          "description": "Retrieves the metadata for a given snapshot ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "path": "games/v1/snapshots/{snapshotId}",
          "id": "games.snapshots.get",
          "httpMethod": "GET"
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "flatPath": "games/v1/metagameConfig",
          "path": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application."
        },
        "listCategoriesByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "httpMethod": "GET",
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "games/v1/players/{playerId}/categories/{collection}"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.leaderboards.list",
          "description": "Lists all the leaderboard metadata for your application.",
          "flatPath": "games/v1/leaderboards",
          "path": "games/v1/leaderboards"
        },
        "get": {
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}"
        }
      }
    },
    "applications": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.get",
          "flatPath": "games/v1/applications/{applicationId}",
          "path": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data."
        },
        "getEndPoint": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/getEndPoint",
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "description": "Returns a URL for the requested end point type."
        },
        "played": {
          "id": "games.applications.played",
          "path": "games/v1/applications/played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "flatPath": "games/v1/applications/played",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "verify": {
          "path": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "id": "games.applications.verify"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "flatPath": "games/v1/achievements",
          "path": "games/v1/achievements",
          "id": "games.achievementDefinitions.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the achievement definitions for your application.",
          "httpMethod": "GET"
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "flatPath": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "path": "games/v1/players/{playerId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.players.get"
        },
        "list": {
          "flatPath": "games/v1/players/me/players/{collection}",
          "httpMethod": "GET",
          "id": "games.players.list",
          "path": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "httpMethod": "POST",
          "id": "games.events.record",
          "flatPath": "games/v1/events"
        },
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/events",
          "flatPath": "games/v1/events"
        },
        "listDefinitions": {
          "flatPath": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "id": "games.events.listDefinitions",
          "description": "Returns a list of the event definitions in this application."
        }
      }
    },
    "achievements": {
      "methods": {
        "increment": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "id": "games.achievements.increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/increment"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/achievements",
          "id": "games.achievements.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player."
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.unlock",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST"
        },
        "setStepsAtLeast": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "id": "games.achievements.setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "updateMultiple": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple"
        },
        "reveal": {
          "httpMethod": "POST",
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "path": "games/v1/stats",
          "httpMethod": "GET",
          "flatPath": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "id": "games.stats.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "path": "games/v1/revisions/check",
          "id": "games.revisions.check",
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Checks whether the games client is out of date.",
          "httpMethod": "GET"
        }
      }
    },
    "scores": {
      "methods": {
        "list": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard, starting from the top."
        },
        "listWindow": {
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "id": "games.scores.listWindow",
          "httpMethod": "GET",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "submit": {
          "description": "Submits a score to the specified leaderboard.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST"
        },
        "submitMultiple": {
          "flatPath": "games/v1/leaderboards/scores",
          "id": "games.scores.submitMultiple",
          "description": "Submits multiple scores to leaderboards.",
          "path": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "id": "games.scores.get",
          "httpMethod": "GET",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}"
        }
      }
    }
  },
  "revision": "20210401",
  "basePath": "",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "canonicalName": "Games",
  "version": "v1",
  "documentationLink": "https://developers.google.com/games/",
  "servicePath": "",
  "baseUrl": "https://games.googleapis.com/",
  "rootUrl": "https://games.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  }
}
