{
  "name": "games",
  "servicePath": "",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "revision": "20240618",
  "ownerDomain": "google.com",
  "canonicalName": "Games",
  "batchPath": "batch",
  "rootUrl": "https://games.googleapis.com/",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "version": "v1",
  "basePath": "",
  "baseUrl": "https://games.googleapis.com/",
  "protocol": "rest",
  "id": "games:v1",
  "title": "Google Play Game Services",
  "resources": {
    "achievementDefinitions": {
      "methods": {
        "list": {
          "id": "games.achievementDefinitions.list",
          "path": "games/v1/achievements",
          "flatPath": "games/v1/achievements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the achievement definitions for your application."
        }
      }
    },
    "achievements": {
      "methods": {
        "increment": {
          "id": "games.achievements.increment",
          "path": "games/v1/achievements/{achievementId}/increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player."
        },
        "list": {
          "id": "games.achievements.list",
          "path": "games/v1/players/{playerId}/achievements",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the progress for all your application's achievements for the currently authenticated player."
        },
        "reveal": {
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player."
        },
        "setStepsAtLeast": {
          "id": "games.achievements.setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified."
        },
        "unlock": {
          "id": "games.achievements.unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Unlocks this achievement for the currently authenticated player."
        },
        "updateMultiple": {
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple",
          "flatPath": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Updates multiple achievements for the currently authenticated player."
        }
      }
    },
    "applications": {
      "methods": {
        "get": {
          "id": "games.applications.get",
          "path": "games/v1/applications/{applicationId}",
          "flatPath": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data."
        },
        "played": {
          "id": "games.applications.played",
          "path": "games/v1/applications/played",
          "flatPath": "games/v1/applications/played",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Indicate that the currently authenticated user is playing your application."
        },
        "verify": {
          "id": "games.applications.verify",
          "path": "games/v1/applications/{applicationId}/verify",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for."
        },
        "getEndPoint": {
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "flatPath": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns a URL for the requested end point type."
        }
      }
    },
    "events": {
      "methods": {
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user."
        },
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "path": "games/v1/eventDefinitions",
          "flatPath": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns a list of the event definitions in this application."
        },
        "record": {
          "id": "games.events.record",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application."
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        },
        "list": {
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards",
          "flatPath": "games/v1/leaderboards",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the leaderboard metadata for your application."
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "id": "games.metagame.getMetagameConfig",
          "path": "games/v1/metagameConfig",
          "flatPath": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Return the metagame configuration data for the calling application."
        },
        "listCategoriesByPlayer": {
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "List play data aggregated per category for the player corresponding to `playerId`."
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "id": "games.players.get",
          "path": "games/v1/players/{playerId}",
          "flatPath": "games/v1/players/{playerId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`."
        },
        "getScopedPlayerIds": {
          "id": "games.players.getScopedPlayerIds",
          "path": "games/v1/players/me/scopedIds",
          "flatPath": "games/v1/players/me/scopedIds",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves scoped player identifiers for currently authenticated user."
        },
        "getMultipleApplicationPlayerIds": {
          "id": "games.players.getMultipleApplicationPlayerIds",
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game."
        },
        "list": {
          "id": "games.players.list",
          "path": "games/v1/players/me/players/{collection}",
          "flatPath": "games/v1/players/me/players/{collection}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Get the collection of players for the currently authenticated user."
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "id": "games.revisions.check",
          "path": "games/v1/revisions/check",
          "flatPath": "games/v1/revisions/check",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Checks whether the games client is out of date."
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "id": "games.scores.get",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'."
        },
        "list": {
          "id": "games.scores.list",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard, starting from the top."
        },
        "listWindow": {
          "id": "games.scores.listWindow",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard around (and including) a player's score."
        },
        "submit": {
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Submits a score to the specified leaderboard."
        },
        "submitMultiple": {
          "id": "games.scores.submitMultiple",
          "path": "games/v1/leaderboards/scores",
          "flatPath": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Submits multiple scores to leaderboards."
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "id": "games.snapshots.get",
          "path": "games/v1/snapshots/{snapshotId}",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves the metadata for a given snapshot ID."
        },
        "list": {
          "id": "games.snapshots.list",
          "path": "games/v1/players/{playerId}/snapshots",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID."
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "id": "games.stats.get",
          "path": "games/v1/stats",
          "flatPath": "games/v1/stats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user."
        }
      }
    },
    "recall": {
      "methods": {
        "linkPersona": {
          "id": "games.recall.linkPersona",
          "path": "games/v1/recall:linkPersona",
          "flatPath": "games/v1/recall:linkPersona",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account"
        },
        "retrieveTokens": {
          "id": "games.recall.retrieveTokens",
          "path": "games/v1/recall/tokens/{sessionId}",
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile."
        },
        "lastTokenFromAllDeveloperGames": {
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile."
        },
        "gamesPlayerTokens": {
          "id": "games.recall.gamesPlayerTokens",
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile."
        },
        "unlinkPersona": {
          "id": "games.recall.unlinkPersona",
          "path": "games/v1/recall:unlinkPersona",
          "flatPath": "games/v1/recall:unlinkPersona",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value."
        },
        "resetPersona": {
          "id": "games.recall.resetPersona",
          "path": "games/v1/recall:resetPersona",
          "flatPath": "games/v1/recall:resetPersona",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile)."
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generatePlayGroupingApiToken": {
          "id": "games.accesstokens.generatePlayGroupingApiToken",
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential."
        },
        "generateRecallPlayGroupingApiToken": {
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken",
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request."
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/games/",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "ownerName": "Google"
}
