{
  "canonicalName": "Gmail",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "name": "gmail",
  "id": "gmail:v1",
  "rootUrl": "https://gmail.googleapis.com/",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        }
      }
    }
  },
  "title": "Gmail API",
  "ownerName": "Google",
  "revision": "20230116",
  "batchPath": "batch",
  "basePath": "",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "resources": {
    "users": {
      "methods": {
        "watch": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "path": "gmail/v1/users/{userId}/watch",
          "httpMethod": "POST",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "id": "gmail.users.watch"
        },
        "getProfile": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "id": "gmail.users.getProfile",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "description": "Gets the current user's Gmail profile.",
          "path": "gmail/v1/users/{userId}/profile",
          "httpMethod": "GET"
        },
        "stop": {
          "description": "Stop receiving push notifications for the given user mailbox.",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "id": "gmail.users.stop",
          "flatPath": "gmail/v1/users/{userId}/stop",
          "httpMethod": "POST",
          "path": "gmail/v1/users/{userId}/stop"
        }
      },
      "resources": {
        "drafts": {
          "methods": {
            "list": {
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "GET",
              "description": "Lists the drafts in the user's mailbox.",
              "id": "gmail.users.drafts.list"
            },
            "create": {
              "path": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "id": "gmail.users.drafts.create",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "description": "Creates a new draft with the `DRAFT` label.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "id": "gmail.users.drafts.delete",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "DELETE",
              "path": "gmail/v1/users/{userId}/drafts/{id}"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.get",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets the specified draft."
            },
            "send": {
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "id": "gmail.users.drafts.send",
              "supportsMediaUpload": true
            },
            "update": {
              "httpMethod": "PUT",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "supportsMediaUpload": true,
              "id": "gmail.users.drafts.update",
              "description": "Replaces a draft's content.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}"
            }
          }
        },
        "settings": {
          "methods": {
            "getVacation": {
              "id": "gmail.users.settings.getVacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets vacation responder settings."
            },
            "updateVacation": {
              "httpMethod": "PUT",
              "description": "Updates vacation responder settings.",
              "id": "gmail.users.settings.updateVacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/vacation"
            },
            "getImap": {
              "httpMethod": "GET",
              "id": "gmail.users.settings.getImap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "description": "Gets IMAP settings.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateLanguage": {
              "httpMethod": "PUT",
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "path": "gmail/v1/users/{userId}/settings/language",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.updateLanguage"
            },
            "getAutoForwarding": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets the auto-forwarding setting for the specified account.",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.getAutoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "updateImap": {
              "id": "gmail.users.settings.updateImap",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "description": "Updates IMAP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/imap"
            },
            "getLanguage": {
              "id": "gmail.users.settings.getLanguage",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "description": "Gets language settings.",
              "path": "gmail/v1/users/{userId}/settings/language",
              "flatPath": "gmail/v1/users/{userId}/settings/language"
            },
            "updateAutoForwarding": {
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "id": "gmail.users.settings.updateAutoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority."
            },
            "updatePop": {
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Updates POP settings.",
              "id": "gmail.users.settings.updatePop",
              "path": "gmail/v1/users/{userId}/settings/pop"
            },
            "getPop": {
              "description": "Gets POP settings.",
              "id": "gmail.users.settings.getPop",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/pop"
            }
          },
          "resources": {
            "filters": {
              "methods": {
                "create": {
                  "id": "gmail.users.settings.filters.create",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Gets a filter.",
                  "id": "gmail.users.settings.filters.get",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}"
                },
                "list": {
                  "description": "Lists the message filters of a Gmail user.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.list",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters"
                },
                "delete": {
                  "description": "Immediately and permanently deletes the specified filter.",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "list": {
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Lists the forwarding addresses for the specified account."
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "httpMethod": "GET",
                  "description": "Gets the specified forwarding address.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority."
                }
              }
            },
            "cse": {
              "resources": {
                "identities": {
                  "methods": {
                    "patch": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "httpMethod": "PATCH",
                      "id": "gmail.users.settings.cse.identities.patch",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887).",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}"
                    },
                    "delete": {
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.cse.identities.delete",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.cse.identities.list",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "description": "Lists the client-side encrypted identities for an authenticated user.",
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities"
                    },
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "description": "Retrieves a client-side encryption identity configuration.",
                      "id": "gmail.users.settings.cse.identities.get",
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}"
                    },
                    "create": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity.",
                      "id": "gmail.users.settings.cse.identities.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "POST"
                    }
                  }
                },
                "keypairs": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "description": "Retrieves an existing client-side encryption key pair.",
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}"
                    },
                    "enable": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities.",
                      "id": "gmail.users.settings.cse.keypairs.enable",
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "id": "gmail.users.settings.cse.keypairs.list",
                      "description": "Lists client-side encryption key pairs for an authenticated user."
                    },
                    "obliterate": {
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages.",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "id": "gmail.users.settings.cse.keypairs.obliterate",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user.",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.cse.keypairs.create"
                    },
                    "disable": {
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method.",
                      "id": "gmail.users.settings.cse.keypairs.disable",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable"
                    }
                  }
                }
              }
            },
            "delegates": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "id": "gmail.users.settings.delegates.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same G Suite organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a G Suite organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that a delegate user mu[...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.create",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "POST"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.delegates.delete",
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}"
                },
                "get": {
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.get",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "GET"
                }
              }
            },
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get"
                    },
                    "delete": {
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "httpMethod": "DELETE",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "insert": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key."
                    },
                    "list": {
                      "httpMethod": "GET",
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    },
                    "setDefault": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "description": "Sets the default S/MIME config for the specified send-as alias."
                    }
                  }
                }
              },
              "methods": {
                "patch": {
                  "description": "Patch the specified send-as alias.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.patch",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PATCH"
                },
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.create",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "POST",
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]"
                },
                "verify": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "id": "gmail.users.settings.sendAs.verify",
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "update": {
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "PUT",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.update"
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "id": "gmail.users.settings.sendAs.get",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "delete": {
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                }
              }
            }
          }
        },
        "labels": {
          "methods": {
            "update": {
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "description": "Updates the specified label.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "get": {
              "id": "gmail.users.labels.get",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Gets the specified label."
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.labels.patch",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Patch the specified label."
            },
            "delete": {
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.labels.delete"
            },
            "create": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels",
              "id": "gmail.users.labels.create",
              "description": "Creates a new label.",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/labels"
            },
            "list": {
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Lists all labels in the user's mailbox.",
              "id": "gmail.users.labels.list",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "messages": {
          "methods": {
            "modify": {
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "description": "Modifies the labels on the specified message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "id": "gmail.users.messages.modify"
            },
            "untrash": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "description": "Removes the specified message from the trash.",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "batchModify": {
              "id": "gmail.users.messages.batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Modifies the labels on the specified messages.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/batchModify"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchDelete",
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "send": {
              "path": "gmail/v1/users/{userId}/messages/send",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "id": "gmail.users.messages.send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/send"
            },
            "get": {
              "id": "gmail.users.messages.get",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Gets the specified message.",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "GET"
            },
            "delete": {
              "id": "gmail.users.messages.delete",
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}"
            },
            "trash": {
              "id": "gmail.users.messages.trash",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "description": "Moves the specified message to the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}/trash"
            },
            "insert": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.insert",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "supportsMediaUpload": true,
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages",
              "description": "Lists the messages in the user's mailbox.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "id": "gmail.users.messages.list"
            },
            "import": {
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note: This function doesn't trigger forwarding rules or filters set up by the user.",
              "supportsMediaUpload": true,
              "path": "gmail/v1/users/{userId}/messages/import",
              "id": "gmail.users.messages.import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "description": "Gets the specified message attachment.",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "id": "gmail.users.messages.attachments.get",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ]
                }
              }
            }
          }
        },
        "threads": {
          "methods": {
            "untrash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash.",
              "id": "gmail.users.threads.untrash",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash"
            },
            "trash": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "id": "gmail.users.threads.trash",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "id": "gmail.users.threads.list",
              "path": "gmail/v1/users/{userId}/threads",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Lists the threads in the user's mailbox.",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/threads"
            },
            "modify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "httpMethod": "POST",
              "id": "gmail.users.threads.modify",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread."
            },
            "delete": {
              "scopes": [
                "https://mail.google.com/"
              ],
              "httpMethod": "DELETE",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead.",
              "id": "gmail.users.threads.delete"
            },
            "get": {
              "description": "Gets the specified thread.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.get",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "id": "gmail.users.history.list",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "flatPath": "gmail/v1/users/{userId}/history",
              "path": "gmail/v1/users/{userId}/history",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "kind": "discovery#restDescription",
  "version": "v1",
  "baseUrl": "https://gmail.googleapis.com/",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "servicePath": ""
}
