{
  "rootUrl": "https://gmail.googleapis.com/",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "name": "gmail",
  "canonicalName": "Gmail",
  "id": "gmail:v1",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "servicePath": "",
  "title": "Gmail API",
  "resources": {
    "users": {
      "methods": {
        "getProfile": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "id": "gmail.users.getProfile",
          "path": "gmail/v1/users/{userId}/profile",
          "httpMethod": "GET",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "description": "Gets the current user's Gmail profile."
        },
        "stop": {
          "description": "Stop receiving push notifications for the given user mailbox.",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "path": "gmail/v1/users/{userId}/stop",
          "flatPath": "gmail/v1/users/{userId}/stop",
          "id": "gmail.users.stop"
        },
        "watch": {
          "path": "gmail/v1/users/{userId}/watch",
          "httpMethod": "POST",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "id": "gmail.users.watch",
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        }
      },
      "resources": {
        "threads": {
          "methods": {
            "get": {
              "description": "Gets the specified thread.",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "id": "gmail.users.threads.get",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "GET"
            },
            "untrash": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "description": "Removes the specified thread from the trash.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.threads.untrash",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash"
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer `threads.trash` instead.",
              "scopes": [
                "https://mail.google.com/"
              ],
              "id": "gmail.users.threads.delete",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "DELETE",
              "path": "gmail/v1/users/{userId}/threads/{id}"
            },
            "list": {
              "description": "Lists the threads in the user's mailbox.",
              "path": "gmail/v1/users/{userId}/threads",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "id": "gmail.users.threads.list",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "id": "gmail.users.threads.modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "httpMethod": "POST"
            },
            "trash": {
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "httpMethod": "POST",
              "description": "Moves the specified thread to the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.threads.trash"
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/history",
              "id": "gmail.users.history.list",
              "path": "gmail/v1/users/{userId}/history",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "httpMethod": "GET"
            }
          }
        },
        "messages": {
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "id": "gmail.users.messages.attachments.get",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "trash": {
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "id": "gmail.users.messages.trash",
              "description": "Moves the specified message to the trash.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "untrash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Removes the specified message from the trash.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash"
            },
            "batchDelete": {
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "id": "gmail.users.messages.batchDelete",
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/messages",
              "id": "gmail.users.messages.list",
              "httpMethod": "GET",
              "description": "Lists the messages in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/messages"
            },
            "import": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message. Note: This function doesn't trigger forwarding rules or filters set up by the user.",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/import",
              "id": "gmail.users.messages.import"
            },
            "insert": {
              "flatPath": "gmail/v1/users/{userId}/messages",
              "httpMethod": "POST",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages",
              "id": "gmail.users.messages.insert"
            },
            "batchModify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.batchModify",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "description": "Modifies the labels on the specified messages."
            },
            "send": {
              "path": "gmail/v1/users/{userId}/messages/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "httpMethod": "POST",
              "id": "gmail.users.messages.send",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/send"
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.delete",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "httpMethod": "DELETE",
              "path": "gmail/v1/users/{userId}/messages/{id}"
            },
            "modify": {
              "id": "gmail.users.messages.modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "description": "Modifies the labels on the specified message.",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets the specified message.",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.get",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "labels": {
          "methods": {
            "get": {
              "id": "gmail.users.labels.get",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Gets the specified label.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}"
            },
            "update": {
              "description": "Updates the specified label.",
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.update",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.labels.delete",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "create": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.labels.create",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "description": "Creates a new label.",
              "path": "gmail/v1/users/{userId}/labels",
              "httpMethod": "POST"
            },
            "patch": {
              "description": "Patch the specified label.",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.patch",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PATCH"
            },
            "list": {
              "flatPath": "gmail/v1/users/{userId}/labels",
              "id": "gmail.users.labels.list",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Lists all labels in the user's mailbox."
            }
          }
        },
        "drafts": {
          "methods": {
            "list": {
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.list",
              "description": "Lists the drafts in the user's mailbox.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "get": {
              "description": "Gets the specified draft.",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.get",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "create": {
              "path": "gmail/v1/users/{userId}/drafts",
              "description": "Creates a new draft with the `DRAFT` label.",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.create",
              "supportsMediaUpload": true
            },
            "delete": {
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "DELETE",
              "id": "gmail.users.drafts.delete"
            },
            "send": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "id": "gmail.users.drafts.send",
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/drafts/send"
            },
            "update": {
              "id": "gmail.users.drafts.update",
              "description": "Replaces a draft's content.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PUT"
            }
          }
        },
        "settings": {
          "resources": {
            "forwardingAddresses": {
              "methods": {
                "list": {
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "GET",
                  "description": "Lists the forwarding addresses for the specified account."
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                },
                "create": {
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "POST"
                },
                "get": {
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "description": "Gets the specified forwarding address.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "delegates": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.list",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.get",
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "delete": {
                  "id": "gmail.users.settings.delegates.delete",
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "DELETE",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}"
                },
                "create": {
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "POST",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.delegates.create",
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same G Suite organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a G Suite organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that a delegate user mu[...]"
                }
              }
            },
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "insert": {
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    },
                    "list": {
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "setDefault": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault"
                    },
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "GET"
                    }
                  }
                }
              },
              "methods": {
                "verify": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "id": "gmail.users.settings.sendAs.verify",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "POST"
                },
                "list": {
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "GET",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.sendAs.list"
                },
                "delete": {
                  "id": "gmail.users.settings.sendAs.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "patch": {
                  "id": "gmail.users.settings.sendAs.patch",
                  "httpMethod": "PATCH",
                  "description": "Patch the specified send-as alias.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "get": {
                  "id": "gmail.users.settings.sendAs.get",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection."
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PUT",
                  "id": "gmail.users.settings.sendAs.update",
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs"
                }
              }
            },
            "filters": {
              "methods": {
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Lists the message filters of a Gmail user."
                },
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "httpMethod": "POST"
                },
                "get": {
                  "description": "Gets a filter.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.filters.get"
                },
                "delete": {
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a filter.",
                  "id": "gmail.users.settings.filters.delete",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}"
                }
              }
            }
          },
          "methods": {
            "updateImap": {
              "description": "Updates IMAP settings.",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/imap"
            },
            "updateVacation": {
              "id": "gmail.users.settings.updateVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Updates vacation responder settings.",
              "httpMethod": "PUT"
            },
            "getVacation": {
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Gets vacation responder settings.",
              "id": "gmail.users.settings.getVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updatePop": {
              "path": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Updates POP settings.",
              "id": "gmail.users.settings.updatePop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop"
            },
            "getImap": {
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.getImap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "description": "Gets IMAP settings.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET"
            },
            "getLanguage": {
              "description": "Gets language settings.",
              "path": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.getLanguage"
            },
            "getAutoForwarding": {
              "httpMethod": "GET",
              "description": "Gets the auto-forwarding setting for the specified account.",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.getAutoForwarding",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "updateLanguage": {
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.updateLanguage",
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "httpMethod": "PUT"
            },
            "updateAutoForwarding": {
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "id": "gmail.users.settings.updateAutoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority."
            },
            "getPop": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets POP settings.",
              "id": "gmail.users.settings.getPop",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "path": "gmail/v1/users/{userId}/settings/pop"
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        }
      }
    }
  },
  "ownerName": "Google",
  "basePath": "",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.",
  "version": "v1",
  "kind": "discovery#restDescription",
  "revision": "20210614",
  "baseUrl": "https://gmail.googleapis.com/"
}
