{
  "revision": "20230206",
  "basePath": "",
  "ownerName": "Google",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "resources": {
    "users": {
      "methods": {
        "getProfile": {
          "path": "gmail/v1/users/{userId}/profile",
          "description": "Gets the current user's Gmail profile.",
          "id": "gmail.users.getProfile",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "httpMethod": "GET"
        },
        "stop": {
          "id": "gmail.users.stop",
          "path": "gmail/v1/users/{userId}/stop",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Stop receiving push notifications for the given user mailbox.",
          "flatPath": "gmail/v1/users/{userId}/stop"
        },
        "watch": {
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "path": "gmail/v1/users/{userId}/watch",
          "description": "Set up or update a push notification watch on the given user mailbox."
        }
      },
      "resources": {
        "messages": {
          "methods": {
            "modify": {
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "description": "Modifies the labels on the specified message.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.modify",
              "httpMethod": "POST"
            },
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.trash",
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "description": "Moves the specified message to the trash.",
              "httpMethod": "POST"
            },
            "send": {
              "supportsMediaUpload": true,
              "id": "gmail.users.messages.send",
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For example usage, see [Sending email](https://developers.google.com/gmail/api/guides/sending).",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ]
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Gets the specified message.",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.get",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "id": "gmail.users.messages.delete",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "batchDelete": {
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "id": "gmail.users.messages.batchDelete"
            },
            "untrash": {
              "description": "Removes the specified message from the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "id": "gmail.users.messages.untrash"
            },
            "batchModify": {
              "id": "gmail.users.messages.batchModify",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Modifies the labels on the specified messages.",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify"
            },
            "import": {
              "path": "gmail/v1/users/{userId}/messages/import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.import",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note: This function doesn't trigger forwarding rules or filters set up by the user."
            },
            "insert": {
              "id": "gmail.users.messages.insert",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages",
              "httpMethod": "POST",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "id": "gmail.users.messages.list",
              "description": "Lists the messages in the user's mailbox.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/messages"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "id": "gmail.users.messages.attachments.get",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ],
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "description": "Gets the specified message attachment.",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "threads": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "description": "Lists the threads in the user's mailbox.",
              "path": "gmail/v1/users/{userId}/threads",
              "id": "gmail.users.threads.list",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "untrash": {
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "id": "gmail.users.threads.untrash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash."
            },
            "trash": {
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash.",
              "id": "gmail.users.threads.trash",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "modify": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "id": "gmail.users.threads.modify",
              "httpMethod": "POST",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.delete",
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead.",
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "DELETE"
            },
            "get": {
              "description": "Gets the specified thread.",
              "id": "gmail.users.threads.get",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}"
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "id": "gmail.users.history.list",
              "flatPath": "gmail/v1/users/{userId}/history",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/history"
            }
          }
        },
        "labels": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "id": "gmail.users.labels.delete",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}"
            },
            "list": {
              "path": "gmail/v1/users/{userId}/labels",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "description": "Lists all labels in the user's mailbox.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.labels.list"
            },
            "create": {
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Creates a new label.",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "id": "gmail.users.labels.create"
            },
            "patch": {
              "description": "Patch the specified label.",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.patch",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PATCH",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "get": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Gets the specified label.",
              "httpMethod": "GET",
              "id": "gmail.users.labels.get",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "update": {
              "id": "gmail.users.labels.update",
              "description": "Updates the specified label.",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PUT",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          }
        },
        "drafts": {
          "methods": {
            "list": {
              "id": "gmail.users.drafts.list",
              "path": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "description": "Lists the drafts in the user's mailbox.",
              "httpMethod": "GET"
            },
            "get": {
              "httpMethod": "GET",
              "id": "gmail.users.drafts.get",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Gets the specified draft.",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "delete": {
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "httpMethod": "DELETE",
              "id": "gmail.users.drafts.delete",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.create",
              "path": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Creates a new draft with the `DRAFT` label."
            },
            "send": {
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "id": "gmail.users.drafts.send",
              "supportsMediaUpload": true
            },
            "update": {
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.update",
              "description": "Replaces a draft's content.",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "PUT"
            }
          }
        },
        "settings": {
          "resources": {
            "forwardingAddresses": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "description": "Gets the specified forwarding address."
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists the forwarding addresses for the specified account.",
                  "id": "gmail.users.settings.forwardingAddresses.list"
                }
              }
            },
            "cse": {
              "resources": {
                "identities": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "id": "gmail.users.settings.cse.identities.get",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "description": "Retrieves a client-side encryption identity configuration."
                    },
                    "create": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.create",
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity.",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.list",
                      "httpMethod": "GET",
                      "description": "Lists the client-side encrypted identities for an authenticated user.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "httpMethod": "PATCH",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887).",
                      "id": "gmail.users.settings.cse.identities.patch"
                    },
                    "delete": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "DELETE",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration.",
                      "id": "gmail.users.settings.cse.identities.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                },
                "keypairs": {
                  "methods": {
                    "disable": {
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.cse.keypairs.disable",
                      "httpMethod": "POST",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable"
                    },
                    "get": {
                      "description": "Retrieves an existing client-side encryption key pair.",
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "id": "gmail.users.settings.cse.keypairs.list",
                      "description": "Lists client-side encryption key pairs for an authenticated user."
                    },
                    "create": {
                      "id": "gmail.users.settings.cse.keypairs.create",
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user.",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs"
                    },
                    "obliterate": {
                      "id": "gmail.users.settings.cse.keypairs.obliterate",
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "enable": {
                      "id": "gmail.users.settings.cse.keypairs.enable",
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities.",
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                }
              }
            },
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "setDefault": {
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "insert": {
                      "httpMethod": "POST",
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}"
                    },
                    "list": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    }
                  }
                }
              },
              "methods": {
                "update": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.update",
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "GET",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.sendAs.get",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection."
                },
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.create",
                  "httpMethod": "POST",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]"
                },
                "patch": {
                  "description": "Patch the specified send-as alias.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "id": "gmail.users.settings.sendAs.delete",
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "verify": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.verify",
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.sendAs.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "httpMethod": "GET"
                }
              }
            },
            "delegates": {
              "methods": {
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.delegates.create",
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same Google Workspace organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a Google Workspace organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that [...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates"
                },
                "list": {
                  "id": "gmail.users.settings.delegates.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}"
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.get",
                  "httpMethod": "GET"
                }
              }
            },
            "filters": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "httpMethod": "POST"
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.list",
                  "httpMethod": "GET",
                  "description": "Lists the message filters of a Gmail user."
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "description": "Immediately and permanently deletes the specified filter.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "description": "Gets a filter.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.filters.get",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "GET",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}"
                }
              }
            }
          },
          "methods": {
            "getLanguage": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.settings.getLanguage",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "description": "Gets language settings.",
              "path": "gmail/v1/users/{userId}/settings/language"
            },
            "updateLanguage": {
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "PUT",
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "id": "gmail.users.settings.updateLanguage",
              "path": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getAutoForwarding": {
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "description": "Gets the auto-forwarding setting for the specified account.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.getAutoForwarding"
            },
            "updateVacation": {
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.updateVacation",
              "description": "Updates vacation responder settings."
            },
            "getImap": {
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "description": "Gets IMAP settings.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.getImap"
            },
            "getPop": {
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "id": "gmail.users.settings.getPop",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/pop",
              "description": "Gets POP settings.",
              "httpMethod": "GET"
            },
            "getVacation": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.getVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Gets vacation responder settings."
            },
            "updateImap": {
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "PUT",
              "description": "Updates IMAP settings."
            },
            "updatePop": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updatePop",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "description": "Updates POP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/pop"
            },
            "updateAutoForwarding": {
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "PUT",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority.",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.updateAutoForwarding"
            }
          }
        }
      }
    }
  },
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "rootUrl": "https://gmail.googleapis.com/",
  "canonicalName": "Gmail",
  "name": "gmail",
  "id": "gmail:v1",
  "title": "Gmail API",
  "ownerDomain": "google.com",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.",
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "version": "v1",
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        }
      }
    }
  },
  "baseUrl": "https://gmail.googleapis.com/"
}
