{
  "revision": "20230612",
  "ownerName": "Google",
  "title": "Gmail API",
  "protocol": "rest",
  "name": "gmail",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "rootUrl": "https://gmail.googleapis.com/",
  "baseUrl": "https://gmail.googleapis.com/",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "basePath": "",
  "batchPath": "batch",
  "id": "gmail:v1",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        }
      }
    }
  },
  "canonicalName": "Gmail",
  "version": "v1",
  "resources": {
    "users": {
      "methods": {
        "watch": {
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "path": "gmail/v1/users/{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "getProfile": {
          "id": "gmail.users.getProfile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "httpMethod": "GET",
          "path": "gmail/v1/users/{userId}/profile",
          "description": "Gets the current user's Gmail profile.",
          "flatPath": "gmail/v1/users/{userId}/profile"
        },
        "stop": {
          "flatPath": "gmail/v1/users/{userId}/stop",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Stop receiving push notifications for the given user mailbox.",
          "path": "gmail/v1/users/{userId}/stop",
          "id": "gmail.users.stop"
        }
      },
      "resources": {
        "history": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "path": "gmail/v1/users/{userId}/history",
              "id": "gmail.users.history.list",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/history"
            }
          }
        },
        "messages": {
          "methods": {
            "untrash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash",
              "description": "Removes the specified message from the trash.",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.messages.get",
              "description": "Gets the specified message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}"
            },
            "modify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "httpMethod": "POST",
              "description": "Modifies the labels on the specified message.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "id": "gmail.users.messages.modify"
            },
            "batchDelete": {
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "httpMethod": "POST",
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "id": "gmail.users.messages.batchDelete",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "id": "gmail.users.messages.trash",
              "httpMethod": "POST",
              "description": "Moves the specified message to the trash.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash"
            },
            "list": {
              "id": "gmail.users.messages.list",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/messages",
              "description": "Lists the messages in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/messages"
            },
            "batchModify": {
              "id": "gmail.users.messages.batchModify",
              "description": "Modifies the labels on the specified messages.",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "id": "gmail.users.messages.delete",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}"
            },
            "import": {
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/import",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "id": "gmail.users.messages.import"
            },
            "insert": {
              "path": "gmail/v1/users/{userId}/messages",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "httpMethod": "POST",
              "id": "gmail.users.messages.insert",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "send": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "id": "gmail.users.messages.send",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For example usage, see [Sending email](https://developers.google.com/gmail/api/guides/sending).",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/send"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "id": "gmail.users.messages.attachments.get",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "description": "Gets the specified message attachment.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ]
                }
              }
            }
          }
        },
        "drafts": {
          "methods": {
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.list",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "description": "Lists the drafts in the user's mailbox."
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "id": "gmail.users.drafts.delete"
            },
            "update": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.update",
              "supportsMediaUpload": true,
              "description": "Replaces a draft's content.",
              "httpMethod": "PUT"
            },
            "create": {
              "id": "gmail.users.drafts.create",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "description": "Creates a new draft with the `DRAFT` label."
            },
            "send": {
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "httpMethod": "POST",
              "id": "gmail.users.drafts.send"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.get",
              "description": "Gets the specified draft.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "settings": {
          "methods": {
            "updateAutoForwarding": {
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "id": "gmail.users.settings.updateAutoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority."
            },
            "updateImap": {
              "id": "gmail.users.settings.updateImap",
              "description": "Updates IMAP settings.",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT"
            },
            "getPop": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getPop",
              "description": "Gets POP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/pop"
            },
            "updateLanguage": {
              "path": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.updateLanguage",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "httpMethod": "PUT"
            },
            "getAutoForwarding": {
              "description": "Gets the auto-forwarding setting for the specified account.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.getAutoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "getLanguage": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "GET",
              "description": "Gets language settings.",
              "id": "gmail.users.settings.getLanguage"
            },
            "updateVacation": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.updateVacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Updates vacation responder settings."
            },
            "getImap": {
              "path": "gmail/v1/users/{userId}/settings/imap",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "id": "gmail.users.settings.getImap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "description": "Gets IMAP settings.",
              "httpMethod": "GET"
            },
            "updatePop": {
              "id": "gmail.users.settings.updatePop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "description": "Updates POP settings.",
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getVacation": {
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Gets vacation responder settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getVacation",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            }
          },
          "resources": {
            "delegates": {
              "methods": {
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "GET",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.delegates.get",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same Google Workspace organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a Google Workspace organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that [...]",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "POST"
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.delegates.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                }
              }
            },
            "filters": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Immediately and permanently deletes the specified filter.",
                  "id": "gmail.users.settings.filters.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}"
                },
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.create",
                  "httpMethod": "POST",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "description": "Gets a filter.",
                  "id": "gmail.users.settings.filters.get",
                  "httpMethod": "GET"
                },
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.list",
                  "description": "Lists the message filters of a Gmail user.",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "cse": {
              "resources": {
                "identities": {
                  "methods": {
                    "delete": {
                      "id": "gmail.users.settings.cse.identities.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "DELETE"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists the client-side encrypted identities for an authenticated user.",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.list",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities"
                    },
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.cse.identities.get",
                      "description": "Retrieves a client-side encryption identity configuration."
                    },
                    "patch": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "id": "gmail.users.settings.cse.identities.patch",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887).",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "PATCH",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}"
                    },
                    "create": {
                      "id": "gmail.users.settings.cse.identities.create",
                      "httpMethod": "POST",
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/identities"
                    }
                  }
                },
                "keypairs": {
                  "methods": {
                    "create": {
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user.",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.create",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "enable": {
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.enable",
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "obliterate": {
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST",
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages.",
                      "id": "gmail.users.settings.cse.keypairs.obliterate",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate"
                    },
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "description": "Retrieves an existing client-side encryption key pair.",
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "disable": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "id": "gmail.users.settings.cse.keypairs.disable",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "POST",
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method.",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable"
                    },
                    "list": {
                      "description": "Lists client-side encryption key pairs for an authenticated user.",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.cse.keypairs.list"
                    }
                  }
                }
              }
            },
            "sendAs": {
              "methods": {
                "update": {
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PUT",
                  "id": "gmail.users.settings.sendAs.update",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "list": {
                  "id": "gmail.users.settings.sendAs.list",
                  "httpMethod": "GET",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "verify": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.verify",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "httpMethod": "POST",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "get": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "GET",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "id": "gmail.users.settings.sendAs.get",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "PATCH",
                  "id": "gmail.users.settings.sendAs.patch",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Patch the specified send-as alias.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "delete": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.delete",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority."
                }
              },
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "httpMethod": "GET"
                    },
                    "insert": {
                      "httpMethod": "POST",
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert"
                    },
                    "setDefault": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "description": "Lists S/MIME configs for the specified send-as alias."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}"
                    }
                  }
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "get": {
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "description": "Gets the specified forwarding address.",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Lists the forwarding addresses for the specified account.",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "GET"
                },
                "create": {
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "POST",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority."
                }
              }
            }
          }
        },
        "labels": {
          "methods": {
            "list": {
              "id": "gmail.users.labels.list",
              "description": "Lists all labels in the user's mailbox.",
              "path": "gmail/v1/users/{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/labels"
            },
            "create": {
              "path": "gmail/v1/users/{userId}/labels",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "httpMethod": "POST",
              "description": "Creates a new label.",
              "id": "gmail.users.labels.create",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Gets the specified label.",
              "id": "gmail.users.labels.get",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "patch": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PATCH",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.patch",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Patch the specified label."
            },
            "delete": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.delete"
            },
            "update": {
              "description": "Updates the specified label.",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            }
          }
        },
        "threads": {
          "methods": {
            "trash": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "id": "gmail.users.threads.trash",
              "httpMethod": "POST",
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/threads/{id}/trash"
            },
            "untrash": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash.",
              "id": "gmail.users.threads.untrash",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash"
            },
            "modify": {
              "id": "gmail.users.threads.modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "description": "Gets the specified thread.",
              "id": "gmail.users.threads.get"
            },
            "list": {
              "description": "Lists the threads in the user's mailbox.",
              "httpMethod": "GET",
              "id": "gmail.users.threads.list",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads",
              "path": "gmail/v1/users/{userId}/threads"
            },
            "delete": {
              "id": "gmail.users.threads.delete",
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead.",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels."
}
