{
  "discoveryVersion": "v1",
  "revision": "20210621",
  "title": "People API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/user.organization.read": {
          "description": "See your education, work history and org info"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://www.googleapis.com/auth/user.emails.read": {
          "description": "See and download all of your Google Account email addresses"
        },
        "https://www.googleapis.com/auth/user.phonenumbers.read": {
          "description": "See and download your personal phone numbers"
        },
        "https://www.googleapis.com/auth/userinfo.profile": {
          "description": "See your personal info, including any personal info you've made publicly available"
        },
        "https://www.googleapis.com/auth/user.birthday.read": {
          "description": "See and download your exact date of birth"
        },
        "https://www.googleapis.com/auth/directory.readonly": {
          "description": "See and download your organization's GSuite directory"
        },
        "https://www.googleapis.com/auth/user.gender.read": {
          "description": "See your gender"
        },
        "https://www.googleapis.com/auth/user.addresses.read": {
          "description": "View your street addresses"
        },
        "https://www.googleapis.com/auth/contacts.readonly": {
          "description": "See and download your contacts"
        },
        "https://www.googleapis.com/auth/contacts": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/contacts.other.readonly": {
          "description": "See and download contact info automatically saved in your \"Other contacts\""
        }
      }
    }
  },
  "mtlsRootUrl": "https://people.mtls.googleapis.com/",
  "version": "v1",
  "basePath": "",
  "rootUrl": "https://people.googleapis.com/",
  "id": "people:v1",
  "description": "Provides access to information about profiles and contacts.",
  "canonicalName": "People Service",
  "baseUrl": "https://people.googleapis.com/",
  "ownerDomain": "google.com",
  "servicePath": "",
  "version_module": true,
  "protocol": "rest",
  "name": "people",
  "ownerName": "Google",
  "resources": {
    "contactGroups": {
      "resources": {
        "members": {
          "methods": {
            "modify": {
              "id": "people.contactGroups.members.modify",
              "description": "Modify the members of a contact group owned by the authenticated user. The only system contact groups that can have members added are `contactGroups/myContacts` and `contactGroups/starred`. Other system contact groups are deprecated and can only have contacts removed.",
              "scopes": [
                "https://www.googleapis.com/auth/contacts"
              ],
              "httpMethod": "POST",
              "path": "v1/{+resourceName}/members:modify",
              "flatPath": "v1/contactGroups/{contactGroupsId}/members:modify"
            }
          }
        }
      },
      "methods": {
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "description": "Create a new contact group owned by the authenticated user. Created contact group names must be unique to the users contact groups. Attempting to create a group with a duplicate name will return a HTTP 409 error.",
          "flatPath": "v1/contactGroups",
          "id": "people.contactGroups.create",
          "path": "v1/contactGroups"
        },
        "batchGet": {
          "httpMethod": "GET",
          "description": "Get a list of contact groups owned by the authenticated user by specifying a list of contact group resource names.",
          "id": "people.contactGroups.batchGet",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "flatPath": "v1/contactGroups:batchGet",
          "path": "v1/contactGroups:batchGet"
        },
        "get": {
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "id": "people.contactGroups.get",
          "path": "v1/{+resourceName}",
          "description": "Get a specific contact group owned by the authenticated user by specifying a contact group resource name."
        },
        "list": {
          "flatPath": "v1/contactGroups",
          "httpMethod": "GET",
          "description": "List all contact groups owned by the authenticated user. Members of the contact groups are not populated.",
          "path": "v1/contactGroups",
          "id": "people.contactGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "id": "people.contactGroups.delete",
          "path": "v1/{+resourceName}",
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "description": "Delete an existing contact group owned by the authenticated user by specifying a contact group resource name.",
          "httpMethod": "DELETE"
        },
        "update": {
          "id": "people.contactGroups.update",
          "httpMethod": "PUT",
          "description": "Update the name of an existing contact group owned by the authenticated user. Updated contact group names must be unique to the users contact groups. Attempting to create a group with a duplicate name will return a HTTP 409 error.",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "path": "v1/{+resourceName}",
          "flatPath": "v1/contactGroups/{contactGroupsId}"
        }
      }
    },
    "otherContacts": {
      "methods": {
        "search": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts.other.readonly"
          ],
          "flatPath": "v1/otherContacts:search",
          "path": "v1/otherContacts:search",
          "id": "people.otherContacts.search",
          "description": "Provides a list of contacts in the authenticated user's other contacts that matches the search query. The query matches on a contact's `names`, `emailAddresses`, and `phoneNumbers` fields that are from the OTHER_CONTACT source. **IMPORTANT**: Before searching, clients should send a warmup request with an empty query to update the cache. See https://developers.google.com/people/v1/other-contacts#search_the_users_other_contacts",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "v1/otherContacts",
          "scopes": [
            "https://www.googleapis.com/auth/contacts.other.readonly"
          ],
          "description": "List all \"Other contacts\", that is contacts that are not in a contact group. \"Other contacts\" are typically auto created contacts from interactions.",
          "httpMethod": "GET",
          "id": "people.otherContacts.list",
          "path": "v1/otherContacts"
        },
        "copyOtherContactToMyContactsGroup": {
          "path": "v1/{+resourceName}:copyOtherContactToMyContactsGroup",
          "description": "Copies an \"Other contact\" to a new contact in the user's \"myContacts\" group",
          "flatPath": "v1/otherContacts/{otherContactsId}:copyOtherContactToMyContactsGroup",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.other.readonly"
          ],
          "id": "people.otherContacts.copyOtherContactToMyContactsGroup"
        }
      }
    },
    "people": {
      "methods": {
        "batchDeleteContacts": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "httpMethod": "POST",
          "id": "people.people.batchDeleteContacts",
          "description": "Delete a batch of contacts. Any non-contact data will not be deleted. Limited to 10 parallel requests per user.",
          "flatPath": "v1/people:batchDeleteContacts",
          "path": "v1/people:batchDeleteContacts"
        },
        "deleteContactPhoto": {
          "path": "v1/{+resourceName}:deleteContactPhoto",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/people/{peopleId}:deleteContactPhoto",
          "httpMethod": "DELETE",
          "description": "Delete a contact's photo.",
          "id": "people.people.deleteContactPhoto"
        },
        "createContact": {
          "description": "Create a new contact and return the person resource for that contact. The request returns a 400 error if more than one field is specified on a field that is a singleton for contact sources: * biographies * birthdays * genders * names",
          "id": "people.people.createContact",
          "path": "v1/people:createContact",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/people:createContact"
        },
        "updateContactPhoto": {
          "flatPath": "v1/people/{peopleId}:updateContactPhoto",
          "path": "v1/{+resourceName}:updateContactPhoto",
          "description": "Update a contact's photo.",
          "id": "people.people.updateContactPhoto",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        },
        "listDirectoryPeople": {
          "path": "v1/people:listDirectoryPeople",
          "httpMethod": "GET",
          "description": "Provides a list of domain profiles and domain contacts in the authenticated user's domain directory.",
          "scopes": [
            "https://www.googleapis.com/auth/directory.readonly"
          ],
          "flatPath": "v1/people:listDirectoryPeople",
          "id": "people.people.listDirectoryPeople"
        },
        "updateContact": {
          "path": "v1/{+resourceName}:updateContact",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "id": "people.people.updateContact",
          "description": "Update contact data for an existing contact person. Any non-contact data will not be modified. Any non-contact data in the person to update will be ignored. All fields specified in the `update_mask` will be replaced. The server returns a 400 error if `person.metadata.sources` is not specified for the contact to be updated or if there is no contact source. The server returns a 400 error with reason `\"failedPrecondition\"` if `person.metadata.sources.etag` is different t[...]",
          "flatPath": "v1/people/{peopleId}:updateContact"
        },
        "batchUpdateContacts": {
          "flatPath": "v1/people:batchUpdateContacts",
          "id": "people.people.batchUpdateContacts",
          "path": "v1/people:batchUpdateContacts",
          "description": "Update a batch of contacts and return a map of resource names to PersonResponses for the updated contacts. Limited to 10 parallel requests per user.",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "httpMethod": "POST"
        },
        "deleteContact": {
          "description": "Delete a contact person. Any non-contact data will not be deleted.",
          "path": "v1/{+resourceName}:deleteContact",
          "id": "people.people.deleteContact",
          "flatPath": "v1/people/{peopleId}:deleteContact",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        },
        "searchDirectoryPeople": {
          "id": "people.people.searchDirectoryPeople",
          "path": "v1/people:searchDirectoryPeople",
          "flatPath": "v1/people:searchDirectoryPeople",
          "scopes": [
            "https://www.googleapis.com/auth/directory.readonly"
          ],
          "description": "Provides a list of domain profiles and domain contacts in the authenticated user's domain directory that match the search query.",
          "httpMethod": "GET"
        },
        "searchContacts": {
          "id": "people.people.searchContacts",
          "flatPath": "v1/people:searchContacts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "description": "Provides a list of contacts in the authenticated user's grouped contacts that matches the search query. The query matches on a contact's `names`, `nickNames`, `emailAddresses`, `phoneNumbers`, and `organizations` fields that are from the CONTACT\" source. **IMPORTANT**: Before searching, clients should send a warmup request with an empty query to update the cache. See https://developers.google.com/people/v1/contacts#search_the_users_contacts",
          "path": "v1/people:searchContacts"
        },
        "get": {
          "flatPath": "v1/people/{peopleId}",
          "id": "people.people.get",
          "description": "Provides information about a person by specifying a resource name. Use `people/me` to indicate the authenticated user. The request returns a 400 error if 'personFields' is not specified.",
          "httpMethod": "GET",
          "path": "v1/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/directory.readonly",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.gender.read",
            "https://www.googleapis.com/auth/user.organization.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ]
        },
        "getBatchGet": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/directory.readonly",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.gender.read",
            "https://www.googleapis.com/auth/user.organization.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/people:batchGet",
          "description": "Provides information about a list of specific people by specifying a list of requested resource names. Use `people/me` to indicate the authenticated user. The request returns a 400 error if 'personFields' is not specified.",
          "id": "people.people.getBatchGet",
          "path": "v1/people:batchGet"
        },
        "batchCreateContacts": {
          "httpMethod": "POST",
          "id": "people.people.batchCreateContacts",
          "flatPath": "v1/people:batchCreateContacts",
          "description": "Create a batch of new contacts and return the PersonResponses for the newly created contacts. Limited to 10 parallel requests per user.",
          "path": "v1/people:batchCreateContacts",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        }
      },
      "resources": {
        "connections": {
          "methods": {
            "list": {
              "flatPath": "v1/people/{peopleId}/connections",
              "scopes": [
                "https://www.googleapis.com/auth/contacts",
                "https://www.googleapis.com/auth/contacts.readonly"
              ],
              "id": "people.people.connections.list",
              "path": "v1/{+resourceName}/connections",
              "description": "Provides a list of the authenticated user's contacts. The request returns a 400 error if `personFields` is not specified. The request returns a 410 error if `sync_token` is specified and is expired. Sync tokens expire after 7 days to prevent data drift between clients and the server. To handle a sync token expired error, a request should be sent without `sync_token` to get all contacts.",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/people/"
}
