{
  "description": "",
  "name": "places",
  "title": "Places API (New)",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/maps-platform.places.textsearch": {
          "description": "Private Service: https://www.googleapis.com/auth/maps-platform.places.textsearch"
        },
        "https://www.googleapis.com/auth/maps-platform.places": {
          "description": "Private Service: https://www.googleapis.com/auth/maps-platform.places"
        },
        "https://www.googleapis.com/auth/maps-platform.places.autocomplete": {
          "description": "Private Service: https://www.googleapis.com/auth/maps-platform.places.autocomplete"
        },
        "https://www.googleapis.com/auth/maps-platform.places.details": {
          "description": "Private Service: https://www.googleapis.com/auth/maps-platform.places.details"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/maps-platform.places.nearbysearch": {
          "description": "Private Service: https://www.googleapis.com/auth/maps-platform.places.nearbysearch"
        }
      }
    }
  },
  "baseUrl": "https://places.googleapis.com/",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "basePath": "",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "resources": {
    "places": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/maps-platform.places",
            "https://www.googleapis.com/auth/maps-platform.places.details"
          ],
          "path": "v1/{+name}",
          "description": "Get the details of a place based on its resource name, which is a string in the `places/{place_id}` format.",
          "flatPath": "v1/places/{placesId}",
          "id": "places.places.get",
          "httpMethod": "GET"
        },
        "autocomplete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/maps-platform.places",
            "https://www.googleapis.com/auth/maps-platform.places.autocomplete"
          ],
          "id": "places.places.autocomplete",
          "flatPath": "v1/places:autocomplete",
          "description": "Returns predictions for the given input.",
          "httpMethod": "POST",
          "path": "v1/places:autocomplete"
        },
        "searchNearby": {
          "description": "Search for places near locations.",
          "id": "places.places.searchNearby",
          "flatPath": "v1/places:searchNearby",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/maps-platform.places",
            "https://www.googleapis.com/auth/maps-platform.places.nearbysearch"
          ],
          "httpMethod": "POST",
          "path": "v1/places:searchNearby"
        },
        "searchText": {
          "path": "v1/places:searchText",
          "description": "Text query based place search.",
          "httpMethod": "POST",
          "flatPath": "v1/places:searchText",
          "id": "places.places.searchText",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/maps-platform.places",
            "https://www.googleapis.com/auth/maps-platform.places.textsearch"
          ]
        }
      },
      "resources": {
        "photos": {
          "methods": {
            "getMedia": {
              "flatPath": "v1/places/{placesId}/photos/{photosId}/media",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/maps-platform.places"
              ],
              "path": "v1/{+name}",
              "id": "places.places.photos.getMedia",
              "httpMethod": "GET",
              "description": "Get a photo media with a photo reference string."
            }
          }
        }
      }
    }
  },
  "batchPath": "batch",
  "documentationLink": "https://mapsplatform.google.com/maps-products/#places-section",
  "mtlsRootUrl": "https://places.mtls.googleapis.com/",
  "rootUrl": "https://places.googleapis.com/",
  "revision": "20240219",
  "version": "v1",
  "ownerName": "Google",
  "id": "places:v1",
  "version_module": true,
  "canonicalName": "Maps Places"
}
