{
  "kind": "discovery#restDescription",
  "rootUrl": "https://reseller.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "title": "Google Workspace Reseller API",
  "version": "v1",
  "canonicalName": "Reseller",
  "revision": "20210720",
  "documentationLink": "https://developers.google.com/google-apps/reseller/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/apps.order.readonly": {
          "description": "Manage users on your domain"
        },
        "https://www.googleapis.com/auth/apps.order": {
          "description": "Manage users on your domain"
        }
      }
    }
  },
  "baseUrl": "https://reseller.googleapis.com/",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "resources": {
    "resellernotify": {
      "methods": {
        "register": {
          "id": "reseller.resellernotify.register",
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/resellernotify/register",
          "path": "apps/reseller/v1/resellernotify/register",
          "description": "Registers a Reseller for receiving notifications.",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "getwatchdetails": {
          "id": "reseller.resellernotify.getwatchdetails",
          "flatPath": "apps/reseller/v1/resellernotify/getwatchdetails",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "path": "apps/reseller/v1/resellernotify/getwatchdetails",
          "description": "Returns all the details of the watch corresponding to the reseller.",
          "httpMethod": "GET"
        },
        "unregister": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Unregisters a Reseller for receiving notifications.",
          "httpMethod": "POST",
          "id": "reseller.resellernotify.unregister",
          "flatPath": "apps/reseller/v1/resellernotify/unregister",
          "path": "apps/reseller/v1/resellernotify/unregister"
        }
      }
    },
    "customers": {
      "methods": {
        "get": {
          "flatPath": "apps/reseller/v1/customers/{customerId}",
          "id": "reseller.customers.get",
          "httpMethod": "GET",
          "path": "apps/reseller/v1/customers/{customerId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "description": "Gets a customer account. Use this operation to see a customer account already in your reseller management, or to see the minimal account information for an existing customer that you do not manage. For more information about the API response for existing customers, see [retrieving a customer account](/admin-sdk/reseller/v1/how-tos/manage_customers#get_customer)."
        },
        "insert": {
          "description": "Orders a new customer's account. Before ordering a new customer account, establish whether the customer account already exists using the [`customers.get`](/admin-sdk/reseller/v1/reference/customers/get) If the customer account exists as a direct Google account or as a resold customer account from another reseller, use the `customerAuthToken\\` as described in [order a resold account for an existing customer](/admin-sdk/reseller/v1/how-tos/manage_customers#create_existin[...]",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "apps/reseller/v1/customers",
          "id": "reseller.customers.insert",
          "httpMethod": "POST",
          "path": "apps/reseller/v1/customers"
        },
        "update": {
          "path": "apps/reseller/v1/customers/{customerId}",
          "description": "Updates a customer account's settings. You cannot update `customerType` via the Reseller API, but a `\"team\"` customer can verify their domain and become `customerType = \"domain\"`. For more information, see [update a customer's settings](/admin-sdk/reseller/v1/how-tos/manage_customers#update_customer).",
          "id": "reseller.customers.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "apps/reseller/v1/customers/{customerId}"
        },
        "patch": {
          "description": "Updates a customer account's settings. This method supports patch semantics. You cannot update `customerType` via the Reseller API, but a `\"team\"` customer can verify their domain and become `customerType = \"domain\"`. For more information, see [Verify your domain to unlock Essentials features](https://support.google.com/a/answer/9122284).",
          "path": "apps/reseller/v1/customers/{customerId}",
          "id": "reseller.customers.patch",
          "flatPath": "apps/reseller/v1/customers/{customerId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        }
      }
    },
    "subscriptions": {
      "methods": {
        "changeSeats": {
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
          "description": "Updates a subscription's user license settings. For more information about updating an annual commitment plan or a flexible plan subscription’s licenses, see [Manage Subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#update_subscription_seat).",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "id": "reseller.subscriptions.changeSeats",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats"
        },
        "suspend": {
          "description": "Suspends an active subscription. You can use this method to suspend a paid subscription that is currently in the `ACTIVE` state. * For `FLEXIBLE` subscriptions, billing is paused. * For `ANNUAL_MONTHLY_PAY` or `ANNUAL_YEARLY_PAY` subscriptions: * Suspending the subscription does not change the renewal date that was originally committed to. * A suspended subscription does not renew. If you activate the subscription after the original renewal date, a new annual subscripti[...]",
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/suspend",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/suspend",
          "id": "reseller.subscriptions.suspend",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "changePlan": {
          "id": "reseller.subscriptions.changePlan",
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Updates a subscription plan. Use this method to update a plan for a 30-day trial or a flexible plan subscription to an annual commitment plan with monthly or yearly payments. How a plan is updated differs depending on the plan and the products. For more information, see the description in [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#update_subscription_plan).",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changePlan"
        },
        "get": {
          "description": "Gets a specific subscription. The `subscriptionId` can be found using the [Retrieve all reseller subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#get_all_subscriptions) method. For more information about retrieving a specific subscription, see the information descrived in [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#get_subscription).",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "id": "reseller.subscriptions.get",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions",
          "httpMethod": "POST",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions",
          "id": "reseller.subscriptions.insert",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Creates or transfer a subscription. Create a subscription for a customer's account that you ordered using the [Order a new customer account](/admin-sdk/reseller/v1/reference/customers/insert.html) method. For more information about creating a subscription for different payment plans, see [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#create_subscription).\\ If you did not order the customer's account using the customer insert method, use the [...]"
        },
        "changeRenewalSettings": {
          "id": "reseller.subscriptions.changeRenewalSettings",
          "description": "Updates a user license's renewal settings. This is applicable for accounts with annual commitment plans only. For more information, see the description in [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#update_renewal).",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings"
        },
        "startPaidService": {
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Immediately move a 30-day free trial subscription to a paid service subscription. This method is only applicable if a payment plan has already been set up for the 30-day trial subscription. For more information, see [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#paid_service).",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
          "id": "reseller.subscriptions.startPaidService"
        },
        "delete": {
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
          "id": "reseller.subscriptions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Cancels, suspends, or transfers a subscription to direct.",
          "httpMethod": "DELETE",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "path": "apps/reseller/v1/subscriptions",
          "description": "Lists of subscriptions managed by the reseller. The list can be all subscriptions, all of a customer's subscriptions, or all of a customer's transferable subscriptions. Optionally, this method can filter the response by a `customerNamePrefix`. For more information, see [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions).",
          "httpMethod": "GET",
          "id": "reseller.subscriptions.list",
          "flatPath": "apps/reseller/v1/subscriptions"
        },
        "activate": {
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/activate",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/activate",
          "httpMethod": "POST",
          "description": "Activates a subscription previously suspended by the reseller. If you did not suspend the customer subscription and it is suspended for any other reason, such as for abuse or a pending ToS acceptance, this call will not reactivate the customer subscription.",
          "id": "reseller.subscriptions.activate",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        }
      }
    }
  },
  "basePath": "",
  "protocol": "rest",
  "batchPath": "batch",
  "servicePath": "",
  "id": "reseller:v1",
  "ownerDomain": "google.com",
  "name": "reseller",
  "description": "Perform common functions that are available on the Channel Services console at scale, like placing orders and viewing customer information",
  "mtlsRootUrl": "https://reseller.mtls.googleapis.com/"
}
