{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        }
      }
    }
  },
  "basePath": "",
  "discoveryVersion": "v1",
  "version": "v1",
  "rootUrl": "https://script.googleapis.com/",
  "revision": "20220323",
  "fullyEncodeReservedExpansion": true,
  "resources": {
    "scripts": {
      "methods": {
        "run": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]",
          "path": "v1/scripts/{scriptId}:run",
          "id": "script.scripts.run",
          "httpMethod": "POST",
          "flatPath": "v1/scripts/{scriptId}:run"
        }
      }
    },
    "processes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/processes",
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "path": "v1/processes",
          "id": "script.processes.list"
        },
        "listScriptProcesses": {
          "path": "v1/processes:listScriptProcesses",
          "flatPath": "v1/processes:listScriptProcesses",
          "id": "script.processes.listScriptProcesses",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "description": "List information about a script's executed processes, such as process type and current status."
        }
      }
    },
    "projects": {
      "resources": {
        "versions": {
          "methods": {
            "get": {
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "id": "script.projects.versions.get",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "description": "Gets a version of a script project.",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "path": "v1/projects/{scriptId}/versions",
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "id": "script.projects.versions.create"
            },
            "list": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "description": "List the versions of a script project.",
              "path": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ]
            }
          }
        },
        "deployments": {
          "methods": {
            "create": {
              "path": "v1/projects/{scriptId}/deployments",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.create",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Creates a deployment of an Apps Script project.",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1/projects/{scriptId}/deployments",
              "path": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.list",
              "httpMethod": "GET",
              "description": "Lists the deployments of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ]
            },
            "delete": {
              "id": "script.projects.deployments.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Deletes a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "update": {
              "httpMethod": "PUT",
              "description": "Updates a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "id": "script.projects.deployments.update",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "get": {
              "id": "script.projects.deployments.get",
              "description": "Gets a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ]
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "script.projects.get",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "path": "v1/projects/{scriptId}",
          "flatPath": "v1/projects/{scriptId}",
          "httpMethod": "GET",
          "description": "Gets a script project's metadata."
        },
        "create": {
          "path": "v1/projects",
          "httpMethod": "POST",
          "id": "script.projects.create",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "flatPath": "v1/projects"
        },
        "updateContent": {
          "id": "script.projects.updateContent",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "flatPath": "v1/projects/{scriptId}/content",
          "httpMethod": "PUT",
          "path": "v1/projects/{scriptId}/content",
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project."
        },
        "getMetrics": {
          "flatPath": "v1/projects/{scriptId}/metrics",
          "httpMethod": "GET",
          "id": "script.projects.getMetrics",
          "description": "Get metrics data for scripts, such as number of executions and active users.",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "path": "v1/projects/{scriptId}/metrics"
        },
        "getContent": {
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets the content of the script project, including the code source and metadata for each script file.",
          "flatPath": "v1/projects/{scriptId}/content",
          "id": "script.projects.getContent",
          "path": "v1/projects/{scriptId}/content"
        }
      }
    }
  },
  "ownerName": "Google",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "batchPath": "batch",
  "name": "script",
  "baseUrl": "https://script.googleapis.com/",
  "title": "Apps Script API",
  "canonicalName": "Script",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "ownerDomain": "google.com",
  "id": "script:v1",
  "description": "Manages and executes Google Apps Script projects. "
}
