{
  "baseUrl": "https://script.googleapis.com/",
  "servicePath": "",
  "version": "v1",
  "ownerName": "Google",
  "name": "script",
  "basePath": "",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        }
      }
    }
  },
  "protocol": "rest",
  "resources": {
    "projects": {
      "methods": {
        "create": {
          "flatPath": "v1/projects",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "path": "v1/projects",
          "id": "script.projects.create",
          "httpMethod": "POST"
        },
        "getContent": {
          "description": "Gets the content of the script project, including the code source and metadata for each script file.",
          "path": "v1/projects/{scriptId}/content",
          "flatPath": "v1/projects/{scriptId}/content",
          "id": "script.projects.getContent",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ]
        },
        "getMetrics": {
          "path": "v1/projects/{scriptId}/metrics",
          "id": "script.projects.getMetrics",
          "httpMethod": "GET",
          "flatPath": "v1/projects/{scriptId}/metrics",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "description": "Get metrics data for scripts, such as number of executions and active users."
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "description": "Gets a script project's metadata.",
          "flatPath": "v1/projects/{scriptId}",
          "id": "script.projects.get",
          "path": "v1/projects/{scriptId}"
        },
        "updateContent": {
          "id": "script.projects.updateContent",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "path": "v1/projects/{scriptId}/content",
          "httpMethod": "PUT",
          "flatPath": "v1/projects/{scriptId}/content"
        }
      },
      "resources": {
        "deployments": {
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.delete",
              "description": "Deletes a deployment of an Apps Script project.",
              "httpMethod": "DELETE"
            },
            "update": {
              "httpMethod": "PUT",
              "id": "script.projects.deployments.update",
              "description": "Updates a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/projects/{scriptId}/deployments",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "description": "Lists the deployments of an Apps Script project.",
              "id": "script.projects.deployments.list",
              "flatPath": "v1/projects/{scriptId}/deployments"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Creates a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "httpMethod": "POST",
              "id": "script.projects.deployments.create"
            },
            "get": {
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "description": "Gets a deployment of an Apps Script project.",
              "id": "script.projects.deployments.get",
              "httpMethod": "GET",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            }
          }
        },
        "versions": {
          "methods": {
            "create": {
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "flatPath": "v1/projects/{scriptId}/versions",
              "path": "v1/projects/{scriptId}/versions",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "id": "script.projects.versions.create",
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "description": "Gets a version of a script project.",
              "id": "script.projects.versions.get"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/projects/{scriptId}/versions",
              "path": "v1/projects/{scriptId}/versions",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "description": "List the versions of a script project.",
              "id": "script.projects.versions.list"
            }
          }
        }
      }
    },
    "processes": {
      "methods": {
        "listScriptProcesses": {
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "path": "v1/processes:listScriptProcesses",
          "id": "script.processes.listScriptProcesses",
          "description": "List information about a script's executed processes, such as process type and current status.",
          "httpMethod": "GET",
          "flatPath": "v1/processes:listScriptProcesses"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "id": "script.processes.list",
          "httpMethod": "GET",
          "path": "v1/processes",
          "flatPath": "v1/processes"
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "httpMethod": "POST",
          "flatPath": "v1/scripts/{scriptId}:run",
          "id": "script.scripts.run",
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "path": "v1/scripts/{scriptId}:run"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "id": "script:v1",
  "description": "Manages and executes Google Apps Script projects. ",
  "canonicalName": "Script",
  "fullyEncodeReservedExpansion": true,
  "title": "Apps Script API",
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "revision": "20211230",
  "rootUrl": "https://script.googleapis.com/",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "kind": "discovery#restDescription",
  "batchPath": "batch"
}
