{
  "description": "Manages and executes Google Apps Script projects. ",
  "discoveryVersion": "v1",
  "rootUrl": "https://script.googleapis.com/",
  "version": "v1",
  "batchPath": "batch",
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "id": "script:v1",
  "title": "Apps Script API",
  "servicePath": "",
  "ownerName": "Google",
  "canonicalName": "Script",
  "kind": "discovery#restDescription",
  "revision": "20231203",
  "resources": {
    "projects": {
      "resources": {
        "deployments": {
          "methods": {
            "list": {
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "GET",
              "description": "Lists the deployments of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "id": "script.projects.deployments.list"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.delete",
              "description": "Deletes a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            },
            "update": {
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Updates a deployment of an Apps Script project.",
              "httpMethod": "PUT",
              "id": "script.projects.deployments.update",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "get": {
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.get",
              "httpMethod": "GET",
              "description": "Gets a deployment of an Apps Script project."
            },
            "create": {
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "POST",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.create",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Creates a deployment of an Apps Script project."
            }
          }
        },
        "versions": {
          "methods": {
            "list": {
              "id": "script.projects.versions.list",
              "description": "List the versions of a script project.",
              "path": "v1/projects/{scriptId}/versions",
              "flatPath": "v1/projects/{scriptId}/versions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ]
            },
            "get": {
              "description": "Gets a version of a script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "httpMethod": "GET",
              "id": "script.projects.versions.get",
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "httpMethod": "POST",
              "id": "script.projects.versions.create",
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "path": "v1/projects/{scriptId}/versions",
              "flatPath": "v1/projects/{scriptId}/versions"
            }
          }
        }
      },
      "methods": {
        "getMetrics": {
          "flatPath": "v1/projects/{scriptId}/metrics",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "description": "Get metrics data for scripts, such as number of executions and active users.",
          "path": "v1/projects/{scriptId}/metrics",
          "id": "script.projects.getMetrics",
          "httpMethod": "GET"
        },
        "updateContent": {
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "httpMethod": "PUT",
          "path": "v1/projects/{scriptId}/content",
          "id": "script.projects.updateContent",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "flatPath": "v1/projects/{scriptId}/content"
        },
        "getContent": {
          "httpMethod": "GET",
          "path": "v1/projects/{scriptId}/content",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "id": "script.projects.getContent",
          "flatPath": "v1/projects/{scriptId}/content",
          "description": "Gets the content of the script project, including the code source and metadata for each script file."
        },
        "get": {
          "path": "v1/projects/{scriptId}",
          "id": "script.projects.get",
          "flatPath": "v1/projects/{scriptId}",
          "description": "Gets a script project's metadata.",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "httpMethod": "GET"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1/projects",
          "flatPath": "v1/projects",
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "id": "script.projects.create",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "flatPath": "v1/scripts/{scriptId}:run",
          "path": "v1/scripts/{scriptId}:run",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "id": "script.scripts.run",
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]"
        }
      }
    },
    "processes": {
      "methods": {
        "list": {
          "id": "script.processes.list",
          "httpMethod": "GET",
          "flatPath": "v1/processes",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "path": "v1/processes"
        },
        "listScriptProcesses": {
          "httpMethod": "GET",
          "id": "script.processes.listScriptProcesses",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "description": "List information about a script's executed processes, such as process type and current status.",
          "flatPath": "v1/processes:listScriptProcesses",
          "path": "v1/processes:listScriptProcesses"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "protocol": "rest",
  "name": "script",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "baseUrl": "https://script.googleapis.com/",
  "ownerDomain": "google.com"
}
