{
  "canonicalName": "Search Console",
  "documentationLink": "https://developers.google.com/webmaster-tools/search-console-api/",
  "servicePath": "",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "title": "Google Search Console API",
  "batchPath": "batch",
  "name": "searchconsole",
  "id": "searchconsole:v1",
  "ownerName": "Google",
  "version": "v1",
  "version_module": true,
  "basePath": "",
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        }
      }
    }
  },
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "resources": {
    "sites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "webmasters.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "description": " Retrieves information about specific site."
        },
        "list": {
          "path": "webmasters/v3/sites",
          "flatPath": "webmasters/v3/sites",
          "id": "webmasters.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "httpMethod": "GET",
          "description": " Lists the user's Search Console sites."
        },
        "delete": {
          "description": " Removes a site from the set of the user's Search Console sites.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "httpMethod": "DELETE",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "path": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.delete"
        },
        "add": {
          "id": "webmasters.sites.add",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "path": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "PUT",
          "description": " Adds a site to the set of the user's sites in Search Console."
        }
      }
    },
    "searchanalytics": {
      "methods": {
        "query": {
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "httpMethod": "POST",
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.searchanalytics.query"
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "httpMethod": "POST",
              "description": "Runs Mobile-Friendly Test for a given URL."
            }
          }
        }
      }
    },
    "sitemaps": {
      "methods": {
        "list": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "id": "webmasters.sitemaps.list",
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "description": "Deletes a sitemap from this site.",
          "id": "webmasters.sitemaps.delete",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ]
        },
        "get": {
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "id": "webmasters.sitemaps.get",
          "description": "Retrieves information about a specific sitemap.",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "httpMethod": "GET"
        },
        "submit": {
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "PUT",
          "id": "webmasters.sitemaps.submit",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": "Submits a sitemap for a site.",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "revision": "20210903",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "kind": "discovery#restDescription"
}
