{
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "title": "Google Search Console API",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "kind": "discovery#restDescription",
  "revision": "20230920",
  "protocol": "rest",
  "servicePath": "",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        }
      }
    }
  },
  "resources": {
    "sites": {
      "methods": {
        "add": {
          "httpMethod": "PUT",
          "id": "webmasters.sites.add",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "path": "webmasters/v3/sites/{siteUrl}",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "description": " Adds a site to the set of the user's sites in Search Console."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "description": " Retrieves information about specific site.",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "path": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.get",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "webmasters/v3/sites",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.sites.list",
          "description": " Lists the user's Search Console sites.",
          "path": "webmasters/v3/sites",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": " Removes a site from the set of the user's Search Console sites.",
          "id": "webmasters.sites.delete",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "DELETE"
        }
      }
    },
    "sitemaps": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "httpMethod": "DELETE",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "id": "webmasters.sitemaps.delete",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "submit": {
          "description": "Submits a sitemap for a site.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "id": "webmasters.sitemaps.submit",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "PUT"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "id": "webmasters.sitemaps.get",
          "httpMethod": "GET",
          "description": "Retrieves information about a specific sitemap.",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "list": {
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "id": "webmasters.sitemaps.list",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "httpMethod": "GET"
        }
      }
    },
    "searchanalytics": {
      "methods": {
        "query": {
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "id": "webmasters.searchanalytics.query",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "httpMethod": "POST"
        }
      }
    },
    "urlInspection": {
      "resources": {
        "index": {
          "methods": {
            "inspect": {
              "id": "searchconsole.urlInspection.index.inspect",
              "flatPath": "v1/urlInspection/index:inspect",
              "httpMethod": "POST",
              "path": "v1/urlInspection/index:inspect",
              "description": "Index inspection.",
              "scopes": [
                "https://www.googleapis.com/auth/webmasters",
                "https://www.googleapis.com/auth/webmasters.readonly"
              ]
            }
          }
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run",
              "httpMethod": "POST",
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run"
            }
          }
        }
      }
    }
  },
  "name": "searchconsole",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/webmaster-tools/search-console-api/",
  "basePath": "",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "id": "searchconsole:v1",
  "version": "v1",
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "canonicalName": "Search Console"
}
