{
  "basePath": "",
  "servicePath": "",
  "title": "Google Search Console API",
  "name": "searchconsole",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "version": "v1",
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "canonicalName": "Search Console",
  "version_module": true,
  "protocol": "rest",
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "ownerName": "Google",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "id": "searchconsole:v1",
  "kind": "discovery#restDescription",
  "resources": {
    "sites": {
      "methods": {
        "get": {
          "id": "webmasters.sites.get",
          "description": " Retrieves information about specific site.",
          "path": "webmasters/v3/sites/{siteUrl}",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ]
        },
        "add": {
          "id": "webmasters.sites.add",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "httpMethod": "PUT",
          "path": "webmasters/v3/sites/{siteUrl}",
          "description": " Adds a site to the set of the user's sites in Search Console."
        },
        "delete": {
          "description": " Removes a site from the set of the user's Search Console sites.",
          "path": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.delete",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "httpMethod": "DELETE",
          "flatPath": "webmasters/v3/sites/{siteUrl}"
        },
        "list": {
          "id": "webmasters.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites",
          "path": "webmasters/v3/sites",
          "httpMethod": "GET",
          "description": " Lists the user's Search Console sites."
        }
      }
    },
    "searchanalytics": {
      "methods": {
        "query": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "id": "webmasters.searchanalytics.query",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "httpMethod": "POST"
        }
      }
    },
    "urlInspection": {
      "resources": {
        "index": {
          "methods": {
            "inspect": {
              "httpMethod": "POST",
              "description": "Index inspection.",
              "id": "searchconsole.urlInspection.index.inspect",
              "path": "v1/urlInspection/index:inspect",
              "scopes": [
                "https://www.googleapis.com/auth/webmasters",
                "https://www.googleapis.com/auth/webmasters.readonly"
              ],
              "flatPath": "v1/urlInspection/index:inspect"
            }
          }
        }
      }
    },
    "sitemaps": {
      "methods": {
        "delete": {
          "id": "webmasters.sitemaps.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "list": {
          "id": "webmasters.sitemaps.list",
          "httpMethod": "GET",
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps"
        },
        "submit": {
          "id": "webmasters.sitemaps.submit",
          "description": "Submits a sitemap for a site.",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "httpMethod": "PUT"
        },
        "get": {
          "id": "webmasters.sitemaps.get",
          "description": "Retrieves information about a specific sitemap.",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run",
              "httpMethod": "POST",
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run"
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/webmaster-tools/search-console-api/",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "batchPath": "batch",
  "revision": "20220128"
}
