{
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "canonicalName": "Search Console",
  "basePath": "",
  "revision": "20220107",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        }
      }
    }
  },
  "version_module": true,
  "ownerName": "Google",
  "protocol": "rest",
  "name": "searchconsole",
  "discoveryVersion": "v1",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "id": "searchconsole:v1",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "title": "Google Search Console API",
  "servicePath": "",
  "resources": {
    "sites": {
      "methods": {
        "get": {
          "path": "webmasters/v3/sites/{siteUrl}",
          "description": " Retrieves information about specific site.",
          "id": "webmasters.sites.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}"
        },
        "delete": {
          "id": "webmasters.sites.delete",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "path": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "DELETE",
          "description": " Removes a site from the set of the user's Search Console sites."
        },
        "add": {
          "id": "webmasters.sites.add",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": " Adds a site to the set of the user's sites in Search Console.",
          "path": "webmasters/v3/sites/{siteUrl}"
        },
        "list": {
          "description": " Lists the user's Search Console sites.",
          "flatPath": "webmasters/v3/sites",
          "httpMethod": "GET",
          "path": "webmasters/v3/sites",
          "id": "webmasters.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ]
        }
      }
    },
    "searchanalytics": {
      "methods": {
        "query": {
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "id": "webmasters.searchanalytics.query",
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "httpMethod": "POST",
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query"
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run",
              "httpMethod": "POST",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run"
            }
          }
        }
      }
    },
    "sitemaps": {
      "methods": {
        "list": {
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "id": "webmasters.sitemaps.list",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "httpMethod": "GET"
        },
        "submit": {
          "httpMethod": "PUT",
          "id": "webmasters.sitemaps.submit",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "description": "Submits a sitemap for a site."
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "id": "webmasters.sitemaps.delete",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ]
        },
        "get": {
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "GET",
          "id": "webmasters.sitemaps.get",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "description": "Retrieves information about a specific sitemap."
        }
      }
    }
  },
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "documentationLink": "https://developers.google.com/webmaster-tools/search-console-api/"
}
