{
  "discoveryVersion": "v1",
  "servicePath": "",
  "description": "Reads and writes Google Sheets.",
  "revision": "20230620",
  "ownerName": "Google",
  "title": "Google Sheets API",
  "documentationLink": "https://developers.google.com/sheets/",
  "batchPath": "batch",
  "protocol": "rest",
  "basePath": "",
  "version": "v4",
  "version_module": true,
  "ownerDomain": "google.com",
  "resources": {
    "spreadsheets": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "v4/spreadsheets/{spreadsheetId}",
          "id": "sheets.spreadsheets.get",
          "path": "v4/spreadsheets/{spreadsheetId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. By default, data within grids is not returned. You can include grid data in one of 2 ways: * Specify a [field mask](https://developers.google.com/sheets/api/guides/field-masks) listing your desired fields using the `fields` URL parameter in HTTP * Set the includeGridData URL parameter to true. If a field mask is set, the `includeGridData` parameter is ignored For large spreadsheets, as [...]"
        },
        "getByDataFilter": {
          "id": "sheets.spreadsheets.getByDataFilter",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "httpMethod": "POST",
          "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. This method differs from GetSpreadsheet in that it allows selecting which subsets of spreadsheet data to return by specifying a dataFilters parameter. Multiple DataFilters can be specified. Specifying one or more data filters returns the portions of the spreadsheet that intersect ranges matched by any of the filters. By default, data within grids is not returned. You can include grid da[...]",
          "path": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
          "flatPath": "v4/spreadsheets/{spreadsheetId}:getByDataFilter"
        },
        "batchUpdate": {
          "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
          "id": "sheets.spreadsheets.batchUpdate",
          "flatPath": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
          "httpMethod": "POST",
          "description": "Applies one or more updates to the spreadsheet. Each request is validated before being applied. If any request is not valid then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. The replies will mirror the requests. For example, if you applied 4 updates and the 3rd one had a reply, then the response will have 2 empty replies, the actual reply, and another empty reply, in that or[...]",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "flatPath": "v4/spreadsheets",
          "id": "sheets.spreadsheets.create",
          "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "path": "v4/spreadsheets"
        }
      },
      "resources": {
        "values": {
          "methods": {
            "append": {
              "description": "Appends values to a spreadsheet. The input range is used to search for existing data and find a \"table\" within that range. Values will be appended to the next row of the table, starting with the first column of the table. See the [guide](/sheets/api/guides/values#appending_values) and [sample code](/sheets/api/samples/writing#append_values) for specific details of how tables are detected and data is appended. The caller must specify the spreadsheet ID, range, and [...]",
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.values.append"
            },
            "batchGetByDataFilter": {
              "httpMethod": "POST",
              "description": "Returns one or more ranges of values that match the specified data filters. The caller must specify the spreadsheet ID and one or more DataFilters. Ranges that match any of the data filters in the request will be returned.",
              "id": "sheets.spreadsheets.values.batchGetByDataFilter",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            },
            "batchClearByDataFilter": {
              "description": "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more DataFilters. Ranges matching any of the specified data filters will be cleared. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
              "id": "sheets.spreadsheets.values.batchClearByDataFilter",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter"
            },
            "batchClear": {
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "description": "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges. Only values are cleared -- all other properties of the cell (such as formatting and data validation) are kept.",
              "id": "sheets.spreadsheets.values.batchClear"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "httpMethod": "PUT",
              "id": "sheets.spreadsheets.values.update",
              "description": "Sets values in a range of a spreadsheet. The caller must specify the spreadsheet ID, range, and a valueInputOption.",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}"
            },
            "get": {
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "httpMethod": "GET",
              "description": "Returns a range of values from a spreadsheet. The caller must specify the spreadsheet ID and a range.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "id": "sheets.spreadsheets.values.get"
            },
            "batchGet": {
              "id": "sheets.spreadsheets.values.batchGet",
              "description": "Returns one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet"
            },
            "clear": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "description": "Clears values from a spreadsheet. The caller must specify the spreadsheet ID and range. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
              "id": "sheets.spreadsheets.values.clear"
            },
            "batchUpdateByDataFilter": {
              "description": "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more DataFilterValueRanges.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.values.batchUpdateByDataFilter",
              "httpMethod": "POST",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter"
            },
            "batchUpdate": {
              "id": "sheets.spreadsheets.values.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
              "description": "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more ValueRanges.",
              "httpMethod": "POST",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate"
            }
          }
        },
        "sheets": {
          "methods": {
            "copyTo": {
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "description": "Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet.",
              "id": "sheets.spreadsheets.sheets.copyTo",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            }
          }
        },
        "developerMetadata": {
          "methods": {
            "search": {
              "description": "Returns all developer metadata matching the specified DataFilter. If the provided DataFilter represents a DeveloperMetadataLookup object, this will return all DeveloperMetadata entries selected by it. If the DataFilter represents a location in a spreadsheet, this will return all developer metadata associated with locations intersecting that region.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.developerMetadata.search",
              "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search"
            },
            "get": {
              "id": "sheets.spreadsheets.developerMetadata.get",
              "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
              "description": "Returns the developer metadata with the specified ID. The caller must specify the spreadsheet ID and the developer metadata's unique metadataId.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "See all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "canonicalName": "Sheets",
  "mtlsRootUrl": "https://sheets.mtls.googleapis.com/",
  "rootUrl": "https://sheets.googleapis.com/",
  "baseUrl": "https://sheets.googleapis.com/",
  "id": "sheets:v4",
  "name": "sheets",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription"
}
