{
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://slides.googleapis.com/",
  "kind": "discovery#restDescription",
  "baseUrl": "https://slides.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "See all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/presentations.readonly": {
          "description": "See all your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/presentations": {
          "description": "See, edit, create, and delete all your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "protocol": "rest",
  "ownerDomain": "google.com",
  "canonicalName": "Slides",
  "name": "slides",
  "version_module": true,
  "description": "Reads and writes Google Slides presentations.",
  "documentationLink": "https://developers.google.com/slides/",
  "ownerName": "Google",
  "revision": "20230209",
  "mtlsRootUrl": "https://slides.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "id": "slides:v1",
  "title": "Google Slides API",
  "basePath": "",
  "resources": {
    "presentations": {
      "methods": {
        "get": {
          "id": "slides.presentations.get",
          "httpMethod": "GET",
          "description": "Gets the latest version of the specified presentation.",
          "flatPath": "v1/presentations/{presentationsId}",
          "path": "v1/presentations/{+presentationId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/presentations.readonly"
          ]
        },
        "create": {
          "id": "slides.presentations.create",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/presentations"
          ],
          "flatPath": "v1/presentations",
          "path": "v1/presentations",
          "description": "Creates a blank presentation using the title given in the request. If a `presentationId` is provided, it is used as the ID of the new presentation. Otherwise, a new ID is generated. Other fields in the request, including any provided content, are ignored. Returns the created presentation.",
          "httpMethod": "POST"
        },
        "batchUpdate": {
          "id": "slides.presentations.batchUpdate",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "description": "Applies one or more updates to the presentation. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and o[...]",
          "flatPath": "v1/presentations/{presentationId}:batchUpdate",
          "httpMethod": "POST",
          "path": "v1/presentations/{presentationId}:batchUpdate"
        }
      },
      "resources": {
        "pages": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ],
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "description": "Gets the latest version of the specified page in the presentation.",
              "id": "slides.presentations.pages.get",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "httpMethod": "GET"
            },
            "getThumbnail": {
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "description": "Generates a thumbnail of the latest version of the specified page in the presentation and returns a URL to the thumbnail image. This request counts as an [expensive read request](/slides/limits) for quota purposes.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ],
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "id": "slides.presentations.pages.getThumbnail",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "version": "v1",
  "batchPath": "batch"
}
