{
  "mtlsRootUrl": "https://sourcerepo.mtls.googleapis.com/",
  "name": "sourcerepo",
  "discoveryVersion": "v1",
  "servicePath": "",
  "title": "Cloud Source Repositories API",
  "kind": "discovery#restDescription",
  "revision": "20220429",
  "documentationLink": "https://cloud.google.com/source-repositories/docs/apis",
  "version": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/source.read_only": {
          "description": "View the contents of your source code repositories"
        },
        "https://www.googleapis.com/auth/source.full_control": {
          "description": "Manage your source code repositories"
        },
        "https://www.googleapis.com/auth/source.read_write": {
          "description": "Manage the contents of your source code repositories"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "ownerName": "Google",
  "basePath": "",
  "protocol": "rest",
  "version_module": true,
  "id": "sourcerepo:v1",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "resources": {
    "projects": {
      "methods": {
        "getConfig": {
          "flatPath": "v1/projects/{projectsId}/config",
          "description": "Returns the Cloud Source Repositories configuration of the project.",
          "httpMethod": "GET",
          "id": "sourcerepo.projects.getConfig",
          "path": "v1/{+name}/config",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "updateConfig": {
          "flatPath": "v1/projects/{projectsId}/config",
          "httpMethod": "PATCH",
          "description": "Updates the Cloud Source Repositories configuration of the project.",
          "id": "sourcerepo.projects.updateConfig",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}/config"
        }
      },
      "resources": {
        "repos": {
          "methods": {
            "create": {
              "flatPath": "v1/projects/{projectsId}/repos",
              "path": "v1/{+parent}/repos",
              "httpMethod": "POST",
              "description": "Creates a repo in the given project with the given name. If the named repository already exists, `CreateRepo` returns `ALREADY_EXISTS`.",
              "id": "sourcerepo.projects.repos.create",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control"
              ]
            },
            "delete": {
              "description": "Deletes a repo.",
              "id": "sourcerepo.projects.repos.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control"
              ]
            },
            "getIamPolicy": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ],
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:getIamPolicy",
              "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
              "path": "v1/{+resource}:getIamPolicy",
              "httpMethod": "GET",
              "id": "sourcerepo.projects.repos.getIamPolicy"
            },
            "list": {
              "flatPath": "v1/projects/{projectsId}/repos",
              "id": "sourcerepo.projects.repos.list",
              "description": "Returns all repos belonging to a project. The sizes of the repos are not set by ListRepos. To get the size of a repo, use GetRepo.",
              "httpMethod": "GET",
              "path": "v1/{+name}/repos",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "testIamPermissions": {
              "path": "v1/{+resource}:testIamPermissions",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ],
              "id": "sourcerepo.projects.repos.testIamPermissions",
              "httpMethod": "POST",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:testIamPermissions",
              "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error."
            },
            "patch": {
              "path": "v1/{+name}",
              "id": "sourcerepo.projects.repos.patch",
              "httpMethod": "PATCH",
              "description": "Updates information about a repo.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}"
            },
            "get": {
              "path": "v1/{+name}",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}",
              "id": "sourcerepo.projects.repos.get",
              "description": "Returns information about a repo.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control",
                "https://www.googleapis.com/auth/source.read_only",
                "https://www.googleapis.com/auth/source.read_write"
              ]
            },
            "setIamPolicy": {
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:setIamPolicy",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/source.full_control"
              ],
              "description": "Sets the access control policy on the specified resource. Replaces any existing policy.",
              "id": "sourcerepo.projects.repos.setIamPolicy",
              "path": "v1/{+resource}:setIamPolicy",
              "httpMethod": "POST"
            },
            "sync": {
              "httpMethod": "POST",
              "description": "Synchronize a connected repo. The response contains SyncRepoMetadata in the metadata field.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "sourcerepo.projects.repos.sync",
              "path": "v1/{+name}:sync",
              "flatPath": "v1/projects/{projectsId}/repos/{reposId}:sync"
            }
          }
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "baseUrl": "https://sourcerepo.googleapis.com/",
  "rootUrl": "https://sourcerepo.googleapis.com/",
  "canonicalName": "Cloud Source Repositories",
  "description": "Accesses source code repositories hosted by Google."
}
