{
  "protocol": "rest",
  "name": "vault",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "canonicalName": "Vault",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "servicePath": "",
  "version_module": true,
  "resources": {
    "matters": {
      "methods": {
        "close": {
          "flatPath": "v1/matters/{matterId}:close",
          "httpMethod": "POST",
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.close"
        },
        "create": {
          "flatPath": "v1/matters",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "httpMethod": "POST",
          "id": "vault.matters.create",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters"
        },
        "reopen": {
          "path": "v1/matters/{matterId}:reopen",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:reopen",
          "id": "vault.matters.reopen",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "httpMethod": "POST"
        },
        "addPermissions": {
          "path": "v1/matters/{matterId}:addPermissions",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.addPermissions",
          "description": "Adds an account as a matter collaborator."
        },
        "count": {
          "id": "vault.matters.count",
          "description": "Counts the accounts processed by the specified query.",
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:count",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:count"
        },
        "undelete": {
          "flatPath": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "description": "Undeletes the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:undelete",
          "id": "vault.matters.undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "removePermissions": {
          "path": "v1/matters/{matterId}:removePermissions",
          "httpMethod": "POST",
          "description": "Removes an account as a matter collaborator.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions"
        },
        "update": {
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}",
          "id": "vault.matters.update",
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "path": "v1/matters",
          "description": "Lists matters the requestor has access to.",
          "id": "vault.matters.list",
          "flatPath": "v1/matters",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "delete": {
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "id": "vault.matters.delete",
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "get": {
          "description": "Gets the specified matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}",
          "id": "vault.matters.get"
        }
      },
      "resources": {
        "holds": {
          "resources": {
            "accounts": {
              "methods": {
                "delete": {
                  "description": "Removes an account from a hold.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "id": "vault.matters.holds.accounts.delete"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "id": "vault.matters.holds.accounts.list",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold."
                },
                "create": {
                  "id": "vault.matters.holds.accounts.create",
                  "httpMethod": "POST",
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts"
                }
              }
            }
          },
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "flatPath": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.create",
              "description": "Creates a hold in the specified matter."
            },
            "delete": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.delete",
              "httpMethod": "DELETE"
            },
            "addHeldAccounts": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "id": "vault.matters.holds.addHeldAccounts"
            },
            "removeHeldAccounts": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "httpMethod": "POST",
              "id": "vault.matters.holds.removeHeldAccounts",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts"
            },
            "update": {
              "httpMethod": "PUT",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.update",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored."
            },
            "list": {
              "id": "vault.matters.holds.list",
              "flatPath": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "description": "Lists the holds in a matter."
            },
            "get": {
              "description": "Gets the specified hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.get"
            }
          }
        },
        "savedQueries": {
          "methods": {
            "get": {
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "description": "Retrieves the specified saved query.",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "id": "vault.matters.savedQueries.get",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a saved query.",
              "path": "v1/matters/{matterId}/savedQueries",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.savedQueries.create"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "id": "vault.matters.savedQueries.list",
              "path": "v1/matters/{matterId}/savedQueries",
              "description": "Lists the saved queries in a matter."
            },
            "delete": {
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Deletes the specified saved query.",
              "id": "vault.matters.savedQueries.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            }
          }
        },
        "exports": {
          "methods": {
            "list": {
              "id": "vault.matters.exports.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/exports",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/exports",
              "description": "Lists details about the exports in the specified matter."
            },
            "delete": {
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "id": "vault.matters.exports.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Deletes an export.",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}"
            },
            "get": {
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Gets an export.",
              "id": "vault.matters.exports.get",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/exports/{exportId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "flatPath": "v1/matters/{matterId}/exports",
              "id": "vault.matters.exports.create",
              "path": "v1/matters/{matterId}/exports",
              "description": "Creates an export."
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "cancel": {
          "path": "v1/{+name}:cancel",
          "id": "vault.operations.cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST"
        },
        "list": {
          "id": "vault.operations.list",
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operatio[...]",
          "httpMethod": "GET",
          "path": "v1/{+name}"
        },
        "delete": {
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "vault.operations.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "DELETE"
        },
        "get": {
          "id": "vault.operations.get",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/operations/{operationsId}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        }
      }
    }
  },
  "rootUrl": "https://vault.googleapis.com/",
  "basePath": "",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/vault",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "baseUrl": "https://vault.googleapis.com/",
  "title": "Google Vault API",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "id": "vault:v1",
  "revision": "20220316"
}
