{
  "title": "YouTube Analytics API",
  "protocol": "rest",
  "canonicalName": "YouTube Analytics",
  "version": "v2",
  "name": "youtubeAnalytics",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "ownerName": "Google",
  "description": "Retrieves your YouTube Analytics data.",
  "kind": "discovery#restDescription",
  "id": "youtubeAnalytics:v2",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "servicePath": "",
  "ownerDomain": "google.com",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        }
      }
    }
  },
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "version_module": true,
  "revision": "20230704",
  "resources": {
    "reports": {
      "methods": {
        "query": {
          "description": "Retrieve your YouTube Analytics reports.",
          "path": "v2/reports",
          "flatPath": "v2/reports",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.reports.query"
        }
      }
    },
    "groups": {
      "methods": {
        "insert": {
          "path": "v2/groups",
          "httpMethod": "POST",
          "description": "Creates a group.",
          "flatPath": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.insert"
        },
        "delete": {
          "id": "youtubeAnalytics.groups.delete",
          "httpMethod": "DELETE",
          "path": "v2/groups",
          "description": "Deletes a group.",
          "flatPath": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.update",
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "description": "Modifies a group. For example, you could change a group's title.",
          "httpMethod": "PUT"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.list",
          "path": "v2/groups",
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "httpMethod": "GET",
          "flatPath": "v2/groups"
        }
      }
    },
    "groupItems": {
      "methods": {
        "delete": {
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.delete",
          "httpMethod": "DELETE",
          "description": "Removes an item from a group.",
          "flatPath": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "insert": {
          "description": "Creates a group item.",
          "httpMethod": "POST",
          "path": "v2/groupItems",
          "flatPath": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "id": "youtubeAnalytics.groupItems.list",
          "flatPath": "v2/groupItems",
          "description": "Returns a collection of group items that match the API request parameters.",
          "path": "v2/groupItems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "batchPath": "batch"
}
