{
  "discoveryVersion": "v1",
  "canonicalName": "YouTube",
  "description": "The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.",
  "basePath": "",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/youtube/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/youtubepartner-channel-audit": {
          "description": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
        },
        "https://www.googleapis.com/auth/youtube.force-ssl": {
          "description": "See, edit, and permanently delete your YouTube videos, ratings, comments and captions"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube.upload": {
          "description": "Manage your YouTube videos"
        },
        "https://www.googleapis.com/auth/youtube.channel-memberships.creator": {
          "description": "See a list of your current active channel members, their current level, and when they became a member"
        }
      }
    }
  },
  "baseUrl": "https://www.googleapis.com/",
  "protocol": "rest",
  "batchPath": "batch/youtube",
  "revision": "20200909",
  "ownerDomain": "google.com",
  "id": "youtube:v3",
  "name": "youtube",
  "version": "v3",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "resources": {
    "commentThreads": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "youtube.commentThreads.insert",
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/commentThreads",
          "flatPath": "youtube/v3/commentThreads",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "flatPath": "youtube/v3/commentThreads",
          "path": "youtube/v3/commentThreads",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.commentThreads.list"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "youtube/v3/commentThreads",
          "id": "youtube.commentThreads.update",
          "description": "Updates an existing resource.",
          "path": "youtube/v3/commentThreads",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        }
      }
    },
    "channels": {
      "methods": {
        "update": {
          "description": "Updates an existing resource.",
          "httpMethod": "PUT",
          "path": "youtube/v3/channels",
          "flatPath": "youtube/v3/channels",
          "id": "youtube.channels.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "youtube.channels.list",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/channels",
          "flatPath": "youtube/v3/channels",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/youtubepartner-channel-audit"
          ]
        }
      }
    },
    "playlists": {
      "methods": {
        "insert": {
          "id": "youtube.playlists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/playlists",
          "httpMethod": "POST",
          "path": "youtube/v3/playlists",
          "description": "Inserts a new resource into this collection."
        },
        "list": {
          "path": "youtube/v3/playlists",
          "id": "youtube.playlists.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Retrieves a list of resources, possibly filtered.",
          "flatPath": "youtube/v3/playlists"
        },
        "delete": {
          "flatPath": "youtube/v3/playlists",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Deletes a resource.",
          "path": "youtube/v3/playlists",
          "httpMethod": "DELETE",
          "id": "youtube.playlists.delete"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing resource.",
          "flatPath": "youtube/v3/playlists",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlists.update",
          "path": "youtube/v3/playlists"
        }
      }
    },
    "i18nRegions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "youtube/v3/i18nRegions",
          "path": "youtube/v3/i18nRegions",
          "id": "youtube.i18nRegions.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Retrieves a list of resources, possibly filtered."
        }
      }
    },
    "abuseReports": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "youtube/v3/abuseReports",
          "id": "youtube.abuseReports.insert",
          "description": "Inserts a new resource into this collection.",
          "flatPath": "youtube/v3/abuseReports",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        }
      }
    },
    "infocards": {
      "methods": {
        "update": {
          "flatPath": "youtube/v3/infocards",
          "httpMethod": "POST",
          "description": "Updates infocards for a given video. Note: * If the card id is not provided, a new card will be created. * If the card id is provided, that card will be updated. * Existing cards will be discarded if they're not included in the request.",
          "id": "youtube.infocards.update",
          "path": "youtube/v3/infocards",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "youtube/v3/infocards",
          "path": "youtube/v3/infocards",
          "id": "youtube.infocards.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Retrieves all infocards for a given video."
        }
      }
    },
    "watermarks": {
      "methods": {
        "unset": {
          "flatPath": "youtube/v3/watermarks/unset",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.watermarks.unset",
          "description": "Allows removal of channel watermark.",
          "httpMethod": "POST",
          "path": "youtube/v3/watermarks/unset"
        },
        "set": {
          "id": "youtube.watermarks.set",
          "flatPath": "youtube/v3/watermarks/set",
          "path": "youtube/v3/watermarks/set",
          "httpMethod": "POST",
          "description": "Allows upload of watermark image and setting it for a channel.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "supportsMediaUpload": true
        }
      }
    },
    "subscriptions": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "id": "youtube.subscriptions.delete",
          "description": "Deletes a resource.",
          "flatPath": "youtube/v3/subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "path": "youtube/v3/subscriptions"
        },
        "insert": {
          "path": "youtube/v3/subscriptions",
          "httpMethod": "POST",
          "id": "youtube.subscriptions.insert",
          "flatPath": "youtube/v3/subscriptions",
          "description": "Inserts a new resource into this collection.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.subscriptions.list",
          "description": "Retrieves a list of resources, possibly filtered.",
          "flatPath": "youtube/v3/subscriptions",
          "path": "youtube/v3/subscriptions",
          "httpMethod": "GET"
        }
      }
    },
    "endscreens": {
      "methods": {
        "get": {
          "id": "youtube.endscreens.get",
          "path": "youtube/v3/endscreen",
          "description": "Retrieves endscreen for a given video.",
          "httpMethod": "GET",
          "flatPath": "youtube/v3/endscreen",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "update": {
          "id": "youtube.endscreens.update",
          "description": "Updates endscreen for a given video. Note: * If the element id is not provided, a new element will be created. * If the element id is provided, that element will be updated. * Existing elements will be discarded if they're not included in the request.",
          "path": "youtube/v3/endscreen",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/endscreen",
          "httpMethod": "POST"
        }
      }
    },
    "videoCategories": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/videoCategories",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videoCategories.list",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/videoCategories",
          "httpMethod": "GET"
        }
      }
    },
    "sponsors": {
      "methods": {
        "list": {
          "description": "Retrieves a list of sponsors that match the request criteria for a channel.",
          "flatPath": "youtube/v3/sponsors",
          "httpMethod": "GET",
          "path": "youtube/v3/sponsors",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "id": "youtube.sponsors.list"
        }
      }
    },
    "guideCategories": {
      "methods": {
        "list": {
          "path": "youtube/v3/guideCategories",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET",
          "flatPath": "youtube/v3/guideCategories",
          "description": "Retrieves a list of guide categories.",
          "id": "youtube.guideCategories.list"
        }
      }
    },
    "superChatEvents": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/superChatEvents",
          "description": "Retrieves a list of resources, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "id": "youtube.superChatEvents.list",
          "path": "youtube/v3/superChatEvents",
          "httpMethod": "GET"
        }
      }
    },
    "captions": {
      "methods": {
        "download": {
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET",
          "path": "youtube/v3/captions/{id}",
          "id": "youtube.captions.download",
          "supportsMediaDownload": true,
          "flatPath": "youtube/v3/captions/{id}",
          "description": "Downloads a caption track."
        },
        "update": {
          "flatPath": "youtube/v3/captions",
          "httpMethod": "PUT",
          "id": "youtube.captions.update",
          "description": "Updates an existing resource.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "path": "youtube/v3/captions",
          "supportsMediaUpload": true
        },
        "insert": {
          "id": "youtube.captions.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "flatPath": "youtube/v3/captions",
          "path": "youtube/v3/captions"
        },
        "list": {
          "flatPath": "youtube/v3/captions",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/captions",
          "id": "youtube.captions.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "youtube/v3/captions",
          "description": "Deletes a resource.",
          "httpMethod": "DELETE",
          "path": "youtube/v3/captions",
          "id": "youtube.captions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "tests": {
      "methods": {
        "insert": {
          "id": "youtube.tests.insert",
          "flatPath": "youtube/v3/tests",
          "path": "youtube/v3/tests",
          "description": "POST method.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "httpMethod": "POST"
        }
      }
    },
    "liveChatMessages": {
      "methods": {
        "delete": {
          "path": "youtube/v3/liveChat/messages",
          "httpMethod": "DELETE",
          "id": "youtube.liveChatMessages.delete",
          "description": "Deletes a chat message.",
          "flatPath": "youtube/v3/liveChat/messages",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "list": {
          "flatPath": "youtube/v3/liveChat/messages",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET",
          "id": "youtube.liveChatMessages.list",
          "path": "youtube/v3/liveChat/messages"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatMessages.insert",
          "path": "youtube/v3/liveChat/messages",
          "description": "Inserts a new resource into this collection.",
          "flatPath": "youtube/v3/liveChat/messages"
        }
      }
    },
    "comments": {
      "methods": {
        "list": {
          "id": "youtube.comments.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/comments",
          "flatPath": "youtube/v3/comments"
        },
        "delete": {
          "id": "youtube.comments.delete",
          "description": "Deletes a resource.",
          "flatPath": "youtube/v3/comments",
          "path": "youtube/v3/comments",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "DELETE"
        },
        "markAsSpam": {
          "path": "youtube/v3/comments/markAsSpam",
          "flatPath": "youtube/v3/comments/markAsSpam",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "POST",
          "description": "Expresses the caller's opinion that one or more comments should be flagged as spam.",
          "id": "youtube.comments.markAsSpam"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "youtube.comments.update",
          "path": "youtube/v3/comments",
          "flatPath": "youtube/v3/comments",
          "description": "Updates an existing resource.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "insert": {
          "flatPath": "youtube/v3/comments",
          "path": "youtube/v3/comments",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST",
          "id": "youtube.comments.insert"
        },
        "setModerationStatus": {
          "path": "youtube/v3/comments/setModerationStatus",
          "id": "youtube.comments.setModerationStatus",
          "flatPath": "youtube/v3/comments/setModerationStatus",
          "description": "Sets the moderation status of one or more comments.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        }
      }
    },
    "liveChatModerators": {
      "methods": {
        "insert": {
          "path": "youtube/v3/liveChat/moderators",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "flatPath": "youtube/v3/liveChat/moderators",
          "description": "Inserts a new resource into this collection.",
          "id": "youtube.liveChatModerators.insert"
        },
        "delete": {
          "id": "youtube.liveChatModerators.delete",
          "path": "youtube/v3/liveChat/moderators",
          "flatPath": "youtube/v3/liveChat/moderators",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Deletes a chat moderator.",
          "httpMethod": "DELETE"
        },
        "list": {
          "id": "youtube.liveChatModerators.list",
          "flatPath": "youtube/v3/liveChat/moderators",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "path": "youtube/v3/liveChat/moderators"
        }
      }
    },
    "thirdPartyLinks": {
      "methods": {
        "insert": {
          "id": "youtube.thirdPartyLinks.insert",
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST",
          "flatPath": "youtube/v3/thirdPartyLinks",
          "path": "youtube/v3/thirdPartyLinks"
        },
        "update": {
          "id": "youtube.thirdPartyLinks.update",
          "description": "Updates an existing resource.",
          "httpMethod": "PUT",
          "path": "youtube/v3/thirdPartyLinks",
          "flatPath": "youtube/v3/thirdPartyLinks"
        },
        "list": {
          "path": "youtube/v3/thirdPartyLinks",
          "flatPath": "youtube/v3/thirdPartyLinks",
          "id": "youtube.thirdPartyLinks.list",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "youtube/v3/thirdPartyLinks",
          "flatPath": "youtube/v3/thirdPartyLinks",
          "description": "Deletes a resource.",
          "httpMethod": "DELETE",
          "id": "youtube.thirdPartyLinks.delete"
        }
      }
    },
    "channelSections": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "youtube.channelSections.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "path": "youtube/v3/channelSections",
          "flatPath": "youtube/v3/channelSections",
          "description": "Inserts a new resource into this collection."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/channelSections",
          "id": "youtube.channelSections.list",
          "path": "youtube/v3/channelSections",
          "description": "Retrieves a list of resources, possibly filtered."
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/channelSections",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.channelSections.delete",
          "path": "youtube/v3/channelSections",
          "description": "Deletes a resource."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing resource.",
          "id": "youtube.channelSections.update",
          "path": "youtube/v3/channelSections",
          "flatPath": "youtube/v3/channelSections",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "search": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/search",
          "id": "youtube.search.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET",
          "path": "youtube/v3/search",
          "description": "Retrieves a list of search resources"
        }
      }
    },
    "videoAbuseReportReasons": {
      "methods": {
        "list": {
          "path": "youtube/v3/videoAbuseReportReasons",
          "flatPath": "youtube/v3/videoAbuseReportReasons",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "id": "youtube.videoAbuseReportReasons.list"
        }
      }
    },
    "channelBanners": {
      "methods": {
        "insert": {
          "flatPath": "youtube/v3/channelBanners/insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload"
          ],
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/channelBanners/insert",
          "id": "youtube.channelBanners.insert",
          "supportsMediaUpload": true,
          "httpMethod": "POST"
        }
      }
    },
    "members": {
      "methods": {
        "list": {
          "description": "Retrieves a list of members that match the request criteria for a channel.",
          "path": "youtube/v3/members",
          "flatPath": "youtube/v3/members",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.channel-memberships.creator",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET",
          "id": "youtube.members.list"
        }
      }
    },
    "i18nLanguages": {
      "methods": {
        "list": {
          "path": "youtube/v3/i18nLanguages",
          "description": "Retrieves a list of resources, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET",
          "flatPath": "youtube/v3/i18nLanguages",
          "id": "youtube.i18nLanguages.list"
        }
      }
    },
    "thumbnails": {
      "methods": {
        "set": {
          "id": "youtube.thumbnails.set",
          "supportsMediaUpload": true,
          "description": "As this is not an insert in a strict sense (it supports uploading/setting of a thumbnail for multiple videos, which doesn't result in creation of a single resource), I use a custom verb here.",
          "path": "youtube/v3/thumbnails/set",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "POST",
          "flatPath": "youtube/v3/thumbnails/set"
        }
      }
    },
    "liveBroadcasts": {
      "methods": {
        "control": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "path": "youtube/v3/liveBroadcasts/control",
          "flatPath": "youtube/v3/liveBroadcasts/control",
          "description": "Slate and recording control of the live broadcast. Support actions: slate on/off, recording start/stop/pause/resume. Design doc: goto/yt-api-liveBroadcast-control",
          "id": "youtube.liveBroadcasts.control"
        },
        "insert": {
          "flatPath": "youtube/v3/liveBroadcasts",
          "id": "youtube.liveBroadcasts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new stream for the authenticated user.",
          "path": "youtube/v3/liveBroadcasts"
        },
        "bind": {
          "flatPath": "youtube/v3/liveBroadcasts/bind",
          "httpMethod": "POST",
          "description": "Bind a broadcast to a stream.",
          "path": "youtube/v3/liveBroadcasts/bind",
          "id": "youtube.liveBroadcasts.bind",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "transition": {
          "flatPath": "youtube/v3/liveBroadcasts/transition",
          "description": "Transition a broadcast to a given status.",
          "httpMethod": "POST",
          "path": "youtube/v3/liveBroadcasts/transition",
          "id": "youtube.liveBroadcasts.transition",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "delete": {
          "id": "youtube.liveBroadcasts.delete",
          "flatPath": "youtube/v3/liveBroadcasts",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "DELETE",
          "description": "Delete a given broadcast.",
          "path": "youtube/v3/liveBroadcasts"
        },
        "update": {
          "id": "youtube.liveBroadcasts.update",
          "path": "youtube/v3/liveBroadcasts",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Updates an existing broadcast for the authenticated user.",
          "flatPath": "youtube/v3/liveBroadcasts",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "youtube/v3/liveBroadcasts",
          "path": "youtube/v3/liveBroadcasts",
          "description": "Retrieve the list of broadcasts associated with the given channel.",
          "httpMethod": "GET",
          "id": "youtube.liveBroadcasts.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ]
        }
      }
    },
    "liveChatBans": {
      "methods": {
        "delete": {
          "description": "Deletes a chat ban.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/liveChat/bans",
          "path": "youtube/v3/liveChat/bans",
          "id": "youtube.liveChatBans.delete"
        },
        "insert": {
          "id": "youtube.liveChatBans.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Inserts a new resource into this collection.",
          "flatPath": "youtube/v3/liveChat/bans",
          "httpMethod": "POST",
          "path": "youtube/v3/liveChat/bans"
        }
      }
    },
    "playlistItems": {
      "methods": {
        "update": {
          "id": "youtube.playlistItems.update",
          "description": "Updates an existing resource.",
          "path": "youtube/v3/playlistItems",
          "flatPath": "youtube/v3/playlistItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "PUT"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/playlistItems",
          "path": "youtube/v3/playlistItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlistItems.delete",
          "description": "Deletes a resource."
        },
        "list": {
          "id": "youtube.playlistItems.list",
          "flatPath": "youtube/v3/playlistItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "path": "youtube/v3/playlistItems",
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered."
        },
        "insert": {
          "path": "youtube/v3/playlistItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new resource into this collection.",
          "flatPath": "youtube/v3/playlistItems",
          "id": "youtube.playlistItems.insert"
        }
      }
    },
    "videos": {
      "methods": {
        "getRating": {
          "path": "youtube/v3/videos/getRating",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "GET",
          "id": "youtube.videos.getRating",
          "description": "Retrieves the ratings that the authorized user gave to a list of specified videos.",
          "flatPath": "youtube/v3/videos/getRating"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/videos",
          "id": "youtube.videos.update",
          "description": "Updates an existing resource.",
          "httpMethod": "PUT",
          "path": "youtube/v3/videos"
        },
        "insert": {
          "supportsMediaUpload": true,
          "id": "youtube.videos.insert",
          "path": "youtube/v3/videos",
          "httpMethod": "POST",
          "description": "Inserts a new resource into this collection.",
          "flatPath": "youtube/v3/videos",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "rate": {
          "description": "Adds a like or dislike rating to a video or removes a rating from a video.",
          "id": "youtube.videos.rate",
          "flatPath": "youtube/v3/videos/rate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "path": "youtube/v3/videos/rate"
        },
        "reportAbuse": {
          "description": "Report abuse for a video.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "path": "youtube/v3/videos/reportAbuse",
          "flatPath": "youtube/v3/videos/reportAbuse",
          "id": "youtube.videos.reportAbuse"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "youtube/v3/videos",
          "id": "youtube.videos.list",
          "path": "youtube/v3/videos",
          "description": "Retrieves a list of resources, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a resource.",
          "flatPath": "youtube/v3/videos",
          "path": "youtube/v3/videos",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.delete"
        }
      }
    },
    "activities": {
      "methods": {
        "list": {
          "path": "youtube/v3/activities",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "id": "youtube.activities.list",
          "flatPath": "youtube/v3/activities"
        }
      }
    },
    "membershipsLevels": {
      "methods": {
        "list": {
          "path": "youtube/v3/membershipsLevels",
          "flatPath": "youtube/v3/membershipsLevels",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.channel-memberships.creator",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Retrieves a list of all pricing levels offered by a creator to the fans.",
          "id": "youtube.membershipsLevels.list"
        }
      }
    },
    "liveStreams": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "flatPath": "youtube/v3/liveStreams",
          "description": "Updates an existing stream for the authenticated user.",
          "id": "youtube.liveStreams.update",
          "path": "youtube/v3/liveStreams"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new stream for the authenticated user.",
          "id": "youtube.liveStreams.insert",
          "path": "youtube/v3/liveStreams",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "flatPath": "youtube/v3/liveStreams"
        },
        "delete": {
          "id": "youtube.liveStreams.delete",
          "flatPath": "youtube/v3/liveStreams",
          "description": "Deletes an existing stream for the authenticated user.",
          "httpMethod": "DELETE",
          "path": "youtube/v3/liveStreams",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "list": {
          "id": "youtube.liveStreams.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "flatPath": "youtube/v3/liveStreams",
          "path": "youtube/v3/liveStreams",
          "httpMethod": "GET",
          "description": "Retrieve the list of streams associated with the given channel. --"
        }
      }
    }
  },
  "rootUrl": "https://www.googleapis.com/",
  "title": "YouTube Data API v3",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "ownerName": "Google"
}
