name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install deps
      run: |
        python -m pip install -r requirements.txt
    - name: Black
      run: |
        python -m black scripts/*.py tests/*.py --check
    - name: MyPy
      run: |
        python -m mypy scripts/*.py tests/*.py
    - name: Unit Tests
      run: |
        python -m unittest tests/*.py
